### ISSUE TITLE
Clearence for IFR option not available on default built-in ATC

### ISSUE THREAD

**Issue by DouglasDRF** [flybywiresim/a32nx#7257] opened 2022-05-30 03:51 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-05-27T23:35:34+00:00",
    "ref": "refs/heads/master",
    "sha": "3de4c9092a9daea2a8f36e55cdab74859566aa20",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:3de4c909"
}
```

### Describe the bug

After setup new flight in Main Menu, with no destination (to avoid fill the flgiht plan automatically in FMS), and insert the flight plan in FMS, the COMM menu does not have the option to ask for clearence to IFR.

![FBW A320](https://user-images.githubusercontent.com/17039306/170913477-3e460379-a1e2-45b2-8a10-e07baa5ee0f6.png)

I Googled it and in the Flight Simulator Forum (https://forums.flightsimulator.com/) I checked a thread that said I could be a incorrent fill of flight plan in FMS or that is required to fill in menu, that, but that doesn't seems true because on other aircrafts such TBM 930, Diamond DA62, doing the same procedure on menu of leaving the destination blank, after put some flight plan info on Garmin G1000 the option of require IFR Clreace is available. I also did the same procedure at default MSFS A320 and it works

![Default A320](https://user-images.githubusercontent.com/17039306/170913874-a039e7f5-1a9e-4715-9126-abefbaae314a.png)

### Expected behavior

After insert some flight plan data on FMS (departure and arrival airport at least) the default built-in ATC should give the option of ask IFR Clearance on clearence frequencies

### Steps to reproduce

1. Create new flight on main menu leaving the destination airport in blank
2. Insert at least departure and arrival airport in FMS
3. Open ATC panel and tune clearece frequencies

**Comment by tshomas** [comment] 2022-05-30 16:05
Please see: https://docs.flybywiresim.com/fbw-a32nx/feature-guides/cFMS/#special-notes

**Comment by 2hwk** [comment] 2022-05-30 18:18
Not a bug, closing. Enable Save Flight plan to MSFS option in the EFB.

**Closed by 2hwk** 2022-05-30 18:18 UTC
Labels: Bug

**Comment by DouglasDRF** [comment] 2022-05-30 23:42
Thanks @tshomas. Sorry if I have misssed it. Previous versions these steps were not necessary.
