### ISSUE TITLE
APU starter always saying"unavailable"

### ISSUE THREAD

**Issue by GivenPaladin809** [flybywiresim/a32nx#252] opened 2020-08-30 16:43 UTC
It's impossible to start the APU, because it always says that the starter is unavailable, even after some time has passed after pressing the APU Master. Also, even if after a while, it is pushable, the APU will start and be available, but the lower ECAM will show amber 
 "XX" EGT and amber "XX" N values.

**Comment by ukflyer** [comment] 2020-08-30 16:49
believe this is being worked on in https://github.com/wpine215/msfs-a320neo/issues/53 :)

**Comment by ThePilot916** [comment] 2020-08-30 17:03
Yup, It has been fixed already, just waiting on the merge.

**Comment by Curtis-VL** [comment] 2020-09-01 15:55
Once the merge has been made, please close this issue! 👍

**Comment by AdenFlorian** [comment] 2020-09-03 06:56
still seems to be an issue, working on a fix

**Comment by Inaxair** [comment] 2020-10-16 23:35
As I believe it has been merge, I'll close the ticket. Feel free to reopen the ticket if you have other query about this issue. Thanks!

**Comment by lukecologne** [comment] 2020-10-16 23:56
Reopened since this still appears to be an issue

**Comment by tareksabet** [comment] 2020-11-07 19:04
@lukecologne couldn't preproduce this issue will close it

**Closed** 2020-11-07 19:04 UTC
Labels: Bug, Can't Reproduce

**Comment by lukecologne** [comment] 2020-11-07 19:06
Yeah, I fixed it in #1476 but forgot to link it
