### ISSUE TITLE
Wrong indication of constraint on ND screen

### ISSUE THREAD

**Issue by luciopl** [flybywiresim/a32nx#4649] opened 2021-04-29 22:23 UTC
**Aircraft Version**
```json
{
  "built": "2021-04-24T09:45:22+00:00",
  "ref": "master",
  "sha": "2abd3631c5fe30bfe544def82719f1e29f44924b",
  "actor": "myselfaaryan",
  "event_name": "manual"
}
```

**Describe the bug**
There is a difference between PFD and ND display.  I changed the altitude constraint of a SID chart from +9500 to 11000 on FMS.  On PFD we can see the constraint correct but ND shows the original constraint.

**To Reproduce**

1. Start a flight and create all flight on FMS with SID chart
2. Change a altitude constraint of the SID chart to a new value.
3. While flying, observe the constraint indicated on ND when the constraint shows up on PFD.

**Expected behavior**

ND shows the new constraint added on FMS

**Actual behavior**

ND shows the previous constraint

**References**

![image](https://user-images.githubusercontent.com/83432045/116625318-d0f92000-a91f-11eb-8863-053615176479.png)

**Additional context**

I found this problem with the KUBEX 1A chart Trans. DEJAN departing from SBCF

Was this working before/when did the issue start occurring?
I don't remember seeing this before.  I was flying stable version before.

Is this a problem in the vanilla unmodded game?
No.  It is not possible to change constraints on original A320, at least I don't know how.

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment] 2021-04-30 08:30
Can you please confirm your issue is the same as reported in https://github.com/flybywiresim/a32nx/issues/1297?

**Comment by luciopl** [comment] 2021-04-30 10:44
Yes.  I didn't see that report and also, didn't realize that deactivating and activating constraint display would display correct value.  I did another test now and saw same behavior.

**Comment by MisterChocker** [comment] 2021-04-30 11:16
Duplicate of #1297

**Closed by MisterChocker** 2021-04-30 11:16 UTC
Labels: Bug, Waiting For Response
