### ISSUE TITLE
Autopilot starts oscillation when increasing sim rate

### ISSUE THREAD

**Issue by assafco1000** [flybywiresim/a32nx#1284] opened 2020-10-13 13:08 UTC
**Mod Version**
0.3.1

**Describe the bug**
When flying with autopilot at cruise altitude at high simulation rates (X8, X16) the plane rolls up and down

**To Reproduce**
1. Fly to cruise altitude with AP (300-380)
2. Increase simulation rate to X8
3. The plane will have diffuclties to maintain the altitude and will start rolling up and down

**Expected behavior**
Plane should maintain altitude

**Actual behavior**
The plane will has diffuclties to maintain the altitude and will start rolling up and down

**References**

**Additional context**

Was this working before/when did the issue start occurring?
No. It is not related straight to the flybywire mod changes. 

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

**Comment by Watsi01** [comment] 2020-10-13 13:11
4x sim rate is safe. Everything above not recommended right now. It's an Asobo thing (as you mentioned). I don't think FBW can do something here.

**Comment by Pleasure0102** [comment] 2020-10-13 13:12
i did not even know that we can change sim rate :D not that i would ever do it anyway.. i like realistic flight times

**Comment by fourdragons** [comment] 2020-10-13 13:16
> No. It is not related straight to the flybywire mod changes

Doesn’t matter. You aren’t me, so it’s okay. 👌

**Comment by assafco1000** [comment] 2020-10-13 13:17
> 4x sim rate is safe. Everything above not recommended right now. It's an Asobo thing (as you mentioned). I don't think FBW can do something here.

Right. But I did consult with one of the guys and he recommended issuing a bug here. FlyByWire people are my last hope for this. Maybe they can direct me to a place that can fix this. I tried with no luck so far

**Comment by Pleasure0102** [comment] 2020-10-13 13:21
> > 4x sim rate is safe. Everything above not recommended right now. It's an Asobo thing (as you mentioned). I don't think FBW can do something here.
> 
> Right. But I did consult with one of the guys and he recommended issuing a bug here. FlyByWire people are my last hope for this. Maybe they can direct me to a place that can fix this. I tried with no luck so far

leave this issue open, if someone can fix it, they might. Its open source, so people choose themselves mostly what they work on

**Comment by Watsi01** [comment] 2020-10-13 14:20
> 
>  
> i did not even know that we can change sim rate :D not that i would ever do it anyway.. i like realistic flight times
@Pleasure0102 If you "miscalculated" your flight time and have a date, it's pretty handy. This or cancel the flight (I don't even try to save the flight and restart, since this always went bullshit so far).

**Comment by fourdragons** [comment] 2020-10-13 14:24
> leave this issue open, if someone can fix it, they might. Its open source, so people choose themselves mostly what they work on

Literally my point. 🤦‍♂️

**Comment by Benjozork** [comment] 2020-10-13 17:29
@fourdragons please remain polite, nobody argued against your point here.

**Comment by fourdragons** [comment] 2020-10-13 17:30
YOU did. Specifically YOU.

**Comment by Benjozork** [comment] 2020-10-13 17:31
> YOU did. Specifically YOU.

I have not even commented in this issue...

If you keep on being rude because we denied a feature request that has NOTHING TO DO with our mod, we will block you from commenting here. Simple as that.

**Comment by fourdragons** [comment] 2020-10-13 17:31
Thanks! Prove my point for me. I appreciate it!

**Comment by R00tD00m** [comment] 2020-10-13 18:49
> > 4x sim rate is safe. Everything above not recommended right now. It's an Asobo thing (as you mentioned). I don't think FBW can do something here.
> 
> Right. But I did consult with one of the guys and he recommended issuing a bug here. FlyByWire people are my last hope for this. Maybe they can direct me to a place that can fix this. I tried with no luck so far

Maybe give the Microsoft flight simulator forums a try? They’ve got an extensive bug report thread there and can be quite helpful.

**Comment by Benjozork** [comment] 2020-10-13 18:50
Hello everyone,

We are planning to introduce our own autopilot implementation so this will not be fixed until we are able to do so, as the Asobo autopilot is not configurable or tweakable from the plane config.

**Comment by assafco1000** [comment] 2020-10-14 04:33
Didn't want to make such a fight about this issue people... Let's all relax. It is a very young simulator. Thanks @Benjozork you confirm what I thought during my wandering in the msfs folders. The the AP is not configurable. Hope you or Asobo may fix this. Thanks anyway!

**Comment by Benjozork** [comment] 2020-10-14 04:54
@assafco1000 don't worry, you didn't do anything. the person we were responding to was upset because of another issue and decided it was appropriate to spam other issues because of it.

**Comment by triangle4mouse** [comment] 2020-10-14 06:05
> decided it was appropriate to spam other issues because of it.

you are dong exctly what you acused them of doing and now have all your cronies kissing butt and falling all over them selfs to show you there loylty peopel see what you are doing you have done some work and think you are king and nobody else is and others follow you but those who actualy take time to read see what you are dont bother blockng or ban or what ever cause i want nothing to do wit you keep your little app or what ev

**Comment by Watsi01** [comment] 2020-10-14 06:49
...trolls coming...

**Comment by Benjozork** [comment] 2020-10-14 14:28
Just little entitled kids, don't pay attention to them and ping a staff member on Discord.

**Comment by MisterChocker** [comment] 2020-12-31 06:17
This is a bug in most sims. @Benjozork Do we want this issue to maintain open for tracking?

**Comment by Taz5150** [comment] 2021-04-24 10:43
Commercial aircraft developers for FSX/ P3D also state and require NOT to accelerate time. This issue should probably be closed.

**Comment by MisterChocker** [comment] 2021-04-24 22:00
Duplicate of #4183

**Closed by MisterChocker** 2021-04-24 22:00 UTC
Labels: Autopilot, Bug, Won't Fix, Working as Intended
