### ISSUE TITLE
[BUG] New thrust levels make proper descent impossible

### ISSUE THREAD

**Issue by flytester** [flybywiresim/a32nx#1638] opened 2020-10-30 18:45 UTC
**Mod Version**

Latest master

**Describe the bug**

Thrust settings are much higher than before. The aircraft can taxi on idle thrust, which is good&realistic. Big problem is the incapability to descent at a normal rate. I suspect the thrust-setting on idle is too high. The aircraft can't descent more than around 1000 feet per minute during approach probably cause this would lead to a airspeed higher than managed or selected. The low descent rate is far from realistic, the A320 should at least be capable to descent 2500 ft per minute in this phase of flight. 
Since performing a realistic approach is not possible anymore, the mod has become of little use, wich I regret A LOT. Hope you guys fix this!!

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Seems to be a problem with the latest master.

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub):

**Comment by flytester** [comment] 2020-10-30 18:47
Addition: even full speedbrakes or flaps don't solve this issue.

**Comment by vlbreda** [comment] 2020-10-30 19:05
Ran into exactly the same problem. Shame the stable version isn't working since the update, didn't have the problem with descending.

**Comment by TheoBearman** [comment] 2020-10-30 19:08
Can also report this.

**Comment by Benjozork** [comment] 2020-10-30 19:09
We are continuously working on an improved flight and engine model on the master branch - therefore we do not guarantee realistic conditions at all times on the master.

A patched stable version is coming today that will work for MSFS 1.10.7.

**Comment by vlbreda** [comment] 2020-10-30 19:17
@Benjozork: I think it is in no way meant as critisiscm, by no one. Just reporting the issues we encounter.

**Comment by Benjozork** [comment] 2020-10-30 19:19
Of course, just explaining what our philosophy is when it comes to master. Stable patch is coming today.

Your criticism is very welcome and appreciated - we need it to improve.

**Comment by korundar** [comment] 2020-10-30 22:22
I find it harder to slow in approach than in previous versions. It seems more like a 777.

**Comment by donstim** [comment] 2020-10-31 05:20
Can you provide more specifics, like what altitude, configuration, weight, and autopilot/autothrust modes?

All modern airliners are pretty slippery. As you get lower and slower, you have less capability to go down and slow down.

**Comment by vlbreda** [comment] 2020-10-31 09:27
I can provide the following: plane's weight is 130.000 LB, speed is around 210 kn, ap/at engaged, approach phase, all in managed mode. Problem occurs with flaps retracted and extended, there's little difference. For example: flying the ILS 25 approach into Luton (EGGW) the STAR requires you to descent from 5000 ft to 2000 ft over a distance from 7 nautical miles. This is not possible, even with full flaps, gear down and speed brakes in use. 

My best guess: the plane is tuned for realistic taxi performance (at idle thrust). This same idle thrust makes that the plane can't descent rapid enough without exceeding the managed or selected speed.

As you mentioned, slower means less capability to go down. But the performance as it is now in the dev-version of the mod is a far cry from reality.

**Comment by vlbreda** [comment] 2020-10-31 13:13
This short youtube-video shows exactly what the problem is. Plane is at 8000 ft, approach phase is activated, plane slows down (very slowly). After that, a (magaged) descent to 5000 feet is flown (at 1 min 09 in the video). Descent-rate is barely 1000 feet/minute. In real life, this is about 2500 feet/minute (to quote a real A320-pilot: 'The A320 can descent like a flying piano).

Hope this makes the problem clear to you and you can fix it!

[https://www.youtube.com/watch?v=5q2d1JFO7wU&feature=youtu.be](url)

**Comment by lve0200** [comment] 2020-10-31 15:46
Just to confirm, that the issue is still there even in 1.10.7.0 & master as of 31/10. APP 8000->1700 at -1700ft/min, 210 Kts, with IDLE, FULL Speedbrakes, Flaps 1 and Gear DOWN!

**Comment by vlbreda** [comment] 2020-10-31 20:21
Found out a workaround for the problem: 
-download and install the latest dev-version
-replace **engines.cfg** file with file from your latest working mod-version (the file to be replaced is located in ..Community/A32NX/SimObjects/Airplanes/Asobo_A320_NEO
-Descent rate is no around 1700 ft/minute during approach, 200 ft/minute with gear down/flaps 3
-If you haven't got the old engines.cfg file anymore, send me your email-adress and I'll send it to you.

**Comment by krieke58** [comment] 2020-10-31 21:22
@vlbreda : please send. 👍

**Comment by lve0200** [comment] 2020-10-31 22:01
OK, here now my 5 cts worth. I did a file compare of the 2 questionable engine.cfg files. The latest from Asobo and FBW. The only relevant difference is the "n1_and_mach_on_thrust_table" line. To make things visible, I transferred everything into an Excel sheet. A picture tell more than 1000 words or numbers. The Excel is attached. For those w/out Excel, here the picture. I think they talk for itself. 

![image](https://user-images.githubusercontent.com/47894777/97790538-a412bd00-1bc9-11eb-8465-e0510210cd70.png)


[xx.zip](https://github.com/flybywiresim/a32nx/files/5469851/xx.zip)

**Comment by MultiMediaWIll** [comment] 2020-10-31 22:06
I too can confirm this is a problem. I have been struggling to slow down the plane for the last week. In fact a few days ago I was completely unable to descend and follow VATSIM ATC's instructions since the plane would not slow down even with speed brakes (this was a few days ago so not sure if the speed brakes have since been fixed). I have the latest dev version.

**Comment by vlbreda** [comment] 2020-10-31 22:22
This is the engine.cfg file that fixes the problem.
[engines.zip](https://github.com/flybywiresim/a32nx/files/5469919/engines.zip)

**Comment by Benjozork** [comment] 2020-10-31 23:13
I want to remind everyone that the stable 0.4.1 version functions with the latest MSFS patch and does not contain the experimental flight model changes.

**Comment by vlbreda** [comment] 2020-10-31 23:19
@Benjozork : the stable version that is installed using the downloader was not properly working the night of sat oct 31th. Maybe it is working by now.

**Comment by Benjozork** [comment] 2020-10-31 23:31
Try to install it manually.

**Comment by MisterChocker** [comment] 2020-11-01 00:28
> This short youtube-video shows exactly what the problem is. Plane is at 8000 ft, approach phase is activated, plane slows down (very slowly). After that, a (magaged) descent to 5000 feet is flown (at 1 min 09 in the video). Descent-rate is barely 1000 feet/minute. In real life, this is about 2500 feet/minute (to quote a real A320-pilot: 'The A320 can descent like a flying piano).
> 
> Hope this makes the problem clear to you and you can fix it!
> 
> []https://www.youtube.com/watch?v=5q2d1JFO7wU&feature=youtu.be

can watch the video, it's on private

**Comment by lve0200** [comment] 2020-11-01 00:29
My little bit of nightly. 1st at all, if I'm violating any kind of rules here, I apologise and promise not to do it again. The admins here may feel free to delete my file!
Looking at the 2 engine.cfg graphs from above, I could not refrain from creating my own personal 3rd one. Hence I took the original Asobo file and modified the lower end 20%-30% to something in the middle of FBW and Asobo. The new graph is attached. Above 30% everything is original Asobo. I am personally quite happy with the mod, altough in the absence of any reliable performance tables, everything remains personal gusto.
The plane does not start rolling on idle, which I find reasonable, but it takes only a little thrust to overcome the initial inertia and then it keeps rolling (very slightly decelerating) on idle.
Decent looks better to me, w/ -1600ft/min @ 210Kt w/out any brakes.
Those who want to give it a shot, the file is attached, as well as the excel and the graphs.
![image](https://user-images.githubusercontent.com/47894777/97792662-53a75980-1be1-11eb-97cf-28225b3f9c51.png)
[Desktop.zip](https://github.com/flybywiresim/a32nx/files/5470020/Desktop.zip)

**Comment by MisterChocker** [comment] 2020-11-01 00:43
Yes the current engine model in the master/dev version is not realistic, it solves a couple of issues with the engines and flight model to improve the flying performance of the aircraft.
Work on a proper long term solution is being done right now, which will be as realistic as possible. #1580
Note: We are also developing a new engine model from scratch which will deliver real life performances in every situation. Because this is quite a task, it takes a lot of time.

@lve0200
I find that quite offensive to publish a solution and not talking to us on discord to give proper feedback, just my personal opinion.

**Comment by MisterChocker** [comment] 2020-11-01 00:49
Also following the chart below and properly configuring the aircraft during approach will help massively.
![image](https://user-images.githubusercontent.com/1857322/97792849-4770cb80-1be4-11eb-9abd-893abac4a55f.png)

**Comment by MisterChocker** [comment] 2020-11-01 00:53
@vlbreda Descent performance varies from situation from situation. There is no fixed value.
Peak descent performance is at 29314ft with 36868kg at  M0.780   CAS300.0  TAS 461.0 IAS 250

**Comment by lve0200** [comment] 2020-11-01 00:57
> I find that quite offensive to publish a solution and not talking to us on discord

Sorry, I don't know what/where "discord" is, and how it works. I also apologised for eventually violating rules, if any. Just wanted to help...

**Comment by MisterChocker** [comment] 2020-11-01 01:01
To respond to the descent rate problem, I am able to apply a small formula to calculate my required distance for descend to a given altitude.

It is altitude divided by 1000 times 3
altitude / 1000 * 3

Additional to make a more precise calculation for e.g. TOD

speed component: for every 10kts higher then 200kts add 1 nm.
wind component: for every 10knt headwind component sub 1nm. For tailwind do the opposite.

**Comment by MisterChocker** [comment] 2020-11-01 01:05
@lve0200
> Sorry, I don't know what/where "discord" is, and how it works. I also apologised for eventually violating rules, if any. Just wanted to help...

Discord is a free communication platform with lots of features.
Click the link to join our discord server https://discord.gg/5WaFfv2N

**Comment by donstim** [comment] 2020-11-01 05:46
> I can provide the following: plane's weight is 130.000 LB, speed is around 210 kn, ap/at engaged, approach phase, all in managed mode. Problem occurs with flaps retracted and extended, there's little difference. For example: flying the ILS 25 approach into Luton (EGGW) the STAR requires you to descent from 5000 ft to 2000 ft over a distance from 7 nautical miles. This is not possible, even with full flaps, gear down and speed brakes in use.
> 
> My best guess: the plane is tuned for realistic taxi performance (at idle thrust). This same tuning of idle thrust makes that the plane can't descent rapid enough without exceeding the managed or selected speed. Idle thrust still gives far too much thrust.
> 
> As you mentioned, slower means less capability to go down. But the performance as it is now in the dev-version of the mod is a far cry from reality.

Tried flying that approach using an EHAM-EGGW flight using the current developer version. Being U.S.-based I'm not that familiar with flying in Europe. I could not find the approach procedure you are referring to that requires you to descend from 5000 ft to 2000 ft over a distance of 7 nm. I found and used the procedures shown below, which have you descend from 8000 feet at Casey (or Abbot) to 6000 feet, thence to the ILS capture altitude of 3000 feet just past Brookway. There was at least 10-12 nm to do that, and it was no problem in managed speed transitioning to CONF 1. Used a bit of speedbrake to reduce the speed from green do to S, but probably didn't need to. At S speed with CONF 1, I had 700-1000 fpm ROD or 2000 fpm with speedbrakes extended. Once at 3000 feet, it is a normal 3 degree glideslope, which is not an issue with this mod.

For your example of needing to descent from 5000 to 2000 feet in 7 nm, at a VAPP of 129 with full flaps, you would need a 1000 fpm descent rate. I'll have to go fly it again to check that, but I don't think I would have any problem maintaining that as there seemed to be plenty of downpath ability on the normal 3-degree glide at 7-800 fpm that I flew (i.e., thrust was not at idle as it should not be).

Maybe you could point out where I went wrong?

**Comment by vlbreda** [comment] 2020-11-01 11:20
@MisterChocker 

About the youtube-stream: it's public now, sorry for the inconvenience. [](https://www.youtube.com/watch?v=5q2d1JFO7wU)

I searched the interent and asked a few A320-pilots what to take for a 'normal' descent-rate on the A320. Got one answer so far: 

_''3000 fpm is considered normal at one company that I worked for. Obviously, we can deviate within reason. I have routinely descended at more than 3000fpm in non-emergency situations. Aggressive stepdowns on a STAR, controller requests expedited descent for traffic, slam dunk from 10,000ft+ (cleared for visual, hand off to tower, immediately cleared to land), etc.''_

About hte STAR: keep in mind that these are published to be used by all aircraft types, not just the A320. ATC knows you're in an A320 and will tell you to descent at a rate suitable for your aircraft, both in MSFS as in real life.

Found a star (EHAM 18R via Artip transition) in MSFS to show you fast descents are required. Of course MSFS might differ here from the real world, but fast descents are required in densely populated areas to reduce noise. In this example you have to descent from 8600 to 2000 ft in just a few NM's!

![image](https://user-images.githubusercontent.com/72414568/97801333-4ff4f080-1c3c-11eb-8d0c-812a1d218ea0.png)

**Comment by vlbreda** [comment] 2020-11-01 11:22
@Benjozork : Hi Benjamin, you suggest to do a manual install. I have to confess I am a total nitwit in the world of Github, Discord, etc. Where do I find the files to do a manual install? On the FlyByWire website? Thought by using the A32 Downloader I would be safe all the time :)

**Comment by MisterChocker** [comment] 2020-11-01 11:28
@vlbreda
> ![image](https://user-images.githubusercontent.com/72414568/97801333-4ff4f080-1c3c-11eb-8d0c-812a1d218ea0.png)

First, I wouldn't trust the ingame flight planner. I am not sure if the distance is scaled properly but thats looking not right to me.
About the noise thing, using speed brakes actually increases the noise, using IDLE thrust and continuous descends are proper economical ways of descending.
Also take a look at comment the above.

**Comment by joniatus** [comment] 2020-11-01 13:32
@vlbreda that's not a star. You put in a direct arrival to ils. The in game planner is not going to descend you properly. Pull up an actual arrival chart (not in game) and fly it. There are no issues managing decent and approach. It's not realistic to deploy speed brakes and descend 5000fpm while slowing from .80 to vapp in 30 seconds

**Comment by vlbreda** [comment] 2020-11-01 13:59
@Jonatius: it's a rather extreme exemple, you're right. This topic however is not about the realism of the MSFS flightplanner, but the capabilities of the A320. Plane should be able to reach 2500 ft/minute descent in all phases of flight, without use of speedbrakes.

**Comment by MisterChocker** [comment] 2020-11-01 14:10
@vlbreda 
> it's a rather extreme exemple, you're right. This topic however is not about the realism of the MSFS flightplanner, but the capabilities of the A320. Plane should be able to reach 2500 ft/minute descent in all phases of flight, without use of speedbrakes.

where do you get those number from?

**Comment by joniatus** [comment] 2020-11-01 14:20
@vlbreda it's literally what you're basing your claims on. Yeah provide a reference that you can descend at 2500fpm in landing config without gaining speed. All I'm saying is go fly an actual arrival and approach procedure and you'll find you can meet restrictions just fine.

**Comment by joniatus** [comment] 2020-11-01 14:30
I'm pretty sure the people having trouble with their descents are using in game planner restrictions which are often incorrect and are not actually looking at and following charts

**Comment by MisterChocker** [comment] 2020-11-01 14:30
> I'm pretty sure the people having trouble with their descents are using in game planner restrictions which are often incorrect and are not actually looking at and following charts

they probably adopted to the space shuttle physics of asobos 320 LMAO

**Comment by vlbreda** [comment] 2020-11-01 15:03
@joniatus, misterchoker : there is a difference between the figures on the chart and what a plane can actual fly. As I mentioned earlier, these charts are fit for ALL types of aircraft, not just the A320. So charts are not a good reference to judge whether the A320 mod meets reality.

Some sources I can recommend to you: youtube channels Captain Joe and 320 sim pilot. These channels are run by real A320 pilots. Watching this footage is very informative!

**Comment by MisterChocker** [comment] 2020-11-01 15:05
@vlbreda Well I was hoping for proper documents of the A320-251 not YouTube channels.

**Comment by lve0200** [comment] 2020-11-01 15:07
Here's probavbly a reliable reference:
[https://contentzone.eurocontrol.int/aircraftperformance/details.aspx?ICAO=A320](url)
![msedge_9OJk5QwNhG](https://user-images.githubusercontent.com/47894777/97806497-25b32b00-1c5c-11eb-982f-e55fa0a74d1d.png)
and here, how to fly possible APPs:
https://www.researchgate.net/figure/Low-Drag-Low-Power-Flight-Procedures-4_fig1_225006763
![image](https://user-images.githubusercontent.com/47894777/97806544-55623300-1c5c-11eb-83d4-0a54348afe7d.png)

**Comment by lve0200** [comment] 2020-11-01 15:14
Adding comments to the above charts, I would say that the current N1 settings do not allow for the indicated RODs w/out applying massiv brakes (gear, flaps, speed brakes) and that there should be probably a "reserve" of 500ft/min.

**Comment by ischmal** [comment] 2020-11-01 15:16
Perhaps we're not all on the same page here...

I also found this to be a huge problem after the mod was updated to support the latest game patch. Having said that, the latest dev release also seems to have resolved this for now, so hopefully we can just disregard this altogether at this point.

**Comment by Benjozork** [comment] 2020-11-01 15:20
@ischmal, the 0.4.1 release contains no flight model changes.

**Comment by MultiMediaWIll** [comment] 2020-11-01 15:21
> @vlbreda that's not a star. You put in a direct arrival to ils. The in game planner is not going to descend you properly. Pull up an actual arrival chart (not in game) and fly it. There are no issues managing decent and approach. It's not realistic to deploy speed brakes and descend 5000fpm while slowing from .80 to vapp in 30 seconds

The plane does have issues managing decent and approach. I was flying an actual STAR into Portland, Maine the other day on a VATSIM event. I was completely unable to follow both the speed restrictions and altitude assignments when getting vectored to the ILS due to the fact that the plane would not slow down no matter what. I ended up being way too high to intercept the ILS and had to manually override the AP and blow 240kts on short final in order to make the landing. Something is definitely off.

**Comment by ischmal** [comment] 2020-11-01 15:26
@Benjozork you know, I couldn't find any commits to explain this, but I figured I was just missing something. Perhaps this is actually far more bizarre than I thought... is anyone able to confirm that they're still experiencing this then? Maybe Asobo snuck it in with their CTD fix somehow. Very strange.

**Comment by vlbreda** [comment] 2020-11-01 15:30
@lve200: That's a splendid chart you provide! Thanks! No it's all clear. 3500 ft/min to FL100 and 1500 ft during approach are not met by the dev-version of the mod this topic is about. Hope Misterchoker and Joniatus studie your chart, so they can become even wiser than they are yet.

**Comment by lve0200** [comment] 2020-11-01 15:40
GUYS, stop the powerplay!!! The  dev is not ready, yet! This was clearly stated!
![image](https://user-images.githubusercontent.com/47894777/97807415-df13ff80-1c60-11eb-88bc-c7a086e3029f.png)
Until now  we got an AB320 about magnitudes better than the Asobo!

**Comment by joniatus** [comment] 2020-11-01 15:47
Oh but I thought it was 2500fpm for all phases?? I have no issues meeting those decent rates and getting fully configured for landing. If you give me the specific star I'd be happy to test it. If the vatsim controller had you deviate from the altitude constraints that caused you to be 240 on short final then ask for a go around.

Show a little respect, @MisterChocker put in a ton of work making the plane actually enjoyable to fly until they rework the fbw. Is it perfect? Of course not, but throwing out speed brakes and diving and slowing down simultaneously is stupidly unrealistic so if that's what you want go fly the default. Otherwise just follow the charts and you'll be fine

**Comment by vlbreda** [comment] 2020-11-01 15:53
Come on, please don't confuse humor with disrespect! I think everyone appriciates the work which is put into this project, there's no doubt about that.

**Comment by MisterChocker** [comment] 2020-11-01 15:53
@joniatus 
> Show a little respect, @MisterChocker put in a ton of work making the plane actually enjoyable to fly until they rework the fbw. Is it perfect? Of course not, but throwing out speed brakes and diving and slowing down simultaneously is stupidly unrealistic so if that's what you want go fly the default. Otherwise just follow the charts and you'll be fine

Thanks for the appreciation of my work! Please go ahead and try to reproduce this issue.
I have tried to reproduce quite a few issues regarding this "problem". All turned out the pilots were not flying the plane correctly.
I should also state, that during the development our QA department as well as our IRL A320 Pilots have worked and tested the changes. We have a good quality control to ensure the changes we make do what they are designed to do.
Please feel free to join our discord to contribute to this mod.

**Comment by lve0200** [comment] 2020-11-01 15:54
@MisterChocker 
> Yes the current engine model in the master/dev version is not realistic, it solves a couple of issues with the engines and flight model to improve the flying performance of the aircraft.
Could you laborate or provide links, which issues you wanted to solve w/ your mod. Lifting the lower end for taxi is clear, but IMHO everything else modifying the curves will be counteracted by the AP/ATH. I attache an excellent document telling about the interacxtion between AP, FD and ATH. in Brief the AP tell what he wants and the ATH sets the thrust. So if the AP says up 500ft/min, ATH sets some thrust. If you go now and mod the power curves so that for this thrust setting, more (or less) power is provided, the ATH will just set another thrust to that the request from the AP will be fullfilled.
[Airbus_Descent_Monitoring_1.pdf](https://github.com/flybywiresim/a32nx/files/5471230/Airbus_Descent_Monitoring_1.pdf)

**Comment by MisterChocker** [comment] 2020-11-01 16:02
@lve0200 Engine performance has been reworked to match real life performances through various flight stages. Taxi, Takeoff, Climb, Cruise and Approach.
Also work on the fuel flow has been done.
Please go ahead and look at the documents used for the changes, they can be found in the pr. https://github.com/flybywiresim/a32nx/pull/1295

**Comment by lve0200** [comment] 2020-11-01 16:05
> I have tried to reproduce quite a few issues regarding this "problem". All turned out the pilots were not flying the plane correctly.

Hold on! Decending @ 210Kts during APP gives me at best -1000Ft/min. (w/out brakes) According to the a.m. performance chart, this is less than the -1500Ft/min and w/out reserve. So what am I doing wrong? It can be perfectly possible to fly vanilla APPs w/ only -1000Ft/min, but what do you do w/ strong tail winds, or when ATC wants you to stay up until the last possible moment??

**Comment by lve0200** [comment] 2020-11-01 16:07
> I should also state that your excel table does not represent engine performance good. It only shows performance at M.1.

Appart from fuel flow and other non performance relevant changes, the file compare showed clearly that only N1 values were the relevant power concerning changes. My excel sheet compares these changes to the original data of Asobo.

**Comment by MultiMediaWIll** [comment] 2020-11-01 16:14
> Oh but I thought it was 2500fpm for all phases?? I have no issues meeting those decent rates and getting fully configured for landing. If you give me the specific star I'd be happy to test it. If the vatsim controller had you deviate from the altitude constraints that caused you to be 240 on short final then ask for a go around.
> 
> 
> 
> Show a little respect, @MisterChocker put in a ton of work making the plane actually enjoyable to fly until they rework the fbw. Is it perfect? Of course not, but throwing out speed brakes and diving and slowing down simultaneously is stupidly unrealistic so if that's what you want go fly the default. Otherwise just follow the charts and you'll be fine

You're missing the point. The A320 should be able to follow the reasonable requests from ATC. I was following the altitude restrictions of the STAR no problem. The problem occurs when you have a busy airspace and the ATC assigns you speed restrictions. The current A320 can't follow the speed restrictions and then slow down fast enough when the restrictions are lifted to descend at approach speeds. There's no way this is similar to real life.

**Comment by MisterChocker** [comment] 2020-11-01 16:16
@lve0200 
> @ 210Kts during APP gives me at best -1000Ft/min

Do you use managed descent or open descent?
Managed descent seems to be broken.

> only N1 values were the relevant power concerning changes. My excel sheet compares these changes to the original data of Asobo

yes but still you are only comparing for M.1.

**Comment by lve0200** [comment] 2020-11-01 16:20
> Do you use managed descent or open descent?

Open decent;

> yes but still you are only comparing for M.1.<
there are no other N1 values in the engines.cfg file! In my excel the X-Axis is the thrust, Y-Axis is teh N1 value and each color of the curves represents settings from 0.1 to 0.9 (I guess weight)

**Comment by MisterChocker** [comment] 2020-11-01 16:23
@lve0200 
Using VS 1200ftm and still having ~30%N1 to maintain speed.
![image](https://user-images.githubusercontent.com/1857322/97808384-de7e6780-1c66-11eb-9c4f-3b8fef5a4c17.png)

**Comment by lve0200** [comment] 2020-11-01 16:27
Hhm, could you try w/out setting a manual V/S? Just set speed to 210 and make an open decent say from 5000 Ft down to 2000Ft and see what you get in terms of throttle and ROD. May be there's something w/ the AP or ATH
Thank you

**Comment by MisterChocker** [comment] 2020-11-01 16:34
@lve0200 will do, GD? or 210?

**Comment by lve0200** [comment] 2020-11-01 16:38
GD?

**Comment by lve0200** [comment] 2020-11-01 16:41
Use minimum clean speed, AFAIK, the little green circle (may be wrong). Just what you can barely fly w/out having to apply flaps

**Comment by MisterChocker** [comment] 2020-11-01 16:44
GD means Green Dot, also known as minimum clean speed. And GD is a safe speed to fly, not a speed you can barely fly.

**Comment by MisterChocker** [comment] 2020-11-01 16:48
@lve0200
Are you flying with a custom livery?

**Comment by lve0200** [comment] 2020-11-01 16:51
NO

**Comment by MisterChocker** [comment] 2020-11-01 17:06
Hard to tell, I get 900 to 1300fpd at 7500ft in Open Descent at GD and in clean config.

**Comment by donstim** [comment] 2020-11-01 17:09
The 0.1 to 0.9 are Mach numbers. Changes to the n1-fn table will change the airplane's climb and descent capability in open climb and open descent modes because these modes are are at a set N1 level (max climb N1 or idle). Airplane pitch is used to control speed, and the rate of climb /descent falls out from that. It can be changed by changing configuration (flaps/slats/gear/speedbrakes) or speed. The rate of climb will naturally reduce as you get higher as climb thrust reduces, and the rate of descent will decrease as you get lower as idle thrust increases. With approach/landing configurations, idle thrust is raised even higher to allow TOGA thrust to be achieved more quickly in the event of a go-around.

**Comment by lve0200** [comment] 2020-11-01 17:13
> With approach/landing configurations, idle thrust is raised even higher to allow TOGA thrust to be achieved more quickly in the event of a go-around.

This is another point of concern 4me. On short final, I see thrust levels on or almost on Idle to achieve the 3° G/S (-900Ft/min) 
@MisterChocker 
I observed the lower you get the lesser the sink rate. 800-1330 @ 7500 but check again around 2000. And pickung up this point, make a landing and check your thrust level on short final.

**Comment by MisterChocker** [comment] 2020-11-01 17:15
@lve0200 yes at 2500ft I got 700ft/m right now.
Thrust on approach is ~41% N1 at SL.

**Comment by lve0200** [comment] 2020-11-01 17:16
SL?

**Comment by MisterChocker** [comment] 2020-11-01 17:16
Sea Level

**Comment by donstim** [comment] 2020-11-01 17:17
Airbus' recommended procedure for a higher rod during initial approach is to deploy Conf 1 early and use speedbrakes as needed. As I stated previously, I was able to maintain ~2000 fpm rid at Cobf 1 with speedbrakes, which provides 500 fpm "reserve" over the 1500 fpm approach rod in the chart you provided.

**Comment by lve0200** [comment] 2020-11-01 17:18
> Airbus' recommended procedure for a higher rod during initial approach

Yeah, but ATC might have other priorities

**Comment by lve0200** [comment] 2020-11-01 17:22
Hey guys, I looked a bit into the Issues, which lead to the mod of idle thrust. It was about surface friction, which cannot be changed due to the SDK. So the decision was to mimik this by increased idle thrust.  Lets face it, the effect we got from this is a flaky decent performance in lower altitudes.  I propose as a compromise to reduce the idle thrust (as I did in my file) to something in the middle of the mod and the original. Then we have better decent and better (although not perfect) taxi behaviour and when eventually a new SDK is out, things can be modded again.
my 5 cts worth

**Comment by donstim** [comment] 2020-11-01 17:29
First thing of piloting to understand, atc is a very poor term. Atc does not control the airplane. The pilot does. The 2nd thing to understand, airplane performance has lumits, and the pilot must work within those limits. Informing the controller when what they are requesting is beyond other the pilot's, the operator's, or the airplane's limits is expected.

**Comment by lve0200** [comment] 2020-11-01 17:33
Hey man, I'm not a CPL, but a PPL and I spent much time in Airliner's cockpits b4 9/11. I can tell you, if in Heathrow, Singapore, Hongkong or Charles de Gaulle, the Controller tells you "maintain FL xxx", " Expedite decent to yyyy", etc. you'll not going to argue that YOU are the pilot.

**Comment by donstim** [comment] 2020-11-01 17:34
I understand there have been comments/statements that ground friction is too high. What is the basis for this belief - how does one separate out ground friction from thrust? Is it friction, thrust, or both? The same comment applies to in-air drag vs thrust.

**Comment by donstim** [comment] 2020-11-01 17:35
If you can't do it, you sure better argue tgat.

**Comment by lve0200** [comment] 2020-11-01 17:49
we're getting side tracked. In the a.m. reference perf chart, a ROD of 1500Ft/m 43 APP is indicated. This reference has to be fullfilled (by the plane or AB) or respected (by ATC). Recommendations of AB are OK, but not mandatory. And as we just learned from MisterChockers check flight we've got 700Ft/m, at 2500Ft, which is not enough, or do you want to apply speed brakes on final?

**Comment by MisterChocker** [comment] 2020-11-01 17:53
> we're getting side tracked. In the a.m. reference perf chart, a ROD of 1500Ft/m 4 APP is indicated. This reference has to be fullfilled (by the plane or AB) or respected (by ATC). Recommendations of AB are OK, but not mandatory. And as we just learned from MisterChockers check flight we've got 700Ft/m, at 2500Ft, which is not enough, or do you want to apply speed brakes on final?

your a.m. reference is not A320-251, its for classic A320 without sharklets.

**Comment by Benjozork** [comment] 2020-11-01 17:54
Alright people, I'm going to lock this as discussion/debate about what proper behaviour is should not happen on GitHub issues, which are strictly for tracking confirmed and confirmed problems. We simply cannot manage this if there is so much noise.

**Closed** 2020-11-01 17:55 UTC
Labels: Bug
