### ISSUE TITLE
[BUG] ADIRS malfunctioning if engines are turned on before alignment finishes

### ISSUE THREAD

**Issue by BreakerHUN** [flybywiresim/a32nx#2473] opened 2020-12-16 20:58 UTC
**Mod Version**

Latest dev version:
{
  "built": "2020-12-16T13:12:05+00:00",
  "ref": "",
  "sha": "",
  "actor": "ThatRedMelon <34657891+ThatRedMelon@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

If you turn on even only one engine before the ADIRS alignment finishes, you get a TCAS fault message.

**To Reproduce**

1. During normal startup power up the plane and put the ADIRS buttons to NAV mode. This will start the alignment.
2. BEFORE alignment finishes start engine 2 or 1. Once spins up, amber message on higher ECAM says TCAS fault.

**Expected behavior**

TCAS should align itself even if you start eninges and while standing still.

**Actual behavior**

TCAS fault message appears and ADIRS not aligned.

**References**

![image](https://user-images.githubusercontent.com/71471788/102405457-79e65480-3fe9-11eb-9789-04d6dc8ed8d5.png)

**Additional context**

Was this working before/when did the issue start occurring?
Not sure. Only noticed about a week ago.

Is this a problem in the vanilla unmodded game?
not tested with vanilla

Discord username (if different from GitHub):
BreakerHUN#3986

**Comment by beheh** [comment] 2020-12-17 02:16
This is expected. TCAS FAULT is inhibited before engine start, but appears once at least once engine is running (FWC phase 2). Just clear it and continue.

**Comment by Benjozork** [comment] 2020-12-17 16:59
Closing as working fine

**Closed by Benjozork** 2020-12-17 16:59 UTC
Labels: Bug, Working as Intended

**Comment by martin-key** [comment] 2020-12-17 17:05
Actually, the problem is that when you start directly on the runway you need to switch off the engines and you need to start all over the procedure and way 7 minutes, which is inconvenient.
