### ISSUE TITLE
Tranponder Code is changing automatically

### ISSUE THREAD

**Issue by Pil0tDave** [flybywiresim/a32nx#5686] opened 2021-08-19 16:54 UTC
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-08-19T05:29:58+00:00",
  "ref": "autopilot-custom-fpm",
  "sha": "6bc1a9f9725f7bd1c839c1a1ed611539c62afb2e",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

The tranponder code is changing after entering in a manual transponder code. This starts to happen when airborne, meaning on the ground the manual squawk will stay consistent. Once taken off it will chnage to a random number. After a maual re-entry it will chnage again after 1 min. The new random number stays the same.

### Expected behavior

The squawk stays the same the whiole time until the user changes it.

### Steps to reproduce

1. Enter in a squawk (eg. 1000)
2. Take off
3. Squawk will change

### References (optional)

At 9:03
![image](https://user-images.githubusercontent.com/89213819/130110629-b93dd78f-6cea-4054-b3a4-991384a1a508.png)

At 9:04
![image](https://user-images.githubusercontent.com/89213819/130110770-f86962f0-9433-459a-a083-d5db15a17a68.png)

**Comment by sidnov** [comment] 2021-08-19 17:11
Firstly, no support will be provided for cFPM builds, which is why I would be closing this issue.

This issue looks like it is caused by having AI Pilot/Assistance turned on. Please make sure AI Piloting is turned off.

**Closed by sidnov** 2021-08-19 17:11 UTC
Labels: Bug

**Comment by sidnov** [comment] 2021-08-19 17:25
On a sidenote, @Pil0tDave feel free to share your feedback/bug reports/suggestions about the cFPM in the #ata-22-fms channel on our Discord server where we have created a thread called "Bugs and Issues"

**Comment by Pil0tDave** [comment] 2021-08-19 17:48
No problem, thanks for the help
