### ISSUE TITLE
CTD When Flicking "ASKID& N/W STRG" Switch

### ISSUE THREAD

**Issue by notl3ks** [flybywiresim/a32nx#6672] opened 2022-02-08 11:44 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-02-08T10:17:26+00:00",
  "ref": "master",
  "sha": "1502efb2d596d3b776ab075c04ed651aa97b7e81",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

I was starting up my aircraft after pushing back from London Gatwick (EGKK), and when turning on Eng Master 1 switch and the engine is powering up, I for whatever reason decided it would be fun to flick the nosewheel steering & anti-skid switch which resulted in an immediate CTD.

### Expected behavior

I just expected the ECAM displays and warning sound to chime telling me about it like normal, but this was not the case.

### Steps to reproduce

1. Go through normal startup procedures (cold & dark, FMGS, all the usual stuff)
2. Push out onto the taxiway
3. Start engine no. 2 sucesfully
4. Start engine master 1
5. While starting, flicking that anti-skid switch caused the game to CTD.

**Comment by crocket63** [comment] 2022-02-09 12:51
Hi, what is the state of the pushback when you flick that switch? Tug is already gone?
Is this something 100% repeatable on your side?

Thanks

**Comment by Axis360** [comment] 2022-02-10 06:27
Hello,
This is very similar to what I had with the status ecam (post above) but I was able to reproduce it just behind on the ground with the engine off...

**Comment by derl30n** [comment] 2022-04-08 23:14
Closing since unable to reproduce, if issue occurs again please do go ahead and re-open this issue or create a new one.

**Closed by derl30n** 2022-04-08 23:14 UTC
Labels: Bug

**Comment by notl3ks** [comment] 2022-04-19 09:31
> Closing since unable to reproduce, if issue occurs again please do go ahead and re-open this issue or create a new one.

Hi. I've left replying off for a bit to see if I can reproduce it again. I'm now convinced this is a simulator issue rather than A32NX related. However, I do find they are a tiny tiny bit more common with the mod than using say default GA aircraft like the Cessna 152. I'll leave a snipped of the error log from Windows Event Viewer.

`Faulting application name: FlightSimulator.exe, version: 1.24.5.0, time stamp: 0x00000000
Faulting module name: FlightSimulator.exe, version: 1.24.5.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000001b9b9ca
Faulting process ID: 0x2858
Faulting application start time: 0x01d8534a9770b1a1
Faulting application path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.24.5.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.24.5.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Report ID: 944a1b1b-7c1c-4e3a-af2a-e7c6722c35cc
Faulting package full name: Microsoft.FlightSimulator_1.24.5.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App`

I'll wait for SU9 to drop, and if I can reproduce, I shall re-open with further details. Thanks!
