### ISSUE TITLE
[REQUEST] TCA Addon Auto brake doesn’t work

### ISSUE THREAD

**Issue by Azores77** [flybywiresim/a32nx#2852] opened 2021-01-03 12:57 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**
the ThrustMaster Airbus Throttle  Addon  Auto break is not working with the FBW mod,it works with the default a320.

**References**

**Additional context**

Discord username):Azorean77

**Comment by Watsi01** [comment] 2021-01-03 12:58
Please use the template and give more information.

**Comment by Saschl** [comment] 2021-01-03 13:58
I’ll have a look at this. It’s about the button mapping for the autobrake that doesn’t work with the mod anymore. 

But I agree that you should use the template, at least remove the line at the bottom ;)

**Comment by Azores77** [comment] 2021-01-03 14:03
Ok thank you,sorry but this is  my first time using GitHub and  I’m finding this a bit to confusing  :)

**Comment by MisterChocker** [comment] 2021-01-03 14:17
@Azores77 

> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by MisterChocker** [comment] 2021-01-13 11:14
This actually also is a duplicate of #1997

**Comment by yukyan1985** [comment] 2021-01-19 14:09
This does not seem to be a problem only with the TCA Quadrant Add-On.
I tried keybinding to the keyboard and AUTO BRK did not work.
In addition to this, I also confirmed that Toggle Approach does not work with the keyboard or TCA Quadrant Add-On.
There may be other switches that don't work as well.

**Comment by MisterChocker** [comment] 2021-01-28 14:21
Duplicate of #1997

**Closed by MisterChocker** 2021-01-28 14:21 UTC
Labels: Enhancement, Waiting For Response
