### ISSUE TITLE
[BUG] AUTOBREAK MAX wasa disengaging before take off automacally

### ISSUE THREAD

**Issue by ducky3333** [flybywiresim/a32nx#982] opened 2020-09-30 05:57 UTC
**Mod Version**

0.3.0 ~0.3.1 same 

**Describe the bug**

T.O list on ECAM , the Autobreak MAX setting disengage automacally. 

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by tyler58546** [comment] 2020-09-30 06:01
Duplicate of #255. Please search before reporting.

**Closed by tyler58546** 2020-09-30 06:01 UTC
Labels: Bug
