### ISSUE TITLE
[BUG] CUSTOM FBW ENGINE SHUTTING OFF AS SOON AS I USE REVERSE THRUST 

### ISSUE THREAD

**Issue by JAMNICKK** [flybywiresim/a32nx#3205] opened 2021-01-27 05:53 UTC
**Mod Version**
 FBW EXPERIMENTAL INSTALLED ON THE 26TH OF JAN AT 9:00PM EST

 

**Describe the bug**

After landing and adding reverse thrust my engines died and all my screens turned black. It took me 2 try's to restart them and when they finally start I used the reversers again and the engine died.

**To Reproduce**

1. use reversers thrust as the engines are running 
2. if that doesn't work try taking off and using reversers
3. start up apu and restart the engines 

**Expected behavior**

after using reversers expect all screens to go black and and engine cutoff. Also expect no brakes after landing. Then expect engines to start on the second attempt of restarting them

**Actual behavior**

all screens will go black, no brakes, and engines will start on second try

**References**

![FlightSimulator_NliydUTq01](https://user-images.githubusercontent.com/78067520/105948342-c4231280-6038-11eb-8255-6ea086ec09e0.png)
![FlightSimulator_TtYPej6nMZ](https://user-images.githubusercontent.com/78067520/105948362-cc7b4d80-6038-11eb-9e7e-670bf2a76ff6.png)

**Additional context**

Was this working before/when did the issue start occurring?
It started happening after installing the new Experimental FBW update on the 26th of Jan at 9:30pm est 
Is this a problem in the vanilla unmodded game? NO

Discord username (if different from GitHub): JAMNICK

**Comment by MisterChocker** [comment] 2021-01-27 13:32
cc. @aguther

**Comment by Rameyuk** [comment] 2021-01-28 14:26
Are you sure your controls don't have double binding the reversers to fuel cutoff or master engine switch?
I just land using the latest FBW experimental mod, downloaded on the 29-Jan-2021 and they feel fine as always:

https://youtu.be/33ne-e17SYU?t=9280

**Comment by JAMNICKK** [comment] 2021-01-28 21:11
> Are you sure your controls don't have double binding the reversers to fuel cutoff or master engine switch?
> I just land using the latest FBW experimental mod, downloaded on the 29-Jan-2021 and they feel fine as always:
> 
> https://youtu.be/33ne-e17SYU?t=9280

**Comment by JAMNICKK** [comment] 2021-01-28 21:13
> > Are you sure your controls don't have double binding the reversers to fuel cutoff or master engine switch?
> > I just land using the latest FBW experimental mod, downloaded on the 29-Jan-2021 and they feel fine as always:
> > https://youtu.be/33ne-e17SYU?t=9280

No, my controls are the same as in the dev version, I only changed the throttle config to work with my tca throttle

**Comment by MisterChocker** [comment] 2021-01-28 21:46
The cockpit texture/model is not supported by our mod. This can lead to bugs.

**Comment by JAMNICKK** [comment] 2021-01-30 03:14
but I'm not using any cockpit texture mod

**Comment by aguther** [comment] 2021-01-31 12:49
I just tried latest cfbw and I'm not facing this issue (I use reversers on the axis).

- How do you use reversers?
- How are you controls mapped?
- Which hardware do you have for controls, especially throttles?
- Can you please share your ThrottleConfiguration.ini?

**Comment by Asianblade** [comment] 2021-02-02 01:47
Don't worry, it's not a bug. Close this. Pretty sure someone is just trying to cause problems.

**Comment by JAMNICKK** [comment] 2021-02-03 02:56
Its now fixed after downloading the latest FBW version

**Closed** 2021-02-03 12:59 UTC
Labels: Bug, Engines, Waiting For Response
