### ISSUE TITLE
[BUG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by pacha35** [flybywiresim/a32nx#3692] opened 2021-02-23 16:04 UTC
**Mod Version**

A32NX V0.5.2 "dev" n°f70e084

**Describe the bug**

On some airports, SID and ILS approaches do not work correctly : 
- during the SID phase, the aircraft go to several loops and we have to use the DIRCT To function to leave the loops
- a waypoint is présent in the MCDU and the aircraft do not use it
- ILS is notified in the MCDU but no ILS information on the PFD and impossible to enter ILS frequency on RAD/NAV page.
- clear or create a waypoint on the MCDU-FPL page does not work at each time

**To Reproduce**

1. ILS approaches : several times on LFRN and LFBD airports
2. Loops : idem
3. Create and delete waypoints : very often

**Expected behavior**

To fix these bugs in order to arrive to fly in RNAV procedure at each time.

**Actual behavior**

On some airports, SID and ILS approaches do not work correctly : 
- during the SID phase, the aircraft go to several loops and we have to use the DIRCT To function to leave the loops
- a waypoint is présent in the MCDU and the aircraft do not use it
- ILS is notified in the MCDU but no ILS information on the PFD and impossible to enter ILS frequency on RAD/NAV page.
- clear or create a waypoint on the MCDU-FPL page does not work at each time

**References**

See the attached document

**Additional context**

FS2020 V13.16.0
A32NX with the last dev version proposed vy the installer
No other mods in Community but it the same problem with other mods in community

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): PACHA35ROTW

[A32NX-ILS-problem.pdf](https://github.com/flybywiresim/a32nx/files/6030097/A32NX-ILS-problem.pdf)

**Comment by Benjozork** [comment] 2021-02-23 18:21
> A32NX V0.5.2 "dev" n°f70e084

This is not a valid version. 0.5.2 is a stable release, not a dev version. Please follow the template instructions and provide the contents of `build-info.json`.

> during the SID phase, the aircraft go to several loops and we have to use the DIRCT To function to leave the loops

Known issue, will be fixed with custom flight plan manager.

> a waypoint is présent in the MCDU and the aircraft do not use it

Duplicate of #939

> ILS is notified in the MCDU but no ILS information on the PFD and impossible to enter ILS frequency on RAD/NAV page.

Can you elaborate on exactly what happens when you enter the frequency in this case ?

> clear or create a waypoint on the MCDU-FPL page does not work at each time

Probably duplicate of #1388. fixed with upcoming custom flight plan manager.

Closing as we do not accept issue tickets for multiple problems.

**Closed by Benjozork** 2021-02-23 18:21 UTC
Labels: Bug
