### ISSUE TITLE
[BUG] Autopilot slides to the right and snaps back

### ISSUE THREAD

**Issue by MTRNord** [flybywiresim/a32nx#1006] opened 2020-09-30 19:46 UTC
**Mod Version**

master

**Describe the bug**

The AP suddenly loses the tracking of the FD and dips to the right side. After a few minutes it snaps back.

I suspect it to either be wind changes or an exception throwing. I suspect it because the controls while this happen are direct again and don't need the extra time it needs until it disengages the AP. So it feels like it killed the AP while still indicating being on AP. Maybe something errors out and it cant handle that

**To Reproduce**
Unknown. Seems random

**Expected behavior**
Should follow route

**Actual behavior**
Suddenly moves

**References**
![grafik](https://user-images.githubusercontent.com/1374914/94732028-f90ea980-0365-11eb-9a27-35bc64460808.png)

**Additional context**

Was this working before/when did the issue start occurring?
Yes

Is this a problem in the vanilla unmodded game?
According to comments it might be

Discord username (if different from GitHub): MTRNord#8524

**Comment by MTRNord** [comment] 2020-09-30 19:49
Just to avoid confusion -> The AP1 Light is still on and it still tracks height adjustments

**Comment by fermansell** [comment] 2020-09-30 19:51
In my case every time I turn on the Autopilot it goes to the right, doesn't matter how many times I turned off or on it does the same turn and basically crash if I leave it on.

**Comment by MTRNord** [comment] 2020-09-30 20:01
I just had that on approach. it took roughly 7m to get back working

**Comment by MTRNord** [comment] 2020-09-30 20:21
Seems like I made a duplicate of #992 I let the devs decide if this should be closed

**Comment by elbryan** [comment] 2020-09-30 20:24
I think this problem is there also in vanilla. I am afraid that we would need to wait for a patch from upstream.

**Comment by MTRNord** [comment] 2020-09-30 20:26
A workaround must be found I am afraid. Not gonna wait 1-2 months for a fix. As i expect them to not fix it but actually to make the game more bugged :) (not a complaint about the mod. This is a complaint about the asobo update quality)

**Comment by drumline18** [comment] 2020-09-30 20:28
Without A32NX the plane still turns aggressively to the left in my case, until crashed.
I'm departing from CYUL 06L going north (CYQB).

**Comment by elbryan** [comment] 2020-09-30 20:32
I even recorded [a video](https://www.youtube.com/watch?v=7YesoSjYmrI) for fun that shows the problem. I think this is what we all refer to.

PS: Once I stopped the video, the AP started working normally. Then I started the descent at 10k feet, as soon as it started to descent, it also started to bank left and loop like in the video.

**Comment by MTRNord** [comment] 2020-09-30 20:34
@elbryan yep thats the issue :) Luckily it still allows you to correct manually. Or well it flies as if it is full manual mode

**Comment by Remy737** [comment] 2020-09-30 21:09
same problem, posted under #1007 and #992

**Comment by visualcookie** [comment] 2020-09-30 21:15
This has nothing to do with the mod unfortunately. The mod can't change the AP behavior, this is something ASOBO has to fix or give the modders access to change the base aircraft files/model.

**Comment by fermansell** [comment] 2020-10-01 03:22
I upload a video of the issue : https://youtu.be/vBbJLKDFjYU

**Comment by speedwaystar** [comment] 2020-10-01 03:31
there was an issue last patch with the player's AP appearing to excute phantom commands intended for AI airfield traffic (sic) which probably hasn't been fixed. try turning off all airfield AI traffic.

**Comment by Remy737** [comment] 2020-10-01 08:30
I just tried without any AI aircraft, seems to be working for me, thank's for the input

**Comment by fermansell** [comment] 2020-10-01 08:38
Not working for me !

**Comment by Remy737** [comment] 2020-10-01 08:43
I disable only the AI aircrafts, Live aircraft are still enable. But I just tried a small LNAV route, I will try a proper flight later today, i'll Report back

**Comment by MTRNord** [comment] 2020-10-01 09:28
The problem is that this makes it unable to work with VATSIM as obviously that one has AI traffic :/

**Comment by fermansell** [comment] 2020-10-01 09:30
so theres no workaround ¡?

**Comment by jimjim76** [comment] 2020-10-01 17:10
A lot of people suggesting the workaround is to adjust the joystick sensitivity and change the deadzone from 0% to 5% .  I'm about to try that now.  And this is a Vanilla problem since 1.9.3 and they introduced the sensitivity settings

**Comment by MTRNord** [comment] 2020-10-01 17:14
@jimjim76 it even happens without external controllers except mouse and keyboard connected. So I highly doubt it is a sensitivity issue

**Comment by jimjim76** [comment] 2020-10-01 18:07
@MTRNord  It's just worked for me - it flew the SID out of EGLL en route to EHAM.  I set the sensitivity to 5%.  Previously it failed the last 3 attempts, and banked to the right until it overstressed.  I think it's a vanilla bug with the sensitivity settings, which affect the AP even though a controller is not in use.  I could be wrong though.

**Comment by fermansell** [comment] 2020-10-01 18:45
I made the changes but still having the issue I manage to correct the bank angle a little bit but the AP doesnt fallow the altitude and the bank still happening

**Comment by marcink7** [comment] 2020-10-01 20:31
I’m having the same issue and have not been able to complete a single flight using AP since 0.3.1

As soon as I engage AP, it’s a 50/50 chance it will follow the planned route or immediately bank right and after a few seconds start following the route. As soon as it hits the first waypoint, it does not follow the route, starts to bank sharply right and begins losing altitude fast. Over speed in red displays on the ECAM and if I don’t take manual control it would crash every time. This happens within 10 minutes of departure every flight I have tried with the new stable master 0.3.1

I have tried all the suggested workarounds, disabling real-time, AI and ground traffic has not helped. Tried the sensitivity one above and no luck as well.

I’m going to try vanilla next and see if it happens there too although I love the cockpit lights in the new master version and mostly fly at night.

**Comment by marcink7** [comment] 2020-10-01 21:55
Confirmed the same with Vanilla so it is definitely an Asobo issue and based on the forum post over [there](https://forums.flightsimulator.com/t/autopilot-no-longer-follow-the-requested-heading-or-that-of-the-flight-plan/291059/19), it may be tied to the xbox controller sensitivity as mentioned above but did not work for me when tested with 0.3.1

I am going to change the dead zone in the game menu to 5% and calibrate the xbox controller in the windows joystick settings and will test again with vanilla and then 0.3.1

**Comment by marcink7** [comment] 2020-10-01 22:22
AP works 100% with changed dead zone in sensitivity game options and recalibrated joystick in windows settings on Vanilla

**Comment by fermansell** [comment] 2020-10-01 22:48
Confirmed deadzone to 25% works for me !

**Comment by Speedbird84** [comment] 2020-10-03 06:13
Setting dead zone to 20% seems to have fixed it for me. I confirm the problem was in both the vanilla and MOD versions but this setting seems to have fixed both versions for me.

**Comment by KGrasbeck** [comment] 2020-10-11 12:34
I experienced this behavior twice and realized I was talking on the phone with my headphones hanging from the yoke when this happened. The slight roll input caused by the weight of the headphones caused the plane to roll, with the AP staying engaged but unable to keep control.

**Comment by SergeantSerk** [comment] 2020-10-14 12:24
I can confirm that this is a bug and happens with or without the mod. With the developer console open, when I enable autopilot I get the following warning in the console:

`ElectricalSystem [Generic Airliner Twin Engines Asobo 01]: Undefined circuit 2539632838418707132:5 when at least one circuit with a higher index is defined (most likely due to this index missing in system.cfg)`

Not sure if this is automatic heading follow issue but might help with diagnosing the fault.

**Comment by LORAK0090** [comment] 2020-12-02 19:33
AP don't work at all. Not follow star and route. Neither HDG and altitude and vs. I can control plane only by manual.

**Comment by MisterChocker** [comment] 2020-12-31 07:00
fixed by now, remaining issues are still covered

**Closed by MisterChocker** 2020-12-31 07:00 UTC
Labels: Autopilot, Bug
