### ISSUE TITLE
Waypoint dis on MCDU

### ISSUE THREAD

**Issue by Bentebert** [flybywiresim/a32nx#6165] opened 2021-11-10 14:19 UTC
### Aircraft Version

Development

### Description

Hi thanks for info.  
I have a questions regards waypoint distance.
There are a fault in waypoint distance in the MCDU flightplan.
Distance from waypoint to waypoint include aircraft altitude. Ex if you fly FL 350 and the flight plan show you are ex 25 miles to next waypoint, then on the MCDU it´s shows 27 miles.
That are wrong because the altitude are >NOT include in the distance (GPS), only in VOR distance (line of sight).

Hope you see what I mean   
Regards Bent Ebert  ebert@danbbs.dk

**Comment by davidwalschots** [comment] 2021-11-10 21:41
Duplicate of #6164

**Closed by davidwalschots** 2021-11-10 21:41 UTC
Labels: Request
