### ISSUE TITLE
LDG LT memo on ECAM is not toggled by keybinding

### ISSUE THREAD

**Issue by Funda86** [flybywiresim/a32nx#4072] opened 2021-03-22 10:13 UTC
**Mod Version**
Dev version 12e8314

**Describe the bug**
LDG LT ecam memo does not appear if you use keybinding L CTRL + L to switch the landing lights on. It works only if you manually switch the lights in the overhead panel

**To Reproduce**
Use L CTRL + L to switch the landing lights on

**Expected behavior**
LDG LT memo should appear

**Actual behavior**
Memo does not appear

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I think it never worked cuz I never saw the memo. I've just noticed the memo in videos people were making

Is this a problem in the vanilla unmodded game?
Not sure

Discord username David Funda

**Comment by beheh** [comment] 2021-03-22 11:25
Looks like the ECAM is relying on `LANDING_1_Retracted` and `LANDING_2_Retracted` LVars respectively. Sounds like they aren't updated correctly through the keybinding?

**Comment by MisterChocker** [comment] 2021-03-22 23:41
Duplicate of #1507

**Closed by MisterChocker** 2021-03-22 23:41 UTC
Labels: Bug
