### ISSUE TITLE
Control Inputs "get stuck" or "get forgotten" on FBW / Control input lag TCA Quadrant/Saitek Rudders

### ISSUE THREAD

**Issue by flyingpaul1980** [flybywiresim/a32nx#5478] opened 2021-07-30 09:02 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-30T02:31:34+00:00",
  "ref": "master",
  "sha": "bab6a451346ee9fb2a28abe20bf4ec454933e371",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

The Problem seems to affect control inputs in general, but mostly Autobrakes, Throttle Levers and Toe Brakes / Rudders

1.) When selecting an Autobrake value (lo/med/max), the button lights up, but without further activities it will stop glowing after a while. Sometimes it will illuminate again, and go off again.. in an interval of a few seconds to up to 20-30 seconds.
This results in set autobrakes on final that then don't work after touchdown because the button somehow deactivated.

I know the Autobrake logic was altered after it didnt work anymore some time before SU5, but now it seems to require attention once again.

(key bindings were checked and found to be correct)

2.)

When taxiing on the ground, there seems to be something causing the inputs to freeze when you use asymmetric thrust on the ground with rudder inputs and asymmetric toebrakes. Rudder, Brake and Thrust Lever then freeze in their positions and the Plane taxis into the ditch uncontrollably.

TCA Throttle and Addon are Calibrated in the Flypad.

- observations - when going to pause and then to control settings, there is a noticable lag before the sim loads in the configuration. i know this is not FBW related, but it might contribute something to the problem

### Expected behavior

I expect auto brake settings to be logged in permanently when pressing the button (when plane standing on ground or being in cruise)

I also expect that rudder, toebrakes and thrust levers can be used individually in a reactive way that keeps the airplane controllable

### Steps to reproduce

1.) spawn on runway, set autobrakes to off and then back to max, wait (with TCA Add-on)

2..) land at a complex airport with a maze of taxiways and wait for rudder pedals or thrust lever to get stuck in their positions as you taxi around

**Comment by aguther** [comment] 2021-07-30 09:08
I cannot reproduce any of your observations of point 2. I have individual throttles, rudder and toe brakes and do. it observe any of the mentioned issue. I suspect either a MSFS issue or double key binding.

**Comment by flyingpaul1980** [comment] 2021-07-30 09:14
> I cannot reproduce any of your observations of point 2. I have individual throttles, rudder and toe brakes and I don’t observe any of the mentioned issue. I suspect either a MSFS issue or double key binding.

Moin,
from the discord i heard that the control inputs freeze if you use right-button-mouselook during taxiing. this would be new. I have to test still if this really is the case and then see if it is for FBW only, but that would explain 2.)

Regarding 1.) do you use the thrustmaster TCA throttle and add-on? it's a special case because it "keeps the button pressed" to select the autobrake setting. this might be the reason why this phenomenon only happens with the thrustmaster TCA

**Comment by ribase** [comment] 2021-07-30 09:34
Same here with Thrustmaster HOTAS throttle, stick and pedals.
Very annoying when taxi, controls stuck and led the aircraft anywhere.

**Comment by Benjozork** [comment] 2021-07-30 09:48
Have any of you tried other aircraft ?

**Comment by aguther** [comment] 2021-07-30 09:53
I have also the TCA throttle but must admit that the autobrake I‘ve mapped using FSUIPC.

**Comment by aguther** [comment] 2021-07-30 09:55
Let‘s hope the hotfix coming today will fix your errors as well. Nothing was actually changed in that area from our side and we have no (new) information that the way we are receiving the control input is done in an inappropriate way.

**Comment by flyingpaul1980** [comment] 2021-07-30 09:56
> Let‘s hope the hotfix coming today will fix your errors as well. Nothing was actually changed in that area from our side and we have no (new) information that the way we are receiving the control input is done in an inappropriate way. Therefore I assume it‘s another SU5 issue.

alles klar, fingers crossed, thx

**Comment by flyingpaul1980** [comment] 2021-07-30 11:48
> Have any of you tried other aircraft ?

I confirm that this also happens with stock planes. thus, 2.) is not a FBW problem.

**Comment by flyingpaul1980** [comment] 2021-07-30 14:09
The Autobrake switch works seamlessly for other airliners, so this is a FBW problem still

**Comment by NUTTTTTTTT** [comment] 2021-07-30 14:17
> Regarding 1.) it's a special case because it "keeps the button pressed" to select the autobrake setting. this might be the reason why this phenomenon only happens with the thrustmaster TCA.

I don't have the hardware, but it seems like this could potentially be a similar issue to what we've seen since the sim update with engine starts, which I've linked below for you to have a read of. Although obviously in this case we're talking about brakes rather than engine switches. 

Can you have a read of the below, and see if a similar issue is happening with brakes? If your controls are expecting "Toggle brake" but are getting a held input instead, it can confuse it and vice verca, or if you have both a "toggle" and "set" control bound to the same key. 

Sim Update 5 issues + Issues when using TCA hardware - known issues and workarounds:
https://docs.flybywiresim.com/start/reported-issues/#su5-issues

**Comment by ohnoitsBlarry** [comment] 2021-07-30 15:55
> Moin,
> from the discord i heard that the control inputs freeze if you use right-button-mouselook during taxiing. this would be new. I have to test still if this really is the case and then see if it is for FBW only, but that would explain 2.)

Moin moin, 
it's not only during taxiing. Looking around via RMB blocks any control inputs whatsoever during the flight, which already caused some uncomfortable situations in the sim. It's the same for all aircraft, though, so not specifically a mod problem.

**Comment by flyingpaul1980** [comment] 2021-07-30 20:27
> > Moin,
> > from the discord i heard that the control inputs freeze if you use right-button-mouselook during taxiing. this would be new. I have to test still if this really is the case and then see if it is for FBW only, but that would explain 2.)
> 
> Moin moin,
> it's not only during taxiing. Looking around via RMB blocks any control inputs whatsoever during the flight, which already caused some uncomfortable situations in the sim. It's the same for all aircraft, though, so not specifically a mod problem.

correct, this point is not a mod problem - temporary workaround can be "toggle" free look with the middle mouse key instead of "hold to free look" with right mouse button.

this is annoying (for me, others who always use middle mouse button will never know), but MSFS should be able to fix this.


The Autobrake Problem with the TCA add on is persisting unfortunately, and that is limited to the FBW.. it works fine in dreamliner and jumbo

**Comment by aguther** [comment] 2021-08-02 09:12
I close this bug now, because the main topic according headline was the controls that got stuck. Please open an extra bug for the autobrake issue.

**Closed by aguther** 2021-08-02 09:12 UTC
Labels: Asobo Bug
