### ISSUE TITLE
[BUG] GPWS LDG Flap 3

### ISSUE THREAD

**Issue by LorDawid** [flybywiresim/a32nx#803] opened 2020-09-22 11:30 UTC
**Mod Version**

DEV Version, and the newest MSFS version

**Describe the bug**

GPWS LDG Flap 3 shows wrong info -> When its turned off, it displays boxed "OFF" info, which i think it shouldnt because this buttons default state should be OFF. Also, when its turned off, the ECAM shows that its turned on.

**To Reproduce**

1.  Click on the LDG FLAP 3 button on the Overhead panel -> GPWS

**Expected behavior**

The button should be OFF by default, and when its off it shouldnt display an ECAM message + it should display only the "ON" light on the button when its turned on

**Actual behavior**

The button is in the ON position by default, and when its off it shows an ECAM message and the OFF light on the button

**References**

![image](https://user-images.githubusercontent.com/44745662/93876802-b6026580-fcd7-11ea-9a66-c33bfca06ecf.png)

Discord username (if different from GitHub): LorDawid#6403

**Comment by DoToAdventures** [comment] 2020-09-22 12:47
Do you have any FCOM or other references than the picture provided? Regardless, we'll probably need pilot feedback on this. Changing it is no big thing.

**Comment by DarkOfNova** [comment] 2020-09-22 13:57
Will be able to change with the model, nothing anyone can do at the moment though

**Comment by NathanInnes** [comment] 2020-09-22 15:47
Duplicate of #551

**Closed** 2021-01-24 14:43 UTC
Labels: Bug, Bug-Vanilla, Overhead Panel, Texture
