### ISSUE TITLE
[BUG] Outside view no Stutters . Inside Cockpit Stutters . 

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#2603] opened 2020-12-22 09:37 UTC
**Mod Version**
0.5.0

**Describe the bug**
When i was inside Cockpit view i have many Stutters . Limited by Mainthread. 
In the Outside view there are nearly no stutters. 
Set Glass Cockpit refresh rate to Medium

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Highflyer2010** [comment] 2020-12-22 14:09
depending on your system specs this will generally be the case.

**Comment by Benjozork** [comment] 2020-12-22 14:24
MSFS is badly optimized, but also caused by #1341.

Closing as half out of scope, half duplicate.

**Closed by Benjozork** 2020-12-22 14:24 UTC
Labels: Bug
