### ISSUE TITLE
All displays remain black after GPU/APU startup

### ISSUE THREAD

**Issue by Lukmas1986** [flybywiresim/a32nx#6690] opened 2022-02-10 15:35 UTC
### Aircraft Version

Development

### Build info

```json
"built": "2022-02-10T10:00:23+00:00",
  "ref": "master",
  "sha": "f33c3094f212661f989a0664a3f7b8782c32d7f7",
  "actor": "sidnov",
  "event_name": "manual"
```

### Describe the bug

![image](https://user-images.githubusercontent.com/99414922/153438260-7310ff5f-f6ee-4b90-b1a3-1b52b4e665d2.png)
After the last update of the A320nx, all displays remain black after the GPU / APU has been switched on.

### Expected behavior

I would like to see my displays back to be able to make a flight ;). 

### Steps to reproduce

1. I started the game
2. I launched the GPU
3. The displays remained black. I checked this on all 3 versions (stable, development, experimental). I reinstalled the mod, I had no problem with screens on default A320. 

### Discord Username (optional)

Lukmas1986

**Comment by flytester** [comment] 2022-02-10 19:13
Did you turn on the batteries and external power?

**Comment by frankkopp** [comment] 2022-02-10 21:54
> ### Aircraft Version
> Development
> 
> ### Build info
> ```json
> "built": "2022-02-10T10:00:23+00:00",
>   "ref": "master",
>   "sha": "f33c3094f212661f989a0664a3f7b8782c32d7f7",
>   "actor": "sidnov",
>   "event_name": "manual"
> ```
> 
> ### Describe the bug
> ![image](https://user-images.githubusercontent.com/99414922/153438260-7310ff5f-f6ee-4b90-b1a3-1b52b4e665d2.png) After the last update of the A320nx, all displays remain black after the GPU / APU has been switched on.
> 
> ### Expected behavior
> I would like to see my displays back to be able to make a flight ;).
> 
> ### Steps to reproduce
> 1. I started the game
> 2. I launched the GPU
> 3. The displays remained black. I checked this on all 3 versions (stable, development, experimental). I reinstalled the mod, I had no problem with screens on default A320.
> 
> ### References (optional)
> _No response_
> 
> ### Additional info (optional)
> _No response_
> 
> ### Discord Username (optional)
> Lukmas1986

This is not a useful issue report as it lacks basic information to narrow the issue. 
Come to the FlyByWire Discord support channel so the team there can help you investigate. 
Please close this in the meantime. If it turns out to be an issue you can open a new one with the appropriate information (from the investigation) so it can actually be reproduced and corrected.

**Comment by juancalvorotger** [comment] 2022-02-11 07:47
Do you use the "Pilot/Copilot mod"?

**Comment by Lukmas1986** [comment] 2022-02-11 10:41
> Do you use the "Pilot/Copilot mod"?

Yes, removing it helped. Thank you!

**Closed** 2022-02-11 10:42 UTC
Labels: Bug
