### ISSUE TITLE
[BUG] inconsistent displays and autopilot behavior

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#3441] opened 2021-02-09 12:40 UTC
**Mod Version**
"built": "2021-02-09T07:03:20+00:00"
"ref": "fbw"

**Describe the bug**
The displays are inconsistent. With autopilot deactivated during the flight, the PFD should display green bars according to the flight plan but it seems to take into account destination directly. It doesn't make me turn when it is expected:
![2](https://user-images.githubusercontent.com/74733393/107364368-a5faef00-6adb-11eb-9514-83be2fe5a5a2.JPG)

When I activated again the autopilot, the plane turns but did anything:
![3](https://user-images.githubusercontent.com/74733393/107364494-ccb92580-6adb-11eb-801d-b7e373808e56.JPG)

Everithing is in managed mode for autopilot with the altitude set to 12000.

It is the first time I have this behavior in game. There was no update of the game since last time I played and I only updated my A32NX mod (FBW version) before playing so I do not know if it is due to it or no.

This behavior is really weird.

**To Reproduce**
Do a flight and activate autopilot after take-off. Deactivate the autopilot during the flight first and check if flight plan is followed. Then, reactivate autopilot and check if the plane takes into account flight plan correctly.

**Expected behavior**
Plane should indicate and follow the flight plan.

**Actual behavior**
When autopilot deactivated, green bars on PFD does not follow the flight plan and plane do anything when it is reactivated.

**References**
See screens in description

**Additional context**

**Comment by Ash624** [comment] 2021-02-09 13:14
Yep, happened to me too. Autopilot stopped following the flight plan (but didn't turn me upside down) When approaching a WP the AP just set off in a different direction instead of making a turn following the flight plan. I had to go into selected mode, steer to next waypoint, then once on that heading I selected "direct to" next waypoint, which worked, then back into managed. Once the "Direct to" waypoint was reached, back into selected, change course, then direct to next waypoint again. All the way home. I rolled back the a32nx version to one I saved from 4th February. Works fine.

**Comment by phildeg31** [comment] 2021-02-09 13:16
So is it due to the last mod version for you?

**Comment by TravisKG** [comment] 2021-02-09 13:28
Had a similar issue with the custom FBW version.

I had just taken of and enabled the AP to fly a SID and it turned away from the green bars. I turned off AP, realigned myself and tried re-enabling AP with the same result. Also attempted to use DIR to fly to the next waypoint without success.

It's worth noting I stayed in managed mode the whole time and did not try selected mode.

**Comment by Ash624** [comment] 2021-02-09 13:28
Yes. All was reasonable ok until I received a request to change "the plan" (deviate) once I had done that the AP no longer continued following the rest of the flight plan.

**Comment by GlitchedYT** [comment] 2021-02-09 13:43
Hello @phildeg31, the autopilot behaving like that is a known issue. The best known fix is to increase your dead zones to over 20% and increase further until the issue is no longer apparent. Both of these issues will be fixed when we have the Custom AP, and custom FPM implemented.

**Comment by phildeg31** [comment] 2021-02-09 15:23
With the old mod version from 4th February it works. 

@GlitchedYT Why don't you search the update that created that bug to correct the problem because it worked fine before?

**Comment by GlitchedYT** [comment] 2021-02-09 15:29
What's your discord username

**Comment by phildeg31** [comment] 2021-02-09 15:35
phildeg31#1453

**Comment by DFWSupertrooper** [comment] 2021-02-09 18:12
I'm using the Custom FBW and my issues all occur on descent/approach.  No approaches work at the moment except manual.  The A/C simply continues on track ahead despite locking onto LOC in APPR mode, or often activating the APPR button causes the immediate turn away from the airport/FPL resulting in continuous circling.  Sometimes the A/C simply goes to another waypoint that exists in the IRL chart but not in my MCDU/filed FPL.  Sometimes it just starts turning toward RWY as before.  It is just not working with no pattern to how or why from my observations.  Every single flight over last few days has some version of approach failure.

**Comment by Benjozork** [comment] 2021-02-09 18:31
A PR was merged a few hours ago that solves a lot of flight plan / AP issues related to the performance fixes.

**Comment by DFWSupertrooper** [comment] 2021-02-10 03:31
The fix did help some.  I was able to fly a route and intercept ILS for a landing but it wasn't pretty.  The age-old turn to RWY happened (the default bug) and when I DIR TO the next waypoint which was the first ILS approach waypoint incidentally, it went there, but didn't turn to follow the remainder of the route like it used to (even though it was in the MCDU and on the PFD).  Fortunately, just past the point, the LOC caught it and it turned back...I watched and waited, and it locked in and proceeded to the ILS approach.  RNAV would have failed.  But it is a noticeable improvement over the random turning from the last few days.  Thx!

**Comment by phildeg31** [comment] 2021-02-14 17:24
Hi, sorry I don't have time to test for now with work and family (children). I will try to test it next week-end.

**Comment by Road-to-Hell9** [comment] 2021-02-14 18:39
I still encounter the bug, it got better but the autopilot still ignores the Flight director on some occasions, about every 5-10 minutes. To correct it I have to manually get close to the indicated cross form the FD and it then catches back on.

**Comment by aguther** [comment] 2021-02-18 23:02
As it is stated in the docs of the custom FBW version the misbehavior of the FD in manual flight is a known issue and the main reason it does not get merged into master yet. While it seems to work when AP is enabled, we cannot rule out any side effects as well (no one expected that the fly-by-wire system has an impact on the FD).

The only way we can fix the FD is by providing our own input to it, coming with the custom Autopilot system,

**Closed** 2021-04-23 22:05 UTC
Labels: Autopilot, Bug, Fixed in custom AP
