### ISSUE TITLE
[BUG] Active waypoint doesn't show again when switching back ND from ROSE VOR to ROSE NAV or ARC

### ISSUE THREAD

**Issue by MattPaxtonBel** [flybywiresim/a32nx#1250] opened 2020-10-11 15:20 UTC
**Mod Version**
Last Master Branch
built: 2020-10-09T21:09:20+00:00
ref: refs/heads/master
sha: f58b93e3d5aa8d80df95732811df02c1370a51f1
actor: NathanInnes
event_name: push

**Describe the bug**
Active waypoint doesn't show again when switching ND back from ROSE VOR to ARC.

**To Reproduce**
1. in flight (cruise)
2. select a VOR in the NAV/RAD page
3.Switch ND to ROSE VOR 
4. Switch back ND to ROSE NAV or ARC
5. Observe upper right corner of ND Waypoint and bearing are missing
6. Once active waypoint is reached and next waypoint becomes the active, the waypoint name and bearing come back.

**Expected behavior**
Active waypoint and bearing should be indicated  when switching ND from ROSE VOR back to ROSE NAV or ARC

**Actual behavior**
Active waypoint and bearing disappear  when switching ND from ROSE VOR back to ROSE NAV or ARC

**References**
![image](https://user-images.githubusercontent.com/70769396/95682482-bf4f6580-0be5-11eb-9a2c-e8c7e7e465ad.png)

**Additional context**
Note that on the F/O ND where I didn't change the ND mode, the active waypoint and bearing are still there.

Was this working before/when did the issue start occurring?
No idea

Is this a problem in the vanilla unmodded game?
No idea (didn't check)

Discord username (if different from GitHub): Matt_paxton

**Comment by Watsi01** [comment] 2020-10-11 20:22
Can confirm that.

**Comment by 2hwk** [comment] 2020-10-13 13:47
Possible duplicate of #1071

**Closed** 2020-10-14 01:16 UTC
Labels: Bug, ND (Navigation Display)
