### ISSUE TITLE
[REQUEST] Separate MCDU

### ISSUE THREAD

**Issue by SameerAli18** [flybywiresim/a32nx#2842] opened 2021-01-02 13:38 UTC
**Is your feature request related to a problem? Please describe.**
I can never remember the metar so I'm always flicking back to the received messages to look at the metar.

**Describe the feature you'd like to see implemented**
Separating the MCDU's. Allowing for the F/O MCDU to be used separately. For example having the FMGC on the Captains MCDU and having the ATSU on the F/O MCDU.

**References**
Non

**Additional context**
Non.

Discord username (if different from GitHub):
Sameer Ali#4139

**Comment by Benjozork** [comment] 2021-01-02 16:36
Duplicate of #1058

**Closed by Benjozork** 2021-01-02 16:36 UTC
Labels: Enhancement
