### ISSUE TITLE
Auto throttle not disengaging when throttle levers in idle

### ISSUE THREAD

**Issue by juancevel** [flybywiresim/a32nx#2999] opened 2021-01-11 20:45 UTC
**Mod Version**

master

**Describe the bug**

When moving the throttles to MCT or TOGA, the auto thrust is engaged ( this is normal). But when moving the throttles to idle the auto thrust should disengage.

**To Reproduce**

1. Just try on the ground or in flight placing the throttles to MCT or TOGA and then back to idle.
2.
3.

**Expected behavior**

When the auto thrust is engaged, moving the throttle levers to idle it should be disengaged.

**Actual behavior**

Auto thrust is not disengaging

**References**

**Additional context**

Was this working before/when did the issue start occurring?
With the original fs2020 it works as it suppose to.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment] 2021-01-11 21:07
Duplicate of #1047

**Closed by MisterChocker** 2021-01-11 21:07 UTC
Labels: Bug
