### ISSUE TITLE
[BUG] A320 is making like Wonder Woman's Airplane (which is to say transparent).  Happens with both stable and dev versions.

### ISSUE THREAD

**Issue by kmoze2001** [flybywiresim/a32nx#3714] opened 2021-02-25 16:11 UTC
**Mod Version**
  I tried both the stable and the dev release.

{
  "built": "2021-02-09T03:48:40+00:00",
  "ref": "master",
  "sha": "2717c0251ce67363fd4295cb19567255a0183bd1",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**
The aircraft itself is transparent from the interior view.  I did not check the exterior.  Also experienced a CTD when trying to exit to main menu.

**To Reproduce**

1.  Start the sim and select the A32NX, either Stable or Dev.
2.
3.

**Expected behavior**

I expected to be able to see the interior of the cockpit.

**Actual behavior**

The interior of the cockpit was transparent.

**References**

I did not take a screenshot, but can go back and capture one if you think it will be helpful.

**Additional context**

I've had the sim installed for a very long time, but except for stepping into the cockpit once or twice just to see what it looked like, this was going to be my first real effort at flying her.

Was this working before/when did the issue start occurring?

Recently (since WU3?), but that isn't useful information as I haven't really used the mod much to date.

Is this a problem in the vanilla unmodded game?

I have a number of other mods active, but not sure any of them would be considered pertinent.  

Discord username (if different from GitHub):  KevyKevTPA#6583

**Comment by Benjozork** [comment] 2021-02-25 16:29
This is a local issue probably caused by a mod conflict.

Please try removing everything from your Community folder and report back.

**Comment by kmoze2001** [comment] 2021-02-25 17:12
AND...  I solved my own problem.

I disabled the co-pilots mods and, BOOM, the wonder woman imitation is gone.  Guess the co-pilot was actually wonder woman.  Now we know her secret!!

**Comment by kmoze2001** [comment] 2021-02-25 17:13
I'm not closing the issue so that if others are having the same problem, they're probably more likely to see it if it's still open.  I think.  But it can be closed if that's not a concern.

**Comment by hotshotp** [comment] 2021-02-25 17:33
I am closing it because mod conflicts dont count as issues of the aircraft

**Closed** 2021-02-25 17:33 UTC
Labels: Bug
