### ISSUE TITLE
CTD when I try to print ATIS

### ISSUE THREAD

**Issue by doggydogg13** [flybywiresim/a32nx#5819] opened 2021-09-14 13:43 UTC
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-09-13T23:09:35+00:00",
  "ref": "experimental",
  "sha": "19bc202923d3ce1881262c4b227551d3832aed95",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

I was climbing to FL370 from EDDS to LEAL.
I started to request ATIS of LEAL via the MCDU, after getting it I press "print"
Then CTD.

### Expected behavior

The expected behavior is to get the ATIS paper by the printer in the cockpit

### Steps to reproduce

Start a flight using simbreif integration in the MCDU.
For me was EDDS to LEAL (real time / real weather)
After take off, during the climb at 15000ft, try to print the Atis of LEAL if its available.
Then see if it CTD or not

**Comment by Benjozork** [comment] 2021-09-14 13:48
Duplicate of #5429

**Closed by Benjozork** 2021-09-14 13:48 UTC
Labels: Bug
