### ISSUE TITLE
Pilot waypoints

### ISSUE THREAD

**Issue by faker320** [flybywiresim/a32nx#5038] opened 2021-06-07 09:48 UTC
### Aircraft Version

Development

### Description

It seems that the "pilot waypoints" function in the mcdu is not working. Could you please make this function work? I would like to add some personal waypoints to the mcdu.

**Comment by MisterChocker** [comment] 2021-06-07 11:44
Needs #4028, may be part of #4953

**Comment by tracernz** [comment] 2021-06-07 18:08
Needs some way to write files from JS, or to transfer data from JS to WASM, or increased local storage. We would need Microsoft to do one of those first.

**Comment by derl30n** [comment] 2021-10-14 15:00
Duplicate of #1380

**Closed by derl30n** 2021-10-14 15:00 UTC
Labels: Request, FPM, Needs System Implementation
