### ISSUE TITLE
Shaking left to right when increasing sim speed

### ISSUE THREAD

**Issue by YuTookMyJob** [flybywiresim/a32nx#4556] opened 2021-04-24 10:45 UTC
**Aircraft Version**

```json
  "built": "2021-04-23T22:07:54+00:00",
  "ref": "master",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
```

**Describe the bug**

Violent shaking when increasing sim speed.

**To Reproduce**

1. Climb to FL380 with autopilot on.
2. Increase sim speed to 4x.
3. Watch the aircraft shake left to right.

**Expected behavior**

Not to shake left to right.

**Actual behavior**

Shakes left to right.

**References**

https://user-images.githubusercontent.com/72301199/115955920-83c91880-a4f1-11eb-89d4-d6fa9d5ccce8.mp4

**Additional context**

Was this working before/when did the issue start occurring? Bug started with the version mentioned above.

Is this a problem in the vanilla unmodded game? No. Unmodded only has a vertical shake issue after 4x.

Discord username (if different from GitHub): YouTookMyJob#7862

**Comment by MisterChocker** [comment] 2021-04-24 12:04
Duplicate of #1284

**Comment by Benjozork** [comment] 2021-04-24 16:08
@MisterChocker it wouldn't be duplicated because this is for the custom AP and that one isn't

**Comment by aguther** [comment] 2021-04-24 19:17
Duplicate of #4183

**Closed by aguther** 2021-04-24 19:17 UTC
Labels: Bug

**Comment by aguther** [comment] 2021-04-24 19:19
How fast you can go with the sim rate depends on your performance. As long as you're above ~ 17 fps as stated then you're fine.

I was able to use 4x with my 60 fps without issues.
