### ISSUE TITLE
allow users to select waypoints and go direct to them 

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#12] opened 2020-08-23 18:21 UTC

**Comment by arvinjarvin** [comment] 2020-08-26 22:59
In progress.

Thanks for bringing this to our attention.

This will likely be rolled out with the CDU update.

**Comment by AdenFlorian** [comment] 2020-09-04 03:41
@arvinjarvin any updates?

**Comment by AdenFlorian** [comment] 2020-09-04 03:51
Does this issue exist in the vanilla unmodded game, or was it caused by the mod?

**Comment by Zyonix007** [comment] 2020-09-04 04:49
No it's a feature request

**Comment by lousybyte** [comment] 2020-10-28 12:16
Closing since no description provided and I assume is a duplicate of #1150.

**Closed by lousybyte** 2020-10-28 12:16 UTC
Labels: Autopilot, Enhancement, Good First Issue, MCDU
