### ISSUE TITLE
Single engine taxy - inverted throttle

### ISSUE THREAD

**Issue by shezan74** [flybywiresim/a32nx#3089] opened 2021-01-17 20:47 UTC
**Mod Version**
master

**Describe the bug**

Taxiing with single engine after landing (#1 shut down, #2 running). Moving lever of engine 1 (the one that has been shut down) will raise the bug in the panel on engine 1, and the ENGINE 2 is spooling up (noise and thrust). Moving lever of engine 2 (the running one) will raise the bug in the panel on engine 2 but nothing happens (like it's acting on engine 1)

**To Reproduce**

1. Land or shut down engine 1 after having both running
2. Raise thrust on lever 1. You will notice the triangle will move on engine 1 BUT engine 2 is raising power
3. Do the same with lever 2 (the running engine). You will notice the triangle move in engine 2 BUT no rising power

**Expected behavior**

Engine 1 lever will raise engine 1 power, and vice versa

**Actual behavior**

Inverted, but bugs on top MFD are moving correctly (the triangle is moving along the arc of the right engine, but it's the other one that spools up)

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2021-01-17 20:48
Duplicate of #1970

**Closed by Benjozork** 2021-01-17 20:48 UTC
Labels: Bug
