### ISSUE TITLE
Clock chronometer resets if weather changed in flight

### ISSUE THREAD

**Issue by Ash624** [flybywiresim/a32nx#1579] opened 2020-10-28 12:36 UTC
**Mod Version**
master
built: 2020-10-27T16:38:33+00:00
ref: refs/heads/master
sha: 8b84f1858c8bdae46df6082f8828dc195a293754
actor: Benjozork
event_name: push

**Describe the bug**
Clock chronometer resets to zero if weather pre-sets changed in flight 

**To Reproduce**

1.Start chronometer on departure
2.Mid flight, change the weather (cloud types, rain, wind etc) This done to be more realistic for the areas flown to/from etc
3. Use MSFS weather pre-sets within the sim (rain, cloud types etc)

**Expected behavior**
 Chronometer not to reset due to weather changes

**Actual behavior**
 Chronometer resets back to zero. This does not seem to happen if the weather isn't amended en-route

**References**

**Additional context**

Was this working before/when did the issue start occurring? Been happening for a time, including previous versions

Is this a problem in the vanilla unmodded game? No, Vanilla doesn't have a working chronometer

Discord username (if different from GitHub):

**Comment by lousybyte** [comment] 2020-10-28 12:44
It's not a problem with the chrono, when you set the new weather, the game also sets the time that you configured there.

**Comment by Snapmatics** [comment] 2020-10-28 13:05
That is hard to be fixed. However, in real life, you can't change the time.

**Comment by RiderKickingMarco** [comment] 2020-10-28 14:21
In real life, you can't change the weather either. Therefore, this is not a big issue. To keep the realism, refrain yourself from changing the weather and stick with live weather setting for the whole flying session.

**Comment by Ash624** [comment] 2020-10-28 14:30
That’s fine thanks, will do. It wasn’t a complaint, the A32nx is amazing, and all thanks to some very talented and devoted volunteers. I don’t change the time in flight, just the weather. Taking off from the UK in “drizzle” and heading south would normally “in real life” improve the weather, it often doesn’t, so I make it “sunny” etc. I find live weather doesn’t reflect real weather, but that’s MSFS.

Thanks again to all the FBW developers, whoever you are. Brilliant job.

**Comment by 2hwk** [comment] 2021-06-21 02:43
Closing as this is not a bug

**Closed by 2hwk** 2021-06-21 02:43 UTC
Labels: Asobo Bug, Bug
