### ISSUE TITLE
Walkable cabin

### ISSUE THREAD

**Issue by DomWin02** [flybywiresim/a32nx#5645] opened 2021-08-13 20:51 UTC
### Aircraft Version

Development

### Description

A Walkable cabin would be nice

### References (optional)

CS 777 -> https://www.simflight.de/wp-content/uploads/2021/05/2021-05-18_CS777-3.jpg

### Discord Username (optional)

DomenicHAJ#0457

**Comment by Benjozork** [comment] 2021-08-13 20:52
Duplicate of #2577

**Closed by Benjozork** 2021-08-13 20:52 UTC
Labels: Enhancement
