### ISSUE TITLE
[BUG] custom livery not working 

### ISSUE THREAD

**Issue by ducky3333** [flybywiresim/a32nx#815] opened 2020-09-23 00:57 UTC
**Mod Version**

lastest master version

**Describe the bug**

if i select the custom livery, if i  EXT PWR to on , all panal not working
default livery had worked fully 

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Discord username (if different from [GitHub):]([url](url
![수정됨_Microsoft Flight Simulator Screenshot 2020 09 05 - 09 46 35 77](https://user-images.githubusercontent.com/38446386/93952051-df2c0000-fd82-11ea-8d52-76bfafc59f12.jpg)

))

**Comment by NathanInnes** [comment] 2020-09-23 02:43
I fly custom liveries all the time and have never had this issue, check to see if you might have misplaced something

**Comment by AdenFlorian** [comment] 2020-09-23 05:07
@ducky3333 the panel appears to be working in your screenshot, what exactly isn't working? Could you be talking about #718 ?

**Comment by ducky3333** [comment] 2020-09-23 10:17
> I fly custom liveries all the time and have never had this issue, check to see if you might have misplaced something

https://youtu.be/iGuYZX6vpc0
here is video. i think this way is faster than my explaining.

**Comment by aboodilatif** [comment] 2020-09-23 11:12
Could you try it with another livery that is known to work? As the issue is most likely related to the livery itself. 
Is this "Peach Aviation" livery available to download or have you made it yourself? If its one you made yourself, please check your texture.cfg and aircraft.cfg in the livery folder and make sure they match an already existing livery folder structure

**Comment by ducky3333** [comment] 2020-09-24 01:04
> @ducky3333 Could you try it with another livery that is known to work? As the issue is most likely related to the livery itself.
> Is this "Peach Aviation" livery available to download or have you made it yourself? If its one you made yourself, please check your texture.cfg and aircraft.cfg in the livery folder and make sure they match an already existing livery folder structure

i got it from twitter. it is not livery

**Comment by Striezelr** [comment] 2020-09-24 16:38
Hello,
that has nothing to do with liveries...  its with GAYA Simulation Sceneries (Partner of ORBX).. all is off, no response on the ext power knob

**Comment by Striezelr** [comment] 2020-09-24 16:39
And a few other Sceneries, must depend/interfere with one file... same issue withe Lissabon citypack freeware scenery

**Comment by messer79** [comment] 2020-09-25 18:00
I have the same issue. The battery- pumps- adirs-, etc. buttons don't illuminate. There is only EXT PWR that I can toggle from AVAIL to ON and back, but it behaves as a dummy button.
When I switch the battery buttons only the tooltips toggle "Turn battery 1 master on" / "Turn battery 1 master off".
Avionics stay blind all the time.

The problem occurs very often. I tested it with custom liveriers (V8-megapack) and a default one.

**Comment by Fabio93103** [comment] 2020-09-25 18:20
Hi everyone,
I think is somehow related to the spawn location, i tried a gate in Turin Airport (LIMF) and batteries didn't turned on, restarted multiple times, no luck. Then I spawned in a gate at Genova Airport (LIMJ) and it worked just fine.

**Comment by messer79** [comment] 2020-09-25 18:46
I have tested different locations. Now i keep spawning in EPWA (Warsaw Okecie). I still cannot find out what is responsible for the issue.

Moreover, sometimes during the flight all the power goes down and switches become unclickable.

I have also noticed that some panels get fully black (not dark) when they are observed from appropriate angles. And when you change the angle with your mouse they become functional again.

**Comment by Fabio93103** [comment] 2020-09-25 19:13
I think the issue that you're talking about in the last sentence affects the whole simulator when it comes to use buttons and functions that are on the edge of the screen, i think the problem here lies in the fact that the simulator only consider buttons/levers/knobs that are located in a panel completely inside the viewport, in the same way it handles graphics, with screen space ambient occlusion and screen space reflections, but I may be completely wrong about it.
I also had the problem of sudden shutdown of the airplane systems, including the engines, takiing out and throttling back to idle.

**Comment by DaBeLG** [comment] 2020-09-25 20:29
have same issue has to do with panel state starting flight at runway works 

maybe tutorial of proper plane cleanup ? going to right panel state

what do you guys do to shutdown the plane ?

**Comment by messer79** [comment] 2020-09-25 22:43
After I had landed and taxied to the ramp I started the APU and - if I recall correctly - I pressed the Ext Pwr btn which was stating AVAIL. I didn't turn off the engines. After a while the plane shut down. I was unable to start it over without respawning.

I think I'll start recording my flights. I believe that videos will explain developers more.

**Comment by DaBeLG** [comment] 2020-09-26 07:07
Ok did 2 flights yesterday from same gate that didn’t work before .

Used the infinite batt. Power in fsuipc 7 beta = batt power 0 think it is something with power not available on loading flight it happens on ground services available airport not on others !

Regards

**Comment by messer79** [comment] 2020-09-26 10:12
This time the plane shuts down just after the logbook is closed. See this video: https://youtu.be/BM-VcV0NhF8
Notice the battery buttons behavior.
No key shortcuts were used.

**Comment by DaBeLG** [comment] 2020-09-26 14:02
So it’s the plane state when flight finish pops up !!!! Mmmm

**Comment by ducky3333** [comment] 2020-09-26 15:31
hi guys. this issue was fixed on 0.3.0

**Comment by NathanInnes** [comment] 2020-09-26 15:38
Closing issue as it's stated to be resolved.

**Closed by NathanInnes** 2020-09-26 15:38 UTC
Labels: bug
