### ISSUE TITLE
On the ND, the names of the waypoints along the flight path are not very readable.

### ISSUE THREAD

**Issue by PatriceCesson** [flybywiresim/a32nx#4331] opened 2021-04-07 13:47 UTC
**Mod Version**
Experimental FBW
{
  "built": "2021-04-06T22:27:05+00:00",
  "ref": "autopilot",
  "sha": "6f4c662108945d72932d9f277c228c4a47703de7",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
The names (in green) of the waypoints in the ND along the flight path are not very readable. 
See screenshots below.

**To Reproduce**
1. Start a flight with a flight plan.
2. Check the names of the waypoints: they are not very readable.

**Expected behavior**
The names of the waypoints shall be clear, very easy to read.

**Actual behavior**
See above.

**References**
Some screenshots:

A detached large window of the ND:
![snap053](https://user-images.githubusercontent.com/30781354/113875521-23c73800-97b7-11eb-9b69-7adc338a3f6d.png)

The ND in its context:
![snap054](https://user-images.githubusercontent.com/30781354/113876172-c54e8980-97b7-11eb-895f-d0f76cf4a359.png)

My screen resolution is 2560*1440 native. with scaling 100%

**Additional context**

Was this working before/when did the issue start occurring?
I think this issue was here some time ago.

Is this a problem in the vanilla unmodded game?
Don't use the vanilla.

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment] 2021-04-07 14:11
Looks like a Duplicate of #1730

**Closed by MisterChocker** 2021-04-07 14:11 UTC
Labels: Bug

**Comment by PatriceCesson** [comment] 2021-04-07 14:26
Ok. Thank you. I have searched but probavly with the same terms.

**Comment by MisterChocker** [comment] 2021-04-07 14:50
Np, sometimes it hard to find issues with the github search. I recommend using the label filter when searching for a specific system or du issue.
I've changed the title to be more intuitive.
