### ISSUE TITLE
[BUG] TAKEOFF CONFIG FLAPS 3 NOT RECOGNIZED

### ISSUE THREAD

**Issue by rafaelmm12** [flybywiresim/a32nx#1770] opened 2020-11-05 14:55 UTC
**Mod Version**
DEV
built: 2020-11-05T22:51:26+00:00
ref: refs/heads/master
sha: 511df5a3fe939426019353ab6a3399f180a82148
actor: wpine215
event_name: push

**Describe the bug**
Upon testing takeoff config and/or trying to takeoff with flaps 3 setting (standard procedure for certain airports, like SBSP and SBRJ), the ECAM shows the FLAPS NOT IN T.O. CONFIG message and the MASTER WARNING HORN will sound , even though the performance page was set to flaps 3 takeoff config.

**To Reproduce**
1-Set FLAPS 3 for takeoff on the MCDU PERF page
2-Select FLAPS 3 and confirm they are in position
3-Press T.O. CONFIG TEST button or start takeoff roll, any of these will be enough to reproduce it.

**Expected behavior**
ECAM MEMO no blue, both T.O. CONFIG TEST and FLAPS should be green.
No horn during takeoff.

**Actual behavior**
ECAM MEMO RED FLAPS NOT IN T.O. CONFIG
MASTER WARNING HORN after T.O. CONFIG TEST and during takeoff roll.

**References**
Proof that config 3 is used: https://youtu.be/TSu8Aqw4f10?t=27 Check the ECAM at 0:30

Was this working before/when did the issue start occurring?
Never worked.

Is this a problem in the vanilla unmodded game?
Might be.

Discord username: Rafe#8824

**Comment by Benjozork** [comment] 2020-11-05 21:59
Please provide the version of the mod you are using as indicated by the template.

**Comment by rafaelmm12** [comment] 2020-11-05 23:01
> Please provide the version of the mod you are using as indicated by the template.

As said before, it happens on all versions. Accordingly to your request, I've updated the post saying I'm using the Dev build.

**Comment by Benjozork** [comment] 2020-11-06 02:23
If you are using the dev version, please send the contents of `build-info.txt`, as stated in the template. This ensures we can reproduce your bug correctly.

We don't ask for this information to be annoying. We need it for reproduction.

**Comment by rafaelmm12** [comment] 2020-11-06 02:44
Done. I've also collected some more info, it appears that the MCDU only recognizes flaps 1 and 2 for takeoff config, even when flaps 3 is set on the PERF page. With flaps 3 set on PERF and flaps 3 set and checked for takeoff, by pressing the T.O. CONFIG TEST button and/or setting thrust for takeoff it will display the red ECAM memo FLAPS NOT IN T.O. CONFIG and sound the MASTER WARNING HORN. If you then, set flaps 2 and check they are in place (without changing the flaps 3 config on the MCDU PERF page) and try the config test/takeoff roll again, it wont sound the horn or display the red memo on the ECAM. So it appears that even when you set the flaps 3 config on the MCDU, the aircraft logic understands it as flaps 2.

**Comment by Benjozork** [comment] 2020-11-07 06:07
Thank you, will look into it.

**Comment by paul92ilm** [comment] 2020-11-07 23:45
#1569 Looks similar

**Comment by rafaelmm12** [comment] 2020-11-08 01:48
Thanks for mentioning the other thread, I didn't find anything similar when I posted the issue :/ (my bad). From what I read there it's the same issue with the additional info I provided during the takeoff roll. They had the Master Warning horn sounding and the red ECAM memo (even though the exact message wasn't mentioned) as well. 

The one thing they said that I didn't quite manage to replicate was this: "𝑰 𝒄𝒍𝒆𝒂𝒓𝒆𝒅 𝒕𝒉𝒆 𝒊𝒔𝒔𝒖𝒆 (𝒘𝒐𝒓𝒌𝒂𝒓𝒐𝒖𝒏𝒅) 𝒃𝒚 𝒔𝒆𝒍𝒆𝒄𝒕𝒊𝒏𝒈 𝑭𝒍𝒂𝒑 2 𝒘𝒊𝒕𝒉 𝒕𝒉𝒆 𝒄𝒐𝒏𝒇𝒊𝒈 𝒘𝒂𝒓𝒏𝒊𝒏𝒈 𝒅𝒊𝒔𝒑𝒍𝒂𝒚𝒆𝒅, 𝒓𝒆𝒕𝒆𝒔𝒕𝒆𝒅 𝑻𝑶 𝑪𝒐𝒏𝒇𝒊𝒈 𝒕𝒐 𝒄𝒍𝒆𝒂𝒓 𝒕𝒉𝒆 𝒎𝒆𝒔𝒔𝒂𝒈𝒆 𝒂𝒔 𝒊𝒕 𝒂𝒄𝒄𝒆𝒑𝒕𝒆𝒅 𝑭2 - 𝒕𝒉𝒆𝒏 𝒓𝒆𝒔𝒆𝒍𝒆𝒄𝒕𝒆𝒅 𝑭3 𝒂𝒇𝒕𝒆𝒓𝒘𝒂𝒓𝒅𝒔." When I tried it, the plane would still recognize that I changed it back to flaps 3 (expected behaviour), declaring wrong takeoff configuration (red memo and horn). I tried it with the same dev build from my post, haven't tested it in stable yet (which, apparently, it's the build they used).

**Comment by EDZET9428** [comment] 2020-12-15 18:30
I had this issue last weekend whilst preparing for take off at Gatwick with a heavy payload and SID that required a tight right hand turn. I wanted to keep the speed down to make the turn, so I selected Flaps 3 as set in Perf page of MCDU.  flaps not in TO configuration warning came up and Master Caution lit and horn sounded. I was running the 5th Dec Dev master build version.

**Comment by MisterChocker** [comment] 2020-12-31 05:48
duplicate of #1569

**Closed by MisterChocker** 2020-12-31 05:48 UTC
Labels: Bug, ECAM
