### ISSUE TITLE
[BUG] Name of some waypoint is not well displayed in ND

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#1870] opened 2020-11-12 04:30 UTC
**Mod Version**

Current master 

**Describe the bug**

The waypoint named D186R is not well displayed on ND but correct on MCDU

**To Reproduce**

1. Use an fplan with long name for waypoint
2.
3.

**Expected behavior**

Correct display on ND

**Actual behavior**

Sometime name is not readable

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
![2020-11-11 (8)](https://user-images.githubusercontent.com/5894146/98895916-1cba2900-24a8-11eb-89a3-12739879a941.png)
![2020-11-11 (9)](https://user-images.githubusercontent.com/5894146/98895918-1fb51980-24a8-11eb-943b-64c1fd190a3d.png)

**Comment by lars-reimann** [comment] 2020-11-12 13:58
I guess you are talking about the ND (navigation display), i. e. the display on the right, rather than the PFD:

![nd](https://user-images.githubusercontent.com/2501322/98948704-13a47880-24f7-11eb-8a5a-593045f85836.png)

This does not seem to be an issue with long names but just two labels that are displayed on top of each other. As you can see on the MCDU the waypoints D186R and R302 seem to be 0nm apart:

![mcdu](https://user-images.githubusercontent.com/2501322/98948916-59614100-24f7-11eb-83a3-b4c5a1ba2dc5.png)

This could still be a bug but the cause is different from what you described.

**Comment by JLD95** [comment] 2020-11-12 14:10
thank you for clarification, I edit the title of this issue.

**Comment by lousybyte** [comment] 2020-11-12 16:26
Seems like just bad nav data, if you can post the exact route maybe someone with Navigraph can check it out.

**Comment by JLD95** [comment] 2020-11-12 18:50
I have the latest Navigraph data and the flight plan is maded with SimBrief with the same Airac.Le 12 nov. 2020 17:26, lousybyte <notifications@github.com> a écrit :
Seems like just bad nav data, if you can post the exact route maybe someone with Navigraph can check it out.

**Comment by JLD95** [comment] 2020-11-12 18:56
I put IVAO flight plan and tomorrow I will add the fs2020 version.
[20201111_1525_AFR95_LEMD_GMMN.fpl.txt](https://github.com/flybywiresim/a32nx/files/5532645/20201111_1525_AFR95_LEMD_GMMN.fpl.txt)

**Comment by JLD95** [comment] 2020-11-13 04:48
Hi, here the original flight plane used by MSFS2020

[LEMDGMMN_MFS_11Nov20.zip](https://github.com/flybywiresim/a32nx/files/5534794/LEMDGMMN_MFS_11Nov20.zip)

**Comment by JLD95** [comment] 2020-11-13 04:49
My Nav data is AIRAC Cycle 2012 rev.1

**Comment by JLD95** [comment] 2020-11-13 10:10
Another example this morning during flight between CYVR and KHLN: R352 is at 0 nm of CUSDA
![2020-11-13 (6)](https://user-images.githubusercontent.com/5894146/99060737-c54bb400-25a0-11eb-9715-39b63d51c249.jpg)

**Comment by JLD95** [comment] 2020-11-13 10:11
and the used flight plan : 
[CYVRKHLN_MFS_13Nov20.zip](https://github.com/flybywiresim/a32nx/files/5536122/CYVRKHLN_MFS_13Nov20.zip)

**Comment by Oberstumfuher** [comment] 2020-11-13 12:33
> My Nav data is AIRAC Cycle 2012 rev.1

It's just that you're forgetting that the Navgraph Airac for the MSFS2020 is BETA.

**Comment by JLD95** [comment] 2020-11-13 13:12
Navigraph is in beta test but where is the problem, the support is very responsive. For many flights (>50), nav data was accurate

**Comment by Oberstumfuher** [comment] 2020-11-13 13:29
> Navigraph is in beta test but where is the problem, the support is very responsive. For many flights (>50), nav data was accurate

After the last MSFS update, was there a Navigraph update? that could be it, things changed in FS, Assobo, and it may not work right now with Navigraph, understand?

**Comment by lousybyte** [comment] 2020-11-13 15:37
Checked and it's similar for the default game nav data as well, the waypoints are just super close to each other. Don't know if this is true to life but we can't really control the approach waypoints at this moment. 
The main problem with this tho is the overlapping text, which as mentioned, there's already an opened issue about it #1731.

**Comment by Benjozork** [comment] 2020-11-15 03:07
Duplicate of #1731

**Closed by Benjozork** 2020-11-15 03:07 UTC
Labels: Bug, PFD
