### ISSUE TITLE
Periodic stuttering/pause every 5 seconds in flight with A32NX experimental

### ISSUE THREAD

**Issue by PatriceCesson** [flybywiresim/a32nx#4592] opened 2021-04-25 20:24 UTC
**Aircraft Version**
{
  "built": "2021-04-23T22:37:56+00:00",
  "ref": "experimental",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
In flight I am facing regular stuttering every 5 seconds: The display stops a very little time and restarts. 
This at a regular period of 5 seconds.

**To Reproduce**

1. I start MSFS, choose the FBW (experimental) A320NX and load a FP from the FP folder (but a FP is not necessary)
2. Load the SIM, prepare the plane and take off.
3. As soon as I am in the air, using the drone to follow the plane, a regular stutter occurs every 5 seconds period and this is continuous. 
What happans: The display is Ok smooth during 5 seconds, 
then a small pause occurs in the display (perhaps 1/10 or 2/10 second duration) and 
after this pause/stutter the display continues smooth again regularly until the next pause/stutter 5 seconds later.
3. I use CapframeX tool to check the behaviour and we can clearly see in the fps diagram these pauses every 5 seconds that impact the fps regularity (regular drops in fps)..

**Expected behavior**
No such pauses/stutters, we need a smooth display with no stutters/pauses.

**Actual behavior**
See above.

**References**
N/A

**Additional context**

My configuration:
W10 pro on an M2 SSD
MB Asus Maximus hero x, Intel core i7-9700K at 5 Ghz, 32 GB RAM, 
MSFS on a dedicated M2 SSD, Scenery on another SATA SSD
GC MSI RTX 2080 8GB VRAM
Scenery: Brittany around Rennes city and the north coast.
Current FPS when testing: 40 FPS. Despeite this FPS value, the issue with the pauses bring stutters every 5 seconds.

Was this working before/when did the issue start occurring?
I think this is present till a long time ago.

Is this a problem in the vanilla unmodded game?
I do not fly the unmodded A320.
What I can say is that these pauses do not occur when using the GA C172 and GA C172-G1000 planes on the same scenery (and above Rennes, a big city, there is no pauses/stutters alos).

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2021-04-25 21:02
Disable MSFS multiplayer

**Comment by Benjozork** [comment] 2021-04-25 21:03
Known issue since world update 4 not related to the plane

**Comment by PatriceCesson** [comment] 2021-04-25 22:32
I do not use multiplayer

**Comment by Benjozork** [comment] 2021-04-25 22:35
Can you show a screenshot of the MSFS DevMode FPS counter showing the pauses ?

> And also no problems with c172 planes.

FYI this is not relevant to whether or not it's a sim problem. The interactions between the sim and the plane are more complex than that.

**Comment by PatriceCesson** [comment] 2021-04-25 22:56
I cannot give such a screenshot as these pauses are very short but I will give you a copy of the fps measures by capframex this morning.

**Comment by CptBayer** [comment] 2021-04-26 11:39
I have stutters as well. The reason is always a flightplan with errors inside .... This Error is most of the time a drawed green line, which is not part of the programmed flighplan. I have no idea what the reasons are for that wrong route drawing on the ND. Flying the bus without flightplan is excellent at the moment! Nearly no stutters. Only few micro ones ...

Greets Klaus

**Comment by PatriceCesson** [comment] 2021-04-26 12:22
I can see this even when no FP is loaded.

**Comment by Benjozork** [comment] 2021-04-26 13:59
Do you not see these pauses in the MSFS DevMode FPS counter ?

It is the only info the can be of use to us.

As a side note, you should not be using the experimental version anymore. As we announced, the dev version now has all its features.

On the good side, the new flight plan manager which is gonna become the new experimental version in a bit already has less stuttering.

**Comment by PatriceCesson** [comment] 2021-04-26 16:05
Yes I understand, but these pauses are extremely short: When I fly with the drone beside the plane, these pause show like the display stops suddenly moving a very short moment and restarts as if nothing happened.
I will try to check what I can do with the developer mode counters, but these are very dynamic and fast.

**Comment by repools** [comment] 2021-04-26 17:17
Just to add to this; i'm having the same problem on the dev version as well. I've removed all mods, old liveries and reinstalled the FBW mod again. Same problem as described by the OP. The pauses are sudden enough to completely mess up the camera, but never long enough to capture the dip.

**Comment by Benjozork** [comment] 2021-04-26 17:26
Some rough analysis of your screenshot shows a long pause on either `Manipulators` or `MainThread` causing the other to freeze as well:

![image](https://user-images.githubusercontent.com/4503241/116124917-e4438b80-a692-11eb-9e64-c1e3399ef94c.png)

There is no visible impact on CoherentGTDraw, which is what any A32NX code causing lag would have an effect.

Keep in mind reduced performance is an official known issue listed by Microsoft.

**Comment by Benjozork** [comment] 2021-04-26 17:28
@repools is multiplayer disabled for you ?

**Comment by repools** [comment] 2021-04-26 17:30
It's not, I forgot to test that on the dev version. I just gave the stable a test and no issues at all.

Screenshot from stable: https://i.imgur.com/LU37oyC.png

I'll redownload the dev, disable MP and give it a go.

**Comment by repools** [comment] 2021-04-26 17:38
Ok, did that, and it seems to have mostly fixed it. I hope that also helps.
![2021-04-26 13_33_54-Window](https://user-images.githubusercontent.com/83239176/116126393-9a5ba500-a694-11eb-9f36-e4bf8c36944a.png)

![2021-04-26 13_35_49-Window](https://user-images.githubusercontent.com/83239176/116126423-9fb8ef80-a694-11eb-9645-d499cc3f58a8.png)

This is dev version with MP disabled. May stick with stable for the first time since FBW had no name..

**Comment by Benjozork** [comment] 2021-04-26 17:41
The problem specifically occurs when MSFS loads multiplayer users for aircraft that use a livery you do not have installed. It seems to only affect certain aircraft, the criteria for that is not known yet.

**Comment by repools** [comment] 2021-04-26 17:42
I appreciate your help with it. It's unfortunate, but a workaround exists and that's a big plus.

**Comment by PatriceCesson** [comment] 2021-04-26 21:11
My problem is related to the experimental version and I never activate the multiplayer feature.
I will try tomorrow with the development version and check if I see the problem also in this version.

**Comment by repools** [comment] 2021-04-26 22:13
@PatriceCesson I was using the experimental before posting, I installed the dev then posted after seeing the same results. I've never used the stable before, but I was seeing the same thing on both exp and dev until MP was disabled. I know not all workarounds work for everyone, but I wanted to clarify that I was originally on the same one as you.

**Comment by PatriceCesson** [comment] 2021-04-27 16:22
So, after 2 tests with the dev version, my thinking is a bit mixed. 
The dev version seems less prone to this phenomenon. 
When stutters occur, it seems that CoherentGTDraw and mainthread are the problem.
Here are some curves from CapFrameX
Cockpit preparation:
![snap074](https://user-images.githubusercontent.com/30781354/116274556-13d1c100-a783-11eb-9cc8-1f8f3aa45467.png)
Takeoff (Cockpit 0 50, Drone 51-85, Cockpit 85-100)
![snap075](https://user-images.githubusercontent.com/30781354/116274795-467bb980-a783-11eb-9f16-05a34d98c135.png)
After take off (mix cockpit and drone)
![snap076](https://user-images.githubusercontent.com/30781354/116274885-5bf0e380-a783-11eb-8012-63a3eb6b109e.png)
During climb Drone view
![snap077](https://user-images.githubusercontent.com/30781354/116274968-6f9c4a00-a783-11eb-98c9-0064323c1649.png)

Below some images from the FPS counter of the dev mode (not related to the above, just some examples):
![snap072](https://user-images.githubusercontent.com/30781354/116276892-3d8be780-a785-11eb-996e-04fb9683b5de.png)
![snap071](https://user-images.githubusercontent.com/30781354/116276894-3e247e00-a785-11eb-9bda-b1a196b0337d.png)
![snap070](https://user-images.githubusercontent.com/30781354/116276896-3e247e00-a785-11eb-8866-c13cc9f0da77.png)
![snap069](https://user-images.githubusercontent.com/30781354/116276897-3ebd1480-a785-11eb-9a33-98e3b068d903.png)
![snap068](https://user-images.githubusercontent.com/30781354/116276898-3ebd1480-a785-11eb-9eea-781af94b5184.png)
![snap067](https://user-images.githubusercontent.com/30781354/116276900-3f55ab00-a785-11eb-9fb5-96b9ba714ef9.png)
![snap066](https://user-images.githubusercontent.com/30781354/116276902-3f55ab00-a785-11eb-8489-bbff6df450c7.png)
![snap065](https://user-images.githubusercontent.com/30781354/116276904-3f55ab00-a785-11eb-918b-62c37792f881.png)
![snap064](https://user-images.githubusercontent.com/30781354/116276907-3fee4180-a785-11eb-9faa-8a2df120cdce.png)

We can see that CoherentGTDraw and MainThread are the processes causing the most stutters;

**Comment by aguther** [comment] 2021-05-07 06:49
Is the issue still exiting after the latest hotfix?

**Comment by PatriceCesson** [comment] 2021-05-07 07:26
The problem is less appearing with the latest dev version.

**Comment by SierraBravo1** [comment] 2021-05-10 17:19
Stuttering by CoherentGT were also discussed here (some days ago): https://github.com/flybywiresim/a32nx/issues/4051#
The issue is still existing.

**Comment by Benjozork** [comment] 2021-05-10 17:27
This issue thread was strictly about the livery stuttering bug which is fixed since the MSFS hotfix, and not general performance / stuttering.

Closing accordingly. Please use #4051 for the aforementionned.

**Closed by Benjozork** 2021-05-10 17:27 UTC
Labels: Bug, Performance
