### ISSUE TITLE
[BUG] ND - double labeling of waypoints

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#3801] opened 2021-03-04 14:01 UTC
**Mod Version**
  "built": "2021-03-03T10:34:40+00:00",
  "ref": "master",
  "sha": "7bb51ec902b0485299f2b59e5177ed86ce3c2263",
  "actor": "beheh",
  "event_name": "manual"

**Describe the bug**
The labels for waypoints on the ND are doubled. Happens not on every flight, but most of them.

**To Reproduce**

1. Start a normal flight (with flightplan)
2. During flight, check labeling of waypoints on the ND

**Expected behavior**
One WP, one label.

**Actual behavior**
see above and below

**References**
![double_letters](https://user-images.githubusercontent.com/72334392/109974838-42d73380-7cfa-11eb-9bb0-3ae28200e72e.jpg)

**Additional context**
I'm using Navigraph AIRAC for MSFS (happens also without it)

Was this working before/when did the issue start occurring?
No idea. Issue exists for a couple of dev versions now.

Discord username (if different from GitHub): RogePete

**Comment by MisterChocker** [comment] 2021-03-05 15:34
Duplicate of #1730

**Closed by MisterChocker** 2021-03-05 15:34 UTC
Labels: Bug, Flight Plan, ND (Navigation Display)
