### ISSUE TITLE
Pixelated screens

### ISSUE THREAD

**Issue by Pushok154** [flybywiresim/a32nx#5459] opened 2021-07-29 14:18 UTC
### Aircraft Version

Development

### Description

Hi, the new pixelated screens feature is awful, i`m a real a320 family pilot, and IRL i`ve never seen pixels on screens, it may be seen if you would look to scren from distance of one centimeter from screen or through the camera but not by human eye from correct position in the cockpit, may be virpils love this feature, but there is no IRL, could you make a toggle in pad options or in MCDU options, to switch on/off this feature, if you need some shots of pfd/nd may take it tomorrow

**Comment by 2hwk** [comment] 2021-07-29 18:00
Duplicate of #5424 closing

**Closed by 2hwk** 2021-07-29 18:00 UTC
Labels: Enhancement
