### ISSUE TITLE
AP  does not follow the vertical constraints at 10000 feet

### ISSUE THREAD

**Issue by Viopassch** [flybywiresim/a32nx#4007] opened 2021-03-16 20:47 UTC
**Mod Version**
{
  "built": "2021-03-16T14:53:58+00:00",
  "ref": "master",
  "sha": "6017aaecba0d2333fb997c0e2debaa4004cbc06a",
  "actor": "myselfaaryan",
  "event_name": "manual"
}

**Describe the bug**
With a managed descend from 13000 feet AP does not follow the horizontal constraint of 10000 feet.
With a horizontal constraint 4000 feet and managed descend to  3000 it works.
Trans Alt 18 000 feet
.

**To Reproduce**
1.  Load a flight plan from LSZH to EDDF
2.  Managed descend from 12000 feet to 5000 feet from Waypoint XORBO to ADNIS 

**Expected behavior**
Decend stops at 10000 feet

**Actual behavior**
Decend goes below 10000 feet

**References**
![image](https://user-images.githubusercontent.com/78740747/111377371-da486900-86a0-11eb-84a7-037350bd181d.png)
![image](https://user-images.githubusercontent.com/78740747/111377402-e3393a80-86a0-11eb-9e93-dec886a524c2.png)

Discord username (if different from GitHub): Viopass

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

**Comment by MisterChocker** [comment] 2021-03-17 00:53
Managed speed target is set so 250kt. What in particular is not working?

**Comment by SirMatze86** [comment] 2021-03-17 09:23
As I can see, the ALT-CSTR is -10000 ft at Waypoint so it means the A/C MUST go under 10000ft. At the next Waypont it says 4000ft so A/C have to stay above 4000ft. There's no problem at all

**Comment by Viopassch** [comment] 2021-03-17 10:45
> rget is set so 250kt. What in particular is not working?

The autopilot should hold the ALT-CSTR of 10,000 like it does it with the ALT-CSTR 4000 later.

**Comment by AirbusA320Pro** [comment] 2021-03-17 10:54
@Viopassch the constraint is -10000 at ADNIS. So, if the aircraft is flying below 10,000ft at waypoint transit, then that is correct. The notation for constraints would be as follows: 

+10000 = Be at/above 10,000ft.
10000 = Be exactly at 10,000ft.
-10000 = Be at/below 10,000ft. 

Other constraints can look something like:
-12000
+10000      meaning the aircraft must transit the waypoint in the 2000ft "window" above 10,000ft and below 12,000ft.

**Comment by SirMatze86** [comment] 2021-03-17 10:58
I guess there's more knowlwdge need. 

An ALT-CSTR says on witch altitude level an A/C have to be on the Waypoint.
There're 2 kinds of ALT-CRST Above (+)or(A) and Below (-)or(B)

For your example ADNIS -10000ft CSTR
That means at this Wayponit you have an altitude-limitiation of Below 10000ft. Your A/C have to stay under 10000ft
no matter if its 9900 or even 4100ft

Your AP is set for 5000ft so it won't collide with the next ALT-CSTR of 4000ft on CHA or what ever that is (picture to small can read it clearly) so your AP keeps Descending to 5000ft.

The A/C behavior is OK

**Comment by pareil6** [comment] 2021-03-17 11:09
Note that the default FPM screws up importing the constraints - all SID constraints are imported as at-or-above (+), all STAR constraints are imported as at-or-below (-) - which is why the plane isn't levelling off in places you'd expect it to based on the chart. If you manually set the constraints to remove the below/above part, it should do what you're expecting.

This is a limitation of the Asobo FPM, and will be fixed with the custom one that is in development.

**Comment by Watsi01** [comment] 2021-03-17 11:41
Regarding my experiences, I'm not sure, if MSFS even understands 'below' constraints at all.

**Comment by MisterChocker** [comment] 2021-03-17 11:43
Okay to clear things up.
There are four types of constraints:
- AT (6000)
- ABOVE (+5000)
- BELOW (-7000)
- BETWEEN (+5000, -7000)

In addition:
During ascent constraints that hold an above restriction are being ignored. For descent vice versa.

If that's the only issue, than the algorithm is working as intended.

**Comment by SirMatze86** [comment] 2021-03-17 11:52
@Watsi01 I don't know if vanilla MSFS understands that. But what I can confirm is that the dev ver. from yesterday and my flight
to LEPA ILS06L STAR with ADX Trans worked proberly

There are some ALT-CSTR on Approachpatch and the A/C stayed at (for example 3000ft) even the ATC foreced me for 1300ft and I set 1300ft. the A320 only began further automatic DES when the CSTR allowed that level between the Points (3000ft actual and 1500ft on next)

**Comment by MisterChocker** [comment] 2021-03-17 12:22
well, if the constraints are in the flight plan, the aircraft will follow them, the algorithm we use follows the fcom and behaves the same as the real one. (except for one minor issue, which can be ignored for now, IRL you can bleed through a constraint which you currently cant, the ap will try to climb again which is wrong.)

**Comment by MisterChocker** [comment] 2021-03-17 12:23
> @Watsi01 I don't know if vanilla MSFS understands that. But what I can confirm is that the dev ver. from yesterday and my flight
> to LEPA ILS06L STAR with ADX Trans worked proberly
> 
> There are some ALT-CSTR on Approachpatch and the A/C stayed at (for example 3000ft) even the ATC foreced me for 1300ft and I set 1300ft. the A320 only began further automatic DES when the CSTR allowed that level between the Points (3000ft actual and 1500ft on next)

you need to use open climb then.

**Comment by SirMatze86** [comment] 2021-03-17 12:30
@MisterChocker Hell NO! :D

There're reasons why they have the constrains ^^ If I had descended to the 1300ft as orderd by ATC then I truly landed the Plane into a Mountain

**Comment by AirbusA320Pro** [comment] 2021-03-17 13:17
@SirMatze86 ATC clearances are different from technical specifications about what the VNAV system does. ATC can clear you under radar control to the MSA (minimum safe altitude) or lower according to radar vectoring minimums. You cannot rely on using managed descent all the time, that's why open descent is available to you. 
If amateur ATC tried to descend you to 1300' into the side of Andraitx, not under proper radar control or within the minimum vectoring segments, then that's them being extra-amateur.

**Comment by MisterChocker** [comment] 2021-03-17 21:43
Closing since working as intended.

**Closed by MisterChocker** 2021-03-17 21:43 UTC
Labels: Bug, Waiting For Response
