### ISSUE TITLE
Pause at TOD

### ISSUE THREAD

**Issue by LH4371** [flybywiresim/a32nx#6682] opened 2022-02-09 12:57 UTC
### Aircraft Version

Experimental

### Description

With the coming VNAV implementation and having seen the TOD marker in a recent exp build (which you pulled again) I would love to see a Pause at TOD option in EFB or MCDU for pilots like me not always able to <caugh caugh> monitor the whole flight. I know, completely unrealistic and thus far away from what you are building here and representing but nonetheless helpful

**Comment by beheh** [comment] 2022-02-09 13:21
Duplicate of #5211

**Closed by beheh** 2022-02-09 13:21 UTC
Labels: Request
