### ISSUE TITLE
APPR MCDU page shows TRANS ALT vice TRANS LVL

### ISSUE THREAD

**Issue by olibarke** [flybywiresim/a32nx#2892] opened 2021-01-05 17:51 UTC
**Mod Version**
{
  "built": "2021-01-05T05:22:58+00:00",
  "ref": "",
  "sha": "",
  "actor": "donstim <70166617+donstim@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**
On the MCDU APPR page the page should show a TRANS LVL line, opposed to TRANS ALT

**To Reproduce**
1. Select MCDU APPR Page

**Expected behavior**
Airbus MCDU APPR page will require a TRANS LVL for descent to remind pilots to set a QNH, the MCDU should auto populate a FL based on the NAV database and be editable by pilots based on correct TRANS LVL for the day.

**Actual behavior**
APPR page shows TRANS ALT instead

**References**
[https://app.photobucket.com/u/olibarke/p/e76d1647-3589-4f7b-a5bc-c3b37be943d5](url)

**Additional context**
Qualified and type rated A330 pilot. Working knowledge of Airbus.

Is this a problem in the vanilla unmodded game? - Yes

Discord username (if different from GitHub): olibarke

**Comment by ThatRedMelon** [comment] 2021-01-05 17:54
The system modelled in A32NX uses TRANS ALT instead of TRANS LVL
![image](https://user-images.githubusercontent.com/34657891/103681127-0055dc80-4f7f-11eb-8ab4-22d2bc5006f4.png)

**Comment by MisterChocker** [comment] 2021-01-05 20:13
@olibarke the transition level is given by ATC, the trans alt is defined by charts.
Closing since this is not a bug.

**Closed by MisterChocker** 2021-01-05 20:13 UTC
Labels: Bug

**Comment by olibarke** [comment] 2021-01-05 21:48
> @olibarke the transition level is given by ATC, the trans alt is defined by charts.
> Closing since this is not a bug.

I understand TL is given by ATC usually via and ATIS, and yes TA is depicted on charts. Some MCDU software modes change the TRANS ALT in the APPR page for TRANS CRZ. As ThatRedMelon has said it is the former MCDU software simulated in this version of the A320.

**Comment by MisterChocker** [comment] 2021-01-05 21:58
> https://app.photobucket.com/u/olibarke/p/88ed2fb8-8fea-4e0b-93b7-27eea10b577d

can access link
