### ISSUE TITLE
[BUG]  When reloading a SAVED flight in-progress, aircraft is loaded with GPS requiring a 9 minute calibration time

### ISSUE THREAD

**Issue by Lepidopterist** [flybywiresim/a32nx#446] opened 2020-09-06 09:17 UTC
**Mod Version**

0.2

**Describe the bug**

Started a flight, and had to save to continue later.  When I reloaded the saved  flight, I was in the air, with all systems turned on, except I had a red notification of GPS Signal Lost (or similar, I don't remember exactly).  There was a warning on the centre console for GPS init with a 9 minute countdown.

**To Reproduce**

see aboove

**Expected behavior**

Save should reload with GPS already initialized, as it's a continuation of a flight.

**Actual behavior**

Save reloads without GPS initialized

**References**

**Additional context**

**Comment by Lepidopterist** [comment] 2020-09-06 09:43
![gps-primary-lost](https://user-images.githubusercontent.com/20169744/92323084-c1923300-f02d-11ea-9d10-3b1b6be24239.jpeg)

**Comment by UncleClapton** [comment] 2020-09-06 11:09
I was unable to reproduce this exact issue on master branch. It may have already been fixed for the latest release.

**Comment by NathanInnes** [comment] 2020-09-21 04:33
Unable to replicate, are you still having this issue?

**Comment by NathanInnes** [comment] 2020-09-21 14:14
In that case I will close this issue, feel free to re open if it happens again.

**Closed by NathanInnes** 2020-09-21 14:14 UTC
Labels: bug
