### ISSUE TITLE
[BUG]Suddenly Cockpit not responsive / Plane does not start up

### ISSUE THREAD

**Issue by Andruh0** [flybywiresim/a32nx#1203] opened 2020-10-08 17:18 UTC
**Mod Version**
Release V0.3.1

**Describe the bug**
The only button available is the external power. When switched on nothing else works. Even the light test (as in the screenshot) shows that it is down. That happened out of a sudden after a successful innereuropean flight. Sim was restarted several times, mod reinstalled, even tried the master (developer version) what lead to the same issue.
When the mod is not installed the default Airbus works. 
The bug does not occur when the plane is started at the holding point ready for departure. It pops up in cold and dark.
(Livery mega pack installed - that has never been an issue)

**To Reproduce**

1. Flight with A320n (In my case EDDL --> ESSA)
2. Back to mainmenu in order to load a new flight plan --> Start new flight --> bug occurs
3. Restart Sim does not help.

**Expected behavior**
I expected the aircraft to work just like it did minutes before when I was really happy that the flight could be processed without any bigger issues 

**Actual behavior**
The aircraft cannot be started anymore. Nomore functionality except the "External Power Button"

**References**
Please find the attached shreenshot

![Bugreport](https://user-images.githubusercontent.com/72570234/95492058-d51d1a80-099a-11eb-8643-b348360d2d8b.JPG)

Best,
Andruh0

**Comment by LissomPineapple** [comment] 2020-10-09 02:53
Just had the same issue on the latest version of the mod

**Comment by Andruh0** [comment] 2020-10-09 07:45
> Just had the same issue on the latest version of the mod

have you been able to solve the issue?

**Comment by LissomPineapple** [comment] 2020-10-09 08:51
Yes. Go download the Master Build from releases. That fixed it for me.

**Comment by Andruh0** [comment] 2020-10-09 09:08
> Yes. Go download the Master Build from releases. That fixed it for me.

Actually I have already tried to install the master build (that is the work in progress, right?) but the issue is still there....

**Comment by Diode42** [comment] 2020-10-09 10:20
Just had the same problem. I was using the stable version, then changed to the Master, which still had the same issue. 

I noticed that the team recommend turning off AI Traffic and Ground Plane Traffic, thought I'd give that a try. Sure enough, seems to be when ever there's planes around me I cannot power the plane but with AI off I can start from cold and dark.

**Comment by Andruh0** [comment] 2020-10-09 11:17
> Just had the same problem. I was using the stable version, then changed to the Master, which still had the same issue.
> 
> I noticed that the team recommend turning off AI Traffic and Ground Aircraft Traffic, thought I'd give that a try. Sure enough, seems to be when ever there's planes around me cockpit is unresponsive, with "Ground Aircraft Density" - set to 0. I can start from cold and dark.
> 
> **Tested YSSY - Gate 43. Turning Traffic on 1 by 1.

Thanks, I will give that a try and get back shortly.

**Comment by Benjozork** [comment] 2020-10-10 17:31
Duplicate of #718

**Closed by Benjozork** 2020-10-10 17:31 UTC
Labels: Bug
