### ISSUE TITLE
[BUG] Can't use "CLR" to delete waypoints

### ISSUE THREAD

**Issue by tellurics** [flybywiresim/a32nx#2799] opened 2020-12-29 22:25 UTC
**Mod Version**

I am using the latest development version

**Describe the bug**
When I set a STAR chart and I need to delete a waypoint, the CLR botton doesn't work.

**To Reproduce**

1. I set a arrival chart.
2. Everytime it shows a trasition and I try to delete
3. The CLR button doesn't work.

**Expected behavior**

The waypoint should be deleted whenever I press CLR.

**Actual behavior**

The waypoint is not deleted.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Sometimes it works, sometimes it doesn't.

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub): Marco#5326

**Comment by Benjozork** [comment] 2020-12-29 22:32
Duplicate of #1388

**Closed by Benjozork** 2020-12-29 22:32 UTC
Labels: Bug
