### ISSUE TITLE
EFB Takeoff Performance Calc

### ISSUE THREAD

**Issue by EuropeanVirtual** [flybywiresim/a32nx#7397] opened 2022-08-05 13:26 UTC
### Aircraft Version

Experimental

### Description

Would it be good if you had a Takeoff Performenc Calculator so you don't always have to switch to a website.

Where would this be good
in the existing EFB

### References (optional)

FsLabs in there in the EFB is present one calculator

### Discord Username (optional)

Rowside#7166

**Comment by derl30n** [comment] 2022-08-05 17:08
Duplicate of https://github.com/flybywiresim/a32nx/issues/4444

**Closed by derl30n** 2022-08-05 17:08 UTC
Labels: Request
