### ISSUE TITLE
Additional entries in MCDU at startup

### ISSUE THREAD

**Issue by pjakrishnan** [flybywiresim/a32nx#3175] opened 2021-01-25 02:50 UTC
In the A320NX, would request the following little features added, in fact merge from default A320Neo!

1. On the Init pages, add
2. A reasonable value for CI, and the Cruise altitude/temp from the FP entered in MSFS.
3. Fill in ZFW/ZFWCG and TOW/LAW  numbers.
3. On the RADNAV page, fill in both ILS and frequency numbers

Thank you.

P.J.Anantha Krishnan

**Comment by MisterChocker** [comment] 2021-01-25 12:18
FYI please don't address multiple requests or issues in one issue and follow the provided templates.

for CI #1816 although the CI is a more complex functionality
for 3. ZFW/ZFWCG can be requested via clicking with an empty scratchpad onto the LSK. TOW/LW are auto computed
for 4. That's already happening. ![image](https://user-images.githubusercontent.com/1857322/104447490-293c2a00-559c-11eb-8741-9aded71109b1.png)

I am closing since none of the above are new requests, issues or are working as intended.

**Closed by MisterChocker** 2021-01-25 12:18 UTC
