### ISSUE TITLE
[BUG] Mismatch Fuel Display

### ISSUE THREAD

**Issue by torontoflyer** [flybywiresim/a32nx#3788] opened 2021-03-03 04:50 UTC
**Mod Version**
Dev version 62771d0
  "built": "2021-03-02T16:47:15+00:00",
  "ref": "master",
  "sha": "62771d00ba5d272d0ee19bca1ffb0c978a8c1622",
  "actor": "Benjozork",
  "event_name": "manual"

**Describe the bug**
Mismatch fuel in ECAM to the actual loaded fuel (see attached picture)

**To Reproduce**
1. Spawn the aircraft in any parking position, at any airport; without inputting flight plan on the menu page
2. Upload flight plan on FMC from Simbrief
3. Load planned weight from AOC menu - under the PERF/W+B option for both fuel and payload
4. Check fuel displayed on ECAM, compared against the value on "Fuel" page in MSFS and Simbrief OFP

**Expected behavior**
Loaded fuel and that shown in ECAM should match

**Actual behavior**
The ECAM displayed less fuel than the actual loaded fuel and payload. The values in "Fuel" page matched the Simbrief OFP, ECAM showing incorrect amount of fuel.

**References**
![image](https://user-images.githubusercontent.com/73716850/109754425-fe408080-7bb1-11eb-8c79-55ebecbd57fb.png)

Was this working before/when did the issue start occurring?
It used to be working fine

Is this a problem in the vanilla unmodded game?
NO

**Comment by felixharnstrom** [comment] 2021-03-07 11:02
Duplicate of #3102?

**Comment by MisterChocker** [comment] 2021-03-07 11:39
Duplicate of #3102

**Closed by MisterChocker** 2021-03-07 11:39 UTC
Labels: Bug
