### ISSUE TITLE
Direct to button doesn't update the route on the navigation screen [BUG]

### ISSUE THREAD

**Issue by TheVivzzy** [flybywiresim/a32nx#853] opened 2020-09-24 22:01 UTC
**Mod Version**

master branch

**Describe the bug**

When pressing the direct to button on the fmc and clicking on the waypoint that you wan't to go to, the airplane turns towards that waypoint but the navigation display or fmc isn't updated to show the direct to the new waypoint.

**To Reproduce**

1. Click direct to button on fmc
2. Select desired waypoint and insert new waypoint
3. 

**Expected behavior**

When the direct for the waypoint was inserted, the navigation screen should should an updated line showing the planes path to the new direct waypoint and the fmc should of updated to show the deleted the waypoints aswell.

**Actual behavior**

The plane turned towards the waypoint and flew to it, but the navigation screen still showed the old route and did not delete the waypoints from the navigation screen or fmc.

**References**

**Additional context**

n/a
Was this working before/when did the issue start occurring?
Issue started from the first time I flew the airbus with the mod.

Is this a problem in the vanilla unmodded game?
Not sure.

Discord username (if different from GitHub):

**Comment by Ares1378** [comment] 2020-09-25 03:44
I can confirm this issue. It is also a vanilla bug

**Comment by wpine215** [comment] 2020-11-03 04:40
Linked issue #1438

**Comment by ties1717** [comment] 2020-12-28 20:22
I have spoken to an a320 pilot and he said that in real life the waytpoints before the slected waytpoints get deleted so i can confurm this bug

**Comment by shanenicholson88** [comment] 2021-02-01 12:21
![WhatsApp Image 2021-02-01 at 11 02 56](https://user-images.githubusercontent.com/78353790/106458101-cd244180-6487-11eb-87a2-53d4b39c5b6e.jpeg)

Good afternoon,

It should update and remove the way points. What may be a workaround at the moment is if we had the option to delete the way points. Some way points do not clear when selected..

**Comment by Treat3O** [comment] 2021-02-23 13:19
Now that this thread has been opened I would like to comment on another related problem.
When performing the direct (in addition to not deleting the aforementioned waypoints) the aircraft performs it by radial and not directly. I mean, when you select the direct point a line is drawn and if the turn is very closed the plane re-finds that line instead of flying to the point once it is oriented. Find attached a photo with which the explanation can be better understood.

![image](https://user-images.githubusercontent.com/79520228/108847962-b2ee0700-75e0-11eb-9bcf-b3f12b15fe4e.png)

There you can see how the direct would be programmed correctly. Where the aircraft follows a curve which orients you to the desired point. I hope to have explained myself well since as normal I already find it difficult to explain myself and besides my english is not very good.


I'd like to say that you're doing a very great job with this plane and I'm sure you'll gradually get to the level of payware one.

**Comment by Treat3O** [comment] 2021-02-23 13:24
In version 0.5.3 this "problem" continues to occur.
I don't know if you'll already be working on it in the new version 0.6.0 if that's how I apologize, I didn't know.

**Comment by 2hwk** [comment] 2021-11-21 07:17
Fixed by #4953 closing ☑️

**Closed by 2hwk** 2021-11-21 07:17 UTC
Labels: Bug, MCDU, Bug-Vanilla, fixed in cFPM
