### ISSUE TITLE
[BUG] Upper Ecam Shows The Wrong Thrust Percentage

### ISSUE THREAD

**Issue by JacobKreindler** [flybywiresim/a32nx#1414] opened 2020-10-16 21:44 UTC
**Mod Version**

master

**Describe the bug**

The upper Ecam shows the wrong thrust percentage all the time

**To Reproduce**

1. Put the throttles anywhere and look at the thrust percentage in the top right of the upper Ecam
2.
3.

**Expected behavior**

It should show the correct thrust percentage

**Actual behavior**

It consistently shows the wrong percentage

**References**

![Microsoft Flight Simulator 2020-10-16 5_40_39 PM](https://user-images.githubusercontent.com/70914399/96311217-0028ef00-0fd7-11eb-9208-5f5988762c7a.png)
![Microsoft Flight Simulator 2020-10-16 5_34_31 PM](https://user-images.githubusercontent.com/70914399/96311223-028b4900-0fd7-11eb-8949-3cde530236e4.png)
![Microsoft Flight Simulator 2020-10-16 5_34_25 PM](https://user-images.githubusercontent.com/70914399/96311228-04550c80-0fd7-11eb-963a-b6c20599a64d.png)

**Additional context**

Was this working before/when did the issue start occurring?
With the update brefore the latest
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):
JacobK #9511

**Comment by Benjozork** [comment] 2020-10-16 22:39
Duplicate of #909

**Closed by Benjozork** 2020-10-16 22:39 UTC
Labels: Bug
