### ISSUE TITLE
[BUG] Terrain ND mode not working

### ISSUE THREAD

**Issue by Roboplayer999** [flybywiresim/a32nx#2153] opened 2020-11-30 22:15 UTC
**Mod Version**
A320NX Master 2020-11-30T21:11:53+00:00

**Describe the bug**
Terrain mode not working

**To Reproduce**
1.Start on the runway
2.take off
3.Turn Terrain mode on

**Expected behavior**
Display colours for the terrain

**Actual behavior**
Nothing
![Screenshot (54)](https://user-images.githubusercontent.com/69807128/100672187-dbf45800-3361-11eb-9a6e-2e9a757d3926.png)

**Comment by tareksabet** [comment] 2020-12-01 07:14
You will have to turn off the WX radar first. But that's not realistic as it should override the WX radar

**Comment by Roboplayer999** [comment] 2020-12-01 07:47
No, still doesn't work with WX radar off
![Screenshot (56)](https://user-images.githubusercontent.com/69807128/100711618-d0c91880-33b1-11eb-90c8-a72f74760829.png)

**Comment by Jacke1012** [comment] 2020-12-01 17:17
For me clicking on the terrain button the weather rader comes up. Even if the weather radar is of. It worked before the patch

**Comment by JLD95** [comment] 2020-12-01 17:19
Confirm this issue with  build "2020-12-01T01:18:52+00:00"

**Comment by Roboplayer999** [comment] 2020-12-01 17:29
Yes

**Comment by ilyeshammadi** [comment] 2020-12-01 20:53
I will have a look at this, it could be due to my recent changes to WX in the Navigation Display.

**Comment by Eaglepilot6** [comment] 2020-12-02 16:54
"Mode Change" shouldn't be displayed when Terrain on ND is selected on/off.

**Comment by Roboplayer999** [comment] 2020-12-03 07:05
only for a few seconds, thank you for looking into it

**Comment by Roboplayer999** [comment] 2020-12-03 07:39
It only works if you start cold and dark

**Comment by BobMiles** [comment] 2020-12-03 13:31
For me it doesn't work from cold and dark either. I have the same issue.

**Comment by JLD95** [comment] 2020-12-03 13:58
1lso for me, with cold and start, terrain don't work anymore

**Comment by Benjozork** [comment] 2020-12-03 14:00
Hello, please refrain from commenting if you have no new information to add. Use the thumbs up reaction if you are experiencing the same issue. Makes information easier to find.

**Comment by tareksabet** [comment] 2020-12-03 14:34
@Roboplayer999 It depends on the database as in some areas you will find terrain and others no. Basically it's a database issue from asobo

**Comment by BobMiles** [comment] 2020-12-03 14:47
> Hello, please refrain from commenting if you have no new information to add. Use the thumbs up reaction if you are experiencing the same issue. Makes information easier to find.

Well, please read my comment more careful. I objection to the issue description and Roboplayer999 it does not work when starting from cold and dark on my setup. 
Also, it clearly does not work in areas where it used to work. Plus it should never show the WX when on TERR on ND, database available or not. At least that's my guess.

**Comment by Benjozork** [comment] 2020-12-03 14:52
You said "For me it doesn't work from cold and dark either. I have the same issue.". Maybe you accidentally deleted part of your comment part to posting it ?

**Comment by Benjozork** [comment] 2020-12-03 14:52
I misread your comment sorry 😄 my bad

**Comment by pluginram** [comment] 2020-12-04 11:36
worked when i selected terrain mode immediately  and left it on the whole flight and weather radar co pilot
started custom flight to check close to Malpensa LIMC mountains because i can confirm it was not working when you first show weather and then turn on terrain like before it always worked.

**Comment by ilyeshammadi** [comment] 2020-12-04 11:50
I have PR open yo fix this, give it a try and let me know your feedbacks in the PR #2218

**Comment by Roboplayer999** [comment] 2020-12-04 12:03
Do you mean the new master?

**Comment by Roboplayer999** [comment] 2020-12-04 12:24
It still doesn't work on the 2020-12-04T06:37:32+00:00.
It displays the WX info if I press terrain even if I disable the WX radar
![Uploading Screenshot (87).png…]()
![Screenshot (88)](https://user-images.githubusercontent.com/69807128/101163529-00875300-3634-11eb-8fb5-b7bcdb7c35d6.png)

**Comment by Benjozork** [comment] 2020-12-04 13:45
@Roboplayer999 the PR is not merged yet so it's not in master

**Closed** 2020-12-05 14:34 UTC
Labels: Bug, Bug-Vanilla, ND (Navigation Display)

**Comment by Roboplayer999** [comment] 2020-12-05 21:28
ok thx
