### ISSUE TITLE
[BUG] FORMAT ERROR catching trying to fill ZFW/ZFWCG 

### ISSUE THREAD

**Issue by AdmiralArtemiy** [flybywiresim/a32nx#2296] opened 2020-12-08 22:56 UTC
Dev. ver.

Describing the bug:
Catching the "FORMAT ERROR" message trying to fill the ZFW/ZFWCG at the FUEL PRED section of the MCDU in all possible formats. 

To Reproduce:
1. During preparing for departure go in the FUEL PRED section of the MCDU.
2.  Fill the ZFW/ZFWCG values.
3. Click the button near the ZFW/ZFWCG.

Expected behavior:
The ZFW/ZFWCG values become entered.

Actual behavior:
Catching the "FORMAT ERROR" message.

Is this a problem in the vanilla unmodded game? - No.

**Comment by Benjozork** [comment] 2020-12-08 22:57
> master build from 7 oct.

Holy hell... You are two months out of date.

There have been over multiple hundred updates since then. You need to update your build....

**Comment by AdmiralArtemiy** [comment] 2020-12-08 23:01
> > master build from 7 oct.
> 
> Holy hell... You are two months out of date.
> 
> There have been over multiple hundred updates since then. You need to update your build....

Should I chose 0.40 or 0.4.1 version so?

**Comment by Benjozork** [comment] 2020-12-08 23:02
> > > master build from 7 oct.
> > 
> > Holy hell... You are two months out of date.
> > 
> > There have been over multiple hundred updates since then. You need to update your build....
> 
> Should I chose 0.40 or 0.4.1 version so?

0.4.2 :)

**Comment by AdmiralArtemiy** [comment] 2020-12-08 23:07
> > > > master build from 7 oct.
> > > 
> > > 
> > > Holy hell... You are two months out of date.
> > > There have been over multiple hundred updates since then. You need to update your build....
> > 
> > 
> > Should I chose 0.40 or 0.4.1 version so?
> 
> 0.4.2 :) unless you want the latest features, then you should get the latest dev (which is of 2 hours ago)
> 
> Keep in mind dev is updated multiple times a day, so you need to update it to stay up to date.

Thank you. And where to find the dev. ver? I see only releases page with the 0.4.2 last.

**Comment by Benjozork** [comment] 2020-12-08 23:08
You can use the installer:

https://github.com/Externoak/A32NX-installer/releases/latest/download/A32NX_Downloader.zip

**Comment by tareksabet** [comment] 2020-12-09 07:34
@AdmiralArtemiy please confirm that you don't have that message anymore on the latest dev version.

**Comment by AdmiralArtemiy** [comment] 2020-12-09 10:06
> @AdmiralArtemiy please confirm that you don't have that message anymore on the latest dev version.

On the latest dev. ver. I catch this message still.

**Comment by AdmiralArtemiy** [comment] 2020-12-09 14:21
So we have to wait to update? Or we need to download something?

**Comment by tareksabet** [comment] 2020-12-09 14:24
> So we have to wait for update? Or we need to download something?

So it's been reproduced and any of the devs will check this issue and repair it.
Thanks for reporting this issue.

**Comment by tareksabet** [comment] 2020-12-09 14:41
@AdmiralArtemiy so tested it on latest master it doesn't work on FUEL PRED page, but INIT 2 works fine (only in cold and Dark state) and it's been worked on by PR #2251

**Comment by AdmiralArtemiy** [comment] 2020-12-09 15:15
> @AdmiralArtemiy so tested it on latest master it doesn't work on FUEL PRED page, but INIT 2 works fine (only in cold and Dark state) and it's been worked on by PR #2251

So I should to download that old ver.? Will be fixed in dev. ver. further?

**Comment by tareksabet** [comment] 2020-12-09 15:24
> > @AdmiralArtemiy so tested it on latest master it doesn't work on FUEL PRED page, but INIT 2 works fine (only in cold and Dark state) and it's been worked on by PR #2251
> 
> 
> 
> So I should to download that old ver.? Will be fixed in dev. ver. further?

It will be fixed when the PR I mentioned above will be merged into the master (development version)

**Comment by warthog02** [comment] 2020-12-12 02:10
Thanks all. Will check the next Dev Master.

**Comment by beheh** [comment] 2020-12-14 22:15
Sounds like this was not fixed in #2251, according to #2430, as it rather crashes the INIT B page now.

**Comment by AdmiralArtemiy** [comment] 2020-12-15 13:16
This bug still happening. INIT B page also is not available.

**Comment by tareksabet** [comment] 2020-12-15 14:41
> This bug still happening. INIT B page also is not available. 

Well, the INIT B page is not avail as IRL after engine start.
Also I will need to check in details the issues with the INIT B page (if there are) with the FUEL PRED page.

**Comment by Lucky38i** [comment] 2020-12-22 10:47
Seems as though this issue is resolved according to #2340

**Closed by Lucky38i** 2020-12-22 10:47 UTC
Labels: Bug, MCDU, Reproduced
