### ISSUE TITLE
[BUG] Phantom fuel draw from outer tanks.

### ISSUE THREAD

**Issue by N7-Andres** [flybywiresim/a32nx#2083] opened 2020-11-24 12:00 UTC
**Mod Version**

{ "built": "2020-11-24T08:08:38+00:00", "ref": "refs/heads/master", "sha": "b570de8c53cd5b52a21c81f8120bfa57d8c53830", "actor": "wpine215", "event_name": "push" }

**Describe the bug**

Phantom fuel draw when powering on plane at ~10% fuel.

**To Reproduce**

1. Load into game with plane cold and dark.
2. Set fuel to about 10% in the fuel menu.
3. Power on the plane. (Ext. power or even just 1 battery)
4. Check the fuel menu or ECAM screen. Fuel should be draining from the outer tanks.

**Expected behavior**

Fuel should not be consumed if there is no system actively consuming it.

**Actual behavior**

At about 10% overall fuel outer fuel tanks start draining until empty.

**References**

Video demonstrating the whole thing.
https://drive.google.com/file/d/1elnKVt-Ack8oqrjJ0hvEuGcwAfGIVb6B/view?usp=sharing

**Comment by lukecologne** [comment] 2020-11-24 12:25
So, there are a few things. The expected behaviour here (I don't know if that's realistic) is that fuel is transferred from the outer to the inner tanks. That it only works with battery is normal, since the fuel valves need electricity to operate. But, the fact that it is only taking fuel out of the outer tanks and not adding it to the inner wing tanks is obviously a bug. I don't know if that is also present in the default A320, I'm checking now.

**Comment by lukecologne** [comment] 2020-11-24 12:33
OK, just checked and this also seems to happen in the default A320. So this is an Asobo bug.

**Comment by Tonyehrd** [comment] 2020-11-24 12:42
I noticed that yesterday, it happened to me when the GPU was connected.

**Comment by donstim** [comment] 2021-07-30 05:10
This has been fixed in Sim Update 5. Fuel transferred from the outer tanks without engines running will now transfer into the inner tanks rather than disappearing.

**Closed** 2021-07-30 08:53 UTC
Labels: Bug, Fuel
