### ISSUE TITLE
N1 trend indicator

### ISSUE THREAD

**Issue by Finn-D-AEWG** [flybywiresim/a32nx#6550] opened 2022-01-16 13:14 UTC
### Aircraft Version

Development

### Description

I would like to see the N1 trend indicator, which can be seen in the image below. It's implemented in all A320 CEOs and also the NEOs. The N1 trend indicator is only visible when the Autothrust is engaged. 

### References (optional)

![image png e039b6d118885292ea20491163e07215](https://user-images.githubusercontent.com/72933147/149661291-3979ae1c-0455-4550-ac4c-5be244bef39f.png)

Visible at 24:55: https://www.youtube.com/watch?v=orXbHqbXkUc

### Discord Username (optional)

Finn_D-AEWG#3595

**Comment by beheh** [comment] 2022-01-16 22:56
Duplicate of #3002

**Closed by beheh** 2022-01-16 22:56 UTC
Labels: Request
