### ISSUE TITLE
[BUG] Air conditioning knobs cant be turned.

### ISSUE THREAD

**Issue by tumev2** [flybywiresim/a32nx#1344] opened 2020-10-14 21:33 UTC
**Mod Version**
master

**Describe the bug**
Air conditioning knobs for COCKPIT, FWD AND AFT-cabin cannot be turned. 

**To Reproduce**
1. Load up the A320
2. Look to the overhead panel.
3. Turn air conditioning knobs.

**Expected behavior**
Knobs should be able to be turned.

**Actual behavior**
No click spot for the knobs appears and they cannot be turned.

**References**

**Additional context**
Started happening after PR #1238 

Was this working before/when did the issue start occurring?
Was working.
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
tume#0313

**Comment by Benjozork** [comment] 2020-10-14 21:45
Cannot reproduce. Could you film a video ?

**Comment by tumev2** [comment] 2020-10-14 22:07
![VIDEO](https://user-images.githubusercontent.com/72464762/96050656-ab745f80-0e82-11eb-84e4-2f66e53e2c36.gif)

**Comment by joshbxd514** [comment] 2020-10-14 22:32
Hi,

Ive tried this on master downloaded about an hour ago and have no issue.

Please see below.

https://gyazo.com/66912bf53385ec88d217fda8e4101697

**Comment by c1be** [comment] 2020-10-15 07:09
They work fine. I not sure, but i think you need to hold mouse to turn it, not click as before, before it used steps, now it's smooth as butter.

**Comment by snaylor111** [comment] 2020-10-15 15:05
yes they work for me as well

**Comment by NathanInnes** [comment] 2020-10-28 01:31
Is this still an issue for you? @tumev2

**Comment by MisterChocker** [comment] 2020-11-04 01:14
Still relevant?

**Comment by lukecologne** [comment] 2020-11-04 01:17
Since the author hasn't answered yet, the issue is pretty old and this was likely an installation problem, I'll close this.

**Closed by lukecologne** 2020-11-04 01:17 UTC
Labels: Bug, Needs More Info
