### ISSUE TITLE
Filed IFR flight plan no longer loads into FMS correctly after SU7

### ISSUE THREAD

**Issue by kilocharlie1** [flybywiresim/a32nx#6762] opened 2022-02-19 22:29 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-02-18T20:47:13+00:00",
  "ref": "master",
  "sha": "054043de97f38cfb79832f2645d865d22c3296de",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "master:054043de"
}
```

### Describe the bug

After SU7 when you file a flight plan on the home menu, with a departure and an arrival, and you load into the sim, power up the plane and go to the Flight Plan page on the FMS, you will see that it is filled with discontinuities, "manual" waypoints, and the waypoints between the departure and arrival are not listed anywhere.

### Expected behavior

All of the waypoints are listed, and the same path that is shown on the main menu or VFR map is displayed on the MFD.

### Steps to reproduce

1. File a flight plan from Indianapolis to Denver, Indy9 departure, Quail1 approach, routing: JAAVE, GORDO, SPI, BAYLI, TWAIN, SAAGS, MCI, CATTS, SLOWR, HLC, HGO, then the Quail1 26 approach.
2. 2. Turn on the battery and external power, go to the FMS, click the FLT PLN button, and read the waypoint listing.

### References (optional)

![20220219170833_1](https://user-images.githubusercontent.com/88682168/154821125-1878e29c-4122-46af-ba59-7be5863edb41.jpg)

### Discord Username (optional)

GeeMeeKee#9761

**Comment by Benjozork** [comment] 2022-02-19 22:31
I don't see anything wrong in your flight plan? The SID you selected contains an altitude leg and a manual. If you want some other routing, don't pick that SID.

**Comment by Benjozork** [comment] 2022-02-19 22:33
As for the missing points, we generally do not recommend using the MSFS world map for planning flights. Enter the flight plan manually or use SimBrief for the best experience.

**Comment by Benjozork** [comment] 2022-02-19 22:34
It's important to keep in note that MANUAL legs and discontinuities are not bugs.

https://docs.flybywiresim.com/pilots-corner/advanced-guides/flight-planning/disco

**Comment by kilocharlie1** [comment] 2022-02-20 16:33
I do file it via SimBrief too, does the same thing

**Comment by kilocharlie1** [comment] 2022-02-20 16:52
Also the thing is it worked fine before

**Comment by Benjozork** [comment] 2022-02-20 17:04
Can you please provide screenshots of what you mean by the green line abruptly ending (with a simBrief flight plan) ? And with matching F-PLN page screenshots, since that does not match the one you provided (you should have an infinite line)

Also, what AIRAC cycle are you using on simBrief vs. the sim ?

Did you ever have navigraph navdata installed ?

**Comment by kilocharlie1** [comment] 2022-02-23 00:27
![bug](https://user-images.githubusercontent.com/88682168/155242423-95a09b88-cd91-4a6f-abde-48ecd374a863.jpg)
So I found that it doesn't actually draw the line at all in correspondence with the waypoints, it just draws a line straight out from the runway from which you took off.

P.S I had it imported from the world map rather than simbrief in this screenshot

**Comment by Benjozork** [comment] 2022-02-23 00:29
- I don't know what your flight plan is. Chances are, this is a MANUAL leg, which means **the drawing you are seeing on the ND is correct - they draw an infinite line - the link I sent explains this.**
- The VFR map should not be used to judge the flight plan. We only do basic syncing and MSFS does not understand the majority of ARINC legs, so it will not look any good.

**Comment by kilocharlie1** [comment] 2022-02-23 00:34
That VFR map is the flight plan I filed on the world menu

**Comment by kilocharlie1** [comment] 2022-02-23 00:35
Also its the same one mentioned above in the original report

**Comment by Benjozork** [comment] 2022-02-23 00:37
Yes. The ND is correct. You have a MANUAL leg in your flight plan, so it draws that.

**Comment by kilocharlie1** [comment] 2022-02-23 00:42
Also AIRAC 2201

**Comment by tracernz** [comment] 2022-02-23 04:31
Just to re-iterate, that is exactly in accordance with your SID, which calls for a manual leg on heading 230 (or as assigned by ATC). You can see on the MCDU the MANUAL leg with heading 230... You need to follow ATC instructions (vectors or direct to), or if flying offline vector yourself or DIR TO the next part of the procedure. Everything is working correctly here.

**Comment by derl30n** [comment] 2022-04-08 23:06
Closing since working as intended

**Closed by derl30n** 2022-04-08 23:06 UTC
Labels: Bug
