### ISSUE TITLE
[BUG] Cold & dark battery BAT power doesn't work unless ground power is first turned on

### ISSUE THREAD

**Issue by AdamNZ** [flybywiresim/a32nx#985] opened 2020-09-30 10:05 UTC
**Mod Version**

0.3.1

**Describe the bug**

Cold & dark start. Activating the two BAT switches does nothing unless EXTERIOR power is first turned on. Crazy - as (theoretically) you can't even power up the radio to call for external power connection.

**To Reproduce**

1. Set up FS 2020 so that the A320 is at a gate that has the full set of ground services.
2. Do NOT turn on external power.
3. Flip both BAT switches. Nothing happens.
4. Turn on EXT power and still nothing.
5. Try again, but this time turn EXT power on and *then* the two BAT switches. All works as per normal.

**Expected behavior**

You should be able to power on the batteries first - so you can call up ground services on the radio and ask for the external power supply to be brought over and plugged in.

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Was working fne pre Japan update and previous mods.

Is this a problem in the vanilla unmodded game? NO.

Discord username (if different from GitHub):

**Comment by messer79** [comment] 2020-09-30 10:49
See this: https://github.com/flybywiresim/a32nx/issues/718.

I sometimes cannot switch the batteries on even if EXT PWR is toggled from AVAIL to ON.
I think it is not related to this awesome mod (0.3.0), as yesterday I removed it and had the same issue on 1.9.3 pure (also no liveries) game version. Hopefully a32nx developers find a workaround very soon. I don't feel like waiting another 2 weeks (or more) for a Microsoft/Asobo fix.

**Comment by NathanInnes** [comment] 2020-09-30 11:45
Can't replicate. I spawned C&D and batteries w/o External PWR works.

**Comment by AdamNZ** [comment] 2020-09-30 12:22
OK ... hmmm .. and you're positive you didn't hit that EXT power panel button - even without calling up ATC/Ground - before you activated the BAT switches?

I tried it with a friend of mine (via Teamspeak) and had the same problem. Once you get a "fail", even toggling the EXT button has no effect. Totally dead. We're both using 0.3.1.

**Comment by messer79** [comment] 2020-09-30 12:27
This is a situation when I spawned in a location with external power available but I didn't activate it.
Just toggled the batteries.

![image](https://user-images.githubusercontent.com/71893611/94611157-9e137e80-02a1-11eb-8808-d5d2d427f8c0.png)
![image](https://user-images.githubusercontent.com/71893611/94611071-82a87380-02a1-11eb-8af3-1faf51b65e78.png)

**Comment by AdamNZ** [comment] 2020-09-30 12:53
> 
> 
> This is a situation when I spawned in a location with external power available but I didn't activate it.
> Just toggled the batteries.

Yes - that's what I get. I tried "cheating it" by attempting to start the APU when in that state but, without power, that's never going to work ;)

**Comment by BernardSW** [comment] 2020-09-30 14:39
I am having the same problem since downloading the latest Japan update.

**Comment by NathanInnes** [comment] 2020-09-30 14:59
#987 with similar issue solved his by deleting the livery mega pack

**Comment by bscout9956** [comment] 2020-09-30 15:01
Just want to add my two cents that I have the livery mega pack and this isn't happening to me.

**Comment by Dgh1974** [comment] 2020-09-30 17:12
Have the same issue ( did not test external power first suggestion ) 

ONLY fresh FS2020 and the 0.3.1 .. no other planes or liveries ( few building sceneries )

Starting on runway does work .. but then other bugs ( no radio frequencies visible / LS button not working etc etc )

**Comment by Dgh1974** [comment] 2020-09-30 17:53
Tested and can confirm extrrnal first and then battery is solving for me

**Comment by NathanInnes** [comment] 2020-09-30 18:29
The latest master and version 0.3.1 are completely different.

Download here: https://github.com/flybywiresim/a32nx/archive/master.zip

**Comment by Dgh1974** [comment] 2020-09-30 18:37
But 0.3.1 is the latest stable version people use right ? 

Bit confused what i should use and what website to check for latest versions ( github or the flybyWire website )

**Comment by NathanInnes** [comment] 2020-09-30 18:54
Stable release is many commits behind master. Master is a dev build that is constantly fixing bugs and adding new features.

**Comment by AdamNZ** [comment] 2020-10-01 01:13
I've installed the latest Master. The problem is still there.

**Comment by apolinski** [comment] 2020-10-01 05:10
This issue seems to be random. Sometimes I can start batteries normally, sometimes the airplane is dead. Sometimes a Restart will fix it, sometimes not. On one occasion I started up from cold and dark (batteries first, then ext power) but sat on the tarmac for awhile (on the phone) and suddenly the aircraft lost all power and could not be restarted. Maybe it's something to do with that "phantom switch" issue?

**Comment by Dgh1974** [comment] 2020-10-01 15:23
Hi can someone seriously test the next ( works for me )

All traffic at 30% .. generic models
Start cold / dark
First external power then battery
If this is NOT working then hit ESC and select RESTART
then again external power then battery

I did this 7 times ... 7 times i had the issue and 7 times the restart did solve for me.

Cold and dark failed 7 times initially ( also with gen models and ALL traffic to “0”). But the restart did solve

**Comment by AdamNZ** [comment] 2020-10-05 03:32
I've been trying the various Master builds since logging this error and the problem persists. I'm running build.py every time I download a new Master.
Can the Master builds not have version numbers so we can always tell if we have the most recent?

**Comment by MrMinimal** [comment] 2020-11-19 21:41
I could not reproduce this on master (5e57e8dd9fbcf3cbbefd119606df2576da85bd7e) anymore.

External power and batteries both bring other overhead lights online.
The description isn't too clear but "Activating the two BAT switches does nothing" isn't true anymore - other lights turn on.

Close?

**Comment by messer79** [comment] 2020-11-19 21:48
@MrMinimal - It seems like this issue is not present any more.

**Comment by lukecologne** [comment] 2020-11-19 21:51
Closing, as I also cannot reproduce this. If you still have this issue, please create a new one.

**Closed by lukecologne** 2020-11-19 21:51 UTC
Labels: Bug
