### ISSUE TITLE
[BUG] Fonts are unreadable in the FBW mod

### ISSUE THREAD

**Issue by FinalLightNL** [flybywiresim/a32nx#1618] opened 2020-10-30 12:20 UTC
**Mod Version**
Latest DEV version from the installer.

**Describe the bug**
Fonts that have a light source behind them in the cockpit are shimmering weirdly and are hardly readable.
![Screenshot_2](https://user-images.githubusercontent.com/72287598/97703933-c1546800-1ab1-11eb-8633-59dc66f575d6.png)

The screenshot has been taken @ Ultra Preset 2560 x 1440 resolution with normal 100% res scale.
The new TAA method that got released with Patch #5 seems to have made it worse than before.

Going back to the stock A320 the fonts are definitely more readable.
![Screenshot_4](https://user-images.githubusercontent.com/72287598/97704077-02e51300-1ab2-11eb-8fc1-7d2f7df4524c.png)

**To Reproduce**
1. Enable TAA & turn on the cockpit lights
2. zoom a little bit out to have that Pilot POV.

**Additional context**
The issue might be with the type of font being used, aliased font or not.

**Was this working before/when did the issue start occurring?**
It was slightly better before Patch #5 

Is this a problem in the vanilla unmodded game?
Not really no.

Discord username (if different from GitHub): FinalLight-NL

**Comment by FinalLightNL** [comment] 2020-10-30 12:25
**additional comment**
There is no issue with the font when zoomed in, forgot to mention that.

**Comment by MuppetOwl** [comment] 2020-10-30 14:40
Can also confirm same issue.

**Comment by Benjozork** [comment] 2020-10-30 15:18
Can you provide a screenshot without TAA ?

**Comment by myselfaaryan** [comment] 2020-10-30 15:23
I think its the same issue as #1560

**Comment by Benjozork** [comment] 2020-10-30 15:24
Thanks, closing as duplicate of #1560.

**Closed by Benjozork** 2020-10-30 15:24 UTC
Labels: Bug

**Comment by myselfaaryan** [comment] 2020-11-03 16:49
Just realized its a different one @Benjozork Can we reopen this?

**Comment by FinalLightNL** [comment] 2020-11-04 04:38
It's pretty much only an issue with the emmisive text, the rest in the cockpit is fine.
don't think it's duplicate @Benjozork

**Comment by Benjozork** [comment] 2020-11-04 05:07
After investigation, it was found to be an issue with the MSFS TAA. We changed the font again today - please re-open an issue if it persists.

**Comment by myselfaaryan** [comment] 2020-11-04 11:43
@Benjozork Seems like the issue is fixed with the new font & it is looking really cool. Thanks to the team 👍
