### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by stedoc** [flybywiresim/a32nx#5967] opened 2021-10-04 22:17 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-10-03T13:38:40+00:00",
  "ref": "master",
  "sha": "1322d775fb8f52e8292a141573829424901b69a6",
  "actor": "IbrahimK42",
  "event_name": "manual"
}
```

### Describe the bug

when I try to print the metar many times the system freezes and closes the simulator
(sorry for the english but I use the translator)

### Expected behavior

press on print and print the metar

### Steps to reproduce

ctrl 5 to zoom in mcdu
I press mcdu menu
I press aoc menu
weather request
return
I await company message
I read the message
I press print
and sometimes the system freezes by closing the simulator

### Discord Username (optional)

Ste_Doc(Stefano)#5894

**Comment by donstim** [comment] 2021-10-04 22:57
Duplicate of https://github.com/flybywiresim/a32nx/issues/5429

**Closed** 2021-10-05 01:56 UTC
Labels: Bug
