### ISSUE TITLE
Holding without function

### ISSUE THREAD

**Issue by Leon30217** [flybywiresim/a32nx#3366] opened 2021-02-06 12:13 UTC
**Mod Version**
DEV

**Describe the bug**
Input the holding is correct, but without execution

**To Reproduce**
see on the appendix

**Expected behavior**
after input Holding, on the Display do you recognize the circle, where
the plane must fly along

**Actual behavior**
nothing work

**References**
![input_data](https://user-images.githubusercontent.com/77197869/107117781-f0326500-687c-11eb-9b0d-39bad99afacc.jpg)
![entered data](https://user-images.githubusercontent.com/77197869/107117783-f4f71900-687c-11eb-9c84-c29dc1820695.jpg)
![after_waypoint](https://user-images.githubusercontent.com/77197869/107117790-fc1e2700-687c-11eb-8d2f-36bcbc8a1357.jpg)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Gian85** [comment] 2021-02-06 12:14
I think it's not implemented yet

**Comment by tellurics** [comment] 2021-02-06 12:57
Duplicate of #673. It's not implemented yet.

**Closed** 2021-02-06 16:16 UTC
Labels: Bug
