### ISSUE TITLE
[BUG] Plane rocks violently in autopilot

### ISSUE THREAD

**Issue by Dreunit1986** [flybywiresim/a32nx#2102] opened 2020-11-26 01:23 UTC
**Mod Version**
Since USA update. I use the latest dev version.

**Describe the bug**
When AP enabled even on climb the plane rocks side to side like a ship on water but horizontally instead of lengthwise

**To Reproduce**

1. climb in autopilot... set alt to 34000ft. watch it rock after a bit... trying to regain control and deactivate the AP makes it worse.
2.
3.

**Expected behavior**

no rocking

**Actual behavior**

plane sways constantly on its xy axis

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-11-26 02:52
Duplicate of #2005.

**Closed by Benjozork** 2020-11-26 02:52 UTC
Labels: Bug
