### ISSUE TITLE
NOT IN DATABASE on init request

### ISSUE THREAD

**Issue by mark7274** [flybywiresim/a32nx#6232] opened 2021-11-23 16:22 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-23T13:37:26+00:00",
  "ref": "master",
  "sha": "6c72eb63d8a5aede7ce2f5225d8d87b8bf27720a",
  "actor": "crocket63",
  "event_name": "manual"
}
```

### Describe the bug

When I enter a flight plan and request an init, the MCDU shows no database and flight error

### Expected behavior

I expected for the flight plan to load; however, it did not load.

### Steps to reproduce

1. spawn at gate
2. create flight plan from KAUS-KATL
3. go to MCDU and click init request

### References (optional)

https://cdn.discordapp.com/attachments/785976111875751956/912734094947942440/2021-11-23_09-58-01.mkv

### Discord Username (optional)

marky mouse#1648

**Comment by Venorcis** [comment] 2021-11-24 07:59
Seems to happen a lot; just trying a second time always fixes it for me (though then you always see FLIGHT NBR IN USE or similar)

**Comment by tracernz** [comment] 2021-11-24 09:46
> Seems to happen a lot; just trying a second time always fixes it for me (though then you always see FLIGHT NBR IN USE or similar)

If it works the second time, it’s a case of the old nav data search API being too slow. There is a new API since SU6 which we will switch to when #6043 is merged.

**Comment by ErikNL80** [comment] 2021-11-25 12:50
I can reproduce the issue here at a flight from EIDW to EGPF... Restarting the flight does not help either...

**Comment by ErikNL80** [comment] 2021-11-25 13:37
After going back to the world map and creating the flightplan again it worked instantly. Very strange...

**Closed** 2021-12-18 16:47 UTC
Labels: Bug
