### ISSUE TITLE
[BUG] Strange behavior of the FMS, F-PLN 

### ISSUE THREAD

**Issue by dedyk** [flybywiresim/a32nx#1283] opened 2020-10-13 11:08 UTC
**Mod Version**
built: 2020-10-13T02:55:20+00:00
ref: refs/heads/master
sha: 16f5d53dbb7ef74b388b166d6aed202029df9f5d
actor: lukecologne
event_name: push

**Describe the bug**
I would like to report strange behavior od the FMS, F-PLN screen. After initialization can't set arrival procedure for destination airport. But after pressed of the CLR button everything looks to be normal. I recorded a short movie which show my error.

https://www.youtube.com/watch?v=Q9NhFPiBoB0

I can add that this problem does not occur in version 0.3.1. Problem exists only in dev version.

**To Reproduce**
1. Set starting and destination airport on INIT screen.
2. Try to set arrival procedure in destination airport

**Expected behavior**
After initialization the arrival procedure should be set without any workarounds.

**Actual behavior**
Can't set the arrival procedure without workarounds.

**References**
https://www.youtube.com/watch?v=Q9NhFPiBoB0

**Additional context**
-

** Was this working before/when did the issue start occurring? **
Works well in 0.3.1 version.

** Is this a problem in the vanilla unmodded game? **
No

**Comment by ChruutvoLuzi** [comment] 2020-10-13 11:27
Yes that is intended, the GPS Primary notification you see is the feedback from the ADIRS that it has been aligned. When pressing CLR it also clears it on the nd like IRL

**Comment by dedyk** [comment] 2020-10-13 11:35
Understand. People much smarter than me know what they are doing, so I close this issue.

**Comment by ChruutvoLuzi** [comment] 2020-10-13 11:45
Nvm i just rewazched the the video and i noticed that it is not overrideable. I dont know how it behaves irl so pilot input would be appreciated

**Comment by RayPov** [comment] 2020-10-13 13:31
I had the issue this morning after downloading the latest Developer update.   I immediately saw GPS primary shown on my nav display and also later in the FMC.   When I tried to check arrival information at my destination pressing the destination button opens a insert waypoint screen

After getting some help and reading this report,  I did use CLR to restore proper screen behavior to both the FMC and the Nav display 
![image](https://user-images.githubusercontent.com/49294218/95866872-722ed900-0d36-11eb-9aef-682b8525c84b.png)

I think having to clear something out to display arrival/departure or something else is going to be ongoing confusion.   I would highly recommend restoring previous operation where no clear action is required.

**Comment by ChruutvoLuzi** [comment] 2020-10-13 13:34
The clr action to remove it is as it should be in real life tho, the only question is, if you can type something and enter it and if it should clear the message aswell

**Comment by RayPov** [comment] 2020-10-13 13:44
I don't remember in the past having to use the clear button, that includes payware aircraft in P3D.  So my comment really is if it wasn't required in the past,  why require it now?

**Comment by ChruutvoLuzi** [comment] 2020-10-13 13:50
Because its true to life i guess? I dont think we should wash down the authentic experience if its confirmed to be true to life. More i think, that flightsimming is alot about having fun learning these bits and details. And when they are able to provide a true study level aircraft, why not do so? But thats up to the devs to decide that, i would really dislike it if they would remove this because i want "to fly the real aircraft" in the sim.

**Comment by Pleasure0102** [comment] 2020-10-13 14:02
@tareksabet Can you confirm this is normal ?

**Comment by St54Kevin** [comment] 2020-10-13 14:23
General behavior is normal yes. Scratchpad should be empty when pressing a LSK that is on a waypoint, which in this case the destination is. F-PLN page is just not up to the real thing yet. The destination line at the bottom is missing. With that, it should be possible. But we have to wait until we got a good system. System guys should confirm the details but I can confirm, generally its NOT a bug

**Comment by Pleasure0102** [comment] 2020-10-13 14:24
@St54Kevin is a Pilot i asked to check :) just so the Author knows

**Comment by St54Kevin** [comment] 2020-10-13 14:29
> So can I close this issue?

I think its something to look at again AFTER we got a good baseline system. Maybe close it and open it again if you find it after an update

**Closed** 2020-10-13 14:33 UTC
Labels: Bug
