### ISSUE TITLE
Texture glitch in the overhead panel

### ISSUE THREAD

**Issue by AVpilot89** [flybywiresim/a32nx#6366] opened 2021-12-15 08:56 UTC
### Aircraft Version

Stable

### Build info

```json
newest installer with newest build
```

### Describe the bug

Hi my friends,
absolute AWESOME plane you have created here, a masterpiece of programming. But there is a little annoying texture glitch on the overhead panel around this (I assume it´s an) air exhaust hose.
The texture glitch appears with the standard livery and the stable and experimental version. Maybe you are so kind to fix this glitch to create a cockpit with absolute 100% perfection.
And thanks for bringing us this awesome Airbus!

Here are some screenshots of the small texture glitch. Will surely be an easy fix.

![Microsoft Flight Simulator 15 12 2021 01_49_09](https://user-images.githubusercontent.com/96172510/146154754-36892344-53d1-4bfd-b9f3-fea2ee1f4597.jpg)

![Microsoft Flight Simulator 15 12 2021 02_34_39](https://user-images.githubusercontent.com/96172510/146154777-1c1f139b-6dc2-485e-abde-983ad5cadeea.jpg)

![Microsoft Flight Simulator 15 12 2021 07_30_50](https://user-images.githubusercontent.com/96172510/146154787-cb3dc9f5-d52f-49fa-b73d-aefb0e5b7340.jpg)

![Microsoft Flight Simulator 15 12 2021 07_31_05](https://user-images.githubusercontent.com/96172510/146154800-8c50b54a-ac6c-42bc-a2d9-06a51a871682.jpg)

Have a wonderful week and always continue your awesome programming skills :)

### Expected behavior

The texture glitch be gone.

### Steps to reproduce

Appears with every livery and in the experimental, stable and development version. (The newest FBW installer only offers stable and development version).

**Comment by bouveng** [comment] 2021-12-18 08:14
Hi. This issue is a duplicate of https://github.com/flybywiresim/a32nx/issues/5607, closing this one.
Thanks for reporting this none the less! =)

Br.

/J

**Closed by bouveng** 2021-12-18 08:14 UTC
Labels: Bug

**Comment by AVpilot89** [comment] 2021-12-18 12:26
Hi :) I was just hoping to get this fixed because the cockpit would be
PERFECT after doing so.

By the way do you plan adding a cargo version to the FlyByWire Airbus
collection some day?

Have a wonderful weekend!



Am Sa., 18. Dez. 2021 um 09:14 Uhr schrieb Johan Bouveng <
***@***.***>:
