### ISSUE TITLE
remember last sceen brightness setting (flight instruments)

### ISSUE THREAD

**Issue by speedwaystar** [flybywiresim/a32nx#6276] opened 2021-11-30 06:17 UTC
### Aircraft Version

Development

### Description

the chore of scrolling all the MFDs up to full brightness at the start of every flight has finally become too much! j/k

alternatively, a setting in the EFB to start all screens at full brightness on power up.

**Comment by WooleyPig** [comment] 2021-12-02 08:43
Hey all,
     I would so like to see all the lights being remembered at their 'previous flight' set positions with maybe an option in the pads settings so PPL can choose to use the feature or not. Full brightness for all would cause the same issue in reverse if you ask me although better than all being fully dim every time.

**Comment by MPO910** [comment] 2021-12-02 13:51
I would like to "spin" this wheel further: 
As a user I would like to have the possibility to store "n" aircraft states to use this stores states "on demand" or one of it stored states the next time I fire up the simulator with this aircraft. 

At the saving process I would like to "name" them as liked and choose 1 of "n" states to set as my "default startup" state.

Example:
- AT GATE (APU Running, displays on, NavLights on, Strobes off (just examples here), Radios on, Parkingbrake set...etc...)
- Cold and Dark (Everything off)
- At Runway (Engines running, completely setup to takeoff (as far as possible)

When "AT GATE" is choose as "Default" state, this one gets used the next time I fire up the simulator and use the FBWa320

Aircraft State=All Buttons/Knobs and values incl. APU, Engines etc.....ALL.

At this way a User can setup its own "setting" and store it completely (Different "standards (Settings) at different Airlines).

Regards
Marcus

**Comment by speedwaystar** [comment] 2021-12-03 03:38
Ah yes. the tollis a321 efb has this, and also auto saves its complete
state every 3 minutes.

**Comment by Aarondodd88** [comment] 2021-12-03 09:01
The chore of brightening the mfd's...All you do is press buttons in this game, why is 5 seconds of scrolling so painful LOL

**Comment by speedwaystar** [comment] 2021-12-03 09:21
you'll notice I appended J/K (just kidding) to the "chore" remark. :)

**Comment by Aarondodd88** [comment] 2021-12-03 09:29
ok :p

**Comment by oMrSmith** [comment] 2021-12-03 09:53
> ok :) Lucky the radios are already put to "on" and not "off" for us in cold and dark :p

This would be helpful when using the default ATC...
How does it work in real life? Are Batteries not required to be turned on for radio communication?

**Comment by derzierau** [comment] 2021-12-07 12:23
nice idea, i would start working on a solution to save different aircraft states, controlled by the EFB.

**Comment by speedwaystar** [comment] 2021-12-07 13:47
I notice that the toliss a321 defaults to 75% brightness for all screens
when power is applied, which seems reasonable.

basically the knobs will be wherever the previous pilots left them after
the turnaround. I don't know if "turn all screens to minimum before
powering down" is an actual procedure. it seems unlikely.

**Comment by speedwaystar** [comment] 2021-12-07 13:54
that would be great. being able to save at the start of an arrival and then
practice the landing over and over (which you can absolutely do in x-plane)
would be a game changer.

**Comment by derzierau** [comment] 2021-12-08 17:32
@2hwk we should also add the EFB as a label cause I think the EFB is the best place to store and load states.

**Comment by Larodian** [comment] 2021-12-30 21:39
I was going to create an entry for this, a simple save and load lighting button on the fly pad would be great.

**Comment by ErickSharp** [comment] 2022-01-27 13:35
Thinking about picking this up into flypados 3

**Comment by derl30n** [comment] 2022-04-09 21:46
Duplicate of https://github.com/flybywiresim/a32nx/issues/5451

**Closed** 2022-04-09 21:49 UTC
Labels: Request, PFD, ECAM, ND, Lighting, EFB
