### ISSUE TITLE
[BUG] Direct To not Working 

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#1150] opened 2020-10-06 19:12 UTC
**Mod Version**
0.3.1

**Describe the bug**
Direct to in FMC Flightplan Page not working . 

**To Reproduce**

1. Set in the Fix to which i want direct to flight . 
2. All other Waypoints before dont delete . 
3. The Autopilot dont fly to the Direct To Fix , the AP flys to one of the Waypoints before . 

**Expected behavior**
When i choose Direct to then the waypoints before this Waypoint should delete and the Autopilot should fly to this waypoint. 

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by SM-396** [comment] 2020-10-07 10:51
Here you see the Problem . 
I want to fly direct to DT444 , but the FMC dont delete the Points between my Position and DT444. Ist a BUG. 

![2020-10-07 12_47_52-Greenshot](https://user-images.githubusercontent.com/50043259/95321735-c13ebf00-089b-11eb-92b1-74729bbd9c80.jpg)

**Comment by SM-396** [comment] 2020-10-16 17:21
Here again an Video which shows you that DIRECT TO on my side is not working . 
I want to do an DIRECT TO DODAT . But after i setup DODAT at DIRECT TO , it is not the next Waypoint in Plan , its KLF and therefore the Plane flys to KLF and not to DODAT . 

https://streamable.com/gv7g1m

**Comment by Benjozork** [comment] 2020-10-16 17:50
@SM-396 please avoid spamming, we have your bug report and commenting many times will not make it go away faster.

**Comment by Benjozork** [comment] 2020-10-16 17:52
Duplicate of #206

**Closed** 2020-10-16 17:52 UTC
Labels: Bug, MCDU
