### ISSUE TITLE
FP's ON?

### ISSUE THREAD

**Issue by MStallen** [flybywiresim/a32nx#5036] opened 2021-06-07 08:54 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-06T10:57:16+00:00",
  "ref": "master",
  "sha": "56337b10b51308a9d09f732141e2ded306ca9921",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

If I start-up cold and dark as soon as I connect external power or put batteries ON then both FD's are turned ON aswell

### Expected behavior

FD's stay off

### Steps to reproduce

1. Start cold and dark
2. Put external power ON (or batteries ON)

### Additional info (optional)

In previous versions this wasn't the case

**Comment by Watsi01** [comment] 2021-06-07 09:38
This is intended behaviour. We changed that as we found out that's what the real thing does.

**Comment by aguther** [comment] 2021-06-07 09:43
According to FCOM DSC-22_30-20:
> The FDs are engaged automatically when the FMGC powers up.

Now currently it’s bound to the FCU which is incorrect. Now this needs to be rebound to the FMGC, although I’m not sure if the FMGC is already bound to correct electric bus. Therefore the current solution might be better than it was before.

Is that what you’re really behind?

**Comment by aguther** [comment] 2021-06-07 09:48
Duplicate of #4242

**Closed by aguther** 2021-06-07 09:48 UTC
Labels: Bug

**Comment by MStallen** [comment] 2021-06-07 09:54
Oke I understand real beheaviour. That's only good
