### ISSUE TITLE
[BUG] Unable to install with Game Pass - Path too long

### ISSUE THREAD

**Issue by gabrielcalderon** [flybywiresim/a32nx#2523] opened 2020-12-19 04:31 UTC
**Mod Version**
Master

**Describe the bug**
Unable to install on a Game Pass version of the game.

When unzipping the files into the community folder the following error appears:

```
Error 0x80010135: Path too long
File: A320_Neo_CDU_CFDS_Common_PowerUpTestRes.js

Full path is: E:\WpSystem\S-1-5-21-3260624516-186256847-876699138-1003\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\
```

**To Reproduce**
1. Download zip file from release section
2. Extract A320NX into the Game Pass Community folder

**Expected behavior**
Able to install the mod

**Actual behavior**
Error appears when unzipping the files

**Comment by Benjozork** [comment] 2020-12-19 04:35
Reinstall MSFS and choose to install packages in another directory. Windows path lengths are max. 260 characters.

**Comment by Benjozork** [comment] 2020-12-19 04:35
Closing as not caused by the mod and out of scope for us to fix

**Closed** 2020-12-19 04:35 UTC
Labels: Bug

**Comment by gabrielcalderon** [comment] 2020-12-19 04:39
@Benjozork It started happening with the latest release. It was working fine since the first version.

The path is the one created by the game itself, not me.

**Comment by Benjozork** [comment] 2020-12-19 04:53
You can configure the installation directory of the `Official/` and `Community/` folder in the MSFS installer.

The Store/GamePass version uses ridiculously long path names, which causes this error. This issue is not in the scope of the mod, as it is a limitation of the WIndows operating system.

If you do not wish to move the installation path, we are planning to remove those file prefixes when the mod is separated from the base-game, in the near future.
