### ISSUE TITLE
[BUG] Throttle (N1) Overshoot

### ISSUE THREAD

**Issue by winkerbie** [flybywiresim/a32nx#2472] opened 2020-12-16 20:36 UTC
**Mod Version**
```
  "title": "A32NX",
  "dependencies": [
    {
      "package_version": "0.1.58",
      "name": "asobo-aircraft-a320-neo"
    },
    {
      "package_version": "0.1.52",
      "name": "asobo-vcockpits-instruments-a320-neo"
    },
    {
      "package_version": "0.1.53",
      "name": "asobo-vcockpits-instruments-airliners"
    },
    {
      "package_version": "0.1.66",
      "name": "fs-base-aircraft-common"
    }
  ],
  "content_type": "AIRCRAFT",
  "minimum_game_version": "1.9.5",
  "manufacturer": "Airbus",
  "package_version": "0.4.2",
  "total_package_size": "00000000000635137414"
```

**Describe the bug**
Whenever powering up the throttles from idle, the engines N1 spools up beyond the set throttle level then cuts back again to correctly match the desired throttle level. I don't know if this is accurate behaviour or a bug.

**To Reproduce**
1. On the taxiway/runway ensure throttle is idle and the plane is not moving
2. Then push throttles to 40/50%
3. Watch as the N1 setting goes beyond the set level then spools back down to the desired level

**Expected behavior**
Not sure if this is accurate behaviour or the engines are only meant to spool up to the set level

**Actual behavior**
As above in reproduce steps.

**References**
Screenshot: https://i.imgur.com/QQMOLQP.jpg

**Additional context**

Was this working before/when did the issue start occurring?
Problem with vanilla A320 too

Is this a problem in the vanilla unmodded game?
Yes

**Comment by hotshotp** [comment] 2020-12-17 10:50
this is being worked on

**Comment by MisterChocker** [comment] 2020-12-31 05:13
duplicate of #2047

**Closed by MisterChocker** 2020-12-31 05:13 UTC
Labels: Asobo Bug, Bug
