### ISSUE TITLE
Emergency Gravity Gear Extension Handle

### ISSUE THREAD

**Issue by emmacorsa** [flybywiresim/a32nx#4742] opened 2021-05-08 05:29 UTC
### Aircraft Version

Development

### Description

To enable the Emergency Gravity Gear Extension Handle.

### References (optional)

![lg-ext-handle-2](https://user-images.githubusercontent.com/82645984/117527805-ff5ab780-b011-11eb-978a-5dd39ad8b168.jpg)

### Discord Username (optional)

Emmacorsa

**Comment by Benjozork** [comment] 2021-05-08 05:31
Duplicate of #1452

**Closed by Benjozork** 2021-05-08 05:31 UTC
Labels: Enhancement
