### ISSUE TITLE
RAT

### ISSUE THREAD

**Issue by SWR901** [flybywiresim/a32nx#5553] opened 2021-08-05 19:11 UTC
### Aircraft Version

Development

### Description

Hi There. 
I love your work on the A32NX, 
Is it possible to implement a 3d Model from the RAT aswel? 

Thx 
Greez Ben

**Comment by Benjozork** [comment] 2021-08-05 19:14
Hello,

Yes, a RAT along with pretty much every other component of the A320 will be implemented. The goal is to make this aircraft very high fidelity.

Right now we focus on normal operations though, so it will have to wait a bit.

I will close your ticket as it is a duplicate of #1668.

Thanks.

**Closed** 2021-08-05 20:08 UTC
Labels: Enhancement
