### ISSUE TITLE
[BUG] Ground spoilers do not automatically retract after landing

### ISSUE THREAD

**Issue by Codeh4ck** [flybywiresim/a32nx#3119] opened 2021-01-20 17:30 UTC
**Mod Version**
{
  "built": "2021-01-19T01:05:05+00:00",
  "ref": "",
  "sha": "",
  "actor": "Matthew Sainsbury <matthew@sainsbury.io>",
  "event_name": "manual"
}

**Describe the bug**
After ground spoilers are deployed on landing, they will not retract automatically when thrust is set to idle and speed brake lever is disarmed. I have to increase the air brake and set it back to 0% in order to have them retract. I am not sure if this is a visual error, as they don't seem to have any other effect other than appearing as deployed after setting the thrust to idle & speed brake to disarmed position.

**To Reproduce**
1. Set autobrake to low or medium before landing, ground spoilers armed
2. Spoilers deploy on reverse thrust but do not retract on idle thrust & disarmed air brake lever
3. Increase airbrake by any value and set it back to 0% - ground spoilers are retracted

**Expected behavior**
Ground spoilers should automatically retract when thrust is set back to idle and ground spoilers lever is disarmed. 

**Actual behavior**
Ground spoilers stay deployed unless I engage the airbrake (by any value) and set it back to 0%

**References**
http://www.a320dp.com/A320_DP/flight-controls/sys-7.10.2.html

**Additional context**
Could this possibly an issue with my air brake mapping? I have a TCA Airbus edition joystick and I have mapped the airbrake on the slider right below the joystic.
This was working just fine with previous development versions though just fine.

Was this working before/when did the issue start occurring?
It was working a few development versions before. I am not exactly sure when it started happening. 

Is this a problem in the vanilla unmodded game?
Haven't tested with the vanilla game.

Discord username (if different from GitHub): Codehack#6987

**Comment by MisterChocker** [comment] 2021-01-20 17:49
Also ground spoiler only retract automatically when not manually armed beforehand.
Duplicate of #https://github.com/flybywiresim/a32nx/issues/791.

**Closed by MisterChocker** 2021-01-20 17:49 UTC
Labels: Bug
