### ISSUE TITLE
If you click a link on the FlyPad on the weather map, the tablet becomes unuable

### ISSUE THREAD

**Issue by patq911** [flybywiresim/a32nx#4024] opened 2021-03-18 21:09 UTC
**Mod Version**
FBW Experimental version downloaded from the flybywire installer. (latest development version)

**Describe the bug**
The tablet is basically a web browser, and when you click one of those tiny links on the weather map it loads a page and you are unable to reset or go back. Thus making the tablet unusable.

Not sure if this would be a bug report or a feature request, but maybe add a reset button to the tablet somewhere in the cockpit?

**To Reproduce**
Zoom in and click one of those tiny blue links.

**References**
https://i.imgur.com/hqxZ1mo.png
**Additional context**
Not really anything else to add.

**Comment by Benjozork** [comment] 2021-03-18 21:19
Duplicate of #3306

**Closed by Benjozork** 2021-03-18 21:19 UTC
Labels: Bug, EFB

**Comment by patq911** [comment] 2021-03-18 21:35
@Benjozork Thanks buddy, I tried to search but I didn't find anything with "tablet" or "flypad" on the issues tracker.
