### ISSUE TITLE
jumps on route - ILS approaches

### ISSUE THREAD

**Issue by Ecam7** [flybywiresim/a32nx#4965] opened 2021-05-31 17:05 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-31T12:18:03+00:00",
  "ref": "master",
  "sha": "5e0c0dcb03e4476e85d62692797ad3a8bbbad100",
  "actor": "sidnov",
  "event_name": "manual"
}
```

### Describe the bug

Hello first of all, congratulations on the enormous work you do, I signed up to donate for this wonderful plane.

I have found the bug in ILS approaches, because it has not happened to me in RNAV. What happens is that it jumps the waypoints when it passes over the magenta D, and the approach mode is activated, it changes its course very close to the start of the ILS locator, skipping all the previous waypoints that it had not yet passed. this bug happens if it passes automatically through D magenta or when one activates the zoom mode before going through D magenta. and the change is reflected in the navigation screen showing that the new route is to the waypoint that was selected automatically, as if a direct to that point had been made.

### Expected behavior

The expected behavior is that regardless of whether I activate the approach mode before the Magenta D or the Magenta D is activated automatically, the aircraft should keep the course and continue through all the waypoints that are left before intercepting the ILS locator.

### Steps to reproduce

1. the plane meets autopilot approaching the ILS and even before the magenta D

2. the plane arrives automatically by the route established on the magenta D

3. the plane changes its course towards a waypoint closer to the approach, skipping the N waypoints that were missing before reaching the waypoint that you selected.

**Comment by Benjozork** [comment] 2021-05-31 17:30
Duplicate of #939

**Closed by Benjozork** 2021-05-31 17:30 UTC
Labels: Bug
