### ISSUE TITLE
[BUG] A320 Still sometimes sharp banks or rolls to the left before touchdown

### ISSUE THREAD

**Issue by CoffeePanda0** [flybywiresim/a32nx#1173] opened 2020-10-07 19:26 UTC
**Mod Version**

Latest master

**Describe the bug**

When coming down to land at some airports and sometimes just randomly when around 10ft, the aircraft will perform a sudden roll to the left or right, striking the wing into the ground. This is randomly triggered and I am not sure what causes it, but me and 3 friends all have had the issue.

**To Reproduce**

1. Spawn in the Rio approach in landing challenges
2. Try and land
3. At around 10ft there is a 50% chance or so of rolling to the left 

**Expected behavior**

The aircraft can land

**Actual behavior**

It banks the wing into the ground

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Since the second asobo update

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub): obama#6262

**Comment by ohnoitsBlarry** [comment] 2020-10-08 14:06
Did you change Vapp in the FMS to any other than the computed value? It shows this behaviour when it deems the approach speed too low - although the computed values for Vapp and VLS are too high compared to the real aircraft. Also you may want to stay in Managed Airspeed mode, as switching to Selected Airspeed may cause the same behaviour, even when flying at the computed approach speed.

**Comment by mc130h** [comment] 2020-10-08 15:36
This issue was solved for another person by them adjusting their roll sensitivity and deadzone in game. The issue was the spoilers were actuating with nearly every input of roll causing the aircraft to roll heavily on final approach before touch down. He thought it was a wind shear before touchdown every time. Pay attention to your flight control page and watch the up arrows on the wing spoilers to indicate they're deployed/retracted as you make your landing. If it looks too touchy, adjust that deadzone/sensitivity and retry until you find a setting that is comfortable.

**Comment by CoffeePanda0** [comment] 2020-10-08 19:50
> 
> 
> Did you change Vapp in the FMS to any other than the computed value? It shows this behaviour when it deems the approach speed too low - although the computed values for Vapp and VLS are too high compared to the real aircraft. Also you may want to stay in Managed Airspeed mode, as switching to Selected Airspeed may cause the same behaviour, even when flying at the computed approach speed.

Yeah I was on selected speed mode at 145kts on this landing, I'll try a higher landing speed next time. What speed would you normally land at?

**Comment by CoffeePanda0** [comment] 2020-10-11 16:21
Just tried landing the A320 with no wind at 155kts, still rolls sharply. Starting to make this plane unflyable if it's not possible to land

**Comment by lve0200** [comment] 2020-10-14 19:20
I would like to add, that in my case, I switch OFF the AP at 100Ft; the plane flies steady onto ground and just upon touch down, it turns heavily left.

**Comment by SWR5488** [comment] 2020-10-14 21:54
@lve0200 same here

**Comment by ThisIzDog** [comment] 2020-10-16 22:18
Same issue here. I noticed that if I begin and hold the flare at about 20-30ft, and then climb to 60-70ft, roll authority is restored. Perhaps it is something to do with a "ground effect" triggering a bug or something?

**Comment by lve0200** [comment] 2020-10-17 09:27
From my own experiments, I'm coming also more and more to the conclusion that the flair/ground effect aerodynamic model is flawed. It comes intensified w/ real weather wind (changes). I remember that in V 1.7 they'd endless flairs and I think they changed this in 1.8 probably to  the other extreme.

**Comment by e4rthdog** [comment] 2020-10-17 10:07
1 out of my 3-4 flights i get this sudden roll behavior and i always get the heavy landing feeling in any landing speed i have tried....

**Comment by donstim** [comment] 2020-10-20 22:04
Have you guys seen these posts?  https://forums.flightsimulator.com/t/a320-rolls-left-on-retard-and-flare/190230/211?u=awareplot117729

Is he in the Flybywiresim program? His posts seem to posit that it is a FBW tuning mode issue that would not necessarily be fully solved by changing aero parameters or increasing speed.

**Comment by ohnoitsBlarry** [comment] 2020-10-21 12:19
> Have you guys seen these posts? https://forums.flightsimulator.com/t/a320-rolls-left-on-retard-and-flare/190230/211?u=awareplot117729

Well, yeah, so things are pretty much working as intended from Asobo's standpoint. The aircraft does switch into Direct Law once it enters the Flare phase and/or is on the ground. So their implementation is insofar correct as it tries to emulate this behaviour despite the vanilla A320 not modelling the different flight control laws. 

I remember asking around in the Discord a couple of days ago whether anyone found a way to switch off automatic elevator trim during the flight. This is also something that the real aircraft does at exactly the same 50/100 ft radar altitudes the linked forum post describes.

**Comment by lve0200** [comment] 2020-10-21 13:01
I see a lot of focus on the plane controls & AP, but what about the aerodynamic model and Ground Effect/Winds? Ground Effect should help the plane flairing, but since it flaires like a brick, there must be something...

**Comment by Oberstumfuher** [comment] 2020-10-21 14:41
> I see a lot of focus on the plane controls & AP, but what about the aerodynamic model and Ground Effect/Winds? Ground Effect should help the plane flairing, but since it flaires like a brick, there must be something...

After this last update it looks like a meteorite hitting the asphalt and rolling so that it is everywhere except towards the center of the track.

**Comment by lve0200** [comment] 2020-10-21 14:47
>After this last update... hitting the asphalt

I don't want repeating myself too much, but 4me the significant change occured already from MS V 1.7.14 (1st release) where plane were flairing forever, and 1.8.3

**Comment by ChruutvoLuzi** [comment] 2020-10-21 14:54
> I see a lot of focus on the plane controls & AP, but what about the aerodynamic model and Ground Effect/Winds? Ground Effect should help the plane flairing, but since it flaires like a brick, there must be something...

check the PRs, there are several improvements in the final stage

**Comment by CoffeePanda0** [comment] 2020-10-21 15:00
> 
> 
> > I see a lot of focus on the plane controls & AP, but what about the aerodynamic model and Ground Effect/Winds? Ground Effect should help the plane flairing, but since it flaires like a brick, there must be something...
> 
> check the PRs, there are several improvements in the final stage

yeah, hopefull #1295 should help fix or alleviate the issue

**Comment by ChruutvoLuzi** [comment] 2020-10-21 21:01
> > 
> 
> > 
> 
> > > I see a lot of focus on the plane controls & AP, but what about the aerodynamic model and Ground Effect/Winds? Ground Effect should help the plane flairing, but since it flaires like a brick, there must be something...
> 
> > 
> 
> > check the PRs, there are several improvements in the final stage
> 
> 
> 
> yeah, hopefully #1295 should help fix or alleviate the issue

Yeah i have been testing it in the last few days and had almost zero issues while landing

**Comment by MisterChocker** [comment] 2020-10-21 21:42
For me my rudder sensitivity/deadzone needed some weeking because it sometimes had "phantom" inputs which were little but somehow caused the plane to dip. (Same for joystick z axis)

**Comment by Smiths76245** [comment] 2020-10-22 10:17
I still observe this issue, albiet it has been reduced slightly. But for example, landing challenge at Paro, the left bank required into the landing zone, at the crucial 80 - 50ft height the bank is 'locked' in place and right alerion input seems ignored for a second or 2, around 40 or 30 ft, it responds and there is an over correction tendancy. Gilbrator landing challenge was better as was more wings-level over the keys but the feeling of less to none alerion response is there. It still better than the default behaviour but unfortuntely still there in how I described in those situations.

**Comment by henrikx** [comment] 2020-10-22 19:54
Is it correct that this issue should be closed now considering #1295 not entirely solves the issue?

**Comment by nonocaptain** [comment] 2020-10-22 19:58
I’m agree with henrikx #1295 not entirely solves the issue !

**Comment by dickbig2** [comment] 2020-10-24 06:10
Still a big problem for me as this kind of abnormal rolling/banking effect makes hand fly landing quite difficult to pull off. Almost everytime when I'm close to the runway like 30-50ft above it, the aileron just didn't react and keep rolling/banking to either directions. This particularly affect my crosswind or windy day landing as i will have to constantly correct the attitude of my plane during approach until the moment before touch down. Any slight correction above the runway will results in big roll or bank. Unless you have lined with the runway perfectly, if you are still doing correction above the runway Like 30-50ft then this issue will occurs.

**Comment by Benjozork** [comment] 2020-10-24 06:23
@henrikx @nonocaptain that PR should not have closed this issue. I merged it, so it says I closed it but it was done automatically by GitHub due to erroneous content of the PR description.

**Comment by Benjozork** [comment] 2020-10-24 06:38
This is actually a duplicate of  #974 - let's continue there.

**Closed by Benjozork** 2020-10-24 06:38 UTC
Labels: Bug, Plane Performance
