### ISSUE TITLE
[BUG] A320 pulling up without rotating the joystick

### ISSUE THREAD

**Issue by kaese5128** [flybywiresim/a32nx#3560] opened 2021-02-16 21:34 UTC
**Mod Version**
I'm using the latest dev. Version.

**Describe the bug**
Since todays World Update UK the A320 is pulling up automaticly at around 120/130 KT without touching the joystick.

**To Reproduce**

1.Start a flight with the Flybywire A320 at any runway
2.Set Takeoff Thrust 
3.The airplane is going to the air without rotating between 110-130 KT. 

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Since the latest World Update UK. 

Is this a problem in the vanilla unmodded game?
Yes also in the official A320. 

Discord username (if different from GitHub):

**Comment by talon03** [comment] 2021-02-16 22:15
I'd add - in the landings I've done since today's update, the aircraft has over-flaired rather hard, and then also attempted to get airborne again

**Comment by Watsi01** [comment] 2021-02-16 22:23
It's been worked on.

**Comment by hotshotp** [comment] 2021-02-16 23:09
fixed in custom flybywire

**Comment by donstim** [comment] 2021-02-16 23:56
> fixed in custom flybywire

I don't think so. I think it just didn't affect that version as much.

**Comment by hotshotp** [comment] 2021-02-17 04:44
> > fixed in custom flybywire
> 
> I don't think so. I think it just didn't affect that version as much.

Ah my bad, I misunderstood. Looks like this was caused by new update

**Comment by diegosala** [comment] 2021-02-17 04:53
On landing, it over-reacts on the flare, can even say that it flairs on its own, have to pull the stick to get it down. This is since today's update.

**Comment by marcman86** [comment] 2021-02-17 04:58
Fix is in testing and will gets implemented afterwards.

https://github.com/flybywiresim/a32nx/pull/3564

**Comment by ChisanaKita** [comment] 2021-02-17 08:49
Yea, can confirm. Just had 2 GA while landing RJTT. One more things, when approaching I've encountered the old "Not turning in course" bug, in my case the aircraft turns 270 deg instead of the next waypoint (KANOH).

**Closed** 2021-02-17 18:38 UTC
Labels: Bug, Plane Performance
