### ISSUE TITLE
Cost Index not affecting cruise speed and efficiency

### ISSUE THREAD

**Issue by Asianblade** [flybywiresim/a32nx#4428] opened 2021-04-13 15:17 UTC
**Mod Version**
Experimental Current Latest: 2a04c98

**Describe the bug**
The aeroplane travels at a faster speed with less efficiency and shorter flight time with a higher cost index; travels at a slower speed with high efficiency and a longer flight time with a lower cost index. When entering different CI's, nothing changes.

**To Reproduce**
1. Load in a flight.
2. Try out different cost indexes (recommend 5, 10, 20, 60), reach cruise altitude above 31000 feet.
3. Compare with each flight, see if the speed varies.

**Expected behaviour**
Higher Cruise Speed and faster fuel drain when typing higher cost index, Lower Cruise Speed and slower fuel drain when typing lower cost indexes. 

**Actual behaviour**
After entering the CI and reaching the mach speed at cruise alt, nothing changes.

**References**
![image](https://user-images.githubusercontent.com/77690813/114576727-fba37180-9cad-11eb-8c0a-88a46139cc97.png)

**Additional context**

Was this working before/when did the issue start occurring?
I don't think it's a feature currently in the mod (even in the old versions), but keep up the great work!

Is this a problem in the vanilla unmodded game?
If the A32nx doesn't have it, then I don't believe the normal 320neo has it.

Discord username (if different from GitHub): Wesley#0008 (Wesley#TripleZero8)

**Comment by MisterChocker** [comment] 2021-04-13 17:03
Duplicate of #345

**Closed by MisterChocker** 2021-04-13 17:03 UTC
Labels: Bug
