### ISSUE TITLE
CTD ECAM FBW 320

### ISSUE THREAD

**Issue by Axis360** [flybywiresim/a32nx#6680] opened 2022-02-09 10:00 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-02-08T23:45:21+00:00",
  "ref": "master",
  "sha": "a104495e0171a7561267f110ca718e7d0d108cbf",
  "actor": "IbrahimK42",
  "event_name": "manual"
}
```

### Describe the bug

I noticed a problem with the FBW A320 (development version).

I can reproduce it quite often, but unfortunately not all the time, it's still quite random, but when I'm on the ground if I do a status ECAM so that I press SYST, CLR then I press SYST again very often MSFS crashes and it's back to the desktop.

Error message :
Faulting application name FlightSimulator.exe, version: 0.0.0.0, timestamp: 0x00000000
Faulting module name: FlightSimulator.exe, version: 0.0.0.0, timestamp: 0x00000000
Exception code: 0xc0000005
Error Offset: 0x000000000130d0ea
Faulting Process ID: 0x27d8
Faulting application start time: 0x01d81d8f2400ca40
Faulting application path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.22.2.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Faulting module path: C:\Program
Files\WindowsApps\Microsoft.FlightSimulator_1.22.2.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Report ID: 01c0f065-5599-48d9-9c7c-d160b14f3aea
Faulting package full name: Microsoft.FlightSimulator_1.22.2.0_x64__8wekyb3d8bbwe
Faulting Package Relative Application ID: App

### Expected behavior

Press the SYST button then CLR RCL and press SYST again

Return to office

### Steps to reproduce

Yesterday no problem today crash before yesterday crash and I was able to reproduce it 2 times in a row...

**Comment by sidnov** [comment] 2022-02-21 10:21
Duplicate of #6378

**Closed by sidnov** 2022-02-21 10:21 UTC
Labels: Bug
