### ISSUE TITLE
Adding the FlightPad to the MCDU Server 

### ISSUE THREAD

**Issue by GaForgone** [flybywiresim/a32nx#7289] opened 2022-06-10 08:05 UTC
### Aircraft Version

Experimental

### Description

add where the MCDU server can double where you can control the flight pad from the browser and or add a norther server you run for it though a different web port because that would be awesome for some simers like me so we can have it where you just cam make a mersive at home cockpit if someone wanted two with simconnect and FSU for flight sim 

### Discord Username (optional)

GA.FORGONE#3679

**Comment by Benjozork** [comment] 2022-06-10 13:40
Duplicate of #6978

**Closed** 2022-06-10 13:41 UTC
Labels: Request
