### ISSUE TITLE
[BUG] COM Frequencies are not updated on Radio display if changed with external program e.g. Pilot2ATC

### ISSUE THREAD

**Issue by dornus** [flybywiresim/a32nx#2865] opened 2021-01-04 07:35 UTC
**Mod Version**

{
  "built": "2020-12-23T05:49:09+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
} 

**Describe the bug**

If I control the COM frequencies with an external programm, in my chase Pilot2ATC via FSUIPC7, the frequencies which are set in there are not displayed correctly on the radios within cockpit. I have to press VHF1 at the radio to force an update of the frequency on the display.

**To Reproduce**

1. Connect Pilot2ATC via FSUIPC7 to the sim and set the needed com frequencies in there
2. Check active frequencies in cockpit-> they are not following the setting defined in Pilot2ATC
3. need to press VHF1 to force to update the display in cockpit

**Expected behavior**

Radio frequencies which are set externally should be updated within cockpit too

**Actual behavior**

Radio frequencies are not updated if changed with external programms.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
NO

Is this a problem in the vanilla unmodded game?
This was an issue with Vanilla before too, but was fixed with latest MSFS update v1.12.13.0.  So with Vanilla it's OK  but not OK in FBW mod

Discord username (if different from GitHub):
Dornus#7758

**Comment by MisterChocker** [comment] 2021-01-05 00:11
looks like a duplicate of #2709.
Could also be related to #2644.

**Comment by dornus** [comment] 2021-01-05 05:35
Hi,
seems to be more like #1079 but with the difference that vanilla is working now. Sorry for duplicate.
But as mentioned in my post, this was an issue with vanilla too before update to 1.12.13.0 but this update fix this in vanilla.
Would be nice if this will be fixed in A32nx  too.

**Comment by MisterChocker** [comment] 2021-01-05 16:59
Thanks for your comment anyways, I will close this issue since it looks to match #1079. Fyi this issue wont be lost since it's being linked in our main issue then, so we still have your input.
Duplicate of #1079

**Closed by MisterChocker** 2021-01-05 16:59 UTC
Labels: Bug, RMP, Waiting For Response

**Comment by paulpenney** [comment] 2021-01-26 00:50
I'm having the same issue. Using external commands does not reflect any changes on the COM frequencies, although I do see something changing on my end, its not reflected in the sim. Works great on all other planes.
