### ISSUE TITLE
Experimental: Altitude does not continue to decrease in managed mode

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#4221] opened 2021-04-01 08:10 UTC
**Mod Version**
"built": "2021-03-31T15:16:20+00:00",
"ref": "autopilot",

**Describe the bug**
When top of descent has been reached, I changed target altitude from 12000ft to 3000ft in managed mode. The plane starts the descent but stopped descending. When deceleration point has been reached, then the target speed changed to approach one on PFD (speed is in managed mode too). After that, only the target speed seems to be taken into account and the altitude stays at 9000 ft (that was the altitude constraint of the point before deceleration point). I have to set a vertical speed in manual mode.

The actions on the autopilot panel was done in game directly.

**To Reproduce**
Change target altitude to approach altitude when top of descent is reached (managed mode).
It is better if the point before deceleration point has an altitude constraint (ex: 9000ft for me) because the altitude stayed blocked to the altitude of this constraint so I do not know if it is linked?

**Expected behavior**
Altitude should decrease to this target altitude gradually during descent but it stayed blocked.

**Actual behavior**
Altitude stayed blocked to 9000 ft.

**References**

**Comment by ChruutvoLuzi** [comment] 2021-04-01 09:07
VNAV is not implemented yet, the managed speed part was simply because it switched into the Approach Phase at Decel

**Comment by phildeg31** [comment] 2021-04-01 09:19
Yes I know that it switches to approach phase at decel point but the altitude, set to 3000 ft before at top of descent, stayed blocked to 9000ft and only the speed is decreasing and not the altitude. I do not know why because target altitude has been set to 3000ft. Without engaging manual mode with a vertical speed, the altitude does not decrease.

**Comment by MisterChocker** [comment] 2021-04-01 09:20
Do you have the airport + arrival? I assume you had an alt constraint.

**Comment by phildeg31** [comment] 2021-04-01 09:23
Yes I set everything before take off (INIT page, flight plan with altitude constraints for 2 points in my case, and PERF pages).

**Comment by MisterChocker** [comment] 2021-04-01 09:25
Can you post the airport + arrival?

**Comment by phildeg31** [comment] 2021-04-01 09:29
What do you mean by arrival? The runway has been set as arrival. Il my case I did, as always for training, LFBO (runway 32L) to LFBD (runway 23). Flight with IFR low altitude (cruise altitude = FL120). Add LERGI point before arrival airport and then select ILS23 with VELI9K for star via VAGNA. Altitude constraint has been set to 9000ft (FL90) for VELIN point.

**Comment by phildeg31** [comment] 2021-04-01 10:18
Ok I did a new test and it stays blocked with the altitude constraint as you can see on this screens:
![1](https://user-images.githubusercontent.com/74733393/113280284-5cad6b80-92e4-11eb-8174-79d060d29e88.JPG)
![3](https://user-images.githubusercontent.com/74733393/113280313-67680080-92e4-11eb-88a7-2cf729a2d8ca.JPG)

**Comment by MisterChocker** [comment] 2021-04-01 16:21
Issue has been fixed with https://github.com/flybywiresim/a32nx/commit/dfc3d3bb98c5a07e4f9e51dbf07f4914ee0f9d2a.
Please update and see this works now as intended.

**Comment by phildeg31** [comment] 2021-04-04 05:47
Thank you. I will try next week because I am not at home this week-end. I will give a feedback.

**Comment by MisterChocker** [comment] 2021-04-04 14:02
Closing as it's working now, please reopen if issue appears again.

**Closed by MisterChocker** 2021-04-04 14:02 UTC
Labels: Autopilot, Bug, Waiting For Response
