### ISSUE TITLE
[BUG] No automatic refresh for ND - Constraints are not the same between MCDU, ND and PFD

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#2165] opened 2020-12-01 17:53 UTC
I tested the last developer version because Ihad problems whith AP not following route and flight plan. This seems to be solved but I saw another issue with constraints between MCDU, ND and PFD:
https://zupimages.net/viewer.php?id=20/49/fxz4.jpg
https://zupimages.net/viewer.php?id=20/49/ctdg.jpg

As you can see, in MCDU I have 8000 feets (FL80) for VELIN and 7000 feets (FL70) for BMC35. On the ND, I have FL150 displayed for theses points (it corresponds to the value before changing it before the flight). On the PFD, FL080 is displayed and taken into account (altitude in MCDU for VELIN so it is good). The  ND does not display the good altitude.

I do not know if it is an issue due to the mod.

To reproduce:
- flight plan from LFBO (runway 32L) to LFBD (runway 23) with cruize altitude of 12000 feets
- suppress SAU waypoint
- do not set an approach
- Launch the flight
- In MCDU, do the following changes for flight plan and approach:
 * approach ILS 23 with star VELI9K via VAGNA
 * LACOU = FL120
 * SECHE = FL120
 * VELIN = FL80
 * BMC35 = FL70

Edit: I have to turn off and turn on the constraints to have good values.

**Comment by MisterChocker** [comment] 2020-12-01 19:42
The constraint's shown are BELOW constraints on descent which are being ignored. The altitude shown on the flight plan page is the predicted altitude. If you open the vert ref page of the waypoints, you will the their constraints are the same as shown on the nd. So nothing wrong from that perspective.

**Comment by MisterChocker** [comment] 2020-12-01 19:43
btw ![image](link) for the images to show.

**Comment by Benjozork** [comment] 2020-12-01 20:08
Please edit to respect the provided template.

**Comment by phildeg31** [comment] 2020-12-01 20:16
I expect to have the constraints set in MCDU on the ND. For example for VELIN I expect FL80 on the ND instead of FL150 that was the default value when setting the approach. As I updated it to FL80 I expect this new value.

Am I wrong?

**Comment by MisterChocker** [comment] 2020-12-01 20:20
Oh, when changing constraints you need to turn OFF and then ON the constraint mode on the ND, we haven't figured out yet how to refresh them.

**Comment by MisterChocker** [comment] 2020-12-01 20:34
So the issue is, that you have changed the constraint manually and the ND didn't showed that change?

**Comment by phildeg31** [comment] 2020-12-02 07:32
Ok so when turningoff andon constraints, it works fine (I have good constraints displayed on ND). I thought it would be refreshed automatically.
Do you want me to close this ticket or to keep it opened for working on an automatically refresh?

Thank you for your answer.

**Comment by MisterChocker** [comment] 2020-12-02 09:24
> the green dot on PFD for flaps 1) but I

green dot only visible when in clean config.

**Comment by phildeg31** [comment] 2020-12-02 09:29
Oh ok I opened a ticket for the green dot.

**Comment by MisterChocker** [comment] 2021-03-26 11:46
Duplicate of #1297

**Closed by MisterChocker** 2021-03-26 11:46 UTC
Labels: Bug, Flight Plan, ND (Navigation Display)
