### ISSUE TITLE
AP TOD implimination 

### ISSUE THREAD

**Issue by Swaluver88** [flybywiresim/a32nx#4860] opened 2021-05-20 17:08 UTC
### Aircraft Version

Stable

### Description

I have been flying the FBWA320 lately just trying to get into flying inb MSFS. However it is pretty frustrating to use the TOD Calculator. is there any plans for the AP system to have a TOD implemented and realistically matched?

### Discord Username (optional)

alex k#8228

**Comment by Benjozork** [comment] 2021-05-20 17:10
Duplicate of #856

**Closed by Benjozork** 2021-05-20 17:10 UTC
Labels: Enhancement
