### ISSUE TITLE
[BUG] Cannot delete or edit waypoints in a STAR

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#1388] opened 2020-10-16 07:19 UTC
**Mod Version**
0.4.0

**Describe the bug**
I insert an Simbrief created Flightplan in Sim and therefore also in A320 . 
I see the complete Plan with SID , TRANS and STAR. 
But all of the Waypoints are in Color blue not in green Color. 

**To Reproduce**
1. Create Flightplan in Simbrief
2.Load it in to FS2020
3.Start Flight

**Expected behavior**
All Waypoints in FMC Flightplan Page should be in Green Color and deleteable . 

**Actual behavior**
All Waypoints in FMC are in Blue Color. 
It is not possible to delete any of this Waypoints . 

**Why the Waypoints are blue and not Green ? Thanks** 

<img width="619" alt="2020-10-16 07_11_18-Microsoft Flight Simulator - 1 9 5 0" src="https://user-images.githubusercontent.com/50043259/96224980-aac9ef00-0f90-11eb-85ee-5ff3f5f95e8d.png">

**Here u can see this Function in P3D with FSLabs .** 

<img width="1168" alt="2020-10-16 09_28_54-Lockheed Martin® Prepar3D® v5 with WideServer_ waiting for clients" src="https://user-images.githubusercontent.com/50043259/96226206-9850b500-0f92-11eb-9daf-28b225dfcb56.png">

**All waypoints are deletable**

<img width="747" alt="2020-10-16 09_31_26-Lockheed Martin® Prepar3D® v5 with WideServer_ waiting for clients" src="https://user-images.githubusercontent.com/50043259/96226216-9dadff80-0f92-11eb-8c48-4816c51ace16.png">

**References**

**Comment by PuL9** [comment] 2020-10-16 07:26
Green colored waypoint is the one that is targeted right now by the autopilot https://i.imgur.com/AisOYMe.png

**Comment by SM-396** [comment] 2020-10-16 07:35
Ok , but thats not correct . Normally all inserted Waypoints should shown in Green Color.

**Comment by PuL9** [comment] 2020-10-16 07:38
> Ok , but thats not correct . Normally all inserted Waypoints should shown in Green Color.

Your screenshots are from a different sim, im not sure how it works there

**Comment by SM-396** [comment] 2020-10-16 07:44
The First Pic is from MFS2020 . The second and third from P3D with FSlabs Airbus . My Unkle is Airbus Captain and he told me that the Pics from P3D shows like it is in real . I think its an MFS2020 / A320X Mode behaviour .

**Comment by Lessar277** [comment] 2020-10-16 07:57
going by [this resource](http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.8.1.html), flight plan waypoints should absolutely be green, not blue.

**Comment by SM-396** [comment] 2020-10-16 07:59
> going by [this resource](http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.8.1.html), flight plan waypoints should absolutely be green, not blue.

Means you are at my Site - this is an Bug from FS2020 or A320X Mode ?

**Comment by dc1ps2** [comment] 2020-10-16 08:08
I also found that in the recent update version, when I plan a route, I can no longer modify the runway as I did before version 0.3.1. Whenever I click the approach target to set the runway, There will be a longitude and latitude coordinate prompt asking me to choose, and when I choose, he will add waypoints by himself, instead of directly entering the airport menu and letting me choose the runway

**Comment by SM-396** [comment] 2020-10-16 08:10
> I also found that in the recent update version, when I plan a route, I can no longer modify the runway as I did before version 0.3.1. Whenever I click the approach target to set the runway, There will be a longitude and latitude coordinate prompt asking me to choose, and when I choose, he will add waypoints by himself, instead of directly entering the airport menu and letting me choose the runway

Its another Bug in the 0.4.0 Version , look here : https://github.com/flybywiresim/a32nx/issues/1378

**Comment by dc1ps2** [comment] 2020-10-16 08:16
> > 我還發現，在最新的更新版本中，當我計劃路線時，不能再像在0.3.1版本之前那樣修改跑道。每當我單擊進場目標設置跑道時，都會出現一個經度和緯度坐標提示，要求我選擇，當我選擇時，他將自己添加航路點，而不是直接進入機場菜單並讓我選擇跑道
> 
> 它是0.4.0版本中的另一個錯誤，請看此處：[＃1378](https://github.com/flybywiresim/a32nx/issues/1378)

Thank you, there is another situation I don’t know if it’s a bug. After the cold cabin is started, there is a "GPU PRIMARY LOST" message on the INIT page. I don’t know how to eliminate it.

**Comment by ChruutvoLuzi** [comment] 2020-10-16 08:21
> > > 我還發現，在最新的更新版本中，當我計劃路線時，不能再像在0.3.1版本之前那樣修改跑道。每當我單擊進場目標設置跑道時，都會出現一個經度和緯度坐標提示，要求我選擇，當我選擇時，他將自己添加航路點，而不是直接進入機場菜單並讓我選擇跑道
> > 
> > 
> > 它是0.4.0版本中的另一個錯誤，請看此處：[＃1378](https://github.com/flybywiresim/a32nx/issues/1378)
> 
> Thank you, there is another situation I don’t know if it’s a bug. After startup, there is a "GPU PRIMARY LOST" message on the INIT page, I don’t know how to eliminate it.

CLR should do the job as in real life

**Comment by PuL9** [comment] 2020-10-16 08:53
> going by [this resource](http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.8.1.html), flight plan waypoints should absolutely be green, not blue.

This website does not look like it's an official statement by Airbus that they should be green colored and blue ones looks better in my opinion

**Comment by SM-396** [comment] 2020-10-16 09:01
> > going by [this resource](http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.8.1.html), flight plan waypoints should absolutely be green, not blue.
> 
> This website does not look like it's an official statement by Airbus that they should be green colored and blue ones looks better in my opinion

What i know is that inactive WP looks blue and in AP activated WPs are green .

**Comment by lousybyte** [comment] 2020-10-16 09:12
You can't delete waypoints part of a SID/STAR, you should be able to delete any other enroute waypoints. Colors are unrelated to the issue.

**Comment by SM-396** [comment] 2020-10-16 09:18
> You can't delete waypoints part of a SID/STAR, you should be able to delete any other enroute waypoints. Colors are unrelated to the issue.

Its not right . Because i talk with an real A320 Pilot . It imust of course be possible to delete Waypoints from SID or STAR because the Traffic Control has the last word and you must be able to change or delete this Waypoints !!!!

**Comment by PuL9** [comment] 2020-10-16 09:23
> > You can't delete waypoints part of a SID/STAR, you should be able to delete any other enroute waypoints. Colors are unrelated to the issue.
> 
> Its not right . Because i talk with an real A320 Pilot . It imust of course be possible to delete Waypoints from SID or STAR because the Traffic Control has the last word and you must be able to change or delete this Waypoints !!!!

Maybe you misunderstood and he meant that you can change the STAR itself which will change waypoints, but not manually removing one of the STAR waypoints?

**Comment by SM-396** [comment] 2020-10-16 09:42
> > > You can't delete waypoints part of a SID/STAR, you should be able to delete any other enroute waypoints. Colors are unrelated to the issue.
> > 
> > 
> > Its not right . Because i talk with an real A320 Pilot . It imust of course be possible to delete Waypoints from SID or STAR because the Traffic Control has the last word and you must be able to change or delete this Waypoints !!!!
> 
> Maybe you misunderstood and he meant that you can change the STAR itself which will change waypoints, but not manually removing one of the STAR waypoints?

Onesmore - It is at every time possible to delete every Waypoint in the FP Page in FMC of the A320 . Its Fact . 
But in the real Plane and also on my Photos from P3D as you can see above the FP Waypoints have to be green not blue as in the FS2020 FP. The Error in FS2020 / A320X Mode is that only the next Waypoint in FP is green ( means deletable ) the other waypoints are blue and therefore not deletable. This is for me an very big BUG.

**Comment by Lessar277** [comment] 2020-10-16 09:44
> > going by [this resource](http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.8.1.html), flight plan waypoints should absolutely be green, not blue.
> 
> This website does not look like it's an official statement by Airbus that they should be green colored and blue ones looks better in my opinion

How about the [Thales FMGS documentation](http://www.smartcockpit.com/docs/Smiths_Thales_A_1_0_1_FM_Pilot_Guide.pdf), page 76, for reference. Page 82 also has a nifty color code guide. It is very well possible that the Airbus in-game models the Honeywell FMGS, but I have not been able to find documentation for that.

I am not a real 320 pilot, just someone interested in the subject. Maybe we should get some pilot feedback on both the color and the ability to remove SID/STAR waypoints. 

Regardless, I don't think personal color preference should play a part in what is or is not implemented.

**Comment by SM-396** [comment] 2020-10-16 09:51
> > > going by [this resource](http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.8.1.html), flight plan waypoints should absolutely be green, not blue.
> > 
> > 
> > This website does not look like it's an official statement by Airbus that they should be green colored and blue ones looks better in my opinion
> 
> How about the [Thales FMGS documentation](http://www.smartcockpit.com/docs/Smiths_Thales_A_1_0_1_FM_Pilot_Guide.pdf), page 76, for reference. Page 82 also has a nifty color code guide. It is very well possible that the Airbus in-game models the Honeywell FMGS, but I have not been able to find documentation for that.
> 
> I am not a real 320 pilot, just someone interested in the subject. Maybe we should get some pilot feedback on both the color and the ability to remove SID/STAR waypoints.
> 
> Regardless, I don't think personal color preference should play a part in what is or is not implemented.

Sorry, but either you're working on getting a realistic A320 or not . The Color of the Waypoints of an active FP in FMC of an A320 is green. The only reason can be that this is an part of the Asobo default Model which cant be changed.

**Comment by Lessar277** [comment] 2020-10-16 09:55
> Sorry, but either you're working on getting a realistic A320 or not . The Color of the Waypoints of an active FP in FMC of an A320 is green. The only reason can be that this is an part of the Asobo default Model which cant be changed.

I was agreeing with you and provided documentation to reference exactly that. I am not a dev.

**Comment by Berniep94** [comment] 2020-10-16 11:11
> > You can't delete waypoints part of a SID/STAR, you should be able to delete any other enroute waypoints. Colors are unrelated to the issue.
> 
> Its not right . Because i talk with an real A320 Pilot . It imust of course be possible to delete Waypoints from SID or STAR because the Traffic Control has the last word and you must be able to change or delete this Waypoints !!!!

Well, in real life, it dosent work like that the ATC dosent have the last word, its a conbination of both (ATC and Pilot), an ATC can tell you descent via your STAR and you have a huge TS ahead of you can go throw it or you can ask the ATC for a deviation... so there are a lot of factors that apply in real life, like a direct or intercept a vector limit, or enter a holding pattern, etc... but in this case you dont have to delete or modify anything in your SID and STARS thats why they are called Standar Instrument Departure and Standar Terminal Arrival  Route, and when you have atc instruction you just follow the instruction and as simple as clicking DIRECT TO and thats it, you dont need to erase any SID or STAR waypoint.

Good luck mate!

**Comment by lousybyte** [comment] 2020-10-16 11:23
> You can't delete waypoints part of a SID/STAR, you should be able to delete any other enroute waypoints. Colors are unrelated to the issue.

I was stating how it's now in the game, not how it should be. Deleting waypoints part of a SID/STAR will crash the game if allowed.

**Comment by Watsi01** [comment] 2020-10-16 11:24
Mostly I've seen green MCDU FP waypoints (with the active one white). But it also can be a preference order of the respective airline how the colors are...

**Comment by Berniep94** [comment] 2020-10-16 11:27
> > You can't delete waypoints part of a SID/STAR, you should be able to delete any other enroute waypoints. Colors are unrelated to the issue.
> 
> I was stating how it's now in the game, not how it should be. Deleting waypoints part of a SID/STAR will crash the game currently if allowed.

I compleatly understand that man, i know that the sim is getting a tons of bugs, and im agree with that, im just saying, what happens in real life... getting into a SID or a STAR departure, thats it. Hahahaha

**Comment by Runway04R** [comment] 2020-10-16 13:45
I have been able to delete waypoints in a STAR.  However, I do not import the flight plan from Simbrief, I program the flight plan directly into the MCDU (using the current Navigraph updates).  For example, I flew into KBOS last night via the ROBUC3 for Runway 22L.  When I programmed the arrival into the MCDU, the path took me to a transition west of the airport which is not correct.  I deleted all the incorrect waypoints (by pressing CLR, then key next to the waypoint that I want to delete, then TMPY INSERT).  I then manually entered the waypoints for the correct path to the east with the altitude restrictions.  I had the same type of issue at KATL where the where a STAR transition took me north of the airport, I deleted it, and manually entered the opposite transition.

I have had weird things happen to my flight plans in the MCDU when I have tried importing them from Simbrief or even using the default flight planner.  This is why I just program flight plans directly into the MCDU.  Correct me if I am wrong, but I think there is a known Asobo bug for the issue of it not being able to recognize multiple runway transitions for one STAR procedure. 

As far as not being able to delete waypoints, I wonder if the problem is because you are essentially importing it through the default flight planner.  I am not a programmer or a dev, but I think something is bugged between the flight planner and the results you get in the MCDU.
![robuc3](https://user-images.githubusercontent.com/72980815/96265514-87ed0a00-0f93-11eb-8dca-115bd73d4b39.JPG)

**Comment by lousybyte** [comment] 2020-10-16 15:15
There are a lot of known issues with the MCDU, some of them are being worked on as we speak by talented people, others will take a bit longer to address. With time, the SDK will improve as well, so we'll be able to iron out most of the issues eventually.

**Comment by Benjozork** [comment] 2020-10-17 01:09
Alright everyone, remember to keep the issue on-topic and open separate issues for separate problems.

I will mark unrelated comments as off-topic - do not take this personally. I am simply clearing up the discussion here so we can focus on @SM-396's main issue.

**Comment by Benjozork** [comment] 2020-10-17 01:12
@dc1ps2, please open separate issues for your problems and avoid commenting about unrelated problems. we need to keep discussion focused so we don't loose track of the problem.

**Comment by SM-396** [comment] 2020-10-17 07:59
Here you can see an Video of my Problem . What i do wrong ?!?!
Its not possible to delete the Waypoints in blue color. 
I use the newest Master Version . I lost the overview of this Post , sorry . 
Is this now an Bug or do i something wrong ? 

https://streamable.com/r59hu4

**Comment by olski320** [comment] 2020-10-17 15:44
For example, why it's necessary: FS2020 database STAR doesn't match RL one and you want to modify it.

**Comment by SM-396** [comment] 2020-10-17 22:33
> For example, why it's necessary: FS2020 database STAR doesn't match RL one and you want to modify it.

Hi, what do you mean exactly with RL ? Thanks

**Comment by olski320** [comment] 2020-10-18 07:23
Apologies, by RL I meant real life. 
My yesterday's case: NZWN STAR WARDS5A http://www.aip.net.nz/pdf/NZWN_33.5_33.6.pdf
If you put it in FMS in A32NX using default MSFS2020 airac database it's totally wrong and you can't make it right because only route waypoints can be deleted, not SID/STAR ones.

**Comment by SM-396** [comment] 2020-10-18 09:52
> Apologies, by RL I meant real life.
> My yesterday's case: NZWN STAR WARDS5A with ILS 34 approach http://www.aip.net.nz/pdf/NZWN_33.5_33.6.pdf
> If you put it in FMS in A32NX using default MSFS2020 airac database it's totally wrong and you can't make it right because only route waypoints can be deleted, not SID/STAR ones.

Ok, But i use the Navdata AIRACS .

**Comment by olski320** [comment] 2020-10-18 10:10
Doesn't really matter which database is used - it should be possible to
remove/edit any waypoint.

**Comment by Runway04R** [comment] 2020-10-18 13:11
I have been able to change STAR waypoints, but only by entering the entire flight plan from start to finish directly into the MCDU and by not using the MS flight planner or anything that involves a .pln file(i.e. import from Simbrief) at all.  In order to stay directly on topic, I will leave it at that.

**Comment by Benjozork** [comment] 2020-10-22 16:47
@olski320 - there are programming-related considerations you might not be aware of.

**Comment by ties1717** [comment] 2020-12-28 20:36
I have the same problem. I have spoken to an easyjet pilot who fly's a320 and he said that you can delete/add waytpoints in the sid/star so this is not matching with real life. So when are they gonna change this?

**Comment by Benjozork** [comment] 2020-12-28 20:44
This is a limitation of MSFS, and will be fixed by integrating a custom flight plan manager. There is no ETA on this at the moment.

**Comment by ties1717** [comment] 2020-12-28 21:11
> This is a limitation of MSFS, and will be fixed by integrating a custom flight plan manager. There is no ETA on this at the moment.

What is a custom flight plan maneger

**Comment by Benjozork** [comment] 2020-12-28 21:12
Basically replacing the code that deals with flight plans.

MSFS does not allow editing arrival waypoints by default.

**Comment by ties1717** [comment] 2020-12-28 21:18
Oke how can i do that?

**Comment by Benjozork** [comment] 2020-12-28 21:25
You cannot. It's something we have to do at some point, it's gonna take time.

**Comment by ties1717** [comment] 2020-12-28 21:29
Ohw that Unfortunately. How long is it gonna take?

**Comment by Benjozork** [comment] 2020-12-28 21:31
No ETA.

**Closed** 2021-11-21 02:27 UTC
Labels: Bug, Critical Bug, MCDU, FPM, fixed in cFPM
