### ISSUE TITLE
[BUG] ECAm bleed page seems a bit messed up

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#1263] opened 2020-10-12 08:21 UTC
**Mod Version**

current master

**Describe the bug**
After implementing PR #1238 the bleed page seems to be a bit messed up.

**To Reproduce**

1. Enter cold&dark
2. follow the normal procedures to start the engines
3. turn the air cond temps to 12 o'clock
4. when engines running switch to ECAM bleed page

**Expected behavior**
Lower temps on the outflow. A single line/pointer below. 

**Actual behavior**
see below

**References**
![bleedpage](https://user-images.githubusercontent.com/72334392/95722449-3f241100-0c74-11eb-8935-5aa3b82403e4.jpg)

**Additional context**

Was this working before/when did the issue start occurring?
see above

**Comment by Benjozork** [comment] 2020-10-12 17:33
Probably fixed by #1209

**Comment by nikotina91** [comment] 2020-10-12 17:53
yeah the problem is the values that the knobs's simvars take, that version of the bleed page used the old values (0,1,2) while pr 1238, which made the knobs continuous, lets the simvars assume values from 0 to 100, as you can imagine that messes up all kind of things (outflow calculations in particular), up to date pr 1209 works fine and was tested today.

**Comment by Watsi01** [comment] 2020-10-12 18:03
Thanks! Then I close this issue.

**Comment by Benjozork** [comment] 2020-10-12 18:17
No need, issues usually stay open until they are fixed.

**Comment by Watsi01** [comment] 2020-10-12 18:42
Ok. Didn't know. Thx.

**Closed** 2020-10-13 02:54 UTC
Labels: Bug
