### ISSUE TITLE
[BUG] A/THR stays on FMA when thrust levers brought to idle

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#1982] opened 2020-11-16 23:14 UTC
**Mod Version**

Latest stable

**Describe the bug**

When the thrust levers are brought to the idle detent, the autothrust should completely disconnect. This means "A/THR" should disappear from the FMA.

**To Reproduce**

1. Have the autothrust on.
2. Move thrust levers to idle detent.
3.

**Expected behavior**

Moving the thrust levers to idle is a way to disconnect the autothrust, so the autothrust indication on the FMA should disappear.

**Actual behavior**

"A/THR" on FMA turns blue but remains on FMA.

**References**

Video detailing the issue:

https://www.youtube.com/watch?v=SLklieGOay0

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment] 2020-11-16 23:48
duplicate of #1195

**Closed** 2020-11-17 01:00 UTC
Labels: Bug, Duplicate
