### ISSUE TITLE
Flight Plan vanishes when using VR

### ISSUE THREAD

**Issue by AlexW1968** [flybywiresim/a32nx#4270] opened 2021-04-04 13:37 UTC
**Mod Version**

{
  "built": "2021-04-03T13:23:26+00:00",
  "ref": "autopilot",
  "sha": "a56c2ed99b6f96669ad63e2be9a39d58b459b7e8",
  "actor": "lukecologne",
  "event_name": "manual"
}

**Describe the bug**

When switching from pancake to VR during a flight, the flight plan gets lost after some time.

**To Reproduce**

1.Fly EGLL/09L DET1K DET L6 DVR UL9 KONAN UL607 SPI T180 UNOKO UNOKO1D
EDDF/07R and initialize the plane from Simbrief as shown in video here https://youtu.be/zwWUoxbz14E.
2.Plans stays active after switching to VR mode. In older versions flight plan was lost immediately after switching to VR mode.
3.Before reaching DF432 in UNOKO1D STAR the flight plan vanishes but plane still flies the waypoints. Video here  https://youtu.be/PRyPwXdQQsE

**Expected behavior**

Waypoints should stay visible

**Actual behavior**

Flight plan and waypoints lost, plane follows some waypoints then flies straight.

**References**

see above

**Additional context**

I am using Navigraph latest AIRAC in Simbrief and MSFS. Happens since some weeks. Can't exactly tell when it started but got "End of flight plan" in earlier versions immediately after switching to VR. Excuse video quality.

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment] 2021-04-04 13:51
Duplicate of #2703

**Closed by MisterChocker** 2021-04-04 13:51 UTC
Labels: Bug
