### ISSUE TITLE
4 Dec Dev version anomalies

### ISSUE THREAD

**Issue by Wings64** [flybywiresim/a32nx#2224] opened 2020-12-04 17:38 UTC
FS2020 1.11.6.0

**Mod Version**

{
  "built": "2020-12-04T06:40:58+00:00",
  "ref": "",
  "sha": "",
  "actor": "crisk73 <74656690+crisk73@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

Cannot access INIT B page
Speed runaway on descent

**To Reproduce**

1. Flt Plan Manston - Heathrow ILS 09R at T/o weight 105050lb CG 23.84% MAC
2. Cannot select alternate INIT page on FMS
3. All OK until turn from USR towards final approach with 180kts set in selected mode.
4. Descent from 7000 to 3500 = speed runaway past 300 kts if left alone.
5. Recovered manually onto auto ILS.
6. Line up and landing along left side of runway.
7. DH set at 0 for autoland, but pitch down at last minute.

Also:
Altitude changes in managed mode not accepted for some descents. Using Selected mode to get change followed by reselection of Managed restored control until next recurrence..
Speed changes after 250kt cruise at 7500ft not accepted in managed mode. Using selected mode to change speed followed by reselection of managed mode caused reversion to 250kts.

**Expected behavior**

I had expected speed and altitude changes input in managed mode to be carried out without having to change to selkected mode.

**Actual behavior**

Only6 first FMS INIT page provided.
As above, speed and altitude changes not accepted in managed mode.

**References**

I have a 1.5gb .mp4 video from which I could extract relevant portions if required.

**Additional context**

Intel Core i9-10900K 3.7 - 5.3GHz
Asus ROG STRIX Z490-E GAMING Motherboard
32GB Corsair Vengeance LPX Black DDR4 3200MHz Memory
NVIDIA GeForce RTX 3080 10GB GDDR6X Graphics Card
2x 2TB Samsung 970 EVO PLUS M.2 PCIe Solid State Drive
4TB Samsung 870 QVO Solid State Drive
Windows 10 Pro 64-bit

Was this working before/when did the issue start occurring? Happened with previous A32NX dev and FS2020 versions.

Is this a problem in the vanilla unmodded game? Don't know

Discord username (if different from GitHub):
akribie@ntlworld.com
--

**Comment by Benjozork** [comment] 2020-12-04 18:10
> Cannot select alternate INIT page on FMS

Not accessible after engine start. Were your engines started ?

For the rest of your issues, I will have to close this as GitHub Issues are for *single *confirmed problems with detailed info. I suggest you talk to us on discord so we get a clear picture on where the problem is and if we understand it correctly before opening a bug report.

**Closed by Benjozork** 2020-12-04 18:10 UTC
Labels: Bug

**Comment by Wings64** [comment] 2020-12-04 18:20
Yes. I did not go through the cold start sequence.

Thanks for the extra information - I'm not an Airbus aviator.

**Comment by Wings64** [comment] 2020-12-04 18:42
Forgive my ignorance, but where do I go in Discord to take this further? Not familiar with this application.

**Comment by Benjozork** [comment] 2020-12-04 18:59
I would discuss this in the **#general** channel.
