### ISSUE TITLE
Add a setting for cockpit lighting at startup

### ISSUE THREAD

**Issue by P1NBA11ER** [flybywiresim/a32nx#5757] opened 2021-08-31 02:44 UTC
### Aircraft Version

Experimental

### Description

My least favorite part of flying is having to twiddle all the knobs at the beginning of a flight. It's definitely a minor annoyance only but an option for integral, display and cockpit lighting at 0, 50, 100% on startup (or a numerical entry for any value) would be really cool and streamline the startup process by a noticeable margin. 

### Additional info (optional)

Thanks to everyone for taking the time to develop something awesome for MSFS!

### Discord Username (optional)

P1NBA11ER

**Comment by tracernz** [comment] 2021-08-31 03:08
Duplicate of #5451

**Closed by tracernz** 2021-08-31 03:08 UTC
