### ISSUE TITLE
[BUG] issues with the flight computer

### ISSUE THREAD

**Issue by ties1717** [flybywiresim/a32nx#2776] opened 2020-12-28 18:55 UTC
**Mod Version**
 0.5.1

"built": "2020-12-27T00:57:27+00:00",
  "ref": "",
  "sha": "",
  "actor": "2hwk <15316958+2hwk@users.noreply.github.com>",
  "event_name": "manual"

**Describe the bug**

the a32nx mod is a great mod. but there are a few things that realy irritate me. 1) when i select direct to what should happen in real life is if we have for example the waytpiont "a-b-c-d" if i select direct to c than waytpionts a-b will be removed from the flightplan (only if i select abeams than they should stay in the flightplan but that is with the letter a and b in front of it witch stand for abeams) but what happens in the game is that all the waytpoints are still there and it does go direct to but the waypionts are not removed from the flightplan. 2) at certain airports the approach is totaly not correct and it is just a total mess and that is ok begous it is realy hard to keep up with the changes. but give us the option that we can change the waytpoints within the approach (witch you also can do in real life but you cant do it in the game)

**To Reproduce**
 fly a flight to for example spil and use the rnav - or click direct to

1. i was flying to split with a realwold a320 pilot and he said that the rnav approach was realy butiful so we did that but when wel look in our flightplan we saw that it was a total mess
2. and we wanted to change that but we could not delete waytpoints or add them
3.  and we wanted to select direct to to get ridd of the mess but the mess whas still there

**Expected behavior**

1)i expect that when selecting direct to that all the waytpoint before the selected waytpoint get removed from the flightplan.
2) i expect that or we could change the waytpoints in the approach or the approaches are totaly correct

**Actual behavior**

you can se that in my descriptoin and in my to reproduce

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): ties - 653402

**Comment by pepperoni505** [comment] 2020-12-28 19:02
Duplicate of #2777

**Closed by pepperoni505** 2020-12-28 19:02 UTC
Labels: Bug
