### ISSUE TITLE
seatbelts signs + autobrakes not working

### ISSUE THREAD

**Issue by frap99** [flybywiresim/a32nx#4796] opened 2021-05-13 05:09 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-12T20:09:03+00:00",
  "ref": "master",
  "sha": "3c615945e45603cca52a3f3190ff33651d414976",
  "actor": "sidnov",
  "event_name": "manual"
}
```

### Describe the bug

seatbelt signs not working + autobrakes max get disconnect for nothing before t/o

### Expected behavior

seatbelts sign should make the bing sound and show up on ecam memo but its like the switch is dead

### Steps to reproduce

start a game 
turn seatbelts
and its like the switch is dead

**Comment by airfirefighter** [comment] 2021-05-13 05:11
do u use co pilot add on?

**Comment by frap99** [comment] 2021-05-13 05:27
yes exactly. so the copilot makes it bug?

**Comment by Benjozork** [comment] 2021-05-13 05:28
Yes.

Please try without any other mods installed before reporting issues.

**Comment by frap99** [comment] 2021-05-13 05:31
ok ill try. but i just notice that when i engage STD the ISI doesnt set itself to std no more. idk if its a real life behavior or its once more a bug

**Comment by Watsi01** [comment] 2021-05-13 05:56
The autobrake max disarming when braking during taxi is a known bug. See here #4771

**Comment by MisterChocker** [comment] 2021-05-13 08:12
> ok ill try. but i just notice that when i engage STD the ISI doesnt set itself to std no more. idk if its a real life behavior or its once more a bug

The ISIS is an independent instrument, you have to adjust the baro pressure manually.

**Comment by MisterChocker** [comment] 2021-05-15 16:56
Closing since duplicate of #4771

**Closed by MisterChocker** 2021-05-15 16:56 UTC
Labels: Bug, Waiting For Response
