### ISSUE TITLE
OpenStreetMap Copyright Info Page kills Flypad

### ISSUE THREAD

**Issue by glowfishDE** [flybywiresim/a32nx#4408] opened 2021-04-12 02:26 UTC
Mod Version
vmaster branch (1f4f072)

Describe the bug
The FlyPad lets you click the OpenStreetMap Legal Info in the lower right corner of the Map Page. However you cannot go back to the regular FlyPad menu/screen anymore after this. Thus clicking that link by accident renders the FlyPad useless and you cannot reset it.

To Reproduce

Enter VR
Click on the "OpenStreetMap" Legal Hyperlink in the lower right corner of the OSM Map
Expected behavior
Link should be clickable but there should be a "Back to EFB" Button or a Power Off/Power On FlyPad Button to reset it.

Actual behavior
If you click the OSM Legal Button you get the OSM Copyright Info Webpage and cannot get back to the normal FlyPad Page. After a while the FlyPad crashes and turns dark.

References
Not applicable.

Additional context
Was this working before/when did the issue start occurring?
Has always been an issue since introduction of efb.

Is this a problem in the vanilla unmodded game?
only a32nx

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2021-04-12 02:44
Your first issue is a duplicate of #3493 - please remove it as we do not accept issues containing multiple reports.

For the second, please reformat your issue to follow the provided issue template.

**Comment by 2hwk** [comment] 2021-06-22 08:39
I'm guessing there was another issue in this thread before, but the remaining issue is itself also a duplicate. See #3306. Closing.

**Closed by 2hwk** 2021-06-22 08:39 UTC
Labels: Bug, EFB
