### ISSUE TITLE
[BUG] severely reduced pitch authority after disengaging autopilot

### ISSUE THREAD

**Issue by A320pilotIRL** [flybywiresim/a32nx#723] opened 2020-09-17 01:40 UTC
**Mod Version**
 latest stable mod release (2.0) and AFTER MSFS PATCH 

**Describe the bug**
After disconnecting the autopilot, EXTREMELY limited pitch (elevator) authority. Pitch authority is reduced to 10% of what it should be.

**To Reproduce**
 fly on autopilot, disengage it. Feels like it's still engaged and you're fighting it

1. Listed above
2.
3.

**Expected behavior**
 should be able to deflect elevator up enough to have a 2.5G (2.0G with flaps down) pitch up ability. Can barely pitch up the plane at all in any config after the MSFS patch

**Actual behavior**
Plane juuuust barely responds to pitch commands

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by PCGamesF1Tech** [comment] 2020-09-17 07:03
This also happened to me although I think it did this before the 2nd patch already...
Little difficult to recover from steeper descents

**Comment by CoffeePanda0** [comment] 2020-09-20 17:21
I can confirm this, just started having it after latest update. Tried 12 full flights and this happened on 3 of them.

**Comment by FS2020Paul** [comment] 2020-10-05 09:48
I experience this with every landing since latest FS Update. I do have the latest version of A32NX installed V0.3.1. FD is on. AP engaged, APP selected. Aircraft is setup for landing and everything is picture perfect. Disengage the AP and now have zero elevator control. Aircraft continues decent rate down to the runway and crashes/hits very hard. Using elevator trim is of little use. FYI Ailerons still work.

**Comment by olski320** [comment] 2020-10-16 17:35
Same here. Two flights, happened twice. No elevator authority once A/P disconnects. Latest FS, latest stable version.

**Comment by authir** [comment] 2020-11-04 16:00
Same here. FS 1.10.8.0, latest stable and development version.

When you disable the AP, it seems to be constantly trimming the elevator when it shouldnt. I had F/CTL page open to confirm. Own trim is possible, but the A320NX seems to "work against it". Stock planes are behaving normally.

**Comment by wpine215** [comment] 2020-11-10 00:55
Fixed by Asobo

**Closed by wpine215** 2020-11-10 00:55 UTC
Labels: Asobo Bug
