### ISSUE TITLE
Web ND, PFD, Engine display, System display and EFB 

### ISSUE THREAD

**Issue by ryucz** [flybywiresim/a32nx#7490] opened 2022-09-15 11:22 UTC
### Aircraft Version

Development

### Description

 Primary Flight Display, Navigation Display, Engine Display, System Display and EFB should be available via web interface as MCDU is. 

This is often reqested feature by cockpit builders. 

The **most important one would be the EFB**, because this interface needs to be controlled, but displaying it as pop-out doesn't work very well.

**Comment by frankkopp** [comment] 2022-09-15 13:05
duplicate of #6712

**Closed** 2022-09-15 19:59 UTC
Labels: Duplicate, Request
