### ISSUE TITLE
[REQUEST] Default Transition Alt/Lvl 

### ISSUE THREAD

**Issue by SteveAull** [flybywiresim/a32nx#2572] opened 2020-12-20 22:33 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like to see implemented**
Flying only in the USA you have to put in transition altitude into performance takeoff and Approach phase pages. Would be nice to implement an optional trans altitude in A320X options. so one can avoid this.  Currently it is defaulted to 10,000.

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-12-20 22:39
This already exists.

**Comment by SteveAull** [comment] 2020-12-20 22:40
OK I'll have to search for it. Will close. Thank you.

**Comment by Benjozork** [comment] 2020-12-20 22:41
Nevermind, I confused for thrust reduction altitude

**Comment by SteveAull** [comment] 2020-12-20 22:41
Copy that...Thanks again

**Comment by Kimbyeoungjang** [comment] 2020-12-21 09:15
I'm working this :) please wait!

**Comment by beheh** [comment] 2021-02-01 14:59
Duplicate of #2068.

**Closed by beheh** 2021-02-01 14:59 UTC
Labels: Enhancement
