### ISSUE TITLE
[REQUEST] Separate De Synced MCDUs

### ISSUE THREAD

**Issue by myselfaaryan** [flybywiresim/a32nx#1821] opened 2020-11-09 08:08 UTC
**Describe the feature you'd like to see implemented**
So, after the ATSU feature merge, guys on discord have been requesting this feature. If possible, can we add this in the near timeline? Separate De Synced MCDUs. 

The point is, it offers convenience using the ATSU > AOC side by side while entering data, on the MCDU. 

**Additional context**
If this can be added in the near milestone, that would be great 🚀

**Discord username (if different from GitHub)**
myselfaaryan#0001

**Comment by Benjozork** [comment] 2020-11-09 11:04
Duplicate of #1058

**Closed by Benjozork** 2020-11-09 11:05 UTC
Labels: Enhancement
