### ISSUE TITLE
[BUG] Altitude knob keeps turning

### ISSUE THREAD

**Issue by Dreunit1986** [flybywiresim/a32nx#1664] opened 2020-10-31 12:20 UTC
**Mod Version**
built: 2020-10-15T01:38:50+00:00
ref: refs/heads/master
sha: a72a977f0b5c74eab9396bab64cb16f6cc4c8120
actor: Benjozork
event_name: push

**Describe the bug**
new bug just started yesterday's changes... when turning altitude knob the knob does not stop right away and keeps turning without clicking... unable to effectively set Autopilot altitude

**To Reproduce**

1. turn altitude knob of AP to the right or left
2. it keeps scrolling seemingly uncontrollably
3.

**Expected behavior**

when i stop clicking the knob and elevation needs to remain at what i set it to.

**Actual behavior**

the knob keeps turning in whatever direction

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes it was working two days ago in dev build.

Is this a problem in the vanilla unmodded game?

No.

Discord username (if different from GitHub):

**Comment by aviationenthusiast** [comment] 2020-10-31 14:43
most of the knobs have issues now...

**Comment by ytr81** [comment] 2020-10-31 19:45
The work-around for me is to use the scrollwheel of your mouse on the knobs.

**Comment by lousybyte** [comment] 2020-10-31 20:27
This is an issue with the vanilla game as well after the last update, it seems random.

**Comment by MrGilgamesh89** [comment] 2020-10-31 20:58
I confirm, indeed it is completely out of control, aside of the knobs - entire AP did not function properly (I couldn't enable NAV & Vertical)

**Comment by ed42t** [comment] 2020-11-03 20:40
Having the same issue, anyone had any luck with a solution other than the mouse wheel thing? Also I've noticed that for the knobs and switches missing animations since the update (so ADIRS, landing lights etc) if you flip them using the mouse wheel the animation works again. Not sure if that might help with troubleshooting that and this issue?

**Comment by lukecologne** [comment] 2020-11-03 21:02
> 
> 
> Having the same issue, anyone had any luck with a solution other than the mouse wheel thing? Also I've noticed that for the knobs and switches missing animations since the update (so ADIRS, landing lights etc) if you flip them using the mouse wheel the animation works again. Not sure if that might help with troubleshooting that and this issue?

This is known, and also occurs in the default A320.

**Comment by RBLiii** [comment] 2020-11-12 21:27
I concur.  The flight control knobs, the ILS/Course knob, and the knob that illuminates sections of the main panel, all continuously turn beyond desired setting.

**Comment by Benjozork** [comment] 2020-11-12 21:28
Closing this as it's been confirmed as a game bug.

**Closed by Benjozork** 2020-11-12 21:28 UTC
Labels: Bug, Bug-Vanilla, MSFS 1.10.7
