### ISSUE TITLE
[BUG] CTD ever since update

### ISSUE THREAD

**Issue by daniel5800** [flybywiresim/a32nx#2866] opened 2021-01-04 09:46 UTC
**Mod Version**

Recent Dev Version

**Describe the bug**

Ever since the update i have CTD with no error message

**To Reproduce**

1. Fly the A320 on a route
2. Get to cruise
3. 20 minutes into cruise it crashes

**Expected behavior**

No CTD

**Actual behavior**

That it shouldn't crash the game

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Didn't occur before

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by Lucky38i** [comment] 2021-01-04 09:59
Do you have any other mods installed?

**Comment by daniel5800** [comment] 2021-01-04 10:17
> Do you have any other mods installed?

I have liveries mega pack but that's not caused me any issues before

**Comment by marcsoler** [comment] 2021-01-04 10:31
Of around 10 flights I've made since the last FS update I had 2 CTDs. One was on the A320neo the other on the DA62.

**Comment by Lucky38i** [comment] 2021-01-04 11:30
> > Do you have any other mods installed?
> 
> I have liveries mega pack but that's not caused me any issues before

are you using the the livery mega pack manager? some liveries may need to be updated. A lot of CTD is the cause of AI aircraft pop-in on the ground or in the air using a livery that causes crashes.

**Comment by daniel5800** [comment] 2021-01-04 11:35
> > > Do you have any other mods installed?
> > 
> > 
> > I have liveries mega pack but that's not caused me any issues before
> 
> are you using the the livery mega pack manager? some liveries may need to be updated. A lot of CTD is the cause of AI aircraft pop-in on the ground or in the air using a livery that causes crashes.

Oh I don’t think i am? I’ve not heard of that before, I’ve turned off AI traffic so only traffic I see is those on my ATC network that I use (IVAO) and all seems to be fine but what is this manager for the mega pack? Would love to get that and see if it helps, I also did have PACX which I forgot to mention, the passenger add on, I’m currently doing a flight using the A32NX from Gatwick to Paris without the use of PACX and AI traffic and all seems fine but it’s all about trial and error at this point

**Comment by AndyCYXU** [comment] 2021-01-04 12:34
I was having the same issue CTD couple times about after reaching cruise then two more tries and CTD 20 minutes into the flight, deleted FBW and used default A320 flew the entire flight no problem without CTD, i was using recent Dev version will get back to stable and see it it works that one was diving on me after take off for no reason.

**Comment by daniel5800** [comment] 2021-01-04 13:08
> I was having the same issue CTD couple times about after reaching cruise then two more tries and CTD 20 minutes into the flight, deleted FBW and used default A320 flew the entire flight no problem without CTD, i was using recent Dev version will get back to stable and see it it works that one was diving on me after take off for no reason.

Only reason I downloaded the dev version was because the FMC wasn’t working on the 747 with the stable version else I would’ve kept the stable version on

**Comment by Watsi01** [comment] 2021-01-04 13:36
I don't think this is A32NX related.
There are many CTD reports on the Flightsim Forum since the latest Asobo update (1.12.13.0). Asobo told me, there is an issue with simconnect. They have to investigate further. In the meantime try do disable all tools which use simconnect.  LittleNavMap (or any other planners or live maps), FSUIPC, PACX, etc. 
For me it helped to disable all AI related connection in the according tools (in LittleNavMap for example, disable showing AI traffic). On FSUIPC go the the .ini file (right in the same folder) and add the line "ProvideAIdata=No" under [General].

**Comment by frankkopp** [comment] 2021-01-05 16:01
> On FSUIPC go the the .ini file (right in the same folder) and add the line "ProvideAIdata=No" under [General].

Confirmed. Solved all CTD for me for several days now.

**Comment by daniel5800** [comment] 2021-01-05 16:55
> > On FSUIPC go the the .ini file (right in the same folder) and add the line "ProvideAIdata=No" under [General].
> 
> Confirmed. Solved all CTD for me for several days now.

And what does this do? I’ve turned off AI traffic anyway, I use IVAO so if I do this will I still be able to see planes around me on the network?

**Comment by Benjozork** [comment] 2021-01-05 17:01
I will close this since it's an issue with FSUIPC and further discussion about it is not relevant to A32NX

**Closed by Benjozork** 2021-01-05 17:01 UTC
Labels: Bug

**Comment by frankkopp** [comment] 2021-01-05 17:14
daniel5800 - read this:
https://forum.simflight.com/topic/90649-fs2020-v1830-crash-with-fsuipc/

**Comment by daniel5800** [comment] 2021-01-05 17:35
Those posts are from months ago, the CTD issue started a couple weeks ago

Sent from my iPhone

On 5 Jan 2021, at 17:14, Frank Kopp <notifications@github.com> wrote:

﻿

daniel5800 - read this:
https://forum.simflight.com/topic/90649-fs2020-v1830-crash-with-fsuipc/
