### ISSUE TITLE
[BUG] ILS Frequencys wasnt automatically inserted in RAD NAV Page

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#1392] opened 2020-10-16 08:38 UTC
**Mod Version**
0.4.0

**Describe the bug**
When i select the right ILS Arrival Runway in FMC with the correct STAR then i can see in the Perf / Approch Page in the upper right corner the ILS Runway in green . Ok till now. 

![12](https://user-images.githubusercontent.com/50043259/96235677-5c6e1d80-0f9b-11eb-9de0-d23c3382d384.jpg)

But when i go to the RAD NAV Page i only can see the ILS Runway, not the Frequency . 
Therefore i never will get an Signal for ILS , right ? 

![11](https://user-images.githubusercontent.com/50043259/96235724-6ee85700-0f9b-11eb-9a99-d30cdb76af94.jpg)

**Expected behavior**
In RAD NAV Page should see the ILS Runway and the assosiated Frequency 

**Actual behavior**
In RAD NAV Page is only the Runway not the Frequency. 

Discord username (if different from GitHub):

**Comment by Watsi01** [comment] 2020-10-16 08:43
I'm not sure, but I think this is a navdata (hence Asobo) problem.

**Comment by SM-396** [comment] 2020-10-16 08:52
> I'm not sure, but I think this is a navdata (hence Asobo) problem.

Ok, means you have to insert this Frequency manually too ?

**Comment by Watsi01** [comment] 2020-10-16 09:26
On my side: totally the same. Sometimes the database knows the ILS and freq. Sometimes not. It is recommendable to always check the NAVRAD page after inserting you approach in the MCDU and insert the freq by hand. As I said, I just think the issue must be solved by Asobo.

**Comment by 2hwk** [comment] 2020-10-18 08:33
Vanilla bug that happens with some handcrafted airports.

**Comment by archetec** [comment] 2020-11-03 00:39
This is not an Asobo issue.  The same flight plan with the vanilla A320 will work, and have the ILS frequency correctly set in the MCDU.  And I tested many time with CYUL, an airport that I often use to test between releases and this bug wasn't there before 0.4.1.

**Comment by lukecologne** [comment] 2020-11-03 00:45
This may have been fixed already in the master branch. If you want, you could try downloading it and test if it works there. If you do so, please report back here with your results

**Comment by archetec** [comment] 2020-11-03 01:03
Indeed I just installed the latest from master and it looks like it's fixed.

**Comment by lukecologne** [comment] 2020-11-03 01:09
@SM-396 Can you confirm this so this issue can be closed?

**Comment by dnoe10** [comment] 2020-11-10 02:19
@lukecologne I can confirm that this is fixed in the latest master

**Closed** 2020-11-10 02:28 UTC
Labels: Bug
