### ISSUE TITLE
Cannot change mode or disengange AP / Routing issue

### ISSUE THREAD

**Issue by foxmike80** [flybywiresim/a32nx#5566] opened 2021-08-06 21:01 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-06T18:46:45+00:00",
  "ref": "master",
  "sha": "a94e3c038d41d91a5873c0f1676e32b561f39a17",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Route from EDDM to EDDF. Shortly before TOD the plane stopped following the route and maintained the last track. I could not change into HDG mode or disengange the AP.
When entering a DCT to a WP on the STAR all WPs between my present position and the end of the STAR were deleted (BOWEK, ITHIT, SEVVE, etc. - see video for details).
The AP did not react to any input anymore. I could not even disengage it, so I had to end the flight midair.

### Expected behavior

Plane should follow route in NAV in NAV-mode and HDG in HDG mode. AP should accept inputs. 

### Steps to reproduce

1. Routing EDDM/08R GIVMI6E GIVMI Y101 ERNAS T161 FAWUR FAWUR2B EDDF/25L
2. ToD out of FL240 40NM before SPESSA(?).

https://user-images.githubusercontent.com/76132268/128570450-a501bd0a-438f-43a7-ab79-5eecbd463af0.mp4

### Discord Username (optional)

foxmike1080

**Comment by aguther** [comment] 2021-08-06 21:05
Please reload the plane, then it should work. There is an issue that the HDG pull does not work when the WASM have been compiled before, we don't now the root cause yet.

When the hotfix is out we will reach out to MS/Asobo again to discuss and hopefully find out. Right now they are very busy.

Let us know if reload of the plane fixed it. As long as you don't update it should continue to work.

**Comment by foxmike80** [comment] 2021-08-06 21:09
Thanks for that super quick reply. By "reloading" you mean in the Dev menu, right? Does that not revert the plane to a cold and dark state? Quite a challenge at ToD ;-)
Also, not only the HDG knob was affected - that was a minor problem. At the beginning I was still in NAV mode and the plane stopped following that route - only then did I try reverting to HDG. Also I could not iniate a descent or even disconnect the AP - the AP did not react to any input anymore.
BTW: Hotfix 1.18.15.0 just went online.

**Comment by aguther** [comment] 2021-08-06 21:11
Yes, just seen it. I will ask next week about it again.

the thing with the route could be an issue with the flight plan manager. These issues should improve with the custom flight plan manager that is in the works.

**Comment by foxmike80** [comment] 2021-08-06 21:15
Glad to hear. Thanks a lot for your effort. I have made quite a few trips with your A320 and I have never encountered this issue with the plane not following route before SU5. After SU5 - or more precisely after Hotfix 1 - I had issues with the plane not following route in each and every flight. Most of the times I could resolve it be going to HDG mode - but that didn't work today either. Again, your efforts are much appreciated.

**Comment by 2hwk** [comment] 2021-08-08 01:52
Consolidating into https://github.com/flybywiresim/a32nx/issues/5479 Closing.

**Closed by 2hwk** 2021-08-08 01:52 UTC
Labels: Bug, Waiting For Response
