### ISSUE TITLE
[REQUEST] VOR/NDB Needle on ND in Arc Mode

### ISSUE THREAD

**Issue by CP241** [flybywiresim/a32nx#3810] opened 2021-03-05 11:01 UTC
On the Nav display (ND) in Arc Mode the needle symbol identifier is present in the bottom left/right of the display, however the needle (bearing) indication (highlighted) of the selected Navaid (left/right) is missing. This is an important feature in the real aircraft.

**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

**References**
![image](https://user-images.githubusercontent.com/76106195/110106338-dddb1680-7da9-11eb-892c-0066ae881852.png)

**Additional context**

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment] 2021-03-05 15:27
Duplicate of #2195

**Closed by MisterChocker** 2021-03-05 15:27 UTC
Labels: Enhancement
