### ISSUE TITLE
Cabin model

### ISSUE THREAD

**Issue by lolisec** [flybywiresim/a32nx#5879] opened 2021-09-22 01:08 UTC
### Aircraft Version

Development

### Description

Would love to see at least a basic cabin in the a32nx for recording and stuff.

**Comment by tracernz** [comment] 2021-09-22 04:53
Duplicate of https://github.com/flybywiresim/a32nx/issues/2577. This is something we will do with our own 3D model which is in the works.

**Closed by tracernz** 2021-09-22 04:53 UTC
Labels: Request
