### ISSUE TITLE
[BUG] controls continuosly zoom and then CTD on takeoff

### ISSUE THREAD

**Issue by jeffhollan** [flybywiresim/a32nx#1051] opened 2020-10-03 00:35 UTC
**Mod Version**
latest from `master` commit 3f26b0638ad5db5adb7eab5959bc69858f6d1487

**Describe the bug**
After takeoff when I start to use the mouse to look around, it keeps zooming in and zooming in.  It does this for about 30 seconds until the game eventually crashes to desktop

**To Reproduce**
1. Takeoff from airport (mine was KSEA) with autopilot on
2. At about 600 feet switch to external and then internal camera
3. Try to look around

**Expected behavior**
Wouldn't zoom

**Actual behavior**
The screen keeps zooming and eventually crashes the game.

**Additional context**
Tried this 2xs and it crashed near the same spot after takeoff.  Finally reverted back to `v0.3.1` tag and restarted, worked fine

**Comment by AndersHogqvist** [comment] 2020-10-03 07:17
I experienced something similar yesterday. I use an EDTracker and just before lining up on rwy it suddenly panned 180 degrees (made me look into the seat). I tried to reset the view but it kept panning and then the sim crashed to desktop

**Comment by Trigger225** [comment] 2020-10-03 07:52
I also encountered this. In my case it was during the last few thousand feet before I reached cruising altitude climbing out of O'Hare headed towards Boston. My view suddenly locked up. I tried panning the view and resetting it. The sim CTD approximately 30-60 seconds afterward. I am using v0.3.1 on MSFS v1.9.3.0.

**Comment by blue-huwie** [comment] 2020-10-12 19:06
I can also confirm on 0.3.1 and 1.9.3.0.  Takeoff from EGCC and it happened just as I was arriving at FL270.  In my case it was after using my second monitor, then going back to the primary monitor where Flight Sim was being played.  Immediately any click&drag caused my view to zoom instead of pan.  In less than a minute I had a CTD.

**Comment by MisterChocker** [comment] 2020-12-31 06:51
Does this sill exist in the current game version? Seems not to be caused by our mod

**Comment by blue-huwie** [comment] 2020-12-31 09:56
No, this is no longer an issue for me.

**Comment by MisterChocker** [comment] 2020-12-31 09:59
closing as issue no longer exists

**Closed by MisterChocker** 2020-12-31 09:59 UTC
Labels: Asobo Bug, Bug, Bug-Vanilla
