### ISSUE TITLE
[BUG] Left ND can become "Frozen" 

### ISSUE THREAD

**Issue by CoffeePanda0** [flybywiresim/a32nx#1247] opened 2020-10-11 11:36 UTC
**Mod Version**

Latest A32NX-Master.zip

**Describe the bug**

The left navigation display can be stuck on an image and no longer refresh whereas the right ND still works. This is temporarily fixed by turning on and off the display so it works again.

**To Reproduce**

1. There is no way yet to reproduce, this seems to randomly come and go on different approaches
2. This only happens to left ND
3. If it happens, when you turn down the brightness to OFF and then up again it will work

**Expected behavior**

The left ND updates

**Actual behavior**

The left ND does not update

**References**

![image](https://user-images.githubusercontent.com/34898787/95677450-8b604a00-0bbd-11eb-8a06-5eb6da8a4861.png)
(Look on Left and Right ND)

**Additional context**

Surfwarrior#1297 (another QA tester) had the same issue and we are not sure what triggers it

Was this working before/when did the issue start occurring?
Worked 4 days ago, latest a32nx master broke it

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): obama#6262

**Comment by Benjozork** [comment] 2020-10-11 14:05
Please provide the `build-info.txt` contents as required in the template. Thanks !

**Comment by Warper4** [comment] 2020-10-11 14:15
Also freezes when VOR / NDB switch is selected. The VOR indication does not come out either. In the FO it works normal

**Comment by bouill** [comment] 2020-10-11 20:58
Had this issue as well. Was actually happening when toggling the VOR buttons on the efis panel. Switching a VOR on freezes the ND. Deselecting it defreezes the ND

**Comment by 2hwk** [comment] 2020-10-13 12:08
Possible duplicate of #1071

**Comment by lukecologne** [comment] 2020-10-13 22:52
Fixed in #1285.

**Closed by lukecologne** 2020-10-13 22:52 UTC
Labels: Bug
