### ISSUE TITLE
Nav & Logo lights not working and autobrake light after gear up/down

### ISSUE THREAD

**Issue by Annolago** [flybywiresim/a32nx#2176] opened 2020-12-02 12:39 UTC
**Mod Version**
"built": "2020-12-01T17:45:57+00:00",

**Describe the bug**
Did a quick flight and here is what I found missing or not working so far.
1: No Logo light on the tail of the plane. 
2: At landing setting the autobrakes to max will not not illuminate the button. The other two buttons seems to be working.

**To Reproduce**
Easily reproduced by starting at night time to clearly see the missing tail light.
The autobrake light does work at taxiing and take off. After gear up and then down they do not work.

**Expected behavior**
Lights to go back on as before for both issues

Was this working before/when did the issue start occurring? Yes, worked in stable release 0.41 and previous unstable versions.

**Comment by Annolago** [comment] 2020-12-02 12:40
Sorry - just realized that I forgot the bug title.. Sorry, cannot seem to be able to change that now..

**Comment by Watsi01** [comment] 2020-12-02 12:41
You can. On the top right, I think.

**Comment by saintwolf** [comment] 2020-12-02 12:43
Confirming the autobrake issue here. Works fine at Taxi and T/O but in the air I cannot select the Max button (the other two work though).

**Comment by Watsi01** [comment] 2020-12-02 12:43
1. The logo light is off in air (when the gear is not pressurized). Only on on ground.

**Comment by mikecbr** [comment] 2020-12-02 13:26
> 1. The logo light is off in air (when the gear is not pressurized). Only on ground.

Not , is not off in air , is when the main gear struts are compressed or the flaps are extended at leats 15 degrees , flaps 1 .
Always oin on the ground , to be more specifyc. 👍

**Comment by Watsi01** [comment] 2020-12-02 13:33
That's what I meant. :)

**Comment by beheh** [comment] 2020-12-02 15:22
> 2: At landing setting the autobrakes to max will not not illuminate the button. The other two buttons seems to be working.

Autobrake MAX cannot be armed in flight as it is only meant for rejected takeoff (this is how the real aircraft works). So this is working as intentional.

**Comment by lukecologne** [comment] 2020-12-02 16:31
Working as intended, closing

**Closed by lukecologne** 2020-12-02 16:31 UTC
Labels: Bug

**Comment by snaylor111** [comment] 2020-12-02 21:12
I've always wondered about the max auto break and use have confirmed my suspicions thanks
