### ISSUE TITLE
[BUG] ECAM SD page for Engine Start - IGNITER incorrect display

### ISSUE THREAD

**Issue by Emile31** [flybywiresim/a32nx#819] opened 2020-09-23 09:16 UTC
**Mod Version**
Tested using version 0.2.0 the 23th of September 2020

**Describe the bug**
The igniters 'A' and 'B' are not display at the correct place on the ECAM page. And they do not behave corretly.

**To Reproduce**
Shutdown the engines, and perform the normal start sequence while checking ECAM display :
Sequence is : Rotary on IGNITION + Master Lever (engine1 for example) to ON. After engine is avail, switch rotary back to NORM.

**Expected behavior**
- Position of symbol A and B :
For each engine we can have a display of "A" "B" or "AB" just above the start air valve symbol.
Meaning each engine has its own igniters A and B. The letters shall be display when the corresponding igniter is activated.
- Normal start sequence :
In normal start sequence there is only 1 igniter used. In the real life it changes at each start : it could be either A or B, and for the next start it will be the other.
Before the starting sequence the igniter are off so the letters A and B shall be hidden. Same after the engine AVAIL. The igniters are no longer used and shall be hidden.
To simplify, the igniter is supposed to start nearly at the same time as the fuel flow. Currently Fuel Flow happens around N2 at 22% which is not bad.

**Actual behavior**
- Symbols A and B are display in te middle of the screen.
- There is only one A and one B but there should be A and B for each engine.
- Symbols A and B are display when the engines are off, they should be hidden.
- Symbols A and B are display when the engines are running, they should be hidden (only display during start sequence).
- Symbols A and B are display all along the start sequence, they should start at the same time as the FF around 22% of N2 and stop when engine is AVAIL.

**References**
Correct position for the symbols A and B :
![igniter](https://user-images.githubusercontent.com/71702639/93991473-a5f88d80-fd8c-11ea-88e4-d070a38a8dc6.PNG)

**Additional context**
I can provide more details on the START sequence and display.
Same for the CRANCK procedure which is not behavior correctly.

**Comment by PCGamesF1Tech** [comment] 2020-09-23 12:23
See #127

**Comment by Ares1378** [comment] 2020-09-23 13:47
Yes, this needs to be fixed. I believe one of the developers is working on cleaning up the E/WD and the Engine SD page. PCGamesF1Tech the issue you tagged here is not the same issue. That issue is about the igniters displaying immediately when they should not display until around 18% and rotate between A and B for each start per engine. So say first start of the day engine 1 uses igniter A and for the second flight when starting the number 1 engine the FADEC will choose igniter B or for an abnormal start the FADEC will use both AB igniters starting engine 1 this is the same for both engine just using engine 1 as an example. That issue is still a problem. This issue is about the placement of the igniters on the SD page. They should be above the start valve. I confirm both of these issues are still open discrepancies. 

Ares

**Comment by PCGamesF1Tech** [comment] 2020-09-23 15:00
Ok, so it's ignition logic AND symbol placement.
I thought the page has to be reworked as well as the stock page is from older generation aircraft...

**Comment by lousybyte** [comment] 2020-09-28 07:21
Related #31

**Comment by AdenFlorian** [comment] 2020-10-20 19:34
reopening as the last PR only says it made improvements to this issue but didnt fix it

**Comment by MrMinimal** [comment] 2020-11-18 21:20
This was supposed to be implemented in https://github.com/flybywiresim/a32nx/pull/1045
I can still reproduce "A" and "B" not showing up after engine shutdown and re-ignition.

Looks like "A" or "B" can each be shown once, but not again after having been hidden.

**Comment by erso44** [comment] 2021-06-12 16:39
I will investigate if this issue is solved or not by reproducing. If the issue is not solved I will start working on this task.
I am new so this would be a good task for me.

**Comment by erso44** [comment] 2021-06-12 16:42
@Emile31 did someone work on this issue ? If not I would like to work on this.

**Comment by davidwalschots** [comment] 2021-06-22 20:54
Fixed by #4502

**Closed by davidwalschots** 2021-06-22 20:54 UTC
Labels: Bug, ECAM, Engines, Good First Issue
