### ISSUE TITLE
[BUG] APU will not shutdown. APU Avil still lit.

### ISSUE THREAD

**Issue by CharlieAlphaLima** [flybywiresim/a32nx#2653] opened 2020-12-23 15:49 UTC
**Mod Version**
0.5.1 ZIP download 

**Describe the bug**
APU will not shutdown once disengaging the APU starter switch as can be seen in the screenshots APU Avil still lit and on the lower ECAM shows Flap open still.

**To Reproduce**

1. Load up at any airport in the Christmas Livery FlyByWire.
2. Battery on, Fuel pumps on and start the APU by pressing APU Master, followed by Starter a few moments later, wait until APU is Avail.
3. Shut down the APU by pressing Master SW and watching ECAM page

**Expected behavior**

APU to shutdown, with the Avail light, extinguished.

**Actual behavior**

AVAIL light remains on and so does the lower ECAM Flap open

**References**

Attached

**Additional context**

Running latest MSFS2020 update

Was this working before/when did the issue start occurring? 
Always had this issue since the start.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub): CharlieAlphaLima
![FlightSimulator_1tTS5L6IX2](https://user-images.githubusercontent.com/57408399/103014285-70ec0a80-4536-11eb-98c5-46cf2f8ad0ce.jpg)
![FlightSimulator_FzrTxWnkA8](https://user-images.githubusercontent.com/57408399/103014292-734e6480-4536-11eb-8030-8b5ea0bbd9b2.jpg)

**Comment by hotshotp** [comment] 2020-12-28 05:48
Cannot reproduce

**Comment by CharlieAlphaLima** [comment] 2020-12-30 14:56
Community folder is empty apart from your Airbus. Tried uninstalling/reinstalling to no avail. No idea what is causing it

**Comment by MisterChocker** [comment] 2020-12-31 04:18
Have you unlimited fuel enabled? If so disable.

**Comment by CharlieAlphaLima** [comment] 2020-12-31 13:25
All Assistance is set True to life and unlimited fuel is off. I have tried to reinstall MSFS and yet the issue persists. Still trying to troubleshoot. Here are a few more screenshots
![FlightSimulator_nQ1vbae9G0](https://user-images.githubusercontent.com/57408399/103412142-a8c50480-4b6b-11eb-8a88-f4b803ef18bd.jpg)
![FlightSimulator_O7Xe0B82RS](https://user-images.githubusercontent.com/57408399/103412144-a9f63180-4b6b-11eb-8cb2-46a5256e8d81.jpg)

**Comment by MisterChocker** [comment] 2020-12-31 13:26
You might want to turn off some or all assist to check if it's caused by an assist.

**Comment by CharlieAlphaLima** [comment] 2020-12-31 13:50
All assists and AI control are off

**Comment by CharlieAlphaLima** [comment] 2020-12-31 13:58
Gents the APU is fixed

**Comment by CharlieAlphaLima** [comment] 2020-12-31 14:06
After much troubleshooting I've solved it. Believe it or not i was searching for all key binding relating to the APU and loan and behold my Thrustmaster warthog Throttle key was binded to APU starter which was constantly in the on position (I must have knocked it despite not using any of those keys)  Just thought i'd let you know in case anyone else has the same trouble as me in the near future.  Have a good New Year!

**Comment by MisterChocker** [comment] 2020-12-31 14:08
Thanks reporting back. I am closing since issue is resolved. Happy new year mate!

**Closed by MisterChocker** 2020-12-31 14:08 UTC
Labels: Bug, Can't Reproduce
