### ISSUE TITLE
Low Frame Rate since version 0.4.0

### ISSUE THREAD

**Issue by Gioppino142** [flybywiresim/a32nx#1539] opened 2020-10-25 20:36 UTC
LOW FRAME RATE BUT GAINED WHEN COPILOT PFD and ND are OFF

**Mod Version**

Related to version 0.4.0 A32X folder only

**Describe the bug**

Entering the cockpit frame rate doesn't go upper than 20 fps on land and low altitude with sluttering, no matters the airport and the location.
In version 0.3.0 I could have 24-25 fps without slatters on land and low altitude. More on high altitude.
Closing Copilot PFD and ND gains the frame rate.
Using other Glass Cockpit panel with the same graphic setting I can have 25 to 30 fps on land or low altitude without slutters.

**To Reproduce**

1. Put folder in community folder without other mods.
2. Enter the cockpit on a selected airport runway.
3.

**Expected behavior**

A fluid 25 fps on land or low altitude and 35 to 40 fps on high altitude without slutters as in other glass cockpits.

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
The cockpit was smooth on version 0.3.0
Since th version 0.4.0 the problem occurs.

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-10-25 20:46
Duplicate of #1341

**Closed by Benjozork** 2020-10-25 20:46 UTC
Labels: Bug
