### ISSUE TITLE
Control Cold and Dark from FMC or Ipad in cockpit

### ISSUE THREAD

**Issue by Rossy5502** [flybywiresim/a32nx#5408] opened 2021-07-25 18:13 UTC
### Aircraft Version

Stable

### Description

a nice feature Aerosoft used to have on their A320 airbus, was that you could control things like cold and dark from FMC, Doors.... also instead of turning the panels lights on every time you start FS2020 and load FBW airbus, a suggestion of a way to turn all the panels lighting with one button maybe within the fmc or ipad.

thank you so much for the wonderful work that you have done and doing, keep up the clever stuff.
cheers

**Comment by MisterChocker** [comment] 2021-07-25 19:43
@Rossy5502 please only request one feature per issue template. (Please create another request for the taxi speed control feature).

**Comment by hotshotp** [comment] 2021-07-25 21:09
Idk about the other features but why would we tweak the taxi speed? We have very realistic engine performance data and it allows the plane to taxi on idle. If you don't like it, I'm sorry but that is how the plane is and we are not tweaking the engine model for such a small thing as it would require a lot of effort.

**Comment by MisterChocker** [comment] 2021-07-25 21:54
Duplicate of #4840

**Closed by MisterChocker** 2021-07-25 21:54 UTC
Labels: Enhancement

**Comment by Rossy5502** [comment] 2021-07-25 23:16
Thank you for your reply , I understand and appreciate everything you have done for us simmers
Many thanks

Sent from my iPad

On 25 Jul 2021, at 22:54, DerL30N ***@***.***> wrote:

﻿

Duplicate of #4840<https://github.com/flybywiresim/a32nx/issues/4840>
