### ISSUE TITLE
[BUG] SimBrief Flight Plan: coordinates not works in A320

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#3385] opened 2021-02-07 10:12 UTC
**Mod Version**

2021-02-06T20:19:15+00:00

**Describe the bug**

Wapypoints defined in coordinates (lat,lon) don't work

**To Reproduce**

1. In SimBrief, use this route   GCXO/30 TFS2D TFS DCT 280030N0170518W DCT 280230N0170842W DCT GCGM/27
2.
3.

**Expected behavior**

The two waypoints 280030N0170518W DCT 280230N0170842W should be entered in MCDU

**Actual behavior**

the two waypoint are not entered

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by FGrabi** [comment] 2021-02-07 13:56
I Also believe that the AIRAC Implementation/Integration with the actual Navigraph cycle 2101 is something "bugy". I just planed a flight in Simbrief from EINN-ESSD:

EINN/06 AGIN3A AGINI ERNAN MAC UN537 GOW L983 SAB UM89 RIVOT UM82 NIVUN P609 KSD XOTBU XOTB1F ESSD/I32-Z

After loading it into the FlightManager via ATSU-Init Data and INIT/Page1, it shows AWY/WYP not in database and ALL Airways are unknown!! Need to add all the waypoints manual. Also the WYPs (SD553, SD551) for the STAR XOTB1F are not loaded.
Simbrief is on actual cycle 2101 and so is the MSFS (updated via Navigraph Installer into community).

**Comment by pareil6** [comment] 2021-02-07 14:09
Only one coordinate format currently works in the MCDU (which I don't think actually aligns with any of the ones SimBrief uses), but there's nothing stopping us trying to parse these out. Only potential issue is that the only available format in the MCDU is less precise, but I'll look at doing a PR to load these.

@FGrabi - your bug doesn't sound directly related to this issue I think, but it actually sounds like it might be a different SimBrief API thing I've tried to debug a couple of times where the SID isn't actually marked as such, which screws up the rest of the flight plan. If you've still got that flight plan as your most recent one, could you send me your SimBrief username (DM me on Discord if you don't want it public, pareil6#0990) so I can take a look at what the API is doing?

**Comment by FGrabi** [comment] 2021-02-07 15:08
@pareil6 - I had the same issue as JLD95 with a flight from LPAZ-EINN with the coordinates before. I'm just flying the EINN-ESSD leg (IVAO Worldtour) so the flightplan is the actual OFP. Username is the same as here in FBW.
BTW: I like to thank all of you for the excellent work on this mod. It makes the MSFS really useable.

**Comment by JLD95** [comment] 2021-02-07 15:26
And why I can make a user waypoint with data menu/ nothing when I pressed Lat/Lon

![2021-02-07](https://user-images.githubusercontent.com/5894146/107151088-15989f00-6961-11eb-86fb-85d5197008cc.jpg)

**Comment by pareil6** [comment] 2021-02-07 15:28
@FGrabi - thanks for that, I've figured out what's going on now for that bug. Could you create a new issue, with your findings + both of those route examples? I've got a fix in mind, but it would be good to track it separately so it doesn't get mixed up with this one (which is a separate problem).

**Comment by pareil6** [comment] 2021-02-07 15:31
> And why I can make a user waypoint with data menu: nothing when I pressed Lat/Lon

@JLD95 - the NEW WAYPOINT page is non-functional at the moment, so it won't do anything if you try to enter something.

**Comment by FGrabi** [comment] 2021-02-07 15:40
> 
> 
> @FGrabi - thanks for that, I've figured out what's going on now for that bug. Could you create a new issue, with your findings + both of those route examples? I've got a fix in mind, but it would be good to track it separately so it doesn't get mixed up with this one (which is a separate problem).

@pareil6 - thanks for the fast response. I will create a new issue as soon as possible. At the moment I will be a little busy with my flight to sweden on IVAO. Is it related to the actual Navigraph cycle?
I also reported these "Flightplan - AIRAC circle" _issues_ in #3233 and #3255

**Comment by pareil6** [comment] 2021-02-07 15:56
@FGrabi - let's not derail this issue any further, tag me when you've created a new issue for it and we can continue there :)

**Comment by FGrabi** [comment] 2021-02-07 16:05
@pareil6 WILCO

**Comment by MisterChocker** [comment] 2021-02-08 02:43
Duplicate of #2923.

**Closed by MisterChocker** 2021-02-08 02:43 UTC
Labels: Bug, Flight Plan
