### ISSUE TITLE
[BUG] Heading and engines not shutting down

### ISSUE THREAD

**Issue by harryhicks1** [flybywiresim/a32nx#2114] opened 2020-11-27 19:55 UTC
**Mod Version**
 master
 {
  "creator": "FlyByWire Simulations",
  "release_notes": {
    "neutral": {
      "LastUpdate": "",
      "OlderHistory": ""
    }
  },
  "package_version": "0.4.1",
  "title": "A32NX",
  "dependencies": [
    {
      "package_version": "0.1.58",
      "name": "asobo-aircraft-a320-neo"
    },
    {
      "package_version": "0.1.52",
      "name": "asobo-vcockpits-instruments-a320-neo"
    },
    {
      "package_version": "0.1.53",
      "name": "asobo-vcockpits-instruments-airliners"
    },
    {
      "package_version": "0.1.66",
      "name": "fs-base-aircraft-common"
    }
  ],
  "content_type": "AIRCRAFT",
  "total_package_size": "00000000000241140472",
  "minimum_game_version": "1.9.5",
  "manufacturer": "Airbus"
}

{
  "content": [
    {
      "path": "en-US.locPak",
      "size": 1961,
      "date": 132482479460103242
    },
    {
      "path": "flybywiresim-a32nx.zip",
      "size": 111332937,
      "date": 132485707590336008
    },
    {
      "path": "effects/LIGHT_A32NX_A320_Pedestal.fx",
      "size": 1354,
      "date": 132482479459873040
    },
    {
      "path": "effects/LIGHT_A32NX_BeaconBelly.fx",
      "size": 1228,
      "date": 132482479459873040
    },
    {
      "path": "effects/LIGHT_A32NX_CockpitMinimalAmbiant.fx",
      "size": 1363,
      "date": 132482479459953106
    },
    {
      "path": "effects/LIGHT_A32NX_CockpitMinimalAmbiantLow.fx",
      "size": 1357,
      "date": 132482479459963112
    },
    {
      "path": "effects/LIGHT_A32NX_CockpitSpot.fx",
      "size": 1359,
      "date": 132482479459973120
    },
    {

**Describe the bug**
 The engines do not shut down once they have been started once and for some reason the aircraft will not follow the flight plan or heading  

**To Reproduce**
 

1. Start engine 
2. Try Shut them down 

1. Take off and try and follow the flight plan

**Expected behavior**
 Engines wont shut down and aircraft will not follow heading 

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring? Started randomly on the 27/11/20

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-11-27 20:00
You sent `package.json` instead of `build-info.json`. Also, partly duplicate of #2089 and does not follow template.

**Closed by Benjozork** 2020-11-27 20:00 UTC
Labels: Bug
