### ISSUE TITLE
Last Experimental version version does not follow the flight plan

### ISSUE THREAD

**Issue by PatriceCesson** [flybywiresim/a32nx#4404] opened 2021-04-11 16:12 UTC
**Mod Version**
  "built": "2021-04-11T12:51:36+00:00",
  "ref": "autopilot",
  "sha": "dee3c534150f2e94700cb3917839fe27b985711e",
  "actor": "aguther",
  "event_name": "manual"

**Describe the bug**
I have a flight plan from LFRN to EGPF with many waypoints (a pln file createds via simbriefd).
For the route I follow SID LABU4V and for arrival I follow STAR RIBE1G.
What happens is when reaching WP LABUL (las WP of SID), the plane deviates completly from the plan and maks a circle.
Normally the next WP is DIN. I tried a DIR to DIN on the MCDU and it does not work either.

With the preceding version of the experimental (from today also), I had a similar problem when entering the STAR. The plane made also a complete deviation to the plan and made a circle. I had to finish the flight manually in heading mode.

I did not see such problem with several versions ago

**To Reproduce**
1 Create a plan from LFRN? to EGPF in Simbrief. Store it in the flights plans folder.
2. Load the SIM. In the SIM, load the plan via Load/save. Check the plan and go fliying
3. When in the plane, check the data : payload and fuel, (get data frim simb).
4. In the plan add the SID and STAR via the MCDU.
5. Check the plan for discontinuities: no discs found.
6. Set data in MCDU (Cost index, flight level, weights and CG,
7. Set perf data and also speeds.
8. Set the lflight level in FCU, set speed and hdg to managed mode, set trim in the pedestal.
9. Start the flight. When climbing, gear up and wait for THR-CLB signal on the FMA.
10. At CLB signal, set lever to CLB and activate AP.
11. Past the first WP, in RW alignement, the plane roll to follow the plan. This is OK.
12. When the plane arrives to final WP of SID (LABUL), contrary to follow to DIN, the plane takes another way (almost 90°) than the plan and starts making a circle.
13. After that, the plane cannot be controlled in managed mode. Plan is not followed, the plane follows a circle
14. DIR command to DIN does not work either.

**Expected behavior**
The plane shall follow the plan.

**Actual behavior**
See above.

**References**

**Additional context**
The plane is loaded engines running ready to take off. I have just to enter the FP and relevant data.
Weather is live weather with calm conditions.
The A320 is the experimental post fork.
I use Navigraph experimental database in the SIM (it is included, cycle is 2103- version 2)

Was this working before/when did the issue start occurring?
This has been seen a very long time ago (2 months?) and I never saw it in the last 2 weeks.

Is this a problem in the vanilla unmodded game?
NA.

**Comment by PatriceCesson** [comment] 2021-04-11 16:28
The last dev version 

  "built": "2021-04-10T15:14:17+00:00",
  "ref": "master",
  "sha": "ac9fbb4b3874ff25622111463e4a524f08bbc8ae",
  "actor": "Benjozork",
  "event_name": "manual"

does not have the problem (same conditions, same flight plan)

**Comment by aguther** [comment] 2021-04-11 19:48
Can you provide me the FDR file from that flight? That would be quite helpful.

**Comment by PatriceCesson** [comment] 2021-04-11 21:37
Where is this file?

**Comment by robro8** [comment] 2021-04-11 21:42
Same issue today

**Comment by CoffeePanda0** [comment] 2021-04-11 21:50
Can agree, same issue here. Resetting FLAC, SEC, and ELAC seems to have no effect, the plane often does this on the STAR for me.

**Comment by PatriceCesson** [comment] 2021-04-11 21:55
Here is the link to a folder in my drive whare the files are stored:

https://drive.google.com/drive/folders/14iFUY6GNRzDlybjYqIpu_oOzI0UMZ-BI?usp=sharing

**Comment by aguther** [comment] 2021-04-12 08:10
> Can agree, same issue here. Resetting FLAC, SEC, and ELAC seems to have no effect, the plane often does this on the STAR for me.

Those have no effect on the experimental version at all.

**Comment by aguther** [comment] 2021-04-12 08:11
> Here is the link to a folder in my drive where the files are stored:
> 
> https://drive.google.com/drive/folders/14iFUY6GNRzDlybjYqIpu_oOzI0UMZ-BI?usp=sharing
> 
> If the files are not the ones you want, please mail me and I will try uploading other files of the same day.

Thank you I will have a look in the evening.

**Comment by PatriceCesson** [comment] 2021-04-12 21:37
Hi,

I added 2 more fdr files in the same drive directory.

The big one (2021-04-21-19-49-00.fdr, 151 MB) is the same flight from Rennes to Glasgow.

A32NX version is the experimental one with the following build info:

  "built": "2021-04-11T18:30:27+00:00",
  "ref": "autopilot",
  "sha": "2a9920b808c313d120aaf9fb2b78aff1246bcd17",
  "actor": "lukecologne",
  "event_name": "manual"

There has been 2 anomalies during this flight.

During this flight, the A320:

1. Made a complete circle to the right a small time after having made the first turn to LABUL WP (at departure). 
Seeing tthis I entered a DIR to DIN and the plane has been able to join DIN and follow the plan.

2. Made another circle to the right just at WP RIBEL, (first WP of the STAR RIBE1G to Glasgow). 
Here also I entered a DIR to the next WP NISKA, but the plane seemed find the right way with difficulty. 
Another point is that once I entered this DIR, all the WP of the STAR have beend removed from the plan in the MCDU, but remained on the ND. In the MCDU, the next WP was GLW, the first WP of the arrival transition.

3. Seeing this behaviour, I decided to stop this flight.

There is also another fdr file (small one, dated 4 april also), seems having been created after I stopped my flight. I do not know what it contains. 

So, be aware that the first file is big (151 MB). Hoping this will help.

**Comment by aguther** [comment] 2021-04-12 21:40
> Hi,
> 
> I added 2 more fdr files in the same drive directory.
> 
> The big one (2021-04-21-19-49-00.fdr, 151 MB) is the same flight from Rennes to Glasgow.
> 
> A32NX version is the experimental one with the following build info:
> 
> "built": "2021-04-11T18:30:27+00:00",
> "ref": "autopilot",
> "sha": "2a9920b808c313d120aaf9fb2b78aff1246bcd17",
> "actor": "lukecologne",
> "event_name": "manual"
> 
> There has been 2 anomalies during this flight.
> 
> During this flight, the A320:
> 
> 1. Made a complete circle to the right a small time after having made the first turn to LABUL WP (at departure).
>    Seeing tthis I entered a DIR to DIN and the plane has been able to join DIN and follow the plan.
> 2. Made another circle to the right just at WP RIBEL, (first WP of the STAR RIBE1G to Glasgow).
>    Here also I entered a DIR to the next WP NISKA, but the plane seemed find the right way with difficulty.
>    Another point is that once I entered this DIR, all the WP of the STAR have beend removed from the plan in the MCDU, but remained on the ND. In the MCDU, the next WP was GLW, the first WP of the arrival transition.
> 3. Seeing this behaviour, I decided to stop this flight.
> 
> There is also another fdr file (small one, dated 4 april also), seems having been created after I stopped my flight. I do not know what it contains.
> 
> So, be aware that the first file is big (151 MB). Hoping this will help.

Thanks! No more necessary, I found the issue and will push a fix in a few minutes.

**Comment by aguther** [comment] 2021-04-12 21:41
Just for fun:
![image](https://user-images.githubusercontent.com/6629914/114466321-9f2a4e80-9be8-11eb-9972-1b97101d3835.png)

**Comment by aguther** [comment] 2021-04-12 21:46
@PatriceCesson fix is pushed, please test when build is done (CDN sometimes needs some extra time so please compare the commit after download) and let me know if any issues are left.

**Comment by aguther** [comment] 2021-04-12 22:26
Ok, unfortunately it's not fixed :-(

I know where the problem is, but up to now I do not fully understand why it calculates it wrong. I've created some log output and it just does not make sense at all.

**Comment by wizard-A20N** [comment] 2021-04-12 22:45
Just wanted to let you know i had this issue today before you pushed the lastest patch. I did some testing on the same route and i can also confirm that the plane does a 360 at each way point on the departure SID.
Previously it was only on the last WP after the SID.

Easy to replicate the issue using the following routing:
DPT: EDDL 23L ARR: EGKK 26L
SONE7T SONEB DCT TENLI DCT VALKO DCT GALSO UQ63 SUMUM Q63 ARREK Y4 TEBRA TEBR1G

Before the latest patch (5711e) it was on WP SONEB but now on (fad6cfd) it looks to be from WP DL248 and ERKUM on the SID.

Hope that helps with the investigation.
Thanks

**Comment by aguther** [comment] 2021-04-12 22:55
I think it's fixed now. Please do you tests again. I tried LFRN -> EGPF via LABUL and it worked.

**Comment by wizard-A20N** [comment] 2021-04-13 09:20
Its looking good to me,
Just tested on the same flight path and no 360 on each WP after departure.
Thanks for looking and sorting this issue. :)

**Comment by PatriceCesson** [comment] 2021-04-13 12:39
Well done aguther!
It works perfectly. Absolutely no issue during the complete flight.
I think problem is solved.
Thanks.
Patrice.

**Comment by lukecologne** [comment] 2021-04-13 12:53
Closing as solved

**Comment by CoffeePanda0** [comment] 2021-04-13 19:40
Had this issue on latest experimental just now; able to replicate multiple times myself. If I have selected an ILS approach on the world map, then reselect it in the MCDU while flying the plane begins to turn left for no apparent reason. FDs stay centered and the flight plan does not change on he ND. To fix: go direct to one of the approach waypoints on the ILS. This fixes AP and it turns back to follow the fligt plan. Any chance of re-opening? Happened to a friend doing the same flight with me, also on same build of experimental.  We were on approach for EGCC 05L if that helps, reselecting the approach causing the turn off flight plan.

**Comment by PatriceCesson** [comment] 2021-04-13 21:16
Do you have the latest msfs update of today 13 apr 2021 (1.15.7.0)
if yes, this is a problem I have also : the plane seems broken with this update.

**Comment by Frag1337** [comment] 2021-04-13 21:56
I had this issue happen twice now, both times on the latest experimental versions once with a simbrief generated flight plan and one with the msfs-built-in planner.

I've added the flight data recorder from my most recent flight (1 hour ago) where it started making circles at climb phase. The flight plan was generated by the msfs-built-in planner.

https://mega.nz/file/mLgm1RDI#KkLIsKe_NhILlkGPaoAZkCHJoXy-gXHVFBsfKqwcpW4

Screenshot Reference: https://i.imgur.com/V82ux02.jpg

Adjusted Deadzone
Live Weather
Realism
Modern

**Comment by PatriceCesson** [comment] 2021-04-13 22:50
As a new info:
I reinstalled the A32NX experimental on the last update of msfs and all is working fine. Do not know what happened before, but for me problem solved. So I suggest you delete your versions from community and reinstall them via the installer and test again.

**Comment by aguther** [comment] 2021-04-15 06:18
Any updates? Did reinstall also work for others?

**Comment by CoffeePanda0** [comment] 2021-04-27 21:41
Re-install today of dev, had the same issue. Flight was fine until I re-programmed the STAR, causing the plane to enter a left hand 180 turn. Going DCT to a waypoint in the new STAR fixes the issue.
Looks like after selecting a STAR, the autopilot picks a random waypoint at the start of the plan instead of the first waypoint in the STAR.
Issue needs re-opening

**Comment by CoffeePanda0** [comment] 2021-04-27 21:44
https://github.com/flybywiresim/a32nx/issues/4404#issuecomment-818261881
Mine seems to do this exact thing. Doesn't happen on all approaches, only some (after reprogramming STAR)

**Comment by CoffeePanda0** [comment] 2021-05-01 14:43
Same issue again today, re-selected ILS 08R for EDDP, and the plane started to turn sharp left off course. Going direct to the STAR entry waypoint fixed the issue.

**Comment by robro8** [comment] 2021-05-01 15:09
Yep, same issue in approach EDDK 32R from Waypoint KOPAG direct COL VOR, plane does not follow the flight plan (nav-mod).

**Closed** 2021-05-01 15:15 UTC
Labels: Bug
