### ISSUE TITLE
GPS error map not available

### ISSUE THREAD

**Issue by jockel1893** [flybywiresim/a32nx#4578] opened 2021-04-25 13:00 UTC
**Aircraft Version**

```json
  "built": "2021-04-15T22:57:32+00:00",
  "ref": "v0.6.0",
  "sha": "981b2e4b0e89998d21a70fe26de54a2f10066f6e",
  "actor": "Benjozork",
  "event_name": "manual"
```

**Describe the bug**
I did a route from LOWI to LSZH planned in MS FS2020. I selected low altidude and start directly on the runway. 

**To Reproduce**

1. Planned route in MS FS2020 with starting on the runway
2. After the loading screen I saw the error. 
3.

**Expected behavior**
Normally the route is properly loaded and there is no GPS error. 

**Actual behavior**
See screenshot

**References**

![image](https://i.imgur.com/Zs3i6at.jpg)

**Additional context**

Was this working before/when did the issue start occurring?
Since the last update of MS FS2020 the issue started.

Is this a problem in the vanilla unmodded game?
Yes, except LH livery from OperatorLand468

**Comment by sidnov** [comment] 2021-04-25 15:11
This happens quite rarely, and a simple flight restart should fix it (just the flight, not the simulator itself)

**Comment by Benjozork** [comment] 2021-04-25 16:45
Duplicate of #4506

**Closed** 2021-04-27 13:52 UTC
Labels: Bug
