### ISSUE TITLE
More pushback options

### ISSUE THREAD

**Issue by TLSY2** [flybywiresim/a32nx#5423] opened 2021-07-27 19:45 UTC
### Aircraft Version

Development

### Description

It would be cool to have more options, like more positions for turning and forward way, also speed.

**Comment by marcsoler** [comment] 2021-07-27 20:33
Also discussed here #4801

**Comment by TLSY2** [comment] 2021-07-27 21:26
> Also discussed here #4801

My has more stuff...

**Comment by MisterChocker** [comment] 2021-07-28 08:32
Duplicate of #4801

**Closed by MisterChocker** 2021-07-28 08:32 UTC
Labels: Enhancement
