### ISSUE TITLE
not launching even with  empty community folder

### ISSUE THREAD

**Issue by jwjconsult** [flybywiresim/a32nx#7290] opened 2022-06-10 15:35 UTC
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-05-14T22:16:17+00:00",
    "ref": "refs/tags/v0.8.1",
    "sha": "19e968cadc00d3c28df3b54996da92ce975b0c92",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.8.1"
}
```

### Describe the bug

I have an empty MSFS 2020 Community folder and I also deleted the packages file before I did an install of the  A32NX.  Did this 3-4 times and when I launch a flight the progress bar stops at approx. 90%.  Waited 1/2 to 45 minutes.  No change.  In the same  installer I installed the B747=8I from Salty and that is working fine.

 

### Expected behavior

I expect the progress bar to go to 100% and the normal launch for a flight to occur.

### Steps to reproduce

Windows 11 system, Turtle Beach Yoke, RAM at 32 GB, plenty of HD, Steam launched.

### Discord Username (optional)

jwj#3334

**Comment by AdamNZ** [comment] 2022-06-11 09:55
I often get quite a long pause for the first run after a new A320 update - but never longer than 10 minutes (if that).

I wonder whether clearing/deleting your content.xml would help. Not sure - as I get the impression that it's the FBW *compile* that takes the time <???>. Worth a try though.

**Comment by derl30n** [comment] 2022-06-16 07:28
Duplicate of #7287

**Closed by derl30n** 2022-06-16 07:28 UTC
Labels: Bug
