### ISSUE TITLE
[BUG] T.O CONFIG AFTER LANDING

### ISSUE THREAD

**Issue by griffon55** [flybywiresim/a32nx#1683] opened 2020-11-01 01:19 UTC
**0.4.1**

**Upon landing, when taxiing to a gate you get the ECAM MEMO for T.O configuration**

  ** landing, start APU and continue taxiing to gate
Check ECAM for TO MEMO**

1.After landing, start APU and continue taxiing to gate
2.Check ECAM for TO MEMO
3.

**There should not be a Take off configuration memo on the ECAM after landing**

**TO Config MEMO after landing when taxiing to gate**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-11-01 01:30
Duplicate of #527.

**Comment by Benjozork** [comment] 2020-11-01 01:30
Will keep this one because the older one is invalid and didn't respect the template.

**Comment by Benjozork** [comment] 2020-11-01 01:31
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Might wanna remove this.

**Comment by MisterChocker** [comment] 2020-11-01 22:59
I have noticed that the aircraft keeps all the information from flight phases before, even the init page maintains "filled out".

**Closed** 2020-11-19 14:58 UTC
Labels: Bug
