### ISSUE TITLE
[BUG] speed and HDG only of 10 deg when rotating knobs

### ISSUE THREAD

**Issue by Marenostrum66** [flybywiresim/a32nx#3337] opened 2021-02-04 20:38 UTC
**Mod Version**

Last DEV update

**Describe the bug**

WHen on ground all is fine...when airborn and I rotate the HDG or SPEED knobs I can modify only the second digit and not the third (10 kts variation or 10 deg variation).

**To Reproduce**

1. set up aicraft on the ground and rotate the speed knob or the hdg knob...variation of 1 unit (ok)
2. when airborne do the same and you'll notice the variation of only 10 units (both speed and HDG)
3.

**Expected behavior**

capability to set change of one unit step for both speed and hdg

**Actual behavior**

variation of 10 deg or 10 kts

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Saschl** [comment] 2021-02-04 20:38
Duplicate of #1712

**Comment by scottfranks84** [comment] 2021-02-04 23:09
Yup I also have this issue. If I left mouse click the knobs I am able to do it in 1 knot/degrees variation

**Comment by Rameyuk** [comment] 2021-02-04 23:41
I thought it's always been like this. Mouse wheel scroll to quickly turn them in 10 increments. Left mouse clicks to turn them in 1 increments. I don't want the mousewheel scroll to turn in 1 increments. That's too much ground to cover if I want to quickly turn them.

**Comment by hotshotp** [comment] 2021-02-05 03:08
dupe of #1712

**Closed by hotshotp** 2021-02-05 03:08 UTC
Labels: Bug
