### ISSUE TITLE
[BUG] Autothrottle not maintaining Vapp on final approach (Custom FBW dev build)

### ISSUE THREAD

**Issue by GlitchedYT** [flybywiresim/a32nx#2463] opened 2020-12-15 23:12 UTC
**Mod Version**
Unstable dev build (with the custom FBW)

**Describe the bug**
When setting flaps full and managed speed on final approach, managed speed drops to correct speed (Vapp) and the plane begins to lose speed, however, when reaching the Vapp the autothrottle does not maintain that speed and continues to slow down causing the plane to stall.

**To Reproduce**
1. Start C&D and load any flight completely.
2. Go through the flight like one normally would.
3. When on final approach, select "ACTIVATE APPROACH PHASE" in the mcdu PERF page if not already activated, while in managed speed set flaps to full and when approaching Vapp notice how the autothrottle does not maintain the Vapp speed.

**Expected behavior**
Autothrottle should maintain Vapp speed

**Actual behavior**
Engines stay idle and plane stalls while on approach

**References**
Will add screenshots during next flight

**Additional context**
P.S. This has been happening to me for about a week now but i've held off of creating a report for it as i would have figured it would have been fixed but it is still happening 

Was this working before/when did the issue start occurring?
I believe it was working when the custom FBW first was made into it's own branch but i just recently noticed this happening almost every flight

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment] 2020-12-31 04:36
Can not reproduce, can you ensure your thrust lever were set to CLB detent? Sometimes they seem to magically move to IDLE detent.

**Comment by GlitchedYT** [comment] 2020-12-31 06:18
Yeah they were set to CLB,  did a flight today and it maintained above stall speed but went below vapp again. But now it's actually maintain speed so I wont stall.

**Comment by MisterChocker** [comment] 2020-12-31 06:21
How many knots below Vapp? more than 5 to 10?

**Comment by jetstream2x4** [comment] 2020-12-31 09:15
Howdy ... to be true, I can confirm the observation... Had recently several ILS Approaches that ended in a stall ... Issue is connected to developer-fbw as well as developer non-fbw. So it would be interesting to know which approach type was set ... 

On my personal observation I can report the following. For your information will i just post my smartcars-landing parameters here ... some report, that speed prior to touchdown were extremely low.

By the way - I have this issue since last week only ... before that, everything worked quite fine.

**Comment by jetstream2x4** [comment] 2020-12-31 09:35
Checked the stuff:

Issue first occured on December, 24th, 2020. Before that, I got along well with prosim as well as fsl, handling visuals, npas and precisions.

**KSTL ILS 29**
[15:29:24] Flaps set to position 1 at 1676 ft at 207 kts
[15:29:28] Gear lever lowered at 1543 ft at 210 kts
[15:29:46] Flaps set to position 2 at 1205 ft at 193 kts
[15:29:58] Flaps set to position 3 at 1094 ft at 172 kts
[15:30:04] Flaps set to position 4 at 1073 ft at 165 kts
[15:31:41] Touched down at -782 fpm, gear lever: down, pitch: 4, roll: 2 degrees left, 116 kts
[15:31:47] Aircraft airborne for more than five seconds
[15:31:47] Standard final approach conditions met
[15:31:48] Touched down at -339 fpm, gear lever: down, pitch: 1, roll: level, 112 kts
[15:32:13] Landed in 2912 ft, fuel: 3426 kg, weight: 59474 kg
[15:32:13] Taxiing to gate

KABQ ILS03
[16:01:41] Approaching
[16:07:29] Gear lever lowered at 3596 ft at 206 kts
[16:07:56] Final approach, 223 kts
[16:08:00] Flaps set to position 1 at 2537 ft at 202 kts
[16:08:38] Flaps set to position 2 at 2270 ft at 185 kts
[16:09:00] Flaps set to position 3 at 1969 ft at 159 kts
[16:09:17] Flaps set to position 4 at 1727 ft at 149 kts
[16:11:02] Touched down at -987 fpm, gear lever: down, pitch: 1, roll: level, 136 kts
[16:11:06] Aircraft bounced, touched back down at -262 fpm
[16:11:35] Landed in 4468 ft, fuel: 3820 kg, weight: 60179 kg

KSAT 31L (sorry, I can´t reproduce approach type anymore)
[15:18:54] Flaps set to position 1 at 3388 ft at 205 kts
[15:21:08] Flaps set to position 2 at 2151 ft at 188 kts
[15:23:08] Gear lever lowered at 1929 ft at 144 kts
[15:23:51] Flaps set to position 3 at 1927 ft at 144 kts
[15:24:15] Flaps set to position 4 at 1914 ft at 144 kts
[15:27:22] Touched down early at -934 fpm, gear level: down, flaps: 4
[15:27:25] Aircraft bounced, touched back down at -47 fpm
[15:28:00] Landed in 4310 ft, fuel: 3466 kg, weight: 60138 kg

Now, let me skip to npas, which work just fine ... 
[15:08:52] Flaps set to position 1 at 2424 ft at 201 kts
[15:10:04] Flaps set to position 2 at 2124 ft at 186 kts
[15:10:05] Gear lever lowered at 2118 ft at 186 kts
[15:11:09] Flaps set to position 3 at 1820 ft at 141 kts
[15:11:25] Flaps set to position 4 at 1807 ft at 140 kts
[15:12:02] Final approach, 132 kts
[15:16:34] Touched down at -301 fpm, gear lever: down, pitch: 3, roll: level, 122 kts
[15:17:04] Landed in 3701 ft, fuel: 3575 kg, weight: 58165 kg

[15:28:56] Descending
[15:58:16] Approaching
[16:08:15] Flaps set to position 1 at 3335 ft at 203 kts
[16:09:59] Flaps set to position 2 at 2118 ft at 186 kts
[16:10:05] Gear lever lowered at 2090 ft at 180 kts
[16:10:41] Flaps set to position 3 at 2003 ft at 141 kts
[16:11:35] Final approach, 159 kts
[16:13:28] Flaps set to position 4 at 1442 ft at 144 kts
[16:15:31] Touched down at -217 fpm, gear lever: down, pitch: 2, roll: 1 degrees left, 132 kts
[16:16:03] Landed in 4368 ft, fuel: 4028 kg, weight: 59868 kg
[16:16:03] Taxiing to gate

To be true my belly tells me, that it is an issue we have with autoland ... if you like I can crosscheck the next few days... 
And may be some last words 

Thinks work fine until reaching runway threshold ... once being over runway, the aircraft does a sharp dive down, that I can´t counter even with a normal stick-up ... and while I was speaking about it ... Normally I deactivate autopilot around 1000 feet AGL... I hear the normal Master Caution Warning ... But then I hear the master caution warning again without input 2 or 3 seconds later

**Comment by MisterChocker** [comment] 2020-12-31 09:39
> To be true my belly tells me, that it is an issue we have with autoland ...

which autoland? we don't have that functionality yet

**Comment by jetstream2x4** [comment] 2020-12-31 09:51
laughs ... I know ... my nomenclature was unsharp ... I meant with ILS, not autoland ... I corrected the matter... thanks for the hint :-)

**Comment by jetstream2x4** [comment] 2020-12-31 16:18
Did a short ferry flight from KSTL to KBYH. Planned Approach was RNAV36. But well, I was skipped to Visual 36... even with devasting bad weather ... So far landing worked fine ... It really seems that for me the issue is limited to ILS approaches. Enclosed is smartcars again ... 

[15:09:53] Descending
[15:25:40] Approaching
[15:32:31] Final approach, 196 kts
[15:33:18] Flaps set to position 1 at 2216 ft at 203 kts
[15:33:28] Gear lever lowered at 2216 ft at 195 kts
[15:33:36] Flaps set to position 2 at 2213 ft at 184 kts
[15:33:51] Flaps set to position 3 at 2210 ft at 156 kts
[15:34:05] Flaps set to position 4 at 2072 ft at 147 kts
[15:36:15] Touched down at -298 fpm, gear lever: down, pitch: 4, roll: level, 104 kts
[15:36:38] Landed in 2713 ft, fuel: 2973 kg, weight: 58707 kg
[15:36:38] Taxiing to gate

**Comment by GlitchedYT** [comment] 2020-12-31 18:52
@MisterChocker It was about 5 knots below Vapp, before this it would continue through below stall speed and I would have to take over the throttle or I would stall every time. If I have time today I’ll do a short flight and record the arrival and approach to show you exactly what is happening.

**Comment by MisterChocker** [comment] 2021-01-09 19:11
![image](https://user-images.githubusercontent.com/1857322/104106526-df5ef580-52b6-11eb-9918-f9ca717f0384.png)

**Comment by MisterChocker** [comment] 2021-01-28 14:08
I still can not reproduce the issue, but sometimes the ATHR commands engine thrust very slowly.

**Comment by MisterChocker** [comment] 2021-02-05 10:02
Could this issue be related to #3201?

**Comment by GlitchedYT** [comment] 2021-02-06 17:40
@MisterChocker im gonna fly today on the custom ap branch and ill take a video of the approach and see if it's still happening

**Comment by GlitchedYT** [comment] 2021-02-06 17:40
not too worried about it cuz the custom athr is coming soon

**Comment by BobbyFuzzy** [comment] 2021-02-25 17:31
I have had this happen a couple of times recently. [Here's a link to a video](https://youtu.be/MgbVrfIrEV0?t=6186) where it happened today. I couldn't see that I was doing anything wrong but you can see as I start extending flaps the A/THR isn't commanding any change in power, its just sitting at idle and subsequently speed just drops through all the GD, F, S and Vapp to stall... 

SPEED mode was in, levers in CLB, FD's off.

**Closed** 2021-04-23 22:06 UTC
Labels: Autopilot, Bug, Fixed in custom AP
