### ISSUE TITLE
[BUG] Setting altimeter with "b" Key doesn't work

### ISSUE THREAD

**Issue by sinistre1973** [flybywiresim/a32nx#2739] opened 2020-12-26 19:58 UTC
**Mod Version**
"built": "2020-12-25T10:12:36+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"

**Describe the bug**
Normally, the altimeter is set with the "b" key on the keyboard. Pushing "b" with this A320 version doesn't do anything

**To Reproduce**
1. Spawn at AP or Gate of your choice, but where the baro isn't 29.92 mm Hg or 1013 hpa
2. Check altimeter. Regardless of actual air pressure it reads 29.92 or 1013
2. Press "b" or key associated with "set altimeter"
3. Value stays the same

**Expected behavior**
Value should change to actual pressure

**Actual behavior**
Value does not change

**References**
none

**Additional context**

Was this working before/when did the issue start occurring?
Started with version stated above

Is this a problem in the vanilla unmodded game?
n/a

Discord username:sinistre#6294

**Comment by Benjozork** [comment] 2020-12-26 20:07
Cannot reproduce as of the latest development version.

Do you have other mods in your Community folder ?

**Comment by daanvb** [comment] 2020-12-26 22:35
Works fine for me too

**Comment by hotshotp** [comment] 2020-12-26 22:45
Cannon reproduce

**Comment by hotshotp** [comment] 2020-12-27 06:54
closing this, you can ask for individual help on our discord, someone will help you out there if you have the issue. make sure you have the correct button bound on the keyboard

**Closed by hotshotp** 2020-12-27 06:54 UTC
Labels: Bug, Can't Reproduce, Waiting For Response
