### ISSUE TITLE
[BUG] SimBrief AWY/WPT MISMATCH failures on valid route segments, correctly loads on second attempt

### ISSUE THREAD

**Issue by pareil6** [flybywiresim/a32nx#3406] opened 2021-02-07 20:52 UTC
**Mod Version**
master (2e8f2470)

**Describe the bug**
When importing a route from SimBrief, the import will fail randomly on a valid airway/waypoint intersection with a AWY/WPT MISMATCH warning. Forcing the route to reload will generally fix it - implying that airway data is failing to load correctly on the first attempt. There's no obvious reason for what does it - have seen it reported several times today, with nothing in common between the routes that caused it. An example route (valid on AIRAC 2014/2101):
TTPP DCT POS UG449 ANADA L452 HARBG Y421 OCTAL DCT BAGGS Y290 LEV GILCO5 KIAH

**To Reproduce**
1. Create a SimBrief route from TTPP to KIAH with the above routing
2. Load in, turn on power, and perform an INIT REQUEST from the INIT A page

**Expected behavior**
Route correctly populates

**Actual behavior**
INIT A page populates, but an AWY/WPT MISMATCH shows, with the route failing to load past POS in the F-PLN page, warning in the MCDU console:
![2021-02-07_20-46-11](https://user-images.githubusercontent.com/73158172/107159055-c0bb4f80-6985-11eb-9f96-54e89613bafc.png)

On clearing the route and reloading from SimBrief (typing TTPP/TTPP in FROM/TO to allow another INIT REQUEST, then making a request), the route fills correctly, console logs:
![2021-02-07_20-49-48](https://user-images.githubusercontent.com/73158172/107159118-0bd56280-6986-11eb-8b4f-b273418f0889.png)

Note that very occasionally, it takes multiple reload attempts to make it work - may potentially be related to the same bug that causes a NOT IN DATABASE error when entering a FROM/TO that then works on the next attempt?

**References**
N/A

**Additional context**

Was this working before/when did the issue start occurring? Seems to have occurred sporadically in the past, but has been reported more frequently lately

Is this a problem in the vanilla unmodded game? N/A

Discord username (if different from GitHub): pareil6#0990

**Comment by pareil6** [comment] 2021-02-07 20:52
Creating issue for tracking - I have a fix locally that seems to fix this 90% of the time, just trying to trace any other potential cause to fix it properly.

**Comment by MisterChocker** [comment] 2021-02-08 02:43
Duplicate of #2923.

**Closed by MisterChocker** 2021-02-08 02:43 UTC
Labels: Bug
