### ISSUE TITLE
Engines can be started with switch in NORM position

### ISSUE THREAD

**Issue by lrargerich** [flybywiresim/a32nx#254] opened 2020-08-30 19:38 UTC
If you leave the engine started switch in Norm position and then start an engine it just starts (APU on APU Bleed ON).
In case you can't reproduce this try putting engine to start with APU Bleed OFF and Engine Switch to Start (it won't start) then move switch to NORM and APU BLEED ON then start engines.

**Comment by ukflyer** [comment] 2020-08-30 22:18
i can't reproduce this one, i get a rise in N2 with start switch in NORM but no EGT or N1.

**Comment by JoeW9** [comment] 2020-08-31 11:37
I have tried this they rise to 1.0 on the N1 and EGT to 15. I'll report it back but a minor issue.

**Comment by NathanInnes** [comment] 2020-10-02 21:56
I believe this has been fixed. Can someone else confirm?

**Comment by lousybyte** [comment] 2020-10-06 14:24
They both limit at N1=1, N2=25 and FF=165, can't go further without IGN, not sure how it should be.

**Comment by tareksabet** [comment] 2020-11-15 15:44
It should be not possible to start the engines in NORM mode it should start in CRANK mode or IGN START

**Comment by MrMinimal** [comment] 2020-11-18 20:51
I cannot reproduce this on master (2f9200767ccf8e008aa33df02e52021e4010ed01).
Tried an external power startup and an APU only startup.
With engine mode selector NORM:
N2 rises to 25%, EGT stays at ambient temperature, N1 at 1%, fuel flow at 165 kg/h.
This stays stable, no ignition until mode selector is set to IGN START.
After it, the engine will start up as you would expect.

IMHO this bug has been resolved. Close?

**Comment by hotshotp** [comment] 2020-12-03 15:12
> I cannot reproduce this on master ([2f92007](https://github.com/flybywiresim/a32nx/commit/2f9200767ccf8e008aa33df02e52021e4010ed01)).
> Tried an external power startup and an APU only startup.
> With engine mode selector NORM:
> N2 rises to 25%, EGT stays at ambient temperature, N1 at 1%, fuel flow at 165 kg/h.
> This stays stable, no ignition until mode selector is set to IGN START.
> After it, the engine will start up as you would expect.
> 
> IMHO this bug has been resolved. Close?

closing as this has been reported as fixed

**Comment by tareksabet** [comment] 2020-12-04 08:27
@hotshotp when was it fixed because from what he says that the N2 rises to 25% N1 at 1% and FF 165 kg/h which is not correct behaviour also as if in normal mode nothing should happen and stays in amber. I need to test it again on the latest master to be sure. Opening it again.

**Comment by aguther** [comment] 2022-04-10 09:38
Seems to be solved. Reopen if needed.

**Closed by aguther** 2022-04-10 09:38 UTC
Labels: Bug, Critical Bug, Engines
