### ISSUE TITLE
[BUG] MCDU PERF page does not work

### ISSUE THREAD

**Issue by luke-stec** [flybywiresim/a32nx#1841] opened 2020-11-10 05:12 UTC
**Mod Version**
Latest Master

**Describe the bug**
When trying to access perf page nothing happens, button clicks, but it stays on any current page

**To Reproduce**

1. Start on runway/gate
2. Attempt to access PERF page
3.

**Expected behavior**
Perf page should show

**Actual behavior**
Nothing happens

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Latest DEV
Is this a problem in the vanilla unmodded game?
No, It works with 4.1 stable version aswell

Discord username (if different from GitHub):

**Comment by ilyeshammadi** [comment] 2020-11-10 05:16
I found this when debating the performance page. `CDUPerformancePage` missing variable. 
![Screenshot 2020-11-10 055319](https://user-images.githubusercontent.com/11317522/98630702-0aab7f80-231c-11eb-98c1-434f9b4cf236.png)

**Comment by luke-stec** [comment] 2020-11-10 05:20
That's exactly what I'm thinking, I posted another issue with ARRIVAL/DEPARTURE runway selection that nothing happens when selecting. It is possibly/probably related.

**Comment by ilyeshammadi** [comment] 2020-11-10 05:22
@luke-stec I also just experienced the ARRIVAL/DEPARTURE but the issue may be related to this one.

**Comment by luke-stec** [comment] 2020-11-10 05:26
I'm glad I'm not the only one! I thought I was doing something wrong! And FYI the DEV mod has been installed with the downloader!

**Comment by theersink** [comment] 2020-11-10 05:30
I can confirm this bug as well.

**Comment by theersink** [comment] 2020-11-10 05:34
> @luke-stec I also just experienced the ARRIVAL/DEPARTURE but the issue may be related to this one.

Possibly but I did not experience that issue but mine was a preloaded flightplan and I just changed the dep RW and loaded the approach, KDEN was departure CYYC was the Arrival, no issues with either of those.

**Comment by luke-stec** [comment] 2020-11-10 05:36
> > @luke-stec I also just experienced the ARRIVAL/DEPARTURE but the issue may be related to this one.
> 
> Possibly but I did not experience that issue but mine was a preloaded flightplan and I just changed the dep RW and loaded the approach, KDEN was departure CYYC was the Arrival, no issues with either of those.

Yes you can preload the flighplan and it'll show which runways you are gonna take off from/land, but you cannot change them.

**Comment by jeffhollan** [comment] 2020-11-10 05:37
Not sure if it's related to #1757 as to test out I tried out on commit afa9e2337bbe08ef81489ec5f1eb06689ad82c95 (commit before that PR) and was able to repro both bugs

**Comment by theersink** [comment] 2020-11-10 05:42
> > > @luke-stec I also just experienced the ARRIVAL/DEPARTURE but the issue may be related to this one.
> > 
> > 
> > Possibly but I did not experience that issue but mine was a preloaded flightplan and I just changed the dep RW and loaded the approach, KDEN was departure CYYC was the Arrival, no issues with either of those.
> 
> Yes you can preload the flighplan and it'll show which runways you are gonna take off from/land, but you cannot change them.

I realize but you misunderstand I was able to change them via the MCDU within the sim for the flight I did. Via the MCDU from the F-PLN page, I changed RW from 36L to 34R and loaded approach for ILS RW29 @ CYYS with no issues so that particular issue you mentioned may be intermittent or only certain nav items.

**Comment by IcedLemonTea** [comment] 2020-11-10 06:04
Not sure if it's related but the aircraft symbol on the PFD has also disappeared following this update. Can confirm Perf page is not working but I managed to get runway approach and departures to work on the F-Plan

![2020 11 09-19 08 png-min](https://user-images.githubusercontent.com/22097224/98634021-8bd73680-235d-11eb-84ec-db35d998b878.jpg)

**Comment by ilyeshammadi** [comment] 2020-11-10 06:31
I have a fix for this bug, will push the PR shortly.

**Comment by ilyeshammadi** [comment] 2020-11-10 06:36
You guys can give it a try on this PR https://github.com/flybywiresim/a32nx/pull/1843

**Comment by luke-stec** [comment] 2020-11-10 06:45
> You guys can give it a try on this PR #1843

Downloading this now and will get back to you as soon as I test!

**Comment by luke-stec** [comment] 2020-11-10 06:51
Works like a charm now! Both issues have been rectified here!

**Comment by ilyeshammadi** [comment] 2020-11-10 07:11
@IcedLemonTea I've tested and do not think it's related to this issue. I'm not getting that PFD issue on the latest `master`

**Comment by ilyeshammadi** [comment] 2020-11-10 07:14
@IcedLemonTea I've tested and do not think it's related to this issue. I'm not getting that PFD issue on the latest `master`

**Comment by IcedLemonTea** [comment] 2020-11-10 07:15
@ilyeshammadi Strange, I used the installer to update to the latest dev master. I'll try to reproduce this issue

**Closed** 2020-11-10 07:39 UTC
Labels: Bug, MCDU, Reproduced
