### ISSUE TITLE
EFB goes black on Simbrief import

### ISSUE THREAD

**Issue by Thorwan** [flybywiresim/a32nx#6615] opened 2022-01-29 23:43 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-28T23:14:44+00:00",
  "ref": "master",
  "sha": "16a62d455e7bb6c435b46afe823440de22a7baf5",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

Importing the attached flightplan from Simbrief can cause the EFB to crash/turn off without responding. 
[SCCISCTE_MFS_29Jan22.pln.txt](https://github.com/flybywiresim/a32nx/files/7964988/SCCISCTE_MFS_29Jan22.pln.txt)

or recreate in Simbrief:

Depart: SCCI
Arrive: SCTE

Use the valid suggested route for current AIRAC 2201:
SIRU3A
SIRUN
UQ802
CAUKE
CAUK2A

### Expected behavior

Flightplan is imported, EFB continues working.

### Steps to reproduce

Start cold & dark at SCCI.
Turn on EFB
click _FROM SIMBRIEF_ on EFB

### Additional info (optional)

Tried multiple Routes from SCCI, some crash the EFB, others (like Routes to SAWG don't).
I've noticed there had been a similar Problem with non-LIDO flightplans, but this one uses the LIDO format.

**Comment by ErickSharp** [comment] 2022-02-07 04:44
I have identified the cause of this issue. A hotfix may be prepared for release into development or this will be included in FlyPadOS 3

**Closed** 2022-02-17 16:01 UTC
Labels: Bug
