### ISSUE TITLE
[BUG] Pedal Brake Animation Glitched with Differential Braking

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/a32nx#3800] opened 2021-03-04 10:31 UTC
master (and all previous + Asobo)

**Describe the bug**

Brake pedal animations are very glitchy when applying differential braking. This cannot be fixed until the Blender importer/exporter is complete so it's here as a reminder for that eventuality.

**To Reproduce**

1. Spawn A32NX
2. Apply differential braking (easiest to see with a set of rudder pedals)
3. Observe glitchy behaviour as below

**Expected behavior**

The brake animation (tilt) for each pedal should be independent and proportional to braking applied only on the corresponding pedal.

**Actual behavior**

If applying only one side braking the other pedal goes to maximum braking despite actually being at zero. If applying both pedals they both glitch back and forth.

**References**

https://imgur.com/a/mdnlhKJ

**Additional context**

Was this working before/when did the issue start occurring?
Never worked properly, Asobo problem.

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

**Comment by Awemeter** [comment] 2021-03-07 04:46
I get this issue on every plane in the sim. It only happens when your parking brake is on.

**Comment by sidnov** [comment] 2022-03-03 19:42
Unable to reproduce this one, glitches/animations seems fixed by #4748
Tested with the latest dev version and used the TFRP pedals

**Closed by sidnov** 2022-03-03 19:42 UTC
Labels: Bug, 3D Model

**Comment by tracernz** [comment] 2022-03-04 04:26
Confirm, we worked around by not using the sim implementation anymore. 😁
