### ISSUE TITLE
[BUG] EFOB inaccurate

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2794] opened 2020-12-29 18:28 UTC
**Mod Version**
Latest DEV

**Describe the bug**
Im trying to make a 7 hours flight , so i load the airplane as always , load it with the new simbrief A320 FBW and once I go to init and put the ZFW(by clicking in the same button and it appears automatically) 62.1 AND BLOCK FUEL  15.9 when i go to FUEL PREDICCTION ITS SAYS my EFOB from destinantion is 15.1 , wich is the same. It only happens when im trying to make a long flights , with short ones the EFOB its kind of right , wich is not accuratte but its ok...

**To Reproduce**

1. Load the flight from simbrief A320 FBW NEW SIMBRIEF .
2. It need to be a 7 hours more less flight or more 
3.

**Expected behavior**
IT should show the right ammount in the EFOB 

**Actual behavior**
Showing in the EFOB the same ammount im loading....

**References**
![image](https://user-images.githubusercontent.com/74787268/103305649-f296d900-4a0b-11eb-8c66-0980f116ff2d.png)

**Additional context**

Was this working before/when did the issue start occurring?
Not sure

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-12-29 18:49
Duplicate of #2694 2765

**Closed by Benjozork** 2020-12-29 18:49 UTC
Labels: Bug
