### ISSUE TITLE
0 quantity when weight set to LBS

### ISSUE THREAD

**Issue by atoi2008** [flybywiresim/a32nx#5416] opened 2021-07-26 18:16 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-26T15:33:16+00:00",
  "ref": "master",
  "sha": "b8d899c4748506968946fd028b5ff54eb5404e87",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

When setting the weight units of the aircraft in EFB to lbs, the total FOB shows 0. And MCDU Perf/W+B also show 0s. Importing from simbrief does not change the load. This also fails at the CG step of the INIT program because it thinks its weight is 0.  When set to kgs it works as expected. 

### Expected behavior

Should have the accurate fuel and weight quantities in lbs as in previous builds. 

### Steps to reproduce

change weight units to lbs from kgs
reload aircraft

**Comment by tracernz** [comment] 2021-07-26 19:43
Duplicate of https://github.com/flybywiresim/a32nx/issues/5316. Please use the work-around in there.

**Closed by tracernz** 2021-07-26 19:43 UTC
Labels: Bug
