### ISSUE TITLE
ECAM dosen't allow choosing another destination and approach

### ISSUE THREAD

**Issue by Schahier** [flybywiresim/a32nx#2064] opened 2020-11-22 22:28 UTC
When entering the flight plan page at the MCDU you can no longer click on destination to choose or change an arrival.
Befor you could click on the line next to the destination airport to choose your approach and arrival, thats no longer possible.

Not sure if that just changed because it wasn't like that in real life.  But if its not intenden I wanted to report it.

Reproduce:

While flying go to the Init page change the destination
Go to Flight Plan and click on the button next to the destination.

Thx for all of your hard work by the way, I really enjoy your mod and efforts.

**Comment by Benjozork** [comment] 2020-11-22 23:04
Duplicate of #1378

**Closed by Benjozork** 2020-11-22 23:04 UTC
Labels: Bug
