### ISSUE TITLE
[BUG] EBW Display Issues

### ISSUE THREAD

**Issue by jesterm97** [flybywiresim/a32nx#3349] opened 2021-02-05 18:42 UTC
**Mod Version**
 Experimental
   "built": "2021-02-05T12:13:17+00:00",
  "ref": "fbw",
  "sha": "02b63345f5a7417286ede0d332305a7612760ed1",
  "actor": "aguther",
  "event_name": "manual"

**Describe the bug**
 EBW is displaying what appears to be a webpage for "Carto" and it is not possible to revert to the 'Dashboard' screen once this appears. 

**To Reproduce**

1. Load in flight of choice; (EIDW - LEPA) in this instance.
2. On the ground or mid-flight, if the text which appears at the bottom of the map on the EBW is clicked this webpage will appear. 

**Expected behavior**

Be able to revert back to dashboard or not have this page appear at all.

**Actual behavior**

Page opens which is bright red and cannot be closed. If one zooms out from the EBW the dashboard reappears but it does not update current info and is non-interactive. If you zoom in again, Carto appears.

**References**

![Carto 2](https://user-images.githubusercontent.com/78615762/107075204-b52f2380-67e1-11eb-80a1-9daaf6348fca.PNG)
![carto 3](https://user-images.githubusercontent.com/78615762/107075205-b6605080-67e1-11eb-9744-379b66dbcc3d.PNG)
![Carto 1](https://user-images.githubusercontent.com/78615762/107075207-b6f8e700-67e1-11eb-9b4d-644d67e49904.PNG)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
Michael Jester#4790

**Comment by Benjozork** [comment] 2021-02-05 19:10
Duplicate of #3306

**Closed by Benjozork** 2021-02-05 19:10 UTC
Labels: Bug
