### ISSUE TITLE
Please Fix The AP Banking Issue

### ISSUE THREAD

**Issue by kgaviation** [flybywiresim/a32nx#4110] opened 2021-03-25 15:48 UTC
**Mod Version**

Stable Version

**Describe the bug**

When the AP is engaged it causes the aircraft to bank left and right.

**To Reproduce**

1. Create a flight plan using the world map feature
2. Load the flight and takeoff
3. After takeoff, engage AP and the aircraft will immediately bank left and right

**Expected behavior**

When AP is engaged, the aircraft should not bank left and right. It should continue flying straight or following the FP route. It should smoothly transition to AP.

**Actual behavior**

After takeoff and climb, I engaged the AP and the aircraft immediately banked left and then right when I had the FD centered and was flying centered on the route line. It then continued to follow the FP as it was expected.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes, it was working correctly before sim update 3. The issue started after the recent sim update.

Is this a problem in the vanilla unmodded game?
No. I have tried flying the default A320 without the mod and it does not behave like this. When I engage the AP, it continues flying straight as it should and does not bank left and right.

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2021-03-25 16:10
This is an issue caused by inputs leaking from your control device (joystick or controller). It is not related to the A32NX mod, as much as it may seem like it is.

Please try setting deadzones in your sensitivity settings for the aileron and elevator axis to 20%.

**Comment by kgaviation** [comment] 2021-03-25 18:53
Please stop saying this is a deadzone issue. It's not. All of my deadzones are set at 20%. It still banks left and right as soon as I engage the AP. If it were a deadzone related issue, it would not follow the FP at all and it would continue banking until it just spiraled. Please look more into this.

**Comment by Benjozork** [comment] 2021-03-25 18:57
Could not reproduce your issue with the steps you gave.

I'm sorry but I'll have to be honest here - I do not see any other reports on this on our Discord. I watch many people fly the plane on stream or on our voice chats and have not seen this issue for **months**.

**Comment by kgaviation** [comment] 2021-03-25 19:05
Over on the MSFS forums, there were many people complaining of this issue since sim update 3. The custom version had a similar issue where when you engaged the AP, it would cause the nose to dip down harshly, but that has since been fixed with the latest custom/experimental version. It now smoothly transitions to AP and continues flying straight.

Someone over on the forums posted a few videos of them taking off and it showed the exact same behavior I'm referring to. It would bank left and right when they engaged the AP, but would eventually continue following the FP line. Someone else thought it might be a SimBrief issue, but I also do not use nor have I ever used SimBrief. I always use the default worldmap to create my flight plans.

My flight model is set to modern and has always been and my community folder is empty with no other mods except the FBW mod. I can't think of anything else that would be affecting this behavior.

**Comment by GlitchedYT** [comment] 2021-03-25 19:06
> Please stop saying this is a deadzone issue. It's not. All of my deadzones are set at 20%. It still banks left and right as soon as I engage the AP. If it were a deadzone related issue, it would not follow the FP at all and it would continue banking until it just spiraled. Please look more into this because this is an ongoing that has persisted since the sim update nearly 3 weeks ago. I have the latest stable version and it also does this in the latest dev. version. I have never experienced this issue before.
> 
> I've posted it here already and on the MSFS forums and nothing has been fixed yet. Other people are also experiencing the same issue and complaining about it. The aircraft should not behave this way.

I’m sorry to say but anything related to the Autopilot other than dead zones we don’t have many things we can do to fix them.. If you’re tired of these issues within the default autopilot then I would highly recommend trying out the Custom Autopilot experimental build. You can find the download link for it pinned under the “#autoflight” channel on our discord... If you don’t feel like doing that then sadly there’s nothing else we can do as it’s not made by us.

**Comment by FRYYYYYY** [comment] 2021-03-25 19:21
Yesterday I had exactly the same issue. I was starting from KLAS. The A320 starts banking directly after activating AP. But I am not able to reproduce it because the second time it works without an issue.

And I also think it's not related to my flight hardware because turning left or right is disabled after enabling the AP.

**Comment by Benjozork** [comment] 2021-03-25 19:23
> Yesterday I had exactly the same issue. I was starting from KLAS. The A320 starts banking directly after activating AP. But I am not able to reproduce it because the second time it works without an issue.

Did it bank forever in one direction or like OP is describing ?

> And I also think it's not related to my flight hardware because turning left or right is disabled after enabling the AP.

This is incorrect. Your control hardware can still affect the AP without the AP disconnecting.

**Comment by kgaviation** [comment] 2021-03-25 19:27
> Yesterday I had exactly the same issue. I was starting from KLAS. The A320 starts banking directly after activating AP. But I am not able to reproduce it because the second time it works without an issue.

How did you manage to get it not to bank the second time? I've never been able to do that myself. Glad we're experiencing similar issues though.

**Comment by FRYYYYYY** [comment] 2021-03-25 19:30
> Did it bank forever in one direction or like OP is describing ?

When I turn on the AP, the plane banks in one direction until it crashes.
When I had it a second time I disabled the AP, stabilized the plane and turned the AP back on. After that it broke out in the other direction and finally crashed. 

> This is incorrect. Your control hardware can still affect the AP without the AP disconnecting.

Really, I can move my sidestick or rudder however I want, in AP mode my inputs are ignored.

**Comment by Benjozork** [comment] 2021-03-25 19:31
> When I turn on the AP, the plane banks in one direction until it crashes.

This is the deadzone issue. What is your deadzone setting at ?

> Really, I can move my sidestick or rudder however I want, in AP mode my inputs are ignored.

Are you using the custom autopilot version ?

**Comment by FRYYYYYY** [comment] 2021-03-25 19:32
> How did you manage to get it not to bank the second time? I've never been able to do that myself. Glad we're experiencing similar issues though.

I don't know because I do not know how to reproduce. I just started a new flight and sometimes I have the issue, sometimes it's working. Yesterday it fails 2 times and one time it was working.

**Comment by kgaviation** [comment] 2021-03-25 19:36
> > How did you manage to get it not to bank the second time? I've never been able to do that myself. Glad we're experiencing similar issues though.
> 
> I don't know because I do not know how to reproduce. I just started a new flight and sometimes I have the issue, sometimes it's working. Yesterday it fails 2 times and one time it was working.

So when you engage AP, does it bank one direction, then back the other direction and then it corrects itself and flies level the rest of the flight? Or, are you saying that it just continues banking until it crashes?

For me, I'll be flying straight after takeoff. The FD will be centered and then as soon as I engage AP, it will bank one direction for a few seconds, then back the other direction for a few seconds to correct itself and then eventually it will continue flying straight and level like it should for the rest of the flight. It's only an issue when I first engage AP. However, it shouldn't bank like this back and forth. The rest of the flight is fine though. For me, it doesn't continue banking. That sounds like more of a deadzone issue than what I'm dealing with.

**Comment by FRYYYYYY** [comment] 2021-03-25 19:37
> This is the deadzone issue. What is your deadzone setting at ?

I have to check that. I resetted everything in sensibility before.

> Are you using the custom autopilot version ?

I am using custom fbw mod. Maybe with the stable version it's as you mentioned; I did not test it. I am using a TCA sidestick and quadrant. Because of the support of the quadrant within cfbw I am using this mod instead the stable one. It's really great and amazing work.

**Comment by FRYYYYYY** [comment] 2021-03-25 19:40
> So when you engage AP, does it bank one direction, then back the other direction and then it corrects itself and flies level the rest of the flight? Or, are you saying that it just continues banking until it crashes?

It banks until it crashs. Not able to finish the flight with activated AP when the issue comes up. So I have to disable AP, correct it and hoping not to crash when I re-enable the AP. 

> For me, I'll be flying straight after takeoff. The FD will be centered and then as soon as I engage AP, it will bank one direction for a few seconds, then back the other direction for a few seconds to correct itself and then eventually it will continue flying straight and level like it should for the rest of the flight. It's only an issue when I first engage AP. However, it shouldn't bank like this back and forth. The rest of the flight is fine though. For me, it doesn't continue banking. That sounds like more of a deadzone issue than what I'm dealing with.

**Comment by kgaviation** [comment] 2021-03-25 19:47
Well, for my issue, I've never had the aircraft crash before. It's not a continuous, out of control bank. It banks for a few seconds one direction, then banks the opposite direction for a few seconds, then eventually flies straight and level. Still, it shouldn't behave this way and it never has before. No aircraft I've ever flown on has done this.

**Comment by kgaviation** [comment] 2021-03-25 22:38
If you want to reproduce my test flight, I'll give you the info:

Stable version, A320neo (Airbus House Livery), route: KMIA (BSTER2 RWY27)-KMCO (GOOFY7 RWY36L)

1. I started cold and dark at gate 153 at KMIA (Miami)
2. I departed from runway 27 using the BSTER2 runway 27 departure
3. After takeoff, I reduced the throttle from FLX to CLB and then engaged the AP where it immediately banked right and then back left. This was even with the FD centered. Eventually it corrected itself and flew straight and level and continued to follow the FP the rest of the way.

Try it for yourself, but everytime I've tried this route and many other routes, I always have this issue.

**Comment by lobosg** [comment] 2021-03-25 23:11
Same issue here, here is the information:

Custom FBW Version, A320neo (Orbit livery), Route: SCEL(17R DGO4)-SCVM(PACIL3 RWY 23) very short flight

From cold & dark in gate 17 SCEL
I departed SCEL using the runway 17R departure SID DGO4 everythings good here.
After takeoff, in TOGA i switched to THR CLB, (i was follwing the flight director) without AP on, when i engaged  the AP, the plane immediately banked full left (like trying to center to follow the flight plan) and when i tried to fix the plane bank i disengaged the AP and the plane started to bank right to left again and again like a bucle, until i get to center it manually, i did an approach on SCEL again full manually.

**Comment by kgaviation** [comment] 2021-03-25 23:52
Thanks for the reply. Glad to know I'm not the only one experiencing this issue. This issue needs to be brought up more so it can be dealt with hopefully.

**Comment by Benjozork** [comment] 2021-03-26 00:01
Please read @GlitchedYT's comment.

> I’m sorry to say but anything related to the Autopilot other than dead zones we don’t have many things we can do to fix them.. If you’re tired of these issues within the default autopilot then I would highly recommend trying out the Custom Autopilot experimental build. You can find the download link for it pinned under the “#autoflight” channel on our discord... If you don’t feel like doing that then sadly there’s nothing else we can do as it’s not made by us.

**Comment by kgaviation** [comment] 2021-03-26 00:11
I did read his comment earlier.

So then what changed in the AP with the last update? This was never an issue after previous updates to the sim.

**Comment by Veexs** [comment] 2021-03-26 00:16
Great to see that I’m not only one with that issue. Issue happens to me earlier this week on TBM, yesterday and today with A32NX. 
(Same issue happened previously in November and was resolved with update from FBW, a member on a topic on fs official forum about this issue talk about set SEC2 & SEC3 OFF on the high panel on the right) after take off tonight plane start to bank right then left then right after setting this 3 off plane start to stabilise but little strangely then follow FPLAN from MCDU.

**Comment by Benjozork** [comment] 2021-03-26 00:16
> So then what changed in the AP with the last update? This was never an issue after previous updates to the sim.

We do not have access to the source code of MSFS. No clue.

**Comment by kgaviation** [comment] 2021-03-26 00:36
> Great to see that I’m not only one with that issue. Issue happens to me earlier this week on TBM, yesterday and today with A32NX.
> (Same issue happened previously in November and was resolved with update from FBW, a member on a topic on fs official forum about this issue talk about set SEC2 & SEC3 OFF on the high panel on the right) after take off tonight plane start to bank right then left then right after setting this 3 off plane start to stabilise but little strangely then follow FPLAN from MCDU.

So then what you're saying is that when you engaged AP it banked one direction and then back another direction. I've never experienced this issue before like you mentioned. Also, I'm not referring to the issue where the aircraft sways slightly left and right all flight during cruise. That's a completely separate issue that was resolved a while back and that was what the SEC solution was regarding. Also, previously there was an issue where you had to have your deadzones increased or else the AP would just cause the aircraft to continue banking until it spiraled and crashed. Again, that's a completely different issue than what I'm referring to here.

The aircraft should not bank left then right immediately after engaging AP. Unless I'm flying off course and not following the FD, then I could understand, but that's not my case.

**Comment by Valastiri** [comment] 2021-03-26 01:55
What do your Flight Director's look like when you engage the AP and at what altitude do you engage AP?

**Comment by kgaviation** [comment] 2021-03-26 02:27
My FD's are usually centered almost perfectly. I know that if they were offset to the left or right this would cause the aircraft to bank in order to correct itself, but it should not need to bank left or right if I'm dead center with the FD. Someone else raised this question to me last week when I first complained about this issue and I did more test flights to make sure that I was indeed centered with the FD.

As far as altitude, sometimes it depends. During a lot of my testing, I've engaged it pretty soon after takeoff, usually after the LVR CLB indicator flashes. However, I've also waited all the way to cruising altitude to engage AP (with my FD centered) and there is no difference. I don't really think that altitude would affect this.

**Comment by Valastiri** [comment] 2021-03-26 03:06
> I don't really think that altitude would affect this.

There is an issue activating default AP at or below 3000 AGL sometimes to due pseudo USR waypoints generated by the sim and/or it wanting to bank at low altitude before reaching a minimum height. Something as mentioned earlier that we don't have access to. 

I think the best option here is to upload a video as I also cannot replicate this with the latest development version.

**Comment by kgaviation** [comment] 2021-03-26 03:45
I mean you might be right, but that wouldn't explain it also banking when I engage it at cruising altitude...

As far as other variables, I even removed my one custom livery mod that I had installed thinking this might be the issue. Well it wasn't. Lastly, I have been setting up my flights the same way as I always have since day one and I've never had this issue until after the sim update. I have no idea what could be causing this issue, but I know other's have confirmed this issue, whether it's on here or on the MSFS forum page. And like I've said, I've been able to replicate the issue myself on every single flight I've flown and tested since sim update 3.

**Comment by AdamNZ** [comment] 2021-03-26 05:51
I've also had this same problem lately - but didn't really take much notice until I saw this thread, so this is mainly a "me too" so the original poster doesn't feel he was imagining things.

I've been an FBW user since day none and haven't had this happen until just lately. Unfortunately, the last installer and DEV update coincided with the latest MSFS update - which doesn't help trying to isolate the issue. BTW - I haven't needed to recalibrate or tweak my dead zones for months, so I don't think it's that.

From now on I'll keep a note of the circumstances should it happen again. I don't think it was below 3,000ft - but it could have been when transitioning from an MCDU-generated SID to the next (Simbrief-generated) waypoint. As far as I can remember, it doesn't seem to happen if I'm too lazy to add SIDs/STARs. Could that be a clue?

**Comment by Benjozork** [comment] 2021-03-26 06:05
> Unfortunately, the last installer and DEV update coincided with the latest MSFS update - which doesn't help trying to isolate the issue

There have been dozens of updates to the development version since the last MSFS update - I'm unsure what you mean.

Regardless - we do not have the capacity to affect the default autopilot a lot, and as I've stated, there's no point trying to solve this issue as we are planning to roll out the custom autopilot to more people soon.

**Comment by MisterChocker** [comment] 2021-03-26 11:51
@kgaviation Please provide screenshots or a video.

**Comment by kgaviation** [comment] 2021-03-27 01:06
I would post screenshots, but I'm having issues with my prt sc fuction on my PC right now.

**Comment by TwattyBollox** [comment] 2021-03-27 16:59
> It banks until it crashs. Not able to finish the flight with activated AP when the issue comes up. So I have to disable AP, correct it and hoping not to crash when I re-enable the AP.
> 
That used to happen if the waypoint was very close to the next one, and to the right, or if it was close to the waypoint but did not cross it.
The aircraft would try to turn to capture the next one, but it would be too close and so it would turn left and goin into a very sharp turn.
That would cause the speed to drop, and eventually it would drop below 180kts.
Now, even with full throttle, it can't climb, so now it's turning on full lock, engines at full power, unable to go faster, unable to maintain height. Slowly it starts to drop and eventually it will just spiral into the ground. Sound familiar?

The only way to cure it is to be prepared when it gets to the close waypoints, and when it starts to turn left instead of right, AP off, steer aircraft straight away from the WP, turn slowly right, recapture AP route and turn AP back on.

I haven't had that issue for some time though, last was probably four weeks ago. I suspect it is because the default is to turn anti-clockwise, so it turns left. Was it something like this? https://youtu.be/ZeisIFn79D8?t=2138
You can see I have an almost 90° right turn coming up.
The AP turns a little early to round off the corner, then it seems to realise it hasn't crossed the WP and tries to go back around to capture it again. It's too close though ...
I cannot recreate this one. 
>
>it should not need to bank left or right if I'm dead center with the FD
>
I think it has to steer one way or the other if it has nothing telling it which way to go, or it uses too large a fault correction.
1. It should be on 232 and it IS on 232, when the AP is turned on, X=232-232=0
Here, it cannot understand why there is no number to steer towards, so it does not correct. Wind kicks it slightly one way, it corrects to the left (default) but too much, and then has to recorrect.
2. It's flying at 232.05 when you are following the FD line, and the AP needs to know which way to steer, normally it woud just 
steer X=232-235=3 so steer -3 to get on course. Here it is X=232.05-232=0.05.
If the AP can only do initial course correction by 0.1 increments, it could possibly over-correct.

Once again, as above, it always seems to turn to the left first as a default.
I am not part of the program though, so it is just my guess from observation and many hours in the A320 with A32NX
Unfortunately I cannot recreate this issue.

**Closed** 2021-03-27 22:55 UTC
Labels: Bug, Can't Reproduce, Waiting For Response
