### ISSUE TITLE
[BUG] Flaps Bug

### ISSUE THREAD

**Issue by Talent442** [flybywiresim/a32nx#3955] opened 2021-03-13 21:32 UTC
**Mod Version**
2021-03-13T17:27:43+00:00
(A32NX-Installer)

**Describe the bug**
When the airplane is on approach at 200 to 220 kts and the flaps are set into position 1, the aircraft starts pitching the nose straight down to -10 degrees. The engines begin to increase the thrust up to 90% and the wings of the airplanes hanging down, like there is no aerodynamic lift. It seems the airplane has too much resistance with flaps 1, and the autopilot respond is too sensitive.

**To Reproduce**

1. Keeping speed below 220 kts.
2. Set flaps in position 1.
3. After reset flaps back to "retracted" airplane pitches up to + 10 degrees.

**Expected behavior**
The autopilot pitches down the nose slowly and down to 0 degrees or maybe -5. The engine thrust is reducing.

**Actual behavior**
The autopilot pitches down the nose rapidly to -10 degrees and the thrust spools up.

**References**

**Additional context**
The issue started after the Sim Update III of MSFS.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2021-03-13 21:37
Duplicate of #3913

**Closed by Benjozork** 2021-03-13 21:37 UTC
Labels: Bug
