### ISSUE TITLE
Taxi Light Toggle assignment wrong

### ISSUE THREAD

**Issue by ACCLT1** [flybywiresim/a32nx#5532] opened 2021-08-04 16:03 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-02T20:07:45+00:00",
  "ref": "master",
  "sha": "62a565f79ef6bbc4db5c2e521cd69fba932ad717",
  "actor": "wpine215",
  "event_name": "manual"
}
```

### Describe the bug

When assign Toggle Taxi Light Switch from joystick it toggles Runway Turnoff Lights

### Expected behavior

When assign Toggle Taxi Light Switch from joystick it toggles Taxi Light Switch 

### Steps to reproduce

1. Assign joystick button to Toggle Taxi Lights

### Discord Username (optional)

Sr Adis

**Comment by sidnov** [comment] 2021-08-04 21:40
It's an issue with the default 320neo as well

**Comment by SierraBravo1** [comment] 2021-08-06 19:20
Same with strobe and landing lights (#5444 )

**Comment by 2hwk** [comment] 2021-10-05 08:26
Duplicate of #5444 closing

**Closed by 2hwk** 2021-10-05 08:26 UTC
Labels: Asobo Bug, Bug-Vanilla

**Comment by P1NBA11ER** [comment] 2021-10-06 13:47
Lots of issues that were vanilla issues are no longer issues in the A32NX. That seems to be the point of the A32NX. Wouldn’t it make sense for the FBW team to work on fixing these poorly asigned lighting variables that are designed to work with lighting configurations across multiple default aircraft in the sim? Or am I misunderstanding how this works?
