### ISSUE TITLE
[BUG] CSTR not automatically updating in ND 

### ISSUE THREAD

**Issue by bdpd1** [flybywiresim/a32nx#2814] opened 2020-12-30 18:38 UTC
**Mod Version**
{
  "built": "2020-12-29T18:35:45+00:00",
  "ref": "",
  "sha": "",
  "actor": "devsnek <me@gus.host>",
  "event_name": "manual"
}

**Describe the bug**
Set altitude constraint revision for KORRY fix, ND not updating the new constraint if CSTR button is selected unless you deselect (push OFF) and reselect (Push ON) CSTR 

**To Reproduce**
1.  CSTR selected ON.  KORRY arrival into KLGA; revise altitude constraint KORRY to be 10000 instead of -10000
2.  Return to flight plan
3.  ND showing old altitude constraint, not new revision
4.  Deselced CSTR and reselect to get the ND to show the newly updated VNAV CSTR

**Expected behavior**
Automatic / near instant updating of VNAV constraints on ND 

**Actual behavior**
As above

**References**
https://youtu.be/RYnAe1vTM3o at about 1:55:00

**Additional context**
NA

Was this working before/when did the issue start occurring?
Don't know 

Is this a problem in the vanilla unmodded game?
NA

Discord username (if different from GitHub):  nnumber

**Comment by MisterChocker** [comment] 2020-12-31 01:55
duplicate of #1297

**Closed by MisterChocker** 2020-12-31 01:55 UTC
Labels: Bug
