### ISSUE TITLE
T/C and T/D pseudo-waypoints

### ISSUE THREAD

**Issue by exocetfalling** [flybywiresim/a32nx#307] opened 2020-09-01 13:36 UTC
On FPLN page, the top of climb and top of descent should be indicated by (T/C) and (T/D) respectively. 

![](https://forum.aerosoft.com/uploads/monthly_2016_11/MCDU1.png.6fa15c17eda8ac4cc4e8fb983c25eae8.png)

**Comment by BROADACRES16xFS17MAP** [comment] 2020-10-25 05:42
Definitely needed and should be represented on the PFD. The plane shouldn't also descent on its own. A320 requires a button to be clicked to tell it to descend. Descends way too early.

**Comment by derl30n** [comment] 2022-04-09 23:52
Duplicate of https://github.com/flybywiresim/a32nx/issues/856

**Closed by derl30n** 2022-04-09 23:52 UTC
Labels: Request, FPM, FMS - Predictions
