### ISSUE TITLE
A320 always turnung left with AP ON

### ISSUE THREAD

**Issue by fabmac29** [flybywiresim/a32nx#2164] opened 2020-12-01 17:31 UTC
**Mod Version**

v0.4.1
[build-info.txt](https://github.com/flybywiresim/a32nx/files/5624242/build-info.txt)

**Describe the bug**

**To Reproduce**

1. When I set the autopilot ON the plane always turn left
2. The autopilot does not follow the lateral nav which is set in the MCDU
3.  I get the same issues with the A32NX-master.zip, or the Dev version

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by beheh** [comment] 2020-12-01 17:53
Duplicate of #2089, and:

> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by Benjozork** [comment] 2020-12-01 18:25
Fixed in dev

**Closed by Benjozork** 2020-12-01 18:25 UTC
Labels: Bug
