### ISSUE TITLE
[BUG] AUTO BRAKE not working

### ISSUE THREAD

**Issue by ferics** [flybywiresim/a32nx#904] opened 2020-09-26 14:37 UTC
**Mod Version**

master

**Describe the bug**

The selected auto brake is not operating as intended. Regardless of any auto brake config chosen (low/med/max), all seem to only work at low.

**To Reproduce**

1. Come in on approach
2. Select MED config for auto brake
3. Land and watch it brake on LOW

**Expected behavior**

MED's DECEL should lit up if MED config is chosen (and maybe MAX's DECEL also lit up if aborting the takeoff?)
![image](https://user-images.githubusercontent.com/38722468/94343153-92357b80-0059-11eb-943d-a1c2d91d474d.png)

**Actual behavior**

LOW's DECEL lit up at landing when MED config is selected during the approach
![image](https://user-images.githubusercontent.com/38722468/94342927-f22b2280-0057-11eb-911f-088dd5acf147.png)

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Always since the beginning

Is this a problem in the vanilla unmodded game?
I can vaguely remember it did occur on the vanilla model as well

Discord username (if different from GitHub):
ferics#3085

**Comment by Ares1378** [comment] 2020-09-26 15:03
I can confirm that it has been an ongoing issue and the dev team is aware of it. @AdenFlorian

**Comment by paul92ilm** [comment] 2020-10-29 00:07
Seems to be fixed
![image](https://user-images.githubusercontent.com/9373163/97509603-0d54bf00-1983-11eb-9c6e-85881dc959e5.png)

**Comment by wpine215** [comment] 2020-11-14 21:31
Fixed in latest master branch.

**Closed by wpine215** 2020-11-14 21:31 UTC
Labels: Bug
