### ISSUE TITLE
AutoThrottle does not work

### ISSUE THREAD

**Issue by Crumbly1602** [flybywiresim/a32nx#5327] opened 2021-07-16 13:37 UTC
### Aircraft Version

Development

### Build info

```json
-
```

### Describe the bug

After take-off the Auto-throttle does not manage speed, even if it s active on the PFD; it s activated only after engage AP; is this normal operation?

### Expected behavior

Auto-Throttle working even without AP engage

### Steps to reproduce

Set a normal flight to MCDU and then take-off

**Comment by MisterChocker** [comment] 2021-07-16 16:03
Please fill in the build info as described.

Also please add screenshots which show PFD, ECAM and FCU.

**Comment by aguther** [comment] 2021-07-16 16:09
Fly the plane properly 🙊

**Comment by Crumbly1602** [comment] 2021-07-16 16:36
> Fly the plane properly 🙊

thanks x these valuable useless tips

**Comment by aguther** [comment] 2021-07-16 19:30
I apologize you're right this was not helpful. You're just not the first and also not the second one having that issue and I'm honestly annoyed being said it's a bug that the system does not work. But that's also one of the reasons I take a big break and I shouldn't look into this here.

**Comment by Crumbly1602** [comment] 2021-07-16 21:54
Don't worry, and a year we have been fighting with this absurd "Flight Simulator", maybe it's time to have 2 laughs ...


I noticed it by chance, after take-off I tried to fly the SID in manual and the plane continued to accelerate, even if the auto-throttle seemed fine (it armed - blue - and then stabilized - white -) but the acceleration continued with engine at full power, exceeding the set speed (managed or selected does not change)


the interesting thing is that taking off without programming FMC, the throttle worked immediately without problems.....

**Comment by Crumbly1602** [comment] 2021-07-16 21:58
> Please fill in the build info as described.
> 
> Also please add screenshots which show PFD, ECAM and FCU.

{
  "built": "2021-07-16T01:48:48+00:00",
  "ref": "master",
  "sha": "900e2a875d55938bd79644c4c421447663b16a3f",
  "actor": "tracernz",
  "event_name": "manual"
}

**Comment by MisterChocker** [comment] 2021-07-16 22:52
@Crumbly1602 thanks for providing the build info.

Can also add a screenshot which shows the PFD, upper ECAM and FCU while this issue occurs.
![image](https://user-images.githubusercontent.com/1857322/126015659-2f14df82-3286-4fab-a6ec-cbfa290e18f1.png)

**Comment by Crumbly1602** [comment] 2021-07-16 23:35
> @Crumbly1602 thanks for providing the build info.
> 
> Can also add a screenshot which shows the PFD, upper ECAM and FCU while this issue occurs.
> ![image](https://user-images.githubusercontent.com/1857322/126015659-2f14df82-3286-4fab-a6ec-cbfa290e18f1.png)

![Screenshot (13)](https://user-images.githubusercontent.com/87530424/126017839-03e72a94-6868-499c-8ae3-3b37f6302f65.png)

**Comment by Crumbly1602** [comment] 2021-07-16 23:35
![Screenshot (14)](https://user-images.githubusercontent.com/87530424/126017899-23a6520b-e67c-4cef-a50b-e1e31239518d.png)

**Comment by lukecologne** [comment] 2021-07-16 23:46
You are in CLB mode, so the A/THR will be in THR CLB mode, which is a fixed thrust mode, and will command CLB thrust, because in the CLB/OP CLB modes, the speed is held with the elevators. Either engage the AP, or follow the FD to hold your speed. If you want to leave the CLB/OP CLB mode, you either need to engage V/S or FPA mode, or disengage both flight directors, which will result in the A/THR going to SPEED mode, which is a variable thrust mode, so the speed will be held with the throttle. Closing this as working as intended.

**Closed by lukecologne** 2021-07-16 23:46 UTC
Labels: Bug, Waiting For Response

**Comment by Crumbly1602** [comment] 2021-07-17 00:11
Thanks for the support and explanation👍
