### ISSUE TITLE
[REQUEST] efb Navigraph Charts page

### ISSUE THREAD

**Issue by airfirefighter** [flybywiresim/a32nx#3679] opened 2021-02-22 05:36 UTC
**Is your feature request related to a problem? Please describe.**
negative

**Describe the feature you'd like to see implemented**
possibility in efb to have a page with navigraph charts

**Comment by Awemeter** [comment] 2021-02-22 05:37
This feature is already being worked on.

**Comment by Awemeter** [comment] 2021-02-22 05:38
Duplicate of #1831 too

**Comment by airfirefighter** [comment] 2021-02-22 05:39
sorry i havent see it im closing it

**Closed** 2021-02-22 05:40 UTC
Labels: Enhancement
