### ISSUE TITLE
Framerate drops/stutter - only when engine running

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2215] opened 2020-12-03 20:33 UTC
**Mod Version**

Master

**Describe the bug**

when I turn on the avionics on the ground, no matter what airport, the framerate are always good and i don´t see any stutters. everything smooth on my high-end system. It seems that the stutter appears after angine start. the whole flight, when i look onto the Panel, the stutters are present. Seems that it became more over time. After landing, when i have turned off the engines, no stutters at all and everything smooth like butter. Same with any in-sim refresh rate options.
Maybe something with the MFD/engine values/rpm-counter etc? !? 

**To Reproduce**

Make a whole flight from cold and dark from gate to gate and turn off the engines after onblock.

1. recognise stutter from  push back to onblock - only with engines running and only when i look onto the panel - no stutter when i look out with no panel in sight
2. stutter free at the gate, when all avionics are on. Could not be the screens/refreshrate etc...
3.

**Expected behavior**

no stutter

**Actual behavior**

stutter when look on the panel while ENG running. without ENG running, panel view is stutter-free and smooth - seems also, that stutter became more over time, until onblock and eng turned off - stutter dissappear

**References**

not possible

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
not tested

Discord username (if different from GitHub):

**Comment by BritishAvgeek** [comment] 2020-12-03 20:59
When you say high end system, what are your specs?

**Comment by andrejetcat** [comment] 2020-12-03 21:05
Ryzen 7 3700X, RTX2070Super, 32GB 3600er DDR4-RAM, 1TB SSD

whole sim runs like butter, also when the airbus is fully under elec power, and all systems running. no stutter at all. only as i discribe, after engine start until engines turned off

**Comment by BritishAvgeek** [comment] 2020-12-03 21:32
So basically almost the exact system that I have then but I have the R5 3600X instead... I only get a stutter at the start when I spawn though, and as I'm turning the systems on - but that's because it's also triggering Unreal Weather to pull the first metar and then generate the weather at the very same time I'm switching the aircraft systems on.
You got any mods or programs running in the background like STKP etc?

**Comment by andrejetcat** [comment] 2020-12-03 21:36
please let me know what STKP is :) 
i only have the working title G1000/3000 mod, the CJ4 mod and DA62 mod. 
The point is, that the stutter disappear, after I turn off the engine at the destination. Thats mysterious, because it seems that is only connected to the engines. or maybe to the MFD´s engine values or something else.

**Comment by c1be** [comment] 2020-12-04 16:23
I can confirm that, it is smoother when you turn off engines, but that's not anything new, that was present for a long time now. I would assume they're gonna improve that with future optimizations.

**Comment by omarsmak** [comment] 2020-12-05 17:07
Yep I feel the stutter got bit worse, I think this is due to the systems complexity? Here is screenshot of my fps:
![image](https://i.ibb.co/y8cYFDF/fbw-performance-1.jpg)

outside the plane:
![image_2](https://i.ibb.co/jH6GDLk/fbw-performance-2.jpg)

My build info:
```
{
  "built": "2020-12-05T14:39:00+00:00",
  "ref": "",
  "sha": "",
  "actor": "Ilyes Hammadi ⵉⵍⵖⴻⵙ <hammadiilyesahmed@gmail.com>",
  "event_name": "manual"
}
```

I have i9-9900K OC to 5.0ghz with RTX2080 on 2K screen. Running between high and ultra

**Comment by andrejetcat** [comment] 2020-12-07 10:23
it is not because of the system complexity i think. because, the first minutes after start and taxi, all is normal and smooth. the stutter became more and more over time. something happening in the background, i guess...

**Comment by Watsi01** [comment] 2020-12-07 10:47
The question is: is this A32NX related, or an Asobo problem (MSFS)...?

**Comment by BritishAvgeek** [comment] 2020-12-07 11:39
You checked your vRAM and rolling cache settings?

**Comment by c1be** [comment] 2020-12-07 12:07
> The question is: is this A32NX related, or an Asobo problem (MSFS)...?

This is related to A32NX, default a320 has higher fps and it's much smoother, it's something FBW devs are aware of, it's caused by increased system complexity added to it. They are planning to do optimizations by rewriting the code, be aware that it's gonna take some time to do it.

**Comment by andrejetcat** [comment] 2020-12-07 13:09
i checked it today once again. It seems, that the the issue become worse, when entering more and more waypoints.... e.g after i selected an RNAV approach in EDDF with several waypoints, the stutters are even more.

**Comment by CoffeePanda0** [comment] 2021-04-11 21:56
Old issue but still happens to me on my system (experimental build). My guess would be more code and systems running with FADEC logic etc during and after engine start. I can sit on ext power with no engines for an hour with no lag, starting engines appears to cause this. After shutting down engines, FPS seems to recover, but still lower than before when the aircraft was from cold and dark with non-engine AC sources. APU doesnt seem to cause an issue for me

**Comment by Benjozork** [comment] 2021-04-11 21:58
@CoffeePanda0 The FADEC update code takes less than 0.1ms to update. This also happens on the development version, so it's not related to the experimental version.

**Comment by 2hwk** [comment] 2021-06-22 08:36
Still an issue, but I'm fairly sure I've isolated the problem to the associated ECAM pages. This should improve once we get around to optimising these displays for performance.

**Comment by 2hwk** [comment] 2021-07-04 17:10
Consolidating this and #2428, closing.

**Closed by 2hwk** 2021-07-04 17:10 UTC
Labels: Bug, Performance
