### ISSUE TITLE
[BUG]FCU BAR ITS BLACK AND NOT WORK

### ISSUE THREAD

**Issue by lorenlan** [flybywiresim/a32nx#413] opened 2020-09-05 11:14 UTC
AT START UP FCU BAR NOT SHOW HDG, ALT, SPEED..ITS TURNED OFF AND THE AP CAN'T BE ACTIVATED.
THE OTHER SYSTEMS WORK'S GOOD AT ECEPTION OF PRESS, HYD, AND ELEC BUTTON'S THAT NOT SHOW NOTHING ON DISPLAY.

THANK YOU FOR YOUR WORK

**Comment by ChruutvoLuzi** [comment] 2020-09-05 11:15
Turn the two black knobs below the fcu

**Comment by lorenlan** [comment] 2020-09-05 11:38
THANK YOU, NOW WORK

**Comment by ChruutvoLuzi** [comment] 2020-09-05 11:46
Dont forget to close the Issue if its solved

**Comment by Benjozork** [comment] 2020-09-05 20:05
1. Please do not spam caps

2. Please do not ignore issue templates

**Comment by Curtis-VL** [comment] 2020-09-05 21:26
Closing as the issue is resolved.

**Closed by Curtis-VL** 2020-09-05 21:26 UTC
Labels: bug
