### ISSUE TITLE
[BUG] Starting the flight from any state starts the screens in self-test mode.

### ISSUE THREAD

**Issue by UncleClapton** [flybywiresim/a32nx#448] opened 2020-09-06 11:14 UTC
**Mod Version**

master

**Describe the bug**

Screen self-test mode is visible when starting from any point in a flight (other than C&D).

**To Reproduce**

1. Start any flight from the runway and view the cockpit screens.

**Expected behavior**

screens should start in their normal "on" state

**Actual behavior**

screens start as if they were just being initialized

**References**

![](https://clapton.dev/u/2009/ba60e4dc.jpg)

**Additional context**

**Comment by winternet-studio** [comment] 2020-09-06 16:32
Mine starts with the screens all black (after powering on the aircraft), but I just need to turn up the brightness of each screen....! So yeah, something needs fixing.

**Comment by Benjozork** [comment] 2020-09-07 04:26
> 
> 
> Mine starts with the screens all black (after powering on the aircraft), but I just need to turn up the brightness of each screen....! So yeah, something needs fixing.

That's intended behaviour.

**Comment by winternet-studio** [comment] 2020-09-07 05:34
> > Mine starts with the screens all black (after powering on the aircraft), but I just need to turn up the brightness of each screen....! So yeah, something needs fixing.
> 
> That's intended behaviour.

Oh really? The real aircraft does that? Why is that?

**Comment by AdenFlorian** [comment] 2020-09-08 04:31
@winternet-studio I believe it's because the previous pilots turned them all off at the end of the day?

I've kind started to work on a fix for this.

**Comment by winternet-studio** [comment] 2020-09-08 05:56
I can't see why they should turn the brightness all the way down - it makes no sense. When the power is cut off anyway it doesn't matter what brightness level they are set to...! I could understand if they were reset to a specific level, but completely black... even if there is something I don't know about I cannot imagine any reason for it.
Thanks.

**Comment by UncleClapton** [comment] 2020-09-08 14:58
It was a part of their SOPs, and remains so for quite a few airliners.

Regardless, this discussion is off-topic for this ticket, really.

**Closed** 2020-09-09 03:59 UTC
Labels: bug
