### ISSUE TITLE
[BUG] Strange Captain side ND issue

### ISSUE THREAD

**Issue by dmajestic80** [flybywiresim/a32nx#1182] opened 2020-10-08 01:08 UTC
**Mod Version**

Latest master

**Describe the bug**

Captain side ND has frozen but FO side functioning normally only started with latest master

**To Reproduce**

1. I started up from C&D as normal. Once IRS align completed the ND became frozen on Captain side only. See screenshot
2.
3.

**Expected behavior**

ND to function as normal after IRS align

**Actual behavior**

As above

**References**

![1250410_20201008102844_1](https://user-images.githubusercontent.com/72002430/95403645-5b653c80-095a-11eb-9384-4cfe1388b9b5.png)

**Additional context**

I reverted back to a previous master and the issue isn't present. Issue only started with the latest master

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-10-08 03:51
I have been told this is the same issue as #1071. Can you confirm this ?

**Comment by dmajestic80** [comment] 2020-10-08 04:10
> 
> 
> I have been told this is the same issue as #1071. Can you confirm this ?

Hmmm it looks similar but is slightly different I think. I have a video but couldn't manage to get it to upload on here. I just tried a new flight and the same thing happened, right after the IRS aligns it goes to this:

![1250410_20201008101559_1](https://user-images.githubusercontent.com/72002430/95413534-3c26d900-0973-11eb-8258-b2201d770107.png)

**Comment by dmajestic80** [comment] 2020-10-08 04:20
> 
> 
> I have been told this is the same issue as #1071. Can you confirm this ?

I think it may be the same as this issue #1128

So if I'm correct, to avoid this issue is not touch ADF/VOR switches until ADIRS are finished aligning?

**Comment by Benjozork** [comment] 2020-10-08 04:21
> So if I'm correct, to avoid this issue is not touch ADF/VOR switches until ADIRS are finished aligning?

Wait, so if you need to avoid touching those buttons, it is the same as both #1071 are #1128

**Comment by dmajestic80** [comment] 2020-10-08 04:26
> 
> 
> > So if I'm correct, to avoid this issue is not touch ADF/VOR switches until ADIRS are finished aligning?
> 
> Wait, so if you need to avoid touching those buttons, it is the same as both #1071 are #1128

I haven't tested with not touching those buttons but it seems to be the same. Although #1071 looks a little different and the scenario that caused it is different to mine, he mentions: Describe the bug

"When reloading a flight which was saved with both button ADF/VOR to VOR position, the ND display stay locked in MODE CHANGE state"

I was not doing the above and his ND display looked different to mine where as #1128 looks identical

**Comment by Benjozork** [comment] 2020-10-08 04:59
Yeah but you are interacting with those buttons, correct ?

Also the exact state of the ND when it fails will not be the same across instances of the issue.

**Comment by dmajestic80** [comment] 2020-10-08 05:12
> 
> 
> Yeah but you are interacting with those buttons, correct ?
> 
> Also the exact state of the ND when it fails will not be the same across instances of the issue.

I would have to test again as I'm unsure if I touched those buttons or not (but I must've and it's possible I did) I will test again and NOT touch those buttons and revert back with my findings.

**Comment by dmajestic80** [comment] 2020-10-08 05:42
> 
> 
> Yeah but you are interacting with those buttons, correct ?
> 
> Also the exact state of the ND when it fails will not be the same across instances of the issue.

Ok, so just tested. I let the IRS align and did not touch the ADF or VOR switches. After alignment had completed the ND looks normal and correct and I am able to switch between ADF 1/2 and VOR 1/2 without issue. So my question is, is this a bug in which you cannot touch those switches prior to IRS alignment or is that how the real bus behaves?

**Comment by hotshotp** [comment] 2020-10-08 12:15
> > Yeah but you are interacting with those buttons, correct ?
> > Also the exact state of the ND when it fails will not be the same across instances of the issue.
> 
> Ok, so just tested. I let the IRS align and did not touch the ADF or VOR switches. After alignment had completed the ND looks normal and correct and I am able to switch between ADF 1/2 and VOR 1/2 without issue. So my question is, is this a bug in which you cannot touch those switches prior to IRS alignment or is that how the real bus behaves?

that is definitely a bug, for now I guess don't touch those switches during alignment.

**Comment by dmajestic80** [comment] 2020-10-08 12:23
> 
> 
> > > Yeah but you are interacting with those buttons, correct ?
> > > Also the exact state of the ND when it fails will not be the same across instances of the issue.
> > 
> > 
> > Ok, so just tested. I let the IRS align and did not touch the ADF or VOR switches. After alignment had completed the ND looks normal and correct and I am able to switch between ADF 1/2 and VOR 1/2 without issue. So my question is, is this a bug in which you cannot touch those switches prior to IRS alignment or is that how the real bus behaves?
> 
> that is definitely a bug, for now I guess don't touch those switches during alignment.

Just doing a flight now, didn't touch the switches until after alignment. Once in the air, if I set both to either ADF or VOR, then the ND freezes still. However, if setting the switches back to off the ND functions again. Oddly this only happens on the Captain side. The FO side is fine.

**Comment by Benjozork** [comment] 2020-10-08 13:21
Closing as confirmed duplicate of #1071. Renaming #1071 to include non-saved flights.

**Closed by Benjozork** 2020-10-08 13:21 UTC
Labels: Bug, Bug-A32NX, ND (Navigation Display)
