### ISSUE TITLE
Moving windows

### ISSUE THREAD

**Issue by boomcreeper11** [flybywiresim/a32nx#5933] opened 2021-09-29 20:05 UTC
### Aircraft Version

Stable

### Description

I think the A32nx could really benefit from moving windows. You'd be able to open windows and move your camera slightly outside the plane, adding to the realsim

### Discord Username (optional)

Scrub Man#4699

**Comment by Benjozork** [comment] 2021-09-29 20:07
This will be included in the upcoming re-modeled cockpit and exterior.

**Comment by MisterChocker** [comment] 2021-10-03 10:40
Duplicate of #4589

**Closed by MisterChocker** 2021-10-03 10:40 UTC
Labels: Request, 3D Model
