### ISSUE TITLE
[REQUEST]Add start the fuel pumps in the prestart checklist.

### ISSUE THREAD

**Issue by SPAREGARLIC556** [flybywiresim/a32nx#1793] opened 2020-11-07 18:45 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by SPAREGARLIC556** [comment] 2020-11-07 18:47
No but if not done the engines do not run.

**Comment by Benjozork** [comment] 2020-11-07 18:54
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by Benjozork** [comment] 2020-11-07 18:54
also, duplicate of #1405

**Closed by Benjozork** 2020-11-07 18:54 UTC
Labels: Enhancement
