### ISSUE TITLE
[BUG] [MCDU] Unable to enter a TA lower than 4500 in the MCDU APR page

### ISSUE THREAD

**Issue by ImenesFBW** [flybywiresim/a32nx#2081] opened 2020-11-24 08:23 UTC
**Mod Version**
{ "built": "2020-11-24T00:05:32+00:00", "ref": "refs/heads/master", "sha": "444ed6f93d2915b76f97a07d2ecf0d545ebcf198", "actor": "wpine215", "event_name": "push" }

**Describe the bug**
Unable to enter a TA lower than 4500 feet in the APR page of the MCDU

**To Reproduce**
1. Enter a TA lower than 4500 feet in the APR page of the MCDU
2. FORMAT ERROR appears

**Expected behavior**
MCDU should accept TA lower than 4500

**Actual behavior**
MCDU did not accept TA lower than 4500

**References**

![image](https://user-images.githubusercontent.com/71195324/100067415-8803e380-2e36-11eb-83af-721b588afe57.png)

Was this working before/when did the issue start occurring?

Yes

Is this a problem in the vanilla unmodded game?

I don't know.

**Comment by Tonyehrd** [comment] 2020-11-24 08:29
In my case it won't go lower then 4500 feet.

**Comment by AdamNZ** [comment] 2020-11-24 08:48
Confirmed here - with the latest dev build.

**Comment by ThatRedMelon** [comment] 2020-11-24 09:00
It seems the aircraft does not allow you to set a transition altitude for approach that is lower than the transition altitude for takeoff, which I don't believe is the correct behaviour.

**Comment by beheh** [comment] 2020-11-24 09:44
I'll incorporate this in #1824.

**Comment by Tonyehrd** [comment] 2020-11-24 10:22
> It seems the aircraft does not allow you to set a transition altitude for approach that is lower than the transition altitude for takeoff, which I don't believe is the correct behaviour.

Yep, i tested it and your right. If the t/o page trans alt is higher then appr trans alt you get this error.

**Comment by Kimbyeoungjang** [comment] 2020-11-24 10:30
it is not bug.
i add that logic. when you enter the trans lvl lower then trans alt(on performance page, takeoff)

Trans ALT is takeoff alt, and Trans LVL is APPR level. Trans ALT should lower than Trans LVL
Also, MCDU default Trans ALT is 10,000ft so, if you're not enter custom value on Trans ALT, you can't insert Trans LVL 4,500ft.

**Comment by Kimbyeoungjang** [comment] 2020-11-24 10:32
https://en.wikipedia.org/wiki/Flight_level

you can check that Transition LVL = Transition ALT + Transition Layer. 
Transition ALT should lower than Transition LVL

**Comment by ImenesFBW** [comment] 2020-11-24 11:04
That would be true if you departed and arrived at the same airport/country. @Kimbyeoungjang 
But what if you take off somewhere where TA is 3000 (TRL FL040) let's say, then you land in a country where TRL is FL120 (TA 10500) or flew the other way around?

**Comment by Kimbyeoungjang** [comment] 2020-11-24 11:26
> That would be true if you departed and arrived at the same airport/country. @Kimbyeoungjang
> But what if you take off somewhere where TA is 3000 (TRL FL040) let's say, then you land in a country where TRL is FL120 (TA 10500) or flew the other way around?

I'm so confuse now. Transiton Altitude and Transition Level is different. if you takeoff with Transition ALT setting with 4,000ft and going to Transition ALT is 12,000ft, that will work when you enter Transition Level on PERF - Appr phase.

My code working with Phase. when you going to descend, you should enter Transition LVL on APPR phase(pre-programming) and will STD flashing when reach FL120.

If that is wrong, i need reference for fix that.

**Comment by Kimbyeoungjang** [comment] 2020-11-24 11:27
![image](https://user-images.githubusercontent.com/23118756/100088393-638a2480-2e93-11eb-885d-db618e14d208.png)
that is basic qnh rule that i know(i only know that rule). always Trans LVL is higher than Trans Alt

**Comment by Kimbyeoungjang** [comment] 2020-11-24 12:17
pilot confirmed. Trans LVL always higher than Trans ALT.

so you can't insert 4,500ft when you're not setting Trans ALT on takeoff page
current we can't automatically insert Trans ALT because asobo is not add trans alt information

you can watch #2068 issue. that issue have relate problem(trans alt currently default 10,000ft(also trans lvl because current logic is weak, need more accurate flight phase logic))

**Comment by Tonyehrd** [comment] 2020-11-24 12:32
> pilot confirmed. Trans LVL always higher than Trans ALT.
> 
> so you can't insert 4,500ft when you're not setting Trans ALT on takeoff page
> current we can't automatically insert Trans ALT because asobo is not add trans alt information
> 
> you can watch #2068 issue. that issue have relate problem(trans alt currently default 10,000ft(also trans lvl because current logic is weak, need more accurate flight phase logic))

No, you are wrong, you are talking about TRANS LVL, we are talking about a TRANS ALT here. As an example, I just took off from LOWI = TRANS ALT 11000 and where I'm going to land (Schiphol) is the TRANS ALT 3000FT. But because I have placed TA11000 in the t / o page, I cannot go lower than FL11000 at appr page. It shouldn't work like that.

**Comment by beheh** [comment] 2020-11-24 12:38
> pilot confirmed. Trans LVL always higher than Trans ALT.

At a single airport, yes. But not at two different airports, possibly in two different countries.

**Comment by Kimbyeoungjang** [comment] 2020-11-24 13:23
> > pilot confirmed. Trans LVL always higher than Trans ALT.
> 
> At a single airport, yes. But not at two different airports, possibly in two different countries.

i can't understand. on the appr page, should insert trans alt isn't it?

in your example, when you takeoff from LOWI, in perf, takeoff transition altitude setting to 11,000

and you're going to insert schiphol airport trans alt to appr phase trans lvl?

**Comment by Tonyehrd** [comment] 2020-11-24 13:26
You do not understand! If I would fill in trans LVL it would be TRA LVL 4500. But I can't type that in either! Because LOWI is already on tra lvl 12000.

**Comment by Kimbyeoungjang** [comment] 2020-11-24 13:31
sorry about my bad english. i just thought schiphol have a transition lvl 3,000ft

anyway, you think mcdu can insert trans level that lower then trans alt is it correct?

**Comment by Tonyehrd** [comment] 2020-11-24 13:37
Schiphol transition ALT is 3000 but transition LVL depends on QH.

**Comment by Kimbyeoungjang** [comment] 2020-11-24 13:57
I’ll fix that tomorrow. Here is 11PM

Sorry about that. I just thought APPR page have trans lvl but it is not. I’ll fix that

**Comment by beheh** [comment] 2020-11-24 14:26
There is no need to open a new PR for the PERF page, there is a major rework already in progress at #1824 (as I've mentioned above). I am implementing field validation as per the Honeywell documentation, so if it's not referenced there then as soon as my PR lands this will be fixed.

**Comment by Kimbyeoungjang** [comment] 2020-11-24 14:30
> There is no need to open a new PR for the PERF page, there is a major rework already in progress at #1824 (as I've mentioned above). I am implementing field validation as per the Honeywell documentation, so if it's not referenced there then as soon as my PR lands this will be fixed.

but my PFD function is wrong. i'll fix that quickly. testing now...

**Comment by MStallen** [comment] 2020-11-27 15:21
@Tonyehrd You are right. But i've another question. If I change the baromteric above TA to STD, ATC is calling me that I'm not on my correct altitude. Is that a bug in MSFS 2020?

**Comment by ImenesFBW** [comment] 2020-11-27 18:36
@MStallen the in-game ATC uses the American standard of FL180 , all over the world, so if you use the accurate one from the charts they will yell at you.

**Comment by Tonyehrd** [comment] 2020-11-27 22:51
> @MStallen the in-game ATC uses the American standard of FL180 , all over the world, so if you use the accurate one from the charts they will yell at you.

Exactly!

**Closed** 2020-12-01 16:24 UTC
Labels: Bug
