### ISSUE TITLE
[BUG] Flaps 1 enormous amount of drag while descending via G/S

### ISSUE THREAD

**Issue by d3cadeaf** [flybywiresim/a32nx#3939] opened 2021-03-12 10:10 UTC
**Mod Version**
Custom FBW 4cfc87c

**Describe the bug**
If the aircraft start descending via glide slope with ATHR and flaps 1 the engines spool up very high without accelerating. Also the airspeed gets reduced extremely fast. 
If flaps 2 were selected afterwards the engines spool down to a "normal" value.

**To Reproduce**
1. ILS Approach + ATHR + CL Throttle
2. Set flaps 1
3. Wait for G/S descending
4. Watch the Engine ECAM page and airspeed :)

**Expected behavior**
I think the behavior with flaps 2 is correct.

**Actual behavior**
It seems like flaps 1 does an enormous amount of drag while G/S descending so the engines have to fight against it.

**References**
Here is a ENCN approach video, the bug is noticeable at around 0:27 -1:03.

https://drive.google.com/file/d/1v6ogVUz1d2UcEP9V6u2zUPAsUpDXH_iL/view?usp=sharing

**Additional context**
I'm not a professional simmer, pilot or developer, just wondering about the behavior.

Was this working before/when did the issue start occurring?
Yes, this was no problem in previous versions.

Is this a problem in the vanilla unmodded game?
Didn't test it. Didn't fly the default A320 for a looooong time. :)

Discord username (if different from GitHub):
d3ca.deaf#0379

**Comment by beheh** [comment] 2021-03-12 11:54
Duplicate of #3913.

**Closed** 2021-03-12 15:57 UTC
Labels: Bug, Flight Model
