### ISSUE TITLE
[REQUEST] MCDU should be independent 

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#1409] opened 2020-10-16 18:22 UTC
Each MCDU should function independently 

Each time you press a button on the MCDU it should not mirror on the other 

**References**

**Additional context**

Zyonix007#0001

**Comment by Benjozork** [comment] 2020-10-16 18:56
Duplicate of #1058

**Closed by Benjozork** 2020-10-16 18:56 UTC
Labels: Enhancement
