### ISSUE TITLE
[BUG] LOC acquired indicated, but not locked on final

### ISSUE THREAD

**Issue by lve0200** [flybywiresim/a32nx#2104] opened 2020-11-26 14:13 UTC
**Mod Version**

 latest dev as of 26.11. noon

**Describe the bug**

EDDH ILS23 APP, clear skies. 1.11.6 latest patch. Although LOC is shown in PFD, locator is not locked and plane is misaligned. see picture

**To Reproduce**

1. Fly ILS APP, activate LS in PFD and see
2.
3.

**Expected behavior**

As b4 patch

**Actual behavior**

Although LOC is shown in PFD, locator is not locked and plane is misaligned. see picture Misalignment is present from T/G until short final, w/out any attempt to correct.

**References**

screenshot

**Additional context**

Was this working before/when did the issue start occurring? YES

Is this a problem in the vanilla unmodded game?
n/a

Discord username (if different from GitHub):

![Bv5YmX5Qwx](https://user-images.githubusercontent.com/47894777/100360976-e4fbc700-2ff9-11eb-8ad1-9b32589a8296.jpg)

**Comment by HubertGer** [comment] 2020-11-26 14:39
same by me with vers 0.41 and also with master

**Comment by lve0200** [comment] 2020-11-26 14:59
Bug confirmed not present in Vanilla Bus
![YJpSIqttJ6](https://user-images.githubusercontent.com/47894777/100365830-4757c600-3000-11eb-9562-c4631676afc4.jpg)

**Comment by Brathwa** [comment] 2020-11-26 15:44
> Bug confirmed not present in Vanilla Bus
> ![YJpSIqttJ6](https://user-images.githubusercontent.com/47894777/100365830-4757c600-3000-11eb-9562-c4631676afc4.jpg)

is the A320 vanilla flying normally?

**Comment by lve0200** [comment] 2020-11-26 15:53
> is the A320 vanilla flying normally?

Havn't done any testing so far, except for ILS APP in an EDDH circuit pattern. The usual stuff is still there. The cockpit is still the old mess and it flairs like a brick.

**Comment by Benjozork** [comment] 2020-11-27 00:13
Duplicate of #2089

**Closed by Benjozork** 2020-11-27 00:13 UTC
Labels: Bug

**Comment by HubertGer** [comment] 2020-11-27 07:33
I have testet it with the original ASOBO A320, the same thing. ILS does capture, but follow the ILS not correctly. I will delete both (A320NX and the original) and will test it without the A320NX again.
