### ISSUE TITLE
[BUG] Specified speed don't work when CRZ phase is activate

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#919] opened 2020-09-27 08:40 UTC
**Mod Version**

v0.3.0

**Describe the bug**

managed speed when CRZ phase is activate

**To Reproduce**

1. The plane arrive at planned FL
2. In Perf menu, activate CRZ phase
3. 

**Expected behavior**
IAS should be around the speed requested in CRZ page

**Actual behavior**

Speed decreases enormously and is not around the managed speed displayed in this page

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by tareksabet** [comment] 2020-11-15 19:02
can't reproduce, closing now.

**Closed by tareksabet** 2020-11-15 19:02 UTC
Labels: Can't Reproduce
