### ISSUE TITLE
Autopilot - flickering inputs, disconnecting when reducing throttle from TOGA to CLB. Thrustmaster Airbus Edition.

### ISSUE THREAD

**Issue by Peyto79** [flybywiresim/a32nx#5812] opened 2021-09-12 15:11 UTC
### Aircraft Version

Development

### Build info

```json
Current Dev and Experimental Version.
```

### Describe the bug

It was working normally until last thursday. I am using the Development Version.
Autopilot is starting flickering weird as soon as I reduce the thrust from TOGA to CLB and its not working anymore.
As soon as I go back to TOGA it's working again.

My thrustlevers are calibrated in SIM and on Flightpad with enough Dead-Zone.

With the Stable Version it works normally but not with Dev and Experimental Version.

I use the Thrustmaster Airbus Edition with the Full Option Thrust Levers (with Add-Ons installed as well).

I have above 17fps and it worked until I installed the newest Dev Version of the A320 on Friday. So I assume it is a bug in the current build and not a problem of my PC.

Thanks for having a look.

Many greetings
Chris

### Expected behavior

Autopilot is not flickering

### Steps to reproduce

Take off
Reduce Thrust Levers from TOGA to CLB
Autopilot displays flicker and also in primary flight display.

**Comment by aguther** [comment] 2021-09-12 19:01
Can you please provide an FDR file from the flight in question?

See reporting issues here:
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/autopilot-fbw/

A video would also be helpful to better see what you mean with flickering, I have an idea but experience tells me that’s it’s better to be clear on the effect.

I can tell you right away that I cannot reproduce it…that’s why it’s important to understand what is going on. I have an idea what could be the issue, but want to confirm.

For larger files you can use Swisstransfer as an example and provide the link here.

**Comment by Peyto79** [comment] 2021-09-12 20:15
I just created a video and uploaded it to YouTube. Here is the link:

https://youtu.be/WtVWANb0a5Y

You can see before takeoff that everything is normal. I point with the mouse curser on the relevant parts of the displays.
After takeoff i reduce the thrust to climb and the displayed Autopilot information is starting to flicker.
Also the managed navigation switches automatically to HDG mode without the possibility to switch it back. 
As soon as i move the thrust lever to TOGA everything is back to normal and autopilot would work normally.

I hope it helps to understand the issue.

**Comment by aguther** [comment] 2021-09-12 21:04
Yeah, this issue is familiar. It's nothing related to the AP itself, it's the flight phase of the FMGC that is not correct and therefore the AP has issues:
https://github.com/flybywiresim/a32nx/issues/5587

**Comment by aguther** [comment] 2021-09-12 21:05
Duplicate of https://github.com/flybywiresim/a32nx/issues/5587

**Closed by aguther** 2021-09-12 21:05 UTC
Labels: Bug
