### ISSUE TITLE
Plane not following STAR

### ISSUE THREAD

**Issue by A320PHX** [flybywiresim/a32nx#2244] opened 2020-12-05 21:23 UTC
Version
Most Recent Dev Version

Bug
Plane does not fly STAR. Over the past two flights I have done, the plane veers off course. This last flight was from Gatwick to Madrid. Right at the Orbis waypoint, the plane banked hard right (not as hard as before though) and I had to quickly intervene manually to get us back on course. Everything else is working good other than altitude constraints which has been mentioned in another bug report. The plane was able to lock onto the LOC and G/S no issue.

To Reproduce
1. Load up a flight plan with SIDs and STARs,
2. Plane will fly entire route no problem.
3. Once you arrive at the first waypoint in the STAR, the plane will either veer right or left (seems random at this point).

Expected behavior
For the aircraft to follow the entire STAR until I get visual and take control.

Actual behavior
Plane reached the STAR and the plane turned off course requiring manual intervention to rectify the issue.

Was this working before/when did the issue start occurring?
After the most recent update that you guys released to fix the autopilot (Awesome job by the way. Thanks for making the plane flyable again!)

Is this a problem in the vanilla unmodded game?
I actually don't know as I have not been able to go back to it after your updates.

**Comment by Benjozork** [comment] 2020-12-05 21:24
Can you verify if the direction the plane is steering towards is the airport ? That is a known problem

**Comment by A320PHX** [comment] 2020-12-05 21:35
It was turning in the general direction of LEMD. But at the angle it was banking at, it would have continued to turn away from the airport. I know the known problem has it flying towards the arrival runway. This was not the case here.

**Comment by Benjozork** [comment] 2020-12-05 22:18
> Most Recent Dev Version

When did you download it ?

**Comment by A320PHX** [comment] 2020-12-05 22:21
Probably around noon or so.

**Comment by vstaritz** [comment] 2020-12-06 04:01
I will use this to say that the #1253 is still very much a thing and not strictly reserved to approaches that pass near the airport. I did three different flights recently where the AP skipped to the RWxx waypoint much too early even though i was a fair way away from the airport itself or the ILS. It happened on older versions, but mostly rare.
using #2179 and #2140 as well. It's still probably a asobo issue but it might have become worse somehow.

**Comment by xtermin8or216** [comment] 2020-12-06 05:08
I also was experiencing this on my last flight From Melbourne to Adelaide, plane just starts banking hard left or right without stopping.

**Comment by txsty364** [comment] 2020-12-06 07:41
Have you check your flight plan in your MCDU? I've noticed that there was a "USER" waypoint that directed to the RW (Runway) and the only workaround that I know of was to direct to a way point

**Comment by 2low2slow** [comment] 2020-12-06 13:22
Happens to me quite frequently with the plane veering directly towards the runway.
I then either disengage AP or DIRECT to next waypoint (rinse and repeat) until I get a lock on ILS glide slope.

**Comment by A320PHX** [comment] 2020-12-06 17:38
> Have you check your flight plan in your MCDU? I've noticed that there was a "USER" waypoint that directed to the RW (Runway) and the only workaround that I know of was to direct to a way point

I have, I actually make it a point to remove all USR waypoints when putting in the route. One time I swore I looked through it and didn't see anything. Later in the flight, when reviewing the approach it was there. I try to clear it, but the plane still got tripped up on it.

**Comment by A320PHX** [comment] 2020-12-06 17:41
> I will use this to say that the #1253 is still very much a thing and not strictly reserved to approaches that pass near the airport. I did three different flights recently where the AP skipped to the RWxx waypoint much too early even though i was a fair way away from the airport itself or the ILS. It happened on older versions, but mostly rare.
> using #2179 and #2140 as well. It's still probably a asobo issue but it might have become worse somehow.

I am aware of that bug as well. The approaches have failed both with very tight approaches, and one like on my test flight that was at about a 45* angle from the final approach heading. No joy. I think for now, I will just have to disable managed heading mode before I get to the STAR waypoint and fly it using vectors until I can use LOC and APPR modes.

**Comment by tylerdola** [comment] 2020-12-06 20:04
This bug has been around for months and I don’t think it is a32nx related. I’ve had it happen in other aircraft as well. Very annoying when after a long flight, you spend the STAR fighting with the plane and manually vectoring around to the approach. I have to always watch the next waypoint to see if it says RWYxx instead of what I expect and then quickly dial in a heading to the next. At least now I know it is when my STAR takes me close and past the airport on route to an approach. Recently happened at CYVR on the CANUC5 star into RWY08R

**Comment by tylerdola** [comment] 2020-12-06 20:34
Should this be closed as a duplicate of #1253 ?

**Comment by lve0200** [comment] 2020-12-13 10:01
> I also was experiencing this on my last flight From Melbourne to Adelaide, plane just starts banking hard left or right without stopping.

There is probalbly a convoluted picture at play. I found that this behavior is caused by two different problems: 1) is #1253 and #2345 
and 2) the PID settings in ai.cfg for "heading".
From a SW point of view, I believe (can't proof) that the PID Algo goes into an overflow, when the I parameter is chosen too high. The PID might go into an increasing oscillation. (see PID theory)
You can try "my" values as following:
headingPID = 2.5, 0.4, 0.3, 0.05, 1.0
I was able to reproduce the problem consistently by setting I to 1 and Imax to 0.1.

**Comment by ischmal** [comment] 2020-12-19 12:02
Two related symptoms here I think:
 1. STAR gets completely ignored
 2. ILS is grossly misaligned with the runway

Okay, so I believe this may actually be a major issue caused by custom or premium sceneries at destination airports. (I'm not talking about just a few instances either -- it's literally happened to me every single time.) Conversely, this problem has _never_ transpired when landing at a "generic/plebian" airport. No idea as to what the hell is up with this, but I'd suggest never using starred airports as your destination until Asobo can fix it.

Also, if you wanna check whether or not you're about to get screwed by the AP because of this, verify that your desired ILS frequency was automatically set on the RAD-NAV page. If not... bad news.

**Comment by MisterChocker** [comment] 2020-12-31 06:20
duplicate of #1253

**Closed by MisterChocker** 2020-12-31 06:20 UTC
Labels: Bug
