### ISSUE TITLE
BUG  App disengage  when AP off and loc engage 

### ISSUE THREAD

**Issue by griffon55** [flybywiresim/a32nx#514] opened 2020-09-08 17:19 UTC
**master**

**when I disengage autopilot app disengage and loc engage itself**

**To Reproduce**

1.
2.
3.

**when disengage autopilot app must stay engage and no loc engage**

**Actual behavior**

**References**

**Additional context**

**Comment by Benjozork** [comment] 2020-09-08 17:47
You didn't write anything in the issue.

**Comment by SmithFR** [comment] 2020-09-08 18:55
Duplicate of #146 and #323

**Comment by griffon55** [comment] 2020-09-08 19:19
I tried but no text appear. Anyway problem  is in the title

**Comment by Benjozork** [comment] 2020-09-08 19:29
> I tried but no text appear. Anyway problem  is in the title

You need to provide all the required information. it is needed to help us reproduce the problem.

**Comment by griffon55** [comment] 2020-09-08 20:04
https://s.amsu.ng/S05LqvE791oN

**Comment by tareksabet** [comment] 2020-11-15 16:41
closing now it's fixed by #1715

**Closed by tareksabet** 2020-11-15 16:41 UTC
Labels: Autopilot, Bug, FCU
