### ISSUE TITLE
Printing an ATIS report crashes to desktop some times after upgrading MSFS to SU5

### ISSUE THREAD

**Issue by Rascal650** [flybywiresim/a32nx#5429] opened 2021-07-28 05:16 UTC
### Aircraft Version

Development

### Build info

```json
Latest dev build as of 7/27
```

### Describe the bug

AFTER SU5 upgrade using the latest dev build of FBY (as of 7/27):

1- Get an ATIS report, send it to your message queue
2- View the ATIS report in your message
3- Click on Print

BUG: crash to desktop (able to reproduce every time)

### Expected behavior

Should not crash.

### Steps to reproduce

1- Get an ATIS report, send it to your message queue
2- View the ATIS report in your message
3- Click on Print

**Comment by MisterChocker** [comment] 2021-07-28 08:31
Please provide the build info as described in the template

**Comment by aguther** [comment] 2021-07-28 09:50
In tests with the preview version it worked without issues. Will do another test when final build is downloaded (preview and final version have the same version number).

**Comment by Rascal650** [comment] 2021-07-28 14:21
I'm using Dev 9d2c910, still the latest dev version from what I can see this morning.    
Printing an ATIS was working fine for months.  I noticed this bug after upgrading to SU5.  Is there a crash log / stack trace I can send you?
I'm also noticing some problems with no being able to set an altitude in managed mode since SU5. The speed indicator in the PFD jumps up and down sometimes. Finally, the TAT temperature at high altitudes ( FL > 200) seems to be off.  I sometimes get +30C  and a bit later,  it's below freezing.    Never seen these problems before SU5.  I had the engine start problem with the Thrustmaster Airbus quadrant (button 3 & 4) but I saw your release notes;  that did the trick.
Should I report bugs for those or are they known problems associated with SU5?
Many thanks for your effort guys;  this is an AWESOME project!
Pascal
    On Wednesday, July 28, 2021, 02:50:47 AM PDT, Andreas Guther ***@***.***> wrote:  
 
 


In tests with the preview version it worked without issues. Will do another test when final build is downloaded (preview and final version have the same version number).

**Comment by Benjozork** [comment] 2021-07-28 14:22
The SAT and TAT are provided by the simulator, not the A32NX. Currently, their live weather service is bugged and will give erratic temperatures. 

For the selected heading issue, make sure to read through the following section on the documentation website:

https://docs.flybywiresim.com/start/reported-issues/#su5-issues

**Comment by Rascal650** [comment] 2021-07-28 14:34
Understood and thanks for the update.
Besides the "printing crash", managed altitude change is my main post-SU5 problem (i.e. pushing the altitude knob only works once in a while, most of the time, I don't get the "dot").  I have to use the V/S dial for most of the altitude changes.  Is that due to the SAT / TAT bug, which in turns, confuses the AP?
Pascal
    On Wednesday, July 28, 2021, 07:23:05 AM PDT, Benjamin Dupont ***@***.***> wrote:  
 
 


The SAT and TAT are provided by the simulator, not the A32NX. Currently, their live weather service is bugged and will give erratic temperatures.

For the selected heading issue, make sure to read through the following section on the documentation website:

https://docs.flybywiresim.com/start/reported-issues/#su5-issues

**Comment by aguther** [comment] 2021-07-28 18:46
Ok, I can confirm the issue. I have it now, too. Wasn't the case with the preview :-(

**Comment by 2hwk** [comment] 2021-07-29 04:05
Verified to be working on 1.17.13 ✔️

**Comment by Rascal650** [comment] 2021-07-29 04:17
FYI:  the crash happened every time for me after upgrading to SU5.   I then deleted FS's cache and did a clean install of the latest FBW build (which was the same dev build number as yesterday);  I can now print an ATIS report  (tried 4 times; no crash).

Another issue (not sure if it's in SU5):  when I press ESC (to bring the menu) and ESC again (to return to the cockpit),  my flaps go down to full.  I've read that other people are reporting this problem too.  Not sure if it's a mapping problem, will check tomorrow.
Pascal
    On Wednesday, July 28, 2021, 09:05:39 PM PDT, 2hwk ***@***.***> wrote:  
 
 


Verified to be working on 1.17.13 ✔️ , SU5 issue.

**Comment by glowfishDE** [comment] 2021-08-07 11:22
I can confirm this issue. I experience the same after the latest FS Sim Update 5. I have the Dev Version 10169b4 installed.

**Comment by ErikNL80** [comment] 2021-08-07 11:43
Hi did not have this issue before, however today also with 10169b4 a first CTD.

**Comment by Joe8617** [comment] 2021-08-07 23:24
I also experienced an instant CTD when trying to print ATIS today.  Thx.

**Comment by Mancoon-Crest** [comment] 2021-08-15 15:41
Same here, DEV edition up to date as of today 15.08.2021. CTD every time I try to print METAR infos.

**Comment by tracernz** [comment] 2021-08-15 22:14
Does your livery have a model folder in it?

**Comment by Joe8617** [comment] 2021-08-15 22:28
I'm not sure what you mean?  Where should I look, happy to help.

-Joe

**Comment by aguther** [comment] 2021-08-16 05:30
Can you try to remove all liveries and check if it still happens then?

**Comment by Joe8617** [comment] 2021-08-16 05:41
Yep, first thing in the morning.

Thx again.

**Comment by Mancoon-Crest** [comment] 2021-08-16 08:19
Just tried this with the FBW Livery on and it worked like a charm! The Livery I used did not have a model folder in it though.

**Comment by aguther** [comment] 2021-08-16 10:48
Then for some reason it's related to the livery (I'm using a Lufthansa livery and it also works with it).

**Comment by Mancoon-Crest** [comment] 2021-08-16 12:40
Let me know if you need the liveries I used to maybe search for the culprit.

**Comment by Joe8617** [comment] 2021-08-16 22:51
I removed all liveries and so far have not had a CTD when printing.
Interestingly, when I click print now, the paper just shows up below the
MCDU, I didn't have to (and cannot) click on it to remove it from the
printer.  I hope that makes sense?  Is that new normal behavior or some
glitch?  It's not a problem for me.

Thanks again for your help.  You guys are awesome.

-Joe

**Comment by jamescooper89** [comment] 2021-08-17 11:23
This happened to me yesterday as well, Approaching Zurich requesting print of the METAR, DEV Build from the installer using UKV Livery

**Comment by blokkie58** [comment] 2021-08-17 20:58
I can unfortunately also confirm this during a flight from EHAM to EGKK, however, on the ground before taxiing, requesting/printing the METAR information was no problem

**Comment by Joe8617** [comment] 2021-08-17 23:05
I took all my liveries out and had no problem printing....  But I was still
on the ground.  And the "paper" went straight up and stuck below the mcdu,
I didn't have to click on it to get it up there.

Thanks again,

Joe

**Comment by Teslix** [comment] 2021-08-25 03:52
I just experienced my first "Print METAR message" CTD as well. Never been an issue until this first time tonight, so I'm not sure if it's hit or miss - I've definitely printed in this livery and build before and I'm on experimental.

**Comment by ErikNL80** [comment] 2021-08-29 19:08
I had one just now on my flight from EGGW to EHEH... After the message comes in I wait a few seconds before printing, and normally this helps, but now a CTD right away :(

**Comment by Mancoon-Crest** [comment] 2021-09-04 14:54
Just wanted to let you know, I just had a "METAR print CTD" but using the A320 NEO default livery! Falling back to one of the two house liveries always helped before. DEV build up to date.

**Comment by igormagun** [comment] 2021-09-10 20:30
Experienced this issue once on SU5 - was hoping WU6 might fix it but I got it again today, crash immediately after hitting Print for METARs. Haven't been able to reproduce it, but I also got a crash exiting to the main menu after failing to reproduce it, not sure if that's related.

**Comment by donstim** [comment] 2021-09-16 05:43
Here is my experience with this issue for what it's worth. I had a CTD the other when trying to print a METAR while in descent when flying between KSEA and KSLC. In dev mode, default livery. After may hours spent testing today, having starting in flight without a flight plan, I decided to check what would happen if I tried to print a METAR for the same route. Put in KSEA/KSLC as the route with a cost index of 6 and cruise alt of FL390. Requested a METAR weather report, and sure enough, a CTD when I tried to print it.

Re-started MSFS, started another flight in flight, put same info in the MCDU, requested METAR, went to print it, and it printed just fine. It was **exactly** the same METAR as in the CTD case.

**Comment by MisterChocker** [comment] 2021-09-20 15:35
Thats interesting maybe worth looking into.

**Comment by jaoord** [comment] 2021-10-16 13:28
Crashed for me too today. 

Version info:

{
  "built": "2021-10-11T13:03:49+00:00",
  "ref": "master",
  "sha": "373c1694eecd325168c2b501e60a126eda9f4b13",
  "actor": "aguther",
  "event_name": "manual"
}

It has worked before for me after SU5, but maybe not this version of the aircraft.

**Comment by 2hwk** [comment] 2021-10-20 08:56
SU6 may have fixed this issue, will watch and see. If nothing this will be closed.

**Comment by maowlirus** [comment] 2021-10-30 18:15
I also have this issue.
It is not easily reproducible, sometimes it happens, sometimes it doesn't.
I just crashed twice at the gate with the same aircraft/location/METAR request setup. The third time around it works like a charm, I can print several times and it doesn't crash.
METARs have not changed.
It seems that this is unrelated to the livery or the specific METAR.
My guess would be something with the animation, maybe it depends on how many ground workers are currently loaded in the sim or something like that.
Does anyone have a pointer how to identify the issue? 
MSFS doesn't have a proper log I think...

**Comment by Tuftymeercat37** [comment] 2021-11-01 11:43
Happening to me now.
Load flight from Simbrief. GMAD to GCRR (with GCLP as alternative)
Request WX, view when received then go to print....boom...CTD.
Reloaded MSFS and input flight manually GMAD to GCRR (omitted alternative airport). Was able to request WX and print without problem.
Tried again loading flight from Simbrief GMAD to GCRR with GCLP as alternative and CTD on WX print.
Can't see anything odd in the Metar data.

**Comment by foxmike80** [comment] 2021-11-01 16:10
Same thing happened here again: Loaded flight EDDS-LGIR from Simbrief. Request WX for EDDS, LGIR, LGAV and CTD.

**Comment by jaoord** [comment] 2021-11-01 17:27
@foxmike80 Wait, it happens for you on weather request? Not on print?

**Comment by foxmike80** [comment] 2021-11-01 20:36
> @foxmike80 Wait, it happens for you on weather request? Not on print?

No, only on printing. Sorry, that this was confusing. My bad.

**Comment by P1NBA11ER** [comment] 2021-11-01 23:43
Also had one of these a couple nights ago for the first time in awhile.

**Comment by ErikNL80** [comment] 2021-11-06 19:13
I did did a night approach into Athens, at approx. 24.000ft requested METAR for LGAV. After receiving it and press Print, instant CTD (sound stuttering, and then in 1-2 seconds to desktop).

**Comment by billw2012** [comment] 2021-11-09 21:20
Had this a couple of times now in stable build (making it a 1/10 occurrence when printing ATIS). Crash dump shows access violation reading some none 0 address. So its not a null pointer access, but some invalid address.
Most recently it was printing PANC ATIS about 160nm out, departing from PAJN. Actually one possible confound: I accidentally clicked ATIS button twice, so I had two reports and attempted to print the newest one. Maybe something dodgy there somehow? I will try repro it...

**Comment by tracernz** [comment] 2021-11-10 05:14
> Had this a couple of times now in stable build (making it a 1/10 occurrence when printing ATIS). Crash dump shows access violation reading some non 0 address. So its not a null pointer access, but some invalid address.

Yep, exactly that. Since MSFS is a big monolithic exe though there aren't any symbols to even get a clue what's happening in the stack trace.

> which could lead to race conditions if execution can be paused on any line.

To my knowledge, the JS runtime executes each callback to completion (or to the next await for async code, which means another callback queued). I do see at least one async function in there... `SimVar.SetSimVarValue`

A potential fix is in:
https://github.com/flybywiresim/a32nx/pull/6088

**Comment by G3NSVRV** [comment] 2021-11-10 16:05
Same happens when I print METAR using A32XN 0.7.2, but does not happens all the time.

Windows Log
```log
Faulting application name: FlightSimulator.exe, version: 1.20.6.0, time stamp: 0x00000000
Faulting module name: FlightSimulator.exe, version: 1.20.6.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000000000123c1da
Faulting process ID: 0x31e4
Faulting application start time: 0x01d7d649e17b8574
Faulting application path: D:\SteamLibrary\steamapps\common\MicrosoftFlightSimulator\FlightSimulator.exe
Faulting module path: D:\SteamLibrary\steamapps\common\MicrosoftFlightSimulator\FlightSimulator.exe
Report ID: eb469567-76a8-4cd8-83a5-75ad64338677
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Saschl** [comment] 2021-11-10 16:21
The mentioned potential fix is now available in dev and experimental.

 It might take a while until it arrives in the next stable so you might be advised to not print on stable or use dev/experimental for the time being.

**Comment by Saschl** [comment] 2021-11-21 11:48
Closing since the change is available on all versions now. Please feel free to open a new issue if it should occur again.

**Closed by Saschl** 2021-11-21 11:49 UTC
Labels: Bug, Critical Bug, Waiting For Response
