### ISSUE TITLE
IR isn't aligned when starting from runway

### ISSUE THREAD

**Issue by oldmanbishop** [flybywiresim/a32nx#4946] opened 2021-05-29 00:19 UTC
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-05-05T06:28:31+00:00",
  "ref": "experimental",
  "sha": "ff7f81fbff658ba8a69c77f6a16754ad1bffabea",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Loading direct to runway the IR still has ~4 minutes left on align. 

### Expected behavior

Loading to runway should be a fully setup and ready to takeoff plane (based on menu selections).

### Steps to reproduce

1) select any airport and runway
2) select ready to fly.
3) observe the PFD, ND, and ECAM

**Comment by Benjozork** [comment] 2021-05-29 00:25
You are using a very old version. Please switch to dev as it has all features of experimental, which itself isn't updated anymore.

**Comment by oldmanbishop** [comment] 2021-05-29 00:32
Thanks, didn't know experimental was deprecated.

**Comment by MisterChocker** [comment] 2021-05-29 08:13
Duplicate of #4506

**Closed by MisterChocker** 2021-05-29 08:13 UTC
Labels: Bug, Waiting For Response
