### ISSUE TITLE
AP is not able to hold cruise flight level after small turbulences 

### ISSUE THREAD

**Issue by Daboj1337** [flybywiresim/a32nx#5487] opened 2021-07-31 09:48 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-30T14:00:27+00:00",
  "ref": "master",
  "sha": "5668670c9fdcd56a31b2a46c95272013fb65e013",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

On cruise fl with AP on, the aircraft cant hold the altitude after small turbulences. 
I can only climb or descend back to crz fl with vertical speed

<img width="618" alt="Unbenannt" src="https://user-images.githubusercontent.com/76589309/127735913-50b08b23-271d-4ca0-af2f-67a8c072e29f.PNG">

### Expected behavior

Hold the flight level 

### Steps to reproduce

Start a flight and climb to crz fl. Set small turbulences in the weather menue

**Comment by FRYYYYYY** [comment] 2021-07-31 10:53
I think this has something to do with the sim update 5 and the live weather issues. Sometimes you will see that a "hard turbulence" will hit the plane and everything is weird. 
Altitude should be fixed by the SU5 Hotfix, but it isnt. So I think this has nothing to do with FBW Mod.

**Comment by aguther** [comment] 2021-07-31 11:12
Yeah, the issue is on MSFS side. Currently the pressure altitude is completely wrong calculated and indicated altitude does not match pressure altitude when set to STD.

We tried already to fix it somehow but did not find a way yet. Honestly I‘m also personally tired to fix stuff with a lot of work to workaround things that should be correct in a simulation in my free time. Maybe we get a new idea how to workaround it with doable amount of work.

I keep this open, so people kind find it, but we cannot do anything right now.

**Comment by aguther** [comment] 2021-07-31 13:20
https://docs.flybywiresim.com/start/reported-issues/#su5-issues

**Comment by Gurkonier** [comment] 2021-07-31 15:24
I understand, that the pressure altitude thing and the hard turbulences are a MSFS problem. But shouldn't the autopilot still be able to follow the indicated altitude after this kind of event? For me, once i got hit by this turbulence, i had to let the plane go a certain amount high or below the assigned altitude (maybe +- 700ft) to be able to select it again, for the plane to reactivate vnav.

**Comment by aguther** [comment] 2021-07-31 15:36
@Gurkonier The problem is that the ALT HOLD mode needs to be robust against ALTIMETER BARO changes. So the question was how to deal with it. I had now the idea with the additional altimeter that is always using STD. This makes ALT HOLD robust against altimeter baro changes when used as pressure altitude. By the way the real plane also uses pressure altitude for ALT HOLD.

The downside of the workaround is, that the pressure altitude will be still wrong. So potentially it will not solve the issues with ATC and VATSIM.

**Comment by lolisec** [comment] 2021-07-31 15:44
I've also experienced this myself when doing a flight from EDDM to EHAM couldn't stay on correct altitude during strong cross wind

**Comment by aguther** [comment] 2021-07-31 15:47
I mean if turbulences occur there might be still a short diversion from altitude, also don't forget that there is also SOFT ALT mode. But those things are usually short term.

The extreme divert that can be observed right now is only coming due to pressure changes and wrong calculation of values in MSFS.

**Comment by aguther** [comment] 2021-07-31 15:48
But I can tell you that I'm right now flying for 1 h on FL350 through different pressure zones and the workaround works quite well. So help is underway.

**Closed** 2021-07-31 20:43 UTC
Labels: Asobo Bug
