### ISSUE TITLE
PSI Value on ENG ECAM Page going blank

### ISSUE THREAD

**Issue by OFC1983** [flybywiresim/a32nx#6861] opened 2022-03-06 16:23 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-05T21:25:08+00:00",
  "ref": "master",
  "sha": "bf05cc86b1a0736fad4ced1e85bfbee8ad8fc426",
  "actor": "Saschl",
  "event_name": "manual",
  "pretty_release_name": "master:bf05cc86"
}
```

### Describe the bug

The PSI Value on the ENG ECAM Page goes blank after engine startup. I have this issue for a long time now.

### Expected behavior

Showing the actual PSI Values

### Steps to reproduce

Startup the A32NX and check the ENG Page for the PSI values

**Comment by tracernz** [comment] 2022-03-07 05:09
Can you share a screenshot? The oil pressure comes from the MSFS engine model and is wrong currently, but that should cause it to (correctly for the pressure read) blink... not go blank?

**Comment by OFC1983** [comment] 2022-03-08 20:43
I will with my next flight next weekend…

**Comment by OFC1983** [comment] 2022-03-13 13:45
![PSI Values](https://user-images.githubusercontent.com/72392200/158062430-990e63bc-3d3d-4277-8ee0-194a3eed16ca.JPG)
Made the screenshot today and can confirm this happens on every flight. As soon as PSI value exceeds 120 the indicator goes blank...

**Comment by juliansebline** [comment] 2022-05-12 12:11
I've had a look, there's something wrong with the CSS (file Eng.css, class .FillPulse or .LinePulse). 

If you remove the blinking code and set a red color for example, the text is showed in red.

**Comment by juliansebline** [comment] 2022-05-12 15:10
I've ran some tests and blinking does not work in cabin alitude either but the text remains

Did it ever worked ?

**Comment by juliansebline** [comment] 2022-05-12 16:24
Insted of using CSS, there's an attribute `animate` in React

http://jsfiddle.net/pLh05ypL/1/
https://stackoverflow.com/questions/29205294/how-to-achieve-blinking-effect-in-svg

**Comment by Saschl** [comment] 2022-05-12 16:30
Do you guys have Menu Animations disabled? 
![image](https://user-images.githubusercontent.com/19493808/168123830-5a1dd215-3b1e-4c8d-a413-09240afab99b.png)

Disabling this prevents the animations from running. For all the other React displays we force this option on, but it's possible that the lower ecam doesn't as it's still a hybrid between vanilla and react. If so, as a workaround we could try to enable it there as well (until the port is fully finished).

See https://github.com/flybywiresim/a32nx/blob/master/src/instruments/src/Common/displayUnit.tsx#L51-L55 for reference

**Comment by juliansebline** [comment] 2022-05-12 17:11
Indeed, that was the problem. Thanks a lot. 

Now I'm trying to find in which pages I have to copy this line to cover them all.

**Comment by juliansebline** [comment] 2022-05-16 10:12
related to #5576

**Comment by tracernz** [comment] 2022-05-26 05:00
Duplicate of #5576.

**Closed by tracernz** 2022-05-26 05:00 UTC
Labels: Bug, ECAM, Engines
