### ISSUE TITLE
[BUG] Pilot-side PFD was frozen for a long time

### ISSUE THREAD

**Issue by Rameyuk** [flybywiresim/a32nx#3719] opened 2021-02-25 22:34 UTC
**Mod Version**

A32NX Experimental Custom FBW

**Describe the bug**

I had something weird happening on my flight last night with the Custom FBW version. It's mainly on the Pilot side PFD. For some reason it was frozen. The airspeed wasn't changing the was it's suppose to and the altitude stays. When I look at the co-pilot side it's makes much more sense because it's displaying the correct data and it's still moving. So I thought of turning off the Pilot PFD, and I waited.. and waited.... and waited... and the screen never goes past the self-test for a long while. So I had to make a decision and switch the pilot flying to copilot, and switches my TCA Quadrant and sidestick the other way for a right-hand flying. After a few more minutes, I look at the Pilot PFD, it's still on self-test.. After a while, I look at it again and it's now working. So I switched back my camera and TCA Quadrant and sidestick back to Pilot flying and I end up landed just fine. My issue is what happened in the first place? Attached is the video evidence.

**To Reproduce**

1. Fly as usual and starting approach.
2. PFD Suddenly frozen, the airspeed and altitude doesn't change to reflect the actual behaviour.
3. Check with Copilot-side PFD, and it's showing a different data that reflects the actual behaviour and it's not frozen.
4. Turn down the brightness knob to reset the Pilot-side PFD. And turn it back on to go to self-test mode.
5. The Self-test mode went far over the 40 second waiting time.
6. The PFD is unusable until short final.

**Expected behavior**

PFD should keep refreshing with real time data of the aircraft behaviour at all times.

**Actual behavior**

Pilot-side PFD is frozen. It doesn't move the airspeed and altitude changes. When I turn off the display, and turn it on. It stays frozen in Self-Test mode for a long while.

**References**

https://youtu.be/IymFrB-xqc0?t=9083

**Additional context**

Was this working before/when did the issue start occurring?
- This is the first time I experience this bug. And I haven't flown enough to see if this is a persistent or consistent bug or if it's just a single incident.

Is this a problem in the vanilla unmodded game?
- I haven't checked.

Discord username (if different from GitHub): Neo 4316

**Comment by aviationenthusiast** [comment] 2021-02-25 23:06
I literally just had this issue exactly as you described it. 
{
  "built": "2021-02-24T23:55:45+00:00",
  "ref": "master",
  "sha": "525dc7c817da20b8c16dd0d674649c2cb12de511",
  "actor": "wpine215",
  "event_name": "manual"
}

**Comment by mikecbr** [comment] 2021-02-25 23:49
me too , it just happened to me during descent.

**Comment by marcman86** [comment] 2021-02-26 01:17
Thank you for reporting.

As a reminder: The >Experimental< Custom FBW branch is not stable. Expect bugs. No support is given.

Please read:
https://github.com/flybywiresim/a32nx/blob/master/README.md

**Comment by Benjozork** [comment] 2021-02-26 01:37
![image](https://user-images.githubusercontent.com/4503241/109242510-3e19f900-77a9-11eb-928f-e35757d1b345.png)

**Comment by mikecbr** [comment] 2021-02-26 01:56
@marcman86   @Benjozork   i though you didn't support via discord,  not github,  which is meant to open bug reports......

**Comment by Benjozork** [comment] 2021-02-26 01:57
@mikecbr yes this is why I pointed out that the lack of support is only on Discord...

**Comment by mikecbr** [comment] 2021-02-26 01:58
@Benjozork  right , thanks Holland

**Comment by marcman86** [comment] 2021-02-26 02:06
Sorry. I misunderstand that. Just wanted to say bugs can happen in the unstable experimental branches.

**Comment by AdamNZ** [comment] 2021-02-26 02:09
I got that in the last **DEV** update. I've since updated to today's latest and am in the middle of a test flight.

**Comment by mikecbr** [comment] 2021-02-26 02:09
@marcman86  I think most of us are aware of it , the thing is that we have to report it , so fbw team can fix it , if no one report it it won't be fix....

**Comment by luiscurtolo** [comment] 2021-02-26 03:58
I had this problem yesterday and today, with the DEVELOPMENT version. 
My dev was updated today and the problem happened again. Only PILOT side. 

It starts when the STAR is about to begin. 
Looks to be connected to that bug that makes Manage mode die when starting a STAR procedure. 

The interesting thing is that there's no USR on flight-plan MCDU page, it supposed to go smooth. With USR is common to start a crazy turn. 

But now it's a crazy turn AND THE PILOT PFD freezes. copilot works fine. 

Very wierd.

**Comment by luiscurtolo** [comment] 2021-02-26 03:59
> I got that in the last **DEV** update. I've since updated to today's latest and am in the middle of a test flight.

How did it go?

**Comment by jcabanascachi** [comment] 2021-02-26 04:34
I downloaded the latest dev version like 2 hours ago and this problem happened to me too. It froze during the STAR and capturing the localizer. After a while it unfroze when gear down if I remember correctly.

**Comment by AdamNZ** [comment] 2021-02-26 05:27
I finished my test flight without the PFD locking up. This was with the latest/current DEV version:
{
  "built": "2021-02-25T21:43:01+00:00",
  "ref": "master",
  "sha": "472cf527726e63d24e95608b6ac66d3430ffaacb",
  "actor": "Benjozork",
  "event_name": "manual"
}

**However** ... I'll need to search out the bug report for the aircraft turning left at the first STAR point, as the a/p made a mess of following the route from there onwards. Had to fly it manually until I intercepted LOC and G/S.

**Comment by aguther** [comment] 2021-02-26 06:47
I think the probability is very high that this issue is not related to the custom fbw system and as already reported might happen on the development version as well.

**Comment by luiscurtolo** [comment] 2021-02-26 14:50
> **Mod Version**
> 
> A32NX Experimental Custom FBW
> 
> **Describe the bug**
> 
> I had something weird happening on my flight last night with the Custom FBW version. It's mainly on the Pilot side PFD. For some reason it was frozen. The airspeed wasn't changing the was it's suppose to and the altitude stays. When I look at the co-pilot side it's makes much more sense because it's displaying the correct data and it's still moving. So I thought of turning off the Pilot PFD, and I waited.. and waited.... and waited... and the screen never goes past the self-test for a long while. So I had to make a decision and switch the pilot flying to copilot, and switches my TCA Quadrant and sidestick the other way for a right-hand flying. After a few more minutes, I look at the Pilot PFD, it's still on self-test.. After a while, I look at it again and it's now working. So I switched back my camera and TCA Quadrant and sidestick back to Pilot flying and I end up landed just fine. My issue is what happened in the first place? Attached is the video evidence.
> 
> **To Reproduce**
> 
> 1. Fly as usual and starting approach.
> 2. PFD Suddenly frozen, the airspeed and altitude doesn't change to reflect the actual behaviour.
> 3. Check with Copilot-side PFD, and it's showing a different data that reflects the actual behaviour and it's not frozen.
> 4. Turn down the brightness knob to reset the Pilot-side PFD. And turn it back on to go to self-test mode.
> 5. The Self-test mode went far over the 40 second waiting time.
> 6. The PFD is unusable until short final.
> 
> **Expected behavior**
> 
> PFD should keep refreshing with real time data of the aircraft behaviour at all times.
> 
> **Actual behavior**
> 
> Pilot-side PFD is frozen. It doesn't move the airspeed and altitude changes. When I turn off the display, and turn it on. It stays frozen in Self-Test mode for a long while.
> 
> **References**
> 
> https://youtu.be/IymFrB-xqc0?t=9083
> 
> **Additional context**
> 
> Was this working before/when did the issue start occurring?
> 
> * This is the first time I experience this bug. And I haven't flown enough to see if this is a persistent or consistent bug or if it's just a single incident.
> 
> Is this a problem in the vanilla unmodded game?
> 
> * I haven't checked.
> 
> Discord username (if different from GitHub): Neo 4316

hey, could you please edit the mod version and add the DEV MOD 472cf52 also? 
Think might help others to quickly see that its affecting other versions. 

thanks

**Comment by lionhell** [comment] 2021-02-26 21:18
The problem regards also DEV version... 
Takeoff and climb no prob.
Cruise no prob.
Descent (at what moment ?) Left PFD speed frozen.
On final (or and of initial app): Left PFD works again.

Occured since 2 days with dev version.
This evening another A32NX in the approach sequence with me got the same problem.

**Comment by Valastiri** [comment] 2021-02-26 21:51
Just wanted to chime in. This and similar reports are happening across all branches now.

**Comment by luiscurtolo** [comment] 2021-02-26 23:19
> Just wanted to chime in. This and similar reports are happening across all branches now.

Even in Stable 5.3 ?

**Comment by frankkopp** [comment] 2021-02-27 00:44
Here a video of the issue - pilot PFD hangs, co-pilot's PFD working 
https://user-images.githubusercontent.com/16833201/109369532-eb216e00-789c-11eb-8686-04831616267a.mp4

started working again when I did gear down for landing

{
  "built": "2021-02-26T17:30:56+00:00",
  "ref": "fbw",
  "sha": "991d5f1b8a31b815f255b645ebce75137b9c8761",
  "actor": "aguther",
  "event_name": "manual"
}

**Comment by luiscurtolo** [comment] 2021-02-27 04:36
Just tried the latest **dev. version F08ce2b** and the issue persists. 
When the gear goes down, the pilot PFD comes back to normal. 
No problem with the ALT indicator, only everything else until Gear is down hahaha 

[off topic] i'm getting this wierd thing with the waypoints, like they are doubled.. starts after the STAR stars (and after a bug that makes me bank and dive). Could someone link me to a proper topic, if there's one. 

![1](https://user-images.githubusercontent.com/79680798/109375423-6da92e00-789b-11eb-8f0b-9ec9bd6ccb0d.png)

**Comment by Benjozork** [comment] 2021-02-27 04:38
Workaround for now is to turn off the PFD and turn it back on again.

**Comment by luiscurtolo** [comment] 2021-02-27 04:42
> Workaround for now is to turn off the PFD and turn it back on again.

I've been trying that but - for me - it doesnt work. 
it comes back for a couple seconds then freezes again. 

workaround acctually is goinig to copilots till main gear is down, or just staying there hehe

**Comment by Benjozork** [comment] 2021-02-27 04:43
hm. strange - worked for others.

this should be fixed relatively soon - looks a problem with the avionics update scheduler

**Comment by sidnov** [comment] 2021-02-27 04:56
Just to confirm, what glass cockpit refresh rate setting are you guys using?

**Comment by A320PHX** [comment] 2021-02-27 05:54
> Just to confirm, what glass cockpit refresh rate setting are you guys using?

Having the same issue here. My glass cockpit setting is on the highest refresh rate.

What worked for me is moving the camera around like I was sitting on the FO side. Returned to pilot side and all was well.

**Comment by ErikNL80** [comment] 2021-02-27 12:20
I am experiencing the same with 'Medium' refresh rate... Turning the display off and on does not work, PFD seems to be stuck at the selftest. On final PFD got working again. Guess it might has to do with FPS; in dense areas PFD tends to freeze more than sparse areas.

**Comment by airfirefighter** [comment] 2021-02-27 12:40
i had the same problem yesterday in dev  mod.And everything start working again after i lowered the gear down....

**Comment by Flyingtrader06** [comment] 2021-02-27 15:55
Experiencing the same with low refresh rate. PFD stuck at self test phase.

**Comment by mak60062** [comment] 2021-02-27 16:14
Occurred for me last night on experimental version with medium refresh rate. PFD unfroze on final.

**Comment by marcman86** [comment] 2021-02-27 16:35
While testing #3504: Got a PFD freeze (unrelated to PR)

After crossing star or decel (dont know exactly) PFD ge stucked. Think it starts when switching to APP phase.

Turned off PFD and back on again: Stuck on test screen
Changed Refreshrate medium - high - medium: nothing

With gears down it gets unstuck, get stuck again with gears up

stuck and unstuck with gear up or down, this is repeatable

**Comment by FrankDevin-dev** [comment] 2021-02-27 17:55
Same here just a few minutes ago

{
  "built": "2021-02-26T17:30:56+00:00",
  "ref": "fbw",
  "sha": "991d5f1b8a31b815f255b645ebce75137b9c8761",
  "actor": "aguther",
  "event_name": "manual"
}

To me it happened directlyafter I inserted the temp arrival data STAR for 25 at EGNT in FMGC
Attitude is stuck after this happens,  AP1 is also stuck.
Switched to AP2 and Co-Pilot stabilised the bird.

**Comment by sidnov** [comment] 2021-02-27 18:02
@Benjozork This is reproducible. Continuation from Discord: 

Completed 3 flights, each about an hour long
1 flight with dev version downloaded at 0900z 27/02/2021 (confirmed the bug, along with desynced PFD refresh rates, check https://discord.com/channels/738864299392630914/754130199804772372/815222201972162561)

2 flights with the PR #3737 (no issues with PFD)

Glass Cockpit Refresh Rate was set to high in sim settings

**Comment by XSJoJo** [comment] 2021-02-27 20:54
Does anybody who is experiencing this issue have https://github.com/dga711/msfs-webui-devkit downloaded and enabled for the PFD? If so, can somebody check for any errors in the console that may be visible when the PFD is frozen?

**Comment by Kimbyeoungjang** [comment] 2021-02-27 23:25
> Does anybody who is experiencing this issue have https://github.com/dga711/msfs-webui-devkit downloaded and enabled for the PFD? If so, can somebody check for any errors in the console that may be visible when the PFD is frozen?

I can help you. Testing start now

**Comment by marcman86** [comment] 2021-02-28 00:28
![117](https://user-images.githubusercontent.com/78707844/109404217-29359500-7964-11eb-95c1-79a79d774591.png)
![118](https://user-images.githubusercontent.com/78707844/109404222-2f2b7600-7964-11eb-9bf6-c4a70da9d879.png)

PFD logs when freezing

**Comment by luiscurtolo** [comment] 2021-02-28 00:51
This maybe obvious but Stable 5.3 was ok.

**Comment by FlyByWire128** [comment] 2021-02-28 17:47
For me, the pilot-side AI, speed tape, and VSI needle are frozen, but the altimeter tape is still moving accurately (latest Dev build from this morning).  Copilot-side works normally.

**Comment by jmihalich** [comment] 2021-02-28 17:52
Looks like it's fixed.  just waiting for testing and pull request.

**Comment by luiscurtolo** [comment] 2021-02-28 18:02
> Looks like it's fixed. just waiting for testing and pull request.

Could you specify which version u will be testing?

**Comment by marcman86** [comment] 2021-02-28 18:09
https://github.com/flybywiresim/a32nx/pull/3748

**Closed** 2021-02-28 19:06 UTC
Labels: Bug, PFD, Reproduced
