### ISSUE TITLE
[BUG] Thrustmaster TCA Quadrant Add-On AUTO BRK not working properly

### ISSUE THREAD

**Issue by DewSebastian** [flybywiresim/a32nx#3003] opened 2021-01-12 04:10 UTC
**Mod Version**
Latest Dev Version

**Describe the bug**
Auto BRK Switch Button not work

**To Reproduce**
1.Switch Button
2.The corresponding function is not implemented

**Expected behavior**
Switch Button change brakes level

**Actual behavior**
Only change to HI working

Is this a problem in the vanilla unmodded game?
YES , vanilla it is working

**Comment by Saschl** [comment] 2021-01-12 07:22
Same as #2852

**Comment by marcsoler** [comment] 2021-01-12 09:53
Since it's hard to get hands on the TCA Quadrant Add-On, maybe you could test this pull-request and give it a review?

#2854

**Comment by Saschl** [comment] 2021-01-12 12:18
It’s not absolutely required to have the addons. One can bind the autobrake keys to e.g a keyboard as well for testing.

**Comment by marcsoler** [comment] 2021-01-12 13:24
> It’s not absolutely required to have the addons. One can bind the autobrake keys to e.g a keyboard as well for testing.

Not so sure. I own an TCA Quadrant (without the Add-on) and I had similar issues with the engine mode selector. (Wasn't able to reset the position to NORM (middle). Only some firmware and a32nx updates later it worked... Keyboard binding wasn't a problem though.

**Comment by andrejetcat** [comment] 2021-01-12 18:36
...but the mousewheel issue still exist... sadly :(

**Comment by MisterChocker** [comment] 2021-01-13 11:13
Duplicate of #2852

**Closed by MisterChocker** 2021-01-13 11:13 UTC
Labels: Bug

**Comment by MisterChocker** [comment] 2021-01-13 11:16
> ...but the mousewheel issue still exist... sadly :(

#1712

**Comment by pilotsteve88** [comment] 2021-01-29 01:02
Can I also add that the LANDING GEAR lever doesn't work either on the TCA Quadrant ADD-ON, whether the lever on the hardware is in the up or down position there is no change in the flightdeck. It does work on the 'Vanilla' version of the A320.

**Comment by Tinpanva** [comment] 2021-02-09 22:08
my TCA (with add-ons) came in today and I can confirm only the "Hi" is working

**Comment by LukasGNN** [comment] 2021-03-02 07:41
Can confirm this. 
Is it resolved since the ticket is closed?
