### ISSUE TITLE
[BUG] IRS does not work after it aligns

### ISSUE THREAD

**Issue by majd3994** [flybywiresim/a32nx#2823] opened 2020-12-31 07:49 UTC
**Mod Version**

0.5.1

**Describe the bug**

 after the IRS align normally and flight plan inserted, the ND works for minutes then it turns red as IRS didnt align, flight path and plan is depicted on the ND, but it is static and does not move as the plane move, and Cant step through the plan in the plan mode 

**To Reproduce**

1. I load the aircraft , initiate the flight plan using simb integration
2. switch the knobs to align then align on ref from the INIT page 
3.

**Expected behavior**

to continue in align mode

**Actual behavior**

it stops following the position 

**References**

![image](https://user-images.githubusercontent.com/76506657/103400346-c023d380-4b12-11eb-8333-a9e314309c15.png)

**Additional context**

Was this working before/when did the issue start occurring?
today , it was working fine before 

Is this a problem in the vanilla unmodded game?
 no 

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by rollonit** [comment] 2020-12-31 12:56
I had the same issue, and it seems to have been caused by a conflict with the Working Title G1000 or the GX mods. They've addressed this their latest beta release, so try either updating or removing those mods.

**Comment by MisterChocker** [comment] 2020-12-31 14:11
Please check with the above stated fix by @rollonit and report back.

**Comment by majd3994** [comment] 2020-12-31 20:58
It worked after removing G1000 mod . Thankss

**Comment by MisterChocker** [comment] 2020-12-31 21:10
closing since issue solved

**Closed by MisterChocker** 2020-12-31 21:10 UTC
Labels: Bug, Waiting For Response
