### ISSUE TITLE
Add full GSX support

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#7473] opened 2022-09-05 09:10 UTC
### Aircraft Version

Experimental

### Description

Hello,

Full GSX support should be added. There are doors and cargo doors that are not active when GSW is running.
The rear cargo door and some straight doors for the catering service.

thanks

**Comment by 2hwk** [comment] 2022-09-05 09:31
Almost a Duplicate of https://github.com/flybywiresim/a32nx/issues/7473 so closing, GSX compatability will be tracked there instead.

**Closed by 2hwk** 2022-09-05 09:31 UTC
Labels: Request
