### ISSUE TITLE
pfd display 

### ISSUE THREAD

**Issue by youngryan7** [flybywiresim/a32nx#5397] opened 2021-07-25 09:43 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-24T20:18:52+00:00",
  "ref": "master",
  "sha": "05a0bbda844850568c82ae6dab6217e509a46aa2",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

co pilot pfd linked to captain pfd

### Expected behavior

should not be linked when i turn down co pilot pfd off
captain display should stay on remain the same

### Steps to reproduce

turn off co pilot pdf display
you will see captains display turn off 

### References (optional)

![2021-07-25](https://user-images.githubusercontent.com/59422760/126894792-67af0c20-b50a-46eb-bb8f-562d9ff5dad5.png)

**Comment by youngryan7** [comment] 2021-07-25 09:44
i usually turn off co pilot displays to save frames :)

**Comment by Benjozork** [comment] 2021-07-25 09:45
Duplicate of #5390 

> i usually turn off co pilot displays to save frames :)

Also, you won't need to do this very soon 😉 stay tuned

**Comment by tracernz** [comment] 2021-07-25 09:45
Already reported in #5390. Keep an eye on that one for a fix soon.

**Closed by Benjozork** 2021-07-25 09:45 UTC
Labels: Bug

**Comment by bouveng** [comment] 2021-07-26 15:36
This is fixed in development branch.
