### ISSUE TITLE
[BUG] Performance issues Long FLIGHT PLAN

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2075] opened 2020-11-23 23:34 UTC
**Mod Version**
Latest master Branch 

**Describe the bug**
Hey there , good evening , when im loading a short flight , LEMD/LEMG 311 NM I have to load very few points , wich my fps (performance) is pretty good , 35 fps with everything in ultra , and i am not having any issues during the flight.
The problem comes when I load a very long FLIGHT PLAN  LEMD/UUDD  1948 NM. 
Once the route is loaded , i dont know if it happens because the plane in the background has so much load (points) ,  or what , but the performance is very very bad , having only 15 fps even in the ground (stand) not flying.
If i go back and delete the route in INIT , my fps will boost instantly.
I think is a very annoying performance issue.
And I cant fly at all with this problem....

I tested so many times , preparing the airplane , for short , and long distances flights and the problem always appear when FCMU has to load so many points. 

**To Reproduce**
LEMD/UUDD    ROUTE     RBO1N RBO UN870 SEGRE UN871 GAMSA N871 BEPAS T709 KOTEK M866 ETUBO M863 MNS T52 MOSON A104 FK FK1D

**Expected behavior**

The same performance as When i load short flight LEMD/LEMG    ROUTE:  VTB1T VTB UN10 CRISA UN864 VULPE VU1DCJ

**Actual behavior**

Performance drops significantly When i load a very long flight plan.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes was working , Specially from the stable release and from the Master Branch of a week ago 

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by mikecbr** [comment] 2020-11-24 12:46
Any news or tested about this ? it is really imposible to make long flights.....

**Comment by Watsi01** [comment] 2020-11-24 13:15
For me it was nearly impossible so far. I can do flights about 3h+, but during the last quarter of the flighttime, my fps gets worse and worse - resulting in having a CTD eventually. My mainthread goes up (not having this issue with shorter flights) and my GPU has no work to do anymore.

But I don't think it's a FBW problem. I guess there's a memory leak problem > Asobo.

**Comment by mikecbr** [comment] 2020-11-24 13:27
> For me it was nearly impossible so far. I can do flights about 3h+, but during the last quarter of the flighttime, my fps gets worse and worse - resulting in having a CTD eventually. My mainthread goes up (not having this issue with shorter flights) and my GPU has no work to do anymore.
> 
> But I don't think it's a FBW problem. I guess there's a memory leak problem > Asobo.
> 
> EDIT: I've done several driver updates (chipset, graphic, etc.) and a BIOS update recently. I don't know if the problem still exists.


Yep , that happened to me yesterday (CTD) The first CTD that i ever had in fs2020. Otherwise this wasnt happening to me in the master branch from a week ago... it is so trange. I did Madrid LEMD TO KMIA  Miami almos 9 hour flight a week ago with the branch over those times and it was going pretty good , so i dont know why its fs2020 faulth if it never change since then but FBW did change....

**Comment by Watsi01** [comment] 2020-11-24 14:16
@mikecbr I had the same issue with other planes. So I'm not sure if it is FBW related (at least on my side).

**Comment by mikecbr** [comment] 2020-11-24 15:19
@Watsi01  Well , it happens to me when i load the flight plan in the stand...... As soon as i delete it in the same stand , INIT page and i load another shorter , the problem dissapears...

**Comment by MisterChocker** [comment] 2020-11-24 16:02
I know why, it's my bad xD

**Comment by mikecbr** [comment] 2020-11-24 16:30
@MisterChocker  Thanks god Im happy again 👍  Thank you so much for listening and read this topic

**Comment by MisterChocker** [comment] 2020-11-24 17:48
after looking into this, this might have a greater scope and caused by something else.
Do you experience the bad performance more permanently or is it only temporary after some inputs to mcdu or fcu?

**Comment by mikecbr** [comment] 2020-11-24 17:56
@MisterChocker Performance is really bad only after uploading long flight plans in the mcdu (flight plans longer than 600NM), otherwise very good performance when I upload short flight plans (50 minutes flight time)

**Comment by lukecologne** [comment] 2020-11-24 17:57
When you did the flights where performance decreased over time, on which traffic setting were you? i.e Live online traffic, or offline traffic

**Comment by mikecbr** [comment] 2020-11-24 18:02
@lukecologne No, it does not decrease over time, the performance was good until I set long flight plans in MCDU. In the master branch of a week ago I went from Madrid (LEMD) to Miami (KMIA) and everything went fine and performance was good overall. I have been experiencing this problem since lasts master branch releases

**Comment by lukecologne** [comment] 2020-11-24 18:04
> 
> 
> For me it was nearly impossible so far. I can do flights about 3h+, but during the last quarter of the flighttime, my fps gets worse and worse - resulting in having a CTD eventually. My mainthread goes up (not having this issue with shorter flights) and my GPU has no work to do anymore.
> 
> But I don't think it's a FBW problem. I guess there's a memory leak problem > Asobo.
> 
> EDIT: I've done several driver updates (chipset, graphic, etc.) and a BIOS update recently. I don't know if the problem still exists.

I'm talking about this.

**Comment by MisterChocker** [comment] 2020-11-24 18:08
@lukecologne I thought this may be a result of the constraint searching the flight plan, but it only does this on changes and only once. It caches the result. But seems not to be related to this.

**Comment by lukecologne** [comment] 2020-11-24 18:11
I'm asking because apparently there was a bug with offline traffic, where it doesn't get deleted when out of range, causing performance issue over time. This should be fixed in the newest MSFS version.

**Comment by mikecbr** [comment] 2020-11-24 18:13
@lukecologne  Nope , performance is the same from take off to landing.....
It is so trange , as i was fliying with the latest branch of a week ago an everything was so smooth even from loading 9h flight plans  and from take off to landing, until one of the latest realeses thats something is not going good.... @MisterChocker

**Comment by lukecologne** [comment] 2020-11-24 18:15
Again, I'm talking to @Watsi01, since they were the one talking about degradation over time.

**Comment by mikecbr** [comment] 2020-11-24 18:47
So am i the only one who is having this problem ? nobody else ? @MisterChocker

**Comment by MisterChocker** [comment] 2020-11-24 19:02
Not sure, so far this seems to be caused by something different then I thought.

**Comment by Watsi01** [comment] 2020-11-24 19:25
@lukecologne I can remember I made some long hauls right after MSFS came out with the vanilla A320. This worked back then. But I also tried the Asobo Japan trip (when Japan came out) and that was a mess after 1 hour - it was with the King Air I believe. My last CTD with the A32NX was from Casablanca to Basel during descent (2 weeks ago I guess). Presaged by lower and lower fps before. So maybe it's the mentioned Asobo bug. I will have a look.

**Comment by Abril1985** [comment] 2020-11-25 00:49
Hey there, I am also experiencing this performance bug... I had the stable release since yesterday afternoon and I wanted to update to the latest master branch.
In the stable, the performance was always great,  even when I make very long flights, with the latest master branch, loaded a short FLIGHT PLAN very good performance, Load a long-haul flight, very bad performance in the moment I insert the route  (When I  LOADED it in the MCDU), strange...
Hope it gets short out soon...

**Comment by mikecbr** [comment] 2020-11-25 01:50
hello from Greece
 same problem here 
Please fix it

**Comment by Hundredabove** [comment] 2020-11-25 01:53
Hello from Greece.
Same problem here
Please fix it

**Comment by Snapmatics** [comment] 2020-11-25 01:59
> Hello from Greece.
> Same problem here
> Please fix it

Σιγά-σιγά φίλε μου! :)

**Comment by Hundredabove** [comment] 2020-11-25 02:07
@Snapmatics    Είσαι Έλληνας

**Comment by Snapmatics** [comment] 2020-11-25 02:13
> @Snapmatics Είσαι Έλληνας

Yup :)

**Comment by Benjozork** [comment] 2020-11-25 02:25
Hello everyone,

We ask everyone to be patient and stick to the stable version if the performance issues are too critical. We do everything possible to avoid those regressions but things will be fixed when we have time and when it can be fixed properly.

**Comment by Watsi01** [comment] 2020-11-25 10:20
No impatience here at all.  Everything is fine. We just want to give as much information as possible. It's WIP after all, and it will be for a some time. 😃

**Comment by javiiberia** [comment] 2020-11-25 13:40
Same problem here, long flight plans performance very bad

**Comment by 2hwk** [comment] 2021-07-04 17:06
Closing as this is being addressed by cFPM + July 27th Sim Update 5 and this is an old issue which has many duplicates.

**Closed by 2hwk** 2021-07-04 17:06 UTC
Labels: Bug
