### ISSUE TITLE
[REQUEST] delete,add,edit STARs waypoints

### ISSUE THREAD

**Issue by jsid87** [flybywiresim/a32nx#1848] opened 2020-11-10 14:35 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**
To be able to delete,add STAR waypoints in MCDU after selecting approach.

**References**

**Additional context**
I'm using Navigraph beta for navdata. Sometimes when I select approach there are missing or wrong waypoints in MCDU. So I would like to be able to edit them. 

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-11-10 15:05
Duplicate of #1388

**Closed by Benjozork** 2020-11-10 15:05 UTC
Labels: Enhancement
