### ISSUE TITLE
Gravity gear extension

### ISSUE THREAD

**Issue by kilocharlie1** [flybywiresim/a32nx#7070] opened 2022-04-16 23:01 UTC
### Aircraft Version

Stable

### Description

It would be cool if we could use the gravity gear extension and perform a manual gear drop, just to add a little realism to hydraulic emergencies :)

You pull the gravity gear extension handle up, then you rotate it three times clockwise
![20220416185242_1](https://user-images.githubusercontent.com/88682168/163693669-4cf6d565-d65f-4cd2-b65c-1f7914b64a2e.jpg)
![gear extension](https://user-images.githubusercontent.com/88682168/163693697-300f4de6-c6ab-4fef-bd13-bfe8ffce537e.jpg)
![gearextension](https://user-images.githubusercontent.com/88682168/163693759-ae0c3d05-e68c-4541-bb2d-9a74e2332338.jpg)

### Discord Username (optional)

GeeMeeKee#9761

**Comment by Benjozork** [comment] 2022-04-16 23:50
Duplicate of #1452

**Closed by Benjozork** 2022-04-16 23:50 UTC
Labels: Request
