### ISSUE TITLE
Fuel Quantity and Fuelflow data not linked since 7.0 launch

### ISSUE THREAD

**Issue by Dreadnought1906** [flybywiresim/a32nx#5876] opened 2021-09-21 18:49 UTC
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-09-18T00:34:38+00:00",
  "ref": "v0.7.0",
  "sha": "e8ea73b3648d48437ca5df55e280a945fd11dab6",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

I use the popular Little Navmap application (latest version 2.6.16) for flight planning and tracking. 

Since version 7.0 (both stable and development versions), fuel quantity and fuel flow data is not being sent to Little Navmap.  All other aircraft types work fine.  

### Expected behavior

fuel quantity and fuel flow data should be available

### Steps to reproduce

1. Start any flight with the FBW A320NX, while Little Navmap is running.  Stay on runway or fly, makes no difference as long as engines are running.
2. Fuel flow in gph and pph should appear in the Progress tab.  It reads zero. 
3. Fuel quantity and Fuel Consumed quantities appear in the Current Performance tab.  Both read zero.

Works fine for all other aircraft, and worked fine prior to version 7.0.

**Comment by tracernz** [comment] 2021-09-22 05:05
This is not something we can fix as we can't write to the simulator's fuel variables, and we use a custom engine and fuel system model.

Duplicate of https://github.com/flybywiresim/a32nx/issues/4703

**Closed by tracernz** 2021-09-22 05:05 UTC
Labels: Bug
