### ISSUE TITLE
Aircraft Initially Banks In Wrong Direction On AP When Following FP

### ISSUE THREAD

**Issue by kgaviation** [flybywiresim/a32nx#4161] opened 2021-03-27 22:17 UTC
**Mod Version**

Custom/Experimental

**Describe the bug**

With the aircraft set on AP and following the FP/route on NAV mode, the aircraft will initially bank in the wrong direction for a few seconds upon reaching a waypoint. It will then correct itself by banking in the opposite/correct direction and continue following the FP.

**To Reproduce**

1. Create route/FP using the worldmap feature in the main menu
2. In the cockpit, engage NAV mode on the panel and FMA
3. Takeoff and set the AP to follow the FP

**Expected behavior**

The aircraft should only bank in the correct/intended direction. If the FP has a right turn, the aircraft should only bank right to follow the FP. It should not initially bank to the left (opposite direction) and then counter bank to correct itself.

**Actual behavior**

After takeoff and during climb to cruising altitude, the aircraft was set to NAV mode in order to follow the FP. Upon reaching every waypoint, the aircraft always initially banks in the wrong direction for a few seconds. It will then correct itself by banking in the opposite direction to correctly continue following the FP. This also happens when the FD is centered correctly.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes. It started occurring after flying and installing the new custom/experimental version.

Is this a problem in the vanilla unmodded game?
Not sure since I don't fly the default/vanilla A320.

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2021-03-27 22:19
Duplicate of #4110

**Closed by Benjozork** 2021-03-27 22:19 UTC
Labels: Bug

**Comment by kgaviation** [comment] 2021-03-27 22:22
> Duplicate of #4110

No, this is a different issue, although somewhat similar. That was using the stable and dev. version. The aircraft only banked hard to the left or right when first engaging AP.

I discovered this issue in the new custom/experimental version today. The aircraft flies smoothly and level when engaging the AP, not like 4110. It's only when the aircraft reaches a waypoint that it always banks the wrong direction first and then banks the opposite direction to correct itself. It has done this for every waypoint during my flight.
