### ISSUE TITLE
Newest Dev version crashes at CYYZ when loading.

### ISSUE THREAD

**Issue by zawadzkk** [flybywiresim/a32nx#5448] opened 2021-07-29 03:03 UTC
### Aircraft Version

Development

### Build info

```json
Dev version
```

### Describe the bug

Newest Dev version crashes at CYYZ when loading.

### Expected behavior

Load gamer

### Steps to reproduce

Start the flight

### Discord Username (optional)

SUB750T

**Comment by NUTTTTTTTT** [comment] 2021-07-29 03:07
Please see https://docs.flybywiresim.com/start/reported-issues/#ctd-resolution
For the time being we don't have much more to go on the sim should hopefully settle down too from experience and other reports.

**Comment by zawadzkk** [comment] 2021-07-29 03:23
Okay updating FSUIPC7 newest beta version released on 28 July 2022 solved the crash problem.

**Comment by zawadzkk** [comment] 2021-07-29 03:25
Updating FSUIPC7 newest beta version released on 28 July 2021 solved the crash problem.

**Comment by zawadzkk** [comment] 2021-07-29 03:30
![image](https://user-images.githubusercontent.com/34450384/127427153-63288269-f7a5-49c8-a4c3-b85452266214.png)

**Comment by aguther** [comment] 2021-07-29 04:54
@zawadzkk If the issue is resolved please close the issue then.

**Comment by zawadzkk** [comment] 2021-07-29 04:56
Nah crash is back again, I noticed no pushback and other vehicles when with FBW, other planes are ok. something wrong in your programing.. Ticket to be open.

**Comment by Benjozork** [comment] 2021-07-29 04:57
> something wrong in your programing

Can you please explain the evidence you have for this ?

**Comment by zawadzkk** [comment] 2021-07-29 04:59
I loaded 787 on CYYZ gate 89 no issue, I load your dev plane and it crash instantly

**Comment by Benjozork** [comment] 2021-07-29 05:00
That does not prove that "something is wrong with your programming".

There are many issues with Sim Update 5 that affect different planes differently.

**Comment by Benjozork** [comment] 2021-07-29 05:00
I would advise waiting for further information from MS/Asobo.

**Comment by zawadzkk** [comment] 2021-07-29 05:00
when the game loads with your plane there is not vehicles the airport is empty of all

**Comment by zawadzkk** [comment] 2021-07-29 05:01
yeah I not reinstalling 100 gb + lol

**Comment by zawadzkk** [comment] 2021-07-29 05:03
all plane loads you the only plane crashing the game, I  have only you in community...  no addsons

**Comment by Benjozork** [comment] 2021-07-29 05:03
Nobody asked that you reinstall the game.

> all plane loads you the only plane crashing the game, I have only you in community... no addsons

Please read again: **There are many issues with Sim Update 5 that affect different planes differently.** We do not have enough information right now to look into anything, as MSFS does not have crash logs.

**Comment by zawadzkk** [comment] 2021-07-29 05:04
roger!

**Comment by 2hwk** [comment] 2021-07-29 05:04
Tested to be working on old build 1.17.3, no CTD. ✔️ SU5 issue. 

Try to do a clean install, including removing the highlighted files.

https://cdn.discordapp.com/attachments/838062729398976522/869736690695172156/unknown.png

https://docs.flybywiresim.com/start/installation/#clean-install-steps

**Comment by zawadzkk** [comment] 2021-07-29 05:05
this does nothing you introduce something in your code that makes this issue, rollback and we be ok

**Closed** 2021-07-29 08:49 UTC
Labels: Bug
