### ISSUE TITLE
[BUG] No electrical power with Battery / External switches ON (after MSFS Patch#2)

### ISSUE THREAD

**Issue by stevex77** [flybywiresim/a32nx#718] opened 2020-09-16 19:40 UTC
**Mod Version**

master / newest MSFS build

**Describe the bug**

In C&D state sometimes (ie. not every time) these Battery / External switches don't provide electricity to the bus.

**To Reproduce**

1. Spawn on a gate in C&D state
2. Turn on Battery / External power switches
3. Check systems that should be powered

**Expected behavior**

When Battery / External power switches are ON, there shold be electrical power.

**Actual behavior**

Sometimes the aircraft remain in C&D state.

**References**

No ref.

**Additional context**

It's ASOSBO's bug, happens to me without a32nx too.
Hard to reproduce, seems to be random behavior.
Not sure it's safely fixable through a32nx overrides.
Restarting the flight (respawn) fixes this.
Before Patch#2 this never happened.

Discord username (if different from GitHub):
n/a

**Comment by Jabafcb** [comment] 2020-09-16 21:10
I'm having the same issue. Although this happens every time i load the aircraft since the new update.

**Comment by jacojazz** [comment] 2020-09-16 21:15
Same issue, every time I load C/D at a gate.

**Comment by RiseofRice** [comment] 2020-09-16 21:18
same issue here with or without a32nx

**Comment by UncleClapton** [comment] 2020-09-16 21:55
Confirmed Asobo bug. We're looking into what we can do, but this one is ultimately on Asobo to fix

**Comment by nabil74** [comment] 2020-09-17 01:27
MMMM

FIRST ATTEMPT
Spawned at gate at YMML and YSSY C&D State
Bat1 on
Bat 2 on
APU Master on
APU Start on
made sure screen pdf / upper / lower ecam screens brightness turned up while waiting
everything normal.

SECOND ATTEMPT
Spawned at gate at YMML and YSSY C&D State
Bat1 on
Bat 2 on
APU Master on
APU Start on
help text says they are on but they are not lit.
APU wont start. or light up.

BUG confirmed.

**Comment by rufio1337** [comment] 2020-09-18 01:28
I'm having the same problem

**Comment by maniuraPL** [comment] 2020-09-18 07:22
Confirmed, happens to me as well

**Comment by ErikNL80** [comment] 2020-09-18 11:10
Is an Asobo issue, occurs also without the A32nx

**Comment by cradle77** [comment] 2020-09-18 15:40
There's a user who's done some investigation on the new electrical buses, not sure it's useful but I'm posting it just in case :)
https://forums.flightsimulator.com/t/1-8-13-a320-cold-dark-not-working-anymore/273564/42

**Comment by Oberstumfuher** [comment] 2020-09-18 16:27
I can send the original files before the first update, would that help?

**Comment by BreakerHUN** [comment] 2020-09-19 22:08
I have made a video of the issue. It comes to surface quite often for me.
https://www.youtube.com/watch?v=OKmUueULcwY

**Comment by Ares1378** [comment] 2020-09-21 01:24
This is a confirmed issue and has been duplicated. Problem has been escalated.

**Comment by 2hwk** [comment] 2020-09-21 10:18
Investigate if this issue is linked to this

https://np.reddit.com/r/MicrosoftFlightSim/comments/iw6mis/plane_exorcisms_or_how_i_seem_to_have_reduced_or/

**Comment by Venorcis** [comment] 2020-09-21 10:44
> Investigate if this issue is linked to this
> 
> https://np.reddit.com/r/MicrosoftFlightSim/comments/iw6mis/plane_exorcisms_or_how_i_seem_to_have_reduced_or/

According to https://forums.flightsimulator.com/t/1-8-3-0-a320-cold-dark-not-working-anymore/273564/42 this bug seems to be related more to the location of spawning than to the ground AI traffic. Moreover, buttons/electrics not working doesn't seem to be very related to the bug of random buttons being pressed by the ghost AI :P.

**Comment by AdenFlorian** [comment] 2020-09-21 18:43
might be a circuit is getting changed from another planes init code, and we dont have a ui to change the circuit.

**Comment by mc130h** [comment] 2020-09-22 04:47
> might be a circuit is getting changed from another planes init code, and we dont have a ui to change the circuit.
> will be looking into this later today, along with all the ghost bugs.

I would like to also comment, on approach the vanilla and all versions of A32NX mod a/c have gone cold/dark. I’ve once restarted via ctl+e while gliding, but power restoration was momentary and went cold/dark quickly after power was back. I’ve avoided flights in the A320 because of the electrical issues both at the gate and when on approach.

**Comment by BlackS0ull** [comment] 2020-09-23 10:20
Hello, I'm still having this annoying issue, even I've downloaded the latest branch (downloaded 2h ago). I cannot start the plane as the batteries buttons are not working. Pressing them and nothing happens. Trying to several LIVERIES from the megapack out there and with no one I was able to start the plane from COLD&DARK.

However when I've selected the default A320 NEO Livery, it seems that still I'm not able to start the plane by pushing the batteries buttons and then the APU etc. For the last STEP I've removed all the LIVERIES installed from the megapack. So I'm having only the default livery from MSFS.

Hope this helps also in solving this incredible and annoying bug/issue

**Comment by sepiroth887** [comment] 2020-09-23 17:49
@BlackS0ull is this a typo? you said even with the default livery you still are unable to get elec power? Or are you now able after removing ALL liveries and using the default one?

**Comment by sepiroth887** [comment] 2020-09-23 20:18
FWIW, workaround seems to be to disable ground traffic entirely to avoid AI collisions it seems.

**Comment by visualcookie** [comment] 2020-09-24 17:48
@AdenFlorian Did you already had the time to look into it and figure it out? Having the issue as well (at any airport/gate), but only when using the mod.

**Comment by BlackS0ull** [comment] 2020-09-24 19:09
> @BlackS0ull is this a typo? you said even with the default livery you still are unable to get elec power? Or are you now able after removing ALL liveries and using the default one?

Sorry, for not replying you earlier. Yeah mate, also with the default livery from MSFS, so with no custom liveries installed, I was not able to start the batteries. :(

**Comment by ziomik** [comment] 2020-09-26 07:13
I'm having the same issue.

**Comment by Andy1966uk** [comment] 2020-09-26 10:18
Same issue also

**Comment by messer79** [comment] 2020-09-26 10:40
Sometimes the plane shuts down just after the logbook is closed with continue button: https://youtu.be/BM-VcV0NhF8

**Comment by messer79** [comment] 2020-09-29 20:34
I have installed the latest patch 1.9.3 and I am still unable to switch the batteries on. I have to respawn several times or restart the game to make them work.

Can you confirm the issue is still present in 1.9.3 patch?

![image](https://user-images.githubusercontent.com/71893611/94611157-9e137e80-02a1-11eb-8808-d5d2d427f8c0.png)
![image](https://user-images.githubusercontent.com/71893611/94611071-82a87380-02a1-11eb-8af3-1faf51b65e78.png)

**Comment by ziomik** [comment] 2020-09-29 20:48
Me too. I don't understand how it can't be one of the first problems to be solved!

**Comment by aerobaticant** [comment] 2020-09-30 13:44
@messer79 yes this is still a problem in 1.9.3. It seems to be in MSFS itself, not to do with A32NX. Trying to start up cold and dark at KLAS (Las Vegas) without the mod installed - same problem.

**Comment by dualcorebrain** [comment] 2020-10-03 21:03
can confirm I have the same issue regardless of A32NX...

**Comment by Wrg1t** [comment] 2020-10-05 02:10
have the same problem in 1.9.3 but at the same gate restart many times it can works randomly

**Comment by aerobaticant** [comment] 2020-10-05 09:35
From the official [MSFS forums](https://forums.flightsimulator.com/t/1-9-3-0-a320neo-cold-dark-doesnt-start/287828/53) it appears there a couple of possible workarounds.
1) Setting airport ground traffic density to 0
2) Setting AI generic models to ON

Allegedly the bug is caused by an AI aircraft overriding your own A320 at certain larger airports.
Hopefully this will be fixed by Asobo/MS

**Comment by hotshotp** [comment] 2020-10-24 02:46
battery bug is no longer present

**Closed by hotshotp** 2020-10-24 02:46 UTC
Labels: Asobo Bug, Bug, Critical Bug
