### ISSUE TITLE
[BUG] Switch to Screen/VR mode delete flight plan

### ISSUE THREAD

**Issue by ThubHulk** [flybywiresim/a32nx#3522] opened 2021-02-14 10:14 UTC
**Mod Version**
 0.5.2

**Describe the bug**

When switching from VR to screen mode or screen mode to VR, le flight plan is deleted 

**To Reproduce**

1. Enter a plight plan
2. Press touch to go to screen mod
2. See that flight plan is deleted
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment] 2021-02-14 14:38
Duplicate of #2703

**Closed by MisterChocker** 2021-02-14 14:38 UTC
Labels: Bug
