### ISSUE TITLE
Selecting a DCT to a waypoint deletes all waypoints in the route

### ISSUE THREAD

**Issue by Flyingtrader06** [flybywiresim/a32nx#4500] opened 2021-04-19 16:19 UTC
**Aircraft Version**
Latest development version (fd7252e)

**Describe the bug**
When performing a DCT to waypoint which is part of the route in FMC, all following waypoints get deleted except the ones which are part of the STAR and transition. Then, after passing that specific waypoint where you are directing to, the waypoints reappear in the FMC.

**To Reproduce**
1. Prepare a flight from LFOB to LFMU
2. Enter the following route in FMC : ERIX1V ERIXU UN860 ETAMO UZ271 ADEKA UT18 MEN J27 AFRIC AFRI2Z 
3. Shortly after take off (around 3000ft), proceed DCT EDOXA
4. All waypoints after EDOXA are deleted in FMC until the STAR (see attached screenshot)
5. After passing EDOXA, all following waypoints reappear in FMC

**Expected behavior**
Performing a DCT should not delete all following waypoints in the route

**Actual behavior**
See bug description

**References**
Not available

**Additional context**
N/A

Was this working before/when did the issue start occurring?
Unsure, it does not always occur but it has happened to me for a while already, including in previous versions.

Is this a problem in the vanilla unmodded game?
Unknown.

None

**Comment by MisterChocker** [comment] 2021-04-19 17:05
Duplicate of #1438 and #1388

**Closed by MisterChocker** 2021-04-19 17:05 UTC
Labels: Bug
