### ISSUE TITLE
Window Shades For Cockpit Windows

### ISSUE THREAD

**Issue by GunaGokul** [flybywiresim/a32nx#6972] opened 2022-03-27 07:00 UTC
### Aircraft Version

Development

### Description

Hey

Can we please get window blinds/shades for the cockpit side windows.

### References (optional)

![41kwcUxmjXL _AC_SY1000_](https://user-images.githubusercontent.com/43273545/160270402-e670aa18-eb7a-4114-88aa-92df7636f3aa.jpg)

![image](https://user-images.githubusercontent.com/43273545/160270472-b53e8d2f-837c-4c03-91c5-b24ec31563d4.png)

### Discord Username (optional)

Guna#3359

**Comment by tracernz** [comment] 2022-03-27 07:26
Duplicate of https://github.com/flybywiresim/a32nx/issues/4587. FBW 3D model needed.

**Closed by tracernz** 2022-03-27 07:26 UTC
Labels: Request
