### ISSUE TITLE
[BUG] Engine 1 Shutting Off

### ISSUE THREAD

**Issue by EsherDemo** [flybywiresim/a32nx#768] opened 2020-09-20 11:48 UTC
**Mod Version**
MASTER

**Describe the bug**
Eng.1 keeps switching off

**To Reproduce**
After a normal, good start and while taxiing for TO eng.1 shuts down and it will not start back up.
Tried on two occations with different proc. 

**Expected behavior**
-

**Actual behavior**
-

**References**
-

**Additional context**
-

**Comment by ferics** [comment] 2020-09-20 11:50
You might be on the outdated version. A temporary fix was released on the master branch. Try to redo it again :)

**Comment by NathanInnes** [comment] 2020-09-20 17:25
Unable to reproduce on latest master.

**Comment by EsherDemo** [comment] 2020-09-20 17:41
Still got the same problem, been trying to fix all day

**Comment by NathanInnes** [comment] 2020-09-20 17:42
Delete the entire mod and reinstall again if you haven't already

**Comment by EsherDemo** [comment] 2020-09-20 18:30
Done two times :(

**Comment by Benjozork** [comment] 2020-09-20 18:32
@EsherDemo do you always spawn at the same airport ?

**Comment by EsherDemo** [comment] 2020-09-20 18:35
No different airport, and different livery

**Comment by Inaxair** [comment] 2020-09-20 20:10
Could you please provide a recording of the thing? Also, can you share us your community folder to see if there's any other stuff that might interfer to our mod? Thanks

**Comment by AdenFlorian** [comment] 2020-09-21 20:25
please make sure you are using actual latest master (https://github.com/flybywiresim/a32nx/archive/master.zip)

this is supposed to have been fixed on master branch (not 0.2.0)

If you still get it after downloading from that link, you can reopen the issue, but at that point we'll probably need a video, or if you could show it to someone in discord that would be great, thanks!

**Closed by AdenFlorian** 2020-09-21 20:25 UTC
Labels: bug, can't reproduce

**Comment by EsherDemo** [comment] 2020-09-27 11:17
![Skjermbilde (43)](https://user-images.githubusercontent.com/70342777/94363640-d2314880-00c3-11eb-9960-041ccd8ec6f5.png)

Still not a fix for this :/
