### ISSUE TITLE
Engines stop when tank pumps are off

### ISSUE THREAD

**Issue by DescendDescend** [flybywiresim/a32nx#4005] opened 2021-03-16 20:05 UTC
**Mod Version**

{
  "built": "2021-03-15T11:39:00+00:00",
  "ref": "fbw",
  "sha": "8fbab904f3e1baa254a002522253441498c00904",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

Engines should run without tank pumps on. Gravity Feeding.

**To Reproduce**

1. Start an Engine with tank pumps on.
2. Turn off all pumps.

**Expected behavior**

Engine should continue to run. No info on whether it should start without tank pump but it is a reasonable expectation.

**Actual behavior**

Engine shuts down

**References**

FCOM CEO - QRH - Fuel : Gravity Fuel Feeding

**Additional context**

See engine discussion on Discord.

Was this working before/when did the issue start occurring?
It has always behaved like this

Is this a problem in the vanilla unmodded game?
Not known

Discord username (if different from GitHub):
DescendDescend

**Comment by MisterChocker** [comment] 2021-03-16 20:28
Duplicate of #2841

**Closed by MisterChocker** 2021-03-16 20:28 UTC
Labels: Bug
