### ISSUE TITLE
[BUG] Insert "Direct"

### ISSUE THREAD

**Issue by Leon30217** [flybywiresim/a32nx#3029] opened 2021-01-13 19:20 UTC
**Mod Version**
Master Branch Build (with custom FBW)

**Describe the bug**

But the another Waypoints should normally be deleted until DS515 from the system

**To Reproduce**
1. enter DS515 (EDDM-EDDS) in path DIR
2. route is displayed until DS515
3. another waypoints are still there

**References**

![Direct](https://user-images.githubusercontent.com/77197869/104499061-d0d94c80-55dc-11eb-96b9-6cdf5a3665e5.jpg)
![Direct_1](https://user-images.githubusercontent.com/77197869/104499066-d33ba680-55dc-11eb-880f-1c75b229dc67.jpg)

Was this working before/when did the issue start occurring?
no
Is this a problem in the vanilla unmodded game?
i don´t know

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment] 2021-01-13 19:21
I have already closed your issue as it is a duplicate of #1746. Please do not open more.

**Closed** 2021-01-13 19:22 UTC
Labels: Bug
