### ISSUE TITLE
A321neo and A321XLR

### ISSUE THREAD

**Issue by michael60634** [flybywiresim/a32nx#7928] opened 2023-04-01 02:20 UTC
### Aircraft Version

Development

### Description

It would be nice to see FBW develop a A321neo and a A321XLR in the future as these are popular versions of the A320neo.

### Discord Username (optional)

michael60634#4776

**Comment by Benjozork** [comment] 2023-04-01 02:36
Duplicate of #1408

**Closed by Benjozork** 2023-04-01 02:36 UTC
Labels: Request
