### ISSUE TITLE
L/G able to be deployed above 260kts

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5093] opened 2021-06-11 23:02 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-11T10:53:14+00:00",
  "ref": "master",
  "sha": "61806933977ff5d448a5ec2a38785e227c8310e6",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

When flying above 260kts, if L/G lever is selected down, the landing gear will actually extend.

### Expected behavior

Above 260kts, the hydraulic system cuts off supply to the L/G operation, thus, it won't be able to operate.

### Steps to reproduce

1. Fly above 260kts
2. Select L/G lever down
3. Gear will come down (not supposed to)

### References (optional)

![image](https://user-images.githubusercontent.com/85410344/121756247-d84f4400-caef-11eb-8656-3d0e588fe7cc.png)
![image](https://user-images.githubusercontent.com/85410344/121756257-e1401580-caef-11eb-86a3-265e69dbce55.png)

### Discord Username (optional)

Illuminati

**Comment by aguther** [comment] 2021-06-12 07:03
Not everything is a bug. It would be a bug if we have said it's implemented but it does not work.

**Comment by Illuminati270** [comment] 2021-06-12 08:16
When I saw the "L/G CTL" on the lower ecam, I thought the logic was already implemented! My bad.

**Comment by davidwalschots** [comment] 2021-06-17 08:13
Duplicate of #2731.

**Closed by davidwalschots** 2021-06-17 08:13 UTC
Labels: Enhancement, Hydraulics, Needs System Implementation
