### ISSUE TITLE
[BUG] HOLDING PATTERNS NOT WORKING

### ISSUE THREAD

**Issue by daniel5800** [flybywiresim/a32nx#2549] opened 2020-12-19 21:42 UTC
**Mod Version**

 A32NX V5 STABLE

**Describe the bug**

When setting a holding pattern at a waypoint it doesn't work

**To Reproduce**

1. Approach a waypoint
2. Set a holding loop for that waypoint
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes

Is this a problem in the vanilla unmodded game?
Not Sure

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-12-19 21:44
Duplicate of #673

**Closed by Benjozork** 2020-12-19 21:44 UTC
Labels: Bug
