### ISSUE TITLE
[BUG] Flight Physics - Wing Dips on Flare

### ISSUE THREAD

**Issue by efortier-95** [flybywiresim/a32nx#974] opened 2020-09-29 23:41 UTC
**Mod Version**

v0.3.1 release version

**Describe the bug**

Aircraft wing dips on idling the engine when on approach

**To Reproduce**

1. Establish the aircraft in landing configuration
2. Idle the aircraft at 50 feet
3. Wing dips

**Expected behavior**

Wing doesn't dip (barring weather phenomena)

**Actual behavior**

Wing dips, linked to idling the engine

**References**

N/A

**Additional context**

Seems to be a flight model issue. Exists in the unmodded game according to MSFS Forums

Discord username (if different from GitHub):
Eefoe#0570

**Comment by AdenFlorian** [comment] 2020-09-29 23:48
please add a title

**Comment by efortier-95** [comment] 2020-09-29 23:50
Whoops, fixed!

**Comment by m-ketan** [comment] 2020-09-30 04:18
Can confirm I'm facing the same issue in the unmodded game.

**Comment by collinbrady** [comment] 2020-10-01 21:54
Definitely an issue. Doesn't matter the configuration - I can have a perfect approach and if you idle too early (even above 140kt which should be perfectly fine with landing flaps) the left wing will try to smack into the ground half of the time. This has been reported all over the place and kinda ruins every flight.

**Comment by efortier-95** [comment] 2020-10-01 22:11
Just an update: since v0.3.1, it appears that the RIGHT wing dips now (albeit less aggressively). 

I've updated the issue title and content to reflect that either wing can drop (unsure of which it is).

**Comment by collinbrady** [comment] 2020-10-01 23:49
It seems whichever wing is even barely out of level alignment facing down is the one that stalls. Needs more testing.

**Comment by Berniep94** [comment] 2020-10-02 09:20
i can confirm that, when i get 150 kts aproach my wings are good, no problem landing in flare, but if i go manual my wings, falls aleatory to a side, and its imposible to land correctly... only if i hit below 145 app... its just something weird! Thank you.

**Comment by August78** [comment] 2020-10-06 14:57
The wing dip is not tied to idling the engine. Yesterday I got it at over 100ft AGL, and I dont pull back on the throttles until 20 ft.

**Comment by dickbig2** [comment] 2020-10-24 06:36
> The wing dip is not tied to idling the engine. Yesterday I got it at over 100ft AGL, and I dont pull back on the throttles until 20 ft.
> 
> To add to the discussion: To me it seems like my aileron inputs are being ignored during this bug. Full oposite aileron will not correct the bug right away, it seems to ignore it. I am not getting any stall warnings, and I am well above stall speed. If this is a stall, I wouldn't know it. I've been speculating if there is a bug that under certain conditions the flare logic of the airbus of a gentle nose down of so-so many degrees per minute is translated into a banking motion instead.

Exactly, it makes hand fly landing so so difficult as you will need to keep correcting and this roll effect basically ruins your landing

**Comment by Benjozork** [comment] 2020-10-24 06:37
This should not have been closed.

**Comment by henrikx** [comment] 2020-10-24 23:23
Has anyone observed the aileron status in the display when this happens? To see if the FBW is commanding left/right roll incorrectly.

**Comment by efortier-95** [comment] 2020-10-25 00:03
Working on it right now, will report back.

**Comment by efortier-95** [comment] 2020-10-25 00:22
Dev mode:
built: 2020-10-24T05:27:00+00:00
ref: refs/heads/master
sha: 16c20e42d50526cfcd042e8da51f1e08c7323008
actor: Benjozork
event_name: push

**Could not recreate**, ailerons remained neutral and no spoilers deployed

Conditions:
- World Config: Winds calm, Temp 17C, QNH 1019, Airport at Sea Level
- Aircraft config: Flaps full, Weight 68,000 kg, Vapp ~138KIAS, Autothrottle in Managed Mode through full approach, idled at 50 feet

This may be related to the change in flight dynamics, I don't think the AoA is as ridiculously high nowadays as it used to be so maybe stall protection doesn't activate?

**Comment by efortier-95** [comment] 2020-10-25 18:55
Tried again, still couldn't recreate.

I captured the landing with the F/CTL ECAM page on. I couldn't see any deviations other than what I commanded with the flight controls.

**Comment by henrikx** [comment] 2020-10-26 22:23
@efortier-95 It is very random when it happens, so if you keep trying it will happen eventually.

**Comment by waterefficiencytech** [comment] 2020-10-26 22:41
I've been doing a ton of flights the past few nights and I haven't seen it once. Will continue, but in the meantime, a couple questions for you all:

- Are you landing overweight?
- Are you in Config 3 (should be ~5 knots faster) or Full?

Regardless, the ground effect is still a total PITA when it comes to floating forever if you miss your flare being perfect - I assume Asobo needs to do something about that.

**Comment by collinbrady** [comment] 2020-10-26 22:42
I've been doing a ton of flights the past few nights and I haven't seen it once. Will continue, but in the meantime, a couple questions for you all:

Are you landing overweight?
Are you in Config 3 (should be ~5 knots faster) or Full?
Regardless, the ground effect is still a total PITA when it comes to floating forever if you miss your flare being perfect - I assume Asobo needs to do something about that.

**Comment by Berniep94** [comment] 2020-10-26 22:48
> I've been doing a ton of flights the past few nights and I haven't seen it once. Will continue, but in the meantime, a couple questions for you all:
> 
> 
> 
> - Are you landing overweight?
> 
> - Are you in Config 3 (should be ~5 knots faster) or Full?
> 
> 
> 
> I've been able to land around 140 to 145 at Full without handling issues.
> 
> 
> 
> Regardless, the ground effect is still a total PITA when it comes to floating forever if you miss your flare being perfect - I assume Asobo needs to do something about that.

This is a known issue from asobo, not for FBW Team, it's supposed to be fixed in tomorrow upadate, we have to cross fingers hahahaha, but definetly is more stable with the new flight model & engine performance... lets see what we can expect for tomorrow update!

**Comment by August78** [comment] 2020-11-08 20:45
I just did the Sidney landing challenge in the a320 with the FBW mod installed. As I came into the flare, the roll input become very insensitive, the plane starts to bank to the left, and the pitch becomes very sensitive. Almost like it's the opposite problem from the bank.

**Comment by dickbig2** [comment] 2020-11-09 04:13
Still not getting fixed in this patch.
Disappointing...

**Comment by MuppetOwl** [comment] 2020-11-12 00:07
See the Asobo patch 6 notes say its fixed.
> The Airbus A320neo Fly-by-wire bank oscillation now works properly

Its not, just happens but still very random like before.

**Comment by Toneking77** [comment] 2020-11-15 21:46
Saw this post on Reddit.  Thought it might help sort this out.  Sorry if this is not helpful... thought it was best to ask.  Thank you!
https://www.reddit.com/r/MicrosoftFlightSim/comments/juosac/simple_fix_for_a320_wing_dip_bug_plane_rolls_left/

**Comment by nhvtmedic** [comment] 2020-11-18 21:55
I am still having this issue with every landing. Left and right wing.

**Comment by collinbrady** [comment] 2020-11-18 22:24
> Saw this post on Reddit. Thought it might help sort this out. Sorry if this is not helpful... thought it was best to ask. Thank you!
> https://www.reddit.com/r/MicrosoftFlightSim/comments/juosac/simple_fix_for_a320_wing_dip_bug_plane_rolls_left/

Has anyone confirmed this works - its functions are obviously related to the control surfaces, and possibly whatever is affecting them or the flight model at the end of landing? Here's that switch's operations from the A320 manual:

**Control the FCSC (Flight control Secondary Computers)**
ON : The following functions are provided by each computer
 - pitch direct
 - roll direct
 - yaw alternate
 - rudder trim
 - rudder travel
OFF – computer off. Off then On resets it.

**Comment by nhvtmedic** [comment] 2020-11-18 22:57
I just tried turning SEC off and it seems to fix the landing issue wing drop issue, having done three landings.

**Comment by Zak101** [comment] 2020-11-25 15:15
> I just tried turning SEC off and it seems to fix the landing issue wing drop issue, having done three landings.

how do you turn off the sec?

**Comment by Berniep94** [comment] 2020-11-25 16:10
> > I just tried turning SEC off and it seems to fix the landing issue wing drop issue, having done three landings.
> 
> how do you turn off the sec?

Just above your head, in the overhead, left section FLT CTR, below IRS

**Comment by e4rthdog** [comment] 2020-12-01 19:43
> > > I just tried turning SEC off and it seems to fix the landing issue wing drop issue, having done three landings.
> > 
> > 
> > how do you turn off the sec?
> 
> Just above your head, in the overhead, left section FLT CTR, below IRS

Does it affect later stages of the flight? Do we need to turn it on again for approach?

**Comment by henrikx** [comment] 2020-12-01 19:57
> 
> 
> I just tried turning SEC off and it seems to fix the landing issue wing drop issue, having done three landings.

So since this fixes it, the bug is probably FBW directing full left aileron then or am I wrong?

**Comment by collinbrady** [comment] 2020-12-03 03:39
> > > > I just tried turning SEC off and it seems to fix the landing issue wing drop issue, having done three landings.
> > > 
> > > 
> > > how do you turn off the sec?
> > 
> > 
> > Just above your head, in the overhead, left section FLT CTR, below IRS
> 
> Does it affect later stages of the flight? Do we need to turn it on again for approach?

You keep it on the entire flight. You ONLY turn it off mid approach.

**Comment by hotshotp** [comment] 2020-12-23 22:15
fixed with custom flybywire

**Comment by MisterChocker** [comment] 2020-12-31 07:07
I'd close this since it's no longer an issue.
@Benjozork opinion?

**Comment by MisterChocker** [comment] 2021-01-18 18:14
Flight Model meta issue for tracking #3105

**Comment by lukecologne** [comment] 2021-04-23 23:58
Fixed with custom FBW.

**Closed by lukecologne** 2021-04-23 23:58 UTC
Labels: Bug, Bug-Vanilla, Flight Model
