### ISSUE TITLE
Brightness of all displays

### ISSUE THREAD

**Issue by nick2332f** [flybywiresim/a32nx#4186] opened 2021-03-29 09:20 UTC
**Is your feature request related to a problem? Please describe.**

I think its better to have an option for all the displays to be turned all the way up automatically so that i dont waste time and its quite annoying to turn the brightness up of everything.

**Describe the feature you'd like to see implemented**

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by DtotheAtotheVtotheE** [comment] 2021-03-29 10:14
No thanks.

**Comment by gb09f** [comment] 2021-03-29 14:09
It's my personal preference that I manually adjust the displays as part of the Cockpit Preparation checklists.

**Comment by Benjozork** [comment] 2021-03-29 14:33
The current cold and dark state is set based on feedback from real pilots. A turnaround state will most likely be introduced in the future.

**Comment by MisterChocker** [comment] 2021-03-29 15:11
From C&D displays are turned all the way down to the lowest brightness IRL.

I am closing since it's working as intended.

**Closed by MisterChocker** 2021-03-29 15:11 UTC
Labels: Enhancement

**Comment by nick2332f** [comment] 2021-03-29 16:08
yea i know they are turned down all the way irl but its annoying in game, at least a keybind to turn all up at the same time.

**Comment by MisterChocker** [comment] 2021-03-29 16:23
As benjozork said, we will eventually have custom aircraft states.
