### ISSUE TITLE
[REQUEST] Complete MCDU in separate window

### ISSUE THREAD

**Issue by AndersHogqvist** [flybywiresim/a32nx#1317] opened 2020-10-14 08:58 UTC
**Is your feature request related to a problem? Please describe.**

At the moment only the displays can be undocked which is great but not very useful for the MCDU since you can't interact with it. Using a touchscreen or having a tablet connected with something like spacedesk it would be awesome if one could have the entire MCDU in a separate window.

**Describe the feature you'd like to see implemented**

I'm not sure how (or even if) this could be accomplished, but after poking around in the source code I have come to the conclusion that the displays are html pages with JavaScripts that acts as a bridge to the underlying logic. I've tried to figure out what's happening when I undock a display but without any luck, but I recon it essentially opens a browser window that is showing the same html page that is shown in the 3D cockpit. If that's the case I'm thinking it should be possible to create a new window or modify the existing one with an image of the MCDU as a background and the display in a div positioned on top of that. The buttons don't need to be animated, using a html map and audible feedback would suffice. 

**References**

**Additional context**

Since I've been a software developer for many years I thought I would be able to pull this off myself, but I have never developed anything for FSX or the likes and since the SDK documentation on HTML panels is lacking I haven't been able to even figure out where to start. If you guys think this could be accomplished but don't have the time I would be more than happy to get my hands dirty if someone is willing to point me in the right direction.

Discord username (if different from GitHub): ZenIT_SWE

**Comment by Benjozork** [comment] 2020-10-14 16:33
Maybe this could be done by making the MCDU screen larger than the physical display, which would make the clickable layout invisible when the screen is undocked.

**Comment by AndersHogqvist** [comment] 2020-10-15 05:09
> Maybe this could be done by making the MCDU screen larger than the physical display, which would make the clickable layout invisible when the screen is undocked.

I've had that thought too, but I haven't been able to find where this windows is created. I recon that's happening somewhere in the files we're not supposed to have access to (in the WindowsApps for the Store version)? I was hoping some of the devs would be able to provide some input on this.

**Comment by MisterChocker** [comment] 2020-12-31 07:48
duplicate of #1058

**Closed by MisterChocker** 2020-12-31 07:48 UTC
Labels: Enhancement, MCDU
