### ISSUE TITLE
[BUG] ILS Indicators not showing on approach

### ISSUE THREAD

**Issue by neto123456789** [flybywiresim/a32nx#1729] opened 2020-11-03 03:45 UTC
**Mod Version**
V0.4.1 Stable version

**Describe the bug**
ILS indicators will not show on PFD or MFD screen. I've tried many different airports, stock a320 and no custom livery, and deleted all Mods less the A320NX mod, yet the problem persists. 

**To Reproduce**

1. Entered an IFR plan on home screen (tried starting at the gate and runway, the problem happened in both scenarios).
2. Activated approach, selected LS button on a320 and ILS indicators did not show up on PFD and MFD.
3. Did not touch RADNAV page on MCDU. I have not had to mess with that screen in prior releases. Not sure if this is a problem with Freq not loading in.

**Expected behavior**
ILS indicators to appear on approach on PFD and MFD.

**Actual behavior**
ILS indicators do not show up on displays when on approach to a runway that supports ILS landings.

**References**
![Microsoft Flight Simulator Screenshot 2020 11 02 - 21 27 49 74](https://user-images.githubusercontent.com/73372052/97947786-07c8f180-1d54-11eb-8a87-337bcdb67633.png)

![Microsoft Flight Simulator Screenshot 2020 11 02 - 21 28 37 10](https://user-images.githubusercontent.com/73372052/97947948-8de53800-1d54-11eb-86ca-20e71bdcace5.png)

![Microsoft Flight Simulator Screenshot 2020 11 02 - 21 29 15 78](https://user-images.githubusercontent.com/73372052/97947959-976ea000-1d54-11eb-96a2-93502aabe75f.png)

**Additional context**

Was this working before/when did the issue start occurring?
No, this issue was not happening on prior releases of the a320NX mod. I've always entered my ILS plans on the main menu and had no issues prior to the release.

Is this a problem in the vanilla unmodded game?
No, this problem is not on the unmodded game/a320. ILS indicators worked with no issue in the vanilla version of the game. 

Discord username (if different from GitHub): Neto787#4660

**Comment by wpine215** [comment] 2020-11-03 03:55
Confirmed, had this issue as well on the latest master branch. The indicators show up for a fraction of a second when turning the LS glareshield button on, then disappear.

**Comment by Benjozork** [comment] 2020-11-03 03:57
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Might wanna remove this.

Also, this should be fixed with the latest master build. In stable, ILS frequency is not entered automatically in the RAD NAV page. Can you try the dev version ?

**Comment by SRMatherson** [comment] 2020-11-03 04:18
Can confirm this too.  ILS frequency is in and selector is enabled but it does not appear even though the glideslope is followed by the equipment.

**Comment by tareksabet** [comment] 2020-11-03 04:54
You will have to enter the ILS frequency manually via RAD NAV page on the MCDU by only typing the frequency only . But sadly I don't know what's the reason for it as it works for some of them and others doesn't also try to press the ILS button on the co pilot side. Thanks for reporting

**Comment by neto123456789** [comment] 2020-11-03 05:29
> > BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning
> 
> Might wanna remove this.
> 
> Also, this should be fixed with the latest master build. In stable, ILS frequency is not entered automatically in the RAD NAV page. Can you try the dev version ?

> ILS indicators worked on the Master version. I'll keep an eye out of the next stable version to switch over. Thanks !
> Build info
> built: 2020-11-02T23:19:21+00:00
ref: refs/heads/master
sha: 0402635c7e9a68807453b5741c9ffc7380af9844
actor: lukecologne
event_name: push

**Comment by assafco1000** [comment] 2020-11-03 13:17
ILS used to work automatically when getting to the final leg. 
Now I need to enter frequency manually and unfortunaelty this info is not accessible during the game. Hope it is a bug and not a feature...

**Comment by Benjozork** [comment] 2020-11-03 14:39
Fixed in master

**Closed by Benjozork** 2020-11-03 14:39 UTC
Labels: Bug

**Comment by SRMatherson** [comment] 2020-11-03 21:47
> ILS used to work automatically when getting to the final leg.
> Now I need to enter frequency manually and unfortunaelty this info is not accessible during the game. Hope it is a bug and not a feature...
You can enter the ILS details in the radnav page (button) in the FMS.
