### ISSUE TITLE
Cannot turn on airplane at the gate

### ISSUE THREAD

**Issue by allemattio** [flybywiresim/a32nx#802] opened 2020-09-22 10:08 UTC
Hi,
I downloaded and installed the master branch to solve the problems with the default A320Neo problems.
Yesterday I started at the gate in Johannesburg, with the airplane Cold&Dark, and I cannot turn on the batteries, and so the whole aircraft.
I click on the batteries buttons on the overhead panel but nothing happens, the systems don't turn on and the battery buttons remain black.
Even pressing ctrl+e does nothing.
This is the same behaviour that occurs with the default a320neo, is there a solution to this? Am I doing something wrong?
Thanks in advance

**Comment by jeremytm** [comment] 2020-09-22 11:06
Same issue here.

**Comment by tmthyDXTR** [comment] 2020-09-22 11:11
Restarting the mission "solved" the bug for me.

**Comment by allemattio** [comment] 2020-09-22 11:42
I tried restarting the flight but didn’t solved..

**Comment by Benjozork** [comment] 2020-09-22 12:02
Please respect the issue templates.

**Comment by UncleClapton** [comment] 2020-09-22 12:26
Duplicate of #718. Closing

**Closed by UncleClapton** 2020-09-22 12:26 UTC

**Comment by allemattio** [comment] 2020-09-22 12:44
I'm sorry, I haven't seen the template, my bad
