### ISSUE TITLE
PFD, ND and ECAMS

### ISSUE THREAD

**Issue by Spartan3001961** [flybywiresim/a32nx#4047] opened 2021-03-21 09:49 UTC
**Mod Version**
Custom 545c472

**Describe the bug**
After updating the installer, the A320NX install folder changed to "flybywire-aircraft-a320-neo" and now PFD, ND and ECAMS are not displaying. 

**To Reproduce**

1. Deleted the old A320NX install folder
2.Updated the installer
3.Installed the latest Custom version

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by BjoernHund** [comment] 2021-03-21 10:19
I noticed the same bug with the new installer this morning. I installed the latest developer version. With the new renamed folder for the A32NX the displays are all black.

After I installed the latest dev version manually - folder name A32NX - everything works as expected.

**Comment by Spartan3001961** [comment] 2021-03-21 10:22
I did exactly the same with the Custom version. I manually downloaded the zip version and this installs correctly

**Comment by notl3ks** [comment] 2021-03-21 14:29
> 
> 
> I did exactly the same with the Custom version. I manually downloaded the zip version and this installs correctly

Hey bud, I can confirm from my end that does work. I was pretty upset this morning about this, I was full on spending at least an hour trying to figure out what the hell was going on, looked on various forums, tried different aircraft switches/configs. But yeah, deleting the new installer folder it makes and replacing it with a manually downloaded one from here seems to work fine.

Hopefully the devs can get this fixed soon. (you all do an amazing job by the way!)

**Comment by BjoernHund** [comment] 2021-03-21 17:13
The installer was fixed. It works fine now.

**Comment by MisterChocker** [comment] 2021-03-22 12:39
Closing since issue resolved.

**Closed by MisterChocker** 2021-03-22 12:39 UTC
Labels: Bug
