### ISSUE TITLE
ND Refresh and TO CONFIG Broken

### ISSUE THREAD

**Issue by dg1234567** [flybywiresim/a32nx#7223] opened 2022-05-19 21:29 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-05-18T19:03:16+00:00",
    "ref": "refs/heads/master",
    "sha": "9b67261c0e10ea026958e179c6132c80388da893",
    "actor": "aguther",
    "event_name": "manual",
    "pretty_release_name": "master:9b67261c"
}
```

### Describe the bug

ND is basically unusable and unreliable as it doesn't refresh appropriately, and doesn't show aircraft flying the correct route even though it is. It is almost impossible to fly manually as the heading is unreliable. The only workaround seems to be using autopilot.

Also the TO CONFIG button needs to clicked multiple times until it actually does the test 

### Expected behavior

Ability to follow route based off the ND and having a normal refresh of the ND 

### Steps to reproduce

Cold and Dark
ADIRS Align
Fly

**Comment by incredibleoxman** [comment] 2022-05-19 21:53
#7216

**Comment by ErikNL80** [comment] 2022-05-20 05:14
Already reported in #7216

**Comment by beheh** [comment] 2022-05-20 08:17
Duplicate of #7216

**Closed by beheh** 2022-05-20 08:17 UTC
Labels: Bug
