### ISSUE TITLE
[BUG] Speed 0, pitch down during flight

### ISSUE THREAD

**Issue by Flier234** [flybywiresim/a32nx#1121] opened 2020-10-05 19:54 UTC
**0.3.1**

**During flight, phase isn't important, the speed indicator suddeny indicates 0 and the plane starts to pitch down, after disengaging autopilot and reengaging the problem disappears for a few minutes, then starts again, after disocnnecting for a while (hand-flying), the problem is solved, until later, when the same problem occurs, eventaully, it goes away.**

**To Reproduce**

1. Any flight on the aircraft
2. It will most liey occur during ascent or descent, it will occur randomly, after a few flights it should happen, it's not that unlikey.

**Expected behavior**
Normal climb and descent, speed indicator showing correct speed

**Actual behavior**
Speed indicator slows to idle suddenly, causes plane to pitch down thinking it's at 0 speed.

**References**
Here's a clip from a twitch stream clip from flight sim bests. 
https://www.youtube.com/watch?v=LVsKekDr0es (3:40)

**Additional context**

Didn't keep track

No idea

Discord username (if different from GitHub): Tim Shaf IQ (3037)

**Comment by CoffeePanda0** [comment] 2020-10-05 19:57
This is caused by the excessive icing asobo have in the sim
The pitot tubes get frozen and so speed displays 0. This makes the plane pitch down as it tries to gain speed
To fix this turn ON pitot heat even not when icing

**Comment by NathanInnes** [comment] 2020-10-05 22:07
#1118 should fix this

**Comment by NathanInnes** [comment] 2020-10-16 18:32
Has this issue now been fixed?

**Comment by lukecologne** [comment] 2020-11-17 22:03
Pitot Icing has been fixed by implementing auto pitot heat.

**Closed by lukecologne** 2020-11-17 22:03 UTC
Labels: Bug
