### ISSUE TITLE
[BUG] SimBrief flightplan don't work but manual mode works

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#3138] opened 2021-01-22 05:58 UTC
**Mod Version**

2021-01-22T001334

**Describe the bug**

SimBrief flightplan (LFKB/16 MOUL6U MOULE L146 ELB L12 LUMAV M726 BRENO BREN2A LOWI/26) don't work but manual mode works

**To Reproduce**

1. Define SimBrief route LFKB/16 MOUL6U MOULE L146 ELB L12 LUMAV M726 BRENO BREN2A LOWI/26
2. In Simbrief mode, AWY/WPT mismatch
![2021-01-22 (11)](https://user-images.githubusercontent.com/5894146/105452613-e3a7ed00-5c7e-11eb-934f-5c2395a43c80.jpg)

3. In manual mode, no problem

**Expected behavior**

No FlightPlan is entered
![2021-01-22 (1)](https://user-images.githubusercontent.com/5894146/105452795-37b2d180-5c7f-11eb-8753-b95565ac38e9.jpg)

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by tracernz** [comment] 2021-01-22 08:32
![image](https://user-images.githubusercontent.com/9995998/105466535-3cb46700-5cf9-11eb-90f1-50c17756a3d9.png)

**Comment by kiokio0987** [comment] 2021-01-22 11:49
@JLD95 We seem to be discussing the same issue under different numbers (#2923).
It is better to close one side.

**Comment by MisterChocker** [comment] 2021-01-23 17:33
Duplicate of #2923

**Closed by MisterChocker** 2021-01-23 17:33 UTC
Labels: Bug
