### ISSUE TITLE
Landing gear indicator lights don't behave correctly

### ISSUE THREAD

**Issue by UncleClapton** [flybywiresim/a32nx#244] opened 2020-08-30 09:13 UTC
There are a few issues with how the indicators behave right now.

1. When coming from the gear down position, the green arrows on the indicators immediately turn off when the landing gear lever is flipped. Instead it seems like those lights are supposed to turn off shortly afterward (perhaps after the doors have opened and the gear has begun retracting)

2. When transitioning between positions, all 3 indicators finish changing together. Instead it appears that each indicator should finish transitioning independently, based on when the respective set of wheels lock into place.

video references: 

* https://youtu.be/cv41hm4JEB8?t=214
* https://youtu.be/myBmuhsJf90?t=560
* https://youtu.be/UKABHGDWg0Q?t=19

UNLK's light color is also an issue, but has been reported previously here: #198

**Comment by NathanInnes** [comment] 2020-08-31 02:33
Ill have a look into solving this issue

**Comment by NathanInnes** [comment] 2020-08-31 11:08
Working on it now

**Comment by Curtis-VL** [comment] 2020-09-01 16:04
Please close this issue once the merge has completed and the issue is resolved. :)

**Closed** 2020-09-05 02:52 UTC
Labels: Waiting for PR merge
