### ISSUE TITLE
select VOR/ILS radio on RMP

### ISSUE THREAD

**Issue by flaminiom** [flybywiresim/a32nx#3268] opened 2021-02-01 01:38 UTC
**Mod Version**

 6dd6c64

**Describe the bug**

Can no longer select VOR/ILS radio mode on nav radio controls. Buttons clicks appear to do nothing. Can’t view or change from the radio.

**To Reproduce**

1. Click radio control buttons to change modes
2.
3.

**Expected behavior**

Clicking buttons change mode to view and change radio frequencies for VOR and ILS

**Actual behavior**

Nothing happens

**References**

**Additional context**

Was this working before/when did the issue start occurring?

An update to the dev model in the past few days.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Awemeter** [comment] 2021-02-01 04:39
The ils functions on your radio that you use for atc has never worked.

**Comment by lukecologne** [comment] 2021-02-01 12:07
> 
> 
> The ils functions on your radio that you use for atc has never worked.

Not true, the STBY NAV functionality on the RMP has worked before

**Comment by flaminiom** [comment] 2021-02-01 21:27
How it's worked in the past, and I believe with the 0.5.2 release is you click the nav button on the radio and it flips up the protector. Click it again and it activates, then you can click ILS. It shows the ILS freq programmed in RAD NAV and you can make changes there. It stopped doing that in the last week.

**Comment by flaminiom** [comment] 2021-02-02 00:34
Loaded 0.5.2 and confirmed it works there.

I noticed some work was done to the radio panel, so it may be related to that.

https://github.com/flybywiresim/a32nx/pull/2980

**Comment by theomessin** [comment] 2021-02-02 18:22
Yes, this is expected and on purpose. Remote radio navigation aid tuning from the radio management panel is currently not working in the development version. We will release a separate pull request with this functionality before release. In the meantime, if you really need this (which by the way, this remote tuning is rarely used in real life, unless both FMGCs are INOP) please stick with the stable version.

**Comment by BozoBBozo** [comment] 2021-02-02 20:54
I can confirm - I had been using a Dev version from about 10 days ago, and this morning updated to the latest Dev version, and...flipped up the Nav cover, and none of the buttons/lights would activate. I then reverted to last stable, and it worked just as I had expected.

90% of the time I'm flying VFR Direct, so I manually lookup and enter the ILS frequency from the chart.

**Comment by flaminiom** [comment] 2021-02-02 23:04
> Yes, this is expected and on purpose. Remote radio navigation aid tuning from the radio management panel is currently not working in the development version. We will release a separate pull request with this functionality before release. In the meantime, if you really need this (which by the way, remote tuning is rarely used in real life, unless both FMGCs are INOP - during normal ops you should use the RAD NAV page on the MCDU) please stick with the stable version.

Thanks for the explanation. It was intended as bug report. I couldn't find any documentation on the change of status with the function.

I find it nice to have as a confidence monitor in the sim to ensure I'm on the correct frequency. Since release, I'm never sure if I messed up or the sim is acting up when things don't go as expected.

**Comment by tracernz** [comment] 2021-02-03 00:14
Regression from #2980?

**Comment by derl30n** [comment] 2022-04-10 12:08
Duplicate of https://github.com/flybywiresim/a32nx/issues/4044

**Closed by derl30n** 2022-04-10 12:08 UTC
Labels: Request, RMP
