### ISSUE TITLE
EFB change weigh units to fuel aircraft via efb

### ISSUE THREAD

**Issue by Paul5287** [flybywiresim/a32nx#5321] opened 2021-07-15 02:45 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-13T05:36:14+00:00",
  "ref": "master",
  "sha": "faee7a996a5c51708fc4ed76963d58b18bbb59a9",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

Trying to change weight units in settings in EFB from KG to LBS. This was always greyed out until the new dev version was dropped yesterday. My MCDU is set to LBS, ive tried changing on the EFB to LBS & restarting the sim many times. Keeps reverting back to KG. Looking to load fuel into the plane using the EFB fuel page, not able to switch from KG to LBS.

### Expected behavior

Switch from KG to LBS on EFB

### Steps to reproduce

turned on battery, confirmed plane is in LBS, turned on EFB, settings page, weight units, switched from KG to LBS. Went to fuel page, still in KG, went back to settings in EFB, back on KG. Repeated.

### Discord Username (optional)

paul5287

**Comment by cavaricooper** [comment] 2021-07-18 10:58
![Screenshot 2021-07-18 065615](https://user-images.githubusercontent.com/34610551/126064601-b40abd11-68da-4cc0-b28a-86966c7660d8.jpg)

![Screenshot 2021-07-18 065654](https://user-images.githubusercontent.com/34610551/126064604-a29d6b7f-ff88-4af0-969e-64251fa1ec86.jpg)

**Comment by tracernz** [comment] 2021-07-18 11:03
Fixed in #5344

**Comment by cavaricooper** [comment] 2021-07-18 11:05
Brilliant- ta!

*Carl F. Avari-Cooper*

The information contained in this electronic mail transmission is intended
only for the use of the recipient(s) named above. It may contain
proprietary, confidential or privileged information of the sender. If you
are not the intended recipient, you are hereby notified that any
disclosure, dissemination, distribution or copying of the information
contained in this transmission is strictly prohibited. If you have received
this transmission in error, please notify the sender immediately by
electronic mail reply, and delete the original message and any copy of it
from your computer system.

**Comment by Paul5287** [comment] 2021-07-20 20:29
is there a fix for this? EFB fuel load page cannot be changed to lbs?

**Comment by tracernz** [comment] 2021-07-20 21:36
> is there a fix for this? EFB fuel load page cannot be changed to lbs?

Yes, in progress as above: https://github.com/flybywiresim/a32nx/issues/5321#issuecomment-882038774

The work-around is to set the unit in the MCDU rather than the FlyPad.

**Comment by Paul5287** [comment] 2021-07-20 21:38
when the sim loads the mcdu is set to lbs & that is all fine, but as far as loading fuel into the craft from the efb, that page is unable to show lbs, always shows kg

**Comment by tracernz** [comment] 2021-07-21 10:36
Duplicate of #5316.

**Closed by tracernz** 2021-07-21 10:36 UTC
Labels: Bug, EFB
