### ISSUE TITLE
Sunvisors

### ISSUE THREAD

**Issue by DomWin02** [flybywiresim/a32nx#5625] opened 2021-08-12 13:06 UTC
### Aircraft Version

Development

### Description

It will be nice, if the sunshaders will be operable. For the front glasses and the sides

### References (optional)

![main-qimg-5f54824a52ec66ca2da413c710c72a11](https://user-images.githubusercontent.com/88674959/129201974-f60758a7-5fbb-4c66-872e-289eb631ee35.jpg)
![51vpBIDYi8L _AC_SL1280_](https://user-images.githubusercontent.com/88674959/129202028-0e40b79b-6d7f-4020-a35f-5cd67d416f42.jpg)

### Discord Username (optional)

DomenicHAJ#0457

**Comment by NUTTTTTTTT** [comment] 2021-08-12 13:10
Repeat of issue https://github.com/flybywiresim/a32nx/issues/4587 - Please check existing issues before posting to avoid duplicate issues/enhancements in future. :)

**Comment by sidnov** [comment] 2021-08-12 13:29
Duplicate of #4587

**Closed by sidnov** 2021-08-12 13:29 UTC
Labels: Enhancement
