### ISSUE TITLE
[BUG] There is no overlap on the line during automatic flight

### ISSUE THREAD

**Issue by dc1ps2** [flybywiresim/a32nx#2078] opened 2020-11-24 02:48 UTC
**Mod Version**

{ "built": "2020-11-23T20:54:26+00:00", "ref": "refs/heads/master", "sha": "4786b605d327a9b32db51a7f5ed3ac4c399bd21b", "actor": "wpine215", "event_name": "push" }

**Describe the bug**

When I perform automatic flight, the aircraft icon seen by the instrument does not overlap with the route, and the same phenomenon appears on the VFR Map.

Before the BASOS waypoint, the plane's flight direction and the route show an angle of about 3 degrees, and continue to move forward.

In theory, it should overlap with the route sooner or later, and continue to follow the direction of the route, but continue to pass

**To Reproduce**

1. Departing from Queenstown International Airport (NZQN) Airport, expected to arrive at Sydney International Airport (YSSY).
2. Before the BASOS waypoint, the plane's flight direction and the route show an angle of about 3 degrees, and continue to move forward.

**Expected behavior**

In theory, it should overlap with the route sooner or later, and continue to follow the direction of the route, and continue to pass

**Actual behavior**

The flight direction of the aircraft presents an angle of about 3 degrees with the course, and continues to move forward at the same angle

**References**

![image](https://user-images.githubusercontent.com/11674129/100040079-97d4f500-2e41-11eb-8545-39ff3c2cdefe.png)

![2020-11-24 06-09-39 00_00_11-00_02_12](https://user-images.githubusercontent.com/11674129/100040610-90621b80-2e42-11eb-8133-8578442f71e6.gif)

build-info content：

{“ built”：“ 2020-11-23T20：54：26 + 00：00”，“ ref”：“ refs / heads / master”，“ sha”：“ 4786b605d327a9b32db51a7f5ed3ac4c399bd21b”，“ actor”：“ wpine215”，“ event_name“：” push“}

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-11-24 02:51
> **Mod Version**
>
> Either a release version

Please provide your version anyway, and the contents of `build-info` if using dev.

**Comment by dc1ps2** [comment] 2020-11-24 03:31
> > **Mod版本**
> > 發行版本
> 
> 無論如何，請提供您的版本以及`build-info`使用dev的內容。

I don’t know where to check the version number

**Comment by Benjozork** [comment] 2020-11-24 03:33
In your Community folder, A32NX folder, it will be right there.

**Comment by dc1ps2** [comment] 2020-11-24 03:34
> > > **Mod版本**
> > > 發行版本
> > 
> > 
> > 無論如何，請提供您的版本以及`build-info`使用dev的內容。
> 


I don’t know where to check the version number, i use A32NX Installer download development version

build-info info content:

{ "built": "2020-11-23T20:54:26+00:00", "ref": "refs/heads/master", "sha": "4786b605d327a9b32db51a7f5ed3ac4c399bd21b", "actor": "wpine215", "event_name": "push" }

**Comment by Benjozork** [comment] 2020-11-24 03:36
Thanks !

**Comment by MisterChocker** [comment] 2020-11-24 15:56
You are having quite a bit crosswind, the aircraft leans into the wind to maintain track. Track and Heading can be seen. Current heading will always be in the center, so from this perspective it works just fine.

**Comment by MisterChocker** [comment] 2020-11-24 15:58
Or did I missed something? And as long the waypoints isn't classified as overfly, the aircraft will not fly directly above the waypoint (on turns) but follows an optimal path instead.

**Comment by lukecologne** [comment] 2020-11-24 16:02
The problem is that the aircraft center should be on the flightpath, but in the current ND, the "nose" of the aircraft symbol is on the path, which is incorrect

**Comment by MisterChocker** [comment] 2020-11-24 16:08
gotchu

**Comment by dc1ps2** [comment] 2020-11-25 07:17
Thank you for flybywiresim team professional ability and wise judgment, I look forward to A32NX continuing to have such an outstanding job

**Comment by 2hwk** [comment] 2021-11-21 07:19
Fixed by #4953 closing ☑️

**Closed by 2hwk** 2021-11-21 07:19 UTC
Labels: Bug, ND, fixed in cFPM
