### ISSUE TITLE
[REQUEST]ADIRS ON BAT light

### ISSUE THREAD

**Issue by hotshotp** [flybywiresim/a32nx#450] opened 2020-09-06 11:27 UTC
**Is your feature request related to a problem? Please describe.**
No, not a problem. Just a feature which would improve realism.

**Describe the feature you'd like to see implemented**
Okay, so from what I've seen, IRL the procedure is to turn every individual ADIRS knob to NAV, and wait until the ON BAT light extinguishes. 

**References**

https://youtu.be/uqKeSO6msDk
At 3:10, the person shows exactly what I am talking about.

**Additional context**
Probably not a high priority right now, and I don't know how hard it would be to implement, but I'll just post it here.

**Comment by NathanInnes** [comment] 2020-09-06 11:41
This can't be worked on until the files from Asobo are released so it may take a while. But will definitely end up there in the future

**Comment by SmithFR** [comment] 2020-09-06 14:29
Duplicate of #320

**Closed** 2020-09-10 17:06 UTC
Labels: Overhead panel, Texture, enhancement
