### ISSUE TITLE
CTD when select ECAM - STATUS Page

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#6378] opened 2021-12-18 11:22 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-17T20:00:07+00:00",
  "ref": "master",
  "sha": "173105c63369fcdc5fed4884effa398e31072ad3",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

totday, I was 1:27h on my way to LEAL when I select STATUS - PAGE, followed by a audio stutter and seconds later CTD. Other Pages worked without CTD.

Update/selftest: I do not see any CTD when I´m on ground shortly after power-up. Only when I´m in flight and try to select it. I tried it only in CRZ and not in CLB or shortly after T/O

### Expected behavior

no CTD when select a ECAM page

### Steps to reproduce

1. start C&D
2. commence a flight
3. try to select ECAM STATUS PAGE on lower selector panel
4. wait for stutter/final CTD

**Comment by BlueberryKing** [comment] 2021-12-23 23:56
Hi! Have you been able to reproduce this consistently or is this more of a one-time thing?

**Comment by tracernz** [comment] 2022-01-13 23:14
Not unlike a real A320 with OEB 9 - “Dual FWC Failure following Status Page Display” 😂

**Comment by derl30n** [comment] 2022-04-09 21:30
Is this still an issue? Have you been able to reproduce the issue?

**Comment by tracernz** [comment] 2022-04-10 03:44
Related https://github.com/flybywiresim/a32nx/pull/6980

**Comment by beheh** [comment] 2022-05-18 19:36
Since #6980 has landed and that page has been completely reworked and there is no further details here, I will close this issue.

**Closed by beheh** 2022-05-18 19:36 UTC
Labels: Bug, Performance, Waiting For Response
