### ISSUE TITLE
[BUG] Continuing Issues with Incorrect Turning/Waypoints & FPL MCDU Screen Reset During Descent

### ISSUE THREAD

**Issue by DFWSupertrooper** [flybywiresim/a32nx#3505] opened 2021-02-13 16:04 UTC
**Mod Version**
Custom FBW 2021-02-13T10:07:19+00:00

**Describe the bug**
FPL screen on MCDU returns to initial portion of route and A/C turns unexpectedly towards beginning of route waypoints on decent.

**To Reproduce**
1. Load FPL EGLL-LOWW (DET1K DET L6 DVR UL9 KONAN UL607 KOK FERDI BUPAL REMBA SPI PESOV TOBOP OSBIT BARSU EKSOS LULAR BUDEX BUDE1W) loaded via MSFS World Map (matched to Simbrief).  Checked MCDU for FPL accuracy.
2. Departed EGLL and flew route to BUDE1W STAR/transition to ILS34 at FL370.
3. ATC ordered descent prior to BUDEX, began descent as ordered.
4. Just before NIRDU, while checking PERF page & FPL page to look for ALT CSTR, the FPL page had returned to original state with departure waypoints (except the last waypoint was still white).
5. Within seconds, MFD displayed next waypoint was D0 663+ miles away (original departure waypoint) and A/C began to turn towards it.
6. Locked in HDG mode and used HDG to navigate remainder of route to ILS capture.
7. Upon ATC order to descend to FL030, pushed in ALT knob to engage descend by constraint.  A/C began to climb to 060 (alt constr back at D0/departure climb).
8. Reengaged OP DES to 030 until GS capture.
9. Land with ILS OK.

**Expected behavior**
A/C should follow the FPL as entered in MCDU and maintain proper altitude constraints in FPL at each step if asked to by pilot (where appropriate).  A/C should know where it is in the FPL and never return to a prior point or constraint (always looking for the next).

**Actual behavior**
Flight after flight, almost 100%, the A/C ignores the FPL once beginning descent and at some point turns back to origin AND/OR towards RWY (as is known in the default Asobo A/C).  A/C should always follow the FPL as loaded unless pilot commands otherwise.

**References**
N/A

**Additional context**
This was supposedly fixed by a prior PR but it still is failing (although some issues have been resolved re: redrawing on MFD, etc).

Was this working before/when did the issue start occurring?
Yes, prior to other changes being made (although I cannot pinpoint _which_ update broke this).  Was close to time EFB was activated (although may not be related at all).  Not long ago, the ONLY issue with incorrect turning was RWY turn.

Is this a problem in the vanilla unmodded game?
RWY turn supposedly is, but this other issue is new w/o Asobo update so I assume no.

DFWSupertrooper

I know this may be a duplicate/known issue wrapped up in other issues but I cannot find notes regarding this issue anymore so this specific issue may be unreported or it is incorrectly believed to have been fixed.

**Comment by DFWSupertrooper** [comment] 2021-02-13 16:10
May be part of #3441 (just located)...but this specific behavior wasn't recorded therein.  This exact behavior is what is consistently occurring (I don't see any of the wild loops or other random behavior).  You may want to merge these issues or treat them as separate since the behaviors reported are similar types but not the same.

**Comment by evpoppel** [comment] 2021-02-14 14:37
I have experienced sudden left turning upon adding star in arrival. Kept left turning. Also a waypoint "usr"  appeared in the flightplan. Simbrief route on vatsim. Eham to egkk. On course to [DECEL]. Maybe the issue is related there. The auto waypoint ??

**Comment by DFWSupertrooper** [comment] 2021-02-15 12:50
In my case, the auto waypoints, while sometimes annoying don't seem to be related.  My incorrect procedure occurs between planned waypoints generally (the A/C turns towards another waypoint not in my route or back to the beginning of the entire FPL).  Mine is also happening with no en route changes to the MCDU (FPL is as was loaded from MSFS and checked for accuracy - 100% matches my intent except for the added departure waypoints and transition waypoints MSFS inserts).

**Comment by AirKoKaine** [comment] 2021-02-17 05:42
> May be part of #3441 (just located)...but this specific behavior wasn't recorded therein. This exact behavior is what is consistently occurring (I don't see any of the wild loops or other random behavior). You may want to merge these issues or treat them as separate since the behaviors reported are similar types but not the same.

Same issue on my flight with Development 997c3c8 Version

**Comment by DFWSupertrooper** [comment] 2021-02-17 14:56
Just had a flawless flight EGKK-EGPH.  Using FBW Custom D/L this morning.  Will continue to fly to see if this was isolated or if there's been significant improvement.

**Comment by DFWSupertrooper** [comment] 2021-02-17 17:18
Using e14f741 just had 2nd perfect flight.  This one EGNT-LIML with RNAV approach 18.  Everything went absolutely perfectly.

**Comment by lve0200** [comment] 2021-02-18 11:51
Probably 2b seen together w/ #3445. Latest experimental as of 17. Feb. Flight into EDDH ILS RWY 15 (same as b4 ILS RWY 23.
The MCDU appears loosing the APP info. Plane turns left or right, RAD ILS info is lost. Going into FPL and setting again the APP info, restores a proper APP info and the plane recovers the APP path.
Probably ( wild speculation!) something w/ geo-data. I observed that geo data of EDDH has changed; Yellow taxi strips are misplaced and fuel truck hose drops below surface. May be theres a gap between APP geo and APT geo data.

**Comment by DFWSupertrooper** [comment] 2021-02-21 18:52
https://github.com/flybywiresim/a32nx/issues/3609#issuecomment-782862966

Adding this here for quick reference.  This is related to #3609.  Issue continuing after latest D/L FBW Custom yesterday and earlier this morning.  Thx.

**Comment by 2hwk** [comment] 2021-11-21 07:14
Fixed by 4953 closing ☑️

**Closed by 2hwk** 2021-11-21 07:14 UTC
Labels: Bug, Autoflight, FPM, fixed in cFPM
