### ISSUE TITLE
[BUG] Displays show self-test when spawning in on runway (i.e. ready for takeoff)

### ISSUE THREAD

**Issue by mythicfci** [flybywiresim/a32nx#456] opened 2020-09-06 16:42 UTC
**Mod Version**
Commit `dd07b4f`

**Describe the bug**
All the LCD cockpit displays undergo self-test when spawning in on runway.

**To Reproduce**
1. Spawn in on any runway.

**Expected behavior**
The aircraft should be fully configured for takeoff, with all LCD screens on and ready.

**Actual behavior**
All the LCD cockpit displays will display the "SELF TEST IN PROGRESS / MAX 40 SECONDS" screen, as if starting from cold & dark. (Note: my first time trying this, all the screens did a self-test; the second time, when I filmed it, the NDs were okay)

**Comment by UncleClapton** [comment] 2020-09-06 16:45
Duplicate of #448 

Please search for your issue before submitting it next time.

**Closed** 2020-09-06 16:55 UTC
Labels: bug
