### ISSUE TITLE
[BUG] Blue haze over displays

### ISSUE THREAD

**Issue by AbitEncrypted** [flybywiresim/a32nx#3897] opened 2021-03-10 15:10 UTC
**Mod Version**
  "built": "2021-03-10T10:03:43+00:00",
  "ref": "master",
  "sha": "3524c1756717803cdc4302fb7d4b349dccf42fc2",
  "actor": "myselfaaryan",
  "event_name": "manual"

**Describe the bug**
Encountered DARK DISPLAYS AFTER 1.14.5 update so installed developer version. Now all displays, FD, ND ECAM have a blue haze/hue that makes them difficult to read.

**To Reproduce**
1. Overwrite stable version with developer version. Start flight and all displays have a blue hue/haze to them.
2.
3.

**Expected behavior**
Crisp clear displays

**Actual behavior**
FD,ND ECAM displays have a blue haze/hue

**References**
I will provide a screen shot as soon as XBOX LIVE allows further logins.

**Additional context**
None

Was this working before/when did the issue start occurring? Worked before. Happens after installing developer version.

Is this a problem in the vanilla un-modded game? No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2021-03-10 15:12
Please provide a screenshot and fill the entire template

**Comment by AbitEncrypted** [comment] 2021-03-10 15:50
<img width="1135" alt="Blue Haze" src="https://user-images.githubusercontent.com/38859244/110656908-4d8d3f00-81b8-11eb-8bbf-382a0343551b.PNG">
Knobs at full

**Comment by AbitEncrypted** [comment] 2021-03-10 15:58
Not sure why this was closed it is an outstanding issue

**Comment by AbitEncrypted** [comment] 2021-03-10 16:00
Please reopen

**Comment by Benjozork** [comment] 2021-03-10 16:13
This is intentional and confirmed to be realistic by Airbus pilots.

**Comment by AbitEncrypted** [comment] 2021-03-10 16:20
Ok, obviously introduced in the new developer version.  Just brought it up because there was a major change from the previous version. Just one last comment.  The cockpit as a whole has a kind of blue hue to it too. The grey has become muted.
Happy to accept it if this is closer to real life.
Big thank you too all the developers that have burnt midnight oil on the A320

**Comment by MisterChocker** [comment] 2021-03-10 16:52
Closing since working as intended.

**Closed by MisterChocker** 2021-03-10 16:52 UTC
Labels: Bug, Working as Intended
