### ISSUE TITLE
Top of descent indication on ND is wrong

### ISSUE THREAD

**Issue by nabil74** [flybywiresim/a32nx#436] opened 2020-09-06 01:34 UTC
**Mod Version**

The latest master mod. (downloaded as of 10:30am Sunday morning AEST

**Describe the bug**
Top of descent white icon on ND is showing on flight plan before the top of climb.
This is incorrect.
Once you approach thetop of climb forecasted point the top of descent location gets updated to show correctly see image 2 below. 
However it shouldnt show before the top of climb at all.

**To Reproduce**
After entering correct flight plan into fmc
including sid and waypoints (melbourne to sydney)
View the ND flight plan and top of descent is shown incorrectly before the top of descent

Correct top of descent only shown once Star procedure entered into FMC.

**Expected behavior**
The top of descent should be calculated based on the flight plan and should show after the top of climb.
Top of descent should show correctly all the time and not once you get close to top of climb,.

**Actual behavior**
See images below.

**References**

![toc](https://user-images.githubusercontent.com/70311304/92316217-42ecc400-f034-11ea-9b16-f80c3cce9a62.JPG)
The top of descent icon is shown before the top of climb in this picture. This is wrong.

![top correct (mid flight)](https://user-images.githubusercontent.com/70311304/92316323-94498300-f035-11ea-8b63-2eeba254482a.JPG)
Here the top of descent updates to correct location just before culin.

**Additional context**

**Comment by ThePilot916** [comment] 2020-09-06 04:32
@nabil74 Could you check what is the altitude constraint on the waypoint coming up ahead(or the altitude set by MCDU for that waypoint? If its lower than your current altitude, there is no issue with it. TOD is being calculated with the next waypoint's altitude target(if you are higher than that altitude, it'll set a new TOD to ensure you are at lower planned altitude at that waypoint).

Can you please try and replicate the issue, with F-PLN page from MCDU image attached too?

**Comment by nabil74** [comment] 2020-09-06 08:35
Sure ill test again shortly.0

**Comment by nabil74** [comment] 2020-09-06 09:24
Retested.
Dosel altitude constraint was 4000ft. 
Autopilot doesnt honour constraints on fmc so i was flying over constraint alt without knowing it..

**Comment by nabil74** [comment] 2020-09-06 09:26
![tod2](https://user-images.githubusercontent.com/70311304/92322811-d21acb80-f076-11ea-84d2-b006a8e68eb2.JPG)

**Comment by ThePilot916** [comment] 2020-09-07 08:06
Looks like your CDU F-PLN has no altitude set for any of the waypoints.

**Comment by nabil74** [comment] 2020-09-08 05:46
Please all note the following!

When using built in flight plan from FS2020.. altitudes are shown on MCDU
However when entering flight plan manually (manual waypoints) into the MCDU altitudes dont get calculated in the MCDU or shown.

the Top of decent and climb should be calculated by the MCDU based on entered info.
I believe its a combination of MCDU waypoint entry issues togethre with how the TOD and TOC are calculated and shown.

**Comment by derl30n** [comment] 2022-04-09 23:50
Duplicate of https://github.com/flybywiresim/a32nx/issues/307

**Closed by derl30n** 2022-04-09 23:50 UTC
Labels: Request, ND, FPM, FMS - Predictions
