### ISSUE TITLE
[BUG] FMA goes from G/S to CLB/ALT mode when disconnecting AP

### ISSUE THREAD

**Issue by veikkos** [flybywiresim/a32nx#878] opened 2020-09-25 21:37 UTC
**Mod Version**

master

**Describe the bug**

FMA goes from G/S to CLB/ALT when disconnecting AP during ILS approach.

![kuva](https://user-images.githubusercontent.com/24453333/94317864-e116de80-ff8f-11ea-8bb8-98b821b9a928.png)

**To Reproduce**

1. Fly ILS approach
2. Catch LOC and G/S
3. Disarm AP

**Expected behavior**

FMA should stay at G/S mode.

**Actual behavior**

FMA goes to CLB mode with ALT armed

**References**

Aerosoft A320 on Prepar3D.

**Additional context**

*Was this working before/when did the issue start occurring?*
As long as I can remember but not sure.

*Is this a problem in the vanilla unmodded game?*
Don't know.

Discord username (if different from GitHub): VeGe-#4631

**Comment by AdenFlorian** [comment] 2020-09-25 21:41
This is caused by the autopilot APPR mode being disengaged automatically for some reason, which also happens in vanilla, just did a bunch of testing and looking at code around this.

**Comment by AdenFlorian** [comment] 2020-09-25 21:43
duplicate of #146

**Closed by AdenFlorian** 2020-09-25 21:43 UTC
Labels: bug, bug-vanilla
