### ISSUE TITLE
[BUG] Can`t reach the arrival chose page due to "NOT IN DATBASE" line after click on dest. icao (UUDD) on the F-PLN page.

### ISSUE THREAD

**Issue by AdmiralArtemiy** [flybywiresim/a32nx#2258] opened 2020-12-06 11:55 UTC
v. 0.4.2

Bug describing:
Can not type the arrival and approach data (selecting rnw and type of approach, etc,) due to when I press the mcdu button of the destination airport (UUDD) on the F-PLN page I catch the line "NOT IT DATEBASE" in input line, so I can not reach the arrival choose page and approach setupping page after it.

Steps for reproduce:
1. Click F_PLN button.
2. Click the button near the destination airport ICAO code, in my case - UUDD.
3. Read the line "NOT IN DATEBASE" on the input line of the MCDU.

Expected:
At the F-PLN page after clicking the button near the destination airport icao code (UUDD) you are able to click on the "ARRIVAL" section to choose the RUNWAY to land with the approaching type.

Actual:
When I press the mcdu button of the destination airport (UUDD) on the F-PLN page I catch the line "NOT IT DATEBASE" in input line, so I can not reach the arrival choose page and approach setupping page after it.

Was this working before/when did the issue start occurring? - After I installed it yesterday and tried to practice the ILS approaching.

Is this a problem in the vanilla unmodded game? - NO.

Discord username (if different from GitHub): ArtemiyVa#8733

**Comment by Benjozork** [comment] 2020-12-06 15:21
Duplicate of #1378

**Comment by MisterChocker** [comment] 2020-12-31 04:47
closing due to duplicate and outdated mod version

**Closed by MisterChocker** 2020-12-31 04:47 UTC
Labels: Bug
