### ISSUE TITLE
[BUG] Throttle stuck at climb 

### ISSUE THREAD

**Issue by dgianne1** [flybywiresim/a32nx#1643] opened 2020-10-30 19:27 UTC
**Mod Version**
Master

**Describe the bug**
When flying if the throttle goes above CLMB it will not go back down below that to auto or idle on ecam. 

**To Reproduce**
I have had this happen the last two times after the 1.10.7 patch. Push the throttle above auto

**Expected behavior**
Throttle should go to auto or idle when lowered 

**Actual behavior**
Throttle sticks at CLMB and will not go to auto or idle. Even after breaking to a stop plane will begin to roll on ground after landing

Was this working before/when did the issue start occurring?
10.1.7 update. 
Is this a problem in the vanilla unmodded game?
Have not had a chance to try it yet

**Comment by MisterChocker** [comment] 2020-10-30 22:45
Thats not a bug, it's called engine thrust rating mode.

**Comment by dgianne1** [comment] 2020-10-30 22:53
Thanks for the explanation. I was a little confused. Even when landing and the throttle all the way down I was still gaining speed when taxing

**Comment by MisterChocker** [comment] 2020-10-30 23:07
np you're welcome! Please join our discord for questions like that!

**Comment by Benjozork** [comment] 2020-10-30 23:30
Closing as question resolved.

**Closed** 2020-10-30 23:30 UTC
Labels: Bug
