### ISSUE TITLE
Wrong approach tuned.

### ISSUE THREAD

**Issue by solarisfire** [flybywiresim/a32nx#4729] opened 2021-05-06 17:33 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-06T07:02:50+00:00",
  "ref": "master",
  "sha": "73ed584d7be313f72b2869618582d8af77fca1e0",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Loaded ILS01Z approach at BIKF. Route loaded fine on the ND, however, the ILS tuned to the freq for ILS RWY10...

![image](https://user-images.githubusercontent.com/420952/117340628-001c0e00-ae99-11eb-909f-3ca670d1698c.png)

### Expected behavior

The ILS should have tuned for RWY01.

### Steps to reproduce

Fly to BIKF, example route:

EGPH/24 GOSAM1C GOSAM DCT GOW DCT BRUCE DCT GOMUP DCT BREKI DCT BASLU BASLU3N BIKF/01

![image](https://user-images.githubusercontent.com/420952/117340999-7fa9dd00-ae99-11eb-9c92-5f40959968d5.png)

Select the ILS01Z approach in the FMGS.

Fly the approach.

### Discord Username (optional)

solarisfire#0001

**Comment by MisterChocker** [comment] 2021-05-06 17:42
Because the issue is loading very slow here a screenshot with the important info marked

![image](https://user-images.githubusercontent.com/1857322/117342132-28106f00-aea3-11eb-8171-9975d88eaa37.png)


Looking at your ND, the ILS 10 approach has been programmed, this is what the PFD also shows.

Closing since working as intended.

**Comment by solarisfire** [comment] 2021-05-06 19:24
You can clearly see at 2 other points on the ND it says RWY01 and the nav path is leading to 01. I need to retest.

**Comment by solarisfire** [comment] 2021-05-06 20:09
Just redid the approach...

![image](https://user-images.githubusercontent.com/420952/117359399-42e8e080-aeaf-11eb-8f26-392823a39652.png)

I'd very much like this reopened @MisterChocker

**Comment by MisterChocker** [comment] 2021-05-07 03:11
That was not visible on the image your provided first

**Comment by solarisfire** [comment] 2021-05-07 08:13
So is this being reopened or am I raising another bug as it's clearly an issue?

**Comment by sidnov** [comment] 2021-05-07 20:39
Are you using Navigraph MSFS Beta by any chance?

**Comment by solarisfire** [comment] 2021-05-07 20:56
Yes I am. Navigraph AIRAC cycle 2104 rev. 1.

**Comment by sidnov** [comment] 2021-05-07 20:58
Is the issue reproducible without the Navigraph data? I have personally had such issues where wrong frequencies get tuned with Navigraph Beta. 

If it doesn't occur without it, I think you can report it to Navigraph.

**Comment by solarisfire** [comment] 2021-05-07 21:07
I'll have to retest the BIRK to BIKF flight with the approach plugged in, will do that next chance I get.

**Comment by solarisfire** [comment] 2021-05-08 09:55
@sidnov - Tested with Navigraph fully removed...

It's still an issue.

![image](https://user-images.githubusercontent.com/420952/117535034-d0c9e600-afeb-11eb-8d14-84df97909228.png)

The approach shown at the top of the ND is different, but it's still RWY10 and not RWY01.

**Comment by tracernz** [comment] 2021-05-08 10:16
The text shown at the top of the ND is the name of the ILS being received. The (borked) autotune code looks through the frequencies for the destination airport looking for the first one that contains the selected runway. For runway 1 it's looking for the first frequency containing 1 in the name, so if "ILS RWY10" appears first in the navdata it will be tuned. I have new logic that fixes this and the other issue where autotune fails to tune the ILS at all, but I'm not sure when I'll have time to work on it again.

The current logic:
```js
const frequency = airportInfo.frequencies.find(f => {
    return f.name.replace("RW0", "").replace("RW", "").indexOf(approach.runway) !== -1;
});
```

**Comment by sidnov** [comment] 2021-05-08 14:17
@solarisfire Thanks for testing it again with those conditions, quite sure tracernz is onto something😄

**Closed** 2021-06-11 22:28 UTC
Labels: Bug, MCDU, Reproduced
