### ISSUE TITLE
[BUG]  CTD when Init request start on YSSY

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#2911] opened 2021-01-06 18:53 UTC
**Mod Version**

2021-01-06T07:07:41+00:00

**Describe the bug**

Crash to desktop when init request and with SimBrief route: DEENA7 WOL H65 RAZZI Q29 LIZZI LIZI8A

With others airports, it’s works fine, only on YSSY, I have a CTD when I press INIT REQUEST

**To Reproduce**

1. Define SimBrief route. YSSY DEENA7 WOL H65 RAZZI Q29 LIZZI LIZI8A YMML
2. Start on YSSY parking
3. Init with SimBrief: when Init request is pressed, I have Crash To Desktop

**Expected behavior**

No CTD

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment] 2021-01-06 18:57
Do you have any other mods installed?

**Comment by igormagun** [comment] 2021-01-06 19:00
I have run into this exact issue, just haven't had the time to put together a full bug report. Do you have Navigraph AIRAC data installed? In my testing it seems to only happen with Navigraph's AIRAC data installed. 

Specifically, it seems to occur when WOL is added as a waypoint after YSSY, before entering a departure - I tried adding the flightplan manually and that gave me a CTD.

**Comment by JLD95** [comment] 2021-01-06 19:02
Yes I have Navigraph 2014 rev2

**Comment by Benjozork** [comment] 2021-01-06 19:04
Can someone attempt this:

1) in the default A320
2) in another aircraft

And report back ?

**Comment by MisterChocker** [comment] 2021-01-06 19:09
Working without navigraph.

**Comment by igormagun** [comment] 2021-01-06 19:20
> Can someone attempt this:
> 
> 1. in the default A320
> 2. in another aircraft
> 
> And report back ?

Had some time to spare so I tried entering the flightplan manually in:

1. The default A320
2. The default 747

And both times it also crashed when entering WOL as the first waypoint, before selecting a departure. Might be safe to assume this is a Navigraph problem.

**Comment by JLD95** [comment] 2021-01-07 07:30
Problem report to Navigraph, waiting for their response  [https://forum.navigraph.com/t/yssy-depart-ctd/3856](url)

**Comment by Watsi01** [comment] 2021-01-07 08:00
This could also be a simconnect issue. Is Navigraph using simconnect?

**Comment by JLD95** [comment] 2021-01-07 08:09
When new AIRAC cycle is available, we can use Navigraph beta tool in order to create a directory Community\navigraph-navdata
These data are available for later flights with using simconnect.

**Comment by tracernz** [comment] 2021-01-07 08:18
Navigraph Simlink uses SimConnect to report the aircraft position back to Navigraph for the moving maps functionality in the charts clients. I tried without that and still get the CTD. I get the CTD with or without A32NX and on the Cessna 172 as well (didn't try any others but I expect it will be all aircraft). Added a repro to the Navigraph thread.

**Comment by JLD95** [comment] 2021-01-07 08:23
Thank you Michael for the report on Navigraph thread

**Comment by Watsi01** [comment] 2021-01-07 08:28
@tracernz Could you try with any AI traffic turned off in the sim? Just to find the issue here.

**Comment by JLD95** [comment] 2021-01-07 08:49
I never used AI traffic, only AI with IVAO, but at CTD, IVAO was not connected

**Comment by tracernz** [comment] 2021-01-07 09:06
@Watsi01 Also occurs with no AI or live traffic.

**Comment by Watsi01** [comment] 2021-01-07 09:22
@tracernz  Ok. Thanks. It seems to be a Navigraph issue with @JLD95. But you said it also happens without NG? Do you use any addon scenery in that area? Do you have/use any other mod or external tool?

**Comment by tracernz** [comment] 2021-01-16 10:14
[This is confirmed fixed](https://forum.navigraph.com/t/yssy-depart-ctd/3856/18) by @JLD95 in navigraph cycle 2014 Rev 3.

**Comment by MisterChocker** [comment] 2021-01-16 13:26
> cycle 2014 Rev 3.

Seems to be a pretty old cycle tbh.

**Comment by JLD95** [comment] 2021-01-16 13:34
I confirm that last Airac 2014 rev3 solves the issue

**Comment by MisterChocker** [comment] 2021-01-16 13:46
Closing on op's request.

**Closed by MisterChocker** 2021-01-16 13:46 UTC
Labels: Bug, Bug-Vanilla, Flight Plan
