### ISSUE TITLE
QNH blinking even below TRL

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#3992] opened 2021-03-15 17:53 UTC
**Mod Version**

Dev 2021-03-15T102212

**Describe the bug**

QNH blinking seems linked with approach phase and not the specified TRL as before. For example In USA, TRL is egal to FL180 . So when I switch baro to QNH mode at TRL, I have QNH blinking until I activate Appr phase.

**To Reproduce**

1.  In USA or Japan for example, I specifiy TRL at FL180 
2. During descent when aircraft altitude is below TRL, I switch baro to QNH value but I don't active APPR phase because I'm still far from the destination airport
3. QNH value is blinking in PFD until APPR phase is activated

**Expected behavior**

Like previous mod versions, QNH blinking when baro remains on STD position and when altitude is below specified TRL

**Actual behavior**

QNH blinking when baro is on QNH position and when altitude is below specified TRL

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Kimbyeoungjang** [comment] 2021-03-16 03:20
This will fix on my pr. Sorry about that bug

**Comment by AirbusA320Pro** [comment] 2021-03-16 13:09
@Kimbyeoungjang I was going to report this as a similar bug, but in the climb. When STD is pushed below Transition Altitude when climbing to a FL from an altitude, STD flashes until the a/c has flown through Transition Altitude. In real life, during the climb it won't flash under those circumstances.

**Comment by Kimbyeoungjang** [comment] 2021-03-16 13:31
> @Kimbyeoungjang I was going to report this as a similar bug, but in the climb. When STD is pulled below Transition Altitude when climbing to a FL from an altitude, STD flashes until the a/c has flown through Transition Altitude. In real life, during the climb it won't flash under those circumstances.

after IRL pilot confirm and document, will fix that. 
thank you for reporting!

**Comment by AirbusA320Pro** [comment] 2021-03-16 13:33
@Kimbyeoungjang I am a real-life pilot (Discord username AirbusA320Pro for confirmation)

**Comment by Kimbyeoungjang** [comment] 2021-03-16 13:52
> ![STD Altimeter](https://user-images.githubusercontent.com/75289637/111319455-ed861500-865d-11eb-828c-ad96a1f096c6.jpg)
> @Kimbyeoungjang apologies for the poor screenshot, I can't screen grab off this particular device. But this FCOM reference describes the appropriate behaviour. 

What a nice document! Thank you for reference!! I'll fix that.

**Comment by Kimbyeoungjang** [comment] 2021-03-16 13:58
@AirbusA320Pro

I fix it on #3762 ! 

thank you :)

**Comment by JLD95** [comment] 2021-03-20 17:59
Hi,
with "built": "2021-03-19T15:20:50+00:00", I still have the bug. I made a flight with a TA 11000ft at climb and a TRL FL080 at descent. During descent, when FL is below FL110  QNH is blinking , so the TRL080 is not taken into account.

**Comment by Kimbyeoungjang** [comment] 2021-03-20 23:59
> Hi,
> with "built": "2021-03-19T15:20:50+00:00", I still have the bug. I made a flight with a TA 11000ft at climb and a TRL FL080 at descent. During descent, when FL is below FL110 QNH is blinking , so the TRL080 is not taken into account.

Not fixed yet. Please wait until merged.

**Comment by MisterChocker** [comment] 2021-05-15 17:14
Duplicate of #3293

**Closed by MisterChocker** 2021-05-15 17:14 UTC
Labels: Bug, PFD
