### ISSUE TITLE
[BUG] Engines can be started without engine selector knob in IGNITION mode

### ISSUE THREAD

**Issue by wpine215** [flybywiresim/a32nx#473] opened 2020-09-07 04:57 UTC
**Mod Version**

Master

**Describe the bug**

Engines can be started without engine selector knob in IGNITION mode

**To Reproduce**

1. Keep engine selector in normal mode
2. Bring either engine cutoff switch to "ON." Engine should start as usual.

**Expected behavior**

Engines should only start when in IGNITION mode.

**Actual behavior**

Engines can start in any mode.

**Comment by Coralec** [comment] 2020-09-07 05:49
The ability to inhibit the engine startup should be in the code already. For example, if you fail to turn on the fuel pumps then the engine startup sequence will stall.

**Comment by Inaxair** [comment] 2020-09-14 12:08
has this been resolved yet?

**Comment by lousybyte** [comment] 2020-10-09 19:40
Duplicate of #254

**Closed by lousybyte** 2020-10-09 19:40 UTC
Labels: Bug, Bug-Vanilla, Good First Issue
