### ISSUE TITLE
[BUG] AP not following flight plan (again) after WU3 update

### ISSUE THREAD

**Issue by LH4371** [flybywiresim/a32nx#3602] opened 2021-02-18 12:08 UTC
**Mod Version**
latest dev mod from the installer

**Describe the bug**
When enabling the autopilot the plane starts after some minutes to enter a deadful spin in 75% of all cases. Happens sometimes also later during the flight.

**To Reproduce**
1. Load flight plan, e.g. via Simbrief
2. Enable Managed Heading
3. Enable Managed Altitude to e.g. FL320
4. After t/o enable AP master

**Expected behavior**
Airplance follows LNAV and VNAV per MCD information; did this for many weeks / dev versions before last MS Update of WU3

**Actual behavior**
Plane enters into steep banking, primarily to the left, ultimately resulting in loss of altitude and excessive speed

**References**
none

**Additional context**
Disabling SEC1 under FLT CTL on the overhead works and AP behaves perfectly. Remember this workaround was recommended some weeks ago, too. So whatever you did back then to fix this AP issue would possibly be required again. Changes in controller (HOTAS X) were NOT made after the WU3 update. Controller deadzones were at 8% before, I increased them now to 13% but still no cure.

Discord username (if different from GitHub):

**Comment by FSC190** [comment] 2021-02-18 15:39
I can confirm this. On begin of the selected STAR it activates the first way point in the FP and turns toward it. I my case the first SID way point.

**Comment by MisterChocker** [comment] 2021-02-18 15:45
Duplicate of #3445

**Closed by MisterChocker** 2021-02-18 15:45 UTC
Labels: Bug
