### ISSUE TITLE
[BUG] Sharp Turns/Dives on AP 

### ISSUE THREAD

**Issue by jasonarmstrong87** [flybywiresim/a32nx#2836] opened 2021-01-01 20:02 UTC
**Mod Version**

**Describe the bug**

**To Reproduce**

1. No real pattern, flight plan inputted via Sim Brief integration. Flight loads up and runs perfectly smooth. 
2. AP activated, sometimes it works fine for 10-20 minutes, other times the dives happen immediately. 

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring? It worked prior to the new SIM update

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by jasonarmstrong87** [comment] 2021-01-01 21:21
Using -   "built": "2021-01-01T14:48:48+00:00", CFBW Mod

**Comment by jasonarmstrong87** [comment] 2021-01-01 23:49
I seem to have figured out what causes it. The second I connect with Vpilot the hard banking starts. If I disconnect flight seems to resume fine. Not sure if this is a coincidence but will continue trying that to see if it affects it.

**Comment by MisterChocker** [comment] 2021-01-01 23:57
Great discovery, I would appreciate the effort if you do some checks for consistency

**Comment by jasonarmstrong87** [comment] 2021-01-02 00:23
Sorry, spoke too soon. The moment the aircraft hit a waypoint requiring a left turn, it turned left uncontrollably.

**Comment by smmoses** [comment] 2021-01-02 20:20
I believe I am having the same issue. I take off successfully, but when I enable auto pilot, it levels out. I try setting the altitude, and then it just turns uncontrollably (even if there is not a turn yet on the flight plan) before going upside down and diving to the ground. I confirmed my barometer is set correctly, for what that is worth, and my flight plan, performance, etc is all set correctly. I am on stable 0.5.1

**Comment by jasonarmstrong87** [comment] 2021-01-02 20:54
I can confirm VPilot has no influence on this. the CFBW continues to do it. I will test the dev. version to see if it does it as well. 

As soon as I take off on my most recent flight on a turn the plane banked uncontrollably to the right. Works fine with autopilot off, though.

**Comment by jasonarmstrong87** [comment] 2021-01-02 21:29
Dev. Version does the same thing, Shortly after take off same behavior. Never had an issue until this past update, but have flown it successfully since 0.5.1 was released. This I did in between were modify my TCA throttle settings as described here:

https://github.com/flybywiresim/a32nx/tree/fbw/docs

Utilizing these settings:
[Throttle]
Log = true
Enabled = true
ReverseOnAxis = true
ReverseIdle = true
DetentDeadZone = 2.5
DetentReverseIdle = -0.90
DetentReverseFull = -1.00
DetentIdle = -0.42
DetentClimb = 0.06
DetentFlexMct = 0.53
DetentTakeOffGoAround = 1.00

@smmoses - Any similarity to what I have done as well?

**Comment by smmoses** [comment] 2021-01-02 22:37
@jasonarmstrong87 I am using the TCA sidestick, but am using the default throttle settings.

**Comment by weldrin** [comment] 2021-01-02 22:57
Have the same problem but I noticed that even when taxing aircraft is steering slightly to the right, then take off is normal but after engaging AP aircraft goes completely out of control with sharp bank to the right and sometimes even upside down and into the ground. Using version 0.51 and it worked fine previously.

**Comment by jasonarmstrong87** [comment] 2021-01-03 01:06
Same issue, with the dev version, when taxing out of nowhere the aircraft turns left (for me), have to course correct, goes straight for a bit and then starts turning left. Didn't see this behaviour on the CFBW.

**Comment by jasonarmstrong87** [comment] 2021-01-03 21:11
Continued testing, on stable (happens on CFBW/Dev as well). More info, the uncontrollable right turn happens as soon as the AP hits a waypoint that requires a right turn.

**Comment by nikitanyc** [comment] 2021-01-04 00:23
Try going to General>Flight Model>Legacy Mode. I'm not sure how or why, but that fixed it for me. 

Also, I'm in developer mode, and I read online that if you start off the runway it should fix it, but so far it works cold and dark and runway by using "legacy mode". Hope that helps.

**Comment by jasonarmstrong87** [comment] 2021-01-04 01:11
@nikitanyc Did you have to set up the Legacy mode before starting a flight? Saw this as I was testing a flight just as the autopilot was banking me uncontrollably. Went into the settings as you indicated, disconnect autopilot reconnecting but the aircraft continued out of control.

Any feedback on how you got it to work?

**Comment by heinrichlaubscher** [comment] 2021-01-04 09:16
I'm experiencing the exact same issue. Attaching a video to show the exact behaviour. 

I've tried both the stable and dev builds and it happens on both. I took off from FAOR, visible in the video. Take note of the chromoteter, 24min into the flight and I didn't really get that far. 

https://user-images.githubusercontent.com/11421164/103519274-ed0f1800-4e7d-11eb-96e9-1f3a6d962864.mp4

**Comment by ThatRedMelon** [comment] 2021-01-04 09:18
As you can see the flight directors are trying to correct the turn, but can't because of some inputs from your controller (even if it's not moving), the solution for this would be to up your deadzones for your controller. I'd recommend starting with 10% and working up until the problem ceases.

**Comment by heinrichlaubscher** [comment] 2021-01-04 09:32
> As you can see the flight directors are trying to correct the turn, but can't because of some inputs from your controller (even if it's not moving), the solution for this would be to up your deadzones for your controller. I'd recommend starting with 10% and working up until the problem ceases.

Thank you, much appreciated. I'll give that a go and give feedback on whether it helped or not.

**Comment by weldrin** [comment] 2021-01-04 13:09
My problem was fixed by adding 15% dead zone to controller. I can fly normally now.

**Comment by heinrichlaubscher** [comment] 2021-01-04 13:11
OK, so I recalibrated my controller and also set the deadzone to 10% as you recommended. Seems to have fixed the issue. Thank you :)

**Comment by jasonarmstrong87** [comment] 2021-01-04 17:56
I had it set to 10% and it was still doing it. I've changed it to 15% and seems to be flying ok, will report if it solves it or if it doesn't.

What hardware are you all using?

**Comment by nikitanyc** [comment] 2021-01-04 21:50
> @nikitanyc Did you have to set up the Legacy mode before starting a flight? Saw this as I was testing a flight just as the autopilot was banking me uncontrollably. Went into the settings as you indicated, disconnect autopilot reconnecting but the aircraft continued out of control.
> 
> Any feedback on how you got it to work?

Hey, so start MSFS and in the general options click on Legacy Mode. I did it as soon as the game loaded and it stays like that so you don't have to do it every time. I did three flights in the past two days KISP-KWBI, KEWR-KMIA, and KBDL to EIDW, and the problem is completely gone. Each time from the gate, cold and dark to ILS landing. 

Here is my setup:
Legacy Mode (all realism settings at 100)
Realism settings - all real (no AI comms delegation, etc.)
DATA - all on (live weather, multiplayer)
vPilot for VATSIM
A32NX
Logitech 3D Pro Joystick - all settings have been reset to default from an earlier attempt to fix this issue
jd-cockpit-livery-a320neo-black-black-creme (although I doubt this has anything to do with it)
Graphics settings - Custom, all medium, with volumetric clouds set to ultra (probably nothing to do with it either)

I've tried those three flights that I mentioned in Frontier, SWA, and Aer Lingus livery, everything works as expected. Before the AP would start randomly banking sharply to the left and basically going in circles. I would turn it off, level off the aircraft, and turn it back on but it would start banking during any phase of the flight.

**Comment by nikitanyc** [comment] 2021-01-04 21:52
> I had it set to 10% and it was still doing it. I've changed it to 15% and about 25-30 min into flight sharp turn time on autopilot. The video above is exactly what happens to me.
> 
> Other than the "dead zone" slider, what does everyone else have set up with the other settings?

While  I don't think it's simply the "Legacy Mode" that fixes this. I think it's a combination of legacy mode and joystick settings. Try to mess with the joystick settings as well and fly a bit, and then "reset to default". 
Like I said, it fixed the problem for me, but I have absolutely no idea how or why.

**Comment by jasonarmstrong87** [comment] 2021-01-05 20:56
Didn't solve it. If it's my TCA Sidestick settings I am unsure what to try as I've played with what I feel is everything.

**Comment by jasonarmstrong87** [comment] 2021-01-08 02:16
After further testing, I decided to test the A320 defult (I should have done that before wasting everyone's time). It did it again, the autopilot caused an rapid turn to the right. I went into the controller settings and set both TCA Side Stick and Throttle to 'default' and the autopilot immediately corrected itself. This leads me to believe it is something in my controller settings that is causing the problem. I honestly do not know how I will fix this, but at least Iknow it's not the Mod that is causing the problem.

**Comment by jasonarmstrong87** [comment] 2021-01-11 20:43
Hi all -

I wanted to share forward that I have resolved this issue on my end, but to be honest I am not sure what of the few things I did fixed it. I have done 3 successful flights with no indication of the issue at hand. Below are the steps I took/take and the issue seems resolved.

1) Removed ALL key assignments to flight surfaces. I think this is what did the trick. When remember when the issue started it seemed to correlate where I set up camera's on my keyboard to the number pad (ex NUM4 for left overwing view, NUM6 for right overwing view, NUM0 for cockpit etc). These keys were also set up to aileron and elevator control surfaces in my keyboard assignments. I deleted all of them so that the only way to control the aircraft would be with my TCA Sidestick. 

2) Test sidestick when taxiing (someone suggested this in some forum) but testing full ailerons, rudder, and elevators as you would in real life. Not sure if this does anything. 

3) Defaulted the settings with my TCA Throttle, though I don't think this has any impact. I will though, test out the settings in the GitHub A32x Mod to have the detents align with the throttle as I don't think this will affect anything

4) I thought I saw a pattern in adding/modifying STARs when in flight that caused the issue, but I have done two flights now, one where the STAR was not set up prior to take off and added mid flight and one with it set up prior to take off. I have also played around with DIRECT to modifications to the STAR and the issue hasn't happened. 

I hope this helps some of you, I went from not being able to do one flight to doing 3 with no issues.

**Comment by donstim** [comment] 2021-01-12 08:04
There are recommendations here to set the flight model to the "legacy" flight model. We do not support use of the legacy flight model. Although parameters in the flight model configuration file have been adjusted to try to better match the legacy flight model to the modern flight model, the legacy flight model does not support all features of the modern flight model. Both our mod and the vanilla Asobo airplane are designed with, and intended to be used with, the modern flight model.  The legacy flight model exists primarily to accommodate porting airplanes over from FSX.

**Comment by dkgolfnut5192** [comment] 2021-01-12 19:15
Did anyone else get relief from what Jason mentioned above?

**Comment by dkgolfnut5192** [comment] 2021-01-14 00:55
I ended up finding the dead zone in the sensitivity function in FS2020 and moved both the aileron and elevator dead zone to 15percent. That solved my issue and the plane followed the entire flight plan on two different flights to different airports.  So glad this is not turning uncontrollably any longer.  Now I can enjoy the great work you guys have been putting in to the mod.  Great work.

**Closed** 2021-04-23 22:06 UTC
Labels: Autopilot, Bug, Fixed in custom AP
