### ISSUE TITLE
[BUG] Simbrief - incomplete data import

### ISSUE THREAD

**Issue by AdamNZ** [flybywiresim/a32nx#2947] opened 2021-01-09 03:35 UTC
**Mod Version**

  "built": "2021-01-08T22:27:54+00:00",
  "ref": "",
  "sha": "",
  "actor": "pepperoni505 <49950581+pepperoni505@users.noreply.github.com>",
  "event_name": "manual"

**Describe the bug**

On a trip from NZAA to NZWN, Simbrief gives me the following routing:
LENG2P LIMES H384 KARRL Y506 TPAPA TPAP3B

When manually loading the plan in MSFS, all waypoints etc. are entered in the MCDU correctly.

However - when using Simbrief import, only LIMES shows up. This is after selecting only the DEP airport (NZAA) in the MSFS loading screen, as has been recommended. I'm guessing that's because AIRWAYS aren't (yet) supported ... but the waypoints either side of the airways should still be honoured <???>.

Trying to "mix and match" (as a test) - and pre-loading the .pln *and* setting up via the AOC menu, all waypoints remain in place but other data (CI and cruise level etc.) isn't added.

**To Reproduce**

1. Create a flight plan in Simbrief.
2. Download the plan (for testing purposes only).
3. Start the A320 cold and dark but selecting only the DEP airport from the main MSFS screen.
4. Check Simbrief options are OK.
5. Import the flight plan.
6. Do all the usual AOC steps.
7. Go to the INIT page and REQUEST the flight plan.

**Expected behavior**

Airways and waypoints should not be deleted/ignored.

**Actual behavior**

**References**

1) Start the flight with no ARR airport selected:
https://i.postimg.cc/6wQ3ZHtp/bug-01-no-pln.png

2) This is what happens:
https://i.postimg.cc/sVyfgmTy/bug-02-partial.png

3) When going to the INIT page, this is what happens:
https://i.postimg.cc/KGpmQ2xv/bug-03-mismatch.png

4) This is a TEST of the same Simbrief flight plan when loaded via the MSFS screen:
https://i.postimg.cc/rcYpNSw-C/bug-04-pln.png

5) ... which gives the full route:
https://i.postimg.cc/x9LTQhyt/bug-05-full-plan.png

6) ... except the CI and CRZ info isn't added (maybe not surprisingly):
https://i.postimg.cc/7HZxg6vW/bug-06-no-ci.png

7) Finally ... maybe I should file a sepearate report ... but there's a cosmetic layout problem on page2 of INIT FUEL PREDICTION ... double arrow\s:
https://i.postimg.cc/690W2ZPZ/bug-07-arrows.png

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Not applicable for the unmodded A320 ... and I haven't really played with Simbrief imports until now.

Discord username (if different from GitHub):

**Comment by oeed** [comment] 2021-01-09 05:29
Can confirm. I actually did this exact flight earlier today with the same route and only LIMES appeared.

Potentially it's due to an old AIRAC cycle on Simbrief? I couldn't find LENG2P in the SID list in the MCDU.

**Comment by kiokio0987** [comment] 2021-01-09 05:57
By changing the SID from "LENG2P" to "STEAL1P", "LIMES" has been placed in the middle of the route.
"LENG2P" is no problem in AIRAC 1903, but its SID is not in the latest AIRAC 2014.

NZAA/23L STEAL1P KARRL Y506 TPAPA TPAPA3B NZWN/16
![LIMES](https://user-images.githubusercontent.com/75520968/104084450-69449980-528a-11eb-90d1-928fd8ad80e1.jpg)

**Comment by AdamNZ** [comment] 2021-01-09 06:55
Thanks for trying this out! I don't have a Navigraph subscription, so will always have to use AIRAC 1903 for my Simbrief sessions. Is it a clash between Simbrief/AIRAC 1903 and whatever MSFS 2020 uses as default (not sure which cycle it uses)?

I'll have a go with STEAL1P and report back.

**Comment by kiokio0987** [comment] 2021-01-09 07:51
I'm not the creator of the mod, so I don't know the details.
The default for MSFS2020 complies with AIRAC 2014.
(As of 9 January 2021)

**Comment by Lucky38i** [comment] 2021-01-09 10:49
The simbrief import does not import SIDs and STARs. However for the remainder of the route we'll try and debug why this is happening

**Comment by MisterChocker** [comment] 2021-01-09 18:17
Looks like a duplicate of #2165

**Comment by AdamNZ** [comment] 2021-01-10 00:18
Yep ... agreed ... I'll follow #2923 instead, thanks ... so I suspect we can close this one off. Funny thing is that I did a search prior to adding this one and #2923 never came up.

**Comment by MisterChocker** [comment] 2021-01-10 02:39
Duplicate of #2923

**Closed by MisterChocker** 2021-01-10 02:39 UTC
Labels: Bug, Waiting For Response
