### ISSUE TITLE
Captain Side ND Non Responsive [BUG]

### ISSUE THREAD

**Issue by danbw9** [flybywiresim/a32nx#1128] opened 2020-10-06 01:38 UTC
**Mod Version**
Master downloaded 5 Oct 2020

**Describe the bug**
When starting from cold and dark. 
When spawning on the RWY, 

**To Reproduce**
Start from Cold & Dark To see what is visually given in my screenshot. Otherwise spawn on RWY to see the non response ND but it looks alright at a glance.

**Expected behavior**
To be just responding like the FO (This master includes the separate displays feature)

**Actual behavior**
Non responsive ND on Captain Side with red rings displayed as if the IRS is 'half aligning'.

**References**

![Screenshot (271)](https://user-images.githubusercontent.com/1753445/95149098-51d6ab80-0785-11eb-84a6-b657731c1e69.png)

![Screenshot (275)](https://user-images.githubusercontent.com/1753445/95149113-5f8c3100-0785-11eb-8039-3ba8fcb1d0c9.png)

Was this working before/when did the issue start occurring?
 
Was working before I changed to the master downloaded on 5 Oct. Before the separate displays are implemented, all was fine.

**Comment by 2hwk** [comment] 2020-10-06 03:53
Here's a relevant console dump:
![image](https://user-images.githubusercontent.com/15316958/95157057-98022e00-07ca-11eb-92b1-7ce32fa034c4.png)

**Comment by lawfulrocky** [comment] 2020-10-06 03:55
Same as #1106 issue

**Comment by Watsi01** [comment] 2020-10-06 11:10
I can confirm that problem > when switching on the ADF or VOR MFD/ND indicators (1 and/or 2) before ADIRS is aligned. Switching them off after alignement, brings ND back to normal again. Switching them on again > ND freeze. Have no problems when keeping the indicators off until ADIRS alignment is done.

**Comment by NathanInnes** [comment] 2020-10-06 16:52
Duplicate of #1071. Closing.

**Closed by NathanInnes** 2020-10-06 16:52 UTC
Labels: Bug, Bug-A32NX, ND (Navigation Display)
