### ISSUE TITLE
[BUG] Unreal night lighting in cockpit

### ISSUE THREAD

**Issue by javiiberia** [flybywiresim/a32nx#1908] opened 2020-11-14 01:07 UTC
**Mod Version**
4.1

**Describe the bug**
 When the cockpit is completely dim , the main screens , even in the darkest mode emit a bit of light wich is not real 

**To Reproduce**

1.
2.
3.

**Expected behavior**

The real ilumination.

![image](https://user-images.githubusercontent.com/74369531/99134054-a0952200-261c-11eb-951d-e04039b72680.png)

![image](https://user-images.githubusercontent.com/74369531/99134345-9162a400-261d-11eb-86fb-3325c7b7fcac.png)

The real ilumination.

**Actual behavior**
What the airplane shows in the "darkest mode"
Unreal light.

![image](https://user-images.githubusercontent.com/74369531/99134200-01245f00-261d-11eb-926e-c106af2acf9a.png)

![image](https://user-images.githubusercontent.com/74369531/99134412-ee5e5a00-261d-11eb-9365-3908bb44e251.png)

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment] 2020-11-14 01:10
Duplicate of #1300

**Closed by Benjozork** 2020-11-14 01:10 UTC
Labels: Bug
