### ISSUE TITLE
A32NX 6  and simbrief import

### ISSUE THREAD

**Issue by DieterKuep** [flybywiresim/a32nx#4466] opened 2021-04-17 12:28 UTC
**Mod Version**

```json
"built": "2021-04-15T21:44:03+00:00",
  "ref": "experimental",
  "sha": "d1026985aa101b317cc2ca0f2c710816a1d4dd06",
  "actor": "aguther",
  "event_name": "manual"
```

**Describe the bug**

after importing the simbrief plan and trying to get the sid (from dep airport) i get the msfs2020 freezing

**To Reproduce**

1.Importing the flightplan with fmc and Atsu - AOC- Init/Pres -AOC- Perf/W+B-Refuel - Payload
2.Init - Iniit Request - Freeze
3.

**Expected behavior**

Going on with fmc feeding

**Actual behavior**

MSFS2020 feezing

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment] 2021-04-17 14:27
Are you using Navigraph airac?
Do you have any other addons/mods or liveries installed?

**Comment by DieterKuep** [comment] 2021-04-17 16:49
Hi,
yes i am using navigraph data and also i use some 32nx liveries..

Von AOL Mobil gesendet
On Samstag, 17 April, 2021 DerL30N ***@***.***> wrote:



Are you using Navigraph airac?
Do you have any other addons/mods or liveries installed?

**Comment by DieterKuep** [comment] 2021-04-17 17:03
i forgot that CJ4 working title mod also in the comunity folder

**Comment by DieterKuep** [comment] 2021-04-18 08:08
Ok try a second time.
i am using navigraph data
also installed nx livveries and CJ4 working title mos

**Comment by MisterChocker** [comment] 2021-04-18 09:02
Please remove any other mods/addons and liveries and try again.

**Comment by DieterKuep** [comment] 2021-04-18 12:22
the error that leads to a crash does not always occur.
some flight plans are correctly registered and processed

**Comment by cchard360** [comment] 2021-04-18 14:56
Are you trying to fly through Northern Italy by any chance? I've had the game freeze for a couple minutes when importing: https://github.com/flybywiresim/a32nx/issues/4338   It usually unfreezes if you wait. Or you can uninstall the Navigraph beta data.

**Comment by DieterKuep** [comment] 2021-04-19 13:18
OK, that is possible...
imported flights with freezing actually work after a small waiting time is factored in..
So it`s Ok now for me
Thanks for these tips
greetings
Dieter

**Comment by MisterChocker** [comment] 2021-04-19 16:03
Duplicate of #4338

**Closed by MisterChocker** 2021-04-19 16:03 UTC
Labels: Bug, Waiting For Response
