### ISSUE TITLE
INIT B Page Not Accessable

### ISSUE THREAD

**Issue by warthog02** [flybywiresim/a32nx#2349] opened 2020-12-11 08:23 UTC
**Mod Version**

<  "built": "2020-12-10T04:54:58+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benedict Etzel <benedict@hearthsim.net>",
  "event_name": "manual"
} -->

**Describe the bug**
<The INIT B page is not accessible after pressing the left arrow on the keypad.>

**To Reproduce**

1. With the aircraft on the runway and all engines and systems running, enter data into the F-PLAN page.
2. Then check the SEC F-PLAN, RAD NAV and INIT pages again.
3. While on the INIT page, press the left arrow key.

**Expected behavior**
<The INIT B page should appear for filling in the ZFW, Total Fuel and CG data.>

**Actual behavior**
<A "NOT AVAILABLE" message appears at the bottom of the INIT A page instead>

**References**
<N/A>

**Additional context**
<N/A>

Was this working before/when did the issue start occurring?

This issue did not occur in the previous installed version (A32NX v4_1 (Master)

Is this a problem in the vanilla unmodded game?

This problem occurred after the installation of the "Xmas" aircraft and before the installation of MSFS update 1.11.7.0

<Not a Discord user>:

![INIT B Page Inaccessible](https://user-images.githubusercontent.com/75111955/101879583-85421600-3bcc-11eb-99f6-4aa235246fe2.JPG)

**Comment by Lucky38i** [comment] 2020-12-11 09:37
This is intended behaviour, please use the FUEL PRED page. INIT B cannot be used once engines are turned on.

**Comment by AirbusA320Pro** [comment] 2020-12-11 11:01
This is correct behaviour IRL. INIT B can only be accessed prior to engine start. As stated above, changes to ZFW/ZFWCG can be modified through the FUEL PRED page only.

**Comment by warthog02** [comment] 2020-12-11 11:40
I tried to enter the ZFW, CG and Fuel Weight on the FUEL PRED page but all could not be entered.

**Comment by Lucky38i** [comment] 2020-12-11 12:54
> I tried to enter the ZFW, CG and Fuel Weight on the FUEL PRED page but all could not be entered.
> See
> #2296

This is being fixed in #2251

**Comment by Benjozork** [comment] 2020-12-11 14:45
Continuing with #2296

**Closed by Benjozork** 2020-12-11 14:45 UTC
Labels: Bug
