### ISSUE TITLE
CTD when pressing Print button on MCDU 

### ISSUE THREAD

**Issue by Kurtsrodz** [flybywiresim/a32nx#5505] opened 2021-08-01 19:26 UTC
### Aircraft Version

Development

### Build info

```json
"built": "2021-08-01T07:00:26+00:00",
  "ref": "master",
  "sha": "5a19f07b56ca9ef74916f2ff9532aa72a02ba6f9",
  "actor": "Benjozork",
  "event_name": "manual"
```

### Describe the bug

PRINT function on MCDU caused a brief pause (freeze) then CTD

### Expected behavior

I expected the Printer to print and not CTD instead

### Steps to reproduce

1. Pull in a OFP (simbrief) on the MCDU
2. Go to AOC on the MCDU to get the METAR and ATIS info 
3. Select MESSAGES and then the METAR message then press PRINT on the LSK
4. CTD

**Comment by Benjozork** [comment] 2021-08-01 19:48
Duplicate of #5429

**Closed by Benjozork** 2021-08-01 19:48 UTC
Labels: Bug
