### ISSUE TITLE
[BUG]Page DES (MCDU) does not activate

### ISSUE THREAD

**Issue by Gian85** [flybywiresim/a32nx#825] opened 2020-09-23 23:00 UTC
**Mod Version**
Master

**Describe the bug**
When flying in OP des or DES the DES page of the MCDU is not activated

**To Reproduce**

1. begins descent ( OP des or DES)
2.Page DES doesn't activate
![Immagine](https://user-images.githubusercontent.com/71722110/94082495-5c965580-fe01-11ea-987a-970a4a5827e5.png)

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by lawfulrocky** [comment] 2020-09-24 02:18
Right now MDCU is being work on from ground up so don't know when it will be finish

**Comment by Ares1378** [comment] 2020-09-24 04:17
I am confused it shows the DES page on the MCDU in the Screenshot you showed

**Comment by Gian85** [comment] 2020-09-24 09:47
the page that I showed DES must be in green when activated (it stays in white), then the speed remains that of cruising instead of being that of descent. Yes I set the right cruising altitude.

**Comment by waredrive** [comment] 2020-09-24 11:01
I've noticed the same is happening for me. Tried it several times  to be sure and the DES phase never activates (stays on cruise).

**Comment by MattPaxtonBel** [comment] 2020-09-24 12:12
Same here, DES phase is never activated (you can see that the title of the page remains in white and the <-Prev phase (CRUISE) LSK is still present). Consequences are, managed DES speed is not used when leaving ALT CRZ and when you step descent following ATC instructions, each step altitude is considered as ALT CRZ on the FMA iso ALT.

**Comment by AdenFlorian** [comment] 2020-09-24 19:55
when did this issue start occurring?

is this a problem in the vanilla unmodded game?

**Comment by Gian85** [comment] 2020-09-24 20:15
i saw this two days ago and reported the problem ... i don't know if it's an old problem

**Comment by AdenFlorian** [comment] 2020-09-24 20:20
im starting work on this now

**Comment by AdenFlorian** [comment] 2020-09-25 03:38
duplicate of #444

**Closed by AdenFlorian** 2020-09-25 03:38 UTC
Labels: bug

**Comment by Ares1378** [comment] 2020-09-25 03:43
My apologies I was half asleep when I looked at that and after testing it can confirm the issue and it is being worked on by @AdenFlorian
