### ISSUE TITLE
 [REQUEST] [Just want the RAM air turbine to work.] (Just tell me if you guys are working on it-)

### ISSUE THREAD

**Issue by X-PetRussian-X** [flybywiresim/a32nx#2018] opened 2020-11-19 19:37 UTC
**Is your feature request related to a problem? Please describe.**

**Kinda want the RAM air turbine to work, i cant do realistic DUAL ENGINE FAIL scenario's because i have to turn on the APU without the RAM turbine.**

**The ram air turbine usually boots automatticly as soon as both engines stop sending power to the aircraft, like when they both fail. The button for the MAN ON under the RAM air turbine is clickable, but does nothing.**

**Additional context**

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-11-19 19:45
Duplicate of #1668

**Closed by Benjozork** 2020-11-19 19:45 UTC
Labels: Enhancement
