### ISSUE TITLE
RNAV approach indications and FMA incorrect

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#326] opened 2020-09-02 06:39 UTC
RNAV approaches should have a V/DEV label and APP NAV lateral mode, not LOC. Also, the glideslope scale only  should be visible without the LS button. The V/DEV also shows incorrect path info. 
![image](https://user-images.githubusercontent.com/70193215/91939880-277a7400-ed29-11ea-9708-82b1c0ba252e.png)

**Comment by Curtis-VL** [comment] 2020-09-02 16:42
I was actually under the impression it wasn't possible to do RNAV approaches right now due to some Asobo bugs, but I can look into it!
I've only ever done ILS approaches, but I've heard of RNAV, need to look it up. :)

**Comment by MisterChocker** [comment] 2021-01-06 15:39
Duplicate of #2792

**Closed by MisterChocker** 2021-01-06 15:39 UTC
Labels: Bug, PFD
