### ISSUE TITLE
[BUG] NOSE DROPPING UPON LANDING

### ISSUE THREAD

**Issue by Skymonkey75** [flybywiresim/a32nx#2501] opened 2020-12-18 14:46 UTC
**Mod Version**
0.5.0 - Stable Version

**Describe the bug**
Upon landing, nice steady approach path - flare should indicate on flight display giving the PF time to begin the flare before the nose drops out on it's own. With an immediate slamming of the airframe into the runway and the "retard" call out - not even seeing the "FLARE" show up???  (I'm rushing to control the slamming piece of metal)

**To Reproduce**

1. Choose an ILS approach and fly it all the way in.
2. Full flaps, managed speed.
3. Maintain sidestick control to follow FD

**Expected behavior**
Aircraft should continue on it's path and not push down towards the runway - nothing has changed in the flightpath/speed, the flare is required to dump last little bit of speed.

**Actual behavior**
As per the BUG - no "FLARE" flag noticed - nose drops down immediately around 30 ft AGL

**References**
Nil

**Additional context**
Nil

This was working well in the last STABLE version - was enjoying some silky smooth landings.

There was reference to this bug in the past, however I found no reference in regards to 0.5.0

**Comment by Benjozork** [comment] 2020-12-18 15:30
Duplicate of #1769

**Closed** 2020-12-18 15:30 UTC
Labels: Bug

**Comment by fahdriyami** [comment] 2021-05-15 20:42
> Duplicate of #1769

Has this been fixed? I experienced this twice on Stable version 0.6.1.

**Comment by Benjozork** [comment] 2021-05-15 20:43
@fahdriyami As said in the linked issue, this is fixed in the custom fly-by-wire system, which is only available in dev at the moment.
