### ISSUE TITLE
unable to press baro selection knob on ISIS

### ISSUE THREAD

**Issue by ccapilot** [flybywiresim/a32nx#4405] opened 2021-04-11 19:09 UTC
**Mod Version**

"built": "2021-04-11T12:51:36+00:00"

**Describe the bug**

Can not press the ISIS barometric selection knob, at the moment the knob can only be rotated, but can not be pressed to switch the barometric reference to STD and back to hPa/inHg.

**To Reproduce**

1. try to press the barometric selection knob on ISIS, it can not be done.
2.
3.

**Expected behavior**

should be able to press the baro selection  knob on ISIS to change from hPa/inHg to STD or form STD to hPa/inHg.

**Actual behavior**

baro selection knob on ISIS can not be pressed, only can be rotated.

**References**

search for ISIS description on FCOM

**Additional context**

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
I don't know.

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment] 2021-04-13 13:36
Duplicate of #1186

**Closed by MisterChocker** 2021-04-13 13:36 UTC
Labels: Bug
