### ISSUE TITLE
After Update (FBW, MSFS) no more MCDU-Server connection to MSFS

### ISSUE THREAD

**Issue by Adi-18** [flybywiresim/a32nx#7765] opened 2023-02-05 12:02 UTC
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2022-01-24T20:26:03+00:00",
  "ref": "master",
  "sha": "6c0bd372fd8674fd86a66dc9b3bf975c27f9d55c",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Since update (from Saturday already) also new Version of MSFS, no more connection to MCDU-Server

### Expected behavior

Possible to work MCDU on Web-Tablret again 

### Steps to reproduce

1. Update MSFS and FBW.
2. Start MSFS, Start MCDU_Server

![2023-02-05](https://user-images.githubusercontent.com/29123730/216817536-55dd14e7-55e8-4e6d-abb1-96d0f66a3da1.png)

**Comment by Gurgel100** [comment] 2023-02-05 16:34
The MCUD_Server is not necessary anymore and is the old method. The new method is via SimBridge. I see that you already have SimBridge running (wifi symbol on FlyPad). In the notification area of the Windows taskbar you find the SimBridge symbol where you can right click on it and open the remote MCDU.

**Comment by 2hwk** [comment] 2023-02-08 02:27
Closed as this is not a bug

**Closed by 2hwk** 2023-02-08 02:27 UTC
Labels: Bug
