### ISSUE TITLE
LS (ILS) button doesn't light up when activated [BUG]

### ISSUE THREAD

**Issue by hummelmose** [flybywiresim/a32nx#449] opened 2020-09-06 11:16 UTC
**Mod Version**

0.2.0

**Describe the bug**

when pressing the LS button for ILS approach it doesn't light up

**To Reproduce**

1. ILS approach
2. press LS 
3. No light

**Expected behavior**

Light in button

**Actual behavior**

No light in button

**References**

**Additional context**

**Comment by UncleClapton** [comment] 2020-09-06 11:20
LS button is tied to panel brightness for some reason. This bug is also present in the base aircraft. 

Duplicate of #67. In the future, please use the search box at the top of the issues list to try to find your problem before reporting it.

**Comment by hummelmose** [comment] 2020-09-06 11:24
Hi Uncle Clapton - I did search for LS but didn't find anything. Sorry.

**Comment by UncleClapton** [comment] 2020-09-06 11:29
No problem! I'll probably be looking into this one soon since nobody has really picked it up

**Comment by Curtis-VL** [comment] 2020-09-06 15:58
Fixed in #451.

**Closed by Curtis-VL** 2020-09-06 15:58 UTC
Labels: bug
