### ISSUE TITLE
Radio control panel is reverse with comms selected

### ISSUE THREAD

**Issue by GlitchedYT** [flybywiresim/a32nx#344] opened 2020-09-03 01:47 UTC
**Describe the bug**
When "Call" button over the VHF1 knob is selected, the VHF2 knob is in use. When "Call" button above VHF2 knob is selected, VHF1 is in use.

**To Reproduce**
Press the Call button above VHF1, you will notice if you try to click on the VHF1 knob to use that it will not work, but the VHF1 knob is able to be used, and vice verse

**Expected behavior**
You should be able to select VHF1 and the "Call" button above it and not have any issues, same goes with VHF2 and the "call" button above that.

**Screenshots or Videos**
https://imgur.com/mZ5ED9U
https://imgur.com/YBv2xjX

**Comment by UncleClapton** [comment] 2020-09-03 08:47
Seems the logic behind this is that the lit volume knobs are the COMs OTHER than the "Call" COM which are active at the same time. all 3 systems can be listened to simultaneously , but only 1 can be transmitted to at a time.

This is default asobo logic. If the real aircraft behaves differently, than this should be a feature request, not a bug with the mod.

**Comment by JackZ974** [comment] 2020-09-03 09:55
In the ACP, lit Volume knobs are for reception only.
When pushed and lit, these allow to receive the voice coming through these channels. So numerous knobs can be pressed at the same time (for example, some SOPs mandate a continuous watch on 121.5 while in cruise, which is attained by setting 121.5 on VHF2, while VHF1 is devoted to ATC transmissions). 

The CALL Pushbuttons are for transmit channels ONLY, so either none is lit (when pressing the sidestick trigger), or only ONE is lit and selected for voice transmission. 

CALL 5transmit) Push buttons are completely independant from the reception & volume knobs

**Comment by JackZ974** [comment] 2020-09-03 11:21
BTW the ACP 1, 2 and 3 are normally completely independent one from another. 

The SEL light behaviour is weird, too. It should lit up whenever  a different configuration from the default for the current RMP is selected, (for example, if CAPT RMP is set to VHF 2 instead of 1, the default config being RMP1: VHF1, RMP 2: VHF 2). 
Also IIRC, the SEL light should be amber instead of green

**Comment by UncleClapton** [comment] 2020-09-03 11:24
thanks! so this should be re-labeled as a feature suggestion!

**Comment by MisterChocker** [comment] 2021-02-10 21:56
Is this fixed by now?

**Comment by GlitchedYT** [comment] 2021-02-10 22:15
I don't think this ever was implemented afaik

**Comment by juliansebline** [comment] 2022-04-22 08:41
I'm working on it for few days.  It's fixed on my side, just doing some tests

**Closed** 2022-08-16 13:50 UTC
Labels: Request, RMP
