### ISSUE TITLE
Aircraft won't fly beyond Mach 0.807

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5413] opened 2021-07-26 10:15 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-25T10:59:19+00:00",
  "ref": "master",
  "sha": "63df888a4695e4cf2a7f4da4668c603daf958611",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

![807](https://user-images.githubusercontent.com/85410344/126972691-7ad7dfeb-fd40-4480-9f26-25e4a034d1a0.jpg)

### Expected behavior

Mach 0.82 is where the barber pole starts when Mach 0.82 < 350kts.

### Steps to reproduce

Climb up to FL300+ at ISA
Select Mach 0.82
Voilà

### References (optional)

Self-experience

### Discord Username (optional)

Illuminati

**Comment by marcsoler** [comment] 2021-07-26 19:45
I'm not a IRL pilot, but isn't this expected by the flight control's normal law?

**Comment by Illuminati270** [comment] 2021-07-26 20:09
> I'm not a IRL pilot, but isn't this expected by the flight control's normal law?

I am. And it's not.

**Comment by NUTTTTTTTT** [comment] 2021-07-26 23:32
![image](https://user-images.githubusercontent.com/87286435/127071951-40aaab3a-e070-4416-8d30-06a73ab0781b.png)

I just did it on the same version, 0.82 is a bit optimistic depending on the conditions though and bordering on overspeed afaik so I can see reasons why you wouldn't have been able to pass 0.807 at a given point in time.

**Comment by Illuminati270** [comment] 2021-07-26 23:35
> ![image](https://user-images.githubusercontent.com/87286435/127071951-40aaab3a-e070-4416-8d30-06a73ab0781b.png)
> 
> I just did it on the same version, 0.82 is a bit optimistic depending on the conditions though and bordering on overspeed afaik so I can see reasons why you wouldn't have been able to pass 0.807 at a given point in time.

Care to show the whole speedtape?

**Comment by NUTTTTTTTT** [comment] 2021-07-26 23:38
Don't have it up anymore I'm afraid, just tested while I was in sim testing something else and snipped that part.

**Comment by oim1** [comment] 2021-07-26 23:56
it also depends on the temperature

**Comment by tracernz** [comment] 2021-07-27 01:11
Check ISA deviation if using live weather, and also N1 vs limit on ECAM.

**Comment by Illuminati270** [comment] 2021-07-27 01:45
> Check ISA deviation if using live weather, and also N1 vs limit on ECAM.

ISA + 0, tracer. N1 reaches the N1 limit, then decelerates once reaching the barber pole.

**Comment by lukecologne** [comment] 2021-07-27 01:54
The fact that it is not exceeding Vmax is normal. The problem here is that the Vmax is calculated by our own algorithm from Mmo, temperature and ambient pressure, and the actual indicated airspeed (the autothrust also bases it's control law on it) is calculated by the sim, which, as I understand it, uses a wrong formula, which results in the wrong position of the overspeed tape and the A/THR holding a too low mach.

**Comment by donstim** [comment] 2021-07-29 16:49
To elaborate on what luke wrote, the MSFS conversions between Mach/KTAS and KCAS are wrong. We use the correct conversion to obtain Vmax and to place the barber pole (red-and-black band) on the PFD speed tape. At 39,000 feet, MMO (Mach 0.82) is 255 KCAS, which is where the red-and-black band starts. All other speed indications are from MSFS. The speed conversions were supposed to be fixed in SU4, but were not included there. They are in SU5, but the incorrect altitudes are still preventing these speed conversions from being correctly implemented.

Summary:  Although it looks like you are at M0.807, you are actually at M0.82 with your speed bug set at M0.83. As you know, in that case, the airplane may slightly overshoot MMO, but would then settle in at MMO (M0.82) as it has as shown in your screenshot.

**Comment by donstim** [comment] 2021-08-13 03:28
Unsure why this issue is still open since I explained that it is due to an Asobo MSFS bug.  In any case, Asobo fixed the speed conversion bug in Sim Update 5, so the issue no longer exists. (The speeds can still be a couple knots off because some of the pressure altitudes are still a bit off, but that is expected to be fully fixed in World Update 6.

In the steps to reproduce, the OP says to climb to FL300, but the PFD screenshot showing the issue was done at FL390. I assume it was a typo, but just in case, here is what the PFD now shows for both cases:
![Screenshot (1092)](https://user-images.githubusercontent.com/70166617/129300963-1cd47b3d-147f-43b3-ad28-42c5888faca8.png)
![Screenshot (1093)](https://user-images.githubusercontent.com/70166617/129300968-a2fa5c2b-dcab-4411-a0ea-8db62a64fdfd.png)

**Closed** 2021-08-13 03:59 UTC
Labels: Bug
