### ISSUE TITLE
A32NX ILS not working

### ISSUE THREAD

**Issue by minkyu-koo** [flybywiresim/a32nx#2111] opened 2020-11-27 05:15 UTC
The ILS on A32NX is buggy for me. When I enable LOC or APPR when the diamonds show up, the airplane turns in a different direction and does not try to line up with the runway. Also even though I had the correct ILS frequency for a runway, it was lining up with the runway next to it.

**Comment by Benjozork** [comment] 2020-11-27 05:42
Duplicate of #2089 and does not respect template.

**Closed by Benjozork** 2020-11-27 05:42 UTC
