### ISSUE TITLE
[BUG] Simbrief Payload won't be loaded

### ISSUE THREAD

**Issue by Polacanthus** [flybywiresim/a32nx#3112] opened 2021-01-19 07:41 UTC
**Mod Version**

  {
  "built": "2021-01-19T01:05:05+00:00",
  "ref": "",
  "sha": "",
  "actor": "Matthew Sainsbury <matthew@sainsbury.io>",
  "event_name": "manual"
}

**Describe the bug**

When I load a flightplan from Simbrief it will pull the fuel but not the payload even though correctly displayed on page 2/2 of the PERF/W&B page. 

**To Reproduce**

1.  Create a flightplan on Simbrief and load it into the aircraft.
2. Use the refuel softkey on the PERF/W&B page and note it works and changes the fuellevels.
3. Do the same for the payload and note it will always remain on what you set on the worldmap.

**Expected behavior**

It should enter the correctly displayed weights to reach a value above simbriefs expected TOW.

**Actual behavior**

Payload will not change.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Never.

Is this a problem in the vanilla unmodded game?
Doesnt support that feature.

Discord username (if different from GitHub):  Polacanthus#4729

** as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by hotshotp** [comment] 2021-01-20 04:54
Duplicate #3102

**Comment by minznerjosh** [comment] 2021-01-30 01:03
I don't think this is a dupe of #3102 @hotshotp. #3102 is about discrepancies when loading fuel. This issue is about the pax/cargo weight not being loaded into the sim. Could you reopen this issue?

FWIW I'm experiencing this issue.

**Comment by AdamNZ** [comment] 2021-01-30 04:07
Same here:
{
  "built": "2021-01-29T21:31:03+00:00",
  "ref": "",
  "sha": "",
  "actor": "Imenes <71195324+ImenesFBW@users.noreply.github.com>",
  "event_name": "manual"
}

As a test, I set fuel to 5% and payload to 0 before powering up the A320. Fuel loaded OK, but payload was ignored. Pics follow.

**Comment by marway84** [comment] 2021-02-10 00:11
why has it been closed? the problem persists in the payload.

**Comment by hotshotp** [comment] 2021-02-10 12:42
My apologies for wrongly closing this issue

**Comment by AdamNZ** [comment] 2021-02-10 23:39
ALSO ... I've noted that when loading the FUEL, that PAYLOAD values are changed. Could it be that values for both pages are erroneously updated when (only) the FUEL page is used?

**Comment by N1EL** [comment] 2021-02-10 23:57
Could adding a number of passengers maybe causing it??

**Comment by AdamNZ** [comment] 2021-02-11 00:02
> Could adding a number of passengers maybe causing it??
> 18720 / 180 pax is 104kg each.

I'm not adding the PAX manually - it's taking that number from the Simbrief plan ... but I'll do the maths and do another check.

**Comment by N1EL** [comment] 2021-02-11 00:10
Yes but im thinking if the SB has 180 passengers thats gets sent to the MCDU, which then x 104kg and adds the weight to the payload section of the MCDU but not the Payload section of the W&B page of the sim.
Maybe theres 180 Pax on the SB flightplan?

**Comment by marway84** [comment] 2021-02-20 23:12
I have tried different numbers of passengers in simbrief. The result is always the same. Clicking on Load Payload does not change the payload into the sim. can someone do tests?

**Comment by felixharnstrom** [comment] 2021-03-29 08:11
According to this comment https://github.com/flybywiresim/a32nx/pull/1865#issuecomment-745271247 this seems to be an Asobo bug. I have verified that the GW value on the ECAM changes and that the suspension gets compressed after requesting the payload, so it seems to be registered. It's just that the MSFS menu is not updated for some reason.

**Comment by sidnov** [comment] 2022-03-03 15:59
The components involved in this issue have been rewritten since then, hence closing

**Closed by sidnov** 2022-03-03 15:59 UTC
Labels: Bug, Waiting For Response
