### ISSUE TITLE
[BUG] Autopilot flys direct to RW threshold on approach rather than following STAR waypoints.

### ISSUE THREAD

**Issue by VigrAU** [flybywiresim/a32nx#3099] opened 2021-01-18 11:25 UTC
**Mod Version**

{
  "built": "2021-01-18T02:36:25+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**

During approach to YBBN RW01R via GLENN apr SMOKA9A the aircraft seems to adjust its next waypoint mid approach to the RW threshold. This also has occured on a number of other approaches, for example RW15 via SUNNY star UPOLO8A the same behaviour occurs.

Despite the flight plan showing the correct waypoints in sequence it jumps the approach waypoints and targets the threshold.

This bug has occured when loading in a flightplan from simbrief, and when setting up a flight beforehand from the world map screen.

**To Reproduce**

1.Load stated aproach into Flight Plan
2.Fly the approach, during the approach the waypoints planned will skip to the threshold of the selected runway.

**Expected behavior**

Aircraft follows the programmed waypoints/approach.

**Actual behavior**

Aircraft skips the programed approach waypoints and flys together to the RW threshold, the destinion in the FMC lists a waypoint with the name of the threshold e.g. RW01R

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Noticed this since I started flying again from 11/01/21, always using the latest Dev version.

Is this a problem in the vanilla unmodded game?
Could not replicate.

**Comment by Benjozork** [comment] 2021-01-18 15:10
Duplicate of #939

**Closed by Benjozork** 2021-01-18 15:10 UTC
Labels: Bug
