### ISSUE TITLE
[BUG] Deck angle/AoA 8-9 degrees during cruise

### ISSUE THREAD

**Issue by dmajestic80** [flybywiresim/a32nx#1437] opened 2020-10-18 03:19 UTC
**Mod Version**

built: 2020-10-17T19:55:28+00:00
ref: refs/heads/master
sha: f2d9a616cd3675d50cbe017a45e3154c7561aaa5
actor: lukecologne
event_name: push

**Describe the bug**

As per screenshot my I am cruising with an AoA of 8-9 degrees with the latest build posted above. Trim is showing 11.1 UP Yesterday's build I did not have this issue. 

Issue was not present using below. Something has changed since yesterday.
built: 2020-10-17T05:47:40+00:00
ref: refs/heads/master
sha: eac80e5bc12ea67936ea5aa93c53256baff461a0
actor: Benjozork
event_name: push

**To Reproduce**

1. Doing a standard flight YSSY to YPAD. Set weights as I normally would (screenshot shows weights) CG within limits. Plane is actually relatively light.
2. ZFW 58.8/ZFWCG 27.4
3.

**Expected behavior**

Deck angle at around 2.5 to 3 degrees (maybe max 5 degrees if heavy)

**Actual behavior**

Deck angle/AoA is 8-9 degrees with trim 11.1 UP

**References**

![1250410_20201018133427_1](https://user-images.githubusercontent.com/72002430/96357786-9714b900-1147-11eb-8af9-6da8ac71ad50.png)
![1250410_20201018134237_1](https://user-images.githubusercontent.com/72002430/96357796-d17e5600-1147-11eb-8b45-be3653449738.png)

**Additional context**

I even dropped the payload to 0.00% and the AoA was still at 5 degrees which is insane

Was this working before/when did the issue start occurring? Using the latest build posted above

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-10-18 03:53
Duplicate of #984

**Comment by Benjozork** [comment] 2020-10-18 03:54
> Is this a problem in the vanilla unmodded game? No

It is. the problem is just very random.

**Closed by Benjozork** 2020-10-18 03:53 UTC
Labels: Bug

**Comment by Benjozork** [comment] 2020-10-18 03:57
FYI, we will fix this issue when our own autopilot implementation is included.

**Comment by donstim** [comment] 2020-10-18 03:58
May be addressed by: https://github.com/flybywiresim/a32nx/pull/1295

**Comment by dmajestic80** [comment] 2020-10-19 00:35
> > Is this a problem in the vanilla unmodded game? No
> 
> It is. the problem is just very random.

Just as an FYI, I’ve worked out that the AoA deck angle issue is caused by REX weather producing an erroneous SAT temp of around -100°c during cruise (about double the normal values) which has a massive affect on the a320’s performance including AoA. I did an identical flight using in sim live weather and SAT was -43°c and aircraft flew normally.
