### ISSUE TITLE
[BUG] Everything shut down after cold & dark startup and unable to start back up

### ISSUE THREAD

**Issue by ferics** [flybywiresim/a32nx#903] opened 2020-09-26 14:14 UTC
**Mod Version**

Master, prior to release 0.3

**Describe the bug**

The plane randomly shut down after i performed a cold & dark startup and getting ready to request ATC clearance. All electrical power went offline but the battery switches and ext power seem to still lit up when pressed (forgot to try for other switches). I restarted the game for the same airport KSFO and gate B9 and same thing happened (a bit later than the first time).

**To Reproduce**

1. Spawn at gate B9 KSFO (only experienced it there)
2. Startup from cold & dark as usual
3. Get ready to request clearance from VATSIM then be welcome with  the whole plane going back to cold & dark and unable to start back up

**Expected behavior**

All power remain online after cold & dark startup.

**Actual behavior**

All power shut down after cold & dark startup.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Unable to say for sure since I only experienced this at one particular airport twice in a row

Is this a problem in the vanilla unmodded game?
Unable to confirm (most likely not).

Discord username (if different from GitHub):
ferics#3085

**Comment by DoToAdventures** [comment] 2020-09-26 14:17
Related to #718
Asobo bug. Workaround currently is to shut off all AI and multiplayer traffic and put all the traffic sliders to 0 in the menu.

**Comment by ferics** [comment] 2020-09-26 14:19
Respawned at the different airport with the same config did fix the issue temporarily though.

**Comment by DaBeLG** [comment] 2020-09-27 11:18
not solved in version 0.3

**Comment by ferics** [comment] 2020-09-27 12:40
I don't think it's the same issue as #718 issue. The #717 issue reported a different issue to this.

**Comment by tareksabet** [comment] 2020-11-15 19:00
can't reproduced it's fixed now

**Closed by tareksabet** 2020-11-15 19:00 UTC
Labels: Can't Reproduce
