### ISSUE TITLE
[BUG] AP/HDG/SPEED

### ISSUE THREAD

**Issue by Middi25X** [flybywiresim/a32nx#1689] opened 2020-11-01 11:38 UTC
**Mod Version**

 0.4.1 stabel

**Describe the bug**

aircraft turn to left and right,sometimes is just holding left. AP doesnt work either and not speed button.

**To Reproduce**

1. climb,crz
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
had this problem since 0.3.0
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment] 2020-11-01 15:16
Please provide a more detailed explanation of your problem.

> aircraft turn to left and right,sometimes is just holding left.

Have you tried increasing your deadzones ?

**Comment by Benjozork** [comment] 2020-11-01 15:17
> AP doesnt work either and not speed button.

What does "doesn't work" mean ? Is the behaviour incorrect ? Does it just not do anything ?

Could you record a video of what you mean ?

**Comment by Benjozork** [comment] 2020-11-01 15:17
>BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Might wanna remove this.

**Comment by goodCat56** [comment] 2020-11-01 17:27
Hi, I hope that I'm not hijacking the thread. I have got the same issue after MFS last update 1.10.7
Below is a short video describing the issue,
https://drive.google.com/file/d/1rlE6m28tPfUHRgTnRDskATBGm8xFeyw-/view?usp=sharing

**Comment by Middi25X** [comment] 2020-11-01 17:32
Correct @goodCat56  this problem is the same i have aircraft start turning to left and not stoping... other issiue airplane swing to left and right and not stop till AP is off

**Comment by Benjozork** [comment] 2020-11-01 17:48
Roll issue is duplicate of #1617

**Comment by Middi25X** [comment] 2020-11-01 17:49
is it going to be fixed ? becuase is not always it work to turn off ap

**Comment by Benjozork** [comment] 2020-11-01 18:20
Sadly it's up to Asobo to fix it, until we have our own autopilot, which will take months.

**Comment by Middi25X** [comment] 2020-11-01 18:23
ahh okei because it is useless sometimes to fly with it :(

**Comment by goodCat56** [comment] 2020-11-02 17:35
@Middi25X I have an update. I tried to disconnect my hotas and test a flight with just mouse and keyboard, A/P works fine in both default and mod aircrafts. It seems there is some issue in the hotas setting which MFS does not like. I'm working to find what is it now. 
Hotas: Thrustmaster warthog

**Comment by goodCat56** [comment] 2020-11-02 18:14
Yup! Mine is fixed by resetting the joystick sensitivity to the default setting :)

**Comment by Middi25X** [comment] 2020-11-02 21:03
okei will try to reset my settings for yoystick :D

**Comment by Middi25X** [comment] 2020-11-02 21:25
i belive my sensitivity is deafult but will check now

**Comment by MisterChocker** [comment] 2020-12-31 05:41
This seems to be a already resolved bug.

**Closed by MisterChocker** 2020-12-31 05:41 UTC
Labels: Bug
