### ISSUE TITLE
MCDU skips 'long way' when flying STAR with parallel paths

### ISSUE THREAD

**Issue by uzytkownik** [flybywiresim/a32nx#4489] opened 2021-04-18 17:30 UTC
**Mod Version**
Development ae1feb6 and older

**Describe the bug**
When flying STAR which has a parallel (e.g. ELKA3A/ELKA3B) or parallel to ILS, MCDU gets lost and takes a shortcut flying directly to later point instead of following full STAR.

**To Reproduce**
1. Program MCDU to follow STAR with a parallel paths
2. Fly itb

**Expected behavior**
Autopilot flies full path.

**Actual behavior**
Autopilot gets confused and skips to later point on STAR.

**Additional context**
Was this working before/when did the issue start occurring?
No.

Is this a problem in the vanilla unmodded game?
I think so.

**Comment by Benjozork** [comment] 2021-04-18 17:45
Duplicate of #939

**Closed by Benjozork** 2021-04-18 17:45 UTC
Labels: Bug
