### ISSUE TITLE
This little arrow is needed on ND

### ISSUE THREAD

**Issue by Soap1422** [flybywiresim/a32nx#6438] opened 2021-12-30 06:24 UTC
### Aircraft Version

Stable

### Description

![111](https://user-images.githubusercontent.com/89972707/147726926-e7d4bf03-81a9-4276-b31f-16cd2ddf110d.png)
This little arrow is needed on ND, I think it is equals boeing's “Height distance ring”
well, I ain't sure, screenshot I have took on P3D's FS lab A320.

### Discord Username (optional)

Soap

**Comment by aguther** [comment] 2021-12-30 08:43
This is part of VNAV and is currently working in progress.

duplicate of #5966

**Comment by aguther** [comment] 2021-12-30 08:44
Duplicate of #5966

**Closed by aguther** 2021-12-30 08:43 UTC
Labels: Request
