### ISSUE TITLE
Unable to engage HDG on AP

### ISSUE THREAD

**Issue by ribase** [flybywiresim/a32nx#5479] opened 2021-07-30 11:51 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-30T02:31:34+00:00",
  "ref": "master",
  "sha": "bab6a451346ee9fb2a28abe20bf4ec454933e371",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Unable to activate HDG mode inflight

### Expected behavior

Able to activate HDG mode inflight

### Steps to reproduce

1. Fly
2. Set direct
3. Press HDG knob

**Comment by marcsoler** [comment] 2021-07-30 11:57
Are you pressing or are you pulling the knob? Also check [this](https://github.com/flybywiresim/a32nx/issues/5427#issuecomment-887847903)

**Comment by ribase** [comment] 2021-07-30 12:00
> Are you pressing or pulling the knob? Also check [this comment](https://github.com/flybywiresim/a32nx/issues/5427#issuecomment-887847903).

Already checked this ;).
Press or push does not do anything, very strange, because with speed button it works. The AP indicates that i interact, puts a ball aside of the set HDG but not activate.

**Comment by aguther** [comment] 2021-07-30 12:38
Please reload the plane or even better the sim. For an to us unknown reason the HDG pull does sometimes not work after the wasm was just compiled.

So potentially happens every time after updating A32NX and the wasm was touched somehow. As already said, the issue is not on our side, it’s an issue of SU5.

**Comment by Node-Ninja** [comment] 2021-07-30 18:18
Still experiencing the same thing even after the hotfix. The heading cannot be engaged.

**Comment by ferryvanaesch** [comment] 2021-07-30 18:28
Same here; first time victim btw.

**Comment by Pretty-Flacko** [comment] 2021-07-30 18:43
I guess I encountered the same problem with altitude knob (can't enable managed altitude sometimes)

**Comment by eljiot5169** [comment] 2021-07-30 19:07
Same here too, swiched FD off and on, then it worked.

**Comment by noobielameo** [comment] 2021-07-31 10:09
Same issue here, with AP pushing hdg activates managed heading while changing heading pulling the knob does nothing but notice does change to dotted line on the panel.

**Comment by aguther** [comment] 2021-07-31 13:19
New interaction system?

**Comment by Teslix** [comment] 2021-07-31 16:14
I update my DEV version almost daily, and never encountered this bug until yesterday's build. All systems working nominally, but I didn't need heading mode until my approach. I was given vectors to intercept, and couldn't use the knob to change to heading mode and had to fly manually instead. When pushing/pulling the knob, the correct choice would come alive on the PDF (dashed line for heading, solid line for nav) and the heading numbers would come alive and you can adjust them, but the plane wouldn't actually turn to the desired heading, it just stays following the planned route (still in nav mode)

**Comment by aguther** [comment] 2021-07-31 16:16
I mean we didn’t change anything in that area. Now guess what was changed…

**Comment by hiroooo1997** [comment] 2021-08-01 10:38
For those knobs, it seems
Left Click + Right Click to Push 
Left Click + Middle Click to Pull
by default.

**Comment by patbuser** [comment] 2021-08-01 14:45
Exactly the same here. Unable to get out of managed heading (nav mode). I had to fly the approach with given vectors manually. The little dot on the right doesn't disappear when pulling the knob.

**Comment by twasono** [comment] 2021-08-01 17:38
I have the same issue.

This happens when I was on approach phase. I changed the approach/runway on the MCDU, then I decided to use HDG mode by pulling the HDG knob. 

The heading number was displayed but the little white dot stays there. I can turn the knob to change the heading number, but the AP doesn't follow it.

**Comment by aguther** [comment] 2021-08-01 17:55
To distinguish a bit between the issue that the event does not work on first load after an A32NX Update, it would be helpful if this information would be provided.

Additionally it would be helpful if you make screenshots or videos…it’s quite time consuming to always ask for those basics.

**Comment by ribase** [comment] 2021-08-01 17:55
In the content manager there was some update for premium content as well, since i did it i dont have any problems since.

**Comment by baptista54** [comment] 2021-08-01 21:14
even here, HDG does not accept, pulling or pushing. I have dotted lines on the MDCU even after the plan executed and the NAV turned on. Many CTDs but I can fly at some point. Any suggestions? Using the DEV version (it was perfect before this damn SU5).tks

**Comment by daddyali** [comment] 2021-08-01 22:49
Hope this helps: Example here - I'm approaching EGGD, EXMOR at the top of the ND is the start of the STAR. Due to the known pre-existing MSFS navigation bug, at time code 0:14, when approach mode kicks in, the nav system gives up on the STAR and heads off direct to BRI. You can see the ND updating accordingly and the aircraft turns. All this is 'normal' and I'm used to pulling the heading knob to managed and manually vectoring. However, note this time I pull the heading knob, the heading window 'opens' but the managed dot remains and the aircraft continues towards BRI despite my attempts to cycle the heading back to North. From around timecode 1:12 I'm pushing and pulling the knob (I'm using full legacy mode for cockpit interaction) and although the ND path updates between dotted and solid lines, the aircraft persists in flying what is effectively managed mode to BRI. As others above, my only way out is AP off and hand fly.

https://youtu.be/7WjlxxXa-Kk

**Comment by aguther** [comment] 2021-08-02 04:43
@daddyali Was this the first flight after the installation or update of the A32NX?

**Comment by Hulkios** [comment] 2021-08-02 05:18
Go to general options > accesibility > change cockpit interaction system to legacy and then try

**Comment by patbuser** [comment] 2021-08-02 06:23
@aguther  for me it was indeed the 1st flight (ie first load of plane) after the update. Will test loading, exiting and reloading the next time.

**Comment by patbuser** [comment] 2021-08-02 07:05
@Hulkios  I don't use the the new mode, I'm on legacy already

**Comment by daddyali** [comment] 2021-08-02 07:25
@aguther tbh, not sure as I was in and out of the sim yesterday doing the post-su5 'add back the addons' dance. Will retest to be certain.

**Comment by LordNecton** [comment] 2021-08-02 09:10
Im having  the same problem as you guys on this topic...Since SU 5 half the sim is now broken, I blame Asobo

**Comment by aguther** [comment] 2021-08-02 09:13
Please try again after reloading the plane. It might happen after direct load when A32NX was updated.

**Comment by ewold** [comment] 2021-08-02 10:40
i can confirm this is after updating the plane. Restarting it solved it for me. I created a video of the behaviour before the restart. I turned the heading mode on and off and rotating the knob. The plane reacted but with showing a dashed line but is not turning towards the requested heading. [https://streamable.com/j1o91g](url)

**Comment by baptista54** [comment] 2021-08-02 13:21
Legacy cockpit happily resolved. HDG ok .I'll try to update the airac and automatic icaos on the mdcu display. Thanks to this amazing forum. Good flights fly again.

**Comment by aguther** [comment] 2021-08-02 13:33
@ewold The issue is that some events need to go to other parts written in JS and they seem to work, but the event notifying the custom autopilot (which is implemented in a wasm) is not receiving the event. I‘ve brought this up early to MS/Asobo, but I got no feedback yet about the reason. It‘s also strange because it always affects the same event while in my tests all other events worked well. Only the one for HDG pull does not work.

**Comment by daddyali** [comment] 2021-08-02 22:02
Also able to confirm following a retest (deliberately not updating the mod first) that the 'pull HDG mode' issue does not present itself so I must have been flying yesterday directly after a mod update. I've clearly been Asoboed. Many thanks to you @aguther and the wider team for making this bird so fun to fly despite this!

**Comment by hawaikicr** [comment] 2021-08-06 22:01
Salutations,
unfortunately I continue to have the same problem, the plane continues to be in managed mode, I cannot activate the HDG, the strange thing is that if I am on the ground the HDG I can activate it, but in the approach phase or anyway at altitude absolutely not ... down arrow to pull the pawl but the management's obsession is always and the plane continues to follow the set route ... I have already followed all your advice ... I don't know anymore ' what to do! Thanks and good job! 
The first image in flying at 30000 can't engage HDG, the second after landing... 

![Screenshot (74)](https://user-images.githubusercontent.com/49593847/128575124-224069fd-b4c1-420b-8de2-53675f14bd09.png)
![Screenshot (76)](https://user-images.githubusercontent.com/49593847/128575129-eef6a526-47e9-45e2-a0c6-b9c18525653e.png)

**Comment by aguther** [comment] 2021-08-06 22:03
On ground it works because the pull event is not needed to disarm NAV, rotation is enough.

**Comment by hawaikicr** [comment] 2021-08-06 22:14
So what is the problem? what can i do to resolve it? I ask in my forum and the same problem have other people too...

**Comment by joseG69** [comment] 2021-08-07 03:53
Problem solved for me. Solution is to close de sim and reload the plane. 
In conclusion, you cant fly directly after updating. 
Update -- launch the sim -- load de plane -- close de sim -- launch the sim --- load the plane -- fly

**Comment by aguther** [comment] 2021-08-07 06:14
@hawaikicr see also here https://github.com/flybywiresim/a32nx/issues/5566

It’s sometimes hard to keep overview because of duplicate issues, so it’s easy to forget to provide information where it’s needed. A bit of help of the users to avoid that would be great.

We are trying to do our best to resolve issues and this needs to be done in our spare time, which often takes a lot of time. I will bring this issue up with Asobo next week to find a root cause.

**Comment by 2hwk** [comment] 2021-08-07 08:15
I've had this happen on a recent flight and I was able to fix it by reloading A320_Neo_FCU. I've also had it with the flight plan manager branch, so I feel this is probably a bug that we can fix.

**Comment by hawaikicr** [comment] 2021-08-07 08:22
Hi guys and thank you... 

Can u explain me how you have reload the a320_neo_fcu exactly? Perphas i reload but no how i have to do... 


Yesterday i have clean the MOD directory and cache too, then reinstallal all to the Last DEV versión, open sim, open plane and close all... Then reopen sim and nothing still problem... 


Wait, thank you very much for your incredibile assista ce free! 


Ciao 


Stefano Miglioli


From my mobile with outlook

Softworld snc

Cremona

www.softworld.info

**Comment by joseG69** [comment] 2021-08-07 14:00
Good morning
Another interesting point I realized is the first time you load the plane after an update, it takes a lot of time to be completed, almost an eternity, after clicking the fly button. In the following times, this process is much more faster.
Congratulations for your team for the excellent job you are doing.

We are looking forward to the new FPM. 

Best regards

Jose

**Comment by joseG69** [comment] 2021-08-07 14:06
@hawaikicr when I say I load the plane, I select A320 NEO FBW in the world map, select a gate in an airport of choice and click FLY!

**Comment by hawaikicr** [comment] 2021-08-07 14:41
Yesss! 

Thanks you and all the staff for patience, i confirm that If reload airplane completely it's ok... 


Good job and thank to José many Thanks 


Stefano Miglioli


From my mobile with outlook

Softworld snc

Cremona

www.softworld.info

**Comment by aguther** [comment] 2021-08-07 14:45
I also found something interesting: the issue indeed appears right after compilation of the wasm and when the issue is there, sending the same event from outside via SimConnect works without issues.

That means the issue is somehow related to the JS part.

**Comment by 2hwk** [comment] 2021-08-07 16:11
> I also found something interesting: the issue indeed appears right after compilation of the wasm and when the issue is there, sending the same event from outside via SimConnect works without issues.
> 
> That means the issue is somehow related to the JS part.
> 
> The strange part on that is that I already debugged the JS code and the event that is triggered right after the one to the AP is working fine and can be observed in the console. So the call seems to work without error message. That suggests an issue inside the sim. Why all the other events work is strange.

Note that setting ``K:A32NX.FCU_TO_AP_HDG_PUSH`` works but not ``K:A32NX.FCU_TO_AP_HDG_PULL``, and as noted ``K:HEADING_SLOT_INDEX_SET`` always works. Also, reloading the js in A320_Neo_FCU.js using either Coherent GT Debugger (reload ignoring cache) or WebUIDevKit resolves the issue entirely.

**Comment by 2hwk** [comment] 2021-08-08 03:15
Console log on first compile
![image](https://user-images.githubusercontent.com/15316958/128619540-dcfce902-d69c-4d67-be2d-143b0ac8e881.png)

**Comment by Blue1308** [comment] 2021-08-08 06:42
Hi,
Just an observation on my side, with a flightplan simbrief in MCDU.
If I don't arm nav mode before take-off, HDG works correctly during my full flight. 
If Nav mode is arm before take off HDG don't work at all 

Christian

**Comment by aguther** [comment] 2021-08-08 07:16
Please reload the flight right after spawning when you’ve updated the A32NX. Then it should work.

**Comment by Blue1308** [comment] 2021-08-08 07:34
> Please reload the flight right after spawning when you’ve updated the A32NX. Then it should work.

Ok great thanks it works. Should we do it with each new update?

**Comment by sidnov** [comment] 2021-08-08 07:42
>  
> > Please reload the flight right after spawning when you’ve updated the A32NX. Then it should work.
> 
> Ok great thanks it works. Should we do it with each new update?
> 
> 
> 

We are investigating the issue. We'll update you once there is an update

**Comment by 2hwk** [comment] 2021-08-08 16:40
Heads up, we have identified the problem. We actually have a workaround that solves the issue, but a proper rework and fix is in the pipeline.

**Comment by hawaikicr** [comment] 2021-08-08 16:47
Avise us when do it? 


Stefano Miglioli


From my mobile with outlook

Softworld snc

Cremona

www.softworld.info

**Comment by 2hwk** [comment] 2021-08-08 16:49
> Avise us when do it? Stefano Miglioli From my mobile with outlook Softworld snc Cremona [www.softworld.info](http://www.softworld.info)

I can't give you a timeline, but in any case we know what the issue is and how to fix it, it's just we will need to implement and then test the changes before this will go live.  It will be in the dev version as soon as possible.

**Comment by hawaikicr** [comment] 2021-08-08 17:11
Thank you very much!!! 


Stefano Miglioli


From my mobile with outlook

Softworld snc

Cremona

www.softworld.info

**Comment by aguther** [comment] 2021-08-08 17:33
As it can be seen a PR is filed that should solve the issue. It needs to go through the review and testing and can be merged then.

**Closed** 2021-08-09 04:40 UTC
Labels: Bug

**Comment by hawaikicr** [comment] 2021-08-12 22:10
Hi guys! the problem with new update is solved? do you advise us when it's ok? so i can upgrade! 
Do you know when the new A380 is coming out? Thanks!!! Good Job!
