### ISSUE TITLE
[BUG] MCDU - ND  constraint discrepancy

### ISSUE THREAD

**Issue by L-1011** [flybywiresim/a32nx#2223] opened 2020-12-04 15:31 UTC
**Mod Version**

**Describe the bug**
MCDU Altitude constraint dont appear correctly on ND 

**To Reproduce**
1. Start a flight
2. Load sid/star and FPL
3. try to change ALT constraint in STAR

**Expected behavior**
Altitude constraint, when update, dont appear correctly on ND 

**Actual behavior**
 during cruise and descend 

**References**
 If applicable, add screenshots or videos to help explain your problem. 

**Additional context**
 https://ibb.co/wcTdVR4

Was this working before/when did the issue start occurring?:
nope, constraints are a new feature

Is this a problem in the vanilla unmodded game?:
I dont know, i think no because vanilla dont have constraints

Discord username (if different from GitHub): L-1011

![1](https://user-images.githubusercontent.com/70903455/101182212-16097680-364e-11eb-80c1-f671d888018f.JPG)

**Comment by MisterChocker** [comment] 2020-12-04 15:40
duplicate of #2165

**Closed** 2020-12-04 15:52 UTC
Labels: Bug
