### ISSUE TITLE
[BUG] CTD flying around / staying at VHHH

### ISSUE THREAD

**Issue by HeFi84** [flybywiresim/a32nx#2706] opened 2020-12-25 15:06 UTC
**Mod Version**
"master"

**Describe the bug**
CTD after staying or flying around VHHH

**To Reproduce**
1. Cold an dark start at Gate 160 at VHHH using no other PlugIn and fbw liverie
2. Realtime data and weather (which mainly is at night in my cases)
3. CTD withing seconds after powering up elec

**Expected behavior**

**Actual behavior**
CTD

**References**

**Additional context**
Latest Version of MSFS. CTD happened after last MSFS Update, no other 3rd Party PlugIns in use. Works fine with standard MSFS A320 Version

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by dhkim0800** [comment] 2020-12-25 15:56
Can you reproduce it?

**Comment by HeFi84** [comment] 2020-12-25 16:03
Yes, happens every time. Reinstalled the complete game, still having this issue only with the mod installed.

**Comment by Benjozork** [comment] 2020-12-25 18:32
Cannot reproduce using provided steps as of `da40f0d1`.

Also,

**Mod Version**

"master"

The template asks you to provide contents of the `build-info.json` file in your A32NX folder of the Community folder. Please provide that info.

**Comment by HeFi84** [comment] 2020-12-25 21:07
{
  "built": "2020-12-23T05:49:09+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}

**Comment by Benjozork** [comment] 2020-12-25 21:26
Can you try updating your dev build ?

I tried with the latest, followed your steps and I got no crashes.

weird.

**Comment by Benjozork** [comment] 2020-12-26 22:23
Do you use FSUIPC ?

**Comment by IcedLemonTea** [comment] 2020-12-27 10:54
> Do you use FSUIPC or SLC ?

Just to add to this, if you are using FSUIPC 7.0.0, try updating it to 7.0.3 because that resolved my CTD's which happened on every single flight.

**Comment by marci1229** [comment] 2020-12-28 15:03
I also has CTD every single flight. I'm using FSUIPC and also Self loading cargo. Cant handle a single flight.

**Comment by Watsi01** [comment] 2020-12-28 20:51
Watching the flightsimforum, it seems there could be a bug with simconnect. Many people have CTDs using external tools like FSUIPC, LittleNavMap, etc. (me too).

**Comment by MisterChocker** [comment] 2020-12-31 06:38
duplicate of #1137

**Closed by MisterChocker** 2020-12-31 06:38 UTC
Labels: Bug, Waiting For Response
