### ISSUE TITLE
Make baggage weight optional

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#6253] opened 2021-11-27 07:25 UTC
### Aircraft Version

Development

### Description

thank you for the new weight and balance model and cargo load feature.

But please split passengers and bag weight. Let us allow to board passengers only (avg weight 87kg per pax) and Bag to cargo.

If i select 140 passengers, there are randomly the weight of 140 Bags in the cargo hold. The only possible thing is to ADD seperate cargo weight. 

not every Pax travel with Bags :) 

so, it would be awesome, if we can select passengers WITHOUT Bags. And Add the baggage weight for the flight to the hold weight.

### References (optional)

latest weight and balance feature

**Comment by tabramowicz** [comment] 2021-11-27 15:53
I think it would be nice to add Payload option to EFB - set options like no. of passengers and baggage there and then sent them to MCDU.

**Comment by tracernz** [comment] 2021-11-28 05:48
We need to keep SimBrief and how it handles baggage etc. in mind when we're designing the loading system.

**Comment by btdc00** [comment] 2021-11-28 10:12
I really appreciate all the work I am amazed every single update, but this weight management.. I can't take it, don't like at all

**Comment by donstim** [comment] 2021-12-01 05:30
Looks like a duplicate of #5937

**Comment by donstim** [comment] 2021-12-10 19:56
@andrejetcat Can you delete issue #5937 so we don't have duplicate issues?

We are in discussion with Navigraph about implementing an explicit per passenger baggage weight in Simbrief.

**Comment by andrejetcat** [comment] 2021-12-11 10:53
@donstim done! I only found the option to "close" it instead of delete it :(

**Comment by donstim** [comment] 2022-01-13 01:06
@andrejetcat Thanks for your continued patience with this. Our coordination with Navigraph on this issue has resulted in the addition of separate passenger and baggage weights in Simbrief profiles. Although at least for now, the number of bags will be set equal to the number of passengers (unless a TOW restriction requires reducing the payload), you will be able to adjust the per passenger baggage weight to hopefully accomplish what you are wanting to do.

It will take some time for the code in our loading process to be changed and QA'd to implement these recent Simbrief changes.

**Comment by sidnov** [comment] 2022-02-21 10:24
@andrejetcat The update is pending to be reviewed and tested in #6701 , but you can take a look at how the updated system works. Simbrief now allows for custom per-passenger and per-baggage weight. More flexibility such as number of bags will come eventually in the new EFB update

**Comment by Swaluver88** [comment] 2022-02-21 11:30
I believe the correct terms would be considered "simbrief can no handle non standard weight" 

Right now winter normal pax weights are 210lbs with average bag weights at 32lbs. 
How lever non standard weights are variables per pax and not just an average like the winter normal pax weights

**Comment by andrejetcat** [comment] 2022-02-21 11:38
I think that there is a fundamental missunderstanding.

I don´t want to set "average weight" 
I want to have the option to set the passenger weigt seperately from the baggage weight in the W&B section of the MCDU.
So, that it is possible to do a flight with "only" passengers and without bags and also with baggages.
E.G. a domestic flight with 100 Passengers with a weight of 8700kg. No one have a Bag, so I want to set the Baggage weight to 0 kg. Thats not possible today. when I select select 100 PAX, the "cargo" weight is everytime above 0. 
 Sorry, when i discribe it a way to complicated.

**Comment by donstim** [comment] 2022-02-21 20:34
@andrejetcat When this PR is implemented, you will be able to set passenger weight and baggage weight separately, but for now you must use Simbrief to do that. Doing so within the A32NX (i.e., without Simbrief) will be added when the weight and balance loading process is moved over to the EFB. For now, if you don't want to use Simbrief, you can set the cargo hold weight to 0 if you wish, but the per passenger weight is hard coded at 84 kg/passenger. If you want around 8700 kg of passengers, you would need to load 103 or 104 passengers.

**Comment by andrejetcat** [comment] 2022-02-21 22:12
Got it! :-) thank you ! I'm very looking forward and thank you for all your hard work!

**Closed** 2022-03-23 14:09 UTC
Labels: Request, Flight Model
