### ISSUE TITLE
Ability to select 2nd Autopilot 

### ISSUE THREAD

**Issue by dogrokket** [flybywiresim/a32nx#1890] opened 2020-11-13 04:09 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**I may have missed this, but when flying an ILS, it is customary to select both autopilots; used for auto land, but if this is not implemented yet, it would be more realistic. 

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment] 2020-11-13 04:33
Duplicate of #119

**Closed by Benjozork** 2020-11-13 04:33 UTC
Labels: Enhancement
