### ISSUE TITLE
Options not saving/loading. Unable to use CLR function in F-PLN in MCDU

### ISSUE THREAD

**Issue by theersink** [flybywiresim/a32nx#4358] opened 2021-04-09 03:33 UTC
**Mod Version**

 "built": "2021-04-08T20:50:36+00:00",
  "ref": "master",
  "sha": "abb2d141e1cd394588bdf4a290cb9972f165db7a",
  "actor": "MisterChocker",
  "event_name": "manual"

**Describe the bug**

LBS and Baro options do not save/load on entry to the sim. Changing from KGS to LBS within options does not do anything. No change to displayed contents and upon scene change the MCDU options page reverts back to KGS. I did not get far enough to test Baro effectively. 

The CLR function to delete waypoints is also not working. Pressing CLR and then the button to the left of the waypoint just takes you into the waypoint details screen.

**To Reproduce**

(NOTE: Installing new version has never reverted LBS or Baro options before. Starting sim this time both were reverted to default values from what I had set)
1. Start cold and dark, turned on Batts and Ext power. Loaded fuel and payload via MCDU from simbrief plan.

2. Started APU, noticed weight was in KGS. Went to options in MCDU and attempted to switch to LBS, I got the indication  on the screen but the weight stayed in KGS. Changed to external view and switched a few internal views. When I came back to the options in the MCDU the setting had reverted to KGS from LBS. Proceeded with startup.

3. Loaded flightplan from simbrief. Loaded fine. Entered SID from KBOS and as always it inserted a USR waypoint just after end of runway. Went to F-PLN page to delete USR, pressed CLR,  I get the amber CLR indication on the bottom and then press the button to the left of the CLR waypoint and instead of giving me the indication on the bottom 2 lines to either erase or Insert it just took me into the waypoint details. At this point I tried deleting other waypoints in the route and was not able to using the process described (As far as I am aware that has not changed, please correct me if I am mistaken). Quit sim and check Discord help and current github for similar issue.

**Expected behavior**

1. I expected the options I had set on prev flights to still be in effect as they have been for probably months I have been playing.
2. Expected changing options from KGS to LBS to reflect in EFB and not revert on scene change.
3. Expected to be able to clear/delete waypoints as I had in the past via the CLR button and the the button to the left of the waypoint line.

**Actual behavior**

1. Started APU, noticed weight was in KGS. Went to options in MCDU and attempted to switch to LBS, I got the indication  on the screen but the weight stayed in KGS. Changed to external view and switched a few internal views. When I came back to the options in the MCDU the setting had reverted to KGS from LBS.
2. pressed CLR,  I get the amber CLR indication on the bottom and then press the button to the left of the CLR waypoint and instead of giving me the indication on the bottom 2 lines to either erase or Insert it just took me into the waypoint details.

**References**

**Additional context**

Was this working before/when did the issue start occurring? Everything above was working as of my flight last night. Prior to this flight I updated the dev version which had most recent PR #4305 

Is this a problem in the vanilla unmodded game? N/A, reported features are FBW additions

Discord username (if different from GitHub): theersink, same as git

**Comment by felixharnstrom** [comment] 2021-04-09 07:05
Regarding your second point: Did you reload the aircraft (simply restarting the flight works fine) after changing the units? The units are by design only loaded at startup, so simply changing views is not enough.

**Comment by tellurics** [comment] 2021-04-09 10:54
The CLR button is a know issue, probably a duplicate of #1388. This will be fixed with the new custom autopilot.

**Comment by tracernz** [comment] 2021-04-09 11:33
Please open separate issues for different issues, and also check for existing issues.
1 = expected behaviour (you will get a scratchpad message advising you to reload the aircraft when changing units), since https://github.com/flybywiresim/a32nx/pull/2824
2 = Known issue #1388. May be fixed by new flightplan manager in future.

**Closed by tracernz** 2021-04-09 11:33 UTC
Labels: Bug

**Comment by theersink** [comment] 2021-04-09 14:29
> The CLR button is a known issue, probably a duplicate of #1388. This will be fixed with the new custom autopilot.

No. I was not able to delete ANY waypoint in the route. It had worked prior to mentioned PR.

**Comment by theersink** [comment] 2021-04-09 14:32
> Please open separate issues for different issues, and also check for existing issues.
> 1 = expected behaviour (you will get a scratchpad message advising you to reload the aircraft when changing units), since #2824
> 2 = Known issue #1388. May be fixed by new flightplan manager in future.

1. I think you misunderstood the issue. It never loaded the LBS in the begging which it had been set to on prior flight. I did not get any scratchcard messages about reloading. It simply did nothing other than change the field.
