### ISSUE TITLE
[BUG] Screens wont turn on

### ISSUE THREAD

**Issue by Mischa1414** [flybywiresim/a32nx#1040] opened 2020-10-02 12:42 UTC
**Mod Version** 

0.3.1

**Describe the bug**

The screens wont turn on

**To Reproduce**

1. Trun on Master Battery 1&2
2. Screens dont turn on
3.

**Expected behavior**

All screens should turn on

**Actual behavior**

The screens wont turn on and ist stays in cold and dark

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Shmizmin** [comment] 2020-10-02 13:54
I may be incorrect, but I'm pretty sure that the PFD, NAV, and ECAM screens will not turn on with just battery power in the real airplane. If I recall correctly this requires an APU gen, engine gen, or ground power to do so.

**Comment by Mischa1414** [comment] 2020-10-02 14:32
@Shmizmin now i tried it but still nothing

**Comment by Mischa1414** [comment] 2020-10-02 14:33
or how lond does it takes till the screens turn on

**Comment by Pleasure0102** [comment] 2020-10-02 15:39
turn of live traffic, and set planes to generic planes, they are causing the issue that some people can't see the screens. This is due to asobo not FBW

**Comment by NathanInnes** [comment] 2020-10-02 17:14
Do they turn on with APU or Ground Power or any powerplant?

If you're trying to use battery power alone this will not work and is intended to be that way.

**Comment by lousybyte** [comment] 2020-10-02 21:00
From what I noticed, this happens if you turn batteries on before external power. Does not happen on vanilla.

**Comment by Hoisig** [comment] 2020-10-03 17:37
Nope, nothing happens. Having the same issue. Before world update everything was fine and now screens won't turn on... It seems that the plane simply has no electricity. I can't use atc, turn on lights or whatsoever.

**Comment by NathanInnes** [comment] 2020-10-03 19:07
Try running build.py

**Comment by Hoisig** [comment] 2020-10-04 13:05
> Try running build.py

What does that mean? Sorry ^^

**Comment by NathanInnes** [comment] 2020-10-04 14:13
Try typing "?elec" on our discord. The bot will send you a list of troubleshooting guides. Worked for a lot of people.

**Comment by OFC1983** [comment] 2020-10-05 12:42
I had the same issue. I fixed it the following way: Deleted the A32NX Folder and all the installed liveries. Also deleted the Rolling Cache File with the CCC ending. After that started Msfs. After successful loading exited the game, placed the A32NX and the liveries back in the Community folder and then it worked for me. Took me a while to figure it out as the loading screens are very time consuming...

**Comment by Benjozork** [comment] 2020-10-10 17:32
Closing as issues seems to have been worked around and is a duplicate of an Asobo bug, #718.

**Closed by Benjozork** 2020-10-10 17:32 UTC
Labels: Bug, Screens
