### ISSUE TITLE
Autobrake disengage when breaking on ground pre-departure

### ISSUE THREAD

**Issue by RomeoMikeFox** [flybywiresim/a32nx#4891] opened 2021-05-24 12:33 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-24T01:02:09+00:00",
  "ref": "master",
  "sha": "3086a27044464e5d1b44c7eeb029df24c10f966a",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

In the before takeoff flow, autobrake is set to max. However, whenever I brake the plane during taxi or line up, autobrake disengages.

### Expected behavior

Autobrake should not disengage when braking the plane upon taxi/line-up. It should stay on the selected level (MAX for T/O).

### Steps to reproduce

Start-up the plane, for taxi.
During taxi, set autobrake to max.
Brake the plane to make a turn or to stop once lined up
Autobrake will disengage.

**Comment by sidnov** [comment] 2021-05-24 12:35
Duplicate of #4771

**Closed** 2021-05-24 12:36 UTC
Labels: Bug
