### ISSUE TITLE
[BUG] Aircraft does not follow the route correctly.

### ISSUE THREAD

**Issue by Silvaronn** [flybywiresim/a32nx#3447] opened 2021-02-09 18:45 UTC
**Mod Version**

A32nx Custom FBW, downloaded by the installer

**Describe the bug**

 During the approach the aircraft stops following the flight plan and goes straight to the airport.

**To Reproduce**

1.Whenever he arrives at the STAR at the destination airport, he stops following the flight plan, going straight to the airport.
2.
3.

**Expected behavior**

Follow correctly or flight plan, same as before.

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

it was functioning normally until last Sunday.

Is this a problem in the vanilla unmodded game?

This problem is with the mod. In experimental versions.

Discord username (if different from GitHub): 

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment] 2021-02-09 18:48
Duplicate of #939 and doesn't follow template

**Closed by Benjozork** 2021-02-09 18:48 UTC
Labels: Bug

**Comment by Joopiest** [comment] 2021-02-13 09:43
I experienced the same issue. Has it been solved yet?

**Comment by Benjozork** [comment] 2021-02-13 16:31
Please read the linked issue.
