### ISSUE TITLE
[BUG] HDG AUTOPILOT NOT WORK

### ISSUE THREAD

**Issue by lorenlan** [flybywiresim/a32nx#2146] opened 2020-11-30 21:06 UTC
**Mod Version**
RELEASE 4.1 AND MASTER BUILD

**Describe the bug**
AFTER UPDATE OF MSFS WITH LAST MASTER BUILD RELEASE, THE HDG ATUOPILOT NOT WORK IN MANAGED OR SELECTED MODE

**To Reproduce**

1.
2.
3.

**Expected behavior**
WHEN ACTIVATE THE AUTOPILOT HDG I EXPECT THAT THE PLANE FOLLOW THE ROUTE

**Actual behavior**
WHEN HDG IS ACTIVATED NOTHING HAPPEN, THE PLANE GOES STRAIGHT ON AND I'LL TURN MANUALLY THA PLANE

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment] 2020-11-30 21:25
Duplicate of #2089

**Closed by Benjozork** 2020-11-30 21:25 UTC
Labels: Bug
