### ISSUE TITLE
[BUG] Airplane Erratic Climb Behavior

### ISSUE THREAD

**Issue by sef3613** [flybywiresim/a32nx#1158] opened 2020-10-07 02:14 UTC
**Mod Version**

Latest

**Describe the bug**

Super erratic climb behavior with AP1 on in open climb. Watch video to see it pitch way up then level twice before even capturing the altitude.
**To Reproduce**

1. Use open climb shortly after takeoff.
2.
3.

**Expected behavior**

Smoothly climbs.

**Actual behavior**

See video, super erratic. Passengers would definitely be throwing up. 

**References**

https://www.youtube.com/watch?v=L3O21dhIA4Y

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-10-07 02:46
Thanks for your bug report. Please fill in this information: 🙂 

> Was this working before/when did the issue start occurring?
>
> Is this a problem in the vanilla unmodded game?

**Comment by CoffeePanda0** [comment] 2020-10-07 19:21
Can confirm, me and a friend have both had this same issue since the latest asobo update. The plane seems to pitch up to sometimes even 8000fpm climb, resulting in a stall and then nosediving. Happens on every single takeoff until past the first few waypoints

**Comment by MisterChocker** [comment] 2020-10-08 22:06
This might also be caused by the overpowered engines. I don't know tho if they have been improved since.

**Comment by MisterChocker** [comment] 2020-12-31 06:29
This has been fixed by game updates

**Closed by MisterChocker** 2020-12-31 06:29 UTC
Labels: Autopilot, Bug, Plane Performance
