### ISSUE TITLE
[BUG] Cant go to FL380

### ISSUE THREAD

**Issue by mixMugz** [flybywiresim/a32nx#933] opened 2020-09-27 22:39 UTC
**Mod Version**
master 0.3.0

**Describe the bug**
ATC send me to FL380 from FL360. Start to change LVL but cant. Aircraft lose speed and lost flight level. 

**To Reproduce**
1. Start with full fuel and zero payload
2. Go to FL360 then FL380
3. Possible front WIND is an issue

**Expected behavior**
FL380 like ATC said

**Actual behavior**
Cant go to FL380

**References**
![image](https://user-images.githubusercontent.com/17923916/94377505-012ed500-012b-11eb-9740-0fadaf4e9750.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
I dint's see this problem before

Discord username (if different from GitHub):
Mugz#6174

**Comment by medic6810** [comment] 2020-09-28 01:19
Looks like there was quite a bit of moisture in the air around you at cruise. Wing and Engine Anti-Ice is not annunciated on the ECAM. Looks like it was off? If so, you will find climb performance is greatly degraded due to ice buildup. This is a feature, not a bug!

The bug is with MSFS — because we usually cruise above the tropopause, encountering moisture at cruise is quite rare. MSFS seems to put clouds up at cruise quite a bit.

**Comment by mixMugz** [comment] 2020-09-28 07:54
Yes it's off. But i didnt see any ice on a plane. Ok. I will check with full antiice on

**Comment by mixMugz** [comment] 2020-09-28 15:09
Now all ok. Only two problems.
1. High angle autopilot at climb (from beginig)
2. Strange speed at cruise its little bit high?
![image](https://user-images.githubusercontent.com/17923916/94450233-af7f5c80-01b5-11eb-96a5-dd838c6fb279.png)

**Comment by lousybyte** [comment] 2020-10-02 08:34
There are already other reports opened for those issues, if the original issue is solved you can close this.

**Closed** 2020-10-03 11:56 UTC
Labels: Bug, Plane Performance
