### ISSUE TITLE
[BUG] COM frequency does not update with in-game button function

### ISSUE THREAD

**Issue by FoxtrotSierra6829** [flybywiresim/a32nx#2709] opened 2020-12-25 16:35 UTC
**Mod Version**
0.5.1 Stable & Dev
{
  "built": "2020-12-25T10:12:36+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benjamin Dupont <benjozorkfr@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**
The standby frequency does not change, if you push a button mapped to increase or decrease the frequency. Neither whole, nor fract nor fract,carry mode works. The frequency is also not updated in ATC menu if you switch for crosscheck (displays what was the standby frequency before), so it's not an issue with the displays.

**To Reproduce**
1. Launch FBW A32NX
2. Map any button to Increase[Decrease] COM1 (Whole[Fract][Fract,Carry])
3. Press the buttons
4. See nothing happening

**Expected behavior**
Standby Frequency should increase[decrease] by xx1.xxx on whole, increase[decrease] by xxx.x25 on fract, and increase[decrease] by xxx.x25 with increasing[decreasing] xx1.xxx when applicable on fract, carry

**Actual behavior**
Nothing happening

**Additional context**
Might be related to #1079 

Was this working before/when did the issue start occurring?
unknown

Is this a problem in the vanilla unmodded game?
No (as long as you are not stuck with 124.850)

Discord username (if different from GitHub):
Foxtrot Sierra#6420

**Comment by FoxtrotSierra6829** [comment] 2020-12-25 16:55
Sidenote: If you need to redo the function as a whole, please consider fract to be changing by 8.33khz instead of 25khz

**Comment by Benjozork** [comment] 2020-12-25 18:02
Duplicate of #2644

**Comment by FoxtrotSierra6829** [comment] 2020-12-25 23:58
> 
> 
> Duplicate of #2644
It's not. This applies if you are able to change it with your mouse wheel but are unable to change it with the function assigned to a button

**Comment by Benjozork** [comment] 2020-12-26 00:01
Sorry, I read your post wrong.

**Comment by FoxtrotSierra6829** [comment] 2020-12-26 00:03
No problem

**Comment by rzimin** [comment] 2020-12-26 09:31
This is very close related to #1079 

Both MSFS options and external hdw using 
COM_STBY_RADIO_SWAP and COM_RADIO_WHOLE_INC/DEC events and this is where it starts to be interesting. When you assign any shortcut in sim options it would call the above events. However airbus is expecting the following

![image](https://user-images.githubusercontent.com/2657639/103148921-f01b5180-4775-11eb-8459-9fe6f715dbc2.png)

and as result not showing values on radio panel no matter what keyboard shortcuts you are using.

On top of that, even if you try to pass MSFS:COM_STBY_RADIO_SET_HZ event directly - it simply ignores it as well as setting COM ACTIVE FREQUENCY:1 values.

Very strange.

**Comment by FoxtrotSierra6829** [comment] 2020-12-26 11:53
Since this is not an issue on the vanilla plane, you should just be able to copy the methods from there then, shouldn't you?

**Comment by Benjozork** [comment] 2020-12-26 16:57
This code does not decide which events the plane listens to.

We cannot change what events influence the COM frequency.

It's something else and I'm still looking into it.

**Comment by Benjozork** [comment] 2020-12-26 17:37
Can you verify that the frequency does not update in the ATC window under any circumstances with the radio panel ?

**Comment by FoxtrotSierra6829** [comment] 2020-12-26 21:07
It displays what the radio panel shows, so both are not influenced by the pressing the button - mentioned this to state it's not an issue with the displaying of it, but rather that it does not change at all

**Closed** 2021-01-31 09:31 UTC
Labels: Bug
