### ISSUE TITLE
[BUG] Constant banking to the right until loss of control

### ISSUE THREAD

**Issue by Gsproson** [flybywiresim/a32nx#1365] opened 2020-10-15 12:12 UTC
**Mod Version**
Master
2020-10-15T01:38:50+00:00

**Describe the bug**
Once Autopilot is engaged, aircraft starts banking to the right, will continue past 90 degress and eventually nose dives. Happened unger NAV or HDG mode.

**To Reproduce**
1 - Load aircraft in free flight
2 - Load a flight plan of choice or just leave option blank
3 - When airborne, select AP1 and pull the Heading knob for selected mode or push for managed mode if flightplan is in the FMGC

**Expected behavior**
Aircraft will start to roll to the right, will continue to do so until manual control is taken.

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by sml-joyo** [comment] 2020-10-15 12:35
This is an issue w/ the base game itself. Apparently if you set the deadzone for your joystick or controller to 5/10/15/...% in the settings then the issue will be resolved.

**Comment by lousybyte** [comment] 2020-10-15 17:35
Duplicate of #1032.

**Closed by lousybyte** 2020-10-15 17:35 UTC
Labels: Autopilot, Bug, Duplicate
