### ISSUE TITLE
TCAS on ND

### ISSUE THREAD

**Issue by Parshva8888** [flybywiresim/a32nx#4843] opened 2021-05-17 13:55 UTC
### Aircraft Version

Development

### Description

Flying on servers like Vatsim or IVAO on places like Gatwick with a large amount of traffic it would be a blessing to see other aircraft their rate of climb decent and a traffic avoidance system .

### References (optional)

![250px-Tcas_EU-Flysafe](https://user-images.githubusercontent.com/83544814/118500691-a1cb1700-b745-11eb-95be-f4fb96532bed.jpg)

### Discord Username (optional)

Parshva8888#1339

**Comment by scoopscode** [comment] 2021-05-17 13:57
Duplicate of #130

**Closed** 2021-05-17 14:36 UTC
Labels: Duplicate
