### ISSUE TITLE
[BUG] Runway missing in the ND

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2061] opened 2020-11-22 20:29 UTC
**Mod Version**
Latest master branch and 4.1

**Describe the bug**
Hey there , i think that , as it is in the real life , once you finish the flight plan or selec the runway for taking off ,it is shown in the ND 

**To Reproduce**

1.Finish the FP.
2.
3.

**Expected behavior**
The runway should appear in the ND

**Actual behavior**
Only the route is shown

**References**

![image](https://user-images.githubusercontent.com/74787268/99916312-c485f100-2d09-11eb-91a7-b2e612bbb697.png)

**Additional context**

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by ilyeshammadi** [comment] 2020-11-24 03:05
This is not a bug but more of an Enhancement since this feature was never implemented before.

**Comment by LoungeFlyZ** [comment] 2020-12-03 00:37
Looks to be a dupe of #1713

**Comment by Benjozork** [comment] 2020-12-03 00:47
Duplicate of #1713

**Closed by Benjozork** 2020-12-03 00:47 UTC
Labels: Enhancement
