### ISSUE TITLE
Speed/Heading/ALT knob dials spin out of control

### ISSUE THREAD

**Issue by chrismay1981** [flybywiresim/a32nx#1891] opened 2020-11-13 06:38 UTC
**Mod Version**

I am using the Dev version

**Describe the bug**

When i turn any of the know dials - work fine then start spinning out of control. Makes it difficult to fly a course as it overshoots then undershoots heading

**To Reproduce**

1. turning the knobs
2.
3.

**Expected behavior**

work normal

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment] 2020-11-13 14:27
> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Also, duplicate of #1664

**Closed by Benjozork** 2020-11-13 14:27 UTC
Labels: Bug
