### ISSUE TITLE
tcas not showing other traffic

### ISSUE THREAD

**Issue by airfirefighter** [flybywiresim/a32nx#4477] opened 2021-04-18 06:04 UTC
**Mod Version**

```json
"built": "2021-04-16T21:01:28+00:00",
  "ref": "master",
  "sha": "b19333584e36344376068945b3604b4a746f9543",
  "actor": "myselfaaryan",
  "event_name": "manual"

```

**Describe the bug**
usually tcas dont show other traffic in high  altitudes but some times i dont know how it works at least if u dont increase the ND distance more than 20 nm in view, in pilot side

**To Reproduce**

1.to keep having traffic image on ND at FL370 I didnt change the distance of 20nm view.more than that its dissappear.
2.
3.

**Expected behavior**
be able to have traffic warning in all flight levels and even if u select more than 20nm  

**Actual behavior**
in high altitudes tcas warning dont saw other traffic but some times it dose if u have without change from the start of the trip the distance of the ND more than 20mn

**References**
![Microsoft Flight Simulator 17_4_2021 11_46_39](https://user-images.githubusercontent.com/71919620/115135944-0ef36b80-a025-11eb-8687-800ed8a2f01a.png)

**Comment by airfirefighter** [comment] 2021-04-18 06:11
did i make something wrong in descriptions? the presentation seems strange this time!!

**Comment by tracernz** [comment] 2021-04-18 06:13
> 
> 
> did i make something wrong in descriptions? the presentation seems strange this time!!

Yeah, I fixed it up. You deleted the `\`\`\`json` part before the build info stuff (click ... then edit to see how it looks now).

**Comment by MisterChocker** [comment] 2021-04-18 09:16
We are currently limited by the simulator itself, once we have a good api to work with I am sure we can solve the issue.
Duplicate of #130

**Closed by MisterChocker** 2021-04-18 09:16 UTC
Labels: Bug

**Comment by airfirefighter** [comment] 2021-04-18 11:59
> We are currently limited by the simulator itself, once we have a good api to work with I am sure we can solve the issue.
> Duplicate of #130

its true its the same but i will like to add as i mention before if that helps that some times its working as u can see in image if in pilot nd u don't add more that 20 nm range in nd

**Comment by airfirefighter** [comment] 2021-04-18 12:00
> > did i make something wrong in descriptions? the presentation seems strange this time!!
> 
> Yeah, I fixed it up. You deleted the `` ```json `` part before the build info stuff (click ... then edit to see how it looks now).

thanks i will try not to remake the same mistake sorry
