### ISSUE TITLE
Outer Fuel Tank Valves Don't Open[BUG]

### ISSUE THREAD

**Issue by MrGoodbytes98** [flybywiresim/a32nx#1307] opened 2020-10-14 01:39 UTC
*Latest master updated on 2020-10-14T01:18:02+00:00
Build Info: 
built: 2020-10-13T22:12:21+00:00
ref: refs/heads/master
sha: 2ee7d20a1d28d14643d22f13ac242a711a73861c
actor: lukecologne
event_name: push

**Describe the bug**
During flight when Center/Inner tanks are empty, no fuel is transferred from the outer fuel tanks leading to a dual engine failure. 

**To Reproduce**
1. Load flight with low fuel in center and inner tanks
2. Wait until center and inner tanks are completely empty, observe engine failure shortly after. 

**Expected behavior**
Outer fuel tank valves should open and allow fuel into the other tanks. 

**Actual behavior**
Valves don't open leading to engine failure.

**References**
![Screenshot (410)](https://user-images.githubusercontent.com/72842237/95933262-60c3ec00-0d8b-11eb-8e9c-bc2bac56baec.png)
Screenshot showing how overhead panel was setup prior to issue. 
![Screenshot (414)](https://user-images.githubusercontent.com/72842237/95933282-6b7e8100-0d8b-11eb-940f-c20682d13e7e.png)
Screenshot showing engine failure and fuel remaining in outer tanks.

I'm not entirely sure if this is a new issue, or if this issue is present in the vanilla version of the game. This is the first time I've completely emptied the center/inner tanks. I've successfully replicated this issue twice.

**Comment by aviationenthusiast** [comment] 2020-10-14 04:22
#1115 same thing here as well.

**Comment by bouill** [comment] 2020-10-14 07:04
For sure the bug is real, the 1.2t of fuel of outer tanks never empty in the inners.
But anyways, who wants to have a realistic airplane to simulate realistic operations, and wants to land with less than 30min fuel reserve?
Maybe this bug should not be corrected ;)

**Comment by nobodyn0se** [comment] 2020-10-14 07:10
Issue present in vanilla version too.

**Comment by lukecologne** [comment] 2020-11-10 01:07
Can't reproduce, was likely fixed in an Asobo update.

**Closed by lukecologne** 2020-11-10 01:07 UTC
Labels: Bug, Plane Performance

**Comment by IllicLanthresh** [comment] 2024-09-15 21:20
had this happen to me today, loaded 1800 kgs of fuel and the outer tanks never feed the inner ones, ran out of fuel mid air.
