### ISSUE TITLE
Cost Index 

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#7501] opened 2022-09-24 00:55 UTC
### Aircraft Version

Experimental

### Build info

```json
experimental latest
```

### Describe the bug

Does not matter if i set 0 to CI or 999 speed wont move at all....

### Expected behavior

Implement a propper cost index 

### Steps to reproduce

1. Set in INIT page while flying and ser a random number and test it

**Comment by tracernz** [comment] 2022-09-24 02:37
Duplicate of #345.

**Closed by tracernz** 2022-09-24 02:37 UTC
Labels: Bug
