### ISSUE TITLE
[BUG] FD and ND light screens reflections

### ISSUE THREAD

**Issue by Gusineas** [flybywiresim/a32nx#2230] opened 2020-12-04 23:24 UTC
**Mod Version**
Dev version 2020-12-03T20:40:56+00:00

**Describe the bug**
FD and ND screens are emitting reflection light to the cockpit even dough those are dark and not working when increasing the brightness. Only batteries are on, external power or apu is off.

**To Reproduce**
1. load up the sim in the night
2. Turn on batteries
3. Increase FD and ND screens brightness and check how screens provide light reflection to the cockpit, even though screens are not working yet.

**Expected behavior**
Not to provide FD and ND screen light reflection when increasing screen brightness, yet when those are still off and not working

**Actual behavior**
FD and ND screens provide light reflection on the cockpit when increasing brightness, yet, screen are still off and not showing up any information.

**References**

**Additional context**

Was this working before/when did the issue start occurring? Not, as far as I know

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub): Gusineas#5010

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment] 2020-12-04 23:34
Duplicate of #1300

**Closed** 2020-12-04 23:34 UTC
Labels: Bug, Duplicate
