### ISSUE TITLE
[BUG] MFD not showing current position, and the ND circles are red

### ISSUE THREAD

**Issue by rhpa23** [flybywiresim/a32nx#2474] opened 2020-12-16 23:06 UTC
**Mod Version**
Latest dev version:
{
  "built": "2020-12-16T13:12:05+00:00",
  "ref": "",
  "sha": "",
  "actor": "ThatRedMelon <34657891+ThatRedMelon@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**
When starting cold and dark with a flight plan configured in the Sim the plane finishes the ADIRS aligns but the ND circles are red like the screenshot.

**To Reproduce**

1. Start and plan a flight (EGNT -  EGGW) set a Gate to start cold and dark
2. Start the Sim 
3. Turn on the batteries external power and aligns the ADIRS
4. when the aligns finish the ND circles are red

**Expected behavior**

ND circles are white and  MFD showing the current position

**Actual behavior**

ND circles are red

**References**

![Capturar](https://user-images.githubusercontent.com/4458967/102416965-91b5dc80-3fd9-11eb-8e1e-cc94111d9d24.JPG)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):
rhpa23

**Comment by ThatRedMelon** [comment] 2020-12-16 23:08
Could be related to #2468 but cannot verify right now.

**Comment by ThatRedMelon** [comment] 2020-12-17 11:57
Have tried multiple alignment methods at different airports and could not replicate. What alignment time do you use and how do you use the ND before alignment completes?

**Comment by rhpa23** [comment] 2020-12-17 12:11
What alignment time do you use and how do you use the ND before alignment completes?

I used Fast and Instant alignment. The same result in both. I only reproduce in some airports like EIDW or EGNT, with a flight plan created in FS World Map. The sceneries are the sim default. 
Tested with and without the Navigraph data.
I don't touch any function of the ND before the alignment.
Later I can record a video to help

**Comment by ThatRedMelon** [comment] 2020-12-17 12:12
That would be great as I tried EGNT with all 3 alignments without any result. Thanks

**Comment by pareil6** [comment] 2020-12-17 12:14
Do you have the new WorkingTitle CJ4 beta installed? I saw a brief discussion on Discord suggesting that could be the cause...

**Comment by rhpa23** [comment] 2020-12-17 12:23
No, I don't have the WorkingTitle CJ4 mod installed. These are the Mods that I have installed:

- fs-base-ingamepanels-metar
- fspm-panel-vfrmap
- navigraph-navdata
- unreal-weather-live-metar

**Comment by ThatRedMelon** [comment] 2020-12-17 12:28
Could you try without any mods installed to see if the problem continues? Could be a conflict with one of them

**Comment by rhpa23** [comment] 2020-12-17 12:30
Ok, I will try.

**Comment by Watsi01** [comment] 2020-12-17 12:31
@rhpa23 Did you switch on any of the VOR/NDB switches before alignement? Could you please switch both off and see if the ND stays that way?

**Comment by TheSledge-SLEJ** [comment] 2020-12-17 16:41
This happened to me on entering an RNAV appr into MCDU. Only the pilot ND was affected with red compass outer ring and the red banana thing on plane icon nose. On both NDs the compass and bearing line froze and the bearing line was terminated 50% way to outer ring. Weather and other displays normal except no ILS or landing data came up on appr.

![Screenshot 2020-12-17 095804](https://user-images.githubusercontent.com/74037604/102516344-a43a1f80-4086-11eb-9089-a15aeac14a62.jpg)

**Comment by ThatRedMelon** [comment] 2020-12-17 17:29
Again, I can't verify this even with an RNAV approach at KDOV, if you have navigraph, could you try without it and see if the issue persists?

**Comment by DanP77** [comment] 2020-12-17 18:01
I confirm same error without Navigraph.
Route LOWK - LFKB<
Sistem frizzed by taxing for TO.
Unfrizzed during flight deselecting Constrains, but definitively locked touching FPL in flight.

Same red Arc.
And trying to solve, many inconsistent information on the ND.

**Comment by ThatRedMelon** [comment] 2020-12-17 18:55
Managed to replicate this bug after installing the WorkingTitle CJ4 beta mod, managed to achieve the red lines on the ND, so current solution would be to uninstall the CJ4 mod or downgrade to the stable release.

**Comment by rhpa23** [comment] 2020-12-18 01:09
I found! The issue occurs when choosing the ILS 25 Approach from the UK EGGW Luton. I noticed theses Approach is duplicated in this scenery. It's a scenery bug and I don't know if it's worth it the fix some code in the A32NX to deal with this. I think you can close this issue. Is up to you guys.
Thanks, for the great support.

![Capturar2](https://user-images.githubusercontent.com/4458967/102561812-66ec8680-40b4-11eb-882e-5074a4b270e9.JPG)

**Comment by texpage1** [comment] 2020-12-19 07:01
Same issue here twice. Once on pre-0.5 dev version and once on v0.5 stable version.  Both times on approach then ND suddenly starts picking up ILS and ignores last few approach waypoints.  Freezes ND with red ring and ND becomes non-responsive.  I do have the CJ4 mod so will unload it and try again tomorrow.

**Comment by hotshotp** [comment] 2020-12-20 22:21
> I found! The issue occurs when choosing the ILS 25 Approach from the UK EGGW Luton. I noticed theses Approach is duplicated in this scenery. It's a scenery bug and I don't know if it's worth it the fix some code in the A32NX to deal with this. I think you can close this issue. Is up to you guys.
> Thanks, for the great support.
> 
> ![Capturar2](https://user-images.githubusercontent.com/4458967/102561812-66ec8680-40b4-11eb-882e-5074a4b270e9.JPG)

closing then!

**Closed by hotshotp** 2020-12-20 22:21 UTC
Labels: Bug

**Comment by gersh99** [comment] 2020-12-22 20:12
I can confirm this is still happening. KDCA1 SOOKI4 - SWANN- DQO-  PHLBO3 arrival into ILS 22L at KEWR seems to trigger it repeatedly after entering arrival plan mid-flight. Notably, the VFR map is ALSO frozen. I am going to unload Workingtitle CJ4 and try again.
