### ISSUE TITLE
[BUG] Altitude constraint discrepancy between MCDU and ND

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#2952] opened 2021-01-09 10:25 UTC
**Mod Version**

2021-01-09T07:07:10

**Describe the bug**

During a flight, I see discrepancy between MCDU altitude and Navigation Display for a waypoint.
FL130 on ND and 9000ft for MCDU

![IMG_20210109_111129](https://user-images.githubusercontent.com/5894146/104089179-fd076d00-526c-11eb-9fe9-3c68035e8dd3.png)

**To Reproduce**

1. Define SimBrief Flight Plan between LOWS and LFSB with route. SBG2A SBG KPT L856 ROMIR TRA STR STR8K
2.  Near ALTIK waypoint, see altitude USR and ND and MCDU
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment] 2021-01-09 18:07
Duplicate of #2165

**Closed by MisterChocker** 2021-01-09 18:07 UTC
Labels: Bug
