### ISSUE TITLE
plane jumps left upon touch down[BUG]

### ISSUE THREAD

**Issue by lve0200** [flybywiresim/a32nx#1337] opened 2020-10-14 18:53 UTC
**Mod Version**

 master

**Describe the bug**

Upon touch down, the ACFT has a havy tendency to turn left

**To Reproduce**

1. fly final APP
2. Obeserve behaviour on touch down
3. regardless of weather

**Expected behavior**

Maintain RWY heading, or behave according to cross wind

**Actual behavior**

Unexpected drift to left, regardless of cross wind

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Too much differejnce, to vanilla version, can't say.

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-10-14 19:13
Duplicate of #1173

**Comment by Benjozork** [comment] 2020-10-14 19:13
Duplicate of #1173

**Closed by Benjozork** 2020-10-14 19:13 UTC
Labels: Bug
