### ISSUE TITLE
Using printer causes crash to desktop

### ISSUE THREAD

**Issue by FlightSimJim** [flybywiresim/a32nx#5654] opened 2021-08-15 14:18 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-14T20:40:24+00:00",
  "ref": "master",
  "sha": "2019690439abe7de5735af4730ef51f1d723e8b6",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

Pretty much every time i print the weather it causes a CTD, literally as soon as i press print on the MCDU. One or two times it hasnt, but mostly it does, and again just 5 minutes ago. From now ill refrain from doing so its not the end of the world but such a good feature id love it to be fixed.

Edit: i can see this has been mentioned a few times already so will leave this to be merged etc

### Expected behavior

The weather to be printed with no CTD.

### Steps to reproduce

Simply press print on the MCDU.

**Comment by 2hwk** [comment] 2021-08-15 15:46
Duplicate of https://github.com/flybywiresim/a32nx/issues/5614 Closing

**Closed by 2hwk** 2021-08-15 15:46 UTC
Labels: Bug
