### ISSUE TITLE
[BUG] After engine failure, SPEED disengages when MCT is selected

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#642] opened 2020-09-13 09:42 UTC
**Mod Version**

master

**Describe the bug**

**To Reproduce**

1. Fail/shutdown one engine in flight. 
2. LVR MCT is not shown. 
3. If thrust lever is moved to MCT, MAN MCT shows instead of an A/THR mode. 

**Expected behavior**

LVR MCT should flash. When thrust lever is moved to MCT with engine failed/shutdown, A/THR should remain engaged in prior mode (SPEED etc). 

**Actual behavior**

The A/THR mode disengages and operating engine thrust increases to MCT. Speed target is disregarded by A/THR. This should not happen. 

**References**

http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.14.html

http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.10.html

**Additional context**

See also #641. 

Do note that engine failure may be the result of manual shutdown. Thus, I recommend checking for ENG MASTER off instead of the engine failure simvar.

**Comment by MisterChocker** [comment] 2020-12-31 07:29
duplicate of #641

**Closed by MisterChocker** 2020-12-31 07:29 UTC
Labels: Autopilot, Bug, Bug-Vanilla
