### ISSUE TITLE
Overflight waypoints?

### ISSUE THREAD

**Issue by lonewulf47** [flybywiresim/a32nx#6466] opened 2022-01-02 15:11 UTC
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-01-02T12:14:39+00:00",
  "ref": "experimental",
  "sha": "0dbab2de61272912e9fee4548dccb937e4754b89",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

I realized that with the neweset Experimental build Waypoint Overflight capability was introduced. However as it seems **EVERY** procedureal waypoint is now considered as an **OVERFLIGHT** waypoint !?!?! This results in mostly unuseabe procedures ! Only clearly defined points (in the FMGG marked with a triangle) are **OVERFLIGHT** waypoints. All other are **NOT** !

### Expected behavior

Only **REAL** Overflight Waypoints should be overflown. All other should be handled as normal waypoints.

### Steps to reproduce

Select any procedure and check against real world charts

**Comment by lukecologne** [comment] 2022-01-02 15:24
It would be helpful if you would provide concrete examples of where this is occuring, with screenshots/videos of the ND and MCDU.

**Comment by lukecologne** [comment] 2022-01-02 21:44
There was a bug in the transition reversion code, that caused a normal "fly-by"-Transition to revert to a "fly-over"-Transition erroneously. A fix will be pushed to experimental. I'll close this issue since I assume that this was the cause of your problems, if this is still occuring please comment here again and we can reopen this.

**Closed by lukecologne** 2022-01-02 21:44 UTC
Labels: Bug
