### ISSUE TITLE
[BUG] Different weights between simulator and ECAM

### ISSUE THREAD

**Issue by Nyxtorm** [flybywiresim/a32nx#3279] opened 2021-02-01 12:54 UTC
**Mod Version**

```
{
  "built": "2021-02-01T08:31:10+00:00",
  "ref": "fbw",
  "sha": "d49ec925b9120f46cd116aeef4518aa33cf491b9",
  "actor": "aguther",
  "event_name": "manual"
}
```

**Describe the bug**

It's not a major bug, but when I load the fuel at 100%, the fuel weight displayed is not the same on the ECAM and on the simulator. Same problem in KG and LB

**To Reproduce**
1. Load the A32NX anywhere
2. Set the fuel level at 100%.
3. Compare the weight displayed on the ECAM and the FS2020 weight management window

**Expected behavior**

Same values

**Actual behavior**

A deviation of 3.5 to 4.5% between the sim and ECAM, depending on the unit chosen

**References**

![image](https://user-images.githubusercontent.com/20800786/106460112-1d54d100-6493-11eb-9a15-efd7ad617946.png)
![image](https://user-images.githubusercontent.com/20800786/106460217-45dccb00-6493-11eb-87e5-ca368804df3e.png)

Was this working before/when did the issue start occurring?

I think I've had the problem on the dev version as well for a few weeks without having a precise date. Probably when the LBs became available with the A32NX.

Is this a problem in the vanilla unmodded game?

Only 1 Kg of difference (out of 21274 in total) with the vanilla unmodded.
LBs are not available without the mod.

**Comment by tracernz** [comment] 2021-02-01 17:17
It's rounded down to the nearest 20 kg intentionally.

**Comment by MisterChocker** [comment] 2021-02-03 23:04
Closing since working as intended.

**Closed by MisterChocker** 2021-02-03 23:04 UTC
Labels: Bug
