### ISSUE TITLE
No Green line on ND showing the route

### ISSUE THREAD

**Issue by toolpusher33** [flybywiresim/a32nx#4910] opened 2021-05-26 10:17 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-26T09:08:11+00:00",
  "ref": "master",
  "sha": "a4c7ec6882f1b36cb65435f0c4ceb0e423ed6a09",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

When I take of from EGPC - EGQS there is no green line on the NT showing the route, it follows the route and lands fine on a ILS but no green line.

On longer routes there is a green line but it disappears as I get closer to the airport

NO mods, latest win 10 updates and latest Sim updates 

### Expected behavior

Expect to see green route on NT

### Steps to reproduce

I have tried this flight several times same results

My friend flys same route and he does not see this problem

### References (optional)

![FlightSimulator_9orM38SJMf](https://user-images.githubusercontent.com/84308438/119643084-436ff980-be13-11eb-8c4f-e8254bd3b500.jpg)

### Discord Username (optional)

toolpusher#8980

**Comment by MisterChocker** [comment] 2021-05-26 13:05
So is there no line at all or does it just disappear at some point? (e.g. prior to takeoff, climb, cruise, descent, approach or somewhere in-between?)

**Comment by Watsi01** [comment] 2021-05-26 14:27
This could be related to this #4086

**Comment by tiimmmiii** [comment] 2021-05-26 16:41
Is still bad the new dev version the autobreak turn off during taxi and during the take off start stalling

**Comment by toolpusher33** [comment] 2021-05-26 16:42
Hi
I always test the ILS landing on a new Dev ver by flying between EGPC -EGQS
I have been doing this for a year. If i select VFR for the loading screen
theres a green line , if I select VOR theres a green line , when I select
Low altitude airways and select ILS23 the plane does not have a green line
on ND but I can still fly the flight the DECL red button is there on the ND
and I can successfully land. There is no green line at all for the complete
flight which is only 40 miles. My friend does the same flight all the time,
same settings everything but he sees the green line.. I have tried
EGPC-EGPD and same ISL landing where I do see a green line. This has only
happened after yesterday's update both on the NX and the sim.

I seem to remember I was flying this morning can't remember from or to and
much longer flight and the green line was there for part of the flight
until I was approaching the airport where line disappeared but flight still
followed the route.

regards

John Munro
07999225009

**Comment by tiimmmiii** [comment] 2021-05-26 16:56
Is still bad the new dev version the autobreak turn off during taxi and during the take off start stalling

**Comment by Benjozork** [comment] 2021-05-26 17:01
@tiimmmiii Please immediately stop with off topic comments or you'll be restricted from posting here.

**Comment by toolpusher33** [comment] 2021-05-26 18:24
Hi

Now I remember what I did before--this sounds crazy but A320NX dev version
is good again regards the missing green line

1 I removed the dev version from the community folder (I have no other mods)
2 I installed the stable version
3 I opened the installer again and selected switch to the developer version
and it seemed to overwrite the stable version which was still it the
community folder

It was the same  dev version that I must have tried 10 times this afternoon
--same two airports

I have loaded into the sim 5 times since I made these changes and green
line appears every time

Hope this will point you in the right direction

regards

John Munro
07999225009

**Comment by toolpusher33** [comment] 2021-05-26 19:37
Hi

Apologies about the above mail, I think it's just baloney.

When I start the sim and select a low altitude ISL to these same airports
it will always start without  the green line but if I press escape and
restart the flight I always get a green line . I have flown the flight
several times tonight just to make sure it works and it does even
autolanding works.
So I will just make sure I have a green line on the ND or press restart.

regards

John Munro
07999225009


---------- Forwarded message ---------
From: Toolpusher33 ***@***.***>
Date: Wed, 26 May 2021 at 19:23
Subject: Re: [flybywiresim/a32nx] No Green line on NT showing the route
(#4910)
To: flybywiresim/a32nx <
***@***.***>


Hi

Now I remember what I did before--this sounds crazy but A320NX dev version
is good again regards the missing green line

1 I removed the dev version from the community folder (I have no other mods)
2 I installed the stable version
3 I opened the installer again and selected switch to the developer version
and it seemed to overwrite the stable version which was still it the
community folder

It was the same  dev version that I must have tried 10 times this afternoon
--same two airports

I have loaded into the sim 5 times since I made these changes and green
line appears every time

Hope this will point you in the right direction

regards

John Munro
07999225009

**Comment by frogmonkey2** [comment] 2021-05-29 23:30
mine is dotted and will not engage AP without direct to command

**Comment by tracernz** [comment] 2021-05-30 00:31
> 
> 
> mine is dotted and will not engage AP without direct to command

Keep in mind that NAV should not engage until you reach the capture zone for the active flight plan leg. Our ND doesn't currently display the plan correctly when NAV is only armed (waiting to engage when you get close to the active leg). When you activate DIR TO, the active leg becomes from your present position to the DIR TO waypoint, so of course NAV can engage immediately.

**Comment by MisterChocker** [comment] 2021-06-06 06:37
So is this actually an issue?

**Comment by toolpusher33** [comment] 2021-06-06 07:16
Hi

No not anymore I was operating the plane wrongly

regards

John Munro
07999225009

**Comment by MisterChocker** [comment] 2021-06-06 13:05
Closing since working as intended.

**Closed by MisterChocker** 2021-06-06 13:05 UTC
Labels: Bug, Waiting For Response
