### ISSUE TITLE
[BUG] VOR DME overlapping FLP RETR speed on APPR page (MCDU)

### ISSUE THREAD

**Issue by michaeldinozzo** [flybywiresim/a32nx#3509] opened 2021-02-13 18:49 UTC
**Mod Version**

Latest Dev version from Installer:
  "built": "2021-02-13T09:46:59+00:00",
  "ref": "master",
  "sha": "7da6cf1c4290d17f737df6807754bb270ee01309",
  "actor": "wpine215",
  "event_name": "manual"

**Describe the bug**

When using VOR DME approach, the FINAL runway information is overlapping the FLP RETR speed on the APPR page of the MCDU.

**To Reproduce**

1. Load the aicraft as usual
2. Insert the flightplan and select a VOR/DME approach
3. When you fill in the APPR page in the MCDU, notice that there is some text overlapping between FLP RETR speed and FINAL runway

**Expected behavior**

No text overlapping on the APPR page of the MCDU.

**Actual behavior**

The FINAL runway information is overlapping the FLP RETR speed on the APPR page of the MCDU.

**References**

See screenshot:
![VOR DME](https://user-images.githubusercontent.com/73102012/107858336-8ccfa680-6e2b-11eb-88cf-cf6fca799a58.png)

**Additional context**

Flightplan: LFPO/06 AGOPA7H AGOPA UL167 ARTAX UN857 LMG LMG9L LFBD/05
Was this working before/when did the issue start occurring?
Just noticed this now but it was probably always there.
Is this a problem in the vanilla unmodded game?
Unknown.

Discord username (if different from GitHub):
Not on discord.

**Comment by beheh** [comment] 2021-02-14 11:10
Duplicate of #3121.

**Closed by beheh** 2021-02-14 11:10 UTC
Labels: Bug, MCDU
