### ISSUE TITLE
Ecam & PFD #1 Self Test Error

### ISSUE THREAD

**Issue by JacobKreindler** [flybywiresim/a32nx#521] opened 2020-09-08 22:54 UTC
**Mod Version**

Master

**Describe the bug**

When spawning on an active runway ECAM & #1 PFD is in self test mode while everything else is good to go

**To Reproduce**

1. Spawn on any active runway
2. Check The ECAM & PFD #1
3.

**Expected behavior**

They both should be in fully functional mode

**Actual behavior**

They are in self test mode

**References**

![Microsoft Flight Simulator 2020-09-08 6_25_21 PM](https://user-images.githubusercontent.com/70914399/92535186-a9284100-f204-11ea-81c6-fe69eb82e83b.png)

**Additional context**

**Comment by AdenFlorian** [comment] 2020-09-09 02:54
this is a duplicate of #448

**Closed by AdenFlorian** 2020-09-09 02:54 UTC
Labels: bug
