### ISSUE TITLE
CTD When Entering Init A Page Mid-Air

### ISSUE THREAD

**Issue by notl3ks** [flybywiresim/a32nx#6676] opened 2022-02-09 00:26 UTC
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-02-08T23:01:45+00:00",
  "ref": "experimental",
  "sha": "4de3209d438525ea783ce4e9d22adcbbfc45777a",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Game CTDs when populating Init A page while in midair.

### Expected behavior

I should expect it to not crash doing this, as I have done this before with no issue on any experimental or development verisons.

### Steps to reproduce

1. Spawn in-game
2. Engage respective autopilots
3. Goto Init A on MCDU
4. Enter from and to (in my case as I wanted to test the hold function, EICK/EICK)
5. Upon clicking the button to enter into the field, the game will CTD

**Comment by Benjozork** [comment] 2022-02-09 00:27
How many times have you reproduced this ?

**Comment by notl3ks** [comment] 2022-02-09 00:41
> How many times have you reproduced this ?

I've just gone ahead and tried several times just now, but it worked this time round? It was very odd. I'm not sure what could of caused this. Do you want to close this for now, and if I come across it again I'll pop in a comment?

**Comment by derl30n** [comment] 2022-04-08 23:12
Closing since unable to reproduce, please re-open or open a new issue report when issue appears again as requested.

**Closed by derl30n** 2022-04-08 23:12 UTC
Labels: Bug
