### ISSUE TITLE
[BUG] Speed dial increment in 10 knots

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#1901] opened 2020-11-13 19:34 UTC
**Mod Version**

Master built: 2020-11-13T17:40:31+00:00

**Describe the bug**

With the latest master I found that the speed dial is only using increments of 10 knots. Initial speed was set to 185. In flight I can only dial to 195-205-215-225 etc... Also when selecting Mach I only get 0.65-0.67-0.69...

**To Reproduce**

1. Plan a flight
2. Take off and use selected air speed mode
3. Verify the issue

**Expected behavior**

I would expect the speed dial to behave in previous versions allowing you to input in single knots.

**Actual behavior**

Input is in steps of 10 knots.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes, before this master. Worked earlier today.
Is this a problem in the vanilla unmodded game?
No

**Comment by Benjozork** [comment] 2020-11-13 21:14
Duplicate of #1712, please look for existing issues before opening new ones

**Closed by Benjozork** 2020-11-13 21:14 UTC
Labels: Bug

**Comment by ErikNL80** [comment] 2020-11-13 21:20
I did, but the search did not give this one back... And today is the first day I experienced this, so thought it is a new issue...
