### ISSUE TITLE
HUD (Heads Up Display) for Captain

### ISSUE THREAD

**Issue by kilocharlie1** [flybywiresim/a32nx#6760] opened 2022-02-19 21:07 UTC
### Aircraft Version

Development

### Description

One thing that I have wanted to see in the default A320neo and the A32nx is a HUD (Heads Up Display) that you can pull down and use. If you google "A320neo Hud "you will see that a lot of modern A320neos have a HUDs on the captain's side. Just thought it would be cool to have one in the FBW A32nx as well.

### Discord Username (optional)

GeeMeeKee#9761

**Comment by beheh** [comment] 2022-02-20 22:29
Duplicate of #3415

**Closed by beheh** 2022-02-20 22:29 UTC
Labels: Request
