### ISSUE TITLE
VNAV 

### ISSUE THREAD

**Issue by ANC101** [flybywiresim/a32nx#6561] opened 2022-01-19 08:54 UTC
### Aircraft Version

Development

### Description

I think it would be extremely useful, and would make the A32NX much more fun if there would be VNAV integrated. Things like the TOD marker would take a lot of workload off the pilot, and overall be extremely fun to use.

**Comment by beheh** [comment] 2022-01-19 09:13
Hey, thanks for filing an issue. Please make sure to search the list of issues for duplicates. This even has the same title as the duplicate.

**Comment by beheh** [comment] 2022-01-19 09:13
Duplicate of #5966

**Closed by beheh** 2022-01-19 09:13 UTC
Labels: Request
