### ISSUE TITLE
[BUG] ILS frequency not configured after planning ingame route

### ISSUE THREAD

**Issue by ronaldvdmeer** [flybywiresim/a32nx#1724] opened 2020-11-02 17:37 UTC
**Mod Version**
Latest stable release 0.4.1

**Describe the bug**
When using the ingame flight planner ILS frequency is not configured in MCDU. Because of this ILS is not working.

**To Reproduce**
1. Plan high altitude IFR flight
2. Select EHAM ILS18-R as destination
3. Fly using autopilot
4. Check if ILS is picked up on approuch

**Expected behavior**
ILS to be configured in MCDU

**Actual behavior**
Frequency missing in MCDU

Was this working before/when did the issue start occurring? Since 0.4.1

**Comment by tareksabet** [comment] 2020-11-02 18:17
You will have to enter the ILS frequency manually via RAD NAV page on the MCDU by only typing the frequency only . But sadly I don't know what's the reason for it as it works for some of them and others doesn't. Thanks for reporting

**Comment by archetec** [comment] 2020-11-02 23:05
I encountered the same issue landing in Montreal (CYUL) on RW24R with ILS.  I added the ILS frequency manually...  The AP will align to the RW but fails to manage speed correctly.  It worked before the last Asobo release and with 0.4.0.  And it works correctly without the mod...

**Comment by Benjozork** [comment] 2020-11-03 00:18
Duplicate of #1392.

**Closed by Benjozork** 2020-11-03 00:18 UTC
Labels: Bug, MCDU
