### ISSUE TITLE
COM frequencies initialised to an invalid number

### ISSUE THREAD

**Issue by spectreofmyself** [flybywiresim/a32nx#3976] opened 2021-03-15 00:33 UTC
**Mod Version**
```
{
  "built": "2021-03-13T19:52:29+00:00",
  "ref": "master",
  "sha": "208f069abc8c489cef1d62bae3cca8e29bb95bd3",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

**Describe the bug**
When the aircraft is initially spawned in, the VHF1 and VHF2 frequencies are initialised to invalid entries.
Here's what it looks like in-sim:
![image](https://user-images.githubusercontent.com/70790175/111089862-9700c580-84fb-11eb-9132-c504ed295716.png)
And here in vPilot, the invalid entry can be seen:
![image](https://user-images.githubusercontent.com/70790175/111089889-a849d200-84fb-11eb-847a-b5a994cf6f1d.png)

**To Reproduce**

1. Spawn the aircraft and turn on the battery power
2. Observe the number in the frequency box
3. Select VHF2 and observe the same issue

**Expected behavior**

The frequency should be set to a valid entry (say, 118.000)

**Actual behavior**

The frequency is invalid and displays as 0.00000

**References**

See images above

**Additional context**

Was this working before/when did the issue start occurring?
This started occurring after I updated from the master branch to the version above

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): n/a

**Comment by Asianblade** [comment] 2021-03-19 16:25
Nope. It was not working since the start. This is a false bug.

**Comment by Benjozork** [comment] 2021-03-19 16:28
@Asianblade Please stop commenting disruptive comments or you will be blocked from this page.

**Comment by blazinga350** [comment] 2021-03-20 01:41
I also have this problem

**Comment by joseph-tobin** [comment] 2021-04-21 00:28
Duplicate of https://github.com/flybywiresim/a32nx/issues/3854

**Comment by sidnov** [comment] 2021-05-08 12:20
Fixed now

**Closed by sidnov** 2021-05-08 12:20 UTC
Labels: Bug, RMP
