### ISSUE TITLE
[REQUEST] Company Route import from PLN file into MCDU

### ISSUE THREAD

**Issue by Samueleonard** [flybywiresim/a32nx#2853] opened 2021-01-03 13:40 UTC
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the feature you'd like to see implemented**

2 scenarios
  - user enters FROM/TO into mcdu, acft checks if PLN exists for that route, then loads in route
  - OR user enters directly into company route field, with PLN name (LHRCDG01) and acft loads in data

**References**

https://i.imgur.com/Ghl7xKx.png not from a thales mcdu, but thales still has a line to enter a company route

**Additional context**

This feature has been used on almost every good addon plane ever, and is used alongside simbrief import on planes like the fslabs
I am not sure if msfs currently has support for reading local files, but there would need to be an export directory that it could read, potentially make it changable?

Discord username (if different from GitHub):
N/A

**Comment by MisterChocker** [comment] 2021-01-03 14:20
Duplicate of #1656

**Closed by MisterChocker** 2021-01-03 14:20 UTC
Labels: Enhancement
