### ISSUE TITLE
aviaworx MCDU and electronic flight bag

### ISSUE THREAD

**Issue by gelderen** [flybywiresim/a32nx#5956] opened 2021-10-02 21:07 UTC
### Aircraft Version

Development

### Description

First of all, compliments and thanks for all the work you guys put in to develop the airbus. It's getting better and better.

For my request: It would be awesome to be able to use aviaworx software to control the MCDU and EFB through an external tablet or phone (see photo).  It already works for the CRJ addon aircraft which is the reason I switched airplanes to the CRJ for now. But as soon as this option becomes available I'd switch right back to the FBW aircraft.

He's is waiting for your implementation so he can implement his end. mark@aviaworx.com

Please consider. To be able to use the MCDU and EFB through an extra tablet really brings the user experience to a higher level.
Thanks and have a great weekend. 

![1633208295144](https://user-images.githubusercontent.com/716034/135731777-a40429cc-bb0b-4e58-b055-59da0469953d.jpg)

**Comment by sidnov** [comment] 2021-10-02 23:22
Duplicate of https://github.com/flybywiresim/a32nx/issues/4000

**Closed by sidnov** 2021-10-02 23:22 UTC
Labels: Request
