### ISSUE TITLE
Inoperative ailerons

### ISSUE THREAD

**Issue by tymoboy** [flybywiresim/a32nx#5085] opened 2021-06-10 16:48 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-10T09:49:19+00:00",
  "ref": "master",
  "sha": "1578f4fa852800ef1d7c46ad6460f21bf92a2c3a",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

In this version of the aircraft, the ailerons do not react and do not work. In the stable version, the aircraft's ailerons are fully functional. I play on a gamepad. 

### Expected behavior

Working ailerons

### Steps to reproduce

1. Installed the latest development update
2. Before the flight, I began to check the operation of the elevator and ailerons.
3. Detected aileron malfunction. They simply didn't react.

**Comment by aguther** [comment] 2021-06-10 19:09
![image](https://user-images.githubusercontent.com/6629914/121582892-dcb42800-ca2f-11eb-9d22-6cb2d838edef.png)

If you're not using an axis but buttons this is due to a bug in the SDK. This must be fixed by MS/Asobo.

Beside that please don't open duplicate bugs, search fist.

Duplicate of #5085

**Closed by aguther** 2021-06-10 19:09 UTC
Labels: Bug
