### ISSUE TITLE
[BUG] Selecting Arrival and Approach Mid Flight Breaks the FD Screen and IRS 

### ISSUE THREAD

**Issue by Cspielman63** [flybywiresim/a32nx#1853] opened 2020-11-10 21:07 UTC
**Mod Version**

master
built: 2020-11-10T15:19:38+00:00
ref: refs/heads/master
sha: 6cb5116649c223cba11e7eec6ee39fcba9ecfb68
actor: Benjozork
event_name: push

**Describe the bug**

When selecting an arrival and approach in FMC mid flight, the FMC says UNAVAILABLE at the top of it's screen and the IRS and FD info breaks and no longer follows in autopilot.

**To Reproduce**

1. Start a flight and get into the air
2. Try to enter an arrival and approach
3.

**Expected behavior**

**Actual behavior**

Breaks FD and AP and FMC

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by lousybyte** [comment] 2020-11-11 10:24
I can't replicate this, do you have a specific route you can share and steps to reproduce?

**Comment by Cspielman63** [comment] 2020-11-11 14:12
> I can't replicate this, do you have a specific route you can share and steps to reproduce?

It was KMSP to KGEG and I was about halfway through the flight. I just went to plug in an arrival, specifically the HELIE2 arrival and the ILS 21 approach and after I clicked insert the MCDU screen just went black and said unavailable at the top of it and I couldn’t click any buttons on it. The artificial horizon screen worked fine but the other route screen had a red bar at the top and didn’t follow the flight plan.

**Comment by SpecialFx78** [comment] 2020-11-13 15:02
I have the same concern even without having started a flight, I'm in a cab, as soon as I enter a runway and a star for the arrival, the flight plan disappears and and displayed UNTITLED in F-PLAN

**Comment by lousybyte** [comment] 2020-11-13 15:46
@Cspielman63 Still can't replicate, those instructions worked just fine for me.

For anyone having issues, try do to a clean install:

1. make sure you have the latest version of the game (currently 1.10.11)
2. completely delete the A32NX folder from the Community folder
3. remove any other addons or liveries you might have from the Community folder
4. use the installer and install the latest development version of the mod (not stable)

**Comment by SpecialFx78** [comment] 2020-11-13 16:40
The error is finally due to the Navigraph navigation data and not your development, thank you for your answer.

**Comment by tareksabet** [comment] 2020-11-13 20:17
Closing this as it cannot be reproduced

**Closed by tareksabet** 2020-11-13 20:17 UTC
Labels: Bug
