### ISSUE TITLE
[BUG] Cost Index 0 ignored by CDU

### ISSUE THREAD

**Issue by ChruutvoLuzi** [flybywiresim/a32nx#2499] opened 2020-12-18 11:03 UTC
**Mod Version**

latest master

**Describe the bug**

Entering a Cost Index of 0 into the CDU is ignored by the FMC, the field stays blank

**To Reproduce**

1. try entering a cost index of 0
2.
3.

**Expected behavior**

Cost Index 0 should give Maximum Range and be accepted by the FMC

**Actual behavior**

It ignors it

**References**

https://ansperformance.eu/library/airbus-cost-index.pdf

**Additional context**

Was this working before/when did the issue start occurring?
Was always wrong
Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

ChruutvoLuzi | SD-PB.ch#8902

**Comment by ChruutvoLuzi** [comment] 2020-12-18 11:04
As i am trying to learn how to program, i am currently investigating this (gotta start it easy, right) so i opened this issue

**Comment by tareksabet** [comment] 2020-12-18 12:10
yep you're correct you can type in  in Cost Index 

![Desktop Screenshot 2020 12 18 - 14 07 47 97](https://user-images.githubusercontent.com/70240330/102613176-b4133b80-413a-11eb-9b87-7015c5690315.png)

**Comment by ChruutvoLuzi** [comment] 2020-12-18 12:19
Working on it and i think i have an idea :)

**Comment by MisterChocker** [comment] 2021-04-13 17:03
Duplicate of #345

**Closed by MisterChocker** 2021-04-13 17:03 UTC
Labels: Bug, MCDU
