### ISSUE TITLE
[BUG] Reverse Thrust on Throttle Axis Ignored by Custom FBW Build

### ISSUE THREAD

**Issue by medic6810** [flybywiresim/a32nx#3305] opened 2021-02-03 01:47 UTC
**Mod Version**
Custom FBW da3b3c0
{
  "built": "2021-02-02T21:59:06+00:00",
  "ref": "fbw",
  "sha": "0d4237c4f2045c296e059d8c71d72c004644084f",
  "actor": "nistei",
  "event_name": "manual"
}

**Describe the bug**
Using TM TCA Throttle Quadrant. Throttle has reverse component of axis defined in "sensitivity" panel of FS2020 controls settings. Every other FS2020 aircraft as well as the FBW Dev and Stable builds recognizes the custom idle point and properly parses the axis into forward and reverse zones. Custom FBW build does not parse axis into forward and reverse zones and instead treats the axis as one large axis, requiring user to move thrust levers to full reverse position to command idle thrust.

**To Reproduce**

1. Install custom FBW version.
2. Set up a throttle axis with a custom idle point so that there is a reverse zone and a positive zone on the axis.
3. Note that the custom idle point is ignored and the reverse zone of the throttle axis is ignored by the aircraft and the reverse zone is treated as the bottom component of the forward throttle axis.

**Expected behavior**

The inflection point set up between forward and reverse throttle should be recognized by the mod, allowing forward throttle and reverse throttle on the same axis.

**Actual behavior**

The custom inflection point set up in FS2020 settings is ignored and the reverse component of the throttle axis is treated as the bottom part of the forward throttle axis instead. When throttle sits in idle position about 50% N1 is produced. In order to retard throttle to idle the physical throttle must be moved to the full reverse thrust position.

**References**
See page 7 of this manual to see how the thrustmaster TCA quadrant axis is set up into forward and reverse zones. https://ts.thrustmaster.com/download/accessories/manuals/TCA_Quadrant/TCA_Quadrant%20Airbus_Edition_user_manual.pdf

**Additional context**

Was this working before/when did the issue start occurring?
Not an issue in the Dev and Stable builds.

Is this a problem in the vanilla unmodded game?
Not an issue in the vanilla simulator.

**Comment by tracernz** [comment] 2021-02-03 03:36
See the [ReadMe](https://github.com/flybywiresim/a32nx/blob/fbw/docs/README.md) in the FBW branch on how to set it up.

**Comment by MisterChocker** [comment] 2021-02-03 22:59
Duplicate of #3203.

**Closed by MisterChocker** 2021-02-03 22:59 UTC
Labels: Bug
