### ISSUE TITLE
Cockpit Save States

### ISSUE THREAD

**Issue by kilocharlie1** [flybywiresim/a32nx#6761] opened 2022-02-19 21:12 UTC
### Aircraft Version

Development

### Description

Another thing that I have wanted to see in the A32nx is cockpit save states, like the PMDG 737NG for FSX. This could be managed in the FlyPad. What would happen is you have the cockpit in a state that it would load in next time you boot up the sim, like say a boarding passengers state, so that you could save the cockpit in its current state, exit out to the main menu after a flight to file another flight plan and hop back in the sim and load that save state and pick up where you left off.

### Discord Username (optional)

GeeMeeKee#9761

**Comment by derl30n** [comment] 2022-04-09 21:02
Duplicate of https://github.com/flybywiresim/a32nx/issues/4840

**Closed by derl30n** 2022-04-09 21:02 UTC
Labels: Request, EFB
