### ISSUE TITLE
[BUG] Impossible to taxi the plane after landing with one engine only

### ISSUE THREAD

**Issue by davydecorps** [flybywiresim/a32nx#1714] opened 2020-11-02 08:45 UTC
**Mod Version**
Last dev version 01/11/2020

**Describe the bug**
After normal landing, cut off engine 2 end of the runway. Then it was nearly impossible to turn left using rudder + brake

**To Reproduce**
Land, slow the airplane, cut engine 2 before taxiing out of runway turning to the left

**Expected behavior**
Airplane should turn using minimal engine thrust even if there is counter torque from single engine configuration

**Actual behavior**
When putting some power on engine 1, plane goes right with full rudder to the left

**References**

**Additional context**

Discord username (if different from GitHub): Davy

**Comment by nreyes90** [comment] 2020-11-02 12:34
I actually didn't check if hydraulic performance is working in any PR's yet.

But did you turn on Yellow Elec Hydraulics? You lose the hydraulics if ENG 2 is turned off and you need to pressurize IRL with the Y Elec pump. You lose nose wheel steering.

**Comment by davydecorps** [comment] 2020-11-02 12:37
That could be a nose steering issue indeed, but I was sure the 3 hyd circuits weren't simulated yet.  Need to check at least if the front wheel is turning in external view to confirm this.

**Comment by Benjozork** [comment] 2020-11-02 15:26
Hello,

Single-engine taxi is currently not possible due to the absence of a proper hydraulic system.

This is coming in a future update.

**Comment by davydecorps** [comment] 2020-11-03 08:23
Tried again yesterday, and couldn't reproduce exactly the problem. I was on a new dev update though if it has any chance of changing this.
In exterior cam the front wheel steering is working perfectly even with engine 2 off. Only "issue" is that you can instantly turn the wheel 90° which makes it slide badly and prevent plane to turn. Less rudder and it the turns accordingly.
Is there a speed logic to reduce steering authority on the real plane?

**Comment by MisterChocker** [comment] 2020-12-31 05:39
Since the only found issue is a nose wheel slide caused by fast and wrong nosewheel "turn angle" which is fixed I will close this issue.

**Closed by MisterChocker** 2020-12-31 05:39 UTC
Labels: Bug
