### ISSUE TITLE
Parking brake set - MSFS Offset 0BC8 shows "0"

### ISSUE THREAD

**Issue by hanomax24** [flybywiresim/a32nx#5012] opened 2021-06-05 08:24 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-04T17:58:47+00:00",
  "ref": "master",
  "sha": "361e1c56e70029eaca2b89c02fba45ed0ef01656",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

The MSFS Offset 0BC8 will still be set to "0" even if the parking brake is set. The parking brake of the A32NX is working fine, but since a few days the MSFS offset 0BC8 will not change if the status of the parking brake will change. This means, that some software tools will not work anymore.

### Expected behavior

Teh MSFS offset 0BC8 should show "-1" if parking brake is set.

### Steps to reproduce

Set and release the parking brake and watch the offset 0BC8 with fsuipc

**Comment by Benjozork** [comment] 2021-06-05 08:46
Duplicate of #5006.

Unfortunately MSFS does not allow us to set that variable when we bypass the default parking brake implementation to link it to our hydraulics. This is being forwarded to Asobo.

**Closed by Benjozork** 2021-06-05 08:46 UTC
Labels: Bug
