### ISSUE TITLE
[BUG] Departure and approah only works sometimes

### ISSUE THREAD

**Issue by brunfloo** [flybywiresim/a32nx#2052] opened 2020-11-21 23:31 UTC
In the fpln menu on the mcdu, when you press the origin airport it only shows up erase or input. The sam thing happesn when you try and press the destination airport to get the arrival menu. It just simply wont work.

**Comment by Benjozork** [comment] 2020-11-21 23:35
Duplicate of #1378 and doesn't respect issue template.

**Closed by Benjozork** 2020-11-21 23:35 UTC
