### ISSUE TITLE
[BUG] Cannot update STAR

### ISSUE THREAD

**Issue by bisinchi** [flybywiresim/a32nx#3051] opened 2021-01-15 08:12 UTC
**Mod Version**
Master

{
  "built": "2021-01-12T06:10:20+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**

When a flightplan is created and a STAR is selected for the approach, it is not possible to add waypoints to the STAR if any are missing. Waypoints are visible on the ND, but they cannot be added to the STAR via the FMC.

**To Reproduce**

1. create flight plan
2.select star for arrival airport
3.add waypoint (either missing in STAR or any waypoint)

**Expected behavior**

Waypoint should be added to flightplan

**Actual behavior**

Waypoint is not added to flightplan

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment] 2021-01-15 08:18
Duplicate of #1388

**Comment by tracernz** [comment] 2021-01-15 08:18
https://github.com/flybywiresim/a32nx/pull/2831 allows deleting fixes in the STAR, not sure about adding.

**Closed by Benjozork** 2021-01-15 08:18 UTC
Labels: Bug
