### ISSUE TITLE
[REQUEST] Add ground roll indicator on PFD

### ISSUE THREAD

**Issue by MapleNAV-TCASFAULT** [flybywiresim/a32nx#2346] opened 2020-12-10 20:57 UTC
**Is your feature request related to a problem? Please describe.**

The PFD artificial horizon doesn't have the ground roll guidance indicator.

**Describe the feature you'd like to see implemented**

A thin green arrow should display below the horizon of the PFD showing the centerline of the runway. It should only be displayed if "ROLLOUT" or "RWY" is shown on the FMA and when runway localizer is available. 

**References**

![pfdrollguidance](https://user-images.githubusercontent.com/72575144/101828906-30d16480-3b00-11eb-8d3f-1131f09438c0.jpg)

https://www.youtube.com/watch?v=TEi-WX08ov8 5:26

https://www.youtube.com/watch?v=ECV3IBkzZLc 0:04

**Additional context**

http://www.a320dp.com/A320_DP/flight-instruments/sys-8.3.27.html#:~:text=The%20Ground%20Roll%20Guidance%20Command,with%20the%20ROLLOUT%20FMA%20displayed.

Discord username (if different from GitHub): ChristopherXie#3904

**Comment by Benjozork** [comment] 2020-12-11 05:33
That reference is for EIS1. Also, the A320DP website only contains references for EIS1, so avoid using it in the future.

**Comment by MapleNAV-TCASFAULT** [comment] 2020-12-11 06:40
Bruh, at least it can be used for the ceo variant with the crt screens :D

**Comment by AirbusA320Pro** [comment] 2020-12-11 11:14
Whilst the reference is for EIS1, the Ground Roll Guidance Command Bar (or "yaw bar") has been present on every variant of Airbus I've flown IRL - A319/320/321/332/333. Although I haven't flown the NEO, so confirmation would be needed for that specifically.

**Comment by jeroensengers** [comment] 2020-12-22 21:40
Reference from FCOM DSC-31-4-: Specific Ground Indications

**Comment by MisterChocker** [comment] 2020-12-31 06:30
duplicate of #1145

**Closed by MisterChocker** 2020-12-31 06:30 UTC
Labels: Enhancement, Needs Reference, PFD
