### ISSUE TITLE
[REQUEST] Autopilot: Entering a holding pattern

### ISSUE THREAD

**Issue by LegoHawk** [flybywiresim/a32nx#1443] opened 2020-10-18 13:02 UTC
**Is your feature request related to a problem? Please describe.**

The problem is that the A320NX can not enter a holding pattern on autopilot, particularly an issue when flying on VATSIM and ATC ask you to enter a holding pattern.

**Describe the feature you'd like to see implemented**

Enter a holding pattern at a waypoint, VOR or NDB on a flight-plan. The current MCDU allows you to enter into the 'Hold' position but the autopilot does not respect it, it flies straight to the next waypoint.

**References**

See here for [reference](http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.8.17.html) and [here](https://www.quora.com/Whats-the-procedure-to-enter-a-HOLD-pattern-in-the-MCDU-of-Airbus-A320-aircraft), please.

**Additional context**

Keep up the great work! 

Discord username (if different from GitHub):

**Comment by d0m4te** [comment] 2020-11-04 00:31
If I'm not mistaken, the holding pattern with entered radial and leg time/distance also should be displayed on the nd.

**Comment by Roboplayer999** [comment] 2020-11-18 19:34
So!

**Comment by Benjozork** [comment] 2020-11-18 19:37
> So!

?

**Comment by Roboplayer999** [comment] 2020-11-18 20:00
Has it been fixed?

**Comment by Benjozork** [comment] 2020-11-18 20:02
If the issue is open, no. We experimented with it but some interventions needed with the in-game AP needed to add holds cause CTDs for now, so we are waiting. Stay tuned.

**Comment by Roboplayer999** [comment] 2020-11-18 20:24
Thanks for the info, I appreciate the work

**Comment by newelldam** [comment] 2021-01-20 12:59
Just wondering, is there any update on this yet?

**Comment by Benjozork** [comment] 2021-01-20 15:22
There is a new flight plan management system in the works that enables us to add holds soon

**Comment by newelldam** [comment] 2021-01-20 15:35
Great, thanks!

**Comment by Samuel-78** [comment] 2021-01-27 00:59
> There is a new flight plan management system in the works that enables us to add holds soon

Great job! Thx

**Comment by MisterChocker** [comment] 2021-02-13 14:11
Duplicate of #673

**Closed by MisterChocker** 2021-02-13 14:11 UTC
Labels: Enhancement
