### ISSUE TITLE
[BUG] Angle of Attack is Incorrect

### ISSUE THREAD

**Issue by AngleAvila** [flybywiresim/a32nx#1417] opened 2020-10-17 02:16 UTC
**Mod Version**
v0.4.0 (Recent)

**Describe the bug**
The aircraft has issues with the angle of attack whenever the autopilot is initiated. The aircraft will not descend even after being commanded to, and when it ascends it nose pitches down.

**To Reproduce**
1. Start in the A320 with the A32nx mod at any location/runway.
2. Takeoff and initiate climb with autopilot by setting higher altitude.
3. Aircraft continues to go past altitude even after climb thrust is adjusted. Aircraft keeps ascending while its nose pitches down. Turning off the autopilot hardly fixes the problem.

**Expected behavior**
Aircraft is supposed to follow commands from the autopilot FCU. The nose is supposed to pitch up when ascending and down when descending. Aircraft hardly descends when commanded to.

**Actual behavior**
Aircraft continues to go past altitude even after climb thrust is adjusted. Aircraft keeps ascending while its nose pitches down. Turning off the autopilot hardly fixes the problem.

**References**
![20201016_191152](https://user-images.githubusercontent.com/70923899/96326242-d4603600-0fe3-11eb-8a69-d7ffc2f6de70.jpg)

**Additional context**
Makes the aircraft incredibly impractical, unsafe, and incapable of flying.

Was this working before/when did the issue start occurring?
The issue started happening on v0.3.0.

Is this a problem in the vanilla unmodded game?
No, this is not a problem in the unmodded game.

Discord username (if different from GitHub): lilangle #1870

**Comment by Benjozork** [comment] 2020-10-17 02:50
Duplicate of #1395

**Closed** 2020-10-17 02:53 UTC
Labels: Bug, Duplicate
