### ISSUE TITLE
configurable ratio for browser fullscreen mode

### ISSUE THREAD

**Issue by sunday747** [flybywiresim/a32nx#6865] opened 2022-03-07 16:40 UTC
### Aircraft Version

Experimental

### Description

As already written in Discord. 
Wenn you build a MCDU with a 5“ Display you will face a non perfect fit to the buttons left and right next to screen. 
So, the first upper line is mostly located near the second button. 

### References (optional)

![5D4230EB-67F4-4433-A53C-D5D1DB749AAC](https://user-images.githubusercontent.com/101129579/157077864-5be0b6c2-5dd4-40cf-bbb4-f972e8ee5fc5.jpeg)

### Discord Username (optional)

Franky_airliner

**Comment by tracernz** [comment] 2022-03-07 18:19
The hardware is wrong in this case. There should be a larger gap between the top and the first LSKs, as on the real aircraft. You won’t be able to get all the rows to align without cutting off the top of the display. 

This is really a duplicate of https://github.com/flybywiresim/a32nx/issues/6842.

**Closed by tracernz** 2022-03-07 18:19 UTC
Labels: Request, Remote MCDU
