### ISSUE TITLE
Simbrief Flightplan Fault

### ISSUE THREAD

**Issue by nbillo** [flybywiresim/a32nx#4481] opened 2021-04-18 08:27 UTC
**Mod Version**

```json
"built": "2021-04-16T21:01:28+00:00",
  "ref": "master",
  "sha": "b19333584e36344376068945b3604b4a746f9543",
  "actor": "myselfaaryan",
  "event_name": "manual"
```

**Describe the bug**

**I have noticed that certain flightplans created with Simbrief cause the aircraft to lock up.**

**To Reproduce**

1. Created flightplan within Simbrief (attached) LOWW - GCRR
2. Start sim and load aircraft
3. Power systems normally
4. Use the FMS and load the flightplan from my Simbrief account as per normal procedure using 'INIT' Page
5. Use LSK and sim locks
6. Close Sim

**Expected behavior**

I expected to load the flightplan and carry on as normal.

**Actual behavior**

I removed the latest Nvidia driver 466.11 and re-installed 465.89, this had no effect.
I used the latest stable version and this had the same result after loading the flightplan.
I removed everything from the community folder apart from FBW, loaded the flightplan and teh same crash happened.
I then realised it was loading a specific flight plan from my Simbrief account, that caused the crash. I have only had two occasions where it has crashed the sim, and this latest crash was because of loading a flightplan with GCRR as the destination.
I subsequently created a new flightplan from LOWW - OJAI and this loaded without any issue, so it was definitely GCRR that was causing the issue.

**References**

N/A

**Additional context**

I have attached the flightplan LOWW-GCRR

Was this working before/when did the issue start occurring?
Yes/ After loading a flightplan with GCRR as the destination.

Is this a problem in the vanilla unmodded game?
No, because the flightplan was loaded through the sim load utility.

Discord username (if different from GitHub):
nbillo

[LOWWGCRR_MFS_18Apr21.zip](https://github.com/flybywiresim/a32nx/files/6330771/LOWWGCRR_MFS_18Apr21.zip)

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment] 2021-04-19 17:07
Duplicate of #4338

**Closed by MisterChocker** 2021-04-19 17:07 UTC
Labels: Bug
