### ISSUE TITLE
CTD after printed ATIS

### ISSUE THREAD

**Issue by doggydogg13** [flybywiresim/a32nx#5821] opened 2021-09-14 13:53 UTC
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-09-13T23:09:35+00:00",
  "ref": "experimental",
  "sha": "19bc202923d3ce1881262c4b227551d3832aed95",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Try to print the ATIS from MCDU.
EDDS to LEAL
When i press print CTD happened.
It was during the climb at 15000ft

### Expected behavior

Get the paper printed after pressing print

### Steps to reproduce

Star Flight from EDDS to LEAL
Live time and wheather
At 15000ft try to print the ATIS
CTD should happen

**Comment by Benjozork** [comment] 2021-09-14 13:54
Duplicate of #5429. Please stop opening more issues - we have already logged it.

**Closed by Benjozork** 2021-09-14 13:54 UTC
Labels: Bug

**Comment by doggydogg13** [comment] 2021-09-14 13:57
I got it, my bad 

Envoyé de mon iPhone
