### ISSUE TITLE
[BUG] Alpha Floor 

### ISSUE THREAD

**Issue by NiklasScheid** [flybywiresim/a32nx#2387] opened 2020-12-12 15:42 UTC
**Mod Version**
Master 2020-12-10T16:06:11+00:00

**Describe the bug**

After the alpha floor protection is "disenaged" engine 1 goes to idle while engine 2 has TOGA thurst. 

**To Reproduce**

1. T/O
2. Thurst Idle
3. Pitch up and don't give any inputs
4. Stall and wait until A.Floor and TOGA LK kicks in
5. Let the AC catch itself
6. Once the speed is above 100 kn IAS engine 1 ignores TOGA LK and goes to idle (or accordingly to the thurst lever position)

**Expected behavior**

Engine 1 should have TOGA thrust due to TOGA LK

**Actual behavior**

Engine 1 ignores TOGA LK

**References**

![image](https://user-images.githubusercontent.com/45736442/101988080-f8fd2500-3c97-11eb-8413-7451fc2d78ad.png)

**Additional context**

I have tested this multiple times, sometimes A.Floor kicks in but no TOGA LK. This occured when I disengaged the A/THR before the stall. I am not sure if this is a correct behavior.

Was this working before/when did the issue start occurring?
unknown

Is this a problem in the vanilla unmodded game?
unknown

Discord username (if different from GitHub): Niklas#6994

**Comment by hotshotp** [comment] 2020-12-14 04:55
Same issue here, if you have engines are 50% thrust while going into a floor only engine number 2 will go into a floor it seems like

**Comment by bisinchi** [comment] 2020-12-15 12:54
Hi same here, with development branch installed via the installer this morning. Both engines go to TOGA, then Engine 1 goes back to idle after a few seconds and engine 2 stays in TOGA

**Comment by MisterChocker** [comment] 2020-12-31 06:13
duplicate of #1329

**Closed by MisterChocker** 2020-12-31 06:13 UTC
Labels: Bug, Reproduced
