### ISSUE TITLE
Fuel Flow indication wrong - IRL units in tenner only

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2423] opened 2020-12-14 10:26 UTC
**Mod Version**

master

**Describe the bug**

the fuel flow indication on the upper ECAS shows the fuel flow (sadly also wrong) in hole units. IRL the fuel flow only showed up in ten steps , (instead of 593 kg- it should be 590kg) (values only example)
Also the Idle fuel flow is WRONG in the engines.cfg. kg and lbs is mixed up, so the idle should be ~300-~320kg/eng/hr

also the refreh rate from the fuel flow is lower.

**To Reproduce**

1. look at the fuel flow
2.
3.

**Expected behavior**

values only in ten steps (not e.g. 542 - only 540) (values are only for the example)

also refrehrate from fuel flow is relatively low. 

**Actual behavior**

it shows the kilogram exactely (e.g. 542)

**References**

https://www.youtube.com/watch?v=dhh2auv9vOI - good to see on final ~4:00

from A319, but same along A32N´s and other airbusses

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-12-14 19:13
No references provided.

**Comment by andrejetcat** [comment] 2020-12-14 19:30
oh sorry, I thought that it is enoungt to state it as a real-life Airbus pilot. I linked a video (from an A319) but its the same along all Airbusses that the values are only show up in ten steps.

**Comment by Benjozork** [comment] 2020-12-14 20:20
You edit your post after I commented.

All good now.

**Comment by MisterChocker** [comment] 2020-12-15 22:23
Please recheck with current master. Thanks!

**Comment by andrejetcat** [comment] 2020-12-16 19:11
awesome, now bit more realistic, but just wrong values. idle flow is like 300-320kg/hr per ENG :) 

keep on working, you all make a greate job!!!!

**Comment by donstim** [comment] 2020-12-29 08:08
Idle fuel flow can vary between engines. Not all A319s, A320s, A321s, etc. have the same idle fuel flow.  Here is a reference for the airplane we are modeling from the FCOM for after start engine idle fuel flow:
![Screenshot (481)](https://user-images.githubusercontent.com/70166617/103264641-20bedf00-4960-11eb-8b4e-d6eac40efce3.png)

According to that info, ground idle fuel flow should be 290 kg/h/eng. (Note that this would be 639 lb/hr/eng vs the 650 given in the parenthetical in the FCOM data.) What we have now, 160 kg/hr/eng is pretty far off.

Also note the N1, N2, and EGT values for engine idle from the FCOM (sea level, ISA). We currently have N1=19.5, EGT=550, and N2=58.5 compared to the FCOM "about 19", 520, and 68. Our current EGT is a bit high, and if we increase idle fuel flow it will go higher. I don't see anything in the engines.cfg file for changing the EGT-Fuel flow relationship to raise idle fuel flow while lowering EGT, but maybe TazX knows.

Also, there seems to be something funny going on with our lower ECAM display of fuel flow. When I tested putting 639 lb/hr in as idle fuel flow, the ECAM gave 280 kh/hr instead of 290 even though the dev debug window showed the correct amount in gal/hr.

**Comment by donstim** [comment] 2020-12-29 10:20
The idle fuel flow issue is a duplicate of #2239 (or the discussion of idle fuel flow should be moved from here into that one).

**Comment by MisterChocker** [comment] 2020-12-31 04:34
closing since duplicate of #2239

**Closed by MisterChocker** 2020-12-31 04:34 UTC
Labels: Bug
