### ISSUE TITLE
[BUG] ALL DISPLAYS BLANK

### ISSUE THREAD

**Issue by Jimothy1st** [flybywiresim/a32nx#3938] opened 2021-03-12 10:05 UTC
**Mod Version**

**Describe the bug**

**To Reproduce**

1. The displays are blank in every flight now after the recent MFS2020 update.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Mod worked fine before the update.

![A32NX - No Displays](https://user-images.githubusercontent.com/80516927/110924913-7decee80-831a-11eb-99ff-aa55acdfa355.jpg)

Discord username (if different from GitHub):

**Comment by Lucky38i** [comment] 2021-03-12 10:08
Can you please fill out the issue template properly. You clearly haven't attested that you followed the issue template.

**Comment by cocoiadrop** [comment] 2021-03-12 10:16
Use the development version.

**Comment by Jimothy1st** [comment] 2021-03-12 10:32
> Use the development version.

I have just tried the Development Version - 640ea13 and the Custom FBW Version - f4fc87c and the problem persists.

**Comment by aero2525** [comment] 2021-03-12 11:20
I have exactly the same problem since last update ... (stable and development version)
All works fine before the update.

**Comment by Nimbus719** [comment] 2021-03-12 11:26
I am having exactly the same issues with no display. This only happened since the latest update for MSFS2020.

**Comment by CVTag** [comment] 2021-03-12 12:20
Same here after latest MSFS update, tho I get them back on the Developers & Custom.

**Comment by Lucky38i** [comment] 2021-03-12 12:43
> 
> 
> > Use the development version.
> 
> I have just tried the Development Version - [640ea13](https://github.com/flybywiresim/a32nx/commit/640ea13fae829c1a486924fb5755fef2fff5bfa6) and the Custom FBW Version - [f4fc87c](https://github.com/flybywiresim/a32nx/commit/f4fc87c3e18bf84de6c71a0f426140da9451f99b) and the problem persists.

I cannot help you until you fill out the issue template.

**Comment by MisterChocker** [comment] 2021-03-12 14:49
Duplicate of #3941

**Closed by MisterChocker** 2021-03-12 14:49 UTC
Labels: Bug, Waiting For Response

**Comment by Benjozork** [comment] 2021-03-12 15:57
> Same here after latest MSFS update, tho I get them back on the Developers & Custom.

Yes because as we said only the development version  works.

This is not a bug. Stable is not compatible with the new update yet.
