### ISSUE TITLE
FOB sensor reads zero after latest DEV update using updater

### ISSUE THREAD

**Issue by delta5150** [flybywiresim/a32nx#5405] opened 2021-07-25 17:08 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-25T10:59:19+00:00",
  "ref": "master",
  "sha": "63df888a4695e4cf2a7f4da4668c603daf958611",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

FOB registers 0 even when tanks are full.

### Expected behavior

FOB in ECAM should show amount of fuel.

### Steps to reproduce

Started C/D at KLAS gate A12. Normal power up using batteries then connecting ground power.

### Additional info (optional)

Was working this morning prior to using installer to update. Having said that I love this plane. Thank you to all of the very smart people on here making it what it is!!

### Discord Username (optional)

delta5150

**Comment by delta5150** [comment] 2021-07-26 08:31
![no fuel](https://user-images.githubusercontent.com/79176046/126958471-d85dbb81-939d-42d9-aba2-be2147c8f678.jpg)
Re-installed MSFS and still no fuel and no fuel flow.

**Comment by tracernz** [comment] 2021-07-26 18:03
Duplicate of https://github.com/flybywiresim/a32nx/issues/5316. Please use the work-around in there.

**Closed by tracernz** 2021-07-26 18:03 UTC
Labels: Bug

**Comment by delta5150** [comment] 2021-07-26 19:36
Thank you very much for your help! Problem solved.
