### ISSUE TITLE
Battery voltage is at 0.0 

### ISSUE THREAD

**Issue by Pilot3434** [flybywiresim/a32nx#6126] opened 2021-11-02 14:12 UTC
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-11-02T11:51:01+00:00",
  "ref": "experimental",
  "sha": "5b3bd56481eab94083dc9d4931dc4c3290d2aca3",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

The battery voltage is at 0.0. That's why I can't start the plane.

### Expected behavior

I expected that I wouldn't have any bugs and I expected that I could just take off the plane and take off.

### Steps to reproduce

I recognized the error myself on the plane. 

### References (optional)

![2021-11-02](https://user-images.githubusercontent.com/93597465/139863805-1bff9cf3-781b-401b-8ea9-8637ab0d71eb.png)

### Discord Username (optional)

Pilot_Lufthansa#3840

**Comment by Saschl** [comment] 2021-11-02 14:50
Does your username contain any special characters like Umlauts?

**Comment by Pilot3434** [comment] 2021-11-02 15:04
> Enthält Ihr Benutzername Sonderzeichen wie Umlaute?

Nein

**Comment by beheh** [comment] 2021-11-02 15:39
Duplicate of #4778

[Please follow these steps](https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#autopilot-fadec-electrical-systems-not-working-as-intended-utf8-issue):
![grafik](https://user-images.githubusercontent.com/929769/139879726-c991c3c7-5995-4a30-8795-3d82532b9cd8.png)

**Closed by beheh** 2021-11-02 15:39 UTC
Labels: Bug
