### ISSUE TITLE
[BUG] No E/WD warning when speed brakes deployed

### ISSUE THREAD

**Issue by edelweiss0** [flybywiresim/a32nx#3730] opened 2021-02-26 16:36 UTC
**Mod Version**
Stable (0.5.3)

**Describe the bug**
When at least one engine is above idle the E/WD should display the "SPEED BRK" in amber.

**To Reproduce**
1. One or two engines above idle
2. Deploy speed brakes 

**Expected behavior**
Display "SPEED BRK" in amber in E/WD

**Actual behavior**
---

**References**
[https://i.gyazo.com/fa1703e2e06874987b246a8cc51c551f.png](https://i.gyazo.com/fa1703e2e06874987b246a8cc51c551f.png)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by hotshotp** [comment] 2021-02-26 18:02
It does show for me actually

**Comment by beheh** [comment] 2021-02-27 10:42
What's missing is the memo switching to pulsing amber if they're left out and then engine is non-idle.

**Comment by beheh** [comment] 2021-08-06 10:06
Turns out this a duplicate of #3087

**Closed by beheh** 2021-08-06 10:06 UTC
Labels: Bug, FWS
