### ISSUE TITLE
CoherentGT spikes cause bad stutters 

### ISSUE THREAD

**Issue by omarsmak** [flybywiresim/a32nx#4051] opened 2021-03-21 15:20 UTC
**Mod Version**

```
{
  "built": "2021-03-21T09:23:47+00:00",
  "ref": "autopilot",
  "sha": "77c3485fac2cde0b5c6648feaa80c6b3b3cc0658",
  "actor": "aguther",
  "event_name": "manual"
}
```

**Describe the bug**

Recently, I have noticed annoying spikes with CoherentGT, which as result, causes overall performance stutters. Although I am using `autopilot` branch, I have tested as well in `fbw` branch and it seems to reproducible these as well.

Here is a video that shows the stutters:
https://streamable.com/mhevoc

A screenshot:
![stutters](https://user-images.githubusercontent.com/1190920/111910240-d6319800-8a60-11eb-9b74-140de6541c34.JPG)

**To Reproduce**

There are no steps to produce it, even if you start from the runway and take off, you'd notice the spikes

**Expected behavior**

CoherentGT spikes should get less

**Actual behavior**

CoherentGT spikes occur

**References**

**Additional context**

Was this working before/when did the issue start occurring?
It occurs after recent few commits. I think last week wasn't there.

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by beheh** [comment] 2021-03-22 11:33
After some investigation, the culprit here seems to somehow be the useContext part of the useSimVar hook, but only on the PFD. 
In my tests the specific timing seemed completely unrelated to the actual refresh rate of the context, even when completely disabled. Maybe the large component tree allocates stuff faster than the gargabe collector can keep up?

**Comment by rhpa23** [comment] 2021-03-26 23:36
I had a CTD after land and the log shows fail on the  C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.14.6.0_x64__8wekyb3d8bbwe\**CoherentGTCore**.dll
Stutters during all the flight. The stutters don't happen on the Aerosoft CRJ700
Please prioritize this issue, I love the bird. Thanks

**Comment by Benjozork** [comment] 2021-03-26 23:48
@rhpa23 it's sadly not possible for us to diagnose the crashing issues before Asobo provides proper crash logs / debugging tools.

As for performance, it's being continuously worked on, but again, without any tracing tools from Asobo it's extremely hard.

**Comment by GlitchedYT** [comment] 2021-03-26 23:49
> I had a CTD after land and the log shows fail on the C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.14.6.0_x64__8wekyb3d8bbwe*_CoherentGTCore_*.dll
> Stutters during all the flight. The stutters don't happen on the Aerosoft CRJ700
> Please prioritize this issue, I love the bird. Thanks

CRJ doesn't have stutters as it doesn't use CoherentGT

**Comment by Benjozork** [comment] 2021-03-26 23:50
Side note: the CTD is extremely unlikely to be caused by the A32NX.

**Comment by rhpa23** [comment] 2021-03-26 23:55
> > I had a CTD after land and the log shows fail on the C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.14.6.0_x64__8wekyb3d8bbwe*_CoherentGTCore_*.dll
> > Stutters during all the flight. The stutters don't happen on the Aerosoft CRJ700
> > Please prioritize this issue, I love the bird. Thanks
> 
> CRJ doesn't have stutters as it doesn't use CoherentGT

There is any chance to remove this dependency from A32NX like the CRJ? I believe that this is the source of the stutters.

**Comment by Benjozork** [comment] 2021-03-27 00:05
That would require rewriting the entire codebase and would remove many features like ACARS, SimBrief integration, and such.

**Comment by SierraBravo1** [comment] 2021-04-04 19:29
I have the same issue like omarsmak with heavy performance drops of CoherentGTdraw every few seconds.
![coherentgt_drops](https://user-images.githubusercontent.com/76132388/113519082-53452d00-958a-11eb-8291-a2d348b28a39.png)

But I also had a CTD during a flight with the experimental version ("built": "2021-04-04T09:45:06+00:00",  "ref": "autopilot"). Windows event viewer showed that CoherentUIGT.dll (Version: 2.9.5.0) was the cause.

I just want to let you know this. Maybe there is a correlation between both failures and this can help to find the root cause.

**Comment by omarsmak** [comment] 2021-04-04 19:36
> I have the same issue like omarsmak with heavy performance drops of CoherentGTdraw every few seconds.
> ![coherentgt_drops](https://user-images.githubusercontent.com/76132388/113519082-53452d00-958a-11eb-8291-a2d348b28a39.png)
> 
> But I also had a CTD during a flight with the experimental version ("built": "2021-04-04T09:45:06+00:00",  "ref": "autopilot"). Windows event viewer showed that CoherentUIGT.dll (Version: 2.9.5.0) was the cause.
> 
> I just want to let you know this. Maybe there is a correlation between both failures and this can help to find the root cause.
> 
> 

Did you try to hide the VFR maps icon from the toolbar? With me, it was the issue actually, I removed the VFR icon from the toolbar and the issue was gone. I think that is a bug in the VFR map that causes these spikes

**Comment by SierraBravo1** [comment] 2021-04-04 21:09
Thank you for the advice. I did several tests, but unfortunately the disabling of the VFR icon or all other icons in the toolbar doesn't help. The spikes in CoherentGT time are still present.

**Comment by Benjozork** [comment] 2021-04-04 21:25
At this point there's not a ton we can do, MSFS needs to be optimized in how it runs aircraft code.

**Comment by SierraBravo1** [comment] 2021-04-04 21:41
Understood, thank you for the feedback.

**Comment by SierraBravo1** [comment] 2021-04-12 20:00
The CoherentGT performance drops and stutters at my setup were mainly caused by the Navigation Display, especially when routes with lots of waypoints are loaded.
The CoherentGT drops and such the stutters are almost eliminated if both Navigation Displays are switched off. This is not very practible, of course, but even disabling the F/O display reduces the drops noticeably.

**Comment by Benjozork** [comment] 2021-05-10 17:30
The most likely culprit of this is probably GC pauses every few seconds due to excessive allocations performed during the preceding update cycles.

Right now there is no way to track allocations, but this is coming with Sim Update 4. I have a few ways in mind of reducing them, and will be doing some testing once tracking allocations is possible.

**Comment by rhpa23** [comment] 2021-05-26 15:08
I don't know if this workaround can help here but seems when reloading the aircraft you flush out allocations.
https://www.youtube.com/watch?v=8R-URWmlyUo

**Comment by SierraBravo1** [comment] 2021-06-15 20:34
@rhpa23 thank you for this good hint. I tested it with my setup.
The stutters are not completely fixed, but reduced as described in the video if the aircraft is reloaded.
It's not much, so it was hard to evaluate. But I made two typical screenshots of the FPS window (see below). Some deep performance drops are still present, but in total there is definitely less activity of the CoherentGTDraw if the aircraft was reloaded.
I tested also to restart the complete flight instead of only the aircraft, which had the same positive effect. (Load flight as usual from the world map [FLY], go to menu by [ESC] and press Restart [HOME]).

First Load of Flight:
![first_load](https://user-images.githubusercontent.com/76132388/122119076-14a0de00-ce29-11eb-995d-d5f88a34ce31.png)

After Reload of Flight:
![restart](https://user-images.githubusercontent.com/76132388/122119093-18346500-ce29-11eb-8f8e-054cc997829b.png)

**Comment by Benjozork** [comment] 2021-06-15 20:47
I've observed the same things. Coherent performance seems noticeably better after reloading all displays using webui-devkit.

**Comment by Benjozork** [comment] 2021-06-26 06:44
Seems fixed by Sim Update 5 (not available yet) so far.

**Comment by SierraBravo1** [comment] 2021-06-30 20:31
Thank you for the update, that would be great.
It was also mentioned in the Dev Q&A today.

**Comment by SierraBravo1** [comment] 2021-07-27 21:28
Fixed with Sim Update 5 👍

**Closed** 2021-07-27 21:32 UTC
Labels: Bug, Performance
