### ISSUE TITLE
A32nx Mod Not Being Integrated (Cope-Paste Installation) [BUG] 

### ISSUE THREAD

**Issue by Mino1112** [flybywiresim/a32nx#1860] opened 2020-11-11 11:35 UTC
**Mod Version**
 
master

built: 2020-11-11T06:51:18+00:00
ref: refs/heads/master
sha: 03831bb4d7b73d0e532b73ce8872189eb05b84c7
actor: Benjozork
event_name: push

**Describe the bug**

I've installed both the dev and master A32nx mod to my community folder, and I even used the new installer, but no luck, the mod is not working/not being integrated. 

**To Reproduce**

1. I downloaded the master A32nx mod yesterday (10/11/2020)
2. I place it in the community folder after unzipping it with 7-zip
3. I started a flight expecting all the new integrations, like ADIRS or Ecam pages, but the mod is not showing up.

**Expected behavior**

I expected the A320 to have all the extra features the mod offers, but the mod isn't working.

**Actual behavior**

The default A320 is what is showing up, and the mod is not working.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
The mod never worked.
Is this a problem in the vanilla unmodded game?
Yes.

Discord username (if different from GitHub):

**Comment by saintwolf** [comment] 2020-11-11 11:39
Are you downloading the master repo, or the vmaster release? I had the same problem where I was downloading directly from the master branch, where npm build is required to generate some files. If you download the pre-built version at https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip then that worked for me!

**Comment by Pleasure0102** [comment] 2020-11-11 12:56
> Are you downloading the master repo, or the vmaster release? I had the same problem where I was downloading directly from the master branch, where npm build is required to generate some files. I downloaded the pre-built version at https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip then that worked for me!

you are correct, the master version requires npm to be run, we use this version to develop and this is automatically run in the vmaster build. This is done this way to make it easier for us to upload changes. 
If you download the link above, or use the installer this should be resolved. Please use discord if it is not.
Closing this as it is not a bug.

**Closed by Pleasure0102** 2020-11-11 12:56 UTC
Labels: Bug
