### ISSUE TITLE
alieron not working

### ISSUE THREAD

**Issue by deian1234** [flybywiresim/a32nx#5865] opened 2021-09-20 08:29 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-09-19T20:59:10+00:00",
  "ref": "master",
  "sha": "74045fb5eb77b3043f816d8d26028c33fb63bfd4",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Hello , i was just flying the plane and suddenly the ailerons didn't work anymore, the pedals didn't work anymore, I tried to re-install the plane from the content manager, I tried all the versions, now the pedals work but the ailerons still don't work, maybe you can help me with this error.thank you

### Expected behavior

the alierions don t work , i expected after re install to work. 

### Steps to reproduce

during taxy the pedals didn t work
than the alierons stopped working

### Discord Username (optional)

𝒹𝑒𝒾𝒶𝓃ﾉᶜᵒˣ#0656

**Comment by aguther** [comment] 2021-09-20 20:55
Are you using keyboard?

**Comment by deian1234** [comment] 2021-09-21 19:07
yes i m using keyboard , i tried even a joystick . please can you help me?

**Comment by deian1234** [comment] 2021-09-21 19:08
> Are you using keyboard?

yes i m using keyboard

**Comment by deian1234** [comment] 2021-09-22 07:12
> Please ensure no SimConnect.cfg is in your document folder and if you’re using keyboard this does currently not work for ailerons due to a bug in the SDK.
> 
> I recommend coming in the discord in support channel which might bring you faster a solution.
> 
> Your issue is with a very high probability related to your setup and not a bug in the A32NX.
i joined your discord , maybe a moderator can help me , thank you

**Comment by aguther** [comment] 2021-09-22 16:47
Please go to channel #support, describe the issue and ask for help. You did not answer if you are using keyboard, if so: it‘s currently not working due to a bug in the SDK.

**Comment by aguther** [comment] 2021-09-23 07:44
Duplicate of #4694

**Closed by aguther** 2021-09-23 07:44 UTC
Labels: Bug, Waiting For Response
