### ISSUE TITLE
[BUG] Airplanes start banking to 45° either right or left not following LNAV 

### ISSUE THREAD

**Issue by Remy737** [flybywiresim/a32nx#1007] opened 2020-09-30 19:58 UTC
**Mod Version**
 master

**Describe the bug**
 Airplanes start banking to 45° either right or left not following LNAV

**To Reproduce**

 everytime after take off 
1.
2.
3.

**Expected behavior**

following LNAV route

**Actual behavior**

Banking left or right

**References**

**Additional context**

Was this working before/when did the issue start occurring?
after the release of version 0.3.1
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MTRNord** [comment] 2020-09-30 20:18
This is a duplicate of #1006 I believe

**Comment by MisterChocker** [comment] 2020-12-31 07:00
closing now

**Closed by MisterChocker** 2020-12-31 07:00 UTC
Labels: Autopilot, Bug
