### ISSUE TITLE
I believe auto throttle should disengage during final flare 

### ISSUE THREAD

**Issue by Zyonix007** [flybywiresim/a32nx#175] opened 2020-08-28 04:31 UTC
I think its supposed to correct me if i am wrong

**Comment by SmithFR** [comment] 2020-08-28 04:40
I think it doesn't that's why you need to put the throttle to idle when touching the ground during cat 3 landing but i'm not an a320 pilot so if someone could help that would be great

**Comment by chrisarrow90** [comment] 2020-08-28 06:54
The Autothrottle remains engaged until thrust lever is set to idle by the pilot. However the behavior of the autothrottle is different depending on whether or not is an automatic or manual landing.

With AP/FD engaged in LAND mode during an autoland the autothrust will automatically enter 'RETARD' mode at approximately 40 FT RA. (Autothrottle remains engaged in RETARD until thrust set to idle by pilots during the landing roll).

During a manual landing, the autothrottle remains in SPEED mode and the thrust levers must be manually retarded to disconnect the autothrust.

Attached is the FCOM references.

![athr retard mode](https://user-images.githubusercontent.com/44491664/91530066-8b362300-e95e-11ea-8644-7d4579d99855.jpg)

![athr2](https://user-images.githubusercontent.com/44491664/91530070-8d987d00-e95e-11ea-8b68-7cbb24504094.jpg)

**Comment by ko-zone** [comment] 2020-08-28 23:46
The plane is meant to RETARD on its own if you have both autopilots on and automatically disengages after touching down

**Comment by chrisarrow90** [comment] 2020-08-29 00:23
> The plane is meant to RETARD on its own if you have both autopilots on and automatically disengages after touching down

No it doesn’t automatically disengage after touchdown. Check my FCOM reference above on second line `... RETARD mode engages and remains engaged after touchdown`. FMA will show IDLE in the autothrust column until pilot retards the thrust lever to idle to disengage the A/THR.

**Comment by PCGamesF1Tech** [comment] 2020-08-29 11:25
A/THR and AP are two independent systems.
A/THR should command idle thrust (THR IDLE in FMA) for landing (thrust levers still in CLB notch). 
For ground logic and spoilers to work (even if you forgot to arm them) and autobrake (activated by spoiler extension) you need the thrust levers physically at idle (or at least one of them in REV)

**Comment by chrisarrow90** [comment] 2020-08-29 12:51
A/THR only commands idle thrust during an AUTOLAND with the AP engaged. There has been several incidents in real life where pilots have forgotten to retard the thrust lever during a manual landing and as a result on contact with the ground the aircraft maintains thrust to target VAPP. That’s why the aural “RETARD” call.

**Comment by PCGamesF1Tech** [comment] 2020-08-29 13:08
Thats why our company policy is "manual flight - manual thrust".
I don't know how other airlines do it...

**Comment by chrisarrow90** [comment] 2020-08-29 13:13
So you disengage the autothrust on every landing unless its an autoland? Interesting... My past 2 airlines let us use the autothrust without the autopilot

**Comment by PCGamesF1Tech** [comment] 2020-08-29 13:17
Whenever we want we can disconnect the AP and A/THR and fly manually.
And yes, basically every landing except autolandings of course.

**Comment by JackZ974** [comment] 2020-08-29 15:40
> 
> 
> Whenever we want we can disconnect the AP and A/THR and fly manually (even from cruise FL...)
> And yes, basically every landing except autolandings of course.

That's definitely NOT the Standard Airbus way, to say the least..... Autothrottle is recommended by Airbus for every landing, to take advantage of the GS Mini function. But can be disconnected of course

**Comment by PCGamesF1Tech** [comment] 2020-08-29 19:30
GSmini is independent from A/THR, it adjusts Vapp in manual or autoflight!
Using selected speed for approach instead of managed speed "kills" the GSmini, NOT by deactivating A/THR.....

**Comment by A320pilotIRL** [comment] 2020-09-03 18:35
Bringing thrust levers to idle is what disengages the autothrust on landing. That’s why it calls out RETARD RETARD because it needs you to move it to idle. 

All that said, in the flare it should still bring the actual thrust to idle even if you dont

**Comment by hotshotp** [comment] 2020-10-24 02:27
autothrust disengages when putting throttle levers to idle. closing as this has been confirmed by real pilots as correct behaviour

**Closed by hotshotp** 2020-10-24 02:27 UTC
Labels: Bug-Vanilla
