### ISSUE TITLE
[BUG] No working EXT Power function with some Sceneries, here GAYA (ORBX Partner) Sceneries

### ISSUE THREAD

**Issue by Striezelr** [flybywiresim/a32nx#838] opened 2020-09-24 16:43 UTC
0.2.0

**Describe the bug**
In connection with GAYA Sceneries (from ORBX..  LGKO, EDDT, LOWZ) no ext Power working, all dead!

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by Aarondodd88** [comment] 2020-09-24 16:54
Are you ate a gate that doesn't have external power on ground? APU power is used if no external power. Not all gates have GPU available

**Comment by x4nthx** [comment] 2020-09-24 17:34
I've been investigating that and it seems since last fs2020 update the code reads airports without gates as no power supply option enable. so it disables the external power button. Tested in different airports with the latest a320nx master

**Comment by visualcookie** [comment] 2020-09-24 17:46
Looks related to #718

**Comment by AdenFlorian** [comment] 2020-09-24 19:36
Does the external power button not say AVAIL? Or it does, but when turning it on, nothing else powers up?

**Comment by AdenFlorian** [comment] 2020-09-24 19:39
closed as this is either not a bug specific to the A320 (meaning its an asobo problem tied to spawn points at airports), or its a duplicate of #718

**Closed by AdenFlorian** 2020-09-24 19:39 UTC
Labels: bug, need more info

**Comment by Striezelr** [comment] 2020-09-24 19:41
I always try on the same airport ( new KEYW) After installing GAYA Airports ext pwr says AVAIL, but no reaction, everything remains dark. After uninstalling Gaya sceneries (also with the Lisboa Citypack freeware) it works on the same airport. So it has nothing to do with the gate
