### ISSUE TITLE
[BUG] Callsign and flight number not used during ATC communication

### ISSUE THREAD

**Issue by HammerAce42** [flybywiresim/a32nx#1795] opened 2020-11-08 00:48 UTC
**Mod Version**
master
built: 2020-11-07T21:16:46+00:00
ref: refs/heads/master
sha: 3dd9cf63ed0f04f8eb95041ec719447dc303f171
actor: Benjozork
event_name: push

**Describe the bug**
ATC callsign + flight number are not used by ATC. Instead, ATC uses the tail number. This does not occur in the vanilla version of the a32x

**To Reproduce**

1. In ATC options for the default Asobo Airbus livery of the A32x, set callsign + flight number e.g. "ALASKA", "1180" respectively
2. Start the flight and initiate any communication with ATC
3. Note that ATC uses Airbus Alpha Sierra 320 as the callsign instead of Alaska 1180

**Expected behavior**

ATC uses the callsign and flight number set in ATC options

**Actual behavior**

ATC uses the tail number of the aircraft even if a callsign and flight number are set.

**References**

**Additional context**

I disabled any liveries for the a32x to ensure that was not the root cause.

Was this working before/when did the issue start occurring?
This was working in earlier versions of the FBW A32nx. Not sure when this issue was introduced since I haven't flown it in a while.

Is this a problem in the vanilla unmodded game? 
No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-11-08 00:50
Could be caused by #1280

**Comment by Rameyuk** [comment] 2020-11-08 06:04
I confirm I have this bug too. But to add some additional context.
I'm using the Callsign and flight number set in my Livery Aircraft.CFG settings (so I don't have to keep changing it in the ATC options) but the latest master build disregards both ATC options and the livery setting.

Prior to the latest master build (the one committed in the 6th or 7th Nov), the mod takes the flight number set in the MCDU as expected which overrides the flight number set in the livery or ATC options as expected. But the latest master build disregards the callsign entirely, even after setting the flight number in the MCDU.

**Comment by ischmal** [comment] 2020-11-08 07:21
After takeoff it will actually switch to using the callsign defined in the game's ATC menu and the flight number defined in the MCDU (which I'd say is the expected behavior).

For full context, my ATC menu is configured: registration is "N1837BC," callsign "AMERICAN," flight number "1837." In the MCDU I set FLT NBR as "610."

![image](https://user-images.githubusercontent.com/5350086/98459446-10f0fe80-2158-11eb-9a18-97383d922cdf.png)

On the ground my callsign is "Airbus NC1837BC," once airborne it suddenly becomes "AMERICAN 610."![image](https://user-images.githubusercontent.com/5350086/98459403-c53e5500-2157-11eb-98b0-89921ac180a5.png)

**Comment by Rameyuk** [comment] 2020-11-08 08:40
I was just to give an update that what @ischmal said is the current behaviour. It started with the Airbus callsign on the ground, after take off my callsign becomes the callsign set in either the ATC options or the Livery aircraft.cfg. Since I don't have my tail number assigned because there's a risk of doubling the tail number with the one in the Livery, mine just called Airbus.

I don't know if this is the expected behaviour on the ground though? We might need confirmation from a real A320 pilot.

**Comment by ischmal** [comment] 2020-11-08 08:57
Sorry, I worded that poorly. I meant that the eventual callsign you switch to is the one you'd expect to have the entire time (starting at the gate). I believe this is very much a bug.

**Comment by stubbyswiss** [comment] 2020-11-08 17:21
I to am experiencing this bug, and actually reported it as well, but then I noticed it had already been reported.

I can also now confirm, that **AFTER** take-off the ATC communications reverts to how it is supposed to be - calling you by the Airline and flight number. Prior to take-off, you are referred to as referred to as aircraft type and tail number, as has been reported.

Thanks.

**Comment by wpine215** [comment] 2020-11-10 00:45
Issue was brought up with ATSU update. Investigating.

**Comment by dnoe10** [comment] 2020-11-11 12:56
I am experiencing the same behavior on the following build:
```
built: 2020-11-09T06:02:02+00:00
ref: refs/heads/master
sha: 1bbab5800817b94fc74411c234548cb31dc5c90c
```

**Comment by nistei** [comment] 2020-11-12 01:34
Found the issue. Working on it

**Closed** 2020-11-12 02:53 UTC
Labels: Bug
