### ISSUE TITLE
Company Routes

### ISSUE THREAD

**Issue by boomcreeper11** [flybywiresim/a32nx#5861] opened 2021-09-19 20:16 UTC
### Aircraft Version

Stable

### Description

I think something that would really increase the realism of the aircraft is a company route sytem.
***
This could work by creating it's own flight plans in it's own format and then just reloading those for company routes.

### Discord Username (optional)

Scrub Man#4699

**Comment by Benjozork** [comment] 2021-09-21 18:58
Duplicate of #1656

**Closed by Benjozork** 2021-09-21 18:58 UTC
Labels: Request
