### ISSUE TITLE
[BUG] FO Radio Dial Doesn't Cycle Frequencies

### ISSUE THREAD

**Issue by mak60062** [flybywiresim/a32nx#2677] opened 2020-12-24 06:02 UTC
**Mod Version**

{
  "built": "2020-12-23T23:38:26+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**

The First Officer-side radio dial does not cycle through frequencies.

**To Reproduce**

1. Twist the FO-side radio dial in either direction. (Either dial)

**Expected behavior**

Frequency should cycle up or down

**Actual behavior**

Dial fully inop.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Working before latest MSFS patch. 

Is this a problem in the vanilla unmodded game?
Unknown

Discord username (if different from GitHub): Mobius_One_Fox3

**Comment by Migqle** [comment] 2020-12-24 15:32
Also not working for me, but on both FO and Captain side.

**Comment by Awemeter** [comment] 2021-01-04 04:54
I believe this is not a bug but is intentional. The FO panel mcdu and radio is currently synced with the Captain's. This is annoying for shared cockpit but I think this was done to minimize the FPS drop. ￼

**Comment by tareksabet** [comment] 2021-01-06 01:17
so It's a known issue until now we can't do anything with it will close the issue right now as it's a vanilla bug to reduce FPS but it will be implemented don't worry. 

Thanks for reporting this issue.

**Closed by tareksabet** 2021-01-06 01:17 UTC
Labels: Bug
