### ISSUE TITLE
Flight Plan Import via .PLN (or similiar) file

### ISSUE THREAD

**Issue by ghost** [flybywiresim/a32nx#4327] opened 2021-04-06 23:21 UTC
**Is your feature request related to a problem? Please describe.**

/

**Describe the feature you'd like to see implemented**

Currently the A32NX only allows importing flight plans via Simbrief. However many people are using standalone software like Little Navmap or PFPX to create their flight plans. I really would like to see a import option via a flight plan file.

**References**

I would just like to point out, that the Aerosoft CRJ700 has an option to import flight plans via a file in the aerosoft "work" folder. Hopefully it is possible to use a similar file format.

**Additional context**

/

Discord username (if different from GitHub): AllCanor

Thanks!

**Comment by tracernz** [comment] 2021-04-07 00:25
A JSON based format would be best, but most likely not worth looking at until further down the track when a new flightplan manager is implemented.

**Comment by Charterflieger** [comment] 2021-07-16 06:53
Hi, in which folder should I save the flightplan created with Simbrief to get them for ready to load in the A32NX? Thanks Charterflug

**Comment by bouveng** [comment] 2021-07-16 07:06
> Hi, in which folder should I save the flightplan created with Simbrief

You do not have to. You can just import it by adding your username to the MCDU.
Look here: https://www.youtube.com/watch?v=l_5J7ZuEEtk

**Comment by derl30n** [comment] 2022-04-10 01:06
Duplicate of https://github.com/flybywiresim/a32nx/issues/1656

**Closed by derl30n** 2022-04-10 01:06 UTC
Labels: Request, FPM
