### ISSUE TITLE
EFB unusable in VR

### ISSUE THREAD

**Issue by 4evercool** [flybywiresim/a32nx#5297] opened 2021-07-11 04:41 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-10T11:13:17+00:00",
  "ref": "master",
  "sha": "a33bbcf89fd5a011163eee22d6c0eb4a8af46796",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

The mouse cursor does not "stick" to the EFB screen in VR mode and hovers above it which makes using EFB in VR virtually impossible. Panel collision should be added as described in the [SDK](https://docs.flightsimulator.com/html/index.htm#t=Asset_Creation%2F3D_Models%2FAircraft%2FAircraft_Cockpit.htm) .

### Expected behavior

Correct operation of the EFB in VR.

### Steps to reproduce

Launch the plane.

### Discord Username (optional)

CoordinatorYS

**Comment by peterg928** [comment] 2021-07-11 09:27
Agreed, but as a workaround I close one eye so I can focus the mouse pointer in the right place!

**Comment by 2hwk** [comment] 2021-07-12 09:43
Duplicate of #3493, closing.

**Closed by 2hwk** 2021-07-12 09:43 UTC
Labels: Bug
