### ISSUE TITLE
[BUG] MCDU DIR Page does not function

### ISSUE THREAD

**Issue by matthias1602** [flybywiresim/a32nx#3986] opened 2021-03-15 13:25 UTC
**Mod Version**
{
  "built": "2021-03-14T22:53:58+00:00",
  "ref": "master",
  "sha": "cd4402452bafee8391bd09a81d1ce362cc2d75f1",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**
The DIR Page should delete the last waypoints if I choosed to fly DIR a Waypoint in the Flightplan. Also it should give a TP
in the Flightplan. Also the Waypoints before the choosen Waypoint schould be deleted.

**To Reproduce**

1.I took for example the ogber25R Transition to EDDB. I gave him a dir DB413 after it reaches the DB413 it wents DIR ROBEG which was 180nm behind my current flight.
2.
3.

**Expected behavior**
Normaly it should delete the Waypoints before and if I reached the Waypoint which I selected for a Direct it should Proceed on the Flightplan (for Example after DB413 the DB423).

**Actual behavior**
The Waypoints before does not deleted and it followed a Waypoint well behind my Lateral Path.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
No

I haven´t got.

**Comment by MisterChocker** [comment] 2021-03-16 17:49
Duplicate of #1745

**Closed by MisterChocker** 2021-03-16 17:49 UTC
Labels: Bug
