### ISSUE TITLE
[BUG] Need Startup Without External Power

### ISSUE THREAD

**Issue by wdmaxq** [flybywiresim/a32nx#621] opened 2020-09-12 19:04 UTC
**Mod Version**
Version 0.2

**Describe the bug**
The panel displays only activate when external power is connected and activated. Thus it is not possible to activate the panel displays straight from battery to APU, without external power.

**Comment by UncleClapton** [comment] 2020-09-13 09:50
This is not a bug. Panels require AC power according to the documentation we've gotten. AC power can only be supplied via external power or the APU. You can turn on the APU with battery power, though.

**Comment by wdmaxq** [comment] 2020-09-14 02:09
Thanks for your quick reply. You are correct. I was not waiting long enough for the APU startup before the APU generator kicks in.

**Comment by NathanInnes** [comment] 2020-09-22 15:43
Closing issue as it seems to be resolved.

**Closed** 2020-09-22 21:51 UTC
Labels: bug
