### ISSUE TITLE
CTD with "Load Modules Asynchronously" setting on master

### ISSUE THREAD

**Issue by egpd1701** [flybywiresim/a32nx#6388] opened 2021-12-19 19:17 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-18T16:57:54+00:00",
  "ref": "master",
  "sha": "6470651afbc7c6643b3568035eb7372e4aae49ad",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

Starting the Sim after pressing the Fly button from the world map with the DEV version or switching to the DEV version after a successful load causes a CTD.

### Expected behavior

Sucessfuly Sim start

### Steps to reproduce

1. Load Sim
2. Choose Airport - Gate or on runway start position with FBW Dev aircraft
3. Press Fly
4. 3/4 of next loading screen CTD occurs

or
1. Load Sim
2. Choose airport with aircraft that come with Sim
3. Press Fly
4. Sim loads ok
5. Change aircraft to Dev version - immediate CTD

Stable version does not CTD

### References (optional)

<img width="656" alt="Capture-err1" src="https://user-images.githubusercontent.com/9488741/146687780-87ae30df-8b80-49c3-b55e-fb221e7bda71.PNG">
<img width="557" alt="Capture-dev" src="https://user-images.githubusercontent.com/9488741/146687788-b3312a7b-7988-4119-aacc-fe610ad3cc5a.PNG">

### Additional info (optional)

The Stable version has no issues

### Discord Username (optional)

Glenn #6307

**Comment by egpd1701** [comment] 2021-12-19 19:45
I cleared out the FBW again and I noticed the fbw dir in the packages has now got the same file names but of a different size from the last post

<img width="574" alt="Capture-dev2" src="https://user-images.githubusercontent.com/9488741/146688605-3679907f-75d3-41fb-8ea2-273688850453.PNG">

**Comment by tshomas** [comment] 2021-12-19 19:45
I've just had this all day too, and I may have a solution.

If you activate developer mode in the sim
![image](https://user-images.githubusercontent.com/74841560/146688646-81b47d3f-d2d6-480a-bc83-9647b83311f5.png)

**Comment by tshomas** [comment] 2021-12-19 19:46
And go to the top bar that appears, under options:
![image](https://user-images.githubusercontent.com/74841560/146688656-426aaf32-285e-48c9-a780-147e1018dad1.png)


If you deselect the "load modules asynchronously", and try loading a flight, does it work then?

**Comment by egpd1701** [comment] 2021-12-19 19:58
Hi

I've already got those options on - just tried removing FAST WASM Compilation but that didn't help

**Comment by tshomas** [comment] 2021-12-19 20:00
Yeah please reread, try with async off!

**Comment by egpd1701** [comment] 2021-12-19 20:05
That worked, much appreciated. Dont know why it worked but it does 😄

**Comment by beheh** [comment] 2021-12-19 20:42
I can confirm the same. CTD upon loading, no matter if loading into a parking position, runway, or the air, and also CTD if loading in a different aircraft and switching to the A32NX since.

@lukecologne reports this issue was introduced with the Tiller PR (#6187) by @crocket63.

**Comment by donstim** [comment] 2021-12-20 02:09
Interesting. I don't have this issue myself. No CTD's, latest dev version, and Load Module Asynchronously is checked.

**Comment by crocket63** [comment] 2021-12-20 10:23
> Interesting. I don't have this issue myself. No CTD's, latest dev version, and Load Module Asynchronously is checked.

Was there a new pr merged after tiller when you tried?

**Comment by frankkopp** [comment] 2021-12-20 10:54
> Interesting. I don't have this issue myself. No CTD's, latest dev version, and Load Module Asynchronously is checked.

Me neither - have made several tests now - no CTD whatsoever - with or without "Load Modules Asynchronously" or any other user reported CTDs (flight plan imports, pressing various buttons in the MCDU, etc.)

I just don't get any CTDs :) while using the A32NX. I get them when changing aircraft - but this stabilizes when I stay with one aircraft for a few starts.

**Comment by tshomas** [comment] 2021-12-20 10:59
The only thing I can say is that the first time in the loading screen after a clean install it was CTDing for me with the async on.

As soon as I turned it off, the dev loaded fine, and then re enabling it afterwards didn’t result in a CTD. 

It’s not the async being on = dev CTD as I can run dev with it on after the first load, but there’s something else going on underneath somewhere…it might even be related to the users setup or anything.

**Comment by crocket63** [comment] 2021-12-20 11:07
Those with the issue still have the issue on last dev?

If yes I might try removing randomly parts of tiller pr to see if anything solves it

**Comment by egpd1701** [comment] 2021-12-20 11:11
I removed one of the Wash files (renamed it) and the CTD's stopped. Re-enabling it again caused the CTD's. I think I mentioned which was file in the Discord channel

**Comment by tshomas** [comment] 2021-12-20 13:12
User today in support with same issue, fix worked for them. Said that they had it working on Saturday (18th), updated today and the CTDs started. No idea if that’s of any use.

**Comment by egpd1701** [comment] 2021-12-20 16:06
Just tried the latest build - still CTD'ing with "Load Modules Asynchronously" ticked

**Comment by donstim** [comment] 2021-12-20 17:23
> > Interesting. I don't have this issue myself. No CTD's, latest dev version, and Load Module Asynchronously is checked.
> 
> Was there a new pr merged after tiller when you tried?

This last time, yes. But didn't have it right after tiller PR was added to the master, nor when I was checking out the tiller PR.

**Comment by aguther** [comment] 2021-12-20 18:27
I have also no issues and loading wasm modules asynchronous is checked.

**Comment by tracernz** [comment] 2021-12-21 03:35
I've got async loading and also no issues on any branches.

**Comment by egpd1701** [comment] 2021-12-22 13:52
Going to try tonight if there has been any updates. It didn't work with yesterdays update though.

**Comment by sidnov** [comment] 2022-02-21 10:19
@egpd1701 issue fixed?

**Comment by egpd1701** [comment] 2022-02-21 10:35
Hi. Not sure. I'll need to check when I get home, I've been scenery designing lately.

**Comment by sidnov** [comment] 2022-02-21 10:46
> Hi. Not sure. I'll need to check when I get home, I've been scenery designing lately.

We currently have systems in place to override the WASM loading/ asynchronous module options, so the issue is most likely to not occur again. Feel free to re-open this issue if it happens anytime in the future

**Closed by sidnov** 2022-02-21 10:46 UTC
Labels: Bug
