### ISSUE TITLE
MCDU - external mobil device

### ISSUE THREAD

**Issue by Blizzard225** [flybywiresim/a32nx#6262] opened 2021-11-28 15:09 UTC
### Aircraft Version

Development

### Description

Aviaworx developed a possibility to control MCDU of MSFS2020 CRJ by mobil devices (e.g.iPad). It would be very very great if FBW could collaborate or give the possibility for Aviaworx to develop a comparable MCDU connection (DataRefs etc.) in order to use the A23NX. It think a lot of user would be very very happy including myself.

### Discord Username (optional)

FSC749 Rolf-Dieter_R#4384

**Comment by robro8** [comment] 2021-11-29 12:33
oh yes, that would be a great thing

**Comment by tracernz** [comment] 2021-11-29 21:15
Duplicate of #4000.

**Closed by tracernz** 2021-11-29 21:15 UTC
Labels: Request
