### ISSUE TITLE
[BUG] Upon touchdown plane does sharp left turn

### ISSUE THREAD

**Issue by ipsjwa1978** [flybywiresim/a32nx#1884] opened 2020-11-12 18:57 UTC
**Mod Version**

**Describe the bug**
<!—Upon landing when the rollout begins the plane turns sharply to the left and no amount of steering with bring it back to the centre. -->

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Issue only occurred after downloading latest master. 
Is this a problem in the vanilla unmodded game?

**Comment by Benjozork** [comment] 2020-11-12 19:05
Duplicate of #974 and doesn't respect template.

**Closed by Benjozork** 2020-11-12 19:05 UTC
Labels: Bug
