### ISSUE TITLE
[BUG] Frequency Com1 don't sync with IVAO Altitude

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#1987] opened 2020-11-17 06:52 UTC
**Mod Version**

2020-11-10T5m

**Describe the bug**

1. Select a frencecy under Altitude like unicom 122.8
2. Displayed com1 remains by default at 124.850
3.
Here answer of IVAO support for this problem:

I have done some testing myself and yes Altitude does not change the frequency of the active Com1/2 in the airbus but this does not affect your ability to contact the controller as on Altitude it will stay on the correct frequency it is only a display issue in the aircraft. It is also possible to change the frequency by the aircraft by changing the standby frequency to active both Altitude and the aircraft will display the correct frequency.

I am aware that the frequency not changing in the aircraft when selected in altitude can not look good but this is due to how the A320 is a module as other MSFS aircraft do not have this issue. Due to this only being an issue on one aircraft it is not a high priority, as this also does not stop you from using the network.

I have also tested the transponder and have no issue with this, changing the code via the sim and via altitude will display both correctly. Also, it is possible to turn the transponder on through both but if turned on by altitude it will not display in the simulator but this is the case with most simulators. The only part that does not work is the Ident button, I believe this is due to the lack of systems in MSFS for this.

As I have not been able to recreate these problems both with and without the Flybywire mod, I can not assist you anymore. If you believe I do not understand the issue I would ask that you recorded your issue so I can better understand.
**Expected behavior**

**Actual behavior**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):

**Comment by JLD95** [comment] 2020-11-17 07:54
![2020-11-17 (6)](https://user-images.githubusercontent.com/5894146/99361493-6f358400-28b2-11eb-88a8-40a0c946f4b6.jpg)

**Comment by jmwebslave** [comment] 2020-11-17 11:22
I know what it is that you're talking about, but I didn't really follow your description.

In my case, I have a Stream Deck that I have a plug-in so that I can change the frequency on COM1 via SimConnect.  I use this so that when I fly on VATSIM using vPilot I can more readily change frequencies.  At first I thought it wasn't working via the Stream Deck because I could key a frequency on it and see it not change in the sim.  What I noticed though was in vPilot the frequency showed as changed, and I could hear other traffic on that frequency.

So, if anything, it seems like the frequencies displayed in the sim don't update when they are set externally via SimConnect.

**Comment by Kimbyeoungjang** [comment] 2020-11-17 13:14
i think that is asobo bug because when you turn on ATC assist, AI change frequency automatically.
when AI change frequency, COM1 frequency is changed but in sim, frequency is not changed(seems not changed but actually changed to target frequency)

**Comment by ElSrJuez** [comment] 2020-11-20 21:11
This I think shares a common root cause with: https://github.com/flybywiresim/a32nx/issues/1079

**Comment by davidwalschots** [comment] 2021-06-22 21:09
This is _likely_ fixed. I'm closing this now. Let me know if this isn't fixed yet.

**Closed by davidwalschots** 2021-06-22 21:09 UTC
Labels: Bug
