### ISSUE TITLE
Different T/O-Trim & CG values (chart/checklist/trim wheel) 

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#6318] opened 2021-12-07 08:58 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-05T22:59:20+00:00",
  "ref": "master",
  "sha": "e7bdd9796930970cbce0267a894bfff052d9f714",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

checking the FBW-Checklist including T/O Trimchart give different trim-values compared to the Airbus Trimwheel in the Plane.
**e.g. C.G. 24%
-Checklist Trimchart gives a trim of ~1.9UP
-Trimwheel gives me a T/O trim of ~0.5UP for CG 24**

I only know the A320CEO IRL - so I do not exactely know whats right on the NEO´s.

see attached

![Unbenannt](https://user-images.githubusercontent.com/72918017/144997844-1e5b07bf-d423-4e3a-98b8-09ff2ca190a5.jpg)
![trimsheet](https://user-images.githubusercontent.com/72918017/144997867-f6dd3e4b-a8fa-4627-b5d6-2a25a351060a.jpg)

### Expected behavior

trim values on checklist trim chart should match values on trimwheel

### Steps to reproduce

1. look for trim for a C.G. Value onto checklist
2. compare it with C.G. Trim value onto trimwheel

**Comment by andrejetcat** [comment] 2021-12-07 10:35
so, trim has to be set according chart on checklist ?!

Thank you for your reply

**Comment by NGS31** [comment] 2021-12-07 10:36
Hi :)

Because the decal is wrong, how can we do for setting a good CG / trim wheel position value ?

**Comment by andrejetcat** [comment] 2021-12-07 10:42
to my understanding, the "up/down" positions are OK, only the corresponding C.G values opposite are not correct...

correct me when I´m wrong

**Comment by NGS31** [comment] 2021-12-07 10:52
I have found this for A320, the scale is a little different.

![image](https://user-images.githubusercontent.com/95093820/145015936-84bd15fc-0b5c-4094-8c61-82d858efa9d1.png)

**Comment by donstim** [comment] 2021-12-10 16:42
> to my understanding, the "up/down" positions are OK, only the corresponding C.G values opposite are not correct...
> 
> correct me when I´m wrong

That is correct.

**Comment by donstim** [comment] 2021-12-10 16:45
> I have found this for A320, the scale is a little different.
> 
> ![image](https://user-images.githubusercontent.com/95093820/145015936-84bd15fc-0b5c-4094-8c61-82d858efa9d1.png)

That is not for the NEO.

**Comment by andrejetcat** [comment] 2021-12-10 16:51
the main difference of a NEO in relation to a CEO is, that the LEAP engines have adifferent weight. The airplane itself is nearly unchanged. So the trim of a NEO is different compared to a CEO. So if you have e.g. 25% MAG on a CEO with another engine weight, so you have to trim the plane different. You can´t use therefore the Trim Chart of a CEO for a NEO. 
But the ASOBO A320 represents the nose-up / Nose-down range of the CEO.

**Comment by NGS31** [comment] 2021-12-10 17:27
> 



> > I have found this for A320, the scale is a little different.
> > ![image](https://user-images.githubusercontent.com/95093820/145015936-84bd15fc-0b5c-4094-8c61-82d858efa9d1.png)
> 
> That is not for the NEO.

Yes, that's why I have written "A320" only :)

So how can we do to set correctly the trim without a good CG scale ?

Thanks :)

**Comment by andrejetcat** [comment] 2021-12-10 17:33
as above, the TAKEOFF CG values in the cockcpit are wrong. You have to look at the FBW Trim-chart. and use the Trim Position from it. The TRIM POS values are OK in the Cockpit, but not the "green range" 
so, e.g. for 28%MAC do not use 0.1UP, but use 0.8UP :)

**Comment by NGS31** [comment] 2021-12-10 17:37
Thanks a lot +++, I understand now :)

**Comment by 2hwk** [comment] 2022-07-15 07:55
Duplicate of https://github.com/flybywiresim/a32nx/issues/4312 closing

**Closed by 2hwk** 2022-07-15 07:55 UTC
Labels: Bug, Texture
