### ISSUE TITLE
MCDU: enter runway only on 'Arrival' page

### ISSUE THREAD

**Issue by TheJulzz** [flybywiresim/a32nx#6853] opened 2022-03-05 12:21 UTC
### Aircraft Version

Development

### Description

In the real aircraft it is possible to only select the runway on the 'Arrival' page in the F-PLN. This is feature is still missing in the FlyByWire's current version. 
Besides being able to select RNAV26-Z in this example, there is also an option to select 26 (as runway) only (→ compare screenshots). If you select it, it is inserted on line 6 in the F-PLN page as ICAO+RWY, like in this example LICC26 (without any other waypoints before it). There are two different versions, depending on the type of MCDU. The screenshots show FF (sceen 1) and Toliss (screen 2) versions. Im not sure how it looks exactly in the Honeywell H3, but im sure a real A320 pilot can answer that question.
Would be great if this could be implemented to make a further step towards the real MCDU and to allow us having more option in our experience. Thanks for your continuous effort!

![runwayonly](https://user-images.githubusercontent.com/75279952/156882511-30c4902e-7c73-4dba-bb47-aacba5ca1267.jpg)

![runwayonly2](https://user-images.githubusercontent.com/75279952/156882512-a6144b07-bb0f-4a59-8d01-9ba4435777c8.jpg)

### References (optional)

See screenshots

**Comment by tracernz** [comment] 2022-03-05 12:55
Duplicate of https://github.com/flybywiresim/a32nx/issues/954. Keep an eye out for this with the next big update to the FMS.

**Closed by tracernz** 2022-03-05 12:55 UTC
Labels: Request
