### ISSUE TITLE
[REQUEST] A32NX Not reaching the 30° of bank 

### ISSUE THREAD

**Issue by Flextemp** [flybywiresim/a32nx#1688] opened 2020-11-01 11:03 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

I've noticed since the project has started that the aircraft miss the standard coordinated bank of 30°, this lack seems to made turn, holdings and interceptions more complicated as the aircraft will take more time in space for a standard turn, hope this will be corrected soon, Regards.

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment] 2020-11-01 17:50
Duplicate of #874.

**Closed by Benjozork** 2020-11-01 17:50 UTC
Labels: Enhancement
