### ISSUE TITLE
[BUG] autopilot flying direct to runway instead of following STAR

### ISSUE THREAD

**Issue by peterg928** [flybywiresim/a32nx#2960] opened 2021-01-09 18:23 UTC
**Mod Version**
 master
{
  "built": "2021-01-09T07:07:10+00:00",
  "ref": "",
  "sha": "",
  "actor": "David Walschots <davidwalschots@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

IFR Flightplan with full routing entered into MCDU (built from Navigraph) with STAR and approach. All looks ok. Ive noticed a few times now when following the STAR at some waypoint the autopilot will disregard the rest of the STAR and head straight for runway.

**To Reproduce**

1. Build flightplan with STAR and approach in Navigraph and enter into MCDU, eg DISI1G to EGKK ILS26L
2. at MID (3rd waypoint of 6 of STAR) ND shows correct path but next waypoint becomes Runway 26L and autopilot follows that
3. change from NAV to heading mode and manually follow star works ok. Return to NAV mode and again flies direct to ILS26L. This is about the 3rd flight where ive seen this behaviour with different airports and approaches

**Expected behavior**

Autopilot should continue to follow routing for STAR as per MCDU and ND display.

**Actual behavior**

see above

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes this was working fine until a recent MS or FBWSIM update
Is this a problem in the vanilla unmodded game?
not tested. Have some 3rd party scenery and Navigraph AIRAC.

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2021-01-09 18:27
Duplicate of #939

**Closed by Benjozork** 2021-01-09 18:27 UTC
Labels: Bug
