### ISSUE TITLE
[BUG] Constraint's change doesn't update on the ND whereas CSTR button is on

### ISSUE THREAD

**Issue by doggydogg13** [flybywiresim/a32nx#3799] opened 2021-03-04 09:01 UTC
**Mod Version**

 Custom FBW

**Describe the bug**
 When I add or change altitude constraints on the F-PLN in MCDU, the new constraints are not displayed on the ND correctly (it's displays the previous constraints). I have to click again on the CSTR button to update it.

**To Reproduce**

1. Make a flight using simbrief intégration on the MCDU.
2. During the descent add or change altitude constraint on the F-PLN page of the MCDU
3. Then the new added constraints should not be displayed correctly on the ND.
4. Deactivate CSTR button and activate it again.
5. Now the correct constraints should be displayed.

**Expected behavior**
 If you change constraints in the MCDU it should be updated automatically and displayed on the ND if CSTR button is on.

**Actual behavior**
 If you change constraints in the MCDU it's not updated automatically and displayed correctly on the ND (CSTR button is on).

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment] 2021-03-04 23:27
Duplicate of #1297

**Closed by MisterChocker** 2021-03-04 23:27 UTC
Labels: Bug
