### ISSUE TITLE
Plane doesnt turn

### ISSUE THREAD

**Issue by Askiz** [flybywiresim/a32nx#5830] opened 2021-09-17 01:26 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-09-13T21:13:14+00:00",
  "ref": "master",
  "sha": "6dc2a169d5b856401327707f033191e7e62c82e0",
  "actor": "beheh",
  "event_name": "manual"
}
```

### Describe the bug

So, plane is not turning to the right and left :c
Whtm i'm trying to turn, nothing happens.
This is trouble of a32nx, because when i'm flying on default a320n with same settings, it turns

### Expected behavior

I've wanted to fly normally and turn the plane, but it doesn't want this

### Steps to reproduce

1. Reinstalled a32nx
2. Checked my settings 

### References (optional)

-

### Additional info (optional)

It was working before some patch

### Discord Username (optional)

dwarf#4874

**Comment by jetdirt** [comment] 2021-09-18 05:48
Also experiencing this bug. Stock Neo is fine.

**Comment by sidnov** [comment] 2021-09-18 06:53
Update to the latest development version, perform a clean install, make sure tug is disconnected when trying to turn

**Comment by aguther** [comment] 2021-09-18 20:18
Using keyboard is currently not working due to a confirmed bug in the SDK, see also here:
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/autopilot-fbw/

**Comment by jetdirt** [comment] 2021-09-19 01:34
> Using keyboard is currently not working due to a confirmed bug in the SDK, see also here:
> https://docs.flybywiresim.com/fbw-a32nx/feature-guides/autopilot-fbw/

I really appreciate the further information, thank you so much.

**Comment by aguther** [comment] 2021-09-19 21:34
Fingers crossed the bug gets fixed in the next sim update or the one after, then we can resolve this issue, too.

**Comment by 2hwk** [comment] 2021-09-21 14:53
Duplicate of https://github.com/flybywiresim/a32nx/issues/4694 closing

**Closed by 2hwk** 2021-09-21 14:53 UTC
Labels: Bug, Asobo Bug

**Comment by nolanblew** [comment] 2021-09-21 23:02
Having this issue only on ground with steering. Ailerons work fine as well as the rudder, but plane cannot turn at all when on the ground. Have the latest version of development branch.
