### ISSUE TITLE
.PLN File

### ISSUE THREAD

**Issue by LievreAI** [flybywiresim/a32nx#5296] opened 2021-07-11 02:06 UTC
### Aircraft Version

Stable

### Build info

```json
{
"built": "2021-05-05T23:03:06+00:00",
"ref": "0.6.1",
"sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
"actor": "Benjozork",
"event_name": "manual"
}
```

### Describe the bug

cannot import flight plan generated for msfs2020 via littlenavmap 
the fmc not applied the plan

### Expected behavior

i need the fmc read the flight pln file to get the flight plan under the F.PLN section on the flight computer

### Steps to reproduce

load the pln from the menu and nothing work , i dont know how i can load from the aircraft himself.

### Additional info (optional)

from some reason i cant access the flybywire server if i right i get kicked from the server since i used a pirate version
but now i have a orignial steam version hope i can access the server soon or later 

### Discord Username (optional)

Katrin#7037

**Comment by LievreAI** [comment] 2021-07-11 16:52
i try lot of diffrent way the plan not even loading
i using pln format what i am doing wrong?

**Comment by sidnov** [comment] 2022-03-08 09:57
Duplicate of #4327

**Closed by sidnov** 2022-03-08 09:57 UTC
Labels: Bug
