### ISSUE TITLE
[BUG] Aircraft does not flare at auto landing, nose in deep dive instead of flaring

### ISSUE THREAD

**Issue by Pilot747-hub** [flybywiresim/a32nx#1826] opened 2020-11-09 11:57 UTC
**Mod Version**
- Master as well as
- Up-to-date development version

**Describe the bug**
At auto landing, no matter at which airport, wind and weather, aircraft does not flare anymore and bounces on runway. Short before touch down, aircrafts nose going deep down. In MCDU in PERF all data is set given by ATC and ATIS. Landing checklist "all green", correct QNH set, PFD says "LAND" and CAT III. Speed selected as provided by PERF.  

**To Reproduce**

1. Set up flight plan
2. Fly approach with autopilot engaged
3. Set up PERF with by ATIS and ATC given Data
4. At approach engage LOC
5. After LOC Star, engage APPR
6. Land
7. Short before toch down nose is going deep down

**Expected behavior**
Flare before final touch down

**Actual behavior**
Deep dive of nose instead of flaring

Was this working before/when did the issue start occurring?
Yes, worked like charm before.

Is this a problem in the vanilla unmodded game?
N/A

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment] 2020-11-09 12:25
Duplicate of #1769

**Closed** 2020-11-09 12:25 UTC
Labels: Bug
