### ISSUE TITLE
Fonts and displays blurry

### ISSUE THREAD

**Issue by dg1234567** [flybywiresim/a32nx#7508] opened 2022-09-25 01:32 UTC
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-09-24T15:23:59+00:00",
    "ref": "refs/heads/master",
    "sha": "eedb3cb6496ef74e4d9e2f4ed8d5e5bf32bf582c",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:eedb3cb6"
}
```

### Describe the bug

Blurry displays and fonts for the words on displays even on 100 render scaling

### Expected behavior

Not blurry

### Steps to reproduce

Spawn anywhere
Look at all screens including flypad

**Comment by tracernz** [comment] 2022-09-25 01:57
Don't use DLSS until nvidia releases a suitable driver to disable it for the displays.

**Comment by dg1234567** [comment] 2022-09-25 19:14
dont use dlss

**Comment by tyler58546** [comment] 2022-09-28 04:49
Duplicate of #7448

**Closed by tyler58546** 2022-09-28 04:49 UTC
Labels: Bug
