### ISSUE TITLE
MCDU Resets itself mid flight after using DIR function.

### ISSUE THREAD

**Issue by MercuryDerpury** [flybywiresim/a32nx#2292] opened 2020-12-08 21:35 UTC
**Mod Version**

Dev version..

"built": "2020-12-07T19:12:22+00:00",
  "ref": "",
  "sha": "",
  "actor": "Connor T <33789660+Sequal32@users.noreply.github.com>",
  "event_name": "manual"

**Describe the bug**

When using Dir to feature on MCDU the FPLN page and INIT page was reset.

**To Reproduce**

1. Took off on flight from EGPH TO LPPT
2. When arriving at STAR XAMAX8A used DIR feature to fly directly to waypoint PT405.
3. After using DIR function the FPLN page went blank with none of the waypoints showing up (including PT405) or the arrival airport.
4. INIT page was also now blank and didn't have from/to information anymore and when trying to reinsert this mid flight the simulator crashed. 

**Expected behavior**

The aircraft to fly direct to the waypoint specified which was on my flight plan and continue with rest of route.

**Actual behavior**

When using the DIR function to an already plotted waypoint the FPLN emptied itself completely of all information and when trying to reinsert INIT information the simulator instantly crashed. 

**References**

**Additional context**

I have used the feature before without this happening but I have never seen the FPLN page empty itself out mid flight before.-

Last used the DIR feature since the 1st December and it worked fine but when trying tonight at 2030 zulu approx. the FPLN page cleared and game crashed.

Is this a problem in the vanilla unmodded game? Unsure.

Discord username (if different from GitHub): i420 Stoner#8854

**Comment by MisterChocker** [comment] 2021-04-16 17:14
Duplicate of #1798

**Closed by MisterChocker** 2021-04-16 17:14 UTC
Labels: Bug, MCDU
