### ISSUE TITLE
Cabin

### ISSUE THREAD

**Issue by Oliverski001** [flybywiresim/a32nx#4741] opened 2021-05-07 16:52 UTC
### Aircraft Version

Development

### Description

I think it would be nice to be able to go into the back of the aircraft and open the doors from the cabin. Similar to the airliners in xplane 11

### Discord Username (optional)

Oliverski001#1816

**Comment by Benjozork** [comment] 2021-05-07 16:53
Duplicate of #2577

**Closed by Benjozork** 2021-05-07 16:53 UTC
Labels: Enhancement
