### ISSUE TITLE
[BUG] After input of SID a blank screen with UNTITLED

### ISSUE THREAD

**Issue by petepawn64** [flybywiresim/a32nx#2099] opened 2020-11-25 14:54 UTC
**Mod Version**
 Master latest

Installer

**Describe the bug**

In LSZH after inserting DEP RWY 16 DEGE2R a blank screen with text UNTITLED and nothing I can do afterwards

**To Reproduce**

1. FMGC FLTPLAN -> DEP rwy 16 DEGE2R INSERT
2.
3.

**Expected behavior**

The SID to have been inserted

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?yes

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment] 2020-11-25 15:09
Duplicate of #1533. Can you try the solutions outlined there and report back on that thread ?

**Closed by Benjozork** 2020-11-25 15:09 UTC
Labels: Bug
