### ISSUE TITLE
VOR needles do not show on nd after sim update 1.15.8.0 with latest dev build.

### ISSUE THREAD

**Issue by MrAdskiy** [flybywiresim/a32nx#4474] opened 2021-04-17 23:49 UTC
**Mod Version**

  "built": "2021-04-16T21:01:28+00:00",
  "ref": "master",
  "sha": "b19333584e36344376068945b3604b4a746f9543",
  "actor": "myselfaaryan",
  "event_name": "manual"

**Describe the bug**
VOR needles do not show on nd after sim update 1.15.8.0 with latest dev build. 

**To Reproduce**

1. Start sim
2. Tune VOR freq
3. Check VOR needles on ND

https://pix.my/Yc5XMp
https://pix.my/jQePex

Was this working before/when did the issue start occurring?
yes, do not work after update 1.15.8.0

Is this a problem in the vanilla unmodded game?
yes

Discord username (if different from GitHub): xtasy#8449

**Comment by tracernz** [comment] 2021-04-18 06:23
Looks like you have a DME only station tuned? VOR-DME stations are working fine for me.

**Comment by CptBayer** [comment] 2021-04-20 22:17
for me too ....

**Comment by MisterChocker** [comment] 2021-05-15 16:48
Closing since working as intended

**Closed by MisterChocker** 2021-05-15 16:48 UTC
Labels: Bug, Waiting For Response
