### ISSUE TITLE
Fuel used not synchronized with simulation rate

### ISSUE THREAD

**Issue by ohnoitsBlarry** [flybywiresim/a32nx#4938] opened 2021-05-28 14:35 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-28T11:09:14+00:00",
  "ref": "master",
  "sha": "aea711f8547eed2669c774481200330670eb3085",
  "actor": "tracernz",
  "event_name": "manual"
}
```

### Describe the bug

Fuel flow, and subsequently fuel used, does not take into account the current rate of time acceleration / simulation rate at which the sim is running. This effectively increases the range by a factor proportional to the percentage of the flight flown using a higher-than-standard simulation rate, and makes fuel planning unreliable especially for long flights whenever a higher simulation rate is used to accelerate the cruise phase.

### Expected behavior

Fuel usage should correctly take into account the simulation rate at which the simulation is running. 

### Steps to reproduce

1. Start up at any airport, climb and maintain any altitude, establish constant level flight with a constant fuel flow.
2. Prepare a stop clock.
3. Switch ECAM 2 to either CRUISE or FUEL page. Monitor any engine's 'fuel used' displayed.
4. Once fuel used increases by 10 kg, start the stop clock.
5. Once fuel used increases by 10 kg again, stop the stop clock. Take note of time passed.
6. Repeat steps 4 - 6 with simulation rate increased to X 2 or X 4. Time passed is pretty much the same as in an unaccelerated setting.

**Comment by aguther** [comment] 2021-05-28 17:26
Please be aware that also from AP perspective time compression is not supported. It may work, but it's not supported right now:
https://docs.flybywiresim.com/start/autopilot-fbw/

**Comment by Emerson2021M** [comment] 2021-05-28 19:16
I tbm already noticed this some time, long flight the fuel reaches the limit I think that it is not possible to switch to the airport alternated !!

**Comment by ohnoitsBlarry** [comment] 2021-05-29 09:02
> Please be aware that also from AP perspective time compression is not supported. It may work, but it's not supported right now:
> https://docs.flybywiresim.com/start/autopilot-fbw/

It fluctuates a bit from build to build. Before 0.6.1, sim rate 2 was the highest factor of time acceleration that worked on my machine without inducing pitch and yaw oscillations. Now, sim rate 4 works mostly stable, as long as you use it on level flight and slow down to real time for turns. Takes a bit of fiddling around, but it's perfectly serviceable within its limits. Just as a heads up.

**Comment by aguther** [comment] 2021-05-29 14:12
How good it works is also frame rate dependent. If you put sim rate on 2x it's for AP (also for the built-in) like cut in half the frame rate. 4x is a quarter, etc.

So the more FPS you have the better...

**Comment by ajs117** [comment] 2021-06-07 12:30
The working as intended label is certainly not merited here, it is a default sim behaviour and should be supported to the best of the addon's ability.

**Comment by tracernz** [comment] 2021-06-07 18:16
> The working as intended label is certainly not merited here, it is a default sim behaviour and should be supported to the best of the addon's ability.

It can't be fixed with reasonable effort unless the sim frame-rate drastically increases (calculations through various systems require small enough time steps to remain stable).

**Comment by aguther** [comment] 2021-06-07 18:44
I mean at least the fuel flow should be fixable, but it's IMHO not a priority. I think it's more important to get a realistic start and shutdown procedure for the engines.

**Closed** 2021-10-11 12:51 UTC
Labels: Bug
