### ISSUE TITLE
[BUG] AIRCRAFT IS TURNING DIRECT TO THE RWY AFTER "DECEL" POINT

### ISSUE THREAD

**Issue by komolysamu** [flybywiresim/a32nx#3613] opened 2021-02-18 21:14 UTC
**Mod Version**

 Up to date stable version of the A32NX according to the installer.

**Describe the bug**

Plane flies direct to RWY after DECEL point. 

**To Reproduce**

1. Selected VS: -1000
2. Speed 250kt (MANAGED, under FL100)
3. FMC: Dest. data inserted, ARRIVAL: FLTPLN/LHBP/APP:ILS13R/STAR:ANEX2T/TRANS: ECKAM. Waypoints checked, correct. 
4. DECEL point activates approach mode automaticly.
5. Aircraft goes direct to RWY
6. Insert direct to BP744

**Expected behavior**

After decel point the aircraft slowing down and follow the flight plan, what is already inserted.

**Actual behavior**

I flew from UUEE(Moscau) to LHBP(Budapest). I was right on the "ANEX2T" STAR and I expected to land on RWY 13R with ILS CAT III. As I reached the "DECEL" point and the aircraft was slowing down to the approach speed, the plane started a right turn direct to RW13R. I tried to fix it, and go direct to my next waypoint, but when I inserted the direct in the FMC, the full flight plan has been deleted and simulator crashed. 

**References**

**Additional context**

Screenshot help: Orange: RWY 13R/31L, Blue: Flown route, Yellow "D": DECEL point, Red: wrong heading
<img width="559" alt="Képernyőkép 2021-02-18 220719" src="https://user-images.githubusercontent.com/79282693/108421997-45378900-7236-11eb-82c9-f558ccf7d122.png">
Thanks for the help, keep ut the good work! ;)

Discord username (if different from GitHub):
komolysamu#7384

**Comment by Benjozork** [comment] 2021-02-18 21:29
Duplicate of #939.

**Closed by Benjozork** 2021-02-18 21:29 UTC
Labels: Bug
