### ISSUE TITLE
A32NX Suggestion

### ISSUE THREAD

**Issue by StormTuber** [flybywiresim/a32nx#4450] opened 2021-04-15 21:03 UTC
**This feature is a suggestion**

**Fully modelled and detailed cabin interior**

**A320**

**Now that the A32NX is a separate aircraft from the A320, a fully modelled cabin interior would be a cool and great addition to the mod**

Discord username: Storm Tuber#8549

**Comment by Benjozork** [comment] 2021-04-15 21:04
Duplicate of #2577

**Closed by Benjozork** 2021-04-15 21:04 UTC
Labels: Enhancement
