### ISSUE TITLE
[BUG] UNSTABLE IN LEVEL FLIGHT: SLOWLY  BANKING RIGHT AND LEFT

### ISSUE THREAD

**Issue by Marenostrum66** [flybywiresim/a32nx#2097] opened 2020-11-25 10:26 UTC
**Mod Version**
{ "built": "2020-11-24T08:08:38+00:00", "ref": "refs/heads/master", "sha": "b570de8c53cd5b52a21c81f8120bfa57d8c53830", "actor": "wpine215", "event_name": "push" }

**Describe the bug**
during climb and level flight the aircraft is sligthly and slowly banking left and right afgter the MSFS2020 update 1.11.6.0

**To Reproduce**
1. just take off and mantain an heading either in HDG mode or NAV mode.
2. you'l notice that the aircraft is not stable. before the FS2020 update was perfect. 
3. same problem  with the previous master build: I updated and tried again..same issue.

**Expected behavior**
Stable flight not banking right/left

**Actual behavior**
Untable flight banking right/left. possibly due to FS2020 update that has changed something in the dynamic

**References**

**Additional context**

Was this working before/when did the issue start occurring?
No problem before he last FS2020 update

Is this a problem in the vanilla unmodded game?
do not know

**Comment by Seth-Dark** [comment] 2020-11-25 10:30
Same issue exactly after new update 1.11.60 and A32NX latest Dev Build

**Comment by Sheetso** [comment] 2020-11-25 11:20
Same issue here :/

**Comment by jf96g** [comment] 2020-11-25 14:04
Same issue! I recorded a video of the plane bankinng

**Comment by Benjozork** [comment] 2020-11-25 14:33
Please use the "thumbs up" reaction is your issue is the exact same.

**Comment by Benjozork** [comment] 2020-11-25 14:34
Duplicate of #2005.

**Closed by Benjozork** 2020-11-25 14:34 UTC
Labels: Bug
