### ISSUE TITLE
[BUG] AP buttons of TBM stop being interactive after installing 0.4.0 version of A320NX

### ISSUE THREAD

**Issue by flannk** [flybywiresim/a32nx#1364] opened 2020-10-15 11:57 UTC
**Mod Version**
Release 0.4.0

**Describe the bug**
0.3.1 worked good for me. After installing the 0.4.0 A320NX version, all the buttons of the autopilot panel in the TBM 930 stopped being clickable. After uninstalling A320NX, or reverting back to 0.3.1 they work again.

**To Reproduce**
1. Make sure A320NX 0.4.0 is installed correctly
2. Launch a flight with the TBM 930, does not matter whether it is with a cold and dark cockpit, or ready to go on a runway
3. Try to use the autopilot, or set altitude. The buttons are not clickable
4. Close down MSFS
5. Uninstall A320NX
6. Restart MSFS and fly with the TBM 930, now everything works again

**Expected behavior**
The buttons of the autopilot panel of the TBM 930 would still function with A320NX 0.4.0

**Actual behavior**
The buttons of the autopilot panel of the TBM 930 are not clickable with A320NX 0.4.0

Was this working before/when did the issue start occurring?
Yes, it works with 0.3.1

Is this a problem in the vanilla unmodded game?
No

**Comment by armankir** [comment] 2020-10-15 14:07
Did you turn on your AP on the overhead of the TBM?

**Comment by Benjozork** [comment] 2020-10-15 14:07
Cannot reproduce.

Can you make sure you reinstall A32NX 0.4.0 and reload a flight ? I have a feeling this might be caused by the unusable cockpit bug that can be fixed by resizing any pop-out window like ATC.

**Comment by joshbxd514** [comment] 2020-10-15 14:14
Hi,

I have tried to reproduce this bug however with no success.

I dont see this being a bug with the mod.

Thanks

Joshbxd515#4978

**Comment by Snapmatics** [comment] 2020-10-15 14:16
Can't reproduce, it works fine for me.

![image](https://user-images.githubusercontent.com/43104362/96141887-1fa61600-0f0a-11eb-8b17-89cd89bc7ec8.png)

**Comment by flannk** [comment] 2020-10-15 14:52
Can reproduce:
1) First completely delete the A320NX folder
2) Reinstall 0.4.0
3) TBM autopilot does not work, buttons are not clickable

Fix:
1) Install A320NX 0.3.1
2) Install A320NX 0.4.0 by overwriting A320NX folder
3) Now it works 👍

**Closed** 2020-10-15 15:43 UTC
Labels: Bug, Bug-A32NX, Critical Bug

**Comment by flannk** [comment] 2020-10-15 15:44
Closed since it is not an issue anymore when installing 0.4.0 on top of 0.3.1.

**Comment by santii90** [comment] 2020-10-15 21:38
Not sure if this should be closed. Not everyone is updating. This means that if a newcomer download the installer and do a fresh install is going to have this bug?

**Comment by flannk** [comment] 2020-10-15 22:23
If you can reproduce it that way, yes.

**Comment by Benjozork** [comment] 2020-10-16 02:37
@flannk do you use the TBM mod by any chance ?

**Comment by flannk** [comment] 2020-10-16 07:04
No.

 The only airplane mods I have are Salty B747 and the A320NX. I do have
some liveries installed, and some airports and sceneries.
