### ISSUE TITLE
[REQUEST] Isseus with the flight computer

### ISSUE THREAD

**Issue by ties1717** [flybywiresim/a32nx#2777] opened 2020-12-28 18:58 UTC
**Is your feature request related to a problem? Please describe.**

the a32nx mod is a great mod. but there are a few things that realy irritate me. 1) when i select direct to what should happen in real life is if we have for example the waytpiont "a-b-c-d" if i select direct to c than waytpionts a-b will be removed from the flightplan (only if i select abeams than they should stay in the flightplan but that is with the letter a and b in front of it witch stand for abeams) but what happens in the game is that all the waytpoints are still there and it does go direct to but the waypionts are not removed from the flightplan. 2) at certain airports the approach is totaly not correct and it is just a total mess and that is ok begous it is realy hard to keep up with the changes. but give us the option that we can change the waytpoints within the approach (witch you also can do in real life but you cant do it in the game)

**Describe the feature you'd like to see implemented**

1)i expect that when selecting direct to that all the waytpoint before the selected waytpoint get removed from the flightplan.
2) i expect that or we could change the waytpoints in the approach or the approaches are totaly correct

**References**

**Additional context**
 

Discord username (if different from GitHub): ties - 653402

**Comment by Benjozork** [comment] 2020-12-28 19:15
1. is a duplicate of #1438
2. is a duplicate of #1388

**Closed by Benjozork** 2020-12-28 19:15 UTC
Labels: Enhancement
