### ISSUE TITLE
[BUG] Dist on fmc stopped updating.

### ISSUE THREAD

**Issue by Silvaronn** [flybywiresim/a32nx#3409] opened 2021-02-08 02:30 UTC
![FlightSimulator_2021_02_07_23_18_10_189_LI](https://user-images.githubusercontent.com/78712238/107169284-45b16380-699c-11eb-886a-c9d9b0c3b63b.jpg)
![FlightSimulator_2021_02_07_23_18_10_189_LI](https://user-images.githubusercontent.com/78712238/107169359-6b3e6d00-699c-11eb-9bdc-a475ba1394b5.jpg)

**Mod Version**

A32nx experimental/custom fbw

**Describe the bug**

during the flight, the fmc dist is not counting down.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
it was working until yesterday / today

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment] 2021-02-08 02:50
Please follow the template and fill the given fields.

Both attached screenshots are identical.

Also

> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by FGrabi** [comment] 2021-02-08 17:47
{
  "built": "2021-02-08T12:40:30+00:00",
  "ref": "master",
  "sha": "0840a59eef33d190fe081ed41270e3d267bc2b9b",
  "actor": "wpine215",
  "event_name": "manual"
}
**Describe the Bug**
Have the same problem on the flight ESSD-EDDH with SimBrief route:
ESSD/32 DCT LEGPO M852 UMVUP DCT BOGMU BOGM1N EDDH/DH257.I05

The Total Dist to EDDH was frozen at 444nm and for the actual Waypoints shown on the FMGC the distance was extrem high (maybe the total distance or remaining distance of the M852 Airway. The Distance on the ND for the waypoint was show correctly. Reported this earlier in #3403 (with screenshots) and @pareil6 was involved. Maybe the same ISSUE that he worked on?

**Comment by pareil6** [comment] 2021-02-08 18:48
Sounds like a duplicate of #3379

**Comment by mixsiak** [comment] 2021-02-09 09:25
same problem..it vwas OK on stable version 0.5.2 and now on dev mode.. with fly_tablet..is distance freezed

**Comment by MisterChocker** [comment] 2021-02-09 12:20
Duplicate of #3379

**Closed by MisterChocker** 2021-02-09 12:20 UTC
Labels: Bug, Waiting For Response
