### ISSUE TITLE
[BUG] When Spawning on approach plane in takeoff phase

### ISSUE THREAD

**Issue by FlightSimmer7700** [flybywiresim/a32nx#1919] opened 2020-11-14 15:33 UTC
**Mod Version**

built: 2020-11-13T18:49:49+00:00
ref: refs/heads/master
sha: 72e7b0c830e17d7984b3aca2dd852cce8ca7662c
actor: Benjozork
event_name: push

**Describe the bug**

When spawning on approach the plane is on takeoff phase which can cause don't sink callout on approach and takeoff config warning a few feet before touch down. It has also caused ADIRS to be off when you spawn on approach

**To Reproduce**

1. Spawn on an approach 
2. On approach your ADIRS may be off
3. After a while there will be continuous don't sink callout for the whole approach.
4. when about to land there may be a takeoff config warning

**Expected behaviour**

Aircraft should be in approach phase when spawning on approach 

**Actual behaviour**

Aircraft is in takeoff phase 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Started occurring last night

Is this a problem in the vanilla unmodded game?
shouldn't be not entirely sure

Discord username (if different from GitHub):  FlightSimmer7700#3468

**Comment by beheh** [comment] 2020-11-14 22:07
Duplicate of #1430.

**Closed** 2020-11-14 23:24 UTC
Labels: Bug
