### ISSUE TITLE
[BUG] PFD causing graphics lag

### ISSUE THREAD

**Issue by kthejoker20** [flybywiresim/a32nx#2569] opened 2020-12-20 19:26 UTC
**Mod Version**

MASTER

**Describe the bug**

PFD and ND is causing major graphics performance slow down.

**To Reproduce**

1.  TURN up the brightness on the PFD and ND, you will see a low refresh rate and visual tearing
2.
3.

**Expected behavior**

Graphics should be smooth

**Actual behavior**

IT's causing a major graphics lag.  You have to shut off one of the PFD so the lag goes away

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Dont know
Is this a problem in the vanilla unmodded game?
nope

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-12-20 19:41
Duplicate of #1341

**Closed by Benjozork** 2020-12-20 19:41 UTC
Labels: Bug
