### ISSUE TITLE
If one engine is shutdown after landing the throttles are cross mixed

### ISSUE THREAD

**Issue by Dimexi78** [flybywiresim/a32nx#3669] opened 2021-02-21 17:30 UTC
**Mod Version**

Mod version 0.52 development and 0.53 also

**Describe the bug**

I landed the plane and started the AOU. After APU start I shut down ENG1. When i apply throttle to ENG2 from my controller the ENG2 does not rev up. But if I move the throttle 1 to rev up ENG1,  ENG2 revs up. So it seems that the inputs go to right place, but the engines are mixed. See the images.

**To Reproduce**

1. Takeoff
2. make ILS approach and landing
3. shut down ENG 1
4. taxi after ENG shutdown
5. Controls are now reversed. Throttle 1 is controlling ENG 2 and vice versa.

**Expected behavior**

After ENG shutdown the throttles control correct engine.

**Actual behavior**

Engine controls are swapped after ILS landing and ENG shutdown.

**References**

![Capture](https://user-images.githubusercontent.com/79414133/108633096-1100da00-747b-11eb-95d8-88bec53c6ef2.JPG)
![Capture2](https://user-images.githubusercontent.com/79414133/108633098-14946100-747b-11eb-91e9-d19ec0ae5e63.JPG)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2021-02-21 17:32
Duplicate of #1970

**Closed by Benjozork** 2021-02-21 17:32 UTC
Labels: Bug

**Comment by Dimexi78** [comment] 2021-02-21 17:52
Hi,

I checked the other bug, in my opinion this is not duplicate. The throttles work as they should with one engine shutted down prior taking off. Problems occur after landing and engine is shutted down.

Br,

Timo Pekkanen

**Comment by Benjozork** [comment] 2021-02-21 17:54
This is caused by the same issue.

**Comment by hotshotp** [comment] 2021-02-21 19:04
> Hi, I checked the other bug, in my opinion this is not duplicate. The throttles work as they should with one engine shutted down prior taking off. Problems occur after landing and engine is shutted down. Br, Timo Pekkanen
> […](#)
> Sent from my iPhone
> On 21. Feb 2021, at 19.33, Benjamin Dupont ***@***.***> wrote: ﻿ Closed #3669. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

yes, your problem occurs due to issue #1970

**Comment by flyingpaul1980** [comment] 2021-03-28 16:50
I also realized that after touchdown, thrust lever 1 will control both engines while thrust lever 2 does not have any effect on spooling the engines up. Manually disconnecting autothrottle solves this, but i guess the airbus should disconnect autothrottle by itself after touching down
