### ISSUE TITLE
fuel flow issue

### ISSUE THREAD

**Issue by youngryan7** [flybywiresim/a32nx#4557] opened 2021-04-24 13:05 UTC
**Aircraft Version**

```json
{
  "built": "2021-04-23T22:37:56+00:00",
  "ref": "experimental",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
}

```

**Describe the bug**

fuel flow issue. departed with 9064kg of fuel for 4 and half hour flight. at position ROTSI simbrief expects to have 2.7 tons - only 700kg remaining. 

**To Reproduce**

1. fuel up aircraft
2. check fuel en route
3.

**Expected behavior**

fuel not to burn so quickly

**Actual behavior**

fuel burn high

**References**

![2021-04-24](https://user-images.githubusercontent.com/59422760/115959797-e4625080-a505-11eb-99f8-a764922f289f.png)

**Additional context**

Was this working before/when did the issue start occurring?
was working before latest experimental update

Is this a problem in the vanilla unmodded game? no

Discord username (if different from GitHub): ryanyoung26 discord

**Comment by MisterChocker** [comment] 2021-04-24 14:33
This is what simbrief gave me for a similar flight with similar headwind (the one from your screenshot)

It calculated the trip fuel to be 9428kg for 04h19m flight time.
Also contingency fuel (15min to be 544kg) and a final reserve of 948kg.
Now adding taxi fuel, we already have a total of 11.120kg and we are still missing the alternate and possibly extra fuel.

Altho fuel burn varies, I already have a higher TO/FUEL weight then you.

[Full OFP](https://www.simbrief.com/ofp/flightplans/EDDMLPMA_PDF_1619274017.pdf)

```
D-AIIA    24APR2021    EDDM-LPMA   A20N DAIIA   RELEASE 1420 24APR21
OFP 2                MUNICH-MADEIRA
                         WX PROG 2415 2418 2421   OBS 2406 2406 2406
	
  ATC C/S   DAIIA        EDDM/MUC   LPMA/FNC      CRZ SYS      CI 15
24APR2021   DAIIA        1450/1510  1929/1937     GND DIST      1752
A320-251N / LEAP1A                  STA  1940     AIR DIST      1869
                         CTOT:....                G/C DIST      1592
                                                  AVG WIND   246/023
MAXIMUM    TOW  79000  LAW  67400  ZFW  64300     AVG W/C       M027
ESTIMATED  TOW  61160  LAW  51732  ZFW  48300     AVG ISA       P003
                                                  AVG FF KGS/HR 2176
                                                  FUEL BIAS    P00.0
ALTN GCXO                                         TKOF ALTN  .......
FL STEPS EDDM/0380/TOLVU/0370
--------------------------------------------------------------------
DISP RMKS   NIL

--------------------------------------------------------------------
         PLANNED FUEL
---------------------------------
FUEL           ARPT   FUEL   TIME
---------------------------------
TRIP            FNC   9428   0419
CONT 15 MIN            544   0015
ALTN            TFN   1940   0047
FINRES                 948   0030
---------------------------------
MINIMUM T/OFF FUEL   12860   0552
---------------------------------
EXTRA                    0   0000
---------------------------------
T/OFF FUEL           12860   0552
TAXI            MUC    200   0020
---------------------------------
BLOCK FUEL      MUC  13060
PIC EXTRA            .....
TOTAL FUEL           .....
REASON FOR PIC EXTRA ............
```

**Comment by Taz5150** [comment] 2021-04-24 14:59
Just checked the fadec code uploaded last night and the new fuel consumption model is there.

Would it be possible to have a look at the FDR and/ or your SimBrief plan??

**Comment by youngryan7** [comment] 2021-04-24 18:26
this is my aircraft profile - possibly simbrief issue but I've never had an issue before that's all 

https://www.simbrief.com/system/dispatch.php?sharefleet=eyJ0cyI6IjE2MTU1OTc1NTIxNjIiLCJiYXNldHlwZSI6IkEzMjAiLCJjb21tZW50cyI6IkJBIE5FTyIsImljYW8iOiJBMjBOIiwibmFtZSI6IkEzMjBORU8iLCJlbmdpbmVzIjoiTEVBUC0xQTI2IiwicmVnIjoiRy1UVE5EIiwiZmluIjoiODMwOCIsInNlbGNhbCI6IkNGTFAiLCJoZXhjb2RlIjoiNDA3NTM0IiwiY2F0IjoiTSIsInBlciI6IkMiLCJlcXVpcCI6IlNERTNGR0hJUldZIiwidHJhbnNwb25kZXIiOiJMQjEiLCJwYm4iOiJBMUIxQzFEMU8xUzEiLCJleHRyYXJtayI6IiIsIm1heHBheCI6IjE3MCIsIndndHVuaXRzIjoiS0dTIiwib2V3IjoiNDEwMDAiLCJtemZ3IjoiNjI1MDAiLCJtdG93IjoiNzkwMDAiLCJtbHciOiI2NjAwMCIsIm1heGZ1ZWwiOiIyMTI3MyIsInBheHdndCI6IjEwNCIsImRlZmF1bHRjaSI6IjIwIiwiZnVlbGZhY3RvciI6Ik0yNSIsImNydWlzZW9mZnNldCI6IlAwMDAwIn0-

**Comment by youngryan7** [comment] 2021-04-24 18:27
[LCLKEGLL_PDF_1619254816.pdf](https://github.com/flybywiresim/a32nx/files/6370347/LCLKEGLL_PDF_1619254816.pdf)

**Comment by Taz5150** [comment] 2021-04-24 21:16
Looking at the dispatched OFP, there are two things I feel are a little low:

- One is block fuel (9,000 Kg.) for a 4.5 hour flight. That same flight for a A320 CEO has a block fuel of 14,000 Kg.

- The other one is average fuel flow .... 1555  Kg/h  means around 750 Kg/h per engine, which is VERY low IMO. Take a look at your picture: at Cruise altitude and an N1 of 79%, you are already in the 1000 Kg/h regime (which is about right).

At ROTSI, you estimated flying time should be around 3:40 hours. Looking at your Fuel Consumed already (8,290 Kg) your fuel flow average should have been around 2,261 Kg/h (which sounds more reasonable). Also, from ROTSI to EGLL you have another good hour to go which means another 2,261 Kg of fuel to burn. So your total trip fuel would be around 10,551 Kg which looks more reasonable as well (without any contingency  fuel).

I think something went wrong during planning, I'm afraid :)

In any case, thank you for the feedback!

**Comment by youngryan7** [comment] 2021-04-24 21:59
Hi taz

yeah thanks for your reply. ive just done couple of flight to Nice and back and no problems at all. I think simbrief underestimated the headwind en route - 

thanks for looking into it 

ryan

**Comment by MisterChocker** [comment] 2021-04-24 22:01
Closing since issue resolved.

**Closed by MisterChocker** 2021-04-24 22:01 UTC
Labels: Bug, Waiting For Response

**Comment by MisterChocker** [comment] 2021-04-24 22:03
BTW your fuel factor is set to M (minus) 25. Thats probably the root cause.

**Comment by youngryan7** [comment] 2021-04-24 22:04
can you advise what is should be?

**Comment by MisterChocker** [comment] 2021-04-24 22:09
default is 0.

**Comment by youngryan7** [comment] 2021-04-24 22:10
thanks a lot.  👍 amazing as always
