### ISSUE TITLE
Removing waypoint from MCDU by clicking the waypoint below it

### ISSUE THREAD

**Issue by jwsteens** [flybywiresim/a32nx#4419] opened 2021-04-12 16:40 UTC
**Mod Version**

```json
{
  "creator": "FlyByWire Simulations",
  "release_notes": {
    "neutral": {
      "LastUpdate": "VERSION 0.6.0\\nInitial Release onto Marketplace",
      "OlderHistory": ""
    }
  },
  "title": "A32NX",
  "dependencies": [
    {
      "package_version": "0.1.58",
      "name": "asobo-aircraft-a320-neo"
    },
    {
      "package_version": "0.1.52",
      "name": "asobo-vcockpits-instruments-a320-neo"
    },
    {
      "package_version": "0.1.53",
      "name": "asobo-vcockpits-instruments-airliners"
    },
    {
      "package_version": "0.1.66",
      "name": "fs-base-aircraft-common"
    }
  ],
  "content_type": "AIRCRAFT",
  "minimum_game_version": "1.9.5",
  "manufacturer": "Airbus",
  "package_version": "0.6.0",
  "total_package_size": "00000000001586470681"
}
```

**Describe the bug**

If you want to remove a waypoint from the F-PLN page, you have to press CLR and the waypoint below it.

**To Reproduce**

1. Load in a flight plan
2. Remove a waypoint
3. See how the waypoint above it gets removed, rather the one you selected

**Expected behavior**

You expect the selected waypoint to be deleted

**Actual behavior**

The waypoint above the selected waypoint gets deleted

**References**

I want to delete BENOT waypoint, I press CLR then BENOT
![image](https://user-images.githubusercontent.com/74742373/114430009-3f1eb280-9bbe-11eb-912c-8703a4db0bd6.png)
TORPA gets deleted.
![image](https://user-images.githubusercontent.com/74742373/114430029-480f8400-9bbe-11eb-8900-f78205b8ce04.png)

**Additional context**

Was this working before/when did the issue start occurring?
This seemed to work a few versions ago.

Is this a problem in the vanilla unmodded game?
Using A32NX with a livery

Discord username (if different from GitHub):
@willem#5819

**Comment by Flyingtrader06** [comment] 2021-04-14 17:46
Additionally, it is somehow impossible to delete any waypoint which is part of a STAR.

**Comment by big-bacchus** [comment] 2021-04-14 19:15
Same problem while inserting waypoints, new waypoint is added before not after selected waypoint

**Comment by danpowel** [comment] 2021-04-26 22:27
KPVD is a mess when all i want to do in the star is the ils for given rnwy i get a "via" pvd then takes me out to the first waypoint for the ils. Can't get rid of the pvd in mcdu...its locked in the ils approach. so when i get near KPVD i do a direct to the 1st waypoint of the ils approach....shouldn't have to do this

**Comment by 2hwk** [comment] 2021-06-06 12:45
Also noticed this, posting to remind myself to investigate this over the next week

**Comment by 2hwk** [comment] 2021-06-07 02:25
I've had this happen on occasion but cannot reproduce, if you happen to notice a flight path that reliable exhibits this behavior comment on this issue.

**Comment by 2hwk** [comment] 2021-11-21 07:12
Fixed by 4953 closing ☑️

**Closed by 2hwk** 2021-11-21 07:12 UTC
Labels: Bug, MCDU, FPM, fixed in cFPM
