### ISSUE TITLE
[BUG]Test Takeoff Config. button incorrectly sates there is an issue with my flaps

### ISSUE THREAD

**Issue by ErickSharp** [flybywiresim/a32nx#1520] opened 2020-10-24 08:42 UTC
**Mod Version**

v0.4.0

**Describe the bug**

When pressing the Takeoff Config. button, it will, regardless of your flap setting, give you an ECAM memo and master warning saying that your flaps are incorrect for takeoff. 

**To Reproduce**

1. Use any appropriate flap setting for takeoff such as 1, 2, or 3.
2. Press Test Takeoff Config. button.
3.

**Expected behavior**

It should only alert the pilot if the flap setting is inappropriate for takeoff.

**Actual behavior**

Alerts the pilot that they are using an inappropriate flap setting, regardless if the flap setting is correct or not.

**References**

https://safetyfirst.airbus.com/takeoff-surveillance-and-monitoring-functions/

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Rameyuk** [comment] 2020-10-24 15:26
I never had this issue. Did you enter the flaps setting in the Take Off PERF page? I enter it as a value of 1, then set my flaps to 1, and pressing the T.O Config button changes the checklist to Normal in green colour without the warning.

**Comment by bluecew** [comment] 2020-10-24 17:35
You have to set your take-off flaps in the PERF page of the MCDU. This way the computers recognize your selected flap setting and won't alert you.

**Comment by ErickSharp** [comment] 2020-10-25 03:03
For context, I did input my flaps into the MCDU, but after restarting the sim, this current flight didn't give me a warning.

**Comment by ErickSharp** [comment] 2020-10-25 04:21
I will say that if you do everything else on the checklist like get autobrake to MAX and spoilers armed that it won't give you the bug.

**Comment by hotshotp** [comment] 2020-10-25 14:43
I cannot reproduce this issue

**Comment by St54Kevin** [comment] 2020-10-27 13:00
I also never had his issue

**Comment by hotshotp** [comment] 2020-10-27 14:11
Closing as issue cannot be reproduced

**Closed by hotshotp** 2020-10-27 14:11 UTC
Labels: Bug
