### ISSUE TITLE
[BUG] Constraints not showing on the ND

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#750] opened 2020-09-19 12:25 UTC
**Mod Version**

Master

**Describe the bug**

Constraints are not shown on the ND. I can select CSTR on the EFIS, but with MSFS 1.8.3 and the master versions no additional information is displayed at the waypoints. Rest of the modes (WPT, VO, NDB, ARPT) are working though.

**To Reproduce**

1. Plan an IFR flight with waypoints
2. Start up the Airbus and try out the various EFIS options
3. Notice constraints not showing

**Expected behavior**

Pressing the CSTR button should show alt information next to the waypoints

**Actual behavior**

Pressing the CSTR does nothing on the ND.

**References**

**Additional context**

Don't know if the issue is caused by Asobo (likely it is) or the A32nx mod.

Discord username (if different from GitHub):

**Comment by ErikNL80** [comment] 2020-09-19 18:20
I did some additional testing and it seems that the EFIS buttons do not always respond to the ND. Sometimes it help to zoom in or out using the range buttons and then click one of the EFIS buttons. Anyone can confirm? Refresh rate is set to medium.

**Comment by ferics** [comment] 2020-09-20 02:43
Did a flight from RJTT to RKSI and none constraint flight level were shown on the ND, so I can confirm on this.

**Comment by Venorcis** [comment] 2020-09-20 10:53
I always see the contraints without issue, so not sure what would be causing this?

**Comment by ErikNL80** [comment] 2020-09-20 18:54
Did a new flight today, same issue. Not only with the constraints, but with all EFIS modes. Only works when you refresh the ND by changing the range...

**Comment by wpine215** [comment] 2020-11-14 21:42
@ErikNL80 Is this issue still active with the latest updates?

**Comment by Mickg56** [comment] 2020-12-25 03:36
It is with mine...constraints not showing at all and ND freezes when CSRTS is pressed..all other buttons work

**Comment by MisterChocker** [comment] 2020-12-31 07:24
constraints now visible, but not updating, closing since we have another issue for tracking

**Closed by MisterChocker** 2020-12-31 07:24 UTC
Labels: Bug, ND (Navigation Display)
