### ISSUE TITLE
[BUG] Flare Issue

### ISSUE THREAD

**Issue by elcareflen** [flybywiresim/a32nx#2093] opened 2020-11-25 00:15 UTC
**Mod Version**

Dev Version

**Describe the bug**

—I used Google Translate—
Hi everyone.
There is a problem in the Flare. When I perform the Flare, the plane starts to rise and this has not happened before. I have tested an old version of Flybywire and have had no problems. I have also tried without mod and have not had problems either. Apparently the plane does not lose power from the engines while the Thrust is in Idle.

This happens at 120, 130, 140 Knots

**To Reproduce**

1. During the landing, specifically in Flare
2. The problem is probably related to the acceleration of the plane in idle while on the ground, perhaps this affected the flare
3.

**Expected behavior**

That the plane does not rise at such a low speed

**Actual behavior**

**References**

Bug - Yesterday
2020/11/23
https://youtu.be/UIQjLn_TKBA
————————
Old version, a couple of weeks ago
Here it works fine
https://youtu.be/Nk6oieH8oEQ
————————
Today, without mod
Here it works fine
https://youtu.be/EXAPLzChBQ8

**Additional context**

This happens at 120, 130, 140 Knots

Was this working before/when did the issue start occurring?
In the latest development versions

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by ntlgr** [comment] 2020-11-25 00:20
Duplicate of #2027

**Comment by elcareflen** [comment] 2020-11-25 00:23
> Duplicate of #2027

Ooh, sorry..
But I hope the videos serve to describe the problem.

**Comment by Benjozork** [comment] 2020-11-25 00:24
Thanks for the video.

**Closed** 2020-11-25 00:24 UTC
Labels: Bug

**Comment by elcareflen** [comment] 2020-11-25 00:25
> Thanks for the video.
Ok, thanks to you. They do a great job!
