### ISSUE TITLE
[BUG] BIG PERFORMANCE ISSUE LONG FLIGHT PLAN.

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2849] opened 2021-01-03 02:01 UTC
**Mod Version**
Latest branch

**Describe the bug**
The performance drops drastically if a long flight plan is loaded in the MCDU , manual or by simbrief. It does not happen with shorts flights 

**To Reproduce**

 1.Load this FLIGHT PLAN to the aircraft From VCCT TO RJTT.

 2.Flight plan :  ESPAP P762 DWI L877 MIGAR L524 BKK W1 KRT B460 SAV A202 SAMAS G221 BIGRO R200 GLN V17 UBDOB V18 
 XEBUL G471 PLT A599 TOL W508 WY V71 CJ W555 KAKIS A599 PUD W11 PINOT W115 MATNU G455 LAMEN A593 FUE V40 
 WOODY Y40 OOITA Y23 BRIGE Y233 UTIBO Y108 KAIHO DARKS

3. Its impossible to fly....

**Expected behavior**
Perform as good as a short FLIGHT PLAN 

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I dont think so

Is this a problem in the vanilla unmodded game?
Not sure 

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2021-01-03 02:07
Duplicate of #2708

**Closed** 2021-01-03 02:07 UTC
Labels: Bug
