### ISSUE TITLE
[BUG] Emergency exit signs switch does not move after latest MSFS 1.8.3.0 update.

### ISSUE THREAD

**Issue by TwattyBollox** [flybywiresim/a32nx#741] opened 2020-09-18 17:45 UTC
**Mod Version**

0.2.0

**Describe the bug**

The "Emergency exit sign" switch does not move.
The text messages and up arrow still appear, but it refuses to move from the off position to "arm"

**To Reproduce**

1. Use the aircraft at any gate or parking
2.
3.

**Expected behavior**

The switch will move to the "arm" position while displaying the text message and an up arrow

**Actual behavior**

The text box appears, the up arrow also appears, the switch does not move

**References**

https://www.youtube.com/watch?v=tubPHYPEOPI
https://forums.flightsimulator.com/t/1-8-3-0-a320-cold-dark-not-working-anymore/273564/70

**Additional context**

1. The MFD pages also seem to be not working since the latest patch
It's as if they routed something a different way whcih disabled the lovely APU/DOORS/BLEED etc.
2. No1 engine switch turns off both engines - turning off No2 switch kills No2
3. Turning off No1 generator also kills both engines - turning off No2 gen does not kill everything
These two are issues that occur only with A32NX running - without A32NX they seem to not cause these symptoms
(well done Microsoft !)

Discord username (if different from GitHub):
You can contact me via:
Twitter @Chaosdruid
Hmmm ... I guess I need to download discord then lol :¬)

**Comment by UncleClapton** [comment] 2020-09-18 21:06
I'm actually unable to reproduce this. maybe changes we have made in updating the codebase fixed it?

**Comment by TwattyBollox** [comment] 2020-09-18 22:01
I just flew a flight, without a start form dark, and the switch and MFD pages worked - looks like it's intermittent ... will try the codebase ...

**Comment by KevinFaussadier** [comment] 2020-09-19 07:18
I currently see this issue with the last release

**Comment by lukecologne** [comment] 2020-09-19 08:54
I can't replicate this, latest master

**Comment by TwattyBollox** [comment] 2020-09-20 00:47
I've just tried some more testing, with the codebase I downloaded yesterday, and cannot replicate after 4 cold starts.
I did get some weird randomised shennanigans from the MFD, switching pages form ENG to APU and then BRAKES without any input, so it does seem to be a completely random MS/ASSobo complication (that's me putting it nicely BTW!)

I will keep testing after I've uploaded my last test (and complete failure of all systems on approach) to YouTube :¬(

**Comment by Venorcis** [comment] 2020-09-20 10:49
Cannot replicate either, switch works fine for me.

**Comment by Coralec** [comment] 2020-09-20 20:08
Just tested this and it is working fine and has been working fine in all my flights since the patch. We are going to need more information to properly replicate this bug.

**Comment by AdenFlorian** [comment] 2020-09-21 01:19
closing as it seems no one can replicate it

**Closed by AdenFlorian** 2020-09-21 01:19 UTC
Labels: bug, bug-a32nx

**Comment by TwattyBollox** [comment] 2020-09-21 06:46
Well, Kevin Faussadier did (see message above), but I cannot replicate it after the last two codechanges
