### ISSUE TITLE
[BUG] FCU and Screens not illumating

### ISSUE THREAD

**Issue by FlightInService** [flybywiresim/a32nx#962] opened 2020-09-29 16:17 UTC
**Mod Version**
Master (re-downloaded after 1.9.3 release)

**Describe the bug**
Spawned Cold and Dark at KCHS, Battery voltage not illuminated, FCU text not illuminated and all screens not illuminating after APU is engaged. 

**To Reproduce**
1. Spawn at Airport Cold and Dark
2. Look at Battery 1 and 2 screens (dark)
3. Engage Battery 1 and 2 and APU
4. FCU and all screens in the aircraft remain dark.

**Expected behavior**
Battery Voltage screens should display current voltage. After engaging APU all screens in the aircraft should begin startup process countdown.

**Actual behavior**
No screens, Battery Voltage and FCU performing properly. 

**References**
![Screenshot (3)](https://user-images.githubusercontent.com/71717288/94584982-61b63300-024d-11eb-8251-4fd5942fbd40.png)

![Screenshot (4)](https://user-images.githubusercontent.com/71717288/94585012-6975d780-024d-11eb-8e30-fbccdea7d6f3.png)

Was this working before/when did the issue start occurring?
Yes, started after 1.9.3

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by SCBionicle** [comment] 2020-09-29 16:59
Can confirm that autopilot and transponder doesn't work either. (Engine starts and APU starts are impossible due to this)

**Comment by donstim** [comment] 2020-09-29 17:19
APU master switch can be turned on and both APU lights illuminate, but APU switch never goes to "AVAIL" and APU bleed cannot be activated (although switch can be turned "on.")

**Comment by bisinchi** [comment] 2020-09-29 17:35
Hi, same issue here, with a not cold and dark cockpit (plane ready to take off at start), no screens or no FCU illuminated either.

**Comment by MjrIncident** [comment] 2020-09-29 17:51
Hi, same issue here, with **a cold and dark cockpit (plane ready to take off at start) has no flight director dashboard illuminations or lower screens and FCU illuminations**. Upper panel is lit and center console.
Got 1.9.3 and reinstalled V3 of the a32NX mod. I have been getting the random plane shutoffs as flagged in the update notes by Asobo as a current "known issue". (dont know if that is related..)

**Comment by MTRNord** [comment] 2020-09-29 17:51
Yep can reproduce :) Asobos update get worse each time :(

**Comment by wsx79** [comment] 2020-09-29 18:16
Same here. I have to delete mod for screen working again.

**Comment by callebstrom** [comment] 2020-09-29 19:04
Same, no sounds from fire tests either (might not be related though)

**Comment by waar19** [comment] 2020-09-29 19:22
No lights

![image](https://user-images.githubusercontent.com/4492064/94605727-215fb080-025f-11eb-9ebb-16a7d15d07be.png)

**Comment by Benjozork** [comment] 2020-09-29 19:38
> Yep can reproduce :) Asobos update get worse each time :(

This is expected as we are patching the base game, do not blame it on them.

**Comment by uriberma** [comment] 2020-09-29 20:24
Hi, same issue here, with a cold and dark cockpit.

**Comment by zurbran** [comment] 2020-09-30 01:41
Same here, screens are off can't turn them on.

**Comment by AdamNZ** [comment] 2020-09-30 02:57
Same here ... looking forward to the next A32NX update :-)

**Comment by smhwd** [comment] 2020-09-30 03:21
I have exactly  the same problem but at a different airport if it matters

**Comment by tyler58546** [comment] 2020-09-30 06:03
Fixed in latest release.

**Closed by tyler58546** 2020-09-30 06:03 UTC
Labels: Bug, Critical Bug, MSFS 1.9.3.0
