### ISSUE TITLE
[BUG] Radio displays blank in certain views/pan orientations

### ISSUE THREAD

**Issue by donstim** [flybywiresim/a32nx#1016] opened 2020-10-01 07:16 UTC
**Mod Version**
Master (03.1)

**Describe the bug**
The radio displays on the pedestal do not display any digits in certain windows and orientations:
View reached by CTRL-1 (instrument view 1- PFD/ND): Panning straight down, the radios display digits. Pan to around 90 degrees (perpendicular to the radios) and the digits disappear.

View reached by CTRL-2 (instrument view 2- FCU)); Same as above

View reached by CTRL-3 (instrument view 3 - ECAM): Panning straight down, no digits are displayed on the radios. Panning around wildly, you can make them appear in certain orientations.

View reached by CTRL-4 (instrument view 4 - center displays): Same as 1 and 2

View reached by CTRL-5 (instrument view 5 - CDU): Same as 3

View reached by CTRL-6 (instrument view 6 - center pedestal): Not displayed in the initial view, which would be the one you would normally use to access the radio panel, but panning upwards slightly will cause the digits to appear.

View reached by CTRL-7 (instrument view 7 - lower pedestal): Panning up to see the radio display - the digits are there.

View reached by CTRL-8 (instrument view 8 - overhead panel): Panning all the way down to see the radio panel, the digits are there.

**To Reproduce**

Just by moving between instrument views in the cockpit.  I went to the central pedestal view (CTRL-6) to set a radio frequency and found the radio display to be blank.  I was going to report this bug, but then just happened to see the digits appear in a different instrument view. I then decided to check all of the instrument views.  Since the panning orientation also seems to affect whether or not the digits are displayed, I tend to think this is probably a base sim issue of some sort.
1.
2.
3.

**Expected behavior**
Digits in radio display to be present in all instrument views/orientations.

**Actual behavior**
Digits in radio display are not present in some instrument views/orientations.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?I don't know. I now suspect it is and will check on that in the next day or so.

Discord username (if different from GitHub):donbikes

**Comment by lousybyte** [comment] 2020-10-01 07:35
Related #986

**Comment by Oberstumfuher** [comment] 2020-10-01 10:12
This problem with the radio view happens even without MOD, I checked it with my "community" folder completely empty.

**Comment by NathanInnes** [comment] 2020-10-01 12:09
Closing as this is a duplicate of the issue listed above.

**Closed by NathanInnes** 2020-10-01 12:09 UTC
Labels: Bug, Visual
