### ISSUE TITLE
Fuel Pred page showing incorrect values for EFOB and UTC

### ISSUE THREAD

**Issue by dani143lund** [flybywiresim/a32nx#6050] opened 2021-10-21 02:43 UTC
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-10-19T16:05:21+00:00",
  "ref": "experimental",
  "sha": "8c3967f1993801630e714218cb2760d6cd5fe75d",
  "actor": "Saschl",
  "event_name": "manual"
}
```

### Describe the bug

It ocurred in previous versions of Experimental as well as before SU6. Basically, there is an inconsistency of values when comparing the expected arrival UTC from the Fuel Pred page against the F-PLN page. The arrival UTC that shows in the Fuel Pred page is significantly higher than the UTC from the F-PLN page. The F-PLN UTC is the correct estimated value. That increase of time from the Fuel Pred page results in wrong EFOB values and amber EFOB messages saying that the fuel is not enough for the Destination, which is wrong, as it always goes as planned and I get to the destination with enough fuel and reserves for alternating and such.

In the following image you can see the F-PLN page and the correct UTC arrival time (01:04), as well as a wrong EFOB value due to this issue.
![Captura de Tela (334)_LI](https://user-images.githubusercontent.com/81655546/138198984-62dc550d-4746-48e4-b6c1-95f268e4dd58.jpg) 

In the next image you can see the Fuel Pred page and the incorrect and inconsistent values for UTC, which is 02 hours and 45 minutes higher than what is shown in F-PLN page, and consequently the EFOB values 
![Captura de Tela (335)_LI](https://user-images.githubusercontent.com/81655546/138199288-4aebfdc3-b197-479a-8722-23808a5b26f4.jpg)

And finally, I compared the EFOB from a route waypoint from the OFP generated from SimBrief and the actual inflight value, just to show that there wasn't any abnormal fuel consumption and everything was as planned, except if compared to the Fuel Pred page.

FOB 4300 Kg when passing "VUDEM" waypoint
![Captura de Tela (336)_LI](https://user-images.githubusercontent.com/81655546/138199740-c53c71e3-40df-484f-ad88-79ffbf5c96d9.jpg)

Estimated FOB for that waypoint was 4400 Kg, with a deviation of only 100 Kg, which is completely ok, proving that the EFOB is ok, except for the Fuel Pred page
![Captura de Tela (337)_LI](https://user-images.githubusercontent.com/81655546/138199789-6cff8a58-6e2b-4f0c-830f-495051ded456.jpg)

That being said, there is clearly some issue with the Fuel Pred page, and it ocurred several times with me

### Expected behavior

I expected the Fuel Pred page to show correct values for EFOB and times related. It should be similar to what was previously planned for the flight.

### Steps to reproduce

Plan your flight through SimBrief and then import the Fuel and Payload weights from the MCDU in the simulator. Check if the fuel and weights are ok from the airplane Systems displays. Then fill the MCDU init page with those weights. When checking the Fuel Pred page you can see that the values are a bit different than the planned value, and as you fly that difference increases.

### References (optional)

Screenshot taken on final app, it can be seem from the ecam display that the FOB was 3540 Kg, and not those weird negative values from the Fuel Pred page
![Captura de Tela (338)](https://user-images.githubusercontent.com/81655546/138201961-8036ed15-36d9-480b-af09-1d95dd0e3cb1.png)

**Comment by tracernz** [comment] 2021-10-21 04:14
Hi Dani. We appreciate detailed bug reports like this. That said, [this is a known issue with the experimental version](https://docs.flybywiresim.com/fbw-a32nx/support/exp/#known-issues). Fuel predictions have yet to be implemented, so it is simply using the old system which obviously doesn't work properly with the new flight planning system. I will close this bug as the issue is already well known and VNAV implementation is planned and in-progress.

**Closed by tracernz** 2021-10-21 04:14 UTC
Labels: Bug
