### ISSUE TITLE
On-Board Airport Navigation System (OANS)

### ISSUE THREAD

**Issue by itscongq** [flybywiresim/a32nx#5008] opened 2021-06-04 20:43 UTC
### Aircraft Version

Development

### Description

Airbus has OANS option to be installed on the newer variant of the A320 and A330 family, is that possible to add into the sim?

### References (optional)

https://www.airbus.com/newsroom/news/en/2014/05/on-board-airport-navigation-system-oans-debuts-on-a320-and-a330-families-of-aircraft.html

### Discord Username (optional)

CongQ#9443

**Comment by aguther** [comment] 2021-06-04 21:06
It's a very rare option on the A320. One issue is that you barely find any references how it's integrated into the A320 (e.g. how do the EFIS knobs look like when the option is installed).

If you can provide any references this would be very helpful.

**Comment by Kimbyeoungjang** [comment] 2021-06-05 06:56
> It's a very rare option on the A320. One issue is that you barely find any references how it's integrated into the A320 (e.g. how do the EFIS knobs look like when the option is installed).
> 
> If you can provide any references this would be very helpful.

I found some photo from google

![20171021_220859 jpg 3f059a5b5324e3a41956f5083da6dfcf](https://user-images.githubusercontent.com/23118756/120883162-9bc6a880-c616-11eb-8b85-4bd0fd033878.jpg)

**Comment by Kimbyeoungjang** [comment] 2021-06-05 06:57
plus
![image](https://user-images.githubusercontent.com/23118756/120883202-c6b0fc80-c616-11eb-93fa-2162419cff83.png)

**Comment by aguther** [comment] 2021-06-05 08:38
Yeah those are two I also found. They are not showing the EFIS knobs or relevance.

**Comment by Kimbyeoungjang** [comment] 2021-06-05 08:54
> Yeah those are two I also found. They are not showing the EFIS knobs of relevance.

https://www.slideserve.com/gizela/ads-b-avionics-solutions

PPT page 20,
![image](https://user-images.githubusercontent.com/23118756/120886069-01bb2c00-c627-11eb-8b2c-d24066223b28.png)

I found that!

**Comment by itscongq** [comment] 2021-06-05 09:01
![image](https://user-images.githubusercontent.com/73812436/120886139-024fc480-c61f-11eb-8794-275a7143fdfe.png)

found this screenshot from an old deleted video, but the general gist i remembered is that when the EFIS knob is clicked to the "zoom" selection it would enable the knob further scrolling to the left to get further zooming on the airport map

**Comment by itscongq** [comment] 2021-06-05 09:04
https://www.youtube.com/watch?v=LTr4DJFL764

this is a video for the OANS interaction for the A330, starting from 5:00 to 5:03, i imagine A320 would be the same since they basically share the same EFIS unit?

**Comment by MisterChocker** [comment] 2021-06-06 06:33
Duplicate of #1893

**Closed by MisterChocker** 2021-06-06 06:33 UTC
Labels: Enhancement
