### ISSUE TITLE
Altimiter not flashing when passing transition altitude

### ISSUE THREAD

**Issue by Scourus1** [flybywiresim/a32nx#4818] opened 2021-05-14 22:05 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-14T18:01:21+00:00",
  "ref": "master",
  "sha": "0e6bd0eff70d9070ceacdd192f69572c2bce8b28",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

IN an airbus the altimiter setting on the pfd is flashing when passing through it. Thats not the case anymore since the custom AP was released.

### Expected behavior

Altimeter flashing when passing TRANS ALT

### Steps to reproduce

Set TRANS ALT prior to T/O
Fly through the mentioned Altitude 
Altimeter setting not flasing as expected

### Discord Username (optional)

scourus

**Comment by MisterChocker** [comment] 2021-05-15 17:15
Duplicate of #3293

**Closed by MisterChocker** 2021-05-15 17:15 UTC
Labels: Bug, PFD
