### ISSUE TITLE
Using .Pln's Bug out the MD Display

### ISSUE THREAD

**Issue by rpxyz** [flybywiresim/a32nx#4162] opened 2021-03-27 22:23 UTC
**Mod Version**

Latest Dev Version

**Describe the bug**

When importing .pln's from SimBrief it makes bugs out the ND Display as shown in the image. 
I have gone over the problem without a .pln and then the ND Display works perfectly fine.

**To Reproduce**

1. Loaded the game, imported the .pln, pressed fly and the ND Display is bugged out.
2. Loaded the game, have not imported any .pln, pressed fly and the ND Display then works perfectly fine.

**Expected behavior**

For the ND Display to work correctly as it should do.

**Actual behavior**

When importing .pln's from SimBrief it bugs out the ND Display as shown in the image. 

**References**

![110859925-29019780-828a-11eb-9a38-a1f8fe4fa7d7](https://user-images.githubusercontent.com/2183651/112736476-ef4bb480-8f4a-11eb-84de-0387f6cf21d0.png)

**Additional context**

Was this working before/when did the issue start occurring?
- Once I started using the .pln (before that it was fine)

Is this a problem in the vanilla unmodded game?
- Sorry not sure, I only tried with A32NX and importing a .pln nothing more.

**Comment by blazinga350** [comment] 2021-03-27 22:26
For me when I power the aircraft, the MFD does not turn on. I use the DEV version.

**Comment by Benjozork** [comment] 2021-03-27 22:31
@blazinga350 this is unrelated to this issue.

Make sure to try without anything else in your Community folder.

**Comment by tracernz** [comment] 2021-03-28 00:27
Just in case you're not aware, you can enter your SimBrief username in the MCDU options menus, and then the INIT REQUEST on INIT A page will fetch your latest SimBrief plan automatically. (Doesn't invalidate this issue though.)

**Comment by LordNecton** [comment] 2021-03-28 06:49
The MFD does not turn on for me either once aircraft is powered up just stays blank.  Latest Dev release

**Comment by MisterChocker** [comment] 2021-03-28 14:05
> The MFD does not turn on for me either once aircraft is powered up just stays blank. Latest Dev release

@LordNecton 

> Make sure to try without anything else in your Community folder.

**Comment by 2hwk** [comment] 2021-06-09 11:49
Seems to be dependent on specific routes, I am unable to reproduce this, loaded several .pln files, no dice, it works as expected.

**Comment by 2hwk** [comment] 2021-07-04 17:16
Closing. If anyone has this happen again, please open a new issue and upload a link to the .pln file.

**Closed by 2hwk** 2021-07-04 17:16 UTC
Labels: Bug, Can't Reproduce, Waiting For Response

**Comment by 2hwk** [comment] 2021-07-08 05:02
Possible resolution:

This kinds of issues can also be caused by default files being corrupted. You will then have to redownload the sim, however, before that, try moving or deleting these packages from your Official Packages folder (same root as Community)
![image](https://user-images.githubusercontent.com/15316958/124865150-bbbe0300-dfec-11eb-96fc-f43b3ef7657b.png)
