### ISSUE TITLE
[BUG] E/WD - Thrust Limit Value and Thrust Rating Mode Logic Incorrect

### ISSUE THREAD

**Issue by olibarke** [flybywiresim/a32nx#3005] opened 2021-01-12 15:15 UTC
**Mod Version**
{
  "built": "2021-01-12T06:10:20+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**
 On the E/WD the Thrust Limit Value and Thrust Rating Mode in top right corner does not reflect correct behaviour either prior to take-off or in the cruise. 

**To Reproduce**
1. Prepare Aircraft IAW FCOM
2. E/WD should display Thrust Rating Mode for desired take off mode (TOGA or FLX). The Thrust Limit Value should display correct digits
3. When manually moving thrust lever during taxi or inflight the green N1 indication should not follow the thrust levers, should just remain on the TLV based on a FLX or TOGA take-off (or inflight Thrust Rating Mode).

**Expected behavior**
When preparing aircraft, and data input into the MCDU. If leaving the Flex box on PERF - TAKE OFF page blank (assuming TOGA takeoff) the top right of E/WD should display:

TOGA
99.8% (or appropriate value for temperature)

If using Flex mode and for example input a flex of 47°C it should display:

 FLX
89.5%       (or appropriate value for tempurature)
47°C

During flight it should reflect the selected engine Thrust Rating Mode such as TOGA, MCT, CLB, FLX with associated Thrust Limit Value for selected mode. 

**Actual behavior**
It displays Thrust Rating Mode, but the Thrust Limit Value changes as you move the trust levers through the range. Additionally when selecting FLX value, it still shows TOGA rather than FLX.

**References**
[img]https://i.imgur.com/zlo07wz.jpg[/img] - This shows a 55°C Flex is selected, it does not show what that maximum thrust is, and still indicates TOGA rather than FLX

[img]https://i.imgur.com/VREa8St.jpg[/img] - Actual A320N E/WD showing an example of the Thrust Rating Mode of CLB and the maximum Thrust Limit Value below. 

**Additional context**

Was this working before/when did the issue start occurring? - Not worked

Is this a problem in the vanilla unmodded game? - Yes

**Comment by MisterChocker** [comment] 2021-01-12 17:06
Not yet implemented.
Duplicate of #989

**Closed by MisterChocker** 2021-01-12 17:06 UTC
Labels: Bug
