### ISSUE TITLE
A320NX Last State Loading

### ISSUE THREAD

**Issue by Cyanide0401** [flybywiresim/a32nx#7079] opened 2022-04-17 23:15 UTC
### Aircraft Version

Experimental

### Description

Was wondering on the A320 would it be possible to create a feature under where there is cold n dark, Ready to fly etc. to create a tab that says perhaps like the pmdg 737's (Previous state) Then this stores your last configurations on all buttons etc like you had it when you stopped the last flight.

This worked nicely for us as we do a lot of flights and don't want to load up and have to set all the lights and aircon switches etc again. 

### Discord Username (optional)

Warren Smith - 1431868#2037

**Comment by aguther** [comment] 2022-04-18 05:33
You can try experimental version which includes this function with defined states like Cold&Dark, Taxi and Ready for Take-Off.

**Comment by Cyanide0401** [comment] 2022-04-18 09:55
Hi

Thanks for the promp reply. I am on the experimental and BTW you guys are doin an super amazing job.

What i ment was.
Within that section where the cold n dark tab etc is.
Can we add a button to remember your last state you had the aircraft in.

For example

When i usualy stop at the gate or stand. Ill have plane on APU. IRS's will be off, all light exept Nav n Logo will be off.
Emergency lights will be on, pax air and crew air will be on and all the panel lights and used flood lights will be on depending what time i got to the gate.

So this button should store what your switches etc was on when you log off. Then when you log in again and you spawn on the apron the aircraft will be how you last left it. 
Then this is nice cause then you dont have to turn on all the million light knobs etc.

Dont know if you ever flown the PMDG 737, 77 or 747. They used to have a function like this called "load last state"

This helos us long haul pilots alot when prepping as the aircraft would be in a ready state. Prety mutch the sane as your turnaround state that is in the experimental version but light knobs under dash and around panel will be where you had it last

**Comment by tracernz** [comment] 2022-04-18 10:03
I would love to see this also, but I’m sure we must already have an issue for it. It’s been discussed many times.

**Comment by derl30n** [comment] 2022-04-18 12:26
Also https://github.com/flybywiresim/a32nx/issues/4840.

But Duplicate of https://github.com/flybywiresim/a32nx/issues/818

**Closed by derl30n** 2022-04-18 12:26 UTC
Labels: Request
