### ISSUE TITLE
[BUG] AP constant disconnect / Haywire

### ISSUE THREAD

**Issue by Ircghost** [flybywiresim/a32nx#2907] opened 2021-01-06 13:47 UTC
```
**Mod Version**
{
    "url": "https://api.github.com/repos/flybywiresim/a32nx/releases/assets/30332387",
    "id": 30332387,
    "node_id": "MDEyOlJlbGVhc2VBc3NldDMwMzMyMzg3",
    "name": "A32NX-master.zip",
    "label": "",
    "uploader": {
        "login": "github-actions[bot]",
        "id": 41898282,
        "node_id": "MDM6Qm90NDE4OTgyODI=",
        "avatar_url": "https://avatars2.githubusercontent.com/in/15368?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/github-actions%5Bbot%5D",
        "html_url": "https://github.com/apps/github-actions",
        "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
        "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
        "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
        "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
        "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
        "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
        "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
        "type": "Bot",
        "site_admin": false
    },
    "content_type": "application/zip",
    "state": "uploaded",
    "size": 317326795,
    "download_count": 240,
    "created_at": "2021-01-06T07:08:16Z",
    "updated_at": "2021-01-06T07:08:21Z",
    "browser_download_url": "https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip"
```

**Describe the bug**
AP went completly haywire. Would continiously disconnect when tried to enable. Plane started to roll back and forth. eventhough AP was disconnected no control input was allowed. It also still followed NAV path. Seems related to throttle as it constantly went into overspeed.

**To Reproduce**
1. Flew from LGIR to HECA, used simbrief to import FLT
2. Flew just before SIT at FL170, awaiting to go to FL190
3. Out of the blue AP disconnected
4. plane  went into overspeed
5. couldn't control throttle
6. tried disconnecting all yoke, throttle etc, still AP kept disconnecting
7. keyboard was clear of pressed buttons
8. 

**Expected behavior**
Keep AP on and fly plane

**Actual behavior**
rolling plane, still following NAV no manual input allowed.

**References**

**Additional context**
I refly immediatly after, no issues.

Was this working before/when did the issue start occurring?
Never happened before

Is this a problem in the vanilla unmodded game?
Unmodded, literally no other mods in community folder. 1.12.13.0

Ircghost

**Comment by Benjozork** [comment] 2021-01-06 14:51
Cannot reproduce as of latest dev

**Comment by Ircghost** [comment] 2021-01-06 15:04
Yeah I just completed the flight and had no issue again (luckily)

**Comment by MisterChocker** [comment] 2021-03-17 01:01
Closing since issue seems to be caused by an unknown conflict.

**Closed by MisterChocker** 2021-03-17 01:01 UTC
Labels: Autopilot, Bug
