### ISSUE TITLE
[BUG] ND is jerky since mod optimization

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#3424] opened 2021-02-08 19:13 UTC
**Mod Version**

2021-02-08T18:54:55+00:00"

**Describe the bug**

Navigation Display is jerky since mod optimization

**To Reproduce**

1. In flight, even during cruise flight, navigation display is not enough smooth: refresh rate is too low
2.
3.

**Expected behavior**

Add settings m in order to adjust refresh rate of ND
Previous refresh rate was be fine

**Actual behavior**

navigation display is not enough smooth: refresh rate is too low

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by ACSoft47** [comment] 2021-02-09 10:01
Do-you mean the slower refresh of the flight path drawing (and also even slower, the aircraft position along the path) ?

Because the arc graduation & WX radar refresh seem correct to me.

In any cases, I hope this can be corrected without the cost to loose partially or totally the optimization. On my 3.5 year PC (i7 7700 / GTX1080 / 16GB RAM), this code improvement is fantastic not only for the FPS but also for the stutters, when looking around inside the cockpit.

**Comment by JLD95** [comment] 2021-02-09 10:09
Yes I have a slower refresh of the flight path drawing and also even slower, the aircraft position along the path.

**Comment by Saschl** [comment] 2021-02-09 10:12
This issue is probably already included in #3380 and #3379

**Comment by beheh** [comment] 2021-02-09 12:24
Duplicate of #3380

**Closed by beheh** 2021-02-09 12:24 UTC
Labels: Bug
