### ISSUE TITLE
RNAV/RNP approach not working, MCDU discrepancies

### ISSUE THREAD

**Issue by PatriceCesson** [flybywiresim/a32nx#4759] opened 2021-05-09 16:26 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-09T13:56:29+00:00",
  "ref": "master",
  "sha": "9e66321a2021f4635c89c287466633cbd879ed53",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

I create a FP from LFRB (Brest) to LFRN (Rennes). FP has been created on Little Nav Map.
At LFRN, I want to make a RNP RW 10 approach and landing.
So, I load the plane and load the FP.
The FP is OK and I load all other parameters.
I start the flight.
En route, I enter the data for the dest.
What I can see is that the PERF/approach page is not the same I can see in the differente tutorials on youtube.

The screen looks like this:

![snap095](https://user-images.githubusercontent.com/30781354/117579013-597e7a00-b0f1-11eb-81de-75ed8d401e58.png)

What are missiing are the MDA and DH fields and also the arrival RW not indicated (LSK 1R 2R and 3R)
So I cannot enter any MDA.

The screen shall be like this:

![snap096](https://user-images.githubusercontent.com/30781354/117579569-c2ff8800-b0f3-11eb-8891-1ee8a41591fc.png)

I follow the plan, set the altitude of 2000 feet at the arrival at the first WP of the approach. At the next WP I try to engage the APPR mode but it does not work. The APPR green light remains switched off and the plane continues at the level of 2000 feet instead of starting the descent.

So, there are many things not ok in this flight:

1. Why the MCDU screen related to PERF/Approach is not the same I can see in the different tutorials (and the one of the tutorials is conform to the official Airbus one)

2. Why the APPR button does not engage when it should be as indicated on the approach plate from Navigraph?
See the plate below below:

![snap097](https://user-images.githubusercontent.com/30781354/117579368-d65e2380-b0f2-11eb-8f76-bd5ea2e366d9.png)

### Expected behavior

The MCDU screen should be as this one (official airbus tutorial screenshot)
![snap096](https://user-images.githubusercontent.com/30781354/117579259-6059bc80-b0f2-11eb-915f-008d3144fa28.png)

The APPR buitton should work as attended.

### Steps to reproduce

See above.

### References (optional)

See above.

### Additional info (optional)

I use navigraph database.
Nothing special either.

**Comment by aguther** [comment] 2021-05-09 16:28
At least about the APPR button:
As stated this is not yet supported with custom autopilot and will come with custom VNAV system.

**Comment by MisterChocker** [comment] 2021-05-09 17:50
@PatriceCesson 

Regarding the MCDU/Approach Page looking different:
We represent the Honeywell Release 2.

Judging by the Font of your MCDU references, your reference is from Thales.
Also if your reference actually is a Honeywell reference, your reference doesn't represent Honeywell Release 2, which is the version we represent.

**Comment by MisterChocker** [comment] 2021-05-09 17:52
Duplicate of #2792

**Closed by MisterChocker** 2021-05-09 17:52 UTC
Labels: Bug

**Comment by PatriceCesson** [comment] 2021-05-09 18:32
OK. Will wait the VNAV and LNAV from the custom AP.
Thanks.
