### ISSUE TITLE
[BUG] Unable to HOLD or enter next waypoint in approach waypoints

### ISSUE THREAD

**Issue by aviadnissel** [flybywiresim/a32nx#3495] opened 2021-02-12 21:57 UTC
**Mod Version**

Development - 7e585da

**Describe the bug**

In the F-PLN page no waypoint created by selecting an approach is selectable, meaning no hold instructions or additional waypoints in between. That includes the entry waypoint (which usually have a hold pattern).

**To Reproduce**

1. Fly
2. Select an approach through the MCDU
3. Try to click on any point in the flight plan menu, nothing.

**Expected behavior**

Being able to select the point, hold or enter waypoints. I am aware that holding pattern is not yet implemented but it feels like it should be consistent with the rest of the flight plan.

**Actual behavior**

Nothing happens.

**References**

**Additional context**

The most important part is the entry waypoint since holds are expected to occur there.

Was this working before/when did the issue start occurring?
Unknown.

Is this a problem in the vanilla unmodded game?
Unknown.

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2021-02-12 21:58
Holding patterns are not implemented.

**Comment by aviadnissel** [comment] 2021-02-12 22:01
I am aware, and I wrote that in the description, but the behavior needs to be consistent when hold is implemented.

**Comment by MisterChocker** [comment] 2021-02-13 14:10
Duplicate of #1388 and #1443

**Closed by MisterChocker** 2021-02-13 14:10 UTC
Labels: Bug
