### ISSUE TITLE
Flight Displays Create Strobe/Flickering Effect In Cockpit [BUG]

### ISSUE THREAD

**Issue by Polluticorn** [flybywiresim/a32nx#1305] opened 2020-10-14 00:48 UTC
**Mod Version**

V0.3.1

**Describe the bug**

[Microsoft Flight Simulator 2020.10.13 - 19.45.00.03.zip](https://github.com/flybywiresim/a32nx/files/5374899/Microsoft.Flight.Simulator.2020.10.13.-.19.45.00.03.zip)
Flight displays seem to create a flickering/strobe effect in the cockpit. Will get worse as you brighten them and will go away when turned off. 

**To Reproduce**

1. Load departure at night
2. It should show right away
3.

**Expected behavior**

Steady cockpit illumination

**Actual behavior**

Strobe/Flickering light

**References**

I attached a very short video so I could upload for reference. If longer video is needed let me know and I can share via another way due to the file size limit. 

**Additional context**

N/A
Was this working before/when did the issue start occurring?
No issues before, noticed it tonight. 
Is this a problem in the vanilla unmodded game?
Not sure

Discord username (if different from GitHub): Psyclone#3666

**Comment by Polluticorn** [comment] 2020-10-14 00:49
If it matters, I have tried to restart my flight, the game and re-install the mod.

**Comment by lukecologne** [comment] 2020-10-14 00:49
This was an issue caused by the new MSFS update. It has been fixed in master.

**Closed by lukecologne** 2020-10-14 00:49 UTC
Labels: Bug

**Comment by Polluticorn** [comment] 2020-10-14 00:51
Thank you!
