### ISSUE TITLE
Autopilot Rocks Left and Right Quickly at Higher Altitudes

### ISSUE THREAD

**Issue by A320PHX** [flybywiresim/a32nx#2163] opened 2020-12-01 11:02 UTC
Most Recent Dev Model With 11.6 Autopilot Fix

First off, THANK YOU for fixing the autopilot for the A320! You guys do awesome work!

The only bug left is that the plane seems to rock left and right quickly. This seems to happen at altitudes above 15-20,000 ft. Turning off SEC1 is a workaround for this at the moment.

1. Load up flight plan.
2. After takeoff, set autopilot and desired altitude.
3. At altitudes above 15-20,000 ft the rocking begins.

What is Expected?
Steady flight, of course turbulence is expected but, stable otherwise.

Was this working before/when did the issue start occurring?
This was working fine pre 11.6 patch. Not sure if this is something you guys can fix since you are now assisting Asobo with this.

Is this a problem in the vanilla unmodded game?
Yes, I believe it is another core sim issue. Not sure if you now have access to address this last issue.

**Comment by captbillybob** [comment] 2020-12-01 12:19
Same thing just happened to me at about FL220 and up.

**Comment by speedbird5** [comment] 2020-12-01 12:45
Can also confirm the above problem.

On dev version 2020-12-01T10:59:14+00:00 on MSFS version 1.11.6.0

Also, will also happen when going direct to a waypoint.  Can stop the roll by turning off ELAC2 and SEC2 and then turning them back on.

**Comment by Benjozork** [comment] 2020-12-01 14:36
Duplicate of #2005

**Closed** 2020-12-01 14:36 UTC
Labels: Bug
