### ISSUE TITLE
Performance degradation in cockpit (low GPU utilization)

### ISSUE THREAD

**Issue by SusurHe** [flybywiresim/a32nx#7119] opened 2022-04-28 14:25 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-27T17:53:01+00:00",
  "ref": "master",
  "sha": "53c9747d0806a8b84120a450de021c331b4bcfa4",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "master:53c9747d"
}
```

### Describe the bug

After MSF2020 update on April 26, I found that the number of frames in the cab decreased significantly, and the GPU did not run 100%, but outside camern is normal;

CPU: Intel Core 12700KF
GPU: 3070ti
SSD(pci-e4.0)

### Expected behavior

Befor that,  the FPS is higher in cab

### Steps to reproduce

 in the cab decreased significantly

### Additional info (optional)

CPU and disk usage is not high. There may be task blocking or low resource utilization

**Comment by Benjozork** [comment] 2022-04-28 14:27
Need screenshots of the MSFS fps counter.

Please keep in mind quite a few people are reporting issues in general with SU9.

**Comment by SusurHe** [comment] 2022-05-07 07:41
> 

![image](https://user-images.githubusercontent.com/51081799/167244209-eac07e3c-3aec-4a13-82c2-f564c466be43.png)

**Comment by Swaluver88** [comment] 2022-05-07 08:00
So I was doing some experimenting just for general FPS gain. Undock any pop up windows (camera, atc, etc) and move it to a second monitor (if applicable) I've gained atleast 50% better frames like that. However volanta now is the one I get terrible frames when running. Think this may go deeper than just FBW, poorly optimized sim connect and pop up windows in msfs. 

However still trying to gain more data on it, but its a start to see if it's msfs and or a FBW thing

**Comment by aguther** [comment] 2022-05-07 08:07
There is also a yet unknown combination with hardware and potentially other environmental conditions that have influence.

I have always two pop-out windows, glass refresh rate on high, Volanta running in the background and still no issues.

That overall makes it so hard to find root causes.

**Comment by JEP795** [comment] 2022-05-07 21:14
I'm noticing this is happening after two hours more or less on the a32nx Development Version, and is particularly noticeable when you are flying over land. I can do a 6 hour flight over the ocean and my degradation won't start until descent when I'm nearing land. 

If I'm flying over land, the degradation begins about 2 hours in and you will notice GPU usage dropping to the mid 50s more or less inside the virtual cockpit. If going to an outside view, GPU usage climbs up to the high 90s again leading me to believe it has something to do with the cockpit systems, particularly when terrain is loading or is present. 

Cruise Level over the Ocean 55+ FPS
Ground Level FPS prior to Degradation ~40
Cruise Level FPS after degradation <41
Ground Level FPS after degradation <31

My Hardware: 
R7 5800x
RTX 3080ti
64 GB Ram @ 3600Mhz
1 TB Samsung Evo Plus 970
MSI X570 MPG Gaming Edge Wifi

Peripherals: 
Honeycomb Alpha
Honeycomb Bravo
Thrustmaster Airbus Sidestick
Thrustmaster T-Flight Rudder

**Comment by 2hwk** [comment] 2022-08-09 06:17
Dupe of https://github.com/flybywiresim/a32nx/issues/6357 Closing

**Closed by 2hwk** 2022-08-09 06:17 UTC
Labels: Bug, Waiting For Response
