### ISSUE TITLE
[BUG] Lose MFD and PFD even with APU/APU Gen

### ISSUE THREAD

**Issue by BrianBash** [flybywiresim/a32nx#390] opened 2020-09-05 01:44 UTC
Trying out Version 0.2.0.

Everything was going good until I disconnected the Ext Pwr at the gate.

APU was on and avail, APU GEN was not off, and I lost the PFD and MFD. Started both engines, disconnected Ext Pwr but did not lose the PFD/MFD.

Not sure if this is on the MSFS side or elsewhere.

**Comment by Benjozork** [comment] 2020-09-05 02:45
Please follow issue templates.

**Comment by Venorcis** [comment] 2020-09-05 11:32
Can confirm I had the same issue, with APU on as normal the displays would turn off once disconnecting external power. Only reconnecting the external power or running the engines would allow the displays to be on.

**Comment by nikotina91** [comment] 2020-09-05 14:06
Just to be sure, did you did turn on both battery switches when using apu?

**Comment by Venorcis** [comment] 2020-09-05 18:16
> Just to be sure, did you did turn on both battery switches when using apu?

I couldn't reproduce it anymore on the latest master version. However, on each switch (EXT> APU, APU > ENG, etc.) you do get a self-test now, I don't know if that's the real-life behavior?

**Comment by AdenFlorian** [comment] 2020-09-05 22:49
fixed by #417 which is now in master

**Closed by AdenFlorian** 2020-09-05 22:49 UTC
Labels: bug
