### ISSUE TITLE
[BUG] RNAV indicator "red square" not shown up

### ISSUE THREAD

**Issue by nwenkel** [flybywiresim/a32nx#2318] opened 2020-12-09 17:06 UTC
**Mod Version**

{
  "built": "2020-12-09T15:31:46+00:00",
  "ref": "",
  "sha": "",
  "actor": "Benedict Etzel <benedict@hearthsim.net>",
  "event_name": "manual"
}

**Describe the bug**

Flying an RNAV 8Z Approach to LOWI (MS Version) no "red square" indicator shows up. During approach NAV APP turns green

**To Reproduce**

1. RNAV 8Z approach to LOWI via EMEM
2.
3.

**Expected behavior**

Square showed have shown up to indicate the attitude 

**Actual behavior**

no indicator square

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by LoungeFlyZ** [comment] 2020-12-09 19:51
Please provide references and follow the template.

**Comment by MisterChocker** [comment] 2021-01-06 15:40
Duplicate of #2792

**Closed by MisterChocker** 2021-01-06 15:40 UTC
Labels: Bug
