### ISSUE TITLE
MCDU "Print" feature causes CTD when trying to print METAR/ATIS

### ISSUE THREAD

**Issue by enriqueo62** [flybywiresim/a32nx#5614] opened 2021-08-10 17:32 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-10T08:14:38+00:00",
  "ref": "master",
  "sha": "d30667bee2a5571ee055371021bee4a7da30eefd",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

After receiving the METAR report and trying to use "PRINT", MSFS crashes to desktop. It happens randomly, because sometimes it does not CTD.

### Expected behavior

No CTD when trying to PRINT the METAR/ATIS

### Steps to reproduce

1) Request METAR
2) Review received METAR
3) PRINT

### Discord Username (optional)

enriqueo

**Comment by bouveng** [comment] 2021-08-10 17:48
I use this feature all the time. Not experienced any CTD from this.

**Comment by glowfishDE** [comment] 2021-08-10 18:04
I can confirm this issue as for the pre-previous development release a few days ago. Have not tried it with d30667b yet as i am afraid of the long loading times so much ^^ but i can confirm, that this happened to me too 4 days ago.

**Comment by ErikNL80** [comment] 2021-08-10 18:19
I am also experiencing the same issue. Was not there before and start occuring somewhere after SU5.

**Comment by enriqueo62** [comment] 2021-08-10 22:02
> I can confirm this issue as for the pre-previous development release a few days ago. Have not tried it with [d30667b](https://github.com/flybywiresim/a32nx/commit/d30667bee2a5571ee055371021bee4a7da30eefd) yet as i am afraid of the long loading times so much ^^ but i can confirm, that this happened to me too 4 days ago.

It happened to me today with d20667b as well, the latest DEV version

**Comment by bouveng** [comment] 2021-08-10 23:48
Cant reproduce with `d30667b`.

![metar](https://user-images.githubusercontent.com/433429/128949112-ea42a140-08cf-4661-847d-d28fedeaf291.png)

**Comment by TheOGReece** [comment] 2021-08-11 00:12
> Cant reproduce with `d30667b`.
> 
> ![metar](https://user-images.githubusercontent.com/433429/128949112-ea42a140-08cf-4661-847d-d28fedeaf291.png)

![Screenshot_1](https://user-images.githubusercontent.com/88752072/128950607-23818f67-8875-4868-90d3-83d753f17dcb.png)

I can also confirm this seems to be fixed in the latest DEV build d30667b as I had the issue before updating.

**Comment by enriqueo62** [comment] 2021-08-11 00:52
I have been using an old ASOBO A320neo livery converted to A320NX. Could it be that old ASOBO liveries are causing the CTD? I'll check to see if I can reproduce it.

**Comment by enriqueo62** [comment] 2021-08-11 12:30
I am sorry...I keep pressing the wrong button.

**Comment by enriqueo62** [comment] 2021-08-11 13:02
Well, it happened again with a livery that had worked well previously. What I am doing is that after receiving the METAR, I go straight and press the PRINT button. It seems that if I wait a little and/or go somewhere else like F-PLAN then return the CTD does not occur,

**Comment by glowfishDE** [comment] 2021-08-11 13:09
I just tried it flying from DNMM to FAPE and it did not crash in the actual development version 1c5335e
Maybe the crashes come from wrong METAR/TAF weather data that cause the crash ? That would explain why it happens to some people and others dont have it. I can say that i had the crashes previously and now that i tried it i didnt crash. But since Asobo has so many problems with Weather Data, Air Pressure and Flight Levels and also the ATCs not knowing your real flight level sometimes or sudden temperature raises to +53°c at FL 360 (where it surely is not that warm !) which resulted in sudden fuel burn of like 4200 kg/min per Engine or something like that.. i would think that the CTDs when printing the METAR/TAF Weather information could also result in the horrible bugs that microsoft/asobo is presenting us after every new update.

What really makes me angry is, that these bugs were there 1 year ago.. it took them weeks or months to fix and now the brought SU5 we have all the same bugs again.. like if they rolled back to an old development branch.

I´m almost sure the CTD has nothing to do with the FBW code.. But maybe some other person who is a real developer has an idea how to prevent these CTDs.

**Comment by enriqueo62** [comment] 2021-08-11 13:18
I am able to reproduce it consistently when after going to Received Messages in the MCDU, and clicking on METAR message, almost immediately I try to PRINT it right away. When I wait a few seconds to click PRINT, or use the arrow to move up/down, and then PRINT, it never CTD's.

**Comment by wpine215** [comment] 2021-08-11 16:17
> I just tried it flying from DNMM to FAPE and it did not crash in the actual development version [1c5335e](https://github.com/flybywiresim/a32nx/commit/1c5335ec13ec6b7d29319db3371299da5e4fb880)
> Maybe the crashes come from wrong METAR/TAF weather data that cause the crash ? That would explain why it happens to some people and others dont have it. I can say that i had the crashes previously and now that i tried it i didnt crash. But since Asobo has so many problems with Weather Data, Air Pressure and Flight Levels and also the ATCs not knowing your real flight level sometimes or sudden temperature raises to +53°c at FL 360 (where it surely is not that warm !) which resulted in sudden fuel burn of like 4200 kg/min per Engine or something like that.. i would think that the CTDs when printing the METAR/TAF Weather information could also result in the horrible bugs that microsoft/asobo is presenting us after every new update.
> 
> What really makes me angry is, that these bugs were there 1 year ago.. it took them weeks or months to fix and now the brought SU5 and we have all the same bugs again.. like if they rolled back to an old development branch.
> 
> I´m almost sure the CTD has nothing to do with the FBW code.. But maybe some other person who is a real developer has an idea how to prevent these CTDs.

None of the METAR/TAF/ATIS data comes from MS/Asobo, they are fetched from our servers. So I’m fairly certain this is not the cause of the issue

**Comment by youngryan7** [comment] 2021-08-12 18:00
this just happened to me. first ctd since the hotfix no.2 
happened as soon as I clicked print

{
  "built": "2021-08-11T07:29:20+00:00",
  "ref": "master",
  "sha": "1c5335ec13ec6b7d29319db3371299da5e4fb880",
  "actor": "davidwalschots",
  "event_name": "manual"
}
 DEV

**Comment by 2hwk** [comment] 2021-08-14 11:48
This one is incredibly hard to reproduce, I've not been able to despite using old liveries from WU5, trying various in-flight states, etc. Seems very intermittent.

**Comment by enriqueo62** [comment] 2021-08-14 18:29
It has happened to me with some frequency,  if after  displaying the METAR as received message, immediately press the PRINT button. If I wait a few seconds after opening the METAR and pressing PRINRR, it never CTD.

**Comment by Paytheon** [comment] 2021-08-14 22:10
I was getting CTD anytime I pressed the PRINT button the other day. However, what I found was I had an interrupt issue, an irregular signal, with my thrustmaster pedals that was causing all sorts of issues with the simulator. I removed the pedals and the CTD when pressing the PRINT button went away. My experience only.

**Comment by PH-BFI** [comment] 2021-08-15 02:44
Exactly the same happened to me just a few minutes ago on the development version. Pressed 'print' just after I've opened the received METAR and it caused a CTD.

**Comment by TravisKG** [comment] 2021-08-15 03:12
Just wanted to add that I've had this same bug. Not sure if it's relevant, but it was on a 6 hour flight, and only happened just before landing. Something else unusual about the flight was my Internet and/or the Microsoft servers seemed to be having problems as I was getting random disconnections throughout the flight.

**Comment by youngryan7** [comment] 2021-08-15 09:10
if it means anything mine only did after i had paused the sim

**Comment by enriqueo62** [comment] 2021-08-15 22:44
I hope FBW brings back the METAR to the EFB main page. It was quite useful when setting up. This would be an alternative to having to use the MCDU PRINT feature.

**Comment by MisterChocker** [comment] 2021-08-16 10:24
Please re-test with the airbus house livery or the fbw livery

**Comment by MisterChocker** [comment] 2021-08-16 11:55
Duplicate of #5429

**Closed by MisterChocker** 2021-08-16 11:55 UTC
Labels: Bug, Can't Reproduce, Waiting For Response
