### ISSUE TITLE
[BUG] ND Malfunction: freezes, red ring appearsin ND

### ISSUE THREAD

**Issue by vlbreda** [flybywiresim/a32nx#2665] opened 2020-12-23 20:30 UTC
**Mod Version**
0.5.1 Latest stable

**Describe the bug**
ND freezes, flightplan is no longer followed, plane starts to circle, red ring appears in ND, ND doesn't show actual position of the aircraft anymore.

**To Reproduce**
1. LaGuardia to KDCA (ILS 01), flight planned with MSFS flightplanner
2. About 20 NM before DC, the bug as mentioned above appears
3. Occured in other flights as well (f.e. EGCC to EGGW 26)

**Expected behavior**
Plane follows flightplan and picks up loc/gs

**Actual behavior**
Plane starts circling and 'loses' flightplan following, red ring appears in ND, ND freezes

**References**
![image](https://user-images.githubusercontent.com/72414568/103034588-8298d680-4565-11eb-8e95-b554babcfd43.png)

**Additional context**
Not sure whether this in an Asobo-bug or not. Might well be, cause the VFR-map (keyboard-V) freezes as well.

Was this working before/when did the issue start occurring?
After  latest MSFS / FBW update (22 dec)

Is this a problem in the vanilla unmodded game?
Not sure

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-12-23 20:32
Hello, do you have any other mods installed ?

**Comment by vlbreda** [comment] 2020-12-23 20:34
Hi Benjamin, mostly airports and scenery, but the CRJ200 working title as well. Could this be the bad guy?

**Comment by Benjozork** [comment] 2020-12-23 21:07
If you mean the CJ4, then it can be. Can you try without it and report back ?

**Comment by MisterChocker** [comment] 2020-12-23 21:28
looks like duplicate of https://github.com/flybywiresim/a32nx/issues/2656

**Comment by vlbreda** [comment] 2020-12-23 21:33
I will remove the other mods and try the same flight again tomorrow (24th), will report!

**Comment by vlbreda** [comment] 2020-12-24 13:01
Made the same flight again after removing the CJ4 mod, Everything seems to be working fine, think the problem is solved! Thanks very much for the helpful advice and have a good Christmas!

**Closed** 2020-12-24 17:30 UTC
Labels: Bug, Waiting For Response
