### ISSUE TITLE
[BUG] FLARE mode push nose down 

### ISSUE THREAD

**Issue by parker10101** [flybywiresim/a32nx#1769] opened 2020-11-05 11:48 UTC
**Mod Version**

v0.4.1 release version.

**Describe the bug**

When the flare mode is activated (about 50ft above the ground), the nose automatically pushes down and hits the ground by AP.

**To Reproduce**

1.Start a flight normally.
2.Use MCDU to make a flight plan. Set STAR and an ILS approach.
3.Select APPR on FCU. The problem occurs about 50ft above the ground.

**Expected behavior**

Flare normally to reduce V/S.

**Actual behavior**

Push nose down when flare mode is activated and hit the ground in V/S about -1000.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

After I use v0.4.1.This never happened before.

Is this a problem in the vanilla unmodded game?
I use navigraph for navdata.

Discord username (if different from GitHub): parker10101

**Comment by flytester** [comment] 2020-11-05 13:17
Apperead strange to me ass well, but searching on youtube learned me that this is correct behaviour. During flare mode the plane expect you to flare by pulling on the sidestick, planes compensates for that bij lowering the nose.

**Comment by parker10101** [comment] 2020-11-05 13:19
> Apperead strange to me ass well, but searching on youtube learned me that this is correct behaviour. During flare mode the plane expect you to flare by pulling on the sidestick, planes compensates for that bij lowering the nose.

It's too fast that I can't correct it. I use full sidestick and it still landing at -1000fpm

**Comment by Oberstumfuher** [comment] 2020-11-05 13:39
It is not the real behavior, flaps armed in full, the aircraft is with the bow slightly raised just to touch with the rear wheels and as soon as it loses speed the nose is lowered. The worst thing that is happening is with the autoland that is completely crazy, and apparently, nobody can fix it, the real behavior in autoland is the aircraft tilted backwards, nose up to the touchdown, where immediately the autopilot is disabled as well as the autothrottle is also disabled. What happens with the autoland now is the aircraft lowers its nose at the moment of landing and jumps, hitting the wheels more than 2 or 3 times while the autothrottle continues to accelerate the aircraft making it practically impossible to perform this type of landing. The A32NX mod corrected this perfectly, perfectly in v1.70.XX, after all the updates, it seems, nobody can fix it.

**Comment by parker10101** [comment] 2020-11-05 13:59
> It is not the real behavior, flaps armed in full, the aircraft is with the bow slightly raised just to touch with the rear wheels and as soon as it loses speed the nose is lowered. The worst thing that is happening is with the autoland that is completely crazy, and apparently, nobody can fix it, the real behavior in autoland is the aircraft tilted backwards, nose up to the touchdown, where immediately the autopilot is disabled as well as the autothrottle is also disabled. What happens with the autoland now is the aircraft lowers its nose at the moment of landing and jumps, hitting the wheels more than 2 or 3 times while the autothrottle continues to accelerate the aircraft making it practically impossible to perform this type of landing. The A32NX mod corrected this perfectly, perfectly in v1.70.XX, after all the updates, it seems, nobody can fix it.

Is it ok to land manually?

**Comment by Oberstumfuher** [comment] 2020-11-05 14:13
> > It is not the real behavior, flaps armed in full, the aircraft is with the bow slightly raised just to touch with the rear wheels and as soon as it loses speed the nose is lowered. The worst thing that is happening is with the autoland that is completely crazy, and apparently, nobody can fix it, the real behavior in autoland is the aircraft tilted backwards, nose up to the touchdown, where immediately the autopilot is disabled as well as the autothrottle is also disabled. What happens with the autoland now is the aircraft lowers its nose at the moment of landing and jumps, hitting the wheels more than 2 or 3 times while the autothrottle continues to accelerate the aircraft making it practically impossible to perform this type of landing. The A32NX mod corrected this perfectly, perfectly in v1.70.XX, after all the updates, it seems, nobody can fix it.
> 
> Is it ok to land manually?

Yes and no, it depends on the situation, I drove 747 for over 25 years and, as I said, it depends a lot on the airport, the runway, the weather conditions and so on. An aircraft is made for such a resource, since everyone wants to make a "game" as if it were in real life, yes, this resource must also be used. Microssoft and Assobo just want to put "products" to sell, but making a "game" in which they can call "simulator" is very far from that, nothing in Flight simulator can be compared to reality, both ATC phonetics, as for taxi, takeoff, puso, aircraft instrumentation everything is very badly done, there are only scenarios, and I believe that nobody who bought this "game" did it for the scenarios, am I correct or not?

**Comment by parker10101** [comment] 2020-11-05 14:34
> > > It is not the real behavior, flaps armed in full, the aircraft is with the bow slightly raised just to touch with the rear wheels and as soon as it loses speed the nose is lowered. The worst thing that is happening is with the autoland that is completely crazy, and apparently, nobody can fix it, the real behavior in autoland is the aircraft tilted backwards, nose up to the touchdown, where immediately the autopilot is disabled as well as the autothrottle is also disabled. What happens with the autoland now is the aircraft lowers its nose at the moment of landing and jumps, hitting the wheels more than 2 or 3 times while the autothrottle continues to accelerate the aircraft making it practically impossible to perform this type of landing. The A32NX mod corrected this perfectly, perfectly in v1.70.XX, after all the updates, it seems, nobody can fix it.
> > 
> > 
> > Is it ok to land manually?
> 
> Yes and no, it depends on the situation, I drove 747 for over 25 years and, as I said, it depends a lot on the airport, the runway, the weather conditions and so on. An aircraft is made for such a resource, since everyone wants to make a "game" as if it were in real life, yes, this resource must also be used. Microssoft and Assobo just want to put "products" to sell, but making a "game" in which they can call "simulator" is very far from that, nothing in Flight simulator can be compared to reality, both ATC phonetics, as for taxi, takeoff, puso, aircraft instrumentation everything is very badly done, there are only scenarios, and I believe that nobody who bought this "game" did it for the scenarios, am I correct or not?

It seems like Microsoft and asobo's expectation is not a simulator but a game. I'm waiting for the pmdg but it's delayed because of SDK. Microsoft and asobo did lots of wried things in 1.10 update. I'm quite disappointed honestly.

**Comment by Oberstumfuher** [comment] 2020-11-05 14:39
> > > > It is not the real behavior, flaps armed in full, the aircraft is with the bow slightly raised just to touch with the rear wheels and as soon as it loses speed the nose is lowered. The worst thing that is happening is with the autoland that is completely crazy, and apparently, nobody can fix it, the real behavior in autoland is the aircraft tilted backwards, nose up to the touchdown, where immediately the autopilot is disabled as well as the autothrottle is also disabled. What happens with the autoland now is the aircraft lowers its nose at the moment of landing and jumps, hitting the wheels more than 2 or 3 times while the autothrottle continues to accelerate the aircraft making it practically impossible to perform this type of landing. The A32NX mod corrected this perfectly, perfectly in v1.70.XX, after all the updates, it seems, nobody can fix it.
> > > 
> > > 
> > > Is it ok to land manually?
> > 
> > 
> > Yes and no, it depends on the situation, I drove 747 for over 25 years and, as I said, it depends a lot on the airport, the runway, the weather conditions and so on. An aircraft is made for such a resource, since everyone wants to make a "game" as if it were in real life, yes, this resource must also be used. Microssoft and Assobo just want to put "products" to sell, but making a "game" in which they can call "simulator" is very far from that, nothing in Flight simulator can be compared to reality, both ATC phonetics, as for taxi, takeoff, puso, aircraft instrumentation everything is very badly done, there are only scenarios, and I believe that nobody who bought this "game" did it for the scenarios, am I correct or not?
> 
> It seems like Microsoft and asobo's expectation is not a simulator but a game. I'm waiting for the pmdg but it's delayed because of SDK. Microsoft and asobo did lots of wried things in 1.10 update. I'm quite disappointed honestly.

I'm disappointed since I bought the FS, at the beginning it still looked better than it does now, v1.7X.XX, but with each update that is done they don't fix what they need and spoil what was good.

**Comment by Benjozork** [comment] 2020-11-05 16:07
Please limit off-topic discussion in GitHub issues. Thanks.

Yes, the A320 does push the nose down on landing to counter ground effect. It's an IRL thing. The problem here is not with the physics engine but rather with the fly-by-wire controls not giving you the necessary ability to flare. We are working on our own.

**Comment by Oberstumfuher** [comment] 2020-11-05 16:20
> Please limit off-topic discussion in GitHub issues. Thanks.
> 
> Yes, the A320 does push the nose down on landing to counter ground effect. It's an IRL thing. The problem here is not with the physics engine but rather with the fly-by-wire controls not giving you the necessary ability to flare. We are working on our own.

I find the work of all of you very commendable, considering that without FlybyWire it would be impossible of anything. What makes me the most angry is seeing Microsrossoft and Assobo launching updates that don't work and at the most spoil what was good. As soon as the FS was launched, the first aircraft I went to test was the 747, what a horror, a disappointment, the second was the A320, even worse, then I discovered your work, in version 0.1.0, if I'm not mistaken, it was salvation, even the autolanding was perfect, then Asobo updates came, they ruined everything and so far nothing has been fixed, every update is a pain. The good thing about this is that there are people like you, programmers, who are trying to fix the work that should be from these two big companies.

**Comment by Rameyuk** [comment] 2020-11-06 02:19
The Nose down pitch only occurs if you keep the Autopilot on just before touch down (around 50 ft, I think). My observation is that it looks like on autopilot approach, the aircraft is trying to “chase” the glideslope magenta diamond that drops down as you fly over the runway. So the aircraft chases this diamond down resulting in a sharp downward pitch.

After my friend (who is using the stable 0.4.1 version, while I always keep my development version updated) reported this issue on autoland, I did several experiments using the same airport, same runway, and the same approach, one on full autolanding procedure, the other with an “assisted” flare. Both cases experience the nose diving behaviour, the autoland is the worst because the nose down resulted in a nose wheel landing which will bounce the aircraft hard.

The assisted flare is less severe, but the I end up trying to “fight” the autopilot for the control of the nose, which is also resulted in a bouncy landing, albeit slightly less so.

So I can confirm this two experiment that the nose dive bug does indeed happen. But then I did a third experiment, by approaching the same airport, same runway, and same approach, but using a technique that I’ve always been using myself. full automated approach, but disengage AP at 100 ft callout, then prepare to retard the thrust lever and manual flare at 50 ft or below.

The third experiment was a success, I did not experience the nose diving bug, and when I disengage AP at 100 ft, I have full control over my aircraft so it won’t try to “chase” the glideslope magenta diamond and instead descend straight in for a manual flare and smooth touchdown.

As long as you disengage the AP before the nose dive kicks in (which generally happen between 100-50ft), you should be good. I think this is an Asobo ILS/autopilot issue, and not A32NX mod issue.

**Comment by collinbrady** [comment] 2020-11-06 05:14
Confirmed as a major issue as well. It seems the only workaround for now is to disengage autopilot well above ~50ft. So much for auto CAT III landings.

**Comment by donstim** [comment] 2020-11-06 06:55
Autoland was not implemented in any version of either the vanilla Asobo A320, nor the A32NX mod.  It sounds like it has gotten much worse, but why do people keep trying to use a capability that simply does not exist? It is not a workaround to disengage the autopilot prior to landing; it is the only procedure currently implemented.

**Comment by Oberstumfuher** [comment] 2020-11-06 10:40
> Autoland was not implemented in any version of either the vanilla Asobo A320, nor the A32NX mod. It sounds like it has gotten much worse, but why do people keep trying to use a capability that simply does not exist? It is not a workaround to disengage the autopilot prior to landing; it is the only procedure currently implemented.

I can guarantee that in version 1.7XX, the first one launched, with the A32nx, it worked perfectly, because I used it a lot

**Comment by collinbrady** [comment] 2020-11-06 18:53
It did work before - maybe it wasn't "fully implemented", but I used it on a few landings where I little to no visibility which would be almost impossible now with the way the nose throws itself into the core of the planet.

**Comment by NickyNiclas** [comment] 2020-11-06 22:53
It did autoland in previous versions but the AP disengaged as soon as tires hit the ground. It's supposed to stay engaged for rollout. It was also landing very hard without flare. Now it tries to slam the front gear into the ground, actually scary!

**Comment by ElSrJuez** [comment] 2020-11-07 23:34
Interesting that the fundamental question if the Neo even features this (or not) is alive here, on official and other forums.

I would love that somebody with inside knowledge of the code, would confirm of deny if the Asobo and/or A32NX actually has AUTOLAND logic including FLARE. 
Only then can there be a discussion with regards on how accurate it may be?

In my experience, the Asobo Neo on ILS only guides the AP to bring the plane to the piano keys in a reasonably smooth and precise way, after that it behaves pretty much like a winged brick. 
The A32NX I was under the impression flies at that phase exactly the same but has some extra landing indicators on the displays, but again, I thought they were only cosmetic?

**Comment by Benjozork** [comment] 2020-11-07 23:42
For reference, the actual fly-by-wire code is exactly the same using the mod or not.

**Comment by Oberstumfuher** [comment] 2020-11-08 00:42
> Interesting that the fundamental question if the Neo even features this (or not) is alive here, on official and other forums.
> 
> I would love that somebody with inside knowledge of the code, would confirm of deny if the Asobo and/or A32NX actually has AUTOLAND logic including FLARE.
> Only then can there be a discussion with regards on how accurate it may be?
> 
> In my experience, the Asobo Neo on ILS only guides the AP to bring the plane to the piano keys in a reasonably smooth and precise way, after that it behaves pretty much like a winged brick.
> The A32NX I was under the impression flies at that phase exactly the same but has some extra landing indicators on the displays, but again, I thought they were (at least for now!) only cosmetic?

When the aircraft is fully adjusted for landing, that is, full flap, when starting the descent in the GS the aircraft already takes the position of FLARE, it raises its nose, and thus remains until the touch, initially with the wheels of the wings, at that moment the autopilot turns off, the A / THR disarms, as soon as it touches the nose with the ground the autobrake goes into action, detail, the autobrake only fulfills its function with all wheels on the ground, and the reverse is activated. How to program this I don't know, I'm not a programmer, unfortunately, I was only a 747 pilot for over 25 years, the attitude of the aircraft I can say how it is, maybe there is something different about the Airbus, but nothing that is absurd, because it is an aircraft too and the landing by instruments, autoland, is a fundamental piece, because it is not always all sun and without clouds or wind. The mood changes in the blink of an eye.

**Comment by donstim** [comment] 2020-11-08 07:27
This is from a post in the official MSFS forum:
Asobo Clearly stated in the last dev q&a that the a320 FBY system is not implemented correctly. The difficult landings are due to the fly by wire nature system that is partially implemented in the sim. To make what in general aviation terms the flare stage (because flare mode of the a320 is something different) of the landing possible Asobo deactivate the ELAC (elevator and aileron control computer) so as to allow you to flare, if not the ELAC would think that you were trying to stall the aircraft and thus not pitch up resulting in a 500fpm landing or a crash if you prefer. Unfortunately, it seems to me that the ELAC controls the trim as well and if you have your trim assigned to an axis a controller, as the ELAC is switched off at 50ft your last trim setting comes into play usually causing a sharp pitch change, (not helpful 50ft from the ground) and rendering the elevators and ailerons extremely sensitive sometimes causing a roll as well.

**Comment by Pilot747-hub** [comment] 2020-11-09 12:40
> > Autoland was not implemented in any version of either the vanilla Asobo A320, nor the A32NX mod. It sounds like it has gotten much worse, but why do people keep trying to use a capability that simply does not exist? It is not a workaround to disengage the autopilot prior to landing; it is the only procedure currently implemented.
> 
> I can guarantee that in version 1.7XX, the first one launched, with the A32nx, it worked perfectly, because I used it a lot

I can confirm that. Worked like charm.

**Comment by Benjozork** [comment] 2020-11-09 12:50
I'm going to clarify some things here.

1. We did not edit the autopilot, and specifically did not edit autoland capabilities
2. The autoland is completely implemented by Asobo and only they can fix it right now
3. We are working on our own autopilot that will solve this issue. Stay tuned :)

**Comment by Pilot747-hub** [comment] 2020-11-09 12:54
> I'm going to clarify some things here.
> 
> 1. We did not edit the autopilot, and specifically did not edit autoland capabilities
> 2. The autoland is completely implemented by Asobo and only they can fix it right now
> 3. We are working on our own autopilot that will solve this issue. Stay tuned :)

Thank you very much! You guys are doing an awesome job! Cheers!

**Comment by Oberstumfuher** [comment] 2020-11-09 12:57
> I'm going to clarify some things here.
> 
> 1. We did not edit the autopilot, and specifically did not edit autoland capabilities
> 2. The autoland is completely implemented by Asobo and only they can fix it right now
> 3. We are working on our own autopilot that will solve this issue. Stay tuned :)

This is exactly what I expect from the team, because if you wait for Asobo it will never be solved, it is the same thing as putting a bricklayer to program a "flight simulator" I am sorry to say, but a team that is working for more than 6 years in a simulator and cannot replicate an autopilot, which is one of the main flight systems of an aircraft, should not have accepted this type of service, it would be more coherent to say that they do not understand anything about flight systems. And I'm sure the Fly By Wire team will show Asobo how it's done. Spending money on a "simulator" that simulates nothing, only disasters, in my opinion, I threw money away.

**Comment by AdamNZ** [comment] 2020-11-09 13:01
Give them a bit of leeway! I think it's been stated in some other thread (somewhere) that France is in lockdown and many of the Asobo developers are isolated and are trying to work from home.

**Comment by lve0200** [comment] 2020-11-15 11:49
> Autoland was not implemented in any version of either the vanilla Asobo A320, nor the A32NX mod.

The question then is, why does the AP follow the autoland procedure? It switches correctly from G/S to Land and onto Flaire? 4me, just the implementation is messy.

**Comment by lve0200** [comment] 2020-11-15 11:55
> Unfortunately, it seems to me that the ELAC controls the trim as well and if you have your trim assigned to an axis a controller, as the ELAC is switched off at 50ft your last trim setting comes into play usually causing a sharp pitch change,

I cannot confirm this. 
I did a few circuits in EDDH ILS23 in "clear skies 272/2". I set my controls trim wheel to maximum **up** during flight, which was compensated by the AP.  In the moment it switched to "Flair" the trim was changed to - 1.7 from +3.x on G/S, resulting in a brutal nose down. I repeated the same flight w/ trim "neutral" on my controls and saw the same behavior.

**Comment by lve0200** [comment] 2020-11-15 14:25
Just to complete the picture; I did a few "manual" landings, taking control between 100 and 200 ft. I switched the AP off, using the mouse, no touching the Stick to avoid any interference. First, the change of trim from 3,3 up to -1.7 DN at 50 ft also happens when the AP is OFF! Second, there's a significant difference. While in manual mode, the trim is **_spooled continously down_** during the whole flair, while in autoland, the value **_flips_** from 3.3 @ 50ft to 0 and then decreses to -1.7. IMHO that's the issue.

**Comment by lve0200** [comment] 2020-11-15 16:32
YES, it can.... flaire...

Well, after I found that autoland is out of play, I could not resist fooling arond w/ "flight_model.cfg" to see, if I could get a better flaire when landing manually. I don't want to advertise this here as A solution, more like a hint to those who know, rather than me, shooting into the dark. But I got a nice flaire...
So I had a look at this file in particular the tag under [AERODYNAMICS]
 lift_coef_ground_effect_mach_table = 0.027:1.25 
Since it mentiones "mach" and "lift" I guess the 0.027 is speed and 1.25 is the uplift. However 0.027 mach == 18 Kts?? What sense makes this?? So I set it to 0.19:1.25 == 125 Kts. 
Well I felt it was a nice flair, but a bit too much uplift.
Finally I spent 2 points for the curve, slightly decreasing speed and uplift for the 2nd point: 0.19:1.2, 0.15:1.1
OK, was good enough for me.

Greetings from an old German engineer, on a rainy idle Sunday in French lock down (Bordeaux)

**Comment by Oberstumfuher** [comment] 2020-11-15 16:55
All of you are right, but you are forgetting one very important thing, when you activate the approach mode on the MCDU the behavior of the aircraft changes completely. In reality the function of FLAPS during a landing is precisely to increase the drag of the aircraft, with the armed FLAPS, the PITCH stops sinking the nose of the aircraft, because, when activating the approach mode, it understands that you want to land, so the PITCH's attitude is another: he leaves the aircraft at about 10 degrees with his nose up during the entire approach, descent and touch the runway. At the exact moment of touch the AUTOPILOT is deactivated, the pilot places the THROTTLE in IDLE, letting the aircraft roll and lower the nose naturally with the loss of speed, then the reverses are used, if necessary, and only with all wheels in contact with the ground is that the BRAKES will take action.

Angle of descent of the aircraft to the ground

[https://imgur.com/rL2gL0o](url)

**Comment by donstim** [comment] 2020-11-15 17:10
The prime function of flaps on a transport category airplane is to increase lift, not drag, in order to allow slower landing speeds. And the pitch attitude of an A320 is 2.5-3 degrees on approach at Vapp, not 10, increasing to around 4 at the threshold at Vref.

**Comment by Oberstumfuher** [comment] 2020-11-15 18:24
> A função principal dos retalhos em um avião de categoria de transporte é aumentar o elevador, não arrastar, a fim de permitir velocidades de pouso mais lentas. E a atitude de arremesso de um A320 é de 2,5-3 graus na aproximação em Vapp, não 10, aumentando para cerca de 4 no limiar em Vref.

Not in the approaching phase, I was a 747 pilot for 25 years, in real life, not in Flight simulator.

**Comment by lve0200** [comment] 2020-11-15 18:49
Dear Sir,
you may be a 747 pilot, serving for 25 years, but the A320 is not a 747. So 10° for 747 and 3 for A320,; so what's the issue?
Second, 
being German, who's Dad was called into war at the age of 17, your pseudonym "Oberstumfuher", probably you meant "Obersturmführer" touches me very negatively. The rank of Obersturmführer was a Nazi SS rank, responsible for the most cruel war crimes, committed by the Nazi regime.
https://en.wikipedia.org/wiki/Obersturmf%C3%BChrer
I don't find this very appropriate in this forum.
RGDS
Hans Kurscheidt

**Comment by donstim** [comment] 2020-11-15 18:52
Is it a translation issue? Because what you stated was absolutely incorrect. With a 10 degree pitch angle you would not even have a view of the runway and may be in alpha protect mode.

The 747 did/does not approach at pitch angle of 10 degrees either. Even 6 degrees would be high. 

I can only assume there must be some translation problem. As an airplane performance engineer for 40 years, my biggest pet peeve is people providing incorrect/false airplane performance information. Please don't do that.

**Comment by NickyNiclas** [comment] 2020-11-15 18:54
Yeah guys, pitch angle vs angle of descent is two separate things. Don't confuse the two.

**Comment by donstim** [comment] 2020-11-15 19:14
10 degrees pitch on 747?  
![Screenshot (289)](https://user-images.githubusercontent.com/70166617/99194232-0a075480-2733-11eb-8605-9714085c556e.png)

Thanks Nicky, it appears our 747 pilot does not know the difference. His figure clearly shows pitch angle, as does his description, but then he refers to angle of descent and ILS glide paths. He also shows a blatant disregard for history as Hans has shown. I will no longer attempt to communicate with him.

**Comment by Oberstumfuher** [comment] 2020-11-15 19:16
> Dear Sir,
> you may be a 747 pilot, serving for 25 years, but the A320 is not a 747. So 10° for 747 and 3 for A320,; so what's the issue?
> Second,
> being German, who's Dad was called into war at the age of 17, your pseudonym "Oberstumfuher", probably you meant "Obersturmführer" touches me very negatively. The rank of Obersturmführer was a Nazi SS rank, responsible for the most cruel war crimes, committed by the Nazi regime.
> https://en.wikipedia.org/wiki/Obersturmf%C3%BChrer
> I don't find this very appropriate in this forum.
> RGDS
> Hans Kurscheidt

Furthermore, your math and that of your friend, which you are defending, leaves something to be desired. I will draw for you to understand.
If you are descending at an angle of 3 degrees and raise the nose of the aircraft by 3 degrees how many degrees are you both ?? Answer = 0 degrees, that is, your aircraft will land with all the wheels at the same time on the ground, on your stomach. If the aircraft is at a maximum of 4 degrees from the A320, which your colleague said, this A320 will settle with just 1 degree of raised wing, that is, another disaster. Did the girls now understand why 10 degrees, or do they need to go back to school? And as for my username Oberleutnant is a PATENT PATENT, and it has nothing to do with Nazism, but one thing for you to go back to school, I'm sorry to tell you, but you and your friend are people who don't understand anything, either aviation and "military patents".

**Comment by Oberstumfuher** [comment] 2020-11-15 19:21
> 10 degrees pitch on 747?
> ![Screenshot (289)](https://user-images.githubusercontent.com/70166617/99194232-0a075480-2733-11eb-8605-9714085c556e.png)
> 
> Thanks Nicky, it appears our 747 pilot does not know the difference. His figure clearly shows pitch angle, as does his description, but then he refers to angle of descent and ILS glide paths. He also shows a blatant disregard for history as Hans has shown. I will no longer attempt to communicate with him.

I said on the descent and I repeat again, an ILS of 3 degrees, right? if you descend with a 3 degree nose up, how many degrees will you actually be in ?? 0 degrees, because 3 descent plus 3 above is zero. and for you to arrive with those 4 nose elevations on the runway, in reality your descent was 7 degrees, for an ILS of 3 degrees of inclination, now try to land, according to your understanding on a runway with an ILS of inclination of 6.65 degrees??? How many degrees will the nose of your aircraft have to stay to reach the ground with 4 degrees ??

**Comment by lukecologne** [comment] 2020-11-15 19:36
Alright, this thread has gone way offtopic, locking until we discussed further actions

**Comment by MisterChocker** [comment] 2020-12-31 05:33
Custom FBW has taken care of this.

**Closed by MisterChocker** 2020-12-31 05:33 UTC
Labels: Bug
