### ISSUE TITLE
[BUG] Lowing alt while in VS mode shouldn't reset VS mode

### ISSUE THREAD

**Issue by ktechmidas** [flybywiresim/a32nx#2211] opened 2020-12-03 17:56 UTC
**Mod Version**
{
  "built": "2020-12-03T06:03:11+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**
If I'm descending in VS mode to FL250 then get given a new alt by ATC (eg FL200) I should be able to move the alt knob down to FL200 without clearing VS mode. Instead it clears VS mode and either goes into ALT HOLD or OP DES

**To Reproduce**
1. Fly at cruising alt and configure the plane to start descending in VS mode
2. Descend at 1200 ft/m in VS mode with 25000 on the MCP alt knob
3. As you're descending through FL270 put 20000 in the MCP alt knob
4. VS mode is cleared as soon as you touch the alt knob.

**Expected behavior**
The plane should continue to descend at 1200ft/m and it should stay in VS MODE until it reaches the new ALT. Note it never reached the old ALT 

To be clear, if it reached the old one (FL250) I'd expect it to go ALT HOLD until I tell it to descend again but if I reset the MCP alt while it's still descending to FL250 to FL200 it shouldn't cancel VS 

**Actual behavior**
Either OP DES or ALT HOLD and VS MODE is cleared

Was this working before/when did the issue start occurring? Not sure

Is this a problem in the vanilla unmodded game? Not Sure

Discord username (if different from GitHub): latteisnotcoffee#2769

**Comment by Benjozork** [comment] 2020-12-03 19:50
Please provide the contents of the `build-info.json` file present in your Community/A32NX folder in **Mod version** as required in the template.

**Comment by ktechmidas** [comment] 2020-12-04 09:07
Done :)

**Comment by MisterChocker** [comment] 2020-12-31 06:40
duplicate of #1134

**Closed by MisterChocker** 2020-12-31 06:40 UTC
Labels: Bug
