### ISSUE TITLE
Ignores constraints in SID

### ISSUE THREAD

**Issue by Captherky** [flybywiresim/a32nx#2170] opened 2020-12-01 20:01 UTC
Ignores SID constarints

**Mod Version**

{
  "built": "2020-12-01T17:45:57+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**

Take off EGKK on SID LAM2X. Set initial alt at 110, as per clearance instructions. Constraints on FP are 5000', 6000'. The Managed altitude mode ignores the constraints and flies through the constraint altitude of 5000'., causing ATC to ask for a descent to constraint altitude! 

**To Reproduce**

1. Take off with a SID in FP with constraints.
2. Set inital altitude in window to cleared altitude...110. ( in the case of EGKK )
3. The Neo climbs in MANANGED MODE!!! Through the constraints and on to the alt set in alt window. In OTHER WORDS, its ignoring the constarints and climbing as if you've selected Commanded altitude and not Managed altitude!

**Expected behavior**

The Neo should halt at the constraint altitde and NOT exceed it! In Managed mode!

**Actual behavior**

Neo ignores the constraint and climbs to the set altitude as if in commanded mode.

**References**

I have videos but you have the issue!

**Additional context**

Looks like the managed mode is ignored and only commanded mode is used?

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment] 2020-12-01 20:17
Have you set a CRZ FL in INIT-A? If not AC transitions into CRZ after TO and this PHASE will ignore all alt constraints.

**Comment by MisterChocker** [comment] 2020-12-01 20:29
The constraint on your SID are not limiting climb performance they are `AT OR ABOVE`.
This is normal and intended behavior.

![image](https://user-images.githubusercontent.com/1857322/100793297-3225d180-341c-11eb-8cca-e1a7e9b390cc.png)
![image](https://user-images.githubusercontent.com/1857322/100793353-41a51a80-341c-11eb-96da-1c18cce07369.png)

No bug.

**Comment by Captherky** [comment] 2020-12-01 21:18
yes

**Comment by Benjozork** [comment] 2020-12-01 21:46
Closed as working as intended

**Closed by Benjozork** 2020-12-01 21:46 UTC
Labels: Bug
