### ISSUE TITLE
[BUG] Everything turns off randomly during CRZ

### ISSUE THREAD

**Issue by salik1992** [flybywiresim/a32nx#1228] opened 2020-10-09 20:15 UTC
**Mod Version**
Release v0.3.1

**Describe the bug**
After performing cold/dark start, climb and reaching the cruise altitude the plane sometimes randomly turns off completely (engines, avionics, electronics). There is no warning/caution beforehand. 

After it happens, clicking on batteries no longer turns battery power on like in similar issues happening right after spawning on the ground. 

Closest issue I found is [#884](https://github.com/flybywiresim/a32nx/issues/884). But unlike in that issue it happens seemingly randomly at different points of the way or not at all on the same route. 

**To Reproduce**
Not really sure. I had the issue happening sometimes on the routes LKTB-->LPMA or LOWW-->EHAM. Even using the same departures, arrivals and approaches does not guarantee it happening. 

**Expected behavior**
Expecting the plane not to turn off completely mid-flight.

**Actual behavior**
See bug description. 

**References**

**Additional context**
- Traffic OFF
- Multiplayer OFF
- Weather LIVE
- Route calculated by sim
- Liveries max pack installed

Was this working before/when did the issue start occurring? 

First time observed was with game v1.9.3.0 and mod release v0.3.1

Is this a problem in the vanilla unmodded game?

I haven't experienced this issue with vanilla version.

**Comment by lousybyte** [comment] 2020-10-09 20:19
Might be related #1115.

**Comment by salik1992** [comment] 2020-10-09 20:47
[#1115](https://github.com/flybywiresim/a32nx/issues/1115) the behaviour is not like that one. This one is sudden and like in 1 frame everything is fine, next frame everything is off and engine's sound goes down as a result of everything turned off. 

Furthermore nothing in the cockpit works after that. No battery power, no APU.

**Comment by Benjozork** [comment] 2020-10-09 20:49
I can confirmed I have seen this issue myself. I have all traffic turned off, but was playing multiplayer.

**Comment by MisterChocker** [comment] 2020-10-09 22:19
> **Additional info**
> I've just had this happened again on final at 900ft. And there was a lightning at the exact moment. I'm not even sure whether lightning strikes are simulated/possible and could cause this. Or whether it is just a coincidence. I've been seeing lightnings everywhere I fly since 1.9.3.0.

lightning strikes are not danger to airplanes.

**Comment by jokey2k** [comment] 2020-10-10 14:41
> > **Additional info**
> > I've just had this happened again on final at 900ft. And there was a lightning at the exact moment. I'm not even sure whether lightning strikes are simulated/possible and could cause this. Or whether it is just a coincidence. I've been seeing lightnings everywhere I fly since 1.9.3.0.
> 
> lightning strikes are no danger to airplanes.

But maybe their simulation is. Same here during approach at around 2000ft to KLAX.

**Comment by hotshotp** [comment] 2020-10-10 17:23
> > > **Additional info**
> > > I've just had this happened again on final at 900ft. And there was a lightning at the exact moment. I'm not even sure whether lightning strikes are simulated/possible and could cause this. Or whether it is just a coincidence. I've been seeing lightnings everywhere I fly since 1.9.3.0.
> > 
> > 
> > lightning strikes are no danger to airplanes.
> 
> But maybe their simulation is. Same here during approach at around 2000ft to KLAX.

No it happened to me with clear skies

**Comment by christertepper** [comment] 2020-10-11 20:09
I'm having this same issue- try to recreate it but it happens at various stages of flight.  Last three times it occurred about 3 mins after takeoff.  Weather is live- thunderstorms in the area, also running PACX and FS2Crew.  Not sure if running the extra apps has anything to do with is, as I have tried flights without them and same problem happened- everything just turns off in a split second and completely unable to restart engines, batteries or anything else- enter an unrecoverable stall.  Very frustrating especially when you're about 5 minutes away from landing...

**Comment by SeanHanway** [comment] 2020-10-11 21:11
Starting to run into this issue in every flight now. It always starts with engine 1 shutting down for me though. I've got the latest development branch from the A32NX downloader.

**Comment by MisterFoxi** [comment] 2020-10-13 08:29
I have the same issue and was able to reproduce it regularly. It seems happening, for me, almost at the same timeframe after take-off, usually 20minutes. 

Here is a save i made few minutes before the crash, heading toward LIMJ
[LocalState.zip](https://github.com/flybywiresim/a32nx/files/5369964/LocalState.zip)

**Comment by NathanInnes** [comment] 2020-10-16 18:31
Anything improved with our latest release or is this still an issue?

**Comment by MisterFoxi** [comment] 2020-10-17 06:47
Yes, all fine for that one.
Thx

**Comment by jokey2k** [comment] 2020-10-17 18:20
I think so too, been unable to reproduce it

**Comment by NathanInnes** [comment] 2020-10-17 19:14
Unable to reproduce also, closing issue. If this still persists then feel free to reopen.

**Closed by NathanInnes** 2020-10-17 19:14 UTC
Labels: Bug
