### ISSUE TITLE
[REQUEST] Transition altitude preference in MCDU otions

### ISSUE THREAD

**Issue by bdpd1** [flybywiresim/a32nx#2813] opened 2020-12-30 18:30 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the feature you'd like to see implemented**
In the same menu as fuel units please add a preference for transition altitude for those countries / regions where it is the same everywhere 
Have this preferred transition altitude populate the PERF pages for Takeoff and approach (i.e will always populate FL180 for North America)

**References**
Not applicable 

**Additional context**
Not applicable 

Discord username (if different from GitHub): nnumber

**Comment by Benjozork** [comment] 2020-12-30 18:30
Hello, this is being worked on by @Kimbyeoungjang and @nistei. Stay tuned.

**Comment by bdpd1** [comment] 2020-12-30 18:41
Great news !

**Comment by Kimbyeoungjang** [comment] 2020-12-31 06:11
yes almost done :) please wait!

**Comment by beheh** [comment] 2021-02-01 14:55
Duplicate of #2572.

**Closed by beheh** 2021-02-01 14:55 UTC
Labels: Enhancement
