### ISSUE TITLE
Airline Call Sign & Flight Number Not Being Used By ATC

### ISSUE THREAD

**Issue by stubbyswiss** [flybywiresim/a32nx#1796] opened 2020-11-08 02:02 UTC
**Mod Version**

built: 2020-11-07T21:16:46+00:00
ref: refs/heads/master
sha: 3dd9cf63ed0f04f8eb95041ec719447dc303f171
actor: Benjozork
event_name: push

**Describe the bug**

Using the last 2 dev. versions, when I enter an Airline call sign and flight number into the world map flight set up, and then I actually press Fly Now to enter the sim, I am finding that ATC only refers to me by 'Airbus + Tail number'. This was not so prior to these 2 updates, and it is not so when I remove the A32NX folder from my community folder. Without the A32nx folder in my community folder, ATC refers to me correctly by my airline call sign and flight number.

**To Reproduce**

1. Open up MSFS2020 with the latest A320NX dev. version installed.
2. Go into the World Map and select the Airbus, and set up a flight, entering a departure and arrival airports, and a departure airport gate, so as to start cold & dark.
3. In the ATC Options, enter a Tail Number, Call Sign and Flight Number.
4. Hit the 'Fly' button and enter the sim proper.
5. Power up the a/c with external power and/or APU and contact ATC for clearance.

**Expected behavior**

I expect ATC to refer to me by the Call Sign and Flight Number that I enter in the World Map page.

**Actual behavior**

ATC refers to me as 'Airbus + the Tail Number' I entered in the World Map.

**References**

N/A

**Additional context**

N/A

Was this working before/when did the issue start occurring?
Yes, this was working before the last 2 dev updates.

Is this a problem in the vanilla unmodded game?
No, it is not. It works correctly in the unmodded game.

Discord username (if different from GitHub):
stubbyswiss#3544

**Comment by stubbyswiss** [comment] 2020-11-08 02:09
I see this has already been reported, probably as I was typing up my own report. Please disregard this as a duplicate report.
Thank you.

**Comment by wpine215** [comment] 2020-11-08 02:20
If you enter a flight number in the MCDU, does ATC use that once it's been inputted?

**Comment by Benjozork** [comment] 2020-11-08 02:33
Duplicate of #1975

**Closed** 2020-11-08 02:33 UTC
Labels: Bug
