### ISSUE TITLE
Minimums value "out of range"

### ISSUE THREAD

**Issue by Nyxtorm** [flybywiresim/a32nx#5749] opened 2021-08-29 20:14 UTC
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2021-08-26T10:35:24+00:00",
  "ref": "experimental",
  "sha": "14a5718876e99aefde0a96682f609f7dc2e82b99",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

When I was scheduling an RNAV approach on GMMX, runway 28, I could not enter a value less than 1268 for the MDH. The chart showed an expected value of 445.

### Expected behavior

It seems to me that I should be able to enter 445 feet for the MDH.

### Steps to reproduce

1. Program an RNAV approach on GMMX runway 28

### References (optional)

![image](https://user-images.githubusercontent.com/20800786/131264039-5ab200a8-d448-4043-9c9d-81691a1c98b4.png)
![baromin1268](https://user-images.githubusercontent.com/20800786/131264082-42a391af-9040-4781-a953-be6fdfd6e5ca.png)

My flight plan : 

EDLW/24 BAMSU2U BAMSU DCT MODRU Z283 LNO M170 KUDIN UM170 RAPOR
UN857 DIRMO UZ365 GUERE UN860 AGN UN869 NASOS UL27 BLN UN869 MGA
UM985 PIMOS UN869 SLK UB11 PELAX UN869 MABAP B11 MAK DCT GMMX/28

### Additional info (optional)

Sorry for my English.

**Comment by BlueberryKing** [comment] 2021-08-29 20:27
The BARO field refers to a barometric altitude above sealevel, not a height above the ground (this would be RADIO). You should therefore enter the value of 1990. 445 is out of range because the airport is at 1545 ft above sealevel.

**Comment by MisterChocker** [comment] 2021-08-29 20:29
Closing since working as intended.

**Comment by Nyxtorm** [comment] 2021-08-29 20:30
@BlueberryKing Indeed, now that you mention it, it seems logical and it was indeed a mistake on my part, thank you for this clarification. 😅

**Closed by MisterChocker** 2021-08-29 20:29 UTC
Labels: Bug
