### ISSUE TITLE
[BUG] no index displayed in IAS speedometer of PFD

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#1690] opened 2020-11-01 11:43 UTC
**Mod Version**

V0.4.1

**Describe the bug**

With last update of FS2020 and with modd, I don't see anymore index forrotate velocity.

**To Reproduce**

1. Start up fs2020. I use load flight plan from simbrief
2. On runway, no index are displayed on IAS meter
3.

**Expected behavior**

Add index for V1, V2 and VR

**Actual behavior**

No index

![97805335-bc301e00-1c55-11eb-8a16-735f45b7fe87.jpg](https://user-images.githubusercontent.com/4503241/97806735-1a93d700-1c2b-11eb-9e43-c5dd911ac189.jpg)

**References**

**Additional context**

Was this working before/when did the issue start occurring?
working before fs2020 update

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by JLD95** [comment] 2020-11-01 14:20
![2020-11-01 (11)](https://user-images.githubusercontent.com/5894146/97805335-bc301e00-1c55-11eb-8a16-735f45b7fe87.jpg)

**Comment by Benjozork** [comment] 2020-11-01 15:14
Might wanna remove this

> BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

**Comment by Benjozork** [comment] 2020-11-01 15:15
Have you properly set your Vspeeds in the mcdu ?

**Comment by JLD95** [comment] 2020-11-01 15:46
No specified Vspeeds in MCDU like before.

**Comment by lukecologne** [comment] 2020-11-01 15:50
Well that's not how it works. If you don't give the FMGC VSpeeds, then obviously there will be none to display on the PFD. Closing as this is not a bug.

**Closed by lukecologne** 2020-11-01 15:50 UTC
Labels: Bug

**Comment by JLD95** [comment] 2020-11-01 18:07
Thank you. A Vspeeds calculator is planned on EFB?
