### ISSUE TITLE
[BUG] strange rudder behaviour / Rudder don´t work

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2768] opened 2020-12-28 08:56 UTC
**Mod Version**

Master (FBW)

**Describe the bug**

The last two flight I recognise a strange Rudder bahaviour. The first flight, I wasen´t able to move the rudder from the beginning, and the secound flight, the issue startet after landing.
The Problem:
Rudder moves the first millisecounds of input, then it returns to NEUTRAL. 
I use the Airbus Stick, with proper deadzone set (4%), and all values recommenced for the FBW mod. 
sometimes it happend, sometimes not, with the same settings. I make 4 Flight today, 2 with this issue, 2 with normal rudder bahaviour. 
I know, in that way hard to reproduce, but i only want to state it here.

**To Reproduce**

1. start a flight from Cold and dark
2. sometimes the issue is from beginning, or sometimes after/inflight/after landing
3.

**Expected behavior**

rudder should move

**Actual behavior**

rudder only move with the first millisecounds of input, then it returns to NEUTRAL

**References**

-

**Additional context**

Was this working before/when did the issue start occurring?
yes
Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):

**Comment by mikecbr** [comment] 2020-12-28 10:07
yepp , same issue here. After landing , its impossible to land with crosswinds.....

**Comment by Rameyuk** [comment] 2020-12-28 10:52
I've investigated this issue some more and I can confirm that the root cause here is the A/THR button. If you have it on, you will have rudder issues as described. Turn off the A/THR and you will have full rudder control.

So when you're taxiing on the ground, don't engage A/THR and you should turn just fine. Let it automatically engage when you're rolling out for take off. Similarly, after landing, turn off the A/THR and you should be able to taxi out and to the gate without issue as well.

Perhaps the FBW team can investigate why the rudder control is affected by the A/THR on or off.

**Comment by andrejetcat** [comment] 2020-12-28 11:19
@Rameyuk thank you for this explaination, but the issue occurs both times with A/THR off. First time, after push back/from the beginning of the flight, until there, A/THR wasen´t enabled at all.
Thank you for you help! You do an awesome job here!

**Comment by FRYYYYYY** [comment] 2020-12-28 13:01
I have the same problem and was able to reproduce it. As soon as the engines are running at <=20% I can't steer anymore, as soon as they are greater than 20% it works again.

**Comment by BobbyFuzzy** [comment] 2020-12-30 13:10
I also have this issue. Using the Custom FBW version of the mod. TM Airbus Sidestick & Quadrant. All settings as per the readme page. Not able to use NW steering on ground (not tried using rudder in air). Usually occurs after landing, not had chance to test @FRYYYYYY's theory although this makes sense as to why you would only notice it after landing in normal operation. [Here is a short video](https://streamable.com/d3lv52) of what happens shortly after landing.

**Comment by Rameyuk** [comment] 2020-12-30 16:24
> I also have this issue. Using the Custom FBW version of the mod. TM Airbus Sidestick & Quadrant. All settings as per the readme page. Not able to use NW steering on ground (not tried using rudder in air). Usually occurs after landing, not had chance to test @FRYYYYYY theory although this makes sense as to why you would only notice it after landing in normal operation. [Here is a short video](https://streamable.com/d3lv52) of what happens shortly after landing, note - I am moving my rudder pedals and holding in that direction here, as you can see the rudder moves for a split second then returns to neutral.

Yes, the current workaround is, when you land, make sure the A/THR is switched off, and you should have full rudder control again. Same with taxiing out from the gate, make sure the A/THR is off to have full rudder control.

**Comment by BobbyFuzzy** [comment] 2020-12-31 00:24
@Rameyuk Got it, thanks. Seems to be fixed as of today A/THR is no longer enabled on the ground.

**Closed** 2021-02-03 23:59 UTC
Labels: Bug
