### ISSUE TITLE
DOC: LVAR and Events for 3rd party tools/hardware

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#4392] opened 2021-04-10 22:41 UTC
**Is your feature request related to a problem? Please describe.**
Trying to make my Logitech Switchpanel and Multipanel fully work with the FBA A32NX. But this request is for other tools and hardware as well. I'm not sure if this is a enhancement request as these things are not yet implemented or a documentation bug report as they are but not sufficiently documented. 

**Describe the feature you'd like to see implemented**
I propose a documentation page with a table listing the FBW A320neo buttons/lights/display and how they can be read, written or triggered.

Currently this is a lot is trial and error without knowing the inner workings of the FBW A32NX.
I'm happy to be available for further information and also testing. 
EDIT: Also happy to help writing this :)

Discord username (if different from GitHub): Cdr_Maverick

**Additional context**
Below my current Logitech Switchpanel and Multipanel Status Quo (experimental version):

FlyByWire A320neo (A32NX)) for MSFS2020
Switch Panel
Working / Extra:
•	MAGNETO SWITCH Position R is used for "EXTERNAL POWER ON"
•	MASTER ALT: turns on both engine generators
•	AVIONICS: turns on avionics (necessary for Multipanel) and also switches on all 3 ADIRS 
(ADIRS are not switched off again - this is intentional)
•	FUEL PUMP: switches all 6 pumps
•	DE-ICE: swtiches WING and ENG 1+2 ANTI_ICE
•	PITOT HEAT: switches PROBE/WINDOW HEAT manually ON (not necessary as A320n does this automatically)
•	COWL SWITCHs: dome light ON/OFF
•	PANEL: turns on/off OVHD panel inegrated lights (need to turn to full in plane first)
•	NAV: Nav lights
•	STROBE: Strobe lights
•	TAXI: switches RWY TURN OFF and NOSE to TAXI
•	LANDING: switches both LAND ON and also NODE to TO - somewhat interacting with TAXI lights
•	GEAR: works fine
Known Issues: 
•	MASTER BAT: not working - needs to be done in plane first otherwise plane ends up ina weired state
•	PANEL: turns on/off OVHD panel inegrated lights (need to turn to full in plane first)
Multipanel
Working / Extra:
Displayand knob:
•	ALT: works (steps of 100ft)
•	VS: displays and changes actual VS, changes FMA announiator, does NOT change FCU*
•	IAS: displays and changes speed bug and actual speed, does NOT change FCU*
•	HDG: displays and changes hdg bug and actual hdg, does NOT change FCU *
(when in SELECTED HDG shows actual hdg)
•	CRS: displays and changes crs1 (ND VOR mode) and actual crs1, does NOT change FMGC RADNAV page CRS
* somehow the A32NX does not synchronize this back to the FMC
AP Buttons:
•	AP-Light: ON when AP1 ON, OFF otherwise
•	AP-Button: NOT WORKINGcorrectly(trurning off works, turning on not)
•	HDG-Lights: ON when in selected HDG, OFF when in managed HDG 
•	HDG-Button: NOT WORKING
•	NAV:-Light: OFF when in selected HDG, ON when in managed HDG 
•	NAV-Button: NOT WORKING
•	IAS:-Light:ON when in selected SPEED, OFF when in managed SPEED 
•	IAS-Button: NOT WORKING
•	ALT-Light: NOT WORKING
•	ALT-Button: NOT WORKING
•	VS-Light: ON when climbing or descending, OFF otherwise
•	VS-Button: NOT WORKING
•	APR-Light:ON when APPR Mode is ON, OFF otherwise
•	APR-Button: NOT WORKING 
•	REV-Light: NOT WORKING
•	REV-Button: NOT WORKING

•	AUTO THOTTLE: switches A/THR
•	FLAPS: works as expected
•	PITCH TRIM: works but useless in A320 as it autotrims

**Comment by aguther** [comment] 2021-04-11 05:36
Did you take a look here (experimental version):
https://github.com/flybywiresim/a32nx/blob/autopilot/docs/a320-simvars.md
https://github.com/flybywiresim/a32nx/blob/autopilot/docs/a320-events.md

**Comment by frankkopp** [comment] 2021-04-11 08:24
Yes - it it was very helpful. But I thought of the other way round.
Instead of just listing all events, list all functions and describe which VARS or EVENTS influence them.

Good example is Master Bat 1 + 2 - I did not yet find out how to turn them on correctly. 

I propose some tables:

OVHD Panel Lights Status (Read):
Battery1 Light: LVAR xyz1
Battery 2 Light: LVAR xyz2
...

OVHD functions:
Turn on Batterie one: ....use EVENT xyz1 or set LVAR abc1
Turn on Batterie two: ....use EVENT xyz2 or set LVAR abc2

...

Autopilot:
Current HDG: LVAR zzz1
Selected HDG: LVAR uuu1
Change Selected HDG: ... (needs to change the heading bug and the FMC value)
Turn on managed HDG: ....
Turn on selected HDG: ....

...

These are just examples but they look at the issue from the functional perspective instead of just listing VARS/EVENTS which often are not sufficient to really use them. E.g. I know where the Seleceted HDG is stored and can read and change it. But it will not change the value in the FMC although it changes the actual used HDG and the heading bug). 
This is either currently not possible or I'm using the wrong VARS or I should use an event for this. I don't know. 

Does that make my request clearer? Happy to continue on Discord: Cdr_Maverick

**Comment by frankkopp** [comment] 2021-04-11 08:47
> Did you take a look here (experimental version):
> https://github.com/flybywiresim/a32nx/blob/autopilot/docs/a320-simvars.md
> https://github.com/flybywiresim/a32nx/blob/autopilot/docs/a320-events.md

Testing the AP event A32NX.FCU_AP_{index}_PUSH currently and it doesn't show up in SPAD.neXt or FSUIPC event logs.
Also tested: HDG, ALT (triggers MSFS:ALTITUDE_SLOT_INDEX_SET Parameter 2 (2 ID 0000:060D), VS
None of these events are visible in SPAD.neXT or FCUIPC.
Not sure if these tools need to be changed to see them though - also a good reason to have a good documentation :)

**Comment by aguther** [comment] 2021-04-11 09:53
Partly the issue is that original events do not always fire that’s why I used custom ones.

I need to investigate further how usage of original events is possible with that in mind.

The problem is also that the FCU has some logic and transitions, so it needs to get updates on those variables. So while it seems to be easy from your point of view in details it’s not always like that.

For all other stuff:
You’re kindly invited to improve documentation for variables. Check where it is written and read and what logic is behind. Not so difficult, just takes time. There is no single person doing that overall. So for example I cannot tell you anything about those other variables but I can help you with the ones I created and documented.

**Comment by frankkopp** [comment] 2021-04-11 22:29
@aguther there is definitely the issue that I can change SPEED, HDG and VS (plane acts correctly, PFD shows correct value) but FCU values do not change.
I tried to look at the code but without understanding all the events and callbacks etc. I can't really tell where the issue is. Someone who knows this code should see this quickly. I simply guess that there is not update trigger from the VARS to the FCU. The other way round works fine. 

Who would be able to clarify how to turn on batteries with VARS and Events? 

Also - I started on a docs page but it would be great if someone would be willing to give a quick crash course how to use github correctly for FBW and create a correct pull request. Discord: Cdr_Maverick

**Comment by tracernz** [comment] 2021-04-11 22:36
> Yes - it it was very helpful. But I thought of the other way round.
> Instead of just listing all events, list all functions and describe which VARS or EVENTS influence them.
> 
> Good example is Master Bat 1 + 2 - I did not yet find out how to turn them on correctly.

Keep in mind that these systems are under heavy development and as such any documentation will be quickly outdated. The code is the only absolute source of truth.

**Comment by MisterChocker** [comment] 2021-04-13 13:45
@frankkopp I am pretty sure that once the AP system is in place and we can start on coding the FCU from ground these issues can be dealt with.

**Comment by aguther** [comment] 2021-04-18 07:56
I made some significant improvements for experimental version:
https://github.com/flybywiresim/a32nx/tree/experimental/docs

**Comment by frankkopp** [comment] 2021-04-18 11:36
Thanks Andreas, makes it really easier for the AP stuff. 
SPAD.neXt does not yet show the new events. I tried to to the SPAD-FSUIPC combination with sending key events but that is rather unreliable. Anyway great work.

Anybody know how to turn on Batteries with vars or events?

**Comment by aguther** [comment] 2021-04-18 11:41
You just need to add the events as client events in SPAD.next. I did this and it worked quite well.

**Comment by frankkopp** [comment] 2021-04-18 14:05
Thanks for the tip with the Client Events - here are the definitions in the SPAD.neXt profile XML:
```
  <CustomClientEvents>
	<CustomClientEvent Name="A32NXAP1PUSH" EventID="A32NX.FCU_AP_1_PUSH" SubCategory="FCU" />
	<CustomClientEvent Name="A32NXAP2PUSH" EventID="A32NX.FCU_AP_2_PUSH" SubCategory="FCU" />
	<CustomClientEvent Name="A32NXSPDPUSH" EventID="A32NX.FCU_SPD_PUSH" SubCategory="FCU" />
	<CustomClientEvent Name="A32NXSPDPULL" EventID="A32NX.FCU_SPD_PULL" SubCategory="FCU" />
	<CustomClientEvent Name="A32NSMTOGGLE" EventID="A32NX.FCU_SPD_MACH_TOGGLE_PUSH" SubCategory="FCU" />
	<CustomClientEvent Name="A32NXHDGPUSH" EventID="A32NX.FCU_HDG_PUSH" SubCategory="FCU" />
	<CustomClientEvent Name="A32NXHDGPULL" EventID="A32NX.FCU_HDG_PULL" SubCategory="FCU" />
	<CustomClientEvent Name="A32NXTRKTOGG" EventID="A32NX.FCU_TRK_FPA_TOGGLE_PUSH" SubCategory="FCU" />
	<CustomClientEvent Name="A32NXALTPUSH" EventID="A32NX.FCU_ALT_PUSH" SubCategory="FCU" />
	<CustomClientEvent Name="A32NXALTPULL" EventID="A32NX.FCU_ALT_PULL" SubCategory="FCU" />
	<CustomClientEvent Name="A32NXVSPUSH" EventID="A32NX.FCU_VS_PUSH" SubCategory="FCU" />
	<CustomClientEvent Name="A32NXVSPULL" EventID="A32NX.FCU_VS_PULL" SubCategory="FCU" />
	<CustomClientEvent Name="A32NXLOCPUSH" EventID="A32NX.FCU_LOC_PUSH" SubCategory="FCU" />	
	<CustomClientEvent Name="A32NXAPRPUSH" EventID="A32NX.FCU_APPR_PUSH" SubCategory="FCU" />	
	<CustomClientEvent Name="A32NXEXPPUSH" EventID="A32NX.FCU_EXPED_PUSH" SubCategory="FCU" />
  </CustomClientEvents>
```

**Comment by aguther** [comment] 2021-04-18 15:22
Thank you for the hint, I've added now an empty profile for SPAD.neXt to the docs folder.

I just checked what happens when one presses one of the battery buttons, but it seems not that easy to understand.

@davidwalschots What would be the easiest way to trigger this from SimConnect?

**Comment by davidwalschots** [comment] 2021-04-18 17:03
I've (luckily) had the pleasure of not requiring SimConnect for any of my work thus far.
The system code reads `L:A32NX_OVHD_ELEC_BAT_10_PB_IS_AUTO` (BAT1) and `L:A32NX_OVHD_ELEC_BAT_11_PB_IS_AUTO` (BAT2) to determine the battery push button position. `1` means AUTO, `0` means OFF. Note that we might change this variable name to use `BAT_1` and `BAT_2` in the future, as the current names are kind of a legacy thing.

You can modify those two variables and everything should work okay.

**Comment by frankkopp** [comment] 2021-04-18 21:03
> `L:A32NX_OVHD_ELEC_BAT_10_PB_IS_AUTO` (BAT1) and `L:A32NX_OVHD_ELEC_BAT_11_PB_IS_AUTO` (BAT2)

SPAD.neXt doesn't seem to expose them. I don't know if LVARS have to be "programmed" in or can be read from the sim somehow. 
A lot of the LVARS from the documentation are not visible.

**Comment by frankkopp** [comment] 2021-04-18 22:30
In the SPAD discord the question came up if these VARS (https://github.com/flybywiresim/a32nx/blob/experimental/docs/a320-simvars.md) are LVARS which can be self discovered by SPAD (or other tools I assume) or if these are HVARS (I personally don't know the difference). Someone said the HVARS would have to be put into SPAD manually (by the developer) while the LVARS would be self discovered.  
Can someone shed some light on this?
Thanks

**Comment by frankkopp** [comment] 2021-04-18 23:57
Update: Somehow SPAD now shows the variables - probably user fault, idk.

But using L:A32NX_OVHD_ELEC_BAT_10_PB_IS_AUTO is not sufficient.
When setting this to 1 you can hear a "relay" switching and you hear the repetitive gong but the second battery lights and fuel pump lights (and others) do not turn on as they do when using the button in the plane.

**Comment by davidwalschots** [comment] 2021-04-19 08:01
Ah yes. Sorry about that. It will be sufficient once [this PR](https://github.com/flybywiresim/a32nx/pull/3980) is merged. Which I expect will happen somewhere this week.

**Comment by aguther** [comment] 2021-04-24 19:14
I suggest closing this issue here and maybe create ones for specific system parts. Otherwise it will be hard to track and close.

**Closed** 2021-04-24 19:14 UTC
Labels: Enhancement, FCU
