### ISSUE TITLE
[BUG] Flaps extending after weather modification

### ISSUE THREAD

**Issue by Juju2004** [flybywiresim/a32nx#2570] opened 2020-12-20 19:50 UTC
**0.5.0**
Release version

**Describe the bug**
After changing the weather (wind and clouds change by pressing enter), the flaps extend to full position without any input of the actual flaps switch, on the ground and at cruise altitude
The weather was overcast with snow, with 8 kts of wind.

1. Load the A320 with the release 0.5.0 version with engines off
2. Change the weather (clouds, wind, etc) by changing the digits and pressing enter
3. Start the pushback and the engines, flaps should come down while the engine starts
4. While in flight, change the wind and clouds again by changing digits and pressing enter, flaps should extend

**Expected behavior**

The flight continues as usual

**Actual behavior**

The flaps extended and the airspeed dropped significantly

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Never tried before

Is this a problem in the vanilla unmodded game?
Never tried

**Comment by andrejetcat** [comment] 2020-12-20 21:41
i also have this issue, not just changing the weather, if you go to the menue and back, without changing anything, its the same!

**Comment by Saschl** [comment] 2020-12-20 21:49
I believe you both are using the Thrustmaster TCA Quadrant? If so then please check and remove the mappings for Flaps and Speedbrakes for now

**Comment by Juju2004** [comment] 2020-12-20 22:00
I am not using a thrustmaster product and i even tried disconnecting my joystick to see if it still happened and it did

**Comment by MisterChocker** [comment] 2020-12-21 10:41
On the Thrustmaster TCA Quadrant this is caused by having short cuts bind to an non existent button, maybe you some sort of short cut binding has no actual button?

**Comment by MisterChocker** [comment] 2021-01-13 11:48
@Juju2004 please respond to my question.

**Comment by Juju2004** [comment] 2021-01-13 14:11
I checked and there was no shortcut binding on my keyboard but once I updated to the most recent dev version the problem was gone.

**Comment by MisterChocker** [comment] 2021-01-13 14:13
Closing since issue resolved.

**Closed by MisterChocker** 2021-01-13 14:13 UTC
Labels: Bug, Waiting For Response
