### ISSUE TITLE
[BUG] A320 Last flight model dosent work good.

### ISSUE THREAD

**Issue by Berniep94** [flybywiresim/a32nx#1053] opened 2020-10-03 06:04 UTC
**Mod Version**
Master (Downloaded 4 hours ago)

**Describe the bug**
when i am in flaps 1 the nose of the airplane goes down while aircraft continue climbing, its just not realistic.

**To Reproduce**
1. Take off Flaps 1+F
2. Didnt gain speed with flaps 1
3. retract Flaps 1 gain speed and altitude but its not real!
4. Approach same issue, was decending to 4000, and hit Flaps 1 and flare to 5,300.
5. imposible to land.

**Expected behavior**
Just reverted it like it was before, that flight model dosent works as it should, please check all the PR good... make and exhaustive test.

**References**
![FlightSimulator_z292sTbmna](https://user-images.githubusercontent.com/71423997/94984694-f0f06e80-050b-11eb-9bf6-3be1b6671253.jpg)

Was this working before/when did the issue start occurring? Yes, much better!

Is this a problem in the vanilla unmodded game? no

Discord username (if different from GitHub):

**Comment by theersink** [comment] 2020-10-03 08:26
I just want to add for the devs with the newest master that included Flightmodel hotfix #1029 this does not appear to be an issue any longer. TO , approach and landing felt better. Autoland flare is still rough but that is a separate issue.

**Comment by Berniep94** [comment] 2020-10-03 08:30
> I just want to add for the devs with the newest master that included Flightmodel hotfix #1029 this does not appear to be an issue any longer. TO , approach and landing felt better. Autoland flare is still rough but that is a separate issue.

I downloaded like 3 hours ago more or less.

**Comment by theersink** [comment] 2020-10-03 08:41
Your bug report states 0.3.1 not the latest master. At any rate I did not encounter the issues you described on my previous 2 flights on the master branch.

I was able to climb and accelerate with flaps 1

Applying flaps 1 at Green dot speed and the nose did pitch up but never got past about 200ft per sec positive. Aircraft did a good job controlling the pitch/speed.

After full flaps and setting 140 approach it was much more stable than prev builds and I was able to hand fly down from 500ft. Does lose a bit of authority on low speeds but that is the only issue I had.

**Comment by Berniep94** [comment] 2020-10-03 08:52
> Your bug report states 0.3.1 not the latest master. At any rate I did not encounter the issues you described on my previous 2 flights on the master branch.
> 
> 
> 
> I was able to climb and accelerate with flaps 1
> 
> 
> 
> On approach and applying flaps 1 at Green dot speed and the nose did pitch up but never got past about 200ft per sec positive. Aircraft did a good job controlling the pitch/speed.
> 
> 
> 
> After full flaps and setting 140 approach it was much more stable than prev builds and I was able to hand fly down from 500ft. Does lose a bit of authority on low speeds but that is the only issue I had. 

My bad, i already do 2 flights with the same result, both on diferent conditions and scenerios... but we will see!

**Comment by c1be** [comment] 2020-10-04 17:55
I have the same problem, downloaded master an hour ago. Plane starts to takeoff by itself at 120 knots, climbing with nose down, completely not flyable...

**Comment by Berniep94** [comment] 2020-10-05 01:34
Another test in the aircraft.... look this its UNFLYABLE!!!!

![FlightSimulator_SSOe0vzWBF](https://user-images.githubusercontent.com/71423997/95032629-8f014780-0678-11eb-94b8-d5d099d3561d.jpg)
![FlightSimulator_vw85h6k3U2](https://user-images.githubusercontent.com/71423997/95032632-9163a180-0678-11eb-9ea0-7864bea6c3a5.jpg)
![FlightSimulator_fSfbGyl5RZ](https://user-images.githubusercontent.com/71423997/95032634-93c5fb80-0678-11eb-8386-834e9cb636db.jpg)
![FlightSimulator_6NWyH1Yo5d](https://user-images.githubusercontent.com/71423997/95032637-958fbf00-0678-11eb-8c4f-beae566dde7c.jpg)
![FlightSimulator_5q1YZmpcYf](https://user-images.githubusercontent.com/71423997/95032641-97598280-0678-11eb-83ae-40abc05307e0.jpg)


like i said, this new flight model its a complete mess!!

**Comment by c1be** [comment] 2020-10-05 05:13
Yeah, same thing, it’s not usable, impossible to land, terrible flight model. I’m suprised more people aren’t reporting it.

**Comment by theersink** [comment] 2020-10-05 05:20
Well all I can say is it is working fairly good for me. 140knts with the aircraft in proper config and lined up and I get about 750 to 850ft per minute decent on landing before flare. 20+ landings with the 320, 8 with this flight model.

The flight model is far from perfect but it is definitely not unflyable. It tends to float a little and you have to flare just perfect. But different people are having different experiences. 

Try doing an ILS or RNAV approach on AP. That is how I setup all mine and then hand fly if you want from 1000ft or so. I have flown a couple of manual approaches as well without the issues you have. Also I was having major issues before I got a tip to set the deadzone for all control axis to 20% and sensitivity down 50%. Really helped to smooth everything out. I think MSFS controller axis are a bit too sensitive.

**Comment by c1be** [comment] 2020-10-05 05:30
Are you using latest stable version or master version, becuase i downloaded
master yesterday and airplane was out of control.

**Comment by Berniep94** [comment] 2020-10-05 06:00
I download da aircraft every single day, the thing is that if you put flaps 1 like on the image, the aircraft just floats and it seems like you twist the engines into vertical position. And floted like 1,500fts, sets flaps 2 your nose wanna go down to find the descend you are looking for, but it continues floating, i have more than 50 landings on the A320 i can tell you that is even better the last flight model, like i was telling you, i download eeeeevery single day the aircraft, to see the progress and try to give my feedback about issues. And this is the first one that i can tell you that is out of the real thing... what i have do right now is setting back to the previous flight model... i wanna give it a try today and i just got the same result as yesterday.

**Comment by c1be** [comment] 2020-10-05 06:09
I agree with you, i had first master after Japan patch and flight model was
ok, downloaded yesterday and it’s the same behaviour as yours, nose pitch
down but aircraft still climbs, impossible to land, you can even fly at
110knots with 10 degree nose down and it will fly straight, if flaps are
set.

**Comment by theersink** [comment] 2020-10-05 06:12
I update every time something is merged. 

What you are describing should not be happening for sure but there is something else going on. If you look at the PRs for the mod they reverted all the flight model changes so is vanilla except for ground steering. Almost sounds like the controller issue I was having.

**Comment by c1be** [comment] 2020-10-05 06:14
Default a320 flight model works fine for me, so it’s not a controller issue.

**Comment by Berniep94** [comment] 2020-10-05 06:19
Yup, i have take the A320 without the MOD right now, and i dont have that issue... so it isnt a vanilla problem because since yesterday im having that problem... so i dont think its a controller or a vanilla issue (at least in floating like this) the low speed wing drop i know it is.

**Comment by theersink** [comment] 2020-10-05 06:34
Well there has to be something else going on then because the flighmodel IS vanilla. #1029  specifies this. It is discussed on the discord channel as well. The old modified NX flightmodel before this 1029 hotfix  would stall at around 150, drop out of the sky at 140. 1.9.3 did not react well with that one so it had to be reverted. 
Best of luck to you both. Not sure what else I can offer for help. Maybe one of the Devs can speculate.

**Comment by c1be** [comment] 2020-10-05 13:56
Nope, changed joystick sens, added deadzone, still the same, something is wrong, this plane's flight model is broken.

**Comment by c1be** [comment] 2020-10-05 18:08
> Well there has to be something else going on then because the flighmodel IS vanilla. #1029  specifies this. It is discussed on the discord channel as well. The old modified NX flightmodel before this 1029 hotfix  would stall at around 150, drop out of the sky at 140. 1.9.3 did not react well with that one so it had to be reverted. 
> 
> Best of luck to you both. Not sure what else I can offer for help. Maybe one of the Devs can speculate. 

I found out what the problem is. For some reason, in menu options you have to set flight model again, choose something else other than modern and get it back tonit again. Delete the master and copy it again. Now it works.

**Comment by mateoriddl** [comment] 2020-10-06 02:08
> Another test in the aircraft.... look this its UNFLYABLE!!!!
> 
> ![FlightSimulator_SSOe0vzWBF](https://user-images.githubusercontent.com/71423997/95032629-8f014780-0678-11eb-94b8-d5d099d3561d.jpg)
> ![FlightSimulator_vw85h6k3U2](https://user-images.githubusercontent.com/71423997/95032632-9163a180-0678-11eb-9ea0-7864bea6c3a5.jpg)
> ![FlightSimulator_fSfbGyl5RZ](https://user-images.githubusercontent.com/71423997/95032634-93c5fb80-0678-11eb-8386-834e9cb636db.jpg)
> ![FlightSimulator_6NWyH1Yo5d](https://user-images.githubusercontent.com/71423997/95032637-958fbf00-0678-11eb-8c4f-beae566dde7c.jpg)
> ![FlightSimulator_5q1YZmpcYf](https://user-images.githubusercontent.com/71423997/95032641-97598280-0678-11eb-83ae-40abc05307e0.jpg)
> 
> like i said, this new flight model its a complete mess!!

I got this same exact issue. I look like a complete idiot nosediving their plane, whenever this happens.

**Comment by Berniep94** [comment] 2020-10-06 09:48
Ok guys, i found a "solution" after a long night i hve found that you need to change the flight model in the sim.

1.- go to general
2.- flight model
3.- change it to modern

This stop causing the aircraft to float when getting flaps 1.

Let me know if that also helps you.

**Comment by theersink** [comment] 2020-10-06 15:02
@DoToAdventures No need to revert values as it appears this is caused by a settings issue where the flightmodel is set to legacy in the sim. 2 users reporting this have fixed the issue by cycling the flight model back to modern.

**Comment by Berniep94** [comment] 2020-10-06 15:42
Yeah, at least for now is working good, im sorry for the misunderstood, it was my fault... but i hace to do an exhausting testing... reverting flight models, modifying flight model, and my last and accurate method was in flight model in the sim.

I was mistaken with the mod. Sorry guys.

**Closed** 2020-10-09 06:29 UTC
Labels: Bug, Bug-A32NX
