### ISSUE TITLE
[BUG] Autobrake MAX doesn't activate on RTO

### ISSUE THREAD

**Issue by Ehmydev** [flybywiresim/a32nx#2034] opened 2020-11-20 15:17 UTC
**Mod Version**

master

**Describe the bug**

While doing an RTO, max autobrake isn't applied

**To Reproduce**

1. Start from runway
2. Go TOGA
3. RTO just before V1 (thrusters to 0)

**Expected behavior**

Max Autobrake is applied, reducing speed quickly

**Actual behavior**

No brake applied at all

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game? Don't know, probably not

Discord username (if different from GitHub): Ehmydev#5985

**Comment by MisterChocker** [comment] 2020-11-21 03:48
Did you armed the autobrake max before?

**Comment by Ehmydev** [comment] 2020-11-21 08:41
Of course x)

**Comment by highperformancedevelopments** [comment] 2020-11-22 21:21
Same behaviour here.
If I pull the thrust lever to idle there is no autobrake. If manual brakes are deployed the following shows up in the upper ECAM-Display:
![grafik](https://user-images.githubusercontent.com/25608553/99917500-04040b80-2d11-11eb-8353-d327442001a5.png)

**Comment by MisterChocker** [comment] 2020-12-31 05:17
closing since it cant be reproduced and seem to be fixed on latest master.

**Closed by MisterChocker** 2020-12-31 05:17 UTC
Labels: Bug, Can't Reproduce
