### ISSUE TITLE
Flightplan data erased when going direct to first waypoint in VR.

### ISSUE THREAD

**Issue by DikTater** [flybywiresim/a32nx#3996] opened 2021-03-16 00:33 UTC
**Mod Version**

  "built": "2021-03-15T18:53:20+00:00",
  "ref": "autopilot",
  "sha": "adafbb3dfd55bbf7b8692409f731c5cc49e05f25",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

On selecting direct to the first waypoint, the flighplan gets removed. This only happens in VR.

**To Reproduce**

1.Depart a runway using the heading bug for guidance. Have a flightplan loaded.
2.When cleared direct to first waypoint, click DIR button on scratchpad. Select appropriate waypoint with LSK. (I have only tried the first waypoint)
3.When you then click the amber TMPY DCT LSK, the flightplan is erased.

**Expected behavior**

I expected to have the computer plot and fly a course to the waypoint I selected.

**Actual behavior**

When selecting TMPY DCT, the flighplan is erased and I have to re-enter the data.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Installed new HD this weekend and that is when I first noticed it.

Is this a problem in the vanilla unmodded game?
Untested.

Discord username (if different from GitHub):
DikTater#9094

**Comment by DikTater** [comment] 2021-03-16 03:38
After more digging I found this old thread on the MS forums... [https://forums.flightsimulator.com/t/switch-from-vr-to-pc-mode-messes-up-flightplan-autopilot/344017/4](url) I tried the workaround which was to simply disable the VFR map from the overhead toolbar and it worked.

**Comment by MisterChocker** [comment] 2021-03-16 17:52
There is not temporary flight plan on the direct page.

**Comment by MisterChocker** [comment] 2021-03-16 17:52
If this is an issue.
Duplicate of #1745

**Closed by MisterChocker** 2021-03-16 17:52 UTC
Labels: Bug, Waiting For Response
