### ISSUE TITLE
[BUG] Severe stutter 

### ISSUE THREAD

**Issue by flaminiom** [flybywiresim/a32nx#3638] opened 2021-02-20 00:47 UTC
**Mod Version**

Tested w/ f70e084. Not sure which version I first noticed it, but first saw it Thursday evening. Didn't have this issue Tuesday or Wednesday w/ World MSFS update.

**Describe the bug**

When starting cold/dark, there is a bad stutter. Frame rates are unaffected. It might get progressively worse as start up procedure advances. In video, see second attempt, after loading flight plan there may be a slight performance issue that wasn't present when before loading plan. Stutter continues into the air. Issue was repeated 5-6 times with developmental release. The issue could not be repeated using stable release.

Test was at Parking 14 at KSTL. Flight plan was KSTL to CYMX via SimBrief.

See videos demonstrating the scnario and problem.

**To Reproduce**

1. Enter plane at KSTL, Parking 14 cold and dark
2. Load flight plan via SimBrief
3. Complete start up procedures (see video)
4. Taxi

**Expected behavior**

Normal performance without stutter. 

**Actual behavior**

Severe stutter that doesn't affect FPS.

**References**

Development version w/ stutter: https://www.youtube.com/watch?v=52RUo4gM2NU

Stable version w/o stutter: https://www.youtube.com/watch?v=3A3htbYcv-Y

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

AuFinger

**Comment by Mickepilot** [comment] 2021-02-20 09:27
@flaminiom, hello, I can confirm that I also have the same problem since Thursday.
I'm using up to date Win10 PC with latest MS FS UK update and the A32NX CustomFBW

**Comment by flaminiom** [comment] 2021-02-23 00:35
I haven't experienced this since KSTL. It happened as described a bunch of times in a row, so something is going on there, but maybe something specific to that airport or starting spot?

**Comment by dcherrie** [comment] 2021-02-23 11:57
I can confirm since the UK World Update III have been getting stutters every 3 or so seconds but only in and around London. It was not isolated to this mod or aircraft though.

**Comment by XSJoJo** [comment] 2021-02-25 16:49
> Development version w/ stutter: https://www.youtube.com/watch?v=52RUo4gM2NU
> 
> Stable version w/o stutter: https://www.youtube.com/watch?v=3A3htbYcv-Y

Mind uploading these to Google Drive so I can step through them frame-by-frame?

**Comment by torontoflyer** [comment] 2021-03-02 15:03
I have the 39de157 dev version and I also experienced the stutter, bad enough to render it unplayable. Had no issue with the stable version as the op suggested.

**Comment by vers010** [comment] 2021-03-04 07:33
I recognize this problem. I have the same issue.

**Comment by Benjozork** [comment] 2021-06-26 06:45
Closing in favour of #4051.

**Closed by Benjozork** 2021-06-26 06:45 UTC
Labels: Bug, Performance
