### ISSUE TITLE
[BUG] Artificial horizon on PFD does not align

### ISSUE THREAD

**Issue by ItsBlitz** [flybywiresim/a32nx#735] opened 2020-09-17 17:03 UTC
**Mod Version**
 0.2.0

**Describe the bug**
 Cold and Dark startup as planned, I go to align the ADIRS, wait as much time as needed for them to align, everything but the HUD display on the PFD will not align and says ATT in red blinking. Tried every way to get it realigned and nothing. All other systems working.

**To Reproduce**

 
1. Align the ADIRS as planned
2. Continue to wait the needed time for alignment

**Expected behavior**
 I expected the HUD to align as planned and get on my way :)

**Actual behavior**
 HUD went with a blinking ATT

**References**
 
![AEE399BA-54C7-43A0-9FC8-8FB3C8BDFDAC](https://user-images.githubusercontent.com/71457734/93503386-d8a61000-f8cc-11ea-8288-c0a24f57efd7.jpeg)

**Additional context**
 I apologize if I formatted anything incorrectly, brand new to GitHub.

Discord username (if different from GitHub):

**Comment by ItsBlitz** [comment] 2020-09-17 17:41
Little update. I realigned the ADIRS another time, they turned on for about 15 seconds and went back to ATT blinking red. 

Then I switched my graphics settings for glass cockpit refresh rate to High and it flickered 3 times and went back.

**Comment by Benjozork** [comment] 2020-09-17 20:14
Hello @ItsBlitz,

Can you specify which version of the simulator you use ? Thanks !

**Comment by ItsBlitz** [comment] 2020-09-17 20:19
> Hello @ItsBlitz,
> 
> Can you specify which version of the simulator you use ? Thanks !

Im currently using the newest patch, 1.8.3.0

**Comment by enesaydogan** [comment] 2020-09-18 13:51
Can not produce on master (4ae691b)(MSFS 1.8.3). Everything works as intended regarding this bug report.

**Comment by AdenFlorian** [comment] 2020-09-20 20:07
sounds like this is fixed in master, closing.

**Closed by AdenFlorian** 2020-09-20 20:07 UTC
Labels: A32NX v0.2.0, ADIRS, PFD, bug, bug-a32nx
