### ISSUE TITLE
[BUG] ECAM/PFD Ambient Light Flickering

### ISSUE THREAD

**Issue by Steam3ngine** [flybywiresim/a32nx#1312] opened 2020-10-14 05:26 UTC
**Mod Version**
Latest Stable build via Installer

**Describe the bug**
The ambient light from the cockpit glasss is flickering.

**To Reproduce**
1. Turn on ECAM/PFD screens; flicker is most noticeable in an otherwise dark cockpit. 

**Expected behavior**
Ambient light shouldn't flicker

**Actual behavior**
Ambient light flickers

**References**
[flickering](https://www.youtube.com/watch?v=xsraxKtQgo4)

**Additional context**
Nvidia 1080 ti with latest drivers, latest version of MSFS

Was this working before/when did the issue start occurring?
Today was my first time using the mod.

Is this a problem in the vanilla unmodded game?
No.

Steam3ngine#0953

**Comment by Benjozork** [comment] 2020-10-14 05:29
Duplicate of #1266, which is fixed in latest master.

**Closed** 2020-10-14 05:29 UTC
Labels: Bug
