### ISSUE TITLE
[BUG] IMSDU distance to destination not showing correctly

### ISSUE THREAD

**Issue by mixsiak** [flybywiresim/a32nx#3435] opened 2021-02-09 09:18 UTC
**Mod Version**  last developer version

**Describe the bug**
<! on MCDU not final disctanns on FLP is  caltulating..iis is not going down.. the distance..it was ok on STABLE version -->

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by kiokio0987** [comment] 2021-02-09 10:46
Duplicate of (#3379)
Please close this post.

**Comment by MisterChocker** [comment] 2021-02-09 12:19
Duplicate of #3379

**Closed by MisterChocker** 2021-02-09 12:19 UTC
Labels: Bug
