### ISSUE TITLE
TOD marker missing

### ISSUE THREAD

**Issue by Ixoman** [flybywiresim/a32nx#6325] opened 2021-12-07 17:46 UTC
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-21T01:55:55+00:00",
  "ref": "v0.7.3",
  "sha": "e6fb4129367d266aa6f77a979e37f66d458a2575",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

When load Flight plan or just put the flight plan, always the TOD(top of descen) marker is missing, so if I'm not flying with ATC i do not clearly where to start desce
![Error_MFS2020_TOD1](https://user-images.githubusercontent.com/95709395/145078980-392b0991-8b7f-40ee-9f9d-29952459f137.png)
![Error_MFS2020_TOD2](https://user-images.githubusercontent.com/95709395/145079094-3c01e8ad-7a0a-4ef1-bf38-24e4cb757d70.png)
nt

### Expected behavior

White arrow should be present
![Error_MFS2020_TOD3](https://user-images.githubusercontent.com/95709395/145079323-873f8170-ac70-45fd-9d56-0fdbbda4c54e.png)

### Steps to reproduce

Do a flight plant with SID and STAR correctly

### Discord Username (optional)

Ixoman0#3533

**Comment by Benjozork** [comment] 2021-12-07 17:46
Duplicate of #5966

**Closed by Benjozork** 2021-12-07 17:46 UTC
Labels: Bug
