### ISSUE TITLE
[BUG] End of Flight Plan Not Appearing in MFD (After STAR Waypoints & Transition to Approach)

### ISSUE THREAD

**Issue by DFWSupertrooper** [flybywiresim/a32nx#3397] opened 2021-02-07 15:43 UTC
**Mod Version**
FBW Custom D/L 07-Feb 07:00am CDT

**Describe the bug**
When approaching end of route, the final waypoints of my route (after final STAR waypoint) are not visible.  Route appears to end (last 2/2 flights different airports).

**To Reproduce**
1. Build FPL using built in routing (example I used EFHK NUNT3P NUNTO DCT LOGNA DCT MILTA DCT DESON DCT VARUS DCT KEDUX DCT BALIT/K0817F360 DCT KUNER DCT BEZMI DCT XERBI DCT GOVEN/N0438F360 DCT BUKIG DCT KOBUS DCT RIKLU DCT MAREM DCT BAGMI BAGM5A).
2. Fly route via IFR.
3. Upon approaching BAGMI, note MFD route ends at MITNU (just prior to approach pattern beginning).  Remaining waypoints appear in MCDU (...LANDU, DM428, DM420, (DECEL), USR, BEGEN, FI08R, RW08R...) but do not appear in MFD.
4. Observe A/C turning towards RWY08R at end of mapped FPL.

**Expected behavior**
Entire route should be mapped and displayed in MFD, matching MCDU.

**Actual behavior**
Route ends too early in MFD map.

**References**
N/A

**Additional context**
N/A

Was this working before/when did the issue start occurring?
Yes.

Is this a problem in the vanilla unmodded game?
No idea...guess not.

N/A

**Comment by DFWSupertrooper** [comment] 2021-02-07 15:48
I should also note I was using ILS 08R into EDDM.  Also, the link (planned line between UNKOM & MITNU was missing, although the MITNU waypoint with constraint is displayed.  On same issue yesterday into KSJC, I DIR TO first waypoint in ILS approach and the route reappeared.

**Comment by DFWSupertrooper** [comment] 2021-02-07 15:53
Interestingly, the A/C continues on the correct path despite it being visually missing in the MFD.

**Comment by depthvader** [comment] 2021-02-07 16:23
Same issue here, flying KMCO  to TJSJ and now the reverse route. Started after yesterday's update same version. Though mine did not continue on the flight plan and I had to disengage AP and fly manually.

**Comment by XSJoJo** [comment] 2021-02-07 16:44
> Route ends too early in MFD map.

Is this also observable in PLAN mode at the beginning of the flight?

**Comment by XSJoJo** [comment] 2021-02-07 16:54
Mind testing this with https://github.com/flybywiresim/a32nx/pull/3396?

![Untitled](https://user-images.githubusercontent.com/3019329/107153326-35ce5b00-696d-11eb-9e75-28cdb5f1b393.png)

I think I have different database (using Navigraph...) but I do see all waypoints on the PLAN page in the MFD, at least at the beginning of the flight. I haven't checked what happens when I would actually fly the route..

**Comment by depthvader** [comment] 2021-02-07 17:02
Yes,, on the PLN the lines are gone and most of the STARs way points.

**Comment by depthvader** [comment] 2021-02-07 17:09
![missing legs](https://user-images.githubusercontent.com/63113075/107153781-4bc42780-693d-11eb-8c93-8b5691bcd2d6.png)

**Comment by XSJoJo** [comment] 2021-02-07 17:15
OK looks like #3396 doesn't fix it, but if you enter the approach in the MCDU it seems to work fine.

So this issue only exists if you enter the approach from the FS built-in flight planning tool and then load the flight.

**Comment by depthvader** [comment] 2021-02-07 17:37
Entered the approach manually and that did give me guidance all the way down, however once activated it way pointed direct to the airport, I had to do a direct to the initial approach fix

**Comment by ErikNL80** [comment] 2021-02-07 19:48
Just experienced the same issue on a flight from EHAM to EGGP, using the standard NavData. Used the in-game flight planner and chose an RNAV 09 approach, via MCT. When approaching, the FP ended at MCT, no further data. In the MCDU manually entered the RNAV 09 again, but the plane did not follow the route. Followed it manually.

**Comment by XSJoJo** [comment] 2021-02-07 20:38
Ok I have a fix for the approach not loading initially, 

However, for the AP not following the approach flight plan, @Benjozork tells me that this has always been happening and doesn't seem to be a regression from #3262

**Comment by XSJoJo** [comment] 2021-02-08 01:26
> Ok I have a fix for the approach not loading initially,
> 
> However, for the AP not following the approach flight plan, @Benjozork tells me that this has always been happening and doesn't seem to be a regression from #3262

That wasn't actually true - this was definitely a regression from #3262 

These should now be fixed with #3396

**Comment by ACSoft47** [comment] 2021-02-08 18:17
Yes, with actual version (I tested with 1st version having FPS optimization, of yesterday 7 february), arrival datas of flightplan I have generated with in game FS planner, are missing. Fortunately, if I re-enter arrival datas when inside the aircraft, the flightplan is corrected and become identical to those generated directly from FS planner in previous  A32NX versions. So, this problem seem not to be specific to the import feature for flightplan of 3rd party external planner.

**Comment by DFWSupertrooper** [comment] 2021-02-08 20:21
GOD!!  This is SO frustrating...not ONE approach has worked since y'all started messing with the "refresh rate" thingamajig.  They ALL worked mostly (except for the know  turn towards RWY issue) prior.  Now the A/C turns dramatically AWAY from the approach if I hit the APPR button when I'm coming in, and often it's turning towards a waypoint not even in my FPL (but on the actual STAR).  Every single approach now I start turning all over the place before locking into ILS.  This is killing me.  Sorry for ranting...you guys do awesome work, but seriously something is broken and it wasn't before.  Just watching my A/C on my other machine circle around like a lost balloon.  Sorry...wish I could help.  Y'all keep at it. :)

**Comment by Benjozork** [comment] 2021-02-08 20:24
@DFWSupertrooper I'm gonna ask you to consider that you're using a DEVELOPMENT version and therefore knowingly using a release that can contain unexpected bugs and crashes.

Regardless of your apologies or frustrations I'm gonna ask you to adjust your tone to be more polite on this GitHub as this kind of rant is not useful to anyone.

**Comment by Benjozork** [comment] 2021-02-08 20:29
We try our best to keep the development version usable but we're at a stage in the development of this add-on where we are swapping out a lot of parts for new stuff that we need to have in to make development easier going forward and performance better in the future.

Breakage is gonna happen, and these issues will show up when we poke in some places. But it'll all be fixed and we wanna make v0.6.0 the best version to date.

**Comment by DFWSupertrooper** [comment] 2021-02-08 20:41
Mea culpa brother!  You guys have an amazing support/development team and turn out quick fixes to everything and up to now your record of putting out _perfect_ upgrades has been virtually flawless...mark of a truly committed team and far better than most developers (_any_ I can think of).  I sincerely thank you guys for making this the only A/C I fly over and over and over, all from the goodness of your own hearts.  It's truly an amazing feat what you've done.  I'll retune myself directly.  I know you'll fix it mui rapido.  Can't wait to see the future with this A/C.  Thanks and again...sincerest apologies.  Keep up the fine work.

**Closed** 2021-02-09 22:00 UTC
Labels: Bug, Flight Plan
