### ISSUE TITLE
[BUG] STAR's won't show up on every airport

### ISSUE THREAD

**Issue by Amunlar** [flybywiresim/a32nx#1020] opened 2020-10-01 15:53 UTC
**Mod Version**

Release version 0.3.1

**Describe the bug**

STAR's won't show up on every airport.

**To Reproduce**

1. I set up the airplane, ready to file the flightplan in the MCDU.
2. I choose ENGM to EGLL in the Init page
3. When i choose runway 27R at EGLL there where no STAR's available for that runway and the others. I also tried EDDB, but there where no available STAR's there either.

**Expected behavior**

I expect to get the STAR's which is available in the decided airac database.

**Actual behavior**

There where no available STAR's at any airport.

**References**

![1250410_20201001174025_1](https://user-images.githubusercontent.com/72214766/94831911-9375f800-040d-11eb-91ec-9c58cb81aeaa.png)

**Additional context**

Was this working before/when did the issue start occurring?
Im not quite sure when it occured, but i know it worked fine for release 0.1

Is this a problem in the vanilla unmodded game?
Yes, the same problem is in the vanilla version, it looks like it occured when the lates patch was released.

Discord username (if different from GitHub): Amunlar#9633

**Comment by lousybyte** [comment] 2020-10-01 16:08
That's not something this mod can fix, you're better off looking for 3rd party providers like Navigraph to correct this. 
Although Asobo did mention they are looking to update their nav data monthly soon.

**Comment by trainab** [comment] 2020-10-01 16:24
I am also experiencing this, however to expand further I am not seeing STARs, even though I have previously seen STARs for that airport/runway. Agree this is an Asobo problem. I am thinking of trying a reinstall of the SIM.

**Comment by trainab** [comment] 2020-10-01 16:28
Agreed, will do

**Comment by Amunlar** [comment] 2020-10-01 16:29
Thank you

**Comment by tyler58546** [comment] 2020-10-01 16:37
Do STARs show up without the mod installed?

**Comment by Amunlar** [comment] 2020-10-01 16:38
No, the same as with the mod

**Comment by lousybyte** [comment] 2020-10-01 16:41
I checked the Navigraph beta and the STARs were all back, it seems it's a nav data issue.

**Comment by Amunlar** [comment] 2020-10-01 16:42
Could you link me the Navigraph Beta?

**Comment by lousybyte** [comment] 2020-10-01 16:48
You can check the details [here](https://forum.navigraph.com/viewtopic.php?f=14&t=9963), you do require an active subscription to their services.

**Comment by tyler58546** [comment] 2020-10-01 20:28
I have a fix for this in #1027.

**Comment by trainab** [comment] 2020-10-03 14:03
Unfortuantly a reinstall of the SIM does NOT fix this issue. It also does NOT fix the autopilot not following the plan issue that everyone is currently experiencing following the latest update from Microsoft. 

#1027 awaiting conflict resoulation but hopefully situation will improve once that has happened.

**Comment by Watsi01** [comment] 2020-10-06 07:34
The funny thing is, that the STARs/approaches are IN the sim (you can plan with them in the MSFS flight planning). They just doesn't show in the MCDU.

**Comment by mak60062** [comment] 2020-10-07 00:34
Just realized that all STARs show up correctly in the TBM930, issue may be isolated to the A320. 

TBM930 (KCMH)
![image](https://user-images.githubusercontent.com/6889399/95273913-4b424580-0812-11eb-838e-eb28b5f2f86a.png)

A320 (KCMH)
![image](https://user-images.githubusercontent.com/6889399/95274233-3ade9a80-0813-11eb-85e1-157c2bec05e6.png)

**Comment by tyler58546** [comment] 2020-10-07 00:37
I already know what the issue is and fixed it in #1027

**Closed** 2020-10-08 00:43 UTC
Labels: Asobo Bug, Bug, Bug-Vanilla, Waiting for PR merge
