### ISSUE TITLE
[BUG] MCDU increasing figures replacing altitude

### ISSUE THREAD

**Issue by MattPaxtonBel** [flybywiresim/a32nx#2261] opened 2020-12-06 21:02 UTC
**Mod Version**
 "built": "2020-12-06T08:38:03+00:00",
  "ref": "",
  "sha": "",
  "actor": "lukecologne <39596827+lukecologne@users.noreply.github.com>",
  "event_name": "manual"

**Describe the bug**
enroute on the following FPL:
LLBG/12 DAFN2C DAFNA W13 VELOX M42 GENOS DCT PEDER DCT EVENO UM601
EXELA UN127 RIKSO UN128 ERESO UN127 LMO DCT EVIVI L863 OKANA DCT
SOMUN DCT PODET DCT ERKIR L608 KPT L856 RAVED DCT HOC UL856 GIVRI
UM982 TINIL TINIL9E LFPG/09R
my CRZ altitude is being replaced by strange numbers that are increasing with time (refer to picture below). These figures are spreading to the next waypoint with time too. 

![image](https://user-images.githubusercontent.com/70769396/101292036-44818000-380d-11eb-8eff-01918c1ea233.png)

![image](https://user-images.githubusercontent.com/70769396/101292052-68dd5c80-380d-11eb-886f-4aeeae0a3405.png)
Figures spreading over time ABARI still OK
![image](https://user-images.githubusercontent.com/70769396/101292097-b1951580-380d-11eb-9750-a71c9ae72b4a.png)
ABARI waypoint "infected" and PENDU still OK

Note: FPL was entered manually (source Simbrief)

**To Reproduce**

1. Start C& D at LLBG (or any other airport)
2. Start-up procedure
3. Take-off and observe Altitude on F-PLN page on MCDU
4. Increasing numbers replaces step by strep over time the CRZ ALT.

**Expected behavior**
the CRZ ALT should be displayed iso increasing numbers

**Actual behavior**
Strange numbers are replacing the altitude on the F-PLN page of the MCDU

**References**
See Above 

**Additional context**
no additional context

Was this working before/when did the issue start occurring?
Couldn't say with with accuracy

Is this a problem in the vanilla unmodded game?
Unknown

Discord username (if different from GitHub):
Matt Paxton #5258

**Comment by beheh** [comment] 2020-12-08 23:28
I believe this is a duplicate of #928.

**Closed** 2020-12-16 22:39 UTC
Labels: Bug
