### ISSUE TITLE
[BUG] Vertical Speed only works after activating Open climb or open descent

### ISSUE THREAD

**Issue by riiiva** [flybywiresim/a32nx#3961] opened 2021-03-14 16:13 UTC
**Mod Version**

{
  "built": "2021-03-12T06:04:47+00:00",
  "ref": "fbw",
  "sha": "d8bfdc03a64ebbadcce8aa8f5c1b3ab21b175458",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

When pulling vertical Speed out of Alt mode it should change to V/S

**To Reproduce**

1. with autopilot engaged in cruise level with alt mode engaged pull v/s
2. when doing so nothing happens though it should
3.

**Expected behavior**

When pulling vertical Speed out of Alt mode it should change to V/S

**Actual behavior**

When pulling vertical Speed out of Alt mode it does not change to V/S

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
yes

Discord username (if different from GitHub):

as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment] 2021-03-14 16:32
Duplicate of #3857

**Closed by MisterChocker** 2021-03-14 16:32 UTC
Labels: Bug
