### ISSUE TITLE
CABIN SOUND same as COCKPIT SOUND

### ISSUE THREAD

**Issue by lalloretpilou** [flybywiresim/a32nx#1107] opened 2020-10-05 07:17 UTC
**Mod Version**
the last version of the repository

**Describe the bug**
In the last version of the repository, the view cabin 12 has the same sound as the cockpit. Can you put a cabin sound with talking passengers for example.

**To Reproduce**

1. Fixed View 12
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by hotshotp** [comment] 2020-10-05 11:05
Not a bug. The showcase fixed views play the interior sounds and they play the cockpit sounds too because of that. Passenger announcements will be added down the line and I am working on removing the cockpit sounds from the cabin

**Comment by hotshotp** [comment] 2020-11-02 04:10
I will close this as now the cabin sounds are different from cockpit. more things will come such as announcements and passenger sounds but as of now the main part of this issue is gone

**Closed by hotshotp** 2020-11-02 04:10 UTC
Labels: Enhancement
