### ISSUE TITLE
[BUG] CRASHING TO DESKTOP UPON LOADING 0.5.0 STABLE

### ISSUE THREAD

**Issue by Skymonkey75** [flybywiresim/a32nx#2628] opened 2020-12-23 00:00 UTC
**Mod Version**

0.5.0 Stable

**Describe the bug**

Doesn't matter what airport or livery I have chosen MSFS crashes to desktop while trying to load the Flybywire MODDED A320neo.  Un-modded having no issues.  New "VR" update force installed on PC today.

**To Reproduce**

1. Open MSFS - update to the newest SIM version.
2. Choose A320neo (with the Flybywire mod installed - stable)
3. Pick an remote airfield, not to taxing on the computer.

**Expected behavior**

It should load the AC on the ramp/runway.

**Actual behavior**

Crashes to desktop at the end of the loading bar into the simulation.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes, 0.5.0 was working great before Sim Update 2???

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-12-23 00:06
Caused by nonexistent fuel valves being referenced in the code. Fixed in the development version.

**Closed by Benjozork** 2020-12-23 00:06 UTC
Labels: Bug
