### ISSUE TITLE
APU will not become AVAIL/APU will not start[BUG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by Tom2018y** [flybywiresim/a32nx#2620] opened 2020-12-22 22:05 UTC
**Mod Version**

**Describe the bug**

When starting a flight cold and dark, I start the provided checklist.  After starting APU, and waiting for "AVAIL" to light up, I check the APU page on the ECAM to see it is not starting.

**To Reproduce**

1.Start flight cold and dark
2.Follow provided checklist up to starting APU
3.Push APU master on
4.Push APU start on
5. Wait and see issue arrise

**Expected behavior**

APU will not start

**Actual behavior**

APU will not start

**References**

**Additional context**

Most recent Dec. 22nd Update

Was this working before/when did the issue start occurring?
Starting occurring after most recent simulator update 
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by maxpull82** [comment] 2020-12-22 22:08
Ciao, si tutti questo problema dopo l' ultima versione di msfs. Infatti come dicevo,se provi anche a far partire in pista quindi tutto l'aereo acceso msfs crasha. Speriamo sistemino questo bug

**Comment by Benjozork** [comment] 2020-12-22 22:09
Fixed in master

**Comment by FRYYYYYY** [comment] 2020-12-22 22:09
I thought that was fixed.

https://github.com/flybywiresim/a32nx/issues/2609

**Closed by Benjozork** 2020-12-22 22:09 UTC
Labels: Bug

**Comment by maxpull82** [comment] 2020-12-22 22:12
> Risolto in master

??

**Comment by Benjozork** [comment] 2020-12-22 22:13
This is fixed in the development version.

**Comment by rokaempf** [comment] 2020-12-22 22:26
Just downloaded master and it does still not work

**Comment by FRYYYYYY** [comment] 2020-12-22 22:30
> Just downloaded master and it does still not work

Please use dev master.

**Comment by Benjozork** [comment] 2020-12-22 22:34
The issue is resolved and it's been confirmed by the QA team. Make sure you delete the A32NX folder and install the **development** (not stable!) version.

**Comment by rokaempf** [comment] 2020-12-22 23:05
Ok! It works when I use the installer, but not with direct download from github!
Also compared the the folders and they have differences!

Thanks for your work!
