### ISSUE TITLE
[REQUEST] RADIO inner decimal rotating knob enhancement 

### ISSUE THREAD

**Issue by Marenostrum66** [flybywiresim/a32nx#2991] opened 2021-01-11 10:07 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

Radio Rotating Inner knob to set decimal frequency requires a lot of scrolling. When flying online and have to rapidly change frequencies it takes too much time.

I'd like to see the **inner** rotating knob changing frequencies more rapidly when scrolled rapidly with the wheel mouse.
More or less like the heading knob (doing it too faster by the way)

**References**

no reference

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by theomessin** [comment] 2021-01-11 14:27
>BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning

Duplicate of #2002. Is currently being worked on #2980.

**Closed** 2021-01-11 15:24 UTC
Labels: Enhancement
