### ISSUE TITLE
[BUG] Visual glitches from engine heat blur

### ISSUE THREAD

**Issue by aviationenthusiast** [flybywiresim/a32nx#1224] opened 2020-10-09 14:56 UTC
**Mod Version**

It's been there all the time I think.

**Describe the bug**

The engine blast blur effect causes plane textures to glitch and white streaks of artifacts to appear along the outlines.

![Screenshot 2020-10-09 162400](https://user-images.githubusercontent.com/71930310/95597140-8f218e80-0a4e-11eb-8d90-1f98f62db5c0.jpg)
![Screenshot 2020-10-09 162333](https://user-images.githubusercontent.com/71930310/95597147-8fba2500-0a4e-11eb-963f-b2bcd380d66f.jpg)
![Screenshot 2020-10-09 164651](https://user-images.githubusercontent.com/71930310/95597752-546c2600-0a4f-11eb-8444-863317c9a979.jpg)

**To Reproduce**

1. Start a flight, preferably in day light.
2. When the engines are on, inspect the surfaces affected by the blast.

**Expected behavior**

No artifacts.

**Actual behavior**

Artifacts 

Was this working before/when did the issue start occurring?
has been there all the time.
Is this a problem in the vanilla unmodded game?
I think so.

**Comment by messer79** [comment] 2020-10-09 15:08
I confirm. I also see shaking distortion in several parts of cockpit.

Master branch as of the time posting.

**Comment by aviationenthusiast** [comment] 2020-10-09 15:15
> 
> 
> I confirm. I also see shaking distortion in several parts of cockpit.
> 
> Master branch as of the time posting.

Yup and that too. Engine blast sometimes bleeds into cockpit.

**Comment by messer79** [comment] 2020-10-09 15:32
Yes. It looks like engine exhaust bleeding into parts of console.

**Comment by Artax04** [comment] 2020-10-09 19:30
I confirm too

**Comment by calwalker1** [comment] 2020-10-11 10:18
> Engine blast sometimes bleeds into cockpit.

Those new engines are powerful hey!
But I can confirm I've also seen blurry engine exhaust artifacts in the cockpit sometimes, always put it down to having a crap GPU, but interested to hear others have experienced this as well.

**Comment by HARRY-C-T** [comment] 2020-10-17 12:37
There is a way to delete at all this effect?

**Comment by ErickSharp** [comment] 2020-10-19 04:42
Oh my god YES. This absolutely ruins the realism of the wing view. I have noticed, however, that when I am in a positive climb it doesn't happen as much. Likely because you are 'running' away from the engine blast I believe.

**Comment by HARRY-C-T** [comment] 2020-10-19 06:26
Yes, that's correct!

**Comment by MuppetOwl** [comment] 2020-12-07 13:35
I have never seen this issue. Maybe only a issue when using lower graphics settings? Or fixed in later patches as this issue is old.
Just checked now after looking on the pictures here and can not see the blur artifacts at all.

**Comment by HARRY-C-T** [comment] 2020-12-07 13:54
Any way, there is a way to remove from our a320? That's what we want.

**Comment by Watsi01** [comment] 2020-12-07 13:58
You can only remove it for the whole sim. See here:
https://forums.flightsimulator.com/t/how-to-disable-unrealistic-heat-blur-effects-from-airliner-jet-engines/331020

**Comment by MuppetOwl** [comment] 2020-12-07 14:00
You can add the lines mentioned here to A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/aircraft.cfg
https://github.com/flybywiresim/a32nx/pull/2221

I hope they don't remove it for all as this is not an issue for everyone. On Ultra settings it looks good and no artifacts.

**Comment by HARRY-C-T** [comment] 2020-12-07 16:01
Ok, many thanks, I'll try it.

**Comment by Aseinsha** [comment] 2021-06-05 19:24
This might be different but since the last sim update although the contrails have been fixed to take the wind into account the engine exhausts are not and looks quite weird.

**Closed** 2021-11-21 22:32 UTC
Labels: Bug
