### ISSUE TITLE
Autobrake Max turning off when brakes applied

### ISSUE THREAD

**Issue by FSFlyer** [flybywiresim/a32nx#4771] opened 2021-05-10 18:44 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-09T19:02:21+00:00",
  "ref": "master",
  "sha": "6afa766ce1816863f178d2567f598c83e9db6ef5",
  "actor": "Saschl",
  "event_name": "manual"
}
```

### Describe the bug

Following standard procedures for takeoff, auto brake is set to Max and whenever I apply brakes during taxi, the auto brake deactivates (essentially how it works on default MSFS aircraft)

### Expected behavior

Autobrake Max should remain on during taxi on the ground when taxing to the runway.

### Steps to reproduce

- Follow standard procedure during startup
- Set the auto brake to max
- Start taxing and then apply some brakes and it turns off

**Comment by markmiller30** [comment] 2021-05-11 02:06
Do you use a button for braking? That is the only way I could re-produce.

**Comment by tjmulls** [comment] 2021-05-11 05:07
Also can confirm issues. Current setup is key bound breaks (Left and right) as soon as key is hit, max breaking is deactivated. Not sure if this is meant to happen all not, started only setting max break and hitting T.O Config while starting the roll on the runway.

**Comment by Saschl** [comment] 2021-05-11 05:45
Also see #3042 and #3546
The issue is that the current keybinding for brake, brake left and brake right automatically resets the state of the autobrake (as already pointed out by @MStallen in #3042).
At this point I see the following possibilities:
 - Asobo changes the effect of the manual braking on the autobrake
 - We use our own variables to control the state of the autobrake or completely reimplement it (would break native compatibility with hardware that controls the autobrake via keybindings, eg. Thrustmaster TCA addons)

**Comment by Watsi01** [comment] 2021-05-12 14:06
I do understand the technical difficulties. But in my view (not using a TCA), this is a step back. We already had a working autobrake setting, which doesn't care about brakes during taxi. And now it's like a few weeks back. I don't know how many people own a TCA. Well, I guess I have to live with it. Or we implement a configuration (EFB) for those who use TCA throttles.

**Comment by nyhmbo** [comment] 2021-05-12 14:27
I have to say I cant replicate this issue with an axis bound to my pedals.
can someone else that has this problem confirm it also happens when an AXIS is bound for braking?

**Comment by Watsi01** [comment] 2021-05-12 14:54
Good question. I have just a button assigned to brakes.

**Comment by frap99** [comment] 2021-05-13 04:50
i have same problem + seatbelts sign not working + crz prog change when changing altitude during climb

**Comment by geoffda** [comment] 2021-05-14 20:03
> I do understand the technical difficulties. But in my view (not using a TCA), this is a step back. We already had a working autobrake setting, which doesn't care about brakes during taxi. And now it's like a few weeks back. I don't know how many people own a TCA. Well, I guess I have to live with it. Or we implement a configuration (EFB) for those who use TCA throttles.

This. I fixed the bug the first time because it was so annoying. TCA users with the extra module that uses the auto brakes are definitely in the minority and existing behavior should never have been broken to satisfy that case. Presumably, the workaround for the TCA case would be to bind the control to the local variable that A32NX uses (or was using).

**Comment by Saschl** [comment] 2021-05-14 20:52
The issue is: even reverting to the old state wouldn't make the situation much better (besides the "ON" light). Take a look at the screenshot from the current stable version 
![image](https://user-images.githubusercontent.com/19493808/118328755-6989c580-b506-11eb-97e4-201aea781e73.png)
We have the light but the actualy variable the controls the autobrake system is 0 (should be 4 for RTO). That way we will not get Autobrake MAX at all. 
One could say that with the current state at least we see that it's deactivated... But I agree it's annoying and I still don't understand why the brake "button" binding does that. However, I'm already looking into a way to force the sync again so we don't lose the setting when braking.

**Comment by Watsi01** [comment] 2021-05-15 07:25
Thanks @geoffda  and @Saschl for your comments. I just feared, that this would be the state for the next weeks/months. And then disappears in the deep darks of the issues section.
I didn't know that the autobrake actally wasn't activated, even with the light on. Never made a rejected takeoff... lol

It's good to know, that there is someone still thinking about how to solve this. I hope there's a work around all can live with.

**Comment by MStallen** [comment] 2021-05-17 10:04
I have a solution for my system wuth a VrInsight Combo

On the Combo I assigned 3 buttons (FSUIPC.ini param 1,2 and 3 for the LUA)  for the autobrake setting and they run the next LUA:

LastAutoBrakePos = ipc.readUB("66D0")
if ipcPARAM == LastAutoBrakePos then
	ipc.writeUB("2F80",1)
	ipc.writeUB("66D0",0)
	ipc.control(32802)
elseif ipcPARAM == 1 then
	ipc.writeUB("2F80",0)
	ipc.writeUB("66D0",1)
	ipc.control(32803)
elseif ipcPARAM == 2 then
	ipc.writeUB("2F80",0)
	ipc.writeUB("66D0",2)
	ipc.control(32804)
elseif ipcPARAM == 3 then
	ipc.writeUB("2F80",0)
	ipc.writeUB("66D0",3)
	ipc.control(32805)
end
32802 = 34=MobiFlight.XMLVAR_Autobrakes_Level_OFF
....
....
....
32805 = 37=MobiFlight.XMLVAR_Autobrakes_Level_MAX
in my .evt-File

Also I programmed my brake-button in the FSUIPC-ini file:
313=PA,1,Cx01002F80,x00 	-{offset byte set, offset 2F80}-
314=UA,1,Cx01002F80,x00 	-{offset byte set, offset 2F80}-
315=B66D0=3 PA,1,C32805,0 	-{:MobiFlight.XMLVAR_Autobrakes_Level_MAX}-
316=B66D0=3 UA,1,C32805,0 	-{:MobiFlight.XMLVAR_Autobrakes_Level_MAX}-

If I push or release my brakes the 2F80 goes back to 0 (because breaking sets this to 1) and
if 66D0 was still on autobrake-max it reengages C32805 (XMLVAR_Autobrakes_Level_MAX)
I use the value in 66D0 for my Autobrake-indicators so they match the A32NX

Works like a charm for me and autobraking is actually working

**Comment by Saschl** [comment] 2021-05-19 10:30
Good news is that the inclusion of brakes + hydraulics will prevent this from happening as we handle the event ourselves. Depending on the progress I'll check whether we'll have an intermediate solution or not.

**Comment by Watsi01** [comment] 2021-05-28 16:02
You can do that. But then, the autobrake won't disconnect when you manually break after landing.

**Comment by crocket63** [comment] 2021-05-29 14:07
Let's not do that then :)  I guess we'll solve this definitly when doing our own autobrake

**Closed** 2021-07-05 08:23 UTC
Labels: Bug, Hydraulics
