### ISSUE TITLE
Seperate PF and PM FMGS Screens

### ISSUE THREAD

**Issue by ecortinas** [flybywiresim/a32nx#7433] opened 2022-08-23 02:46 UTC
### Aircraft Version

Development

### Description

Any change that the MCDU screen will eventually be independent so I can have on screen on pilot side and a different screen on co-pilot side?

**Comment by Benjozork** [comment] 2022-08-23 05:28
This will be done because it exists in the real plane (therefore it isn't necessary to request it). However as every feature it that isn't yet available, other things need to happen beforehand and a lot of work is involved.

**Comment by 2hwk** [comment] 2022-09-05 09:40
Duplicate of https://github.com/flybywiresim/a32nx/issues/1058 closing.

**Closed by 2hwk** 2022-09-05 09:40 UTC
Labels: Request
