### ISSUE TITLE
[REQUEST] Add energy circle

### ISSUE THREAD

**Issue by krangerich** [flybywiresim/a32nx#2930] opened 2021-01-07 18:35 UTC
**Is your feature request related to a problem? Please describe.**
Improve realism. SOPs for approach require monitoring the flight path in HDG/TRK mode using the energy circle

**Describe the feature you'd like to see implemented**

The energy circle is a green arc shown on ND during approach, when in HDG or TRK mode. 

**References**

FCOM, 22-20-40-30
![image](https://user-images.githubusercontent.com/7890659/103929522-ba834a80-511d-11eb-964a-ab2bea174752.png)
![image](https://user-images.githubusercontent.com/7890659/103929637-e43c7180-511d-11eb-8260-586f541bdd8b.png)

FCOM 31-45
![image](https://user-images.githubusercontent.com/7890659/103929699-f7e7d800-511d-11eb-8369-6b6334e108d2.png)

**Additional context**

Explanation in the FCOM is vague an ambigious. The prediction involves deceleration to Vapp, but that doesn't mean, that the aircraft immediately decerelates to Vapp at current altitude and then descents, but rather a normal descent at the usual descent speed of the current flight profile, then decelerating to Vapp during the approach. 

Pilot input might be required for details (does wind affect the calculation and so on)

Discord username (if different from GitHub):
n/a

**Comment by MisterChocker** [comment] 2021-01-07 18:44
Duplicate of #856

**Closed by MisterChocker** 2021-01-07 18:44 UTC
Labels: Enhancement
