### ISSUE TITLE
[BUG] Airplane gets out of the route

### ISSUE THREAD

**Issue by jcalor** [flybywiresim/a32nx#3255] opened 2021-01-31 13:39 UTC
**Mod Version**
0.5.2

**Describe the bug**
Yesterday on a flight between EIDW and EDDF with A32NX v0.5.2, while cruising, I´ve changed CI from 18 to 80. Inmediatly after doing it, airplane started to turn left increasing more and more the  bank angle completly ignoring the FD.

UPDATE 31/01 16:48z: I´ve did another flight and this continue happens without changing CI. I don´t know what is causing this, but is unflyable.

**To Reproduce**
1. Depart from whatever airport and climb until cruise level
2. See if the plane turns heavily to the left ignoring FD
3.

**Expected behavior**
n/a

**Actual behavior**
Airplane will start to turn left with more and more bank angle

**References**
Didn´t take screenshots nor videos, n/a

**Additional context**

Was this working before/when did the issue start occurring? Was my first flight with A32NX

Is this a problem in the vanilla unmodded game? I didn´t try it, don´t know

Discord username (if different from GitHub): Jorge#6816

**Comment by dnoe10** [comment] 2021-01-31 21:27
I experienced the same issue on a flight from RJFU to RJCC. At some point during cruise, without making any input, the airplane went into a hard left (more than 45 degrees bank angle) turn. I was on the dev build and I switched over to stable after that.

**Comment by jcalor** [comment] 2021-01-31 21:31
Hi, but your problem was a puntual problem or happens on all of your flights? For me happens yesterday on a EIDW-EDDF and today on a EHAM-EGLL. I'm using stable version (0.5.2)

**Comment by mreza1st** [comment] 2021-01-31 22:30
I experienced the same issue yesterday on two routes (OIAW to OITT and OITT to OIII). The plane went off route during the descent skipping a few waypoints.

**Comment by dnoe10** [comment] 2021-02-01 05:30
I experienced the same issue even after switching to stable. Seems to happen as the aircraft is approaching the DECEL point of the approach. This has happened to me on 3 flights in a row now.

**Comment by AbAndyBar** [comment] 2021-02-01 11:54
Expirienced this since yesterday. I dont have installed something. Happend on three Flights now, Airplane went off the Route direct to Runway and skip the Star at descent. Very annoying problem. I´m on stable 0.5.2

**Comment by FGrabi** [comment] 2021-02-01 16:09
Experienced the same on the last flights (TFFR-MDPC via ANTE1W STAR and MDPC-MMMD via NAPRA1A STAR). As soon as the Transition WPT is reached the Plane skips the STAR WPTs and takes course direct to the Rwy - gives a bit of stress, especially if one is flying with online ATC like IVAO. If one immediately after the STAR route is skipped, uses the DIR TO for the next original WPT, the aircraft uses the STAR approach. Have this since I updated the Navigraph to the actual AIRAC cycle 2101

**Comment by LEDFlighter** [comment] 2021-02-01 16:23
I normally fly with the latest development-version and I also had this problem the last few flights. Very annoying, especially when you fly on IVAO... one time it was fixed by turning off the middle flight-controls, another time by switching on and off the crash-mechanics in the menu...

**Comment by Benjozork** [comment] 2021-02-01 16:29
Please keep the issue on topic.

The plane skipping STAR waypoints is already reported in #939.

For the banking issue, this is 99% of the time caused by the deadzone being set too low in sensitivity settings of your controller.

**Comment by LEDFlighter** [comment] 2021-02-01 16:34
> 
> 
> Please keep the issue on topic.
> 
> The plane skipping STAR waypoints is already reported in #939.
> 
> For the banking issue, this is 99% of the time caused by the deadzone being set too low in sensitivity settings of your controller.

I fly with my keybord because i don't have a controller at the moment, so i don't have any deadzone set and don't need a deadzone... my plane does not only skips STAR-Waypoints, but circles around with left-turns after departure!

**Comment by Benjozork** [comment] 2021-02-01 16:37
That is most likely caused by bad design of the MSFS keyboard inputs - nothing is automatically centered so when you set an aileron input with your keyboard it stays like this until you manually center it. Nothing we can do about it.

**Comment by LEDFlighter** [comment] 2021-02-01 16:39
> 
> 
> That is most likely caused by bad design of the MSFS keyboard inputs - nothing is automatically centered so when you set an aileron input with your keyboard it stays like this until you manually center it. Nothing we can do about it sadly.

But shouldn't the AP then take the controls and center the ailerons? For the rudder i have set up a key for manual centering.

**Comment by Benjozork** [comment] 2021-02-01 16:40
It should, but the MSFS autopilot is incorrectly programmed.

**Comment by HiggsBoson777** [comment] 2021-02-01 16:50
Same issue here. Perhaps it has to do with the new AIRAC?

Never knew people actually tried to fly with a keyboard....oh boy....LOL!

**Comment by dnoe10** [comment] 2021-02-01 16:52
For what it's worth, I started experiencing both the STAR waypoints and the hard banking issues on the same day after having used this mod for months. For the banking issue, I can try changing the sensitivity, but the banking occurred with the AP fully on. In fact, the way to get rid of the issue was to fly the plane manually past the DECEL point and then re-engage the approach.

**Comment by Benjozork** [comment] 2021-02-01 17:04
> the banking issue, I can try changing the sensitivity, but the banking occurred with the AP fully on

The AP being on does not prevent aileron inputs from overriding the AP as the default MSFS behavior is incorrect

**Comment by LEDFlighter** [comment] 2021-02-01 18:08
> 
> 
> It should, but the MSFS autopilot is incorrectly programmed.
> 
> Try setting a key for aileron centering

Ohhh noo, then i wait until the FBW-Autopilot is finished! Yes thanks, i try to center it manually with a key...

**Comment by FGrabi** [comment] 2021-02-01 20:08
I always use the actual Dev using the Installer before I start. Had no problems with banking (Deadzone is big enough), only with the STARS. I'm just on my way to MUHA (IVA-Worldtour) with STAR FARAC3 for RNAV Approach Rwy 24.
Reached MUHA. STAR again "broken". After passing the FARAC3 Transition NAKRO, the plane goes direct to MUNBA (Transition for RNAV 24) and skipped the next WPTs on the STAR (FARAC, JUGAR, AFFIL). After DIR-TO -> FARAC it skips the next WPTs on the STAR and goes direct to the Rwy. Again I used DIR TO, this time to the RNAV Transition MUNBA and was able to use the APPR after I reached MUNBA. Maybe this has to do with the actual AIRAC.

**Comment by Asianblade** [comment] 2021-02-02 01:38
Alright everyone, here's a conclusion. No staff will be reviewing this bug forum since it is a known issue since the very beginning, and trust me, Asobo and FBW is working very hard on it. A point I also want to point out is, don't fly with the stable version, it is very far behind, just download the dev version since it actually works quite well.

**Comment by Asianblade** [comment] 2021-02-02 01:40
> **Mod Version**
> 0.5.2
> 
> **Describe the bug**
> Yesterday on a flight between EIDW and EDDF with A32NX v0.5.2, while cruising, I´ve changed CI from 18 to 80. Inmediatly after doing it, airplane started to turn left increasing more and more the bank angle completly ignoring the FD.
> 
> UPDATE 31/01 16:48z: I´ve did another flight and this continue happens without changing CI. I don´t know what is causing this, but is unflyable.
> 
> **To Reproduce**
> 
> 1. Depart from whatever airport and climb until cruise level
> 2. See if the plane turns heavily to the left ignoring FD
> 
> **Expected behavior**
> n/a
> 
> **Actual behavior**
> Airplane will start to turn left with more and more bank angle
> 
> **References**
> Didn´t take screenshots nor videos, n/a
> 
> **Additional context**
> 
> Was this working before/when did the issue start occurring? Was my first flight with A32NX
> 
> Is this a problem in the vanilla unmodded game? I didn´t try it, don´t know
> 
> Discord username (if different from GitHub): Jorge#6816

This is fixed very long ago. Pay attention. Go to known-issues on the discord, and FIX YOUR DEADZONES on msfs.

**Comment by jcalor** [comment] 2021-02-02 08:32
Thanks, I will try.

**Comment by AbAndyBar** [comment] 2021-02-02 11:19
Not working for me, Deadzones all above 10. The Problem is that the plane doesn`t follow the FP in the last part of the flight, it skips a few waypoints and go straight to the Runway. Its working fine a few days ago, but now the problem ocurs on every flight.

**Comment by Asianblade** [comment] 2021-02-02 11:39
> Not working for me, Deadzones all above 10. The Problem is that the plane doesn`t follow the FP in the last part of the flight, it skips a few waypoints and go straight to the Runway. Its working fine a few days ago, but now the problem ocurs on every flight.

Yup, this is the issue I’m also talking about. Skipping the FP and going direct to a runway, isn’t caused by the dead zone issue. It is a problem that the sim has from the very start. And flying into pretty well known airport/places will prevent this issue slightly, since Aspbo will focus a bit more on popular areas. As I asked staff members, Asobo and FBW is fixing this issue and it’s in progress. Thanks

**Comment by Asianblade** [comment] 2021-02-02 11:40
> Not working for me, Deadzones all above 10. The Problem is that the plane doesn`t follow the FP in the last part of the flight, it skips a few waypoints and go straight to the Runway. Its working fine a few days ago, but now the problem ocurs on every flight.

Also, are you using the stable version? If yes, that is the reason, download the development version.

**Comment by AbAndyBar** [comment] 2021-02-02 11:50
Thanks for your answer. I‘m now on latest Developer Build but the problem is still present.

**Comment by iFred320** [comment] 2021-02-02 12:03
Confirming that on some point during approach the plane does not follow the flight path. Was ok for me with the last builds, but today it start to happen again. (knowing that this is a speculation: New Navdata secretly added by Asobo or Navigraph?).

**Comment by AbAndyBar** [comment] 2021-02-02 12:21
Something happened, it worked last week without any problems.

**Comment by Asianblade** [comment] 2021-02-02 12:28
> Yup, this is the issue I’m also talking about. Skipping the FP and going direct to a runway, isn’t caused by the dead zone issue. It is a problem that the sim has from the very start. And flying into pretty well known airport/places will prevent this issue slightly, since Aspbo will focus a bit more on popular areas. As I asked staff members, Asobo and FBW is fixing this issue and it’s in progress. Thanks



> Something happened, it worked last week without any problems.

So, as you can see on this comment, It is a common issue, that the waypoints are broken, so the devs are working hard to fix it. On complex approaches (like around terrain, ILS 360’s), I also have experienced this issue many many times before. Well, I contacted staff, they’re trying their best.

**Comment by Benjozork** [comment] 2021-02-02 15:02
Alright, going to clear up some information being spread here.

1. If your plane does not follow the flight plan during the entire flight or during departure / cruise, your issue is deadzones.

2. The stable and development build have the exact same autopilot.

3. The STAR not being followed is an MSFS autopilot issue that is being resolved via a custom flight plan manager, part of the upcoming custom AP. It did not start happening recently, it's always been a problem. It is being tracked in #939.

**Comment by LEDFlighter** [comment] 2021-02-02 17:16
> 
> 
> Alright, going to clear up some misinformation being spread here.
> 
>     1. If your plane does not follow the flight plan during the entire flight or during departure / cruise, your issue is deadzones.
> 
>     2. The stable and development build have the exact same autopilot.
> 
>     3. The STAR not being followed is an MSFS autopilot issue that is being resolved via a custom flight plan manager, part of the upcoming custom AP. It did not start happening recently, it's always been a problem since the sim launched. It is being tracked in #939.

I just want to say, that I often have the problem that the Autopilot isn't following the Flight-Director right after departure and banking extremely to the left... sometimes i can fix this (by turning on/off some of the flight controls or something), sometimes i can't. That's really annoying.

**Comment by HiggsBoson777** [comment] 2021-02-02 20:56
> Alright, going to clear up some misinformation being spread here.
> 
> 1. If your plane does not follow the flight plan during the entire flight or during departure / cruise, your issue is deadzones.
> 2. The stable and development build have the exact same autopilot.
> 3. The STAR not being followed is an MSFS autopilot issue that is being resolved via a custom flight plan manager, part of the upcoming custom AP. It did not start happening recently, it's always been a problem since the sim launched. It is being tracked in #939.

I have to disagree with you on that one; it is not misinformation! First off, the aircraft was flying great at one point, obviously something happened in the background to cause this. I suspect a problem with the interaction between the new AIRACS; but what do I know. Secondly, the deadzones theory has already been discussed without success, check out https://github.com/flybywiresim/a32nx/discussions/2316. 

The project is wonderful and the hard work is greatly appreciated. However, I think there is way too many people working on it. One thing gets fixed and it causes two more issues. One other thing get implemented, here are more issues.

**Comment by AbAndyBar** [comment] 2021-02-02 21:13
@HiggsBoson777 

That's exactly what i tried to say, it worked without issues due the weekend but something happened in the meantime.

**Comment by MjrIncident** [comment] 2021-02-03 11:59
I have been experiencing the same behaviour again as described by OP in the last 2-3 days. On approach, it loses the waypoint and banks left and sets next waypoint to the end of the intended approach runway. As mentioned, I can DIR to next waypoint and the FD resumes correct control.
Using Dev mod btw - it hadnt done this for me for a few weeks, but started again 2-3 days ago.
I re-flew the flight at a much slower approach speed and the bug didnt happen.

It does seem to be something to do with speed+rate of turn imo. Slower speed and less turning and it stays on course. Faster speed and more dramatic turns and it loses the waypoint. Why it reselects the last wp (runway end) by itself I do not know. Don't think it's controller deadzones or wouldn't it do this with every aircraft and/or every flight?

**Message to you DEVS - You are FRIGGING AMAZING. Well done guys. Truly incredible what you are accomplishing here.
During this lockdown, you are providing us all with UNLOCK capabilities ;-) Thank you.**

**Comment by Saschl** [comment] 2021-02-03 12:20
> > Alright, going to clear up some misinformation being spread here.
> > 
> > 1. If your plane does not follow the flight plan during the entire flight or during departure / cruise, your issue is deadzones.
> > 2. The stable and development build have the exact same autopilot.
> > 3. The STAR not being followed is an MSFS autopilot issue that is being resolved via a custom flight plan manager, part of the upcoming custom AP. It did not start happening recently, it's always been a problem since the sim launched. It is being tracked in #939.
> 
> I have to disagree with you on that one; it is not misinformation! First off, the aircraft was flying great at one point, obviously something happened in the background to cause this. I suspect a problem with the interaction between the new AIRACS; but what do I know. Secondly, the deadzones theory has already been discussed without success, check out #2316.
> 
> The project is wonderful and the hard work is greatly appreciated. However, I think there is way too many people working on it. One thing gets fixed and it causes two more issues. One other thing get implemented, here are more issues.

Many people working on this project is not an issue. The problems described here are all caused by the default AP and default flightplan manager (which are in the process of being rewritten from scratch to solve exactly these issues). 

The way these bugs appear might lead to the conclusion that some recent changes in the mod might be the fault, but the reality is that these bugs are somewhat "random".

The deadzone issue for example is highly dependent on the peripherals one is using. For me it never appeared but I know it exists.

**Comment by radug112** [comment] 2021-02-06 20:57
Confirming that this indeed is a new issue. Never appeared until today for me. (on latest Dev build as of 6th Feb 08,54 UTC. Aircraft banks left and goes in circles after DECEL point, and i need to go in HDG mode to catch it. Right turn also happens when activating LOC from HDG mode. 

I don't think it's related to either deadzones or STAR known bug, as I have never encountered these before today.

Happened to both legs on EGLL-EGPH-EGLL flight.

**Comment by Benjozork** [comment] 2021-02-06 21:13
> I have to disagree with you on that one; it is not misinformation! First off, the aircraft was flying great at one point, obviously
> something happened in the background to cause this. I suspect a problem with the interaction between the new AIRACS; but
> what do I know. Secondly, the deadzones theory has already been discussed without success, check out #2316.
>
> The project is wonderful and the hard work is greatly appreciated. However, I think there is way too many people working on it.
> One thing gets fixed and it causes two more issues. One other thing get implemented, here are more issues.

Before you come and claim things without having the full picture, I would ask you to consider the general situation that affects every single add-on user.

We have more than a thousand people flying this addon online every day, hundreds of support requests on Discord and elsewhere. We understand very well the issue that plagues the default AP and flight plan sequencing, and unless you have additional information / proof to bring to the tablet, I will consider the greater amount of information we have over one or two comments.

For once, your claim of " First off, the aircraft was flying great at one point, obviously something happened in the background to cause this" is a logical fallacy that fails to prove anything. You do realize that a large share of programming bugs and erroneous behavior is not simply "always works" or "never works", right ? Issues might not appear for your for months, it does not mean that the issue started existing the moment *you* noticed it.

Second, "Secondly, the deadzones theory has already been discussed without success, check out #2316.": the discussion ticket you linked is completely unrelated to the aircraft flying in circles.

Third, " I think there is way too many people working on it. One thing gets fixed and it causes two more issues. One other thing get implemented, here are more issues.". I would please ask you to study software engineering practices before making comments like this.

**Comment by HiggsBoson777** [comment] 2021-02-12 19:13
What a crappy answer! I do have to disagree with you once again! First off, judging by the amount of posts about the aircraft leaving the route and unexpected left turns; I assume that was claims are valid. It is clear that I am not the only one who unexpectedly experienced this after every was fine; but yet again, that might be logical fallacy that fails to prove anything bull crap. 

As far as my comments about too many people working on it, you don't need to be a software engineer to get that people don't give a damn about the printer's print speed and half-ass EFB when the plane can't even hold its route.

Oh and by the way, the only reason I spoke of the deadzones in my comment is was in response to your lame excuse for the plane's route departure.

Have a wonderful day

**Comment by LEDFlighter** [comment] 2021-02-12 19:17
Okay i got news for you, i have set a key to center my ailerons and if i press it before every flight, the Autopilot works just fine!

**Comment by Benjozork** [comment] 2021-02-12 19:39
@HiggsBoson777 You will correct your abhorrent and impolite tone right now or you're getting permanently banned from this GitHub. There are ways to express your criticism, but childish ranting is not one we will tolerate.

**Comment by Benjozork** [comment] 2021-02-12 19:47
> Okay i got news for you, i have set a key to center my ailerons and if i press it before every flight, the Autopilot works just fine!

Glad to hear your issues are resolved!

**Comment by dnoe10** [comment] 2021-02-16 06:42
Confirming that the banking issue was fixed by increasing deadzones, and the STAR waypoints issue was fixed by managing speed better.

**Comment by MisterChocker** [comment] 2021-03-05 10:33
Closing since reported issues are a) duplicates or b) have been resolved.

**Closed by MisterChocker** 2021-03-05 10:33 UTC
Labels: Bug
