### ISSUE TITLE
[BUG] RADIAL IN/DIR

### ISSUE THREAD

**Issue by IlanMoshe** [flybywiresim/a32nx#3459] opened 2021-02-10 14:06 UTC
Mod Version
"built": "2021-01-09T06:59:30+00:00",
"ref": "refs/remotes/upstream/HEAD",

**Describe the bug**
I have a problem with the "RADIAL IN".
After I entered a waypoint, I can define the RADIAL IN, I entered the Heading and press on RADIAL IN but nothing happened.

![image](https://user-images.githubusercontent.com/66770470/107519881-74585580-6bb9-11eb-9178-8f84df5b069e.png)

**To Reproduce**

1. DIR
2. Select a waypoint and press on waypoint filed (OK)
3. Select an heading and press on RADIAL IN filed (nothing happened)

**Expected behavior**
Expect to see the heading entered in the field RADIAL IN and the airbus will stay in the choose heading until reaching the radial inbound navigation solution.

**Actual behavior**
Nothing happened

**Comment by beheh** [comment] 2021-02-10 15:04
Duplicate of #897

**Closed by beheh** 2021-02-10 15:04 UTC
Labels: Bug

**Comment by IlanMoshe** [comment] 2021-02-10 15:52
I did exactly the same procedure show in this link but it is not working. https://drive.google.com/file/d/1qwuQMrcxh82K86Ig6qpsVxg87zw7cQ0O/view

**Comment by beheh** [comment] 2021-02-10 16:35
Yes - your issue has not been closed because it was fixed, but because someone else reported it first in #897. That way we don't have the same issue tens of times. For progress updates please that issue.

**Comment by IlanMoshe** [comment] 2021-02-10 16:37
Ah okay, sorry :)
Thank you
