### ISSUE TITLE
No throttle setting in the aircraft tablet

### ISSUE THREAD

**Issue by calou952002** [flybywiresim/a32nx#4726] opened 2021-05-06 12:31 UTC
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Hello,

When I consult the tablet in the plane, I don't see the adjustments for the throttle, there are missing.
I have the CH Product throttle controller correctly configured; I use basic livreries.

Which function in the aircraft is used to display these missing settings.

Thank you for your help.

Pascal Massonneau

### Expected behavior

Is it the correct version of the plane ?

### Steps to reproduce

The bug is when aircraft loading

**Comment by tshomas** [comment] 2021-05-06 12:32
You’re currently on stable, the throttle calibration tool is on the development version of the mod, please install that one if you’d like to use it!

**Comment by MisterChocker** [comment] 2021-05-06 12:37
Closing since working as intended.

**Closed by MisterChocker** 2021-05-06 12:37 UTC
Labels: Bug

**Comment by calou952002** [comment] 2021-05-06 13:42
Thank you for your answer.Pascal 
-------- Message d'origine --------De : Shomas ***@***.***> Date : 06/05/2021  14:33  (GMT+01:00) À : flybywiresim/a32nx ***@***.***> Cc : calou952002 ***@***.***>, Author ***@***.***> Objet : Re: [flybywiresim/a32nx] No throttle setting in the aircraft tablet (#4726) 

You’re currently on stable, the throttle calibration tool is on the development version of the mod, please install that one if you’d like to use it!
