### ISSUE TITLE
Cannot Link With Simbrief

### ISSUE THREAD

**Issue by Halobiont** [flybywiresim/a32nx#6350] opened 2021-12-12 19:39 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-11T21:50:08+00:00",
  "ref": "master",
  "sha": "a67929151b900ead0589f00d7c58556562c48a75",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

In the current development build the username or pilot ID will not "connect" with Simbrief.  When I enter either username or pilot id then move to a different tab and come back the field is once again blank.  If I type in the id the cursor keeps blinking until I click somewhere else on the efb.  When I click back on the box the cursor is blinking again.  Also while the cursor is blinking, the logitech  G700 mouse pre programmed view buttons will not work but they work if I click out of the input box for Simbrief ID.  None of the mouse clicks work in this mode. Hitting enter on the keyboard has no effect.  While the username or id is in the box and I click elsewhere on the flypad and the name stays I still get "No Simbrief User" on the MCDU.  Sometimes I see Simbrief error in red by the box on the flypad but it seems random.  I can't reproduce that.  Most of the time nothing happens, sometimes the box goes blank on it's own.

MSFS2020 Version:

- 1.21.13.0

Hardware:

- Alpha and Bravo Honeycomb, G700 mouse

Things I've tried:

- Turning off all items in the community folder, using addon linker
- No FSUIPC7
- Disconnect Honeycomb
- Turning off Malwarebytes and Firewall
- Allowing Simbrief and MSFS folders on Malwarebytes
- Stable version on the MCDU won't work either.  When I click on LS1 to input the id it stays blank
- Tried a different simple non-gaming mouse, same exact behavior as described above

### Expected behavior

I expect to enter my Simbrief Pilot ID or Username and be able to import the flight plan on the MCDU under Init A.  I did try to get support on Discord and the admin took my id and was able to load a flight plan which suggests this is a hardware conflict of some kind.

### Steps to reproduce

1. Start Neo at KIAH on ramp or runway **without** loading a flightplan from World
2. Power up with ground power
3. Start EFB
4. Go to Settings
5. Try to enter Pilot ID or Username

### Additional info (optional)

Development a679291

I don't have Simbrief integration problems with PMDG or FSLabs on P3D so I don't think it's a firewall issue.

### Discord Username (optional)

Halobiont#9809

**Comment by Halobiont** [comment] 2021-12-13 22:37
I've let through simbrief.com on Malwarebytes but this didn't help.
I'm able to see the correct api in my browser from Simbrief.

**Comment by tracernz** [comment] 2021-12-14 06:58
Are you able to enable MSFS dev mode, load in and try your steps to reproduce, and with the sim and aircraft still in the background point your web browser at http://127.0.0.1:19999, and check the console tab. There should be a number of messages, and a few red ones at the end where it couldn't load source files for the debugger... but higher up near the start it might have a red or yellow HTTP error of some kind.

**Comment by Halobiont** [comment] 2021-12-14 16:00
NOTIFICATION [coui://html_UI/Pages/Notifications/Notifications.html?type=MESSAGE|STACKABLE|OVERLAY&theme=TIPS|GAMEPLAY|INFO|SCORE]
    NOTIFICATION [coui://html_UI/Pages/Notifications/Notifications.html?type=POPUP|MESSAGE|OBJECTIVE|ACTION_STEP|SUBTITLES&theme=SYSTEM]
    Page 5 [coui://html_UI/Pages/TooltipAtlas/TooltipAtlas.html]
    Flight Briefing [coui://html_UI/Pages/FlightPlanning/FlightBriefingPage.html]
    Flight planning [coui://html_UI/Pages/FlightPlanning/FlightPlanningPage.html]
    VLivery01 [coui://html_UI/Pages/VLivery/Core/VLivery.html]
    VLivery02 [coui://html_UI/Pages/VLivery/Core/VLivery.html]
    VLivery03 [coui://html_UI/Pages/VLivery/Core/VLivery.html]
    Page 13 [coui://html_UI/Pages/Transition/Transition.html]
    Page 16 [coui://html_UI/Pages/ActivitiesBackground/ActivitiesBackground.html]
    VCockpit01 - PFD_TEMPLATE_1 [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit02 - ND_TEMPLATE_1 [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit03 - A320_Neo_EICAS_1 [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit04 - A320_Neo_EICAS_2 [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit05 - ISIS_TEMPLATE [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit06 - Clock_TEMPLATE [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit07 - DCDU_TEMPLATE [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit08 - A320_Neo_CDU [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit09 - A320_Neo_FCU [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit10 - RMP_TEMPLATE [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit11 - ATC_TEMPLATE [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit12 - RTPI_TEMPLATE [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit13 - BAT_TEMPLATE [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit14 - PFD_TEMPLATE_2 [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit15 - ND_TEMPLATE_2 [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit16 - EFB_TEMPLATE [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    VCockpit17 - WasmInstrument - WasmInstrument - WasmInstrument [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]
    Page 38 [coui://html_UI/Pages/Pause/Pause.html]
    VLogic [coui://html_UI/Pages/VCockpit/Core/VCockpitLogic.html]
    Page 40 [coui://html_UI/Pages/InGameMarkers/InGameMarkers.html]
    Page 41 [coui://html_UI/Pages/InGameMarkers/InGameMarkers.html]
    Page 43 [coui://html_UI/Pages/ToolBar/ToolBar.html]
    CAMERA [coui://html_UI/ingamePanels/GenericPanel/GenericPanel.html]
    FUEL [coui://html_UI/ingamePanels/PanelFuelPayload/PanelFuelPayload.html]
    Navigraph Charts [coui://html_UI/ingamePanels/NavigraphPanel/NavigraphPanel.html]

**Comment by Halobiont** [comment] 2021-12-14 16:15
Now checking the console.  Searched on Neo and Flypad.  Here is some of what I saw that might be relevant.

VFS Bitmap Loader | Attempt to load texture for incompatible texture slots. This is not supported; please duplicate your texture: 'vfs://flybywire-aircraft-a320-neo/SimObjects/Airplanes/FlyByWire_A320_NEO/texture/FLYPAD_NORM.PNG.DDS'.

Behaviors XML
File: A320_NEO_INTERIOR.xml
Model verification
No matching animation "ANIM_NAME".
	ID: PUSH_EFB_SIDE
	Node: PUSH_EFB_SIDE
	Animation: ANIM_NAME
	PartIds: 

Behaviors XML
File: A320_NEO_INTERIOR.xml
Component: EFB:PUSH_EFB_SIDE
Template parameter #ANIM_NAME# not found. Ignoring.
	Path : EFB:PUSH_EFB_SIDE/PUSH_EFB_SIDE
	UseTemplate Path:
		ASOBO_GT_PUSH_BUTTON
		ASOBO_GT_ANIMTRIGGERS_2SOUNDEVENTS

Also got some red x's on the elevator trim and autopilot.

**Comment by Halobiont** [comment] 2021-12-14 16:16
Searched on http in the console.  Nothing.  216 errors and 314 warnings total.

**Comment by Halobiont** [comment] 2021-12-14 20:54
That throws over a dozen red x's on the console.  They all start with [Coherent GT] Failed to locate file vfs:///html_ui/.......

**Comment by Benjozork** [comment] 2021-12-14 20:57
Can you please show a screenshot ?

**Comment by Halobiont** [comment] 2021-12-14 20:59
![Clipboard01](https://user-images.githubusercontent.com/96021260/146078508-137dd7ab-c94d-4bcf-a5bf-228f33c52063.jpg)

**Comment by Halobiont** [comment] 2021-12-14 21:02
This is what console shows when I click on VC Cockpit 08

**Comment by Halobiont** [comment] 2021-12-14 21:05
![Clipboard02](https://user-images.githubusercontent.com/96021260/146079168-c34179d9-1486-491c-a78e-c1deb08a9610.jpg)

**Comment by Halobiont** [comment] 2021-12-14 21:05
Here is what I see on the browser

**Comment by Halobiont** [comment] 2021-12-14 21:06
I've reinstalled several times using the installer.

**Comment by Halobiont** [comment] 2021-12-14 21:13
Everything else on the EFB and aircraft seem to function correctly

**Comment by Halobiont** [comment] 2021-12-14 21:16
I can view Navigraph charts no problem

**Comment by Benjozork** [comment] 2021-12-14 21:22
You did not click on Console. You are on the Elements tab.

Also, please try to avoid posting many messages one after the other, it is a bit spammy.

**Comment by Halobiont** [comment] 2021-12-14 21:27
In dev mode windows->Console.  The window says console at the top.  That's the screenshot I uploaded.  I don't understand.

**Comment by tracernz** [comment] 2021-12-14 21:32
> ![Clipboard02](https://user-images.githubusercontent.com/96021260/146079168-c34179d9-1486-491c-a78e-c1deb08a9610.jpg)

See the far right on this one... console tab.

**Comment by tracernz** [comment] 2021-12-15 00:58
> [Error] Error: No SimBrief pilot ID provided
getSimBriefOfp (a32nx_atsu.js:139)

What do you have on the flyPad Settings -> ATSU/AOC page?

**Comment by Halobiont** [comment] 2021-12-15 01:31
I see the Simbrief username/pilotid box.  

I put in my username and the cursor just keeps blinking at the end of the username.  While it's blinking the mouse won't work anywhere in the sim.  Hitting enter does nothing.

If I click out on the ATSU/AOC page anywhere the cursor stops blinking and I can use the mouse however I still get the error on the MCDU when trying to init.

If I go to another page on the Flypad and come back the field is blank again.

It's like the username or id won't "stick"  Occasionally I see Simbrief Error flash but that's random.  


![Clipboard01](https://user-images.githubusercontent.com/96021260/146106277-b90245d6-5dd2-42cc-b1b4-58fd931f84f9.jpg)

**Comment by tracernz** [comment] 2021-12-15 01:51
Seems like it's something wrong with your internet/router/firewall blocking SimBrief? I can put your username and it works fine:

![image](https://user-images.githubusercontent.com/9995998/146108198-c1f84506-d35e-4266-a7e5-5eb899c110ab.png)
![image](https://user-images.githubusercontent.com/9995998/146108213-b77e37b4-fc22-4319-8d09-35f5de080053.png)
![image](https://user-images.githubusercontent.com/9995998/146108141-c0f2c715-c211-4520-ad23-842557c77c58.png)

There is also a lack of error handling apparently because the EFB shouldn't silently fail when it can't fetch your username (cc @ErickSharp ).

**Comment by ErickSharp** [comment] 2021-12-15 01:57
> 

What do you mean? There is an indication if it cant fetch your username.,,

**Comment by Halobiont** [comment] 2021-12-15 01:57
I have Malwayrebytes and Defender.  I've turned them both off and I've made exceptions for Simbrief.com.  None of that worked.

**Comment by ErickSharp** [comment] 2021-12-15 02:06
When you type into the input field, you need to click somewhere outside of the box for it to make the request to certify that the username you entered is valid, in this case if it isn't it will say 'Simbrief Error' in red next to the title. If you click outside of the box, are you still having issues with it not saving?

**Comment by Halobiont** [comment] 2021-12-15 02:13
Yes.  When I click somewhere else on the same page I don't see the Simbrief Error message but I can't init on the MCDU.  I get No Simbrief User.  Sometimes when  I look back on the Flypad after trying the MCDU the field is blank again.  Sometimes it's not.  And as stated sometimes, almost randomly I will see the red Simbrief Error even though we've shown it's correct.

I agree it sounds like a firewall issue.  But I don't do anything special with the firewall.

**Comment by ErickSharp** [comment] 2021-12-15 02:17
> Yes. When I click somewhere else on the same page I don't see the Simbrief Error message but I can't init on the MCDU. I get No Simbrief User. Sometimes when I look back on the Flypad after trying the MCDU the field is blank again. Sometimes it's not. And as stated sometimes, almost randomly I will see the red Simbrief Error even though we've shown it's correct.
> 
> I agree it sounds like a firewall issue. But I don't do anything special with the firewall.

If you enter in your username, and click somewhere on the screen, does the setting's value update? If you do that and go to another EFB page and come back is the setting still saved? If you go onto the home page and tell it to fetch simbrief data, does it fill everything in the flight data card out?

**Comment by Halobiont** [comment] 2021-12-15 02:21
If you enter in your username, and click somewhere on the screen, does the setting's value update?

- Nothing happens.  I'm not sure what you mean the setting's value updates.  I don't see anything happening except the cursor stop blinking and box is not highlighted

 If you do that and go to another EFB page and come back is the setting still saved? 

-No, It's always blank when I do this

If you go onto the home page and tell it to fetch simbrief data, does it fill everything in the flight data card out?

-No, does nothing and when I return to ATSU/AOC blank again

**Comment by ErickSharp** [comment] 2021-12-15 02:25
So when you click on the screen, the value just empties out? Or does the value you had just typed in there stay?

**Comment by Halobiont** [comment] 2021-12-15 02:27
It stays.  For awhile.  I'll go mess around with the MCDU and come back and sometimes it's blank again.  If I sit on the Flypad page and click on the page somewhere it stays.

**Comment by Halobiont** [comment] 2021-12-15 02:29
I just typed it in and let it sit.  After two minutes I saw Simbrief Error flash and now it's blank

**Comment by ErickSharp** [comment] 2021-12-15 02:35
This is interesting, it seems like an issue with something blocking the network request from going through. However, what does make this weird is that if the network request can't go through, an error should be generated that is caught inside of the code and cause the 'SimBrief Error' message to show up.

**Comment by Halobiont** [comment] 2021-12-15 02:41
I'll keep working on the firewall.  Maybe I'll uninstall Malwarebytes.  When I try to make an exclusion for flightsimulator.exe in defender I get an error message that the system can't access the file.  Searching seems to answer that it's encrypted by MS and not really in that location.  Idk.  
I do see "Simbrief Error" flash in red occasionally.
It's obviously not a bug and we can close this if you want.  I've just got some configuration that is just not working with this plane.  Lucky me.

**Comment by Halobiont** [comment] 2021-12-15 02:45
Thank you all for trying to help.

**Comment by tracernz** [comment] 2021-12-15 02:45
> 



> > 
> 
> What do you mean? Is there something that I am missing? There is an indication if it cant fetch your username next to the title of the setting..

So it does! There's a very brief error next to the label:
![image](https://user-images.githubusercontent.com/9995998/146113573-262a5082-63e6-404e-bdc3-4226358871c1.png)

**Comment by tracernz** [comment] 2021-12-15 02:46
> Thank you all for trying to help.

What happens if you go to http://www.simbrief.com/api/xml.fetcher.php?json=1&username=Halobiont in your web browser?

**Comment by Halobiont** [comment] 2021-12-15 02:49
Right now it's hanging.  I've done that earlier and it worked fine.  I saw all the data.

**Comment by Halobiont** [comment] 2021-12-15 02:54
Yeah I got it to work. from https://www.simbrief.com/api/xml.fetcher.php?json=1&username=Halobiont  Same as your link but it wouldn't work from your link.

<html><body>


 
--
params | {…}
general | {…}
origin | {…}
destination | {…}
alternate | {…}
takeoff_altn | {}
enroute_altn | {}
navlog | {…}
etops | {}
atc | {…}
aircraft | {…}
fuel | {…}
times | {…}
weights | {…}
impacts | {…}
crew | {…}
notams | {…}
weather | {…}
sigmets | {}
text | {…}
tracks | {}
database_updates | {…}
files | {…}
fms_downloads | {…}
images | {…}
links | {…}
vatsim_prefile | "<form method=\"GET\" act…value=\"38000\"> </form>"
ivao_prefile | "<form action=\"https://f… value=\"173\">\n</form>"
pilotedge_prefile | "https://www.pilotedge.ne…an[remarks]=RMK/SIMBRIEF"
poscon_prefile | "https://hq.poscon.net/fl…t=&remarks=TCAS+SIMBRIEF"
map_data | "https://www.simbrief.com…AHKDEN_MJS_1639430224.js"
api_params | {…}


</body>
</html>

**Comment by tracernz** [comment] 2021-12-15 02:56
> Same as your link but it wouldn't work from your link.

That is very interesting... I wonder if you have some security software stopping plain http but allowing https...

**Comment by Halobiont** [comment] 2021-12-15 02:58
Don't know what it would be.  I'll search that.

**Comment by tracernz** [comment] 2021-12-15 03:04
> Don't know what it would be. I'll search that.

I'll get you to try this when it's finished building... do you know how to manually install the package into your community directory?
https://github.com/flybywiresim/a32nx/pull/6363

There are some instructions here (gotta wait for the build to be done first though...) https://docs.flybywiresim.com/dev-corner/qa-process/#how-to-get-pr-builds

**Comment by tracernz** [comment] 2021-12-15 03:18
Try now https://github.com/flybywiresim/a32nx/suites/4660855926/artifacts/126650911

**Comment by Halobiont** [comment] 2021-12-15 03:18
Yes I do.  I'm using addon linker by the way.

**Comment by Halobiont** [comment] 2021-12-15 03:29
Working on it...

**Comment by Halobiont** [comment] 2021-12-15 03:49
Downloading slowly.  I don't have great internet here.  I'll report as soon as it's done.  Thank you.

**Comment by Halobiont** [comment] 2021-12-15 04:34
It works!  Thank you again!  That's been eating at me for weeks.  I really wanted to get this going. Love FBW!

**Comment by tracernz** [comment] 2021-12-15 05:57
> It works! Thank you again! That's been eating at me for weeks. I really wanted to get this going. Love FBW!

Thanks for reporting back! :D

**Comment by AdamNZ** [comment] 2021-12-15 06:51
I've been following this (painful) thread with interest. Not because I'm similarly afflicted, but as an example of how far the devs here are prepared to go to help out.

So ... is it the case that the currently available dev version will still have the problem - and this new patch/build fixes it? 

Either way - well done to all concerned!

**Comment by tracernz** [comment] 2021-12-15 07:08
> I've been following this (painful) thread with interest. Not because I'm similarly afflicted, but as an example of how far the devs here are prepared to go to help out.
> 
> So ... is it the case that the currently available dev version will still have the problem - and this new patch/build fixes it?
> 
> Either way - well done to all concerned!

^_^
As soon as the fix gets a QA test it will be merged to dev (master branch).

**Comment by Halobiont** [comment] 2021-12-16 00:28
Completed a flight.  Really nice model.  Don't want to be "a pain" but thought you should know that on the Flypad Navigraph page it's stuck on Authenticate with Navigraph, loading and reset button doesn't do anything.  Don't know if that's related to this build but thought you should know.

**Comment by tracernz** [comment] 2021-12-18 13:24
> Completed a flight. Really nice model. Don't want to be "a pain" but thought you should know that on the Flypad Navigraph page it's stuck on Authenticate with Navigraph, loading and reset button doesn't do anything. Don't know if that's related to this build but thought you should know.

Dev version will work for you now. ;)

**Closed** 2021-12-18 13:24 UTC
Labels: Bug
