### ISSUE TITLE
[BUG] "LDG LT" text can't be updated if landing light were to be controlled by Joystick buttons

### ISSUE THREAD

**Issue by Lamao2244** [flybywiresim/a32nx#1528] opened 2020-10-25 03:24 UTC
**Mod Version**

built: 2020-10-24T22:23:17+00:00
ref: refs/heads/master
sha: d042c787be8149971e0e4f13549cc374438e4fe9
actor: wpine215
event_name: push

**Describe the bug**
 The LDG LT" text on the Upper Ecam will not be updated if landing light were to be controlled by a programmed joystick button. Only update if switch from virtual cockpit using mouse. However, on the ext, the landing light switches on/off with response to the joystick button

**To Reproduce**

1. Program a button on a joystick to toggle ON/OFF landing light
2.Click programmed button
3.Monitor upper Ecam

**Expected behavior**
 "LDG LT" text should be updated 

**Actual behavior**
The LDG LT" text on the Upper Ecam will not be updated if landing light were to be controlled by a programmed joystick button. Only update if switch from virtual cockpit using mouse. However, on the ext, the landing light switches on/off with response to the joystick button

**References**

![bug](https://user-images.githubusercontent.com/72637344/97098133-836fd200-16b4-11eb-8c22-d2f868966abe.png)

**Additional context**
Nil

Was this working before/when did the issue start occurring?  No idea

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub):LaMao

**Comment by Benjozork** [comment] 2020-10-25 03:27
Duplicate of #1507.

**Closed by Benjozork** 2020-10-25 03:27 UTC
Labels: Bug
