### ISSUE TITLE
[BUG] Autopilot crashes to the ground after engaging

### ISSUE THREAD

**Issue by oashidam** [flybywiresim/a32nx#2675] opened 2020-12-24 04:11 UTC
**Mod Version**

 release version 0.5.1 (stable)

**Describe the bug**

Right after departure, engaging autopilot simply stalls the airplane. I have no control whatsoever to bring the airplane under control.

**To Reproduce**

1. Flight from KLAX to KLAS.
2. Managed heading And speed (250kts)
3. Hand fly until about 3000ft, then engage AP

**Expected behavior**

AP to steer plane with managed heading and speed, also to follow waypoints concisely.

**Actual behavior**

AP does not follow flight plan. AP stalls the aircraft after a few seconds, then crashes to the ground. Unable to gain control of the airplane after this begins to happen.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
This worked in previous versions before 0.5.0.

Is this a problem in the vanilla unmodded game?
With the vanilla this does not happen. I only encounter the problem using the mod.

Discord username (if different from GitHub): othniel

**Comment by Benjozork** [comment] 2020-12-24 04:12
Have you tried setting a deadzone on your controller sensitivity settings ?

**Comment by oashidam** [comment] 2020-12-24 04:12
Yes all my dead zones have been set to 14%

**Comment by ErikNL80** [comment] 2020-12-24 07:37
Have you also reset/deleted your profile after the update?

**Comment by donstim** [comment] 2020-12-24 07:46
Can you provide a little more information?  Was your flight plan from the MSFS flight planner? Were your flaps up at this point? Do you know what your managed speed was? Were your thrust levers in the CLB detent?  Managed speed and heading, what vertical mode was your autopilot in and what altitude did you have dialed in? Thanks.

**Comment by WillemSax** [comment] 2020-12-24 09:43
Same Problem

**Comment by phnkone** [comment] 2020-12-24 09:58
the same problem, flight plan created in mfs, approach entry, in activating flaps 1 the plane pitches down strongly and crashes, two tests two failures

**Comment by foxmike80** [comment] 2020-12-24 10:38
> Have you also reset/deleted your profile after the update?

How do I rest/delete the profile?

**Comment by jydsj** [comment] 2020-12-24 11:23
Same Problem. approach entry, in activating flaps 1 the plane pitches down strongly and crashes。There are only a32nx in the community folder.

**Comment by Snorti05** [comment] 2020-12-24 13:44
Same problem here, loaded flighplan via simbrief Interface, than climb on runway HDG (HDG as course) with AP enable, set climb rate etc. Everhing is fine, after a few secons later it starts to descent and turn to the ground. Have it all the time with the latest DEV Base on LSZH (28 departure) LSGG (22 departure)
Try to produce i video...

**Comment by oashidam** [comment] 2020-12-24 14:28
> Can you provide a little more information? Was your flight plan from the MSFS flight planner? Were your flaps up at this point? Do you know what your managed speed was? Were your thrust levers in the CLB detent? Managed speed and heading, what vertical mode was your autopilot in and what altitude did you have dialed in? Thanks.

Flight plan was from the MSFS flight planner. Flaps were up. Selected speed was 250kts. Thrust levers were in CLB. Selected speed, managed heading. Altitude dialed in was 34000.

**Comment by WillemSax** [comment] 2020-12-24 14:56
Used SimBrief in flybywire 5.01 , after 5000 ft the plane crashed every times . 

Verstuurd vanaf mijn iPad

**Comment by Benjozork** [comment] 2020-12-24 23:33
Hello, are you using the modern flight model or legacy ?

**Comment by oashidam** [comment] 2020-12-24 23:58
> Hello, are you using the modern flight model or legacy ?

I'm using the modern flight model

**Comment by hugo6053** [comment] 2020-12-25 08:33
Same problem as others. Have tried all the usual tricks, verification's and checks on latest stable and master versions. The default A320 after the latest MS update works.

**Comment by Snorti05** [comment] 2020-12-25 09:04
Happens every time to this Airport (LSGG/Runway 22 Intersection B Departure) /Route (MOLUS N871 BERSU)
load via simbrief interface.
Select MOLU4A departure
Start vom Gate 3 with this add on:
https://flightsim.to/file/4515/geneva-lsgg-airport-basic

Details see in Video:
https://user-images.githubusercontent.com/76561415/103129175-1965b000-4698-11eb-9fd8-5875e3288e7f.mp4

Same thing in LSZH with runway 28

With default A20N it works.

**Comment by WillemSax** [comment] 2020-12-25 13:29
Hi , AP1 didn’t work in SimBrief !!

Verstuurd vanaf mijn iPhone

**Comment by WillemSax** [comment] 2020-12-25 13:32
Verstuurd vanaf mijn iPhone

**Comment by WillemSax** [comment] 2020-12-25 13:33
Ap 1 didn’t work in SimBrief !

Verstuurd vanaf mijn iPhone

> Op 25 dec. 2020 om 14:32 heeft Willem van der Meijde <wmeijde@xs4all.nl> het volgende geschreven:
> 
> ﻿
> 
> <IMG_7966.jpg>
> 
> 
> 
> <IMG_7967.jpg>
> 
> 
> Verstuurd vanaf mijn iPhone

**Comment by donstim** [comment] 2020-12-25 16:43
> Happens every time to this Airport (LSGG/Runway 22 Intersection B Departure) /Route (MOLUS N871 BERSU)
> load via simbrief interface.
> Select MOLU4A departure
> Start fromGate 3 with this add on:
> https://flightsim.to/file/4515/geneva-lsgg-airport-basic
> 
> Details see in Video:
> https://user-images.githubusercontent.com/76561415/103129175-1965b000-4698-11eb-9fd8-5875e3288e7f.mp4
> 
> Same thing in LSZH with runway 28
> 
> With default A20N it works.
> 
> btw: What is the modern flight model or Legacy?

Thanks for the video. It is helpful to have and will hopefully allow me to reproduce it and ensure the fix I have developed for the issue occurring on takeoff will also work for approach.

This issue is now listed on our Discord known issues channel:   - Stall and unrecoverable dive after takeoff or during approach with CONF 1+F.  (Workaround:  On takeoff, select flaps up at S speed and definitely below 210 knots. On 
      approach,  do not exceed 210 knots in CONF 1 (+F). Under active investigation.

There is a modification currently undergoing quality assurance testing that will provide a preliminary fix so that you won't have to be so watchful of speed in CONF 1+F, but until then the workaround should prevent the issue from occurring. 

As for the modern/legacy flight model question, MSFS has a new flight model definition, but also supports the old FSX flight model. In the MSFS options menu, if you go to "General", there is a selection called "Flight Model." If you click on that, the top line will show what flight model definition you are using. It can be either "Modern" or "Legacy," You want to use "Modern."

**Comment by donstim** [comment] 2020-12-25 20:46
This appears to be a duplicate of issue #2661

**Comment by Benjozork** [comment] 2020-12-26 22:35
Closing as duplicate

**Closed by Benjozork** 2020-12-26 22:35 UTC
Labels: Bug
