### ISSUE TITLE
[REQUEST] DUAL AP implementation

### ISSUE THREAD

**Issue by ZiCongQ** [flybywiresim/a32nx#1223] opened 2020-10-09 14:37 UTC
**Is your feature request related to a problem? Please describe.**

No.

**Describe the feature you'd like to see implemented**

DUAL AP implementation, when you click on the other AP button, it should activate dual AP instead of switching to that AP, for cross checking purposes during actions that requires higher than normal accuracy such as CATIII ILS instrument landings.

**References**

for some reasons cant really find a lot of reference documentation on this.
![image](https://user-images.githubusercontent.com/70565899/95596247-b6dd1a80-0a7f-11eb-8fef-224aa491efed.png)

**Additional context**

Discord username (if different from GitHub):

**Comment by dhkim0800** [comment] 2020-10-09 16:12
For me, both AP1 and 2 turned on during my CATIII ILS approach. Have you tried an approach?

**Comment by bouill** [comment] 2020-10-09 18:27
IRL behaviour is that both AP engage together only when APPROACH phase is active and the approach is an ILS

**Comment by NathanInnes** [comment] 2020-10-09 19:38
![image](https://user-images.githubusercontent.com/18389085/95624800-57770e80-0a6f-11eb-9b31-e79cdbb5cb4d.png)

**Comment by NathanInnes** [comment] 2020-10-09 19:39
Not just an ILS.

**Comment by ZiCongQ** [comment] 2020-10-11 19:56
It should be engaged manually within conditions not automatically

**Comment by MisterChocker** [comment] 2021-03-17 00:56
Duplicate of #119

**Closed by MisterChocker** 2021-03-17 00:56 UTC
Labels: Autopilot, Enhancement
