### ISSUE TITLE
ENG BLEED not working, only APU BLEED

### ISSUE THREAD

**Issue by g0per** [flybywiresim/a32nx#144] opened 2020-08-27 16:43 UTC
Checked on **current dev build**. Last night I noticed some strange behaviour on the stable build, so I switched to dev today for the test and report.

Followed procedure:

- BAT1+2 ON
- (IRS ON, but not related)
- All fuel pumps ON
- APU MASTER SW ON
- APU START
- (wait until it finishes starting)
- APU BLEED ON
- MASTER ENG1 ON
- ENG MODE IGN START

**Result:** ENG1 starts (expected)

Now I disable APU BLEED, and try to start ENG2 with ENG1 BLEED:

- APU BLEED OFF
- MASTER ENG2 ON
- (ENG MODE IGN START still left like that from starting ENG1)

**Result:** nothing
**Expected:** ENG2 start sequence

ENG2 only begins start sequence if I turn APU BLEED back ON.

It does the same when starting ENG2 and then trying to start ENG1.

**Comment by arvinjarvin** [comment] 2020-08-27 16:57
Hello

Thanks for raising this issue into the logic of MSFS.

As you know the game has been released at a stage where the logic is not entirely perfect, leaving some flaws in the realism and correct function of aircraft instruments.

We will look into this and keep you updated.

All the best
Arvin

**Comment by EmPExodus** [comment] 2020-08-28 11:49
I think you need to set the cross bleed selector to open for this to work.

**Comment by g0per** [comment] 2020-08-28 17:22
It was on AUTO, but let me check it in a while.

**Comment by lousybyte** [comment] 2020-08-28 17:44
It's on AUTO by default and the switch is Inop. atm.

**Comment by g0per** [comment] 2020-08-28 19:13
Indeed. It's currently fixed on the AUTO position - which should allow BLEED air to pass through, if required.

**Comment by EmPExodus** [comment] 2020-08-28 21:31
When cross bleed selector is set to auto, the valve only opens while APU-bleed is active. You can see the procedure in this video at around 1:15 https://www.youtube.com/watch?v=s7EG-CUaiyM.

**Comment by g0per** [comment] 2020-08-28 22:25
I may be able to check a CEO FCOM in a few days, and confirm that. Now Im not so sure lol.

**Comment by AdenFlorian** [comment] 2020-09-04 03:54
Does this issue exist in the vanilla unmodded game, or was it caused by the mod?

**Comment by g0per** [comment] 2020-09-08 05:08
Hi @AdenFlorian . IIRC it was already like that on the vanilla plane.

**Comment by 2hwk** [comment] 2021-01-01 13:58
Current status:

X-bleed only works when APU bleed switch is ON, in any case, which is incorrect behaviour.

**Comment by aguther** [comment] 2022-04-10 09:37
Duplicate of #820

**Closed by aguther** 2022-04-10 09:37 UTC
Labels: Bug, Pneumatic
