### ISSUE TITLE
[BUG] Rudder control with XBOX One Controller

### ISSUE THREAD

**Issue by TheStraing** [flybywiresim/a32nx#2627] opened 2020-12-22 23:47 UTC
**Mod Version**

Latest master branch with custom FBW

**Describe the bug**

After the new update, new rudder controls have been added. 
Now xbox one controller triggers are registered as buttons in the sensitivity panel but after remapping them to the new "Rudder Axis Left" and "Rudder Axis Right" commands the original aircraft works fine.
When I install the A32NX mod It doesn't work as well... the rudder starts "flickering" when trying to move it and when the triggers (LT or RT) are pushed to the end the rudder turns back to it's "straight" position.

**To Reproduce**

1. Clear the LT and RT original bindings
2.  Manually bind them to the new "Rudder Axis Left" and "Rudder Axis Right"
3.  Start a flight

Was this working before/when did the issue start occurring?
Yes, it was and It broke after the new patch.

Is this a problem in the vanilla unmodded game?
No and the master branch without the custom FBW works fine

**Comment by kthejoker20** [comment] 2020-12-23 04:40
THIS IS A MAJOR BUG.  Plane is unflyable with the bug.   The rudder is either full left or full right.  There is no variance

**Comment by ErickSharp** [comment] 2020-12-24 03:49
If you are using the A32NX with custom fly-by-wire, this is an issue that currently can't be mitigated. However, if you are just using the normal A32NX, this is an issue with the controller setting configuration. Try this to fix the issue:

1. Access the settings menu by pressing escape.
2. Go into controls.
3. Select your Xbox controller.
4. Set the search from "Assigned" to "All"
5. Search by name, and enter "Rudder"
6. You should see something that looks like "Rudder axis left" or "Rudder axis right." Bind each one to the respective trigger. You will need to use the dropdown, as it can't scan your Xbox controller input.
7. Unbind the standard rudder controls.

Let me know if you are still having issues, feel free to reach out to me.

**Comment by carlosgaucho** [comment] 2020-12-24 05:15
@ErickSharp @kthejoker20  I have the same issue with the current 5.1 stable version, the developer master as well as the vanilla msfs2020. I've tried the recommendation about changing the assignments to "rudder axis" but no change.  I have an old x-box one controller that I have been using since launch, the  LT and RT for rudder. Since yesterday, these buttons have no longer worked as linear rather just on/off. 
I have verified in win10 / Game Controllers / Properties - that both the LT and RT are still responding linearly - not just on off

**Comment by ErickSharp** [comment] 2020-12-24 15:23
> @ErickSharp @kthejoker20 I have the same issue with the current 5.1 stable version, the developer master as well as the vanilla msfs2020. I've tried the recommendation about changing the assignments to "rudder axis" but no change. I have an old x-box one controller that I have been using since launch, the LT and RT for rudder. Since yesterday, these buttons have no longer worked as linear rather just on/off.
> I have verified in win10 / Game Controllers / Properties - that both the LT and RT are still responding linearly - not just on off

This issue relates to the rudder not being assigned to an axis. Are you able to check that all of your bindings for both triggers are correctly assigned to an axis, and unbound from the default rudder settings?

**Comment by TheStraing** [comment] 2020-12-24 18:32
@ErickSharp I'm not talking about the necessity to re-assign the LT and RT triggers. That's a simulator problem, I wouldn't have opened the issue if it wasn't related to the A32NX mod.
I'm just talking about the problem that the custom FBW has that I guess it can't be fixed from the user side.

**Comment by Rameyuk** [comment] 2020-12-28 10:53
I've investigated this issue some more and I can confirm that the root cause here is the A/THR button. If you have it on, you will have rudder issues as described. Turn off the A/THR and you will have full rudder control.

So when you're taxiing on the ground, don't engage A/THR and you should turn just fine. Let it automatically engage when you're rolling out for take off. Similarly, after landing, turn off the A/THR and you should be able to taxi out and to the gate without issue as well.

Perhaps the FBW team can investigate why the rudder control is affected by the A/THR on or off.

**Comment by aguther** [comment] 2021-02-03 23:58
Should be fixed in the meantime.

**Closed** 2021-02-03 23:58 UTC
Labels: Bug
