### ISSUE TITLE
[BUG] Format error on MCDU ZFW/ZFWCG

### ISSUE THREAD

**Issue by Sixfootsctram** [flybywiresim/a32nx#1332] opened 2020-10-14 18:23 UTC
**Mod Version**
Current Dev version (Update 14.10.2020 2019L)

**Describe the bug**
When entering ZFW and ZFWCG I receive a format error message.

**To Reproduce**

1.Start Cold and Dark
2.Power the aircraft.
3.Trying to enter ZFW/ZFWCG

**Expected behavior**
Load the data

**Actual behavior**
Nothing

**Additional context**
Used to work.

Discord username (if different from GitHub):Joker11#9119

**Comment by Benjozork** [comment] 2020-10-14 18:33
Duplicate of #1320

**Closed by Benjozork** 2020-10-14 18:33 UTC
Labels: Bug
