### ISSUE TITLE
[BUG] FD Flight Directors not working correctly (not aligned with the route)

### ISSUE THREAD

**Issue by Marenostrum66** [flybywiresim/a32nx#2101] opened 2020-11-25 22:18 UTC
**Mod Version**
Both tested
{ "built": "2020-11-24T08:08:38+00:00", "ref": "refs/heads/master", "sha": "b570de8c53cd5b52a21c81f8120bfa57d8c53830", "actor": "wpine215", "event_name": "push" }

{ "built": "2020-11-25T18:46:03+00:00", "ref": "refs/heads/master", "sha": "5b0a8f2b7fa725ab7427e8092a74f1610a8c8d3a", "actor": "wpine215", "event_name": "push" }

 both after the MSFS2020 update 1.11.6.0

**Describe the bug**
FD keep alive after take off but not aligned with the route.
This bug happened on 3 flights of 4
Flight 1: **built 2020-11-24T08:08:38+00:00"** 
              ULLI ESSA FD not working... either in NAV or HDG mode. All flight with the autopilot disengaged 
Flight 2: **built 2020-11-24T08:08:38+00:00"**       
              EGCC - ENGM FD working...flight normal
Flight 3: **built 2020-11-24T08:08:38+00:00"**       
              LYBE - URWA  FD not working... either in NAV or HDG mode. 
                                     partial solution in flight: deleted all wpts. Inserted a new wpt nearby the destination. Set a direct to the 
                                     new waypoint. Autopilot engaged.  not aligned but after about 10 min it FD was able to find the correct 
                                     direction of the flight
Flight 4: **built 2020-11-25T18:46:03+00:00",** 
              EDDM - EPWA FD not working... either in NAV or HDG mode. 
                                      no solutions founded. 

**To Reproduce**
1- set up a norma flight
2- take off with all the system correctly set and FD ON
3- you'll see the lateral guidance of the FD shifted off route
4- try to set a direct to....will not work
5- take into account that once it worked correctly (flight EGCC ENGM) so try twice if the first time FD works correctly.

**Expected behavior**
I expect the FD being aligned with the planned route.

**Actual behavior**
FD laterla nav totally not aligned

**References**
see screenshots of the FD not aligned with the planned route (4 different flights).
lateral guidance in the PFD is shifted to the right or left....in any case off route.

![Capture1A](https://user-images.githubusercontent.com/74383127/100286701-8a1f8c80-2f73-11eb-8e59-ecb777724a7d.JPG)
![Capture1B](https://user-images.githubusercontent.com/74383127/100286714-8db31380-2f73-11eb-9ff5-1a6dc0fa07ae.JPG)
![Capture1C](https://user-images.githubusercontent.com/74383127/100286718-90ae0400-2f73-11eb-859f-d6ccd3fc0133.JPG)
![Capture1D](https://user-images.githubusercontent.com/74383127/100286727-93105e00-2f73-11eb-8852-eb3bad30ffe6.JPG)

**Additional context**
no additional context

Was this working before/when did the issue start occurring?
Yes: the FD worked fine since the last MSFS2020 update.
After the update, both the last 2 built are not working correctly.

Is this a problem in the vanilla unmodded game?
not tested

Stefano Biasiotti 
#1729

**Comment by Benjozork** [comment] 2020-11-25 22:25
Duplicate of #2089

**Closed by Benjozork** 2020-11-25 22:25 UTC
Labels: Bug
