### ISSUE TITLE
[BUG] Autopilot don't follow approach pattern when the approach passes close to the final runway

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#1253] opened 2020-10-11 17:05 UTC
**Mod Version**

dev version 2010-10-08

**Describe the bug**

Autopilot don't follow approach pattern when the approach passes close to the final runway. For example approach RUSI1E for RWY07 of GCTS airport. When I take this screenshot, I just switch to heading mode because autopilot want to go directly GCTS airport.

![2020-10-11 (41)](https://user-images.githubusercontent.com/5894146/95684871-a7331280-0bf4-11eb-8935-e281f9625ea8.jpg)

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by aviationenthusiast** [comment] 2020-10-11 17:18
I confirm

**Comment by stevex77** [comment] 2020-10-11 17:30
I confirm actually to KMIA/ILS 27, via HENDN, STAR FLIPR7.

**Comment by vlbreda** [comment] 2020-10-11 17:55
Is a bug indeed. EHEH -> EDLP RW24 gives same error.

**Comment by nabil74** [comment] 2020-10-11 20:35
confirmed.

**Comment by ChruutvoLuzi** [comment] 2020-10-11 20:55
Can confirm aswell, had this issue twice today on ULMM - ESPA and ESPA - ULLI

**Comment by bscout9956** [comment] 2020-10-11 21:10
I can confirm this issue as well, though I can't remember exactly where I've had it happen to me.

**Comment by dmajestic80** [comment] 2020-10-12 18:22
> **Mod Version**
> 
> dev version 2010-10-08
> 
> **Describe the bug**
> 
> Autopilot don't follow approach pattern when the approach passes close to the final runway. For example approach RUSI1E for RWY07 of GCTS airport. When I take this screenshot, I just switch to heading mode because autopilot want to go directly GCTS airport.
> 
> ![2020-10-11 (41)](https://user-images.githubusercontent.com/5894146/95684871-a7331280-0bf4-11eb-8935-e281f9625ea8.jpg)
> 
> **To Reproduce**
> 
> 
> **Expected behavior**
> 
> **Actual behavior**
> 
> **References**
> 
> **Additional context**
> 
> Was this working before/when did the issue start occurring?
> 
> Is this a problem in the vanilla unmodded game?
> 
> Discord username (if different from GitHub):

I’ve have this issue too. The workaround I discovered is before reaching final, say at around 10000ft go into the MCDU and re-enter the arrival runway. Seems to fix the issue for me.

**Comment by fourdragons** [comment] 2020-10-12 18:27
“ I’ve have this issue too. The workaround I discovered is before reaching final, say at around 10000ft go into the MCDU and re-enter the arrival runway. Seems to fix the issue for me.”

Confirmed. (Still a pain)

**Comment by tylerdola** [comment] 2020-10-31 23:08
This is still happening, is this A32NX related or base MSFS?

**Comment by Nadelbaum** [comment] 2020-11-18 06:49
Confirming this with latest dev build from 17Nov2020 with EFHK/ILS 04R, STAR INTO6R. About right after starting the STAR the next waypoint (and thus AP) switches to the runway.

**Comment by Benjozork** [comment] 2020-11-18 06:54
This is confirmed to be an Asobo AP issue. We do not modify autopilot.

**Comment by MisterChocker** [comment] 2020-12-31 07:11
duplicate of #939

**Closed by MisterChocker** 2020-12-31 07:11 UTC
Labels: Asobo Bug, Autopilot, Bug, Flight Plan
