### ISSUE TITLE
[REQUEST] Improvements to new textures

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#3945] opened 2021-03-12 17:02 UTC
**Is your feature request related to a problem? Please describe.**

I want to share a pitcure from somebody from the Flightsimulator forum  (@GamingCat2130 forums user name)

he posted a foto that compare the new vs old textures, especially the "covers" of the cockpit. To my mind, I completly comply with it that it is overdone and looks like "styrofoam". As a Airbus pilot I can´t really see much realism in the new textures of the covers. (other new textures looks fantastic!!!)

To my mind, the "orginal" textures of the covers with far less deep structures look quite more realistic. 

I only want to share my opinion. If the community love it, its okay, but it doesn´t look like real. 

**Describe the feature you'd like to see implemented**

textures more like the original ones (only for parts with new cover textures)

**References**

**Additional context**

Discord username (if different from GitHub):

![cockpit textures](https://user-images.githubusercontent.com/72918017/110972926-dc3ac100-835c-11eb-9b9d-7c47269ac8b3.jpg)

(copyright by GamingCat2130 from FS2020 forum)
![7d8cc6e51821b7511fa99a5cf19086b27f5d76e6_2_690x318](https://user-images.githubusercontent.com/72918017/110973601-b9f57300-835d-11eb-9656-b6cdb740858b.jpeg)

**Comment by ImenesFBW** [comment] 2021-03-12 17:13
These are still being refined they are not in the stable release for a reason. Mike has already reworked the mentioned parts and they will be added soon with some other improvements. The leather was made from scratch and is amazing out of the sim, but does not play well with the sims engine so the creases were toned down. 

You can close the issue as this is a known issue that is being resolved. Especially since the picture linked doesn't use the most constructive language.

**Closed** 2021-03-12 17:17 UTC
Labels: Enhancement, Texture

**Comment by andrejetcat** [comment] 2021-03-12 17:18
thank you for that :) sorry for tha language. 
I´m very happy that there is such a huge support within this project from your side! THANKS FOR THAT!!!

**Comment by Benjozork** [comment] 2021-03-12 17:27
Your provided explanation picture isn't really the kind of feedback we like to work with.

**Comment by fluffyGamingCat** [comment] 2021-04-07 22:57
I wanted to thank you too for your endless efforts and your awesome work, and I absolutely LOVE the Airbus now thanks to all the extra features and cockpit realism!

And sorry I did not wanted to be mean I first thought these texture problems are some glitch caused by a Flight Simulator update and were a direct Flight Simulator main programm patch problem because these textures appeared on all regular Airbusses after a specific Flight Sim update a few weeks ago. And I cannot write English perfect and don`t really know what is considered "neutral explaining" or "mean" by native speakers. :)

But please keep on doing your absolute AWESOME work with the FBW Airbus and I am looking forward for every new update made for this gorgeous plane.
