### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by jagu000** [flybywiresim/a32nx#669] opened 2020-09-14 11:50 UTC
How does the a32nx update? Is it automatically or is it a go to download process?

**Comment by Inaxair** [comment] 2020-09-14 12:04
You need to delete the old version, then download the new version and install it like you did at the first place

**Comment by CoffeePanda0** [comment] 2020-09-14 15:18
Please close this issue if it is not a bug or enhancement. If you need help, join the discord

**Closed** 2020-09-14 15:24 UTC
