### ISSUE TITLE
[BUG] Performance degradation with mod since MSFS 1.9.5.0

### ISSUE THREAD

**Issue by G4mer0921** [flybywiresim/a32nx#1341] opened 2020-10-14 20:44 UTC
**Mod Version**
master

**Describe the bug**
I am getting low performance (5-15 fps less) compared to the vanilla; this didn’t happen some days ago.

**To Reproduce**
Compare fps with mod and without mod

1.
2.
3.

**Expected behavior**
The mod should not affect performance so much.

**Actual behavior**
 Mod affect performance (5-15 fps less compared to the vanilla)

**References**

**Additional context**

Was this working before/when did the issue start occurring?
I noticed it today for the first time.

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-10-14 21:43
How much FPS did you get before installing the mod ?

**Comment by G4mer0921** [comment] 2020-10-14 21:50
> How much FPS did you get before installing the mod ?

Not less than 30 in worst cases (for example  at LFPG during taxi and T.O.).

**Comment by mdionizio** [comment] 2020-10-14 22:31
I also noticed a similar performance degradation after installing the latest MSFS patch. 

Around 60 on the ground without mod, 45 with the mod.

**Comment by MisterChocker** [comment] 2020-10-14 23:54
Since latest MSFS patch bad performance for me too. I guess they broke something :(

**Comment by Artax04** [comment] 2020-10-15 02:14
I got 10 - 15 fps less than Vanilla version, unplayable right now for me, the frametime got crazye after that useless double screen update :(

**Comment by Benjozork** [comment] 2020-10-15 02:48
>  after that useless double screen update :(

Please refrain from judging people's contributions because you do not agree with them.

We will work on performance optimizations, but keep in mind that the performance loss is currently also caused by some unknown issue due to the 1.9.5.0 MSFS update that we are currently investigating.

**Comment by Benjozork** [comment] 2020-10-15 03:00
Additional info:

Performance seems probably related to screens / `CoherentGTDraw` frametimes, as looking away from the screens or being in outside view dramatically increases FPS

**Comment by wpine215** [comment] 2020-10-15 03:27
Please set display refresh rate to medium or low - high is unnecessary as it uses a significant amount of FPS for a marginal improvement in display smoothness.

**Comment by mdionizio** [comment] 2020-10-15 03:29
I've used low for a while now. Performance still dropped considerably after the new patch.

**Comment by 2hwk** [comment] 2020-10-15 03:48
Switch the First officer's side PFD off (brightness knob to 0) if you have having issues for now. PFDs are known to have the most impact on performance.

**Comment by Artax04** [comment] 2020-10-15 04:02
> Switch the First officer's side PFD off (brightness knob to 0) if you have having issues for now. PFDs are known to have the most impact on performance.

performance is a lot worst than vanilla also with both pfd turned OFF, and with refresh on LOW :(

**Comment by Benjozork** [comment] 2020-10-15 04:44
> > Switch the First officer's side PFD off (brightness knob to 0) if you have having issues for now. PFDs are known to have the most impact on performance.
> 
> performance is a lot worst than vanilla also with both pfd turned OFF, and with refresh on LOW :(

As stated, we are working on this. Stay tuned.

Your feedback is important and even if we don't shout from the roofs that we are fixing it, we very much care. I have myself a now low end GPU and I am having very bad issues.

**Comment by Artax04** [comment] 2020-10-15 04:57
i have tons of faith in you, you made this game playable, witout this mod was unplayable.
But that double screen was a modkiller for me :/

**Comment by Benjozork** [comment] 2020-10-15 05:05
> i have tons of faith in you, you made this game playable, witout this mod flight simulator was unplayable.
> I did like five post on ms forum just saying "thank you"
> But that double pfd was a modkiller for me, after that i have to play with vanilla, the frametime is crazy :/

We understand the degradation is annoying, but keep in mind this is not a final release and we cannot guarantee everything to work all the time.

We are all unpaid who dedicate time towards this without being compensated in any way. As I made that comment someone was already investigating how to optimize the performance of the PFD.

We are also considering an option to disable split PFD/ND - stay tuned.

**Comment by 2hwk** [comment] 2020-10-15 05:07
> 
> 
> > Switch the First officer's side PFD off (brightness knob to 0) if you have having issues for now. PFDs are known to have the most impact on performance.
> 
> performance is a lot worst than vanilla also with both pfd turned OFF, and with refresh on LOW :(

This indicates the issue is not related to the PFDs being unlinked, but rather some of the other systems that were implemented. Performance will probably improve once we have done a pass to optimise performance.

**Comment by c1be** [comment] 2020-10-15 07:03
> > > Switch the First officer's side PFD off (brightness knob to 0) if you have having issues for now. PFDs are known to have the most impact on performance.
> > 
> > performance is a lot worst than vanilla also with both pfd turned OFF, and with refresh on LOW :(
> 
> As stated, we are working on this. Stay tuned.
> 
> Your feedback is important and even if we don't shout from the roofs that we are fixing it, we very much care. I have myself a now low end GPU and I am having very bad issues.

Can i ask why is this separate screen feature so important? So many people are saying it's not necessary, it's not worth it, no one asked for it, remove it or release different version for shared cockpit, it causes big fps hit, a lot of stutters even if screens are off and it's a feature for something most people will never use? I'm noy trying to be rude, i'm into flight sims 10 years now, i have a lot of respect for you guys and everything you're doing, this is by far the best plane in msfs, nothing is even close, and i think a year from now, even payware airplanes are gonna have tough time to compete with it.

**Comment by myselfaaryan** [comment] 2020-10-15 09:12
@c1be @Artax04 Come on guys. A feature is a feature. No one asks for it. 

If you have fps issues, just turn off the FO Displays or delete the following file:

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR_LOD00.gltf

It's a temporary fix. I am working on a release here: https://github.com/myselfaaryan/a32nx

**Comment by Benjozork** [comment] 2020-10-15 14:10
> Can i ask why is this separate screen feature so important? So many people are saying it's not necessary, it's not worth it, no one asked for it, remove it or release different version for shared cockpit, it causes big fps hit, a lot of stutters even if screens are off and it's a feature for something most people will never use? I'm noy trying to be rude, i'm into flight sims 10 years now, i have a lot of respect for you guys and everything you're doing, this is by far the best plane in msfs, nothing is even close, and i think a year from now, even payware airplanes are gonna have tough time to compete with it.

Those are things we are discussing all the time and here is the current plan:

We will improve performance and draw time of the PFD and ND, and if that does not improve performance noticeably we will provide the option to disable that feature.

**Comment by armankir** [comment] 2020-10-15 14:28
I have also experienced this and a good fix is to turn off the FO PFD.

**Comment by Seth-Dark** [comment] 2020-10-15 15:00
Same here with out any significant fps-drop but with permanent stutters ( micro-stutters) even with 2nd PFD/ND turned off. Its getting better when they are off , but still the stuttering is there and destroys the whole immersion.
Maybe has to do with some new systems added ( default A320 is smooth with no issues ) 
Beside that new update is amazing, you saved MFS Airbus, started to be alive. Thanks for your great work and time.

**Comment by Berniep94** [comment] 2020-10-15 20:55
Hey, i am going to post, a few screenshots of what im having right now....

i got like a 35% perfomance drop when im looking forward, but if i turn to the window, i restore my fps.

![FlightSimulator_rivr6YbZMX](https://user-images.githubusercontent.com/71423997/96184935-6427b680-0ef6-11eb-8165-3fdf147d116a.jpg)

![FlightSimulator_rqZQk5PbRB](https://user-images.githubusercontent.com/71423997/96184945-68ec6a80-0ef6-11eb-8c5f-39baf1366c1e.jpg)


Thank you guys!

**Comment by Benjozork** [comment] 2020-10-17 05:01
As you can see I have opened a PR optimizing some of the update code.

I do NOT guarantee significant improvements at the moment - I still have to go through a lot of the code.

Hold tight.

**Comment by jokey2k** [comment] 2020-10-24 11:49
For people not daily into software development:
Developers typically proceed in 3 Steps:

1. Make it work (aka Prototype)
2. Make it work well (so Users can interface with it and it does not break)
3. Make it work fast (As you know all cases where you need what kind of data and optimize for that)

A32NX is currently somewhere between 1 and 2, depending on the features being worked on. Yes performance is key, but not the first thing to go for. As much as I am a user and know the pain with frame stutters, I am also a developer and adhere to the steps to avoid lots and lots of duplicate work.

Keep up the good work guys 😊

**Comment by Berniep94** [comment] 2020-10-25 01:02
> For people not daily into software development:
> 
> Developers typically proceed in 3 Steps:
> 
> 
> 
> 1. Make it work (aka Prototype)
> 
> 2. Make it work well (so Users can interface with it and it does not break)
> 
> 3. Make it work fast (As you know all cases where you need what kind of data and optimize for that)
> 
> 
> 
> A32NX is currently somewhere between 1 and 2, depending on the features being worked on. Yes performance is key, but not the first thing to go for. As much as I am a user and know the pain with frame stutters, I am also a developer and adhere to the steps to avoid lots and lots of duplicate work.
> 
> 
> 
> Keep up the good work guys 😊

And i am agree with you, we want to help as users to get the best performance and looking plane, i download the aircraft everysingle time there is an update, so i can try to find a bug or try to see how its working... but maybe on your PC (high end) you dont see this kind of frame stutters, maybe yes... but we keep up like a team because also users or the final customer gets part in the project!!! Like i always say Keep the work as you know!!! 

Cheers from Mexico!

**Comment by mdionizio** [comment] 2020-10-29 00:43
> > > Switch the First officer's side PFD off (brightness knob to 0) if you have having issues for now. PFDs are known to have the most impact on performance.
> > 
> > 
> > performance is a lot worst than vanilla also with both pfd turned OFF, and with refresh on LOW :(
> 
> As stated, we are working on this. Stay tuned.
> 
> Your feedback is important and even if we don't shout from the roofs that we are fixing it, we very much care. I have myself a now low end GPU and I am having very bad issues.

Have you been able to see any improvements lately? :)

**Comment by Benjozork** [comment] 2020-10-29 00:53
@mdionizio

We are currently exploring a new rendering engine for the displays, in the mean time I will merge my temporary optimization PR soon.

**Comment by mdionizio** [comment] 2020-10-29 00:54
@Benjozork Thanks mate appreciate it

**Comment by Berniep94** [comment] 2020-10-29 02:23
Thank you so much @Benjozork for your hard work, and the entire team!!

**Comment by mdionizio** [comment] 2020-11-04 22:28
@Benjozork Hi there, any update on when your temporary optimization PR will be available? :)

**Comment by Benjozork** [comment] 2020-11-04 22:40
I'll merge it soon. However don't expect anything meaningful, we're not gonna do further optimization on this and we'll instead rewrite the entire PFD since it's a mess inherited from the base game.

**Comment by dickbig2** [comment] 2020-11-13 10:20
I was having like ~42fps when using the external view but when I go back into the cockpit, my fps instantly drops below 30. 
I tried to switch off FO’s display but only recieved a few fps gain. My fps finally settled around 27-30 stationary on ground.

**Comment by mdionizio** [comment] 2020-12-02 22:57
> I'll merge it soon. However don't expect anything meaningful, we're not gonna do much further optimization on this and we'll instead rewrite the entire PFD and ND since it's a mess inherited from the base game.
> 
> Currently that is planned for 0.6.0.
> 
> In the mean time, turning off the F/O displays solves the issue. If it doesn't for you, then your problem is unrelated to the displays.

Unfortunately turning off the F/O displays only sees an improvement of 2 or 3 FPS. 

Vanilla A320 runs beautifully otherwise.

**Comment by c1be** [comment] 2020-12-02 23:07
Yeah, it has a lot of stutters compared to default, hope some optimizations
are planned in future.

**Comment by Benjozork** [comment] 2020-12-02 23:23
We have said before and I'll say it again, we are planning the process of rewriting all avionics and using different frameworks to improve performance. But you gotta remember that it's probably never gotta perform as well as the default - it has more systems and more complex graphics to simulate and render.

My PR probably won't be merged because the PFD and ND will be redone anyway.

**Comment by mdionizio** [comment] 2020-12-02 23:25
I only messaged again because you repeatedly said that you were releasing a temporary optimization. But no worries, I shall wait for the PFD and ND work to be released.

Thanks for all your work

**Comment by Benjozork** [comment] 2020-12-02 23:33
Plans change, things don't come out as expected.

I know you don't mean bad and that your message was not in bad faith, but we as developers also suffer from this, and it's not that we don't care. The code we have to deal with is simply an enormous spaghetti of logic built upon default avionics code from the game that creates very inefficient patterns. I myself am on a lower end system and the performance annoys me just as much.

I tried doing those temporary improvements but I saw no reduction in frame time. The problem is with the overall structure of the code that is extremely difficult to work with and frankly I prefer keeping this how it is instead of trying to improve performance which will inevitably break 10 other things because of how badly the code was originally written.

This will all be solved when everything is rewritten. Hopefully. We ultimately need to collaborate with Asobo in order to plan things in a way that will ensure best performance going forward.

I am on a system below minimum spec and I find the experience fine. Sure, it's stuttery, but it's a flight sim not Counter Strike. You spend most of your time looking in front of you anyway. I'm not dismissing the problem but if my low end system can yield and acceptable experience on a game that's already graphically and computationally demanding, it's not realistic to target specs even lower than that.

**Comment by Benjozork** [comment] 2020-12-02 23:42
As an experiment, can you report what you are being limited by while looking at the screens ? Use the games FPS counter.

**Comment by mdionizio** [comment] 2020-12-03 00:02
I have a pretty decent system (CPU: I9-9900kf, GPU: RTX 3080). Around 15/20 FPS less than vanilla.

I'll test it in sec and report back.

**Comment by Seth-Dark** [comment] 2020-12-03 00:16
System: 8700k @ 5.1ghz +1080TI overclocked i am limited by GPU when looking at the screens.
When turning off right PFD/ND displays stutters are decreased with glass cockcpit refresh rate at low and much better with Medium ( but with less fps). The main cause of  stutter is for sure PFDs as i made many tests/combinations with each screen on/off +  different refresh rate.

**Comment by G4mer0921** [comment] 2020-12-04 23:18
I would like to give you some more information I recently noticed; a big portion of the stutter, in my case, came from additional liveries I intalled: removing them (all of them) reduced the stutter a lot so I think this should be investigate. Another important things is that I’m experiencing huge frame drops at two specific moments: the exact instant in which the plane leave the ground during t.o. and touch down during landing. This is so specific that could be worth a try to fix it.
Thank you all for the amazing work you are doing! Never give up!

**Comment by AdmiralArtemiy** [comment] 2020-12-15 13:18
Confirm. FPS dropped down to 19-25 FPS from 30-35.

**Comment by michaeldinozzo** [comment] 2020-12-15 16:18
If it can help people while we wait for further optimizations of the PFD & ND, try lowering the cockpit refresh rate in MSFS settings. In my case lowering from Medium to Low increased the FPS by 20+%.

**Comment by AdmiralArtemiy** [comment] 2020-12-15 16:51
> If it can help people while we wait for further optimizations of the PFD & ND, try lowering the cockpit refresh rate in MSFS settings. In my case lowering from Medium to Low increased the FPS by 20+%.

Was set on the lowest. After the msfs update FPS droped by 10-15 FPS

**Comment by JaceR69** [comment] 2020-12-15 20:06
I have the same performance problem, the most fps drops are in final app with sttuters and at the moment that I active the reverse, the fps suddenly drops to a very low level, 5 fps, if I deactivate the reverse, the fps rise but not as the begining of the flight that I have and average of 30FPS locked.

**Comment by Benjozork** [comment] 2020-12-17 05:44
Relevant PRs

**ECAM rewrite**

#2461
#2453

**PFD rework**

#1866

**Comment by amarkhy** [comment] 2020-12-26 12:52
Hello,

first thank you for your work really ! But just to notice, I also have a lot of « low fps » in the cockpit since the new release. 

I’ve puted my refresh rate to low but it’s still the same.

my config is :

ryzen 7 3700X
Rtx2080 super
32go of ram
On 1080P

**Comment by mreza1st** [comment] 2021-01-04 04:51
Low frame rates I experience are both in the cockpit and window views! 12 to 15 fps drop at minimum! Love the FBW and hope they can address this issue.

9th Gen Intel(R) Core(TM) i9 9 900 (8-Core, 16MB Cache, up to 5GHz with Intel(R) Turbo Boos t Technology)
64GB Dual Channel HyperX(TM) F URY DDR4 XMP at 2933MHz
NVIDIA(R) GeForce(R) RTX 2080 SUPER(TM) 8GB GDDR6
2TB M.2 PCIe NVMe SSD (Boot)

**Comment by ArashHosseini** [comment] 2021-01-07 15:36
great work, but same issue as @mreza1st, frame rate drops ~15, i had to uninstall it very sadly

Intel i9 10. Generation
64GB DDR
NVIDIA(R) GeForce(R) RTX 3090

**Comment by Benjozork** [comment] 2021-01-12 22:56
#2976 should resolve this.

**Comment by mreza1st** [comment] 2021-01-13 04:43
Hi, thanks for looking into this. By any chance, would the sound pack have anything to do with the stutters? I do get the significant reduction in the fps and continuous stutters once the engine is turned on in both cockpit and window views (specially the right view)! Just a thought!

**Comment by Benjozork** [comment] 2021-01-13 04:51
If it was, it is an issue with MSFS and we cannot do anything about it. But I would highly doubt that.

**Comment by hotshotp** [comment] 2021-01-13 05:44
> Hi, thanks for looking into this. By any chance, would the sound pack have anything to do with the stutters? I do get the significant reduction in the fps and continuous stutters once the engine is turned on in both cockpit and window views (specially the right view)! Just a thought! 

Absolutely not anything sound related, I can tell you for sure

**Closed** 2021-01-17 03:01 UTC
Labels: Bug, Bug-A32NX, Critical Bug, Performance, Reproduced
