### ISSUE TITLE
[BUG] Problems in FP when DCT after STAR

### ISSUE THREAD

**Issue by alfalfasecas** [flybywiresim/a32nx#2680] opened 2020-12-24 07:06 UTC
**Mod Version**

Master 0.5.1

**Describe the bug**

During the flight, if you make a DCT to any waypoint there is no issue, everything works fine. But once an STAR has started, if you make a DCT to any point, the waypoints of the original FP are not skipped (you start your DCT, but once it has finished, the plane tries to come back to the first waypoint you skipped. This behaviour has been found using Navigraph rev 4 AIRAC, not tested without it.

**To Reproduce**

1. Landing into LEBL, BISBA 1W approach, LESBA transition, ILS-Z RWY 25R
2. Before reaching XAMUR, press DCT to TEBLA (IF)
3. After that, you will start a DCT to TEBLA, but all the waypoint that are part of the TRANS will be kept. Not possible to CLR on the MCDU. 
4. After reaching TEBLA, the plane will fly to the first point of the TRANS you skipped (LESBA)

**Expected behavior**

After making a DCT to any WP once a STAR has started, to erase the skipped ones from the MCDU, at the same it happens once you make a DCT during cruise. If not possible, at least to be able to CLR the skipped WP from the MCDU.

**Actual behavior**

After making a DCT to any WP once a STAR has started, the skipped points are kept on the MCDU. This implies when you reach the DCT WP, the plane comes back to the first WP you skipped. Moreover, it is not possible to CLR these WP from the MCDU manually.

**References**

![Microsoft Flight Simulator 23_12_2020 18_08_38](https://user-images.githubusercontent.com/70801345/103068816-49d91b80-45be-11eb-9700-d409db130c45.png)
![Captura de pantalla (11)](https://user-images.githubusercontent.com/70801345/103068854-5eb5af00-45be-11eb-9271-cb65d285b1b5.png)

**Additional context**

Was this working before/when did the issue start occurring? Not tested with passed release version

Is this a problem in the vanilla unmodded game? No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-12-24 07:08
Duplicate of #1438

**Closed by Benjozork** 2020-12-24 07:09 UTC
Labels: Bug
