### ISSUE TITLE
[BUG] AP doesn't follow flight plan.

### ISSUE THREAD

**Issue by TansyEliot** [flybywiresim/a32nx#1292] opened 2020-10-13 19:34 UTC
**Mod Version**

built: 2020-10-13T17:02:32+00:00

**Describe the bug**

Autopilot doesn't follow the flight plan after takeoff.

**To Reproduce**

1. Insert flight plan in the FMC
2. Takeoff
3. Engage autopilot

**Expected behavior**

Plane should follow flight plan.

**Actual behavior**

The plane doesn't follow the flight plan correctly.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes.

Is this a problem in the vanilla unmodded game?
Yes and no.

Discord username (if different from GitHub): TansyEliot#9914

**Comment by Benjozork** [comment] 2020-10-13 19:52
Duplicate of #159.

**Closed by Benjozork** 2020-10-13 19:52 UTC
Labels: Bug
