### ISSUE TITLE
gps AP issues....no matter what the GPS primary will not align at all, I am aware that there is an ADIR waiting period but I have been using this mod for a while now and no issues until today.  the last time it aligned I took off and was told to fly RWY HDG then I was told to go direct to waypoint in which I turned on MY AP and selected manage HDG mode and the plane took a hard left and nose dived with the AP on and the altitude set correctly.  I do a ton of flights and it has never done this before PLEASE HELP

### ISSUE THREAD

**Issue by mcm71288** [flybywiresim/a32nx#2131] opened 2020-11-29 23:28 UTC
**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by wpine215** [comment] 2020-11-30 00:01
> **BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

Closed for not following issue template at all.

**Comment by Benjozork** [comment] 2020-11-30 00:02
Duplicate of #2089, doesn't respect template

**Closed by wpine215** 2020-11-30 00:01 UTC
Labels: Bug
