### ISSUE TITLE
Certain Autopilot Shortcuts (Events, simvars) not working as they used to

### ISSUE THREAD

**Issue by mojoair** [flybywiresim/a32nx#4347] opened 2021-04-08 10:12 UTC
**Mod Version**
Experimental 8998b9e and all Experimental versions after the split from stock A320.

NOTE: This issue does NOT exist in Developmental version. 

**Describe the bug**
The following shortcut controls when assigned do not work. I'm also providing the sim variable/event code that is associated by default to those shortcuts.

"Increase Autopilot Reference Airspeed" (AP_SPD_VAR_INC, ID: 65896)
"Decrease Autopilot Reference Airspeed" (AP_SPD_VAR_DEC, ID: 65897)
"Increase Heading Bug" (HEADING_BUG_INC, ID: 65879)
"Decrease Heading Bug" (HEADING_BUG_DEC, ID: 65880)

**To Reproduce**
1. Assign any of the above shortcuts in Controls to any key, button or encoder.
2. Try using the shortcut to change Autopilot MCP value, it will not change. But if you look on your MFD, it will show it's changing. If you use tooltips, it will also show changing on the tooltip, but never update on AP MCP.

**Expected behavior**
Shortcuts change values in AutoPilot MCP like they used to in prior releases.

**Actual behavior**
SPD and HDG Values in AP MCP do not change when using assigned shortcut keys/events. But the MFD shows both Airspeed and Heading change when using shortcut keys assigned. I also noted in reviewing the Event Viewer from FSUIPC7 (I do not use any key bindings in FSUIPC7), you don't see an event registering when you change AP Speed or AP Heading, but you do see one when changing AP Altitude (The shortcut for Altitude works just fine).

Was this working before/when did the issue start occurring? Yes, it used to work on all variants of A32NX including CAP. Issue started recently after the split on Experimental version only.

Is this a problem in the vanilla unmodded game? No

**Comment by tracernz** [comment] 2021-04-08 10:35
Duplicate of https://github.com/flybywiresim/a32nx/issues/4255
This may come later as the new autopilot develops.

**Closed by tracernz** 2021-04-08 10:35 UTC
Labels: Bug
