### ISSUE TITLE
During take off, the flight plan line on the ND disappears a moment to reappear later

### ISSUE THREAD

**Issue by PatriceCesson** [flybywiresim/a32nx#4086] opened 2021-03-23 09:01 UTC
**Mod Version**

{
  "built": "2021-03-22T12:58:17+00:00",
  "ref": "master",
  "sha": "316984c4eb8f1fafc83647a549a1c7b514b867d6",
  "actor": "MisterChocker",
  "event_name": "manual"
}
 and also
{
  "built": "2021-03-18T05:12:53+00:00",
  "ref": "fbw",
  "sha": "545c47204bd9d7c99197555c5687dc2bd79c2f6c",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Describe the bug**
1. I have a flight plan in the MCDU and the flight plan is displayed on the ND before take off.
2. I take off, The flight plan line is still  displayed on the ND
3.  After a short time after take off, the flight plan line disappears from the ND (rose or arc mode). Only displayed are the waypoints.
4.  After some time later (Setting CLB mode, AP activation, next turn), the flight plan line reappears and no problem after that.

**Steps To Reproduce**
See above.

**Expected behavior**
The flight plan line should never disappear from the ND.

**Actual behavior**
See above.

**References**
I will try to add one very soon.

**Additional context**
Nothing special to notice. Simplae flight from LFRN to EGKK, FP imported via the load function of the SIM.

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
I do not know as I do not use the vanilla airbus.

Discord username (if different from GitHub):

**Comment by PatriceCesson** [comment] 2021-03-23 09:36
Here are some screenshots:
FP display before take off
![snap049](https://user-images.githubusercontent.com/30781354/112125013-448e6b80-8bc3-11eb-9781-eada2ad6b54a.png)
FP display just after take off
![snap050](https://user-images.githubusercontent.com/30781354/112125062-5112c400-8bc3-11eb-9739-a85649a1121f.png)
FP display a moment later (line has disappeared)
![snap051](https://user-images.githubusercontent.com/30781354/112125100-5c65ef80-8bc3-11eb-9371-9b95ea283899.png)
FP display on first turn PA activated (FP line is OK)
![snap052](https://user-images.githubusercontent.com/30781354/112125233-7ef80880-8bc3-11eb-8e0d-76c76f121584.png)

**Comment by Watsi01** [comment] 2021-03-23 16:14
Can confirm that. Have the same behaviour. Route line reappears after passing the next wp.

**Comment by Watsi01** [comment] 2021-03-23 16:20
@PatriceCesson Do you use Navigraph?

**Comment by PatriceCesson** [comment] 2021-03-23 16:57
Yes I use navigraph (included in community folder)

**Comment by Watsi01** [comment] 2021-03-23 17:05
> 
> 
> Yes I use navigraph (included in community folder)

Me too. Could be a Navigraph thing...

**Comment by jmihalich** [comment] 2021-03-23 17:30
I've seen this several times as well.

**Comment by ErikNL80** [comment] 2021-03-23 17:55
Reproduced this today when departing from Orly. Using stock NavData...

**Comment by Watsi01** [comment] 2021-03-23 18:00
Thanks @ErikNL80. I'm kinda glad it's not an issue related to Navigraph data only.

**Comment by PatriceCesson** [comment] 2021-03-23 19:49
To notice: I am seeing this since a few versions ago only (perhaps the 3 or 4 previous versions I do not know exactly). It was not there before in the FBW A320. And this occurs with both FBW version: development version and custom FBW version.

**Comment by Watsi01** [comment] 2021-05-05 07:03
I think I know now what the problem is: everytime the flightplan (especially the SID) has waypoints included, which can't be displayed by the MCDU - e.g. waypoints with lowercase letters, like "Intercept" or "Altitude" - the line dissapears during takeoff / initial climb. With "normal" waypoints, this does not happen.

Since the current MCDU font does not support lowercase letters, maybe we need something which converts lowercase letters in the flightplan to uppercase letters.

**Comment by PatriceCesson** [comment] 2021-05-05 07:42
Yes. It works. I remove an "Altitude" WP from my FP in the departure and the FP remains OK in the ND.
Thanks.

**Comment by toolpusher33** [comment] 2021-05-26 15:46
I have similar problem this happens on a short flight that I have used many time to test ILS landings. Since yesterday I no longer see the green line on the ND when I select low altitude air ways. I dont like Navigraph but have used it in the past so I just plan the flight from the sim loading screen . But if I fly VFR or Vor-Vor I do see the green line--tried every thing

**Comment by 2hwk** [comment] 2021-11-21 07:13
Fixed by 4953 closing ☑️

**Closed by 2hwk** 2021-11-21 07:13 UTC
Labels: Bug, ND, FPM, fixed in cFPM
