### ISSUE TITLE
FOB shows zero even though fuel is loaded

### ISSUE THREAD

**Issue by delta5150** [flybywiresim/a32nx#5509] opened 2021-08-02 00:28 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-31T20:53:08+00:00",
  "ref": "master",
  "sha": "12dd02fba9f16606942a76176c73dfb3da230cfa",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Spawning C/D at KAVL gate 55. No fuel amount displayed even though 20.5 lbs loaded. This happened last week also.

### Expected behavior

Fuel On Board should display correctly.

### Steps to reproduce

Spawn C/D
Power up aircraft
Check display amount (shows zero)
Check actual fuel load in MSFS drop menu. Shows 20.5 LBS

### Additional info (optional)

This happened last week. I would love to revert to the dev that I had last week but it won't work with SU5.

### Discord Username (optional)

delta5150

**Comment by Skkkitzo** [comment] 2021-08-02 13:44
Can second this, every flight I do the aircraft spawns in with 0 FOB on MCDU. PERF page shows:
![PERF page](https://user-images.githubusercontent.com/20148107/127871594-827036c0-0471-4269-be72-7da1a0ce8208.png)

**Comment by NUTTTTTTTT** [comment] 2021-08-02 14:01
@Skkkitzo @delta5150 This is a known issue, if you're set as LB's, change to KG in the MCDU, reload the flight and then change in the MCDU, not the EFB/Flypad. Reload the flight again and you should be good to go.  

The issue is that the lbs setting in the EFB is broken, and sets the conversion factor to 0, so all weights on the displays go to zero. The work-around is to set lbs through the MCDU then reload the aircraft (do not touch the pounds option on the EFB).

Fix is in-progress https://github.com/flybywiresim/a32nx/pull/5344

**Comment by delta5150** [comment] 2021-08-02 14:20
@NUTTTTTTTT 
Thank you very much sir!

**Comment by MisterChocker** [comment] 2021-08-03 09:15
Duplicate of #5316

**Closed by MisterChocker** 2021-08-03 09:15 UTC
Labels: Bug
