### ISSUE TITLE
[BUG] ECAM - LDG LT not displayed with Logitech Flight Panels

### ISSUE THREAD

**Issue by JLD95** [flybywiresim/a32nx#2700] opened 2020-12-25 08:39 UTC
**Mod Version**

2020-12-23T23:38:26+00:00

**Describe the bug**

When landing light are switch on with  Logitech Flight Panels, the buttons on overhead panel inficated ON, the landing lights in external view are illuminated but in ECAM, no "LDG LT" is displayed.

**To Reproduce**

1. In cruise flight, set landing lights with Logitech Flight Panels
2.
3.

**Expected behavior**

"LDG LT" shall be displayed with Logitech Flight Panels

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
not tested

**Comment by Benjozork** [comment] 2020-12-25 18:35
Most likely the same issue as #1507.

> Is this a problem in the vanilla unmodded game?
> not tested

Can you test it ?

**Comment by MisterChocker** [comment] 2020-12-25 21:25
most likely the same because it doesn't work with a key bind.

**Comment by JLD95** [comment] 2020-12-26 05:40
Hi tested without NX mod, LDG LT is never displayed on ECAM whether cliking with mouse on cockpît or the Logitech Flight Panel buttons

**Comment by MisterChocker** [comment] 2020-12-31 05:56
duplicate of #1507

**Closed by MisterChocker** 2020-12-31 05:56 UTC
Labels: Bug, Bug-Vanilla
