### ISSUE TITLE
no taxi with idle thrust possible after 22th update

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2637] opened 2020-12-23 07:11 UTC
**Mod Version**

DEV

**Describe the bug**

it isen´t possible to taxi with idle thrust, like it was before. min 40% thrust needed to taxi. (6000kg fuel, 41% payload)

**To Reproduce**

1.cold and dark start
2.try to taxi with idle thrust like befor or IRL
3.

**Expected behavior**

plane should start moving with idle thrust

**Actual behavior**

plane do not start moving with idle thrust, only with significant amount of thrust (6000kg fuel, 41%payload)

**References**

actual state

**Additional context**

Was this working before/when did the issue start occurring?
yes
Is this a problem in the vanilla unmodded game?
-

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-12-23 07:16
Cannot reproduce. Can you show a screenshot of your upper ECAM ?

**Comment by pareil6** [comment] 2020-12-23 08:19
Also cannot reproduce, are you sure the game is loading the mod? (Based on #2638 as well...)

**Comment by andrejetcat** [comment] 2020-12-23 08:21
yes, i´m definitely shure that is the 0.5.1 DEV build, loaded via downloader.

**Comment by andrejetcat** [comment] 2020-12-23 08:33
no  notice, after landing, that the plane moves with idle thrust...but before takeoff it doesen´t. i rechecked it, when i taxi for takeoff, i will not move by idle thrust. (short flight, eddf-egll, 6t fuel, 41% payload) so now it works @ destination

**Comment by iFred320** [comment] 2020-12-23 08:58
Same issue here. 40 % Thrust was needed.
Idea: Could be weather/surface related, had heavy rain when it occured. Will test in CAVOK and report later.

**Comment by wpine215** [comment] 2020-12-23 08:59
> 
> 
> Same issue here. 40 % Thrust was needed.
> Idea: Could be weather/surface related, had heavy rain when it occured. Will test in CAVOK and report later.

Yep, please try on a light/normal load, at an airport near sea level during clear weather.

**Comment by andrejetcat** [comment] 2020-12-23 09:04
I landed @ EGLL with real weather, also rain and cold temp. There i don´t have that phenomena and taxing with idle works as it should. When i takeoff in Frankfurt, 1 hour ago, also with real weather, rain and so on, it was there.

**Comment by iFred320** [comment] 2020-12-23 09:49
Clearly reproducable for me: Change weather preset to CAVOK: Everything good, change it to STORM (Wet surface) and voilá. Snow doesnt matter, the rain is the problem.

**Comment by pareil6** [comment] 2020-12-23 09:52
Throwing in another datapoint - I can taxi on idle thrust in the dry (although it does feel slightly less powerful than before, but not sure if I'm imagining that), but the plane won't roll on idle thrust in the wet.

**Comment by andrejetcat** [comment] 2020-12-23 12:04
strange, when i takeoff in wet condition, idle taxing is not possible, but when i land in that condition, it is!

**Comment by MisterChocker** [comment] 2020-12-23 15:31
> strange, when i takeoff in wet condition, idle taxing is not possible, but when i land in that condition, it is!

Do you have TOW and LW for us?

**Comment by IcedLemonTea** [comment] 2020-12-23 16:30
Can confirm idle taxi not possible in rain. 64 Tonne TOW, 62 Tonne LW. Did a live weather EHAM-EGCC and needed around 40% thrust to taxi for both departure and arrival and it was raining heavily at both airports

**Comment by donstim** [comment] 2020-12-23 22:08
Confirm that runway wetness level has an effect on taxi. Dev mode debug wheel screen shows level of wetness in %. At least on a surface type concrete" runway as the wetness level increases, it appears to provide more rolling resistance. At 100% runway wetness, it takes higher N1 (in the 40's range as noted by the commenters above) to initiate taxi at the default weight.

I don't know of a way to manipulate the runway wetness level to keep it at a certain amount to test its effect on rolling and braking friction. It seems like with anything weather-related, Asobo has greatly exaggerated the effect of a wet runway. IRL, standing water will provide a significant drag force, but with well-designed crowned and especially, grooved runways, this is a rare occurrence.

**Comment by andrejetcat** [comment] 2020-12-24 14:51
@donstim can confirm from real life, that standing water is for shure a additional friction factor. But is is mainly perceptible @ higher taxi speed. When you initiate taxi, its mainly no (or a very small) factor. For shure, if you taxi with 30kts GS at an airport with 2cm standing water, you will have some %´s more N1 needed for taxi. but 40%+ is a way too much! :)

**Comment by hotshotp** [comment] 2020-12-25 03:56
closing as it is intentional by asobo on wet runways, we cant really edit the idle thrust more since it would be way too overpowered so we will wait until asobo changes this

**Closed by hotshotp** 2020-12-25 03:56 UTC
Labels: Bug
