### ISSUE TITLE
Any plans to have the Flypad working in VR

### ISSUE THREAD

**Issue by LordNecton** [flybywiresim/a32nx#5458] opened 2021-07-29 11:29 UTC
### Aircraft Version

Development

### Description

I can turn the Flypad on but apart from that you cant click anything...

Im Flying the latest Dev build as of this morning..Love flying this aircraft in VR id love to be able to use the Flypad in it

Keep up the good work guys

**Comment by wined2310** [comment] 2021-07-29 12:55
what is your VR Hardware?

I'm running an Oculus Rift CV1 and the flyPad is working just fine for me...

**Comment by LordNecton** [comment] 2021-07-29 14:24
Im using the Oculus quest 2 via the official link cable....As i said i can turn it on but switching between menus  is a no go

**Comment by 2hwk** [comment] 2021-07-30 21:08
Yes, there are plans, however there are some blocking issues we have to work out. As this is a duplicate of https://github.com/flybywiresim/a32nx/issues/3493, this is being closed. Thank you.

**Closed by 2hwk** 2021-07-30 21:08 UTC
Labels: Enhancement
