### ISSUE TITLE
FPS Reduces by 12=15 fps

### ISSUE THREAD

**Issue by mreza1st** [flybywiresim/a32nx#2859] opened 2021-01-03 21:41 UTC
I deleted the FBW A320 to see the change in frame rate since it was getting fairly bad with lots of stutters. The frame rate is 12 to 15 fps higher with the MSFS A320! The stutters are a lot less and the sim seemed significantly smoother! I hate not using FBW since it has a lot of good things (including a significantly better flight model) but the the 12-15 fps decline frame rate is significant! With the MSFS A320 I am getting frame rates in the range of 40 to 55 which is fairly reasonable and smooth. I saw some other comments regarding this but the lower frame rate that I am experiencing is both inside the cockpit and outside (i.e. window views, etc.). My settings are generally high with terrain at 200 and render at 100.

9th Gen Intel(R) Core(TM) i9 9 900 (8-Core, 16MB Cache, up to 5GHz with Intel(R) Turbo Boos t Technology)
64GB Dual Channel HyperX(TM) F URY DDR4 XMP at 2933MHz
NVIDIA(R) GeForce(R) RTX 2080 SUPER(TM) 8GB GDDR6
2TB M.2 PCIe NVMe SSD (Boot)

**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by Benjozork** [comment] 2021-01-03 21:44
Duplicate of #1341

**Closed by Benjozork** 2021-01-03 21:44 UTC
Labels: Bug
