### ISSUE TITLE
[BUG] VOR needle missing 

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/a32nx#2195] opened 2020-12-02 23:13 UTC
**Mod Version**
Latest branch and stable release

**Describe the bug**
VOR needles in ARC MODE missing.

**To Reproduce**

1.
2.
3.

**Expected behavior**
VOR needles should appear in ARC MODE  even if RAD NAV its in manual mode or automatic mode .

**Actual behavior**
Not appear

**References**
![image](https://user-images.githubusercontent.com/74787268/100942823-4e993b00-34fc-11eb-8be5-f6a2b3d7e250.png)

**Additional context**

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-12-03 14:04
This reference is for the EIS1 display standard (CRT screens). Can you provide a reference for EIS2 (LCD panels) ?

**Comment by tareksabet** [comment] 2020-12-03 17:52
> This reference is for the EIS1 display standard (CRT screens). Can you provide a reference for EIS2 (LCD panels) ?

@Benjozork it's the same in the neo

**Comment by tareksabet** [comment] 2020-12-03 18:00
Aslo @Benjozork here's a reference ![image](https://user-images.githubusercontent.com/70240330/101069043-666ece80-3591-11eb-97d7-64ce271543ed.jpeg)

**Comment by MisterChocker** [comment] 2021-03-05 15:30
Duplicate of #3055

**Closed by MisterChocker** 2021-03-05 15:30 UTC
Labels: Bug, Needs Reference
