### ISSUE TITLE
[BUG] Direct-To Stops Waypoints Being Cycled

### ISSUE THREAD

**Issue by Relayer2112** [flybywiresim/a32nx#3442] opened 2021-02-09 13:08 UTC
**Mod Version**
Master - 2717c0251ce67363fd4295cb19567255a0183bd1

**Describe the bug**
Selecting 'direct to' an approach waypoint (i.e after the autopilot goes direct to rwy after a STAR), flies to the directed waypoint but does not cycle to the following waypoints in the approach, instead orbits the waypoint the direct-to was commanded to.

**To Reproduce**
1. Select approach +  STAR
2. At end of STAR, instead of continuing to next approach waypoint, aircraft goes direct to rwy waypoint
3. Select DIR and scroll through flight plan to the expected next waypoint in the approach, insert as a 'direct to' (EG 'a')
4. Aircraft will fly to designated waypoint ('a'), but will not proceed to next waypoint in flightplan ('b').

**Expected behavior**
Aircraft should resume cycling through waypoints as they are reached after a 'direct to' waypoint

**Actual behavior**
Aircraft does not cycle to next waypoint and orbits current waypoint

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Noticed in last 2 days

Is this a problem in the vanilla unmodded game?
Unknown

Discord username (if different from GitHub):
Relayer2112#6791

**Comment by DFWSupertrooper** [comment] 2021-02-09 13:11
This is happening to me too.  I usually engage the DIR TO after the generic RWY turn error if I need the route for an RNAV approach (otherwise I simply use HDG mode to the ILS intercept).  RNAVs are no longer able to be flow at all if the route is interrupted for any reason now.

**Comment by GlitchedYT** [comment] 2021-02-09 13:45
@Relayer2112, this is a known issue and will be corrected when our Custom FPM is implemented. For now the workaround is to either fly manually or use selected heading.

**Comment by MisterChocker** [comment] 2021-02-09 17:54
Duplicate of #1745

**Closed by MisterChocker** 2021-02-09 17:54 UTC
Labels: Bug
