### ISSUE TITLE
Keyboard not working in flight

### ISSUE THREAD

**Issue by bluedoors** [flybywiresim/a32nx#2377] opened 2020-12-12 07:27 UTC
```
{
  "built": "2020-12-11T05:42:25+00:00",
  "ref": "",
  "sha": "",
  "actor": "Kimbyeoungjang <kim9431237@naver.com>",
  "event_name": "manual"
}
```

Have also tried Stable build
No additional mods/liveries etc
Standard MS aircraft works without issue

Running Logitech:
Extreme 3d Pro
Switch panel
Comms panel
Mult panel
Rudder pedals

Keyboard is unresponsive as soon as you say go fly with the flybywire mod. didn't previouslty have a problem but upgraded a few weeks ago to latest stable and have had problem since. Tried latest development in case that fixed things.

Have tried removing some USB devices, or running them on another bus. BUT the fact the Windows key still works suggests to me this is not USB hardware related but software. 

What logs/debug information can i provide to help track this issue down as it is unusable in it's current state :(

**Comment by Benjozork** [comment] 2020-12-12 07:30
Duplicate of #1575

**Closed by Benjozork** 2020-12-12 07:30 UTC
