### ISSUE TITLE
[BUG] Autopilot Heading

### ISSUE THREAD

**Issue by Abyssial** [flybywiresim/a32nx#1171] opened 2020-10-07 18:21 UTC
**Master**

**Autopilot Heading does not work in Managed or in Manual mode. The plane will start roll to the left or right, very erratic at times where the plane will roll 20 degrees left or right out or nowhere and not recover.**

**To Reproduce**

1. Start the flight and setup a route in the FMC
2. Fly the flight on autopilot
3. The plane should not be able to hold the heading for very long and should start to bank as mentioned and described above instead of flying steady. You will need to input very small elevator movement to get it back on course

**The plane should follow the route exactly, occasional turbulence is expected but it should recover from it**

**Never recovered from turbulence or from gradually entering a roll to the left or right, you cannot leave the plane alone at all even to use the restroom without worry**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

This started within the last week of development on the beta releases, not sure what patch it started in exactly but it was working before that

Is this a problem in the vanilla unmodded game?

No

Discord username (if different from GitHub): Byss#6994

**Comment by Abyssial** [comment] 2020-10-07 18:29
Ahhh, I messed up under Step 1 to reproduce by saying but a route in the FCU, meant the MCDU

**Comment by Abyssial** [comment] 2020-10-08 03:00
Just tested this issue in V0.3.1, the issue is not present, present in the latest master though

**Comment by Benjozork** [comment] 2020-10-08 03:48
This is unlikely to be caused by a change in the mod since we do not control the autopilot. A/P errors are random are pretty erratic, so the difference you saw between master and 0.3.1 is probably a fluke.

**Comment by Abyssial** [comment] 2020-10-08 03:57
Thanks for the comment, I can't help but say that I flew 3 flights with the master and had this problem, they were all on separate days with different routes, no common arrival or departure airport. Today when I switched to the V0.3.1 it was like a dream, perfect heading holding. Could just be the game being weird or what not, I'm no programmer so I am unsure. 
Thanks for the clarification,
Byss

**Comment by Benjozork** [comment] 2020-10-08 04:23
I will be checking this with QA. Thanks.

**Comment by Abyssial** [comment] 2020-10-08 05:04
Thanks

**Comment by donstim** [comment] 2020-10-09 07:25
I have not had this issue on any version, from the unmodified up through the current master mod version EXCEPT when using a controller that would not return exactly to center and was not calibrated with an appropriate dead zone. This may not be your issue Abyssial, but checking your controller calibration in Windows Game Controllers Control Panel and setting an appropriate dead zone (anywhere from 5% to 10-20% depending on controller) has fixed this issue for a number of people.

**Comment by dhkim0800** [comment] 2020-10-09 09:13
I'm using 0.3.1, 1.9.3.0 and this happened to me while using managed heading mode. I'm just using Xbox One controller.

**Comment by wills-web** [comment] 2020-10-09 14:22
I've been using the same versions as dhkim0800 and my old Logitech Attack 3 joystick while I wait for the Airbus stick/throttle combo to release. My stick leans right ever so slightly, and doesn't usually cause me any issues, but I have the exact same symptoms.

Problem was solved when I unplugged the stick (following a short game freeze).

**Comment by Abyssial** [comment] 2020-10-09 15:31
When using the master and v0.3.2 the only thing I changed was the version of the addon, I used the same controller when I was playing. You could be right I won't knock it but I am no confident that it is my problem

**Comment by dhkim0800** [comment] 2020-10-09 16:16
Switching to AP2/AP1 might be the workaround. Right after than the plane fixed heading for me.

**Comment by Mariolink123** [comment] 2020-10-10 12:23
I've only experienced this bug when I've flown on pre-defined flight plans set from the MFS 2020 Menu, and not the planes FMC.

**Comment by fourdragons** [comment] 2020-10-10 12:29
I’m sure the gamepads are great, but it sure seems they cause this problem a lot. 90% (made up) of those reporting it are using gamepads.

**Comment by Flyingtrader06** [comment] 2020-10-21 16:03
The aircraft also needs to be able to bank at 30 degrees bank instead of the current 20 degrees, otherwise it constanstly overshoots procedures.

**Comment by MisterChocker** [comment] 2020-12-31 06:37
The bank issue will be addressed by our own ap.
Closing since game updates improved AP behavior. Can be reopened or create a new issue if this exists.

**Closed by MisterChocker** 2020-12-31 06:37 UTC
Labels: Autopilot, Bug, Needs Verifying
