### ISSUE TITLE
CTD printing METAR

### ISSUE THREAD

**Issue by WooleyPig** [flybywiresim/a32nx#6141] opened 2021-11-05 17:19 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-04T17:07:11+00:00",
  "ref": "master",
  "sha": "8b09e54b4ae1a0269f59e78829cf24cb35cc6a5e",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

CTD every time I hit the 'Print' button for a METAR

### Expected behavior

No CTD when I print a METAR

### Steps to reproduce

Starting at Gate 566 at Gatwick (DAGGA 1M SID) to ENBR - ILS RWY35W - (BADA 2P STAR) 
Power up A320NX on external power
request METAR for EGKK and ENBR
Wait for 'Company MSG'
View new METAR
Click 'Print' option

### References (optional)

N/A

### Additional info (optional)

Sim Update 6 installed.

INIT and PREF set up before requesting the METAR's.

Updated to the latest Development build today before firing up MSFS 2020, was fine last time I played with previous development build.

Never have I ever had an issue printing before now and it crashed again after restarting MSFS.

Thanks

### Discord Username (optional)

WooleyPig #8444

**Comment by Benjozork** [comment] 2021-11-05 17:29
Duplicate of ##5429

**Closed** 2021-11-05 17:29 UTC
Labels: Bug
