### ISSUE TITLE
[BUG] Activating CSTR freezes secondary display (ARC)

### ISSUE THREAD

**Issue by yeyep** [flybywiresim/a32nx#1400] opened 2020-10-16 14:33 UTC
**Mod Version**
```
built: 2020-10-16T00:15:31+00:00
ref: refs/heads/master
sha: e08f84b3c7db7767aab2c34c8a90ea059bd1f9fe
actor: lukecologne
event_name: push
```

**Describe the bug**
When I activate CSTR and have ARC selected the display freezes' and doesn't move with the location of the plane.

**To Reproduce**
1. Have flightplan (KSFO - KSAN)
2. Active CSTR at any time --> Freeze

**Expected behavior**
Display doesn't freeze and move's with the airplane position and simply works.

**Actual behavior**
Freeze as soon as I activate CSTR. Without it everything works as expected.

**References**
I'm in the air, but activated CSTR during plane startup therefore the display is still stuck. I would also freeze mid air.
Co-pilot display shows what I expected, but if I click CSTR on co-pilot side the display freezes as well.
![image](https://user-images.githubusercontent.com/5039883/96271208-e2568c80-0fcc-11eb-9219-6213f783a4f7.png)

**Additional context**

Was this working before/when did the issue start occurring?
With the latest MSFS patch. Before everything worked as expected.

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-10-16 16:13
Duplicate of #1309

**Closed by Benjozork** 2020-10-16 16:13 UTC
Labels: Bug
