### ISSUE TITLE
[BUG] Library is broken(XMAS version only)

### ISSUE THREAD

**Issue by kiokio0987** [flybywiresim/a32nx#2651] opened 2020-12-23 13:32 UTC
**Mod Version**

{
  "built": "2020-12-23T08:54:29+00:00",
  "ref": "",
  "sha": "",
  "actor": "Will Pine <wpine215@gmail.com>",
  "event_name": "manual"
}

**Describe the bug**

The FBW(XMAS) version of the library is broken.
The wings have a strange texture when the camera is moved farther away in the EXTERNAL view.

**To Reproduce**

1.Spawn at the gate of EGLL airport
2.Switch to External view.
3.Move the camera further away
4.Only the FBW(XMAS) version has a broken wing texture.

**Expected behavior**

Texture must not be broken

**Actual behavior**

Strange textures are discovered

**References**

Zoom Level 48% (No problem)
![zoom_level_48](https://user-images.githubusercontent.com/75520968/102999702-dfe45600-456c-11eb-82d4-abc44c655b5e.jpg)

Zoom Level 13% (broken)
![zoom_level_13](https://user-images.githubusercontent.com/75520968/103001412-4c148900-4570-11eb-955f-70ca09bf4d66.jpg)

**Additional context**

Was this working before/when did the issue start occurring?
From 1.12.13.0 onwards

Is this a problem in the vanilla unmodded game?
YES
Because the library of other aircraft is broken in the same way.
It is possible that asobo has changed the structure of the library.

I don't have any mods other than A32nx.

Discord username (if different from GitHub):

**Comment by kiokio0987** [comment] 2020-12-23 13:44
Correction of image

**Comment by pepperoni505** [comment] 2020-12-23 17:45
This isn't an issue caused by the mod, for some reason the lower LODs have those strange textures. I'll look into it

**Comment by kiokio0987** [comment] 2020-12-24 10:59
pepperoni505 Thank you very much for your useful advice.
I adjusted the graphics settings. 
The best effect was achieved by doing the following. (but not completely restored) 

"Increased the value of OBJECTS LEVEL OF DETAIL from 100 to 200".
![WS000010](https://user-images.githubusercontent.com/75520968/103083890-e92efa80-4620-11eb-905f-b0e32f50561b.JPG)

ZOOM LEVEL also recovered from 13% to 10%.　(Less than 9% resulted in a strange texture.)
![zoom_level_10](https://user-images.githubusercontent.com/75520968/103083902-f21fcc00-4620-11eb-99ab-c2492577ab78.jpg)


As the issue does not seem to be caused by this mod, I will report the problem to Zendesk.
Should I close this forum?

**Comment by pepperoni505** [comment] 2020-12-24 19:51
Yes, please report that to their Zendesk. I will close this issue

**Closed by pepperoni505** 2020-12-24 19:51 UTC
Labels: Bug
