### ISSUE TITLE
VORs stuck in Manual and do not auto tune

### ISSUE THREAD

**Issue by ccapilot** [flybywiresim/a32nx#4107] opened 2021-03-25 13:14 UTC
**Mod Version**
  "built": "2021-03-24T18:18:10+00:00",
  "ref": "master",
  "sha": "a81ec5b30f7af1106e2140ded249321625a64cb2",
  "actor": "tracernz",
  "event_name": "manual"

**Describe the bug**
VOR are always stuck in manual mode and hence they are not auto tuning during flight.

**To Reproduce**
1. after takeoff, CLR whatever VORs you have selected for your departure, if any.
2. see that in ND both VOR are in Manual when they should be auto-tuning
3.

**Expected behavior**
After Clearing the VOR at the RAD NAV page, they should start to auto tune, and associated M should disappear form ND

**Actual behavior**
VORs are clear at the RAD NAV page, however they appear with white M in ND, which means they are in manual but there are no VORs manually selected.

**References**
![nav rad and vor](https://user-images.githubusercontent.com/71601106/112478399-69ced580-8d8d-11eb-8ef7-f655ccd0e8ff.jpg)

**Additional context**

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
I don't know, I don't use vanilla 

Discord username (if different from GitHub):

**Comment by Watsi01** [comment] 2021-03-25 17:09
This is a known issue. Or better to say, we didn't work on the autotuning yet.

**Comment by tracernz** [comment] 2021-03-25 17:44
I have some WIP, but it's not ready yet.

**Comment by MisterChocker** [comment] 2021-03-26 11:49
Duplicate of #2050

**Closed by MisterChocker** 2021-03-26 11:49 UTC
Labels: Bug
