### ISSUE TITLE
MCDU FPLAN deleted and INIT page cleared during flight after choosing DIR to button

### ISSUE THREAD

**Issue by obadvw** [flybywiresim/a32nx#4456] opened 2021-04-16 11:59 UTC
**Mod Version**

```json
{
  "built": "2021-04-15T22:57:32+00:00",
  "ref": "v0.6.0",
  "sha": "981b2e4b0e89998d21a70fe26de54a2f10066f6e",
  "actor": "Benjozork",
  "event_name": "manual"
}

```

**Describe the bug**

FPLAN deleted and INIT page cleared during flight after choosing DIR to button

**To Reproduce**

1.During Flight click DIR button
2.Choose another waypoint from the flight plan

**Expected behavior**

Plane to go direct to selected Waypoint

**Actual behavior**

Flightplan page will be wiped and init page is cleared , you have to fill all from scratch , issue in intermittent
PPOS displayed in the FPLAN page

**References**

**Additional context**

Was this working before/when did the issue start occurring? just noticed it recently

Is this a problem in the vanilla unmodded game? i dont know

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment] 2021-04-16 17:14
Duplicate of #1798

**Closed by MisterChocker** 2021-04-16 17:14 UTC
Labels: Bug
