### ISSUE TITLE
[BUG] Landing height announcements too quiet 

### ISSUE THREAD

**Issue by wb747** [flybywiresim/a32nx#1663] opened 2020-10-31 12:07 UTC
**Mod Version**

master 

**Describe the bug**

The height announcements in the landing Phase (1000, 500, ..., retard) are too quiet and should be louder. It is hard to hear because of the engine noise.  

**To Reproduce**

1. During ILS landing under 1000 ft height.
2.
3.

**Expected behavior**

announcements volume well  over engine noise 

**Actual behavior**

Volume too quiet.

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by ntlgr** [comment] 2020-10-31 23:51
Kudos for this report. I can barely hear that in the sim as well and have tweaked sliders, changed speakers, used HDMI outputs, to no avail. I also don't think there is an "approaching minimums" and "minimums" callout.

**Comment by hotshotp** [comment] 2020-11-01 15:22
Hey, so with new engine sounds, wind sounds, and fan sounds the default gpws call-outs became way too quiet. I'm in the process of remaking the call-outs to be louder

**Comment by ntlgr** [comment] 2020-11-01 15:39
You guys rock. Thanks.

**Comment by wb747** [comment] 2020-11-01 18:44
> Hey, so with new engine sounds, wind sounds, and fan sounds the default gpws call-outs became way too quiet. I'm in the process of remaking the call-outs to be louder

Thank You 😀

**Comment by c1be** [comment] 2020-11-01 21:10
I can confirm this, they are way too quiet, you really have to focus if you want to hear them, they should be loud and clear.

**Comment by ntlgr** [comment] 2020-11-01 22:20
It would also be good to know which of the volume sliders is affecting those altitude callouts (warnings? cockpit? voices?) Does anyone know?

**Comment by hotshotp** [comment] 2020-11-02 03:53
> It would also be good to know which of the volume sliders is affecting those altitude callouts (warnings? cockpit? voices?) Does anyone know?

warnings. but they are too quiet even at 100 and i will make them loud and clear :)

**Comment by wb747** [comment] 2020-11-08 16:43
Anything new on this issue?

**Comment by c1be** [comment] 2020-11-11 09:49
> Anything new on this issue?

As far as i know they're working on it, hope to hear some info about it.

**Comment by ntlgr** [comment] 2020-12-02 09:38
Hey team, just wondering when this change will be made and merged? For some people with hearing difficulties that can be very important. Many thanks.

**Comment by hotshotp** [comment] 2020-12-02 11:08
> Hey team, just wondering when this change will be made and merged? For some people with hearing difficulties that can be very important. Many thanks. 

Not soon unfortunately. This would require me to remake every single radio call-out I'm the sim. It's not as easy as changing a slider, I really wish it was.

**Comment by ntlgr** [comment] 2020-12-02 11:32
Understood, knowing a bit about audio editing on computer, I imagined it would be easy to just amplify volume, software tools like adobe audition can do batch-processing-amplify many files at once. No worries. Efforts are much appreciated, as long as it happens at some time.

**Comment by hotshotp** [comment] 2020-12-02 11:34
> Understood, knowing a bit about audio editing on computer, I imagined it would be easy to just amplify volume, software tools like adobe audition can do batch-processing-amplify many files at once. No worries. Efforts are much appreciated, as long as it happens at some time.

It's a thing with wwise. Since asobo didn't give us a wwise project, we have to make our own files if we want to make changes. So I'll have to make completely new audio call-outs and warnings and match them with volume in wwise then rewrite the code for everything to call the new wwise event

**Comment by ntlgr** [comment] 2020-12-02 11:36
Got it! that is much more complex than I thought! Thanks for the update.

**Comment by MisterChocker** [comment] 2020-12-31 05:41
@hotshotp did we worked on this since then?

**Comment by hotshotp** [comment] 2020-12-31 05:42
> @hotshotp did we worked on this since then?

I started doing some work on it but it's going slow as it's not really a priority right now

**Closed** 2021-03-29 18:49 UTC
Labels: Audio, Bug
