### ISSUE TITLE
LDG Lt ECAM message not updated when switched ON from HOTAS [BUG]

### ISSUE THREAD

**Issue by lve0200** [flybywiresim/a32nx#1507] opened 2020-10-23 14:53 UTC
**Mod Version**

Master as of 22.10.

**Describe the bug**

When LDG LT is switched ON (from retracted) via an HOTAS switch, nothing happens in the ECAM, but the lights go on. Only when switched ON on Ovhd Panel via mouse, the msg appears.

**To Reproduce**

1. Switch LDG LT to retracted and switch LDG LT ON from a switch on your throttle/stick.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

SAITEK X55

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
n/a

Discord username (if different from GitHub):

**Comment by Benjozork** [comment] 2020-10-23 15:25
> Is this a problem in the vanilla unmodded game?

Please fill in the missing information. Thanks!

**Comment by lve0200** [comment] 2020-10-23 16:15
I wrote n/a, because the vanilla version has no ECAM Msg for LDG Lt  at all.

**Comment by Benjozork** [comment] 2020-10-23 17:23
Right. Thanks

**Comment by Benjozork** [comment] 2020-10-23 17:31
Can you try binding a key on your keyboard to that function and tell me if it works ?

**Comment by lve0200** [comment] 2020-10-23 18:27
OK, so here now the full story:
MSF 1.9.5, Master as of 22/10, WinStore, Win 10-latest, Core i5, GTX 1650
EDDF line up 25C, on the ground
LDG Lt ON, ECAM LDG LT ON
HOTAS LDG Lt OFF (No retract) Light OFF, ECAM MSG ON
Ovhd Panel Mouse action Retract, ECAM MSG OFF
HOTAS LDG Lt ON, Lights ON,  LDG Lt OFF, Lights OFF  (multipl), Nothing on ECAM
Ovhd Panel Mouse action Retract, Nothing on ECAM
Keybd LDG Lt ON, Lights ON, Nothing on ECAM

**Comment by Benjozork** [comment] 2020-10-23 20:06
So if I understand correctly, if you bind a key to turning on the landing lights on your keyboard, the same problem is present. Correct ?

**Comment by lve0200** [comment] 2020-10-24 14:28
Right!

**Comment by ntlgr** [comment] 2020-10-30 16:03
The problem is not unique to specific controller model, I can confirm I have the same problem when assigning Landing light toggle to any controller (logitech, CH products). Landing lights turn on, illuminate the runway, but LDG LT does not appear on ECAM,

**Comment by Benjozork** [comment] 2020-10-30 16:10
Sorry I hadn't had the time to look into this, I have a theory but will have to purchase a controller myself

**Comment by lve0200** [comment] 2020-10-30 16:45
Hi, you don't need HW, just map a key; does the same job!

**Comment by ntlgr** [comment] 2020-11-01 19:08
That might have something to do with the fact landing lights switches have three positions (ON, OFF, RETRACT). Testing as below:
1. Lights are off, switch is at RETRACT; Controller button pressed; switches flip from RETRACT straight to ON; ECAM doesn't show LDG LT
2. Lights have been turned on using controller, switch is at ON, no ECAM notification; Controller button pressed; switches flip **from ON straight to RETRACT**
3. Lights have been turned on using mouse click, switch is at ON, ECAM LDG LT; Controller button pressed; switches flip **from ON to OFF (not RETRACT!)**; ECAM notification disappears

**Comment by sidnov** [comment] 2022-02-26 10:34
The toggle issue is caused due to sim bindings, and is expected to be fixed in the next sim updates. LDG LT memo on ECAM though can be seen when using a HOTAS (verified with a recent dev build).

**Closed by sidnov** 2022-02-26 10:34 UTC
Labels: Bug, ECAM, Bug-A32NX, FWS
