### ISSUE TITLE
[BUG] Inaccurate ILS path

### ISSUE THREAD

**Issue by o4oren** [flybywiresim/a32nx#2861] opened 2021-01-03 22:12 UTC
**Mod Version**

{
  "built": "2020-12-30T15:37:41+00:00",
  "ref": "",
  "sha": "",
  "actor": "hotshotp <70779662+hotshotp@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

ILS localizer is inaccurate. For example - ILS for RWY28R in KSFO takes the aircraft to the right of the runway.
I have seen this in other airports as well.

**To Reproduce**

1. Fly and ILS approach to RWY 28R in KSFO
2. Notice the localizer takes you to the right of the runway.

**Expected behavior**

Dead on ILS approach.

**Actual behavior**

**References**

 Localizer takes you to the right of the runway.

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
Yes. See comment and screenshot below.

Discord username (if different from GitHub): o4oren
![Untitled](https://user-images.githubusercontent.com/23486326/103489992-6b899c80-4e21-11eb-9b42-978c20293181.jpg)

**Comment by CnRJay** [comment] 2021-01-04 01:35
Try and remove the A32NX mod and do the exact same ILS landing and see if it still veers off to the right. I have noticed some strange things with the dev version. But not the stable version.

**Comment by o4oren** [comment] 2021-01-04 09:29
Without the mod it is accurate.
I think this is urgent - it made me miss approaches in bad weather, emerging out of the clouds and not in front of the runway.
![Untitled](https://user-images.githubusercontent.com/23486326/103520611-14ff7b00-4e80-11eb-8857-076e8dfee4f7.jpg)

**Comment by angry-bender** [comment] 2021-01-04 14:30
Can confirm this issue, YSCB 32 and YSSY 32L had the issue but not YMML 32

**Comment by angry-bender** [comment] 2021-01-04 15:20
Additionally, it seems to skip waypoints constantly, and go straight onto RWxx
![image](https://user-images.githubusercontent.com/18164137/103550139-5e8bac80-4ef8-11eb-8356-1725971e320a.png)

**Comment by Benjozork** [comment] 2021-01-04 15:23
@angry-bender this issue is already reported in #939 and will be resolved soon.

**Comment by angry-bender** [comment] 2021-01-04 15:24
> @angry-bender this issue is already reported in #939 and will be resolved soon.

Ty, I was looking for that it's hard to find issues with such a huge project 😊.

**Comment by tareksabet** [comment] 2021-01-05 23:41
closing right now. duplicate of #939 

@o4oren Thanks for reporting this issue.

**Comment by o4oren** [comment] 2021-01-05 23:46
> closing right now. duplicate of #939 
> 
> @o4oren Thanks for reporting this issue. 

Are you sure it's a suplicate of that one? It's a different behavior completely.
I am not talking a out following the flight path. The old localize needle is centered while the aircraft is not aligned with the runway. On some airports...
Doesn't seem a duplicate.

**Comment by tareksabet** [comment] 2021-01-05 23:50
> > closing right now. duplicate of #939
> > @o4oren Thanks for reporting this issue.
> 
> @tareksabet
> Are you sure it's a duplicate of that one? It's a different behavior completely.
> I am not talking a out following the flight path. The old localize needle is centered while the aircraft is not aligned with the runway. On some airports...
> Doesn't seem a duplicate.

reopened again the comment of the duplicate was based on another comment my bad.

**Comment by angry-bender** [comment] 2021-01-06 06:38
> 
> 
> > > closing right now. duplicate of #939
> > > @o4oren Thanks for reporting this issue.
> > 
> > 
> > @tareksabet
> > Are you sure it's a duplicate of that one? It's a different behavior completely.
> > I am not talking a out following the flight path. The old localize needle is centred while the aircraft is not aligned with the runway. On some airports...
> > Doesn't seem a duplicate.
> 
> reopened again the comment of the duplicate was based on another comment my bad.

That's my bad. But he is correct, it is a different behaviour. It can be seen replicated here as well https://www.youtube.com/watch?v=0aK_d4VwO8g&t=900s Whilst this is in an old version, I have seen similar behaviour at other airports ignoring the autoland part, and the localiser component. 

It could, however, also be aggravated by an existing MSFS Issue, as I get the same issue, to a lesser degree in other airports. Often, I see the localiser bang on, bu the aircraft is about 2-4 degrees off the runway, requiring a correction before minimums or at worst, a go around.

**Comment by tareksabet** [comment] 2021-01-06 13:01
@angry-bender what I think is that on microsoft side because it's placed by the runway and the placement of it is wrong.
I had that issue before on several airports it's just the misplaced ILS like when I captured the ILS and landing it was putting me very high at the end.

**Comment by o4oren** [comment] 2021-01-06 13:47
> @angry-bender what I think is that on microsoft side because it's placed by the runway and the placement of it is wrong.
> I had that issue before on several airports it's just the misplaced ILS like when I captured the ILS and landing it was putting me very high at the end.

I showed on my first response that the same airport/rwy are good without the fbw mod.

**Comment by DaveBC** [comment] 2021-01-07 03:05
> 
> 
> > @angry-bender what I think is that on microsoft side because it's placed by the runway and the placement of it is wrong.
> > I had that issue before on several airports it's just the misplaced ILS like when I captured the ILS and landing it was putting me very high at the end.
> 
> I showed on my first response that the same airport/rwy are good without the fbw mod.
> Look at my original image - loc centered, runway to the left. This is reproducible with the mod on KSFO RWY28R.
> Then the second image on my first response - without the mod, dead center.

In the original post, you have loaded the **LDA** 28R approach, which is to the right of the runway ([1183' according to the approach plate](https://flightaware.com/resources/airport/SFO/IAP/LDA_DME+RWY+28R/pdf)). The second post you've loaded the ILS 28R approach. Can you try again with the mod and ILS 28R? It worked flawlessly for me.

![Microsoft Flight Simulator Screenshot 2021 01 06 - 22 00 25 44](https://user-images.githubusercontent.com/3708210/103845908-09bc7300-506b-11eb-91bc-8202bebb5c6a.png)

**Comment by Awemeter** [comment] 2021-01-07 05:06
If the runway is placed inaccurate then maybe people with navigraph which has accurate nav data is having issues

**Comment by o4oren** [comment] 2021-01-07 07:11
Again,
I showed the difference with and without fbw on the original report and my first response. 
The only change is removing fbw. This is repeatable. 
Try to reproduce.

**Comment by DaveBC** [comment] 2021-01-07 13:29
> Again,
> I showed the difference with and without fbw on the original report and my first response.
> The only change is removing fbw. This is repeatable.
> Try to reproduce.

Again, the difference between your original post and response is different approaches. Can you get a screenshot of the ILS 28R being off-center with fbw?

![Untitled-1](https://user-images.githubusercontent.com/3708210/103898104-71ea7380-50c2-11eb-84f0-6b518582a791.jpg)

**Comment by ThatRedMelon** [comment] 2021-01-07 13:33
For the LDA 28R approach into KSFO, the LOC course is 1183ft to the right of the runway, but the ILS 28R LOC is correctly aligned. So the original issue report is intended and correct.

**Comment by o4oren** [comment] 2021-01-08 14:09
@DaveBC You're right!
The bug is different. I just retried it. LDA and ILS behave correctly.
The problem is that when selecting the ILS 28R approach on the FMGS the frequency and course selected are those of the LDA approach (110.75/281 and not 111.7/284)...
That may be a problem with the navdata, I presume.
<img width="652" alt="1" src="https://user-images.githubusercontent.com/23486326/104024506-e52bdc80-51cb-11eb-900f-65c4067b42a3.png">
<img width="562" alt="2" src="https://user-images.githubusercontent.com/23486326/104024511-e6f5a000-51cb-11eb-95e8-d26f3f2ef5e7.png">

**Comment by DaveBC** [comment] 2021-01-08 16:56
Same issue in the 787. Either a MSFS or Navigraph issue.

![Microsoft Flight Simulator Screenshot 2021 01 08 - 11 55 49 57](https://user-images.githubusercontent.com/3708210/104042464-8acd5480-51a8-11eb-984d-5fe4c462600d.png)

**Comment by AirbusA320Pro** [comment] 2021-01-10 15:01
The approach to SFO 28R is either a standard ILS (i.e straight in towards the runway) or what's known as a SOIA (Simultaneous Offset Instrument Approach) - the clue being "Offset". When simultaneous approaches are being conducted to 28L and 28R, the approach paths are separated in a shallow triangle shape. 
![SFO 28R LDA Apporach](https://user-images.githubusercontent.com/75289637/104126482-b8ef9780-5354-11eb-9adc-c8a179f22012.jpg)

**Comment by tareksabet** [comment] 2021-01-10 15:06
@o4oren I guess I will close the issue as it's explained in the comment above as it doesn't do anything with our mod.
Thanks fore reporting this issue.

**Closed by tareksabet** 2021-01-10 15:06 UTC
Labels: Bug

**Comment by angry-bender** [comment] 2021-01-11 10:21
@o4oren Just tested with the latest dev version, and latest navigraph data in Flight sim, although the charts have a Heading of 284, the Sim as 285, and it works a treat. 

Check out here to see :-) https://youtu.be/TxGLqwaI2pE 

From the comment above, that looks like for an LDA Approach, but it seems with the latest Dev Version, the ILS Selection is putting in the correct frequency now.

**Comment by o4oren** [comment] 2021-01-11 11:39
Looks great.
I'll give it a try later today

**Comment by angry-bender** [comment] 2021-01-11 11:58
> 
> 
> Looks great.
> I'll give it a try later today

np, any issues feel free to message me on discord angry-bender :-)
