### ISSUE TITLE
PFD ND and ECAM Screens only on when aux power...

### ISSUE THREAD

**Issue by nabil74** [flybywiresim/a32nx#434] opened 2020-09-06 01:00 UTC
**Mod Version**
latest master version (as of 10:30am melbourne AEST)
master 0.2.0

**Describe the bug**
Screens do not turn on after apu power available.
ONly turn on when aux power is used.

**To Reproduce**
Batteries 1 and 2 on.
APU master on
APU start pressed

Once APU is available  tried to turn up brightness up on 
PFD ND AND ECAM SCREENS. They stay black

Turn on avail ext power. screens turn on.

**Expected behavior**
Screens should turn on once apu power is avail. (self test mode).

**Actual behavior**
APU power avail statys does not turn on screens (increasing brightness does not turn screens on)
APU avail should provide power to the aircraft so that ext power is not required.

**References**
]
(url
![pfds etc not on with apu power](https://user-images.githubusercontent.com/70311304/92315926-1e8ee880-f030-11ea-9731-9637ed3b9096.JPG)
)

**Additional context**
Confirming that once engines are up and running
turning off external power
Turning off apu master, 
screens stay on as expected.

**Comment by UncleClapton** [comment] 2020-09-06 10:40
This is a duplicate of #421

**Comment by AdenFlorian** [comment] 2020-09-06 22:13
closing as it is a duplicate

**Closed by AdenFlorian** 2020-09-06 22:13 UTC
Labels: bug
