### ISSUE TITLE
New spoiler animation on landing

### ISSUE THREAD

**Issue by SashaSemenishchev** [flybywiresim/a32nx#6592] opened 2022-01-25 15:37 UTC
### Aircraft Version

Experimental

### Description

When plane lands with spoilers armed their animation are flickering. I think this animation should be more smooth, than now

### Discord Username (optional)

MrFunny#8972

**Comment by aguther** [comment] 2022-01-25 16:55
I agree this is not really nice. I’m yet unsure what the cause is. A part might be from the partial ground spoiler deployment but if you look at the target value that is sent to the sim it’s smooth and not jumping. So no idea why it’s flickering.

At latest it will be fixed when hydraulic system is implemented…

**Closed** 2022-03-12 16:15 UTC
Labels: Request
