### ISSUE TITLE
Flap 2+Flap 3 Config Take Off 

### ISSUE THREAD

**Issue by Frafty** [flybywiresim/a32nx#2701] opened 2020-12-25 09:08 UTC
**Mod Version**
Master Version

**Describe the bug**
Flap Config 2 and Flap Config 3 take offs are causing aural warning when hitting the Take Off config button.

**To Reproduce**
1. Set flaps 2 or flaps 3
2. Click the TO Config Button
3. Enjoy the music

**Expected behavior**

Take Off Config ECAM memo should go green (assuming the a/c meets the rest of TO requirements).

**Actual behavior**

Aural warning sounds, ECAM message (TO Config) turns red.

**References**

**Additional context**

N/A

Was this working before/when did the issue start occurring?
Not sure. First two flights produced the same issue.

Is this a problem in the vanilla unmodded game?

N/A

Discord username (if different from GitHub): @Tones

**Comment by Benjozork** [comment] 2020-12-25 18:04
Please add a title.

**Comment by Frafty** [comment] 2020-12-25 20:30
Done! Sorry, didn't even see this field.

**Comment by MisterChocker** [comment] 2020-12-25 21:26
@Frafty to my knowledge CONF2 works, you have to set the TO CONFIG FLAPS in the TO PERF PAGE, have you done that?
But CONF3 doesn't work afaik.

**Comment by Frafty** [comment] 2020-12-25 21:30
I haven’t done config two, only three as the field I was in required that
flap take off. So I assumed 2 didnt work if 3 didn’t.

**Comment by Rameyuk** [comment] 2020-12-28 10:56
Maybe use flaps 3, set flaps 2 then press T.O Test button, then set flaps 3 without pressing the T.O Test button again?

**Comment by Frafty** [comment] 2020-12-28 17:10
I can give it a test, though I have a hard time imagining that to work.
When I retracted the flaps from the first two instances, I tried hitting
the TO config when I went back to Flaps 2, but no joy.

**Comment by MisterChocker** [comment] 2020-12-31 05:34
duplicate of #1770

**Closed by MisterChocker** 2020-12-31 05:34 UTC
Labels: Bug, Waiting For Response
