### ISSUE TITLE
Issue using 2 frequencies on RMP/ACP with vPilot VATSIM 

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/a32nx#5620] opened 2021-08-11 16:23 UTC
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-11T16:21:54+00:00",
  "ref": "HEAD",
  "sha": "bbb804a8bd43180830fd97b3996ef1df48785fe8",
  "actor": "David Walschots <davidwalschots@users.noreply.github.com>",
  "event_name": "manual"
}
```

### Describe the bug

After reports in #support I tested this.

Using a second frequency only works when VHF1! is tuned, VHF2 is tuned and __both__ VHF2 and VHF3 receiver knobs are enabled (illuminatiing white)

Also: 
* VHF1 does not illuminate - not sure if this is normal on captain side. 
* Volume knobs have no effect - can be turned but no effect on volume

![2021-08-11_17h58_54](https://user-images.githubusercontent.com/16833201/129064436-3ba65068-d497-4220-85b9-c7985635396f.png)
 

### Expected behavior

Realistic implementation compared to real aircraft to be able to use RMP/ACP as described in the FCOM. 

### Steps to reproduce

1. Go to airport with at least two VATSIM ATC stations manned
2. Activate vPilot (maybe Observer)
3. Tune VHF1 to first ATC station and make sure you hear chatter
4. Tune VHF2 to second ATC station and enable VHF2 and VHF3 receiver knobs - vPilot should now show COM2 RX in white and you should be able to hear chatter
5. Try deactivating VHF2 receipt knob - COM2 not white any longer, no chatter
6. Try deactivating VHF3 receipt knob and reactivate VHF2 receipt again - COM2 still not white any longer, no chatter
7. Activate VHF2 and VHF3 again - vPilot should now show COM2 RX in white and you should be able to hear chatter

### References (optional)

![2021-08-11_18h14_11](https://user-images.githubusercontent.com/16833201/129065304-11c47e8c-7377-4e5d-a526-c9ff0b10daf4.png)
![2021-08-11_18h13_54](https://user-images.githubusercontent.com/16833201/129065317-dff4a0cd-54b0-4aa2-ba7b-d6a732057bfb.png)
![2021-08-11_18h14_03](https://user-images.githubusercontent.com/16833201/129065333-888edcc2-cb7f-476d-93c0-2f074d4231a2.png)
![2021-08-11_18h14_18](https://user-images.githubusercontent.com/16833201/129065346-31d1b295-db80-4117-a2fd-7defde77af98.png)

### Discord Username (optional)

Cdr_Maverick#6475

**Comment by frankkopp** [comment] 2021-11-29 13:59
Might be related or similar to https://github.com/flybywiresim/a32nx/issues/3854

**Comment by sidnov** [comment] 2022-03-08 11:09
It is indeed a duplicate of #3854

Quoting from there, 
```It's a vPilot bug. They need COM RECEIVE:ALL enabled to receive on both VHF1&2 to support older sims like FSX. On the A32NX, we have coded it as it would be on the real aircraft, thus COM RECEIVE:ALL is only set to true when all VHF channels (1,2,3) are set to receive.```

I don't think we should change anything on our end (correct implementation) to support a legacy version of the same (vPilot)

**Closed by sidnov** 2022-03-08 11:09 UTC
Labels: Bug, RMP
